spacetelescope/jwst

- jwst/ipc/ipc_corr.py
- jwst/ipc/ipc_step.py
@nden Please review these changes.  Thanks.
> import datamodels from ..; models changed to datamodels

- jwst/background/background_step.py
- jwst/background/background_sub.py
- jwst/background/subtract_images.py
- jwst/background/subtract_images_step.py
> Updated imports and use of datamodels

- jwst/coron/hlsp.py
- jwst/coron/hlsp_step.py
- jwst/coron/klip.py
- jwst/coron/klip_step.py
- jwst/coron/stack_refs.py
- jwst/coron/stack_refs_step.py
> change import statements in coron

- jwst/datamodels/__init__.py
- jwst/datamodels/model_base.py
This is a pretty trivial change that I made to make sure that I understood the new workflow for jwst.
> Change model -> DataModel in some exceptions and comments

- jwst/stpipe/crds_client.py
- jwst/stpipe/linear_pipeline.py
- jwst/stpipe/pipeline.py
- jwst/stpipe/step.py
- jwst/stpipe/subproc.py
- jwst/stpipe/tests/steps/__init__.py
- jwst/stpipe/tests/steps/local.py
- jwst/stpipe/tests/test_crds.py
- jwst/stpipe/tests/test_pipeline.py
- jwst/stpipe/tests/test_step.py
I updated two modules in stpipe from references to jwst_lib.models to jwst.datamodels.   The changes involved comments and a log message.
Based on feedback from Howard,  I also changed all the existing datamodels imports from absolute to relative.
> Updated references to datamodels in stpipe,  comments.

- jwst/pipeline/calwebb_spec2.py
I updated the 3 occurrences of exp_type 'NRS_MSA' to 'NRS_MSASPEC'.
@nden
> Fixed calwebb_spec2 to use correct exptype for NIRSpec MSA

- .travis.yml
- README.md
- setup.cfg
For OSX and Linux this config does the following... 
1. Checks the package installation
2. Runs unit tests
3. Reports pep8 code violations
I had to tell pep8 to report only the first occurrence of an issue, because there are >13,000 and travis limits output to 10,000 lines.
I've tested this travis configuration extensively on my fork and I believe it's good to go. The only errors I'm seeing are "real ones". :smile:
> Initial travis-ci integration

- setup.py
Travis is running `python setup.py test` to start its testing. This change tells setuptools to use `pytest` rather than the default, `unittest`.
Misc: fixed whitespace
> Add pytest hook for setuptools

- jwst/stpipe/tests/steps/__init__.py
- jwst/stpipe/tests/steps/python_pipeline.cfg
- jwst/stpipe/tests/steps/some_other_step.cfg
- jwst/stpipe/tests/test_crds.py
- jwst/stpipe/tests/test_pipeline.py
- jwst/stpipe/tests/test_step.py
- The depth of the `stpipe` testing sub-package could not resolve `from .. import datamodels`
- Discovered a few more `jwst_` references
> Fix relative imports in stpipe

- MANIFEST.in
- setup.py
These filetypes were omitted from the initial port.
EDIT:
Oh good -- travis is working 👍
> Include CSV files

- jwst/datamodels/tests/test_fits.py
- jwst/stpipe/tests/steps/python_pipeline.cfg
With regards to jwst/datamodels/test/test_fits.py, the CORONMSK keyword is now defined in the core schema and hence no longer appears in the extra_fits portion of the data model (it's part of the main meta attribute). So a new keyword ('SCIYSTRT') was chosen to replace it in this test, because it is not part of the core schema and hence appears in the extra_fits attribute of the data model.
The stpipe test was failing because the datamodels package is now able to handle different file formats (fits and asdf) and hence it needs to know what type of file is desired when specifying an output file name.
> Fixed a couple tests

- jwst/pipeline/__init__.py
- jwst/pipeline/calwebb_image2.cfg
- jwst/pipeline/calwebb_image2.py
- jwst/pipeline/calwebb_sloper_b7.cfg
- jwst/pipeline/calwebb_sloper_b7.py
As documented in Trac #336 ([https://aeon.stsci.edu/ssb/trac/jwst/ticket/336]) the calwebb_sloper pipeline needed to be updated for Build 7, in order to use a different processing order for MIRI data, as well as to move the persistence correction step from calwebb_image2 to calwebb_sloper. So that on-going use of the existing calwebb_sloper pipeline is not disrupted, I've created a new version of it for Build 7, with class name "SloperPipelineB7" and config file "calwebb_sloper_b7.cfg." Before B7 is delivered, this new version of calwebb_sloper will be renamed to take the place of the existing version.
The calwebb_image2 pipeline module has also been updated, to remove the persistence step (moving to calwebb_sloper), and the not-yet-implemented emission step. The emission step will be …
> Updated calwebb_sloper and calwebb_image2

- jwst/pipeline/calwebb_sloper_b7.py
As documented in #90 the persistence correction step needs to be between linearity and dark for NIR exposures, and following dark and refpix for MIRI exposures.
> Updated calwebb_sloper for new location of persistence step

- jwst/datamodels/__init__.py
- jwst/datamodels/photom.py
- jwst/datamodels/schemas/nirspecfs_photom.schema.yaml
- jwst/photom/photom.py
- jwst/photom/photom_step.py
The NIRSpec IDT delivered their first complete set of flux calibration (photom) reference files in their pre-CDP3 package a couple months ago (the real CDP3 is expected "any day now"). All of these reference files use a one-dimensional vector of flux cal conversion factors that are a function of wavelength. The current ref files are dummies, in that all of the conversion factors are set to 1.
The ref files for the MOS and IFU modes are relatively easily accommodated in the existing photom reference file scheme, with the only slight modification being the addition of uncertainty/error/variance values for the wavelength-dependent correction factors. Ref data for both of these modes are dependent only on the combination of filter+grating in use for an exposure. Thus the existing …
> Photom updates for new NIRSpec flux cal

- .gitignore
- .travis.yml
- docs/mkdocs.sh
Building the documentation via travis takes roughly 5 minutes. This is not used for throwing docs into production. Instead this acts as an early warning system to detect whether your production doc builds will succeed.
> Sphinx integration

- jwst/transforms/models.py
- jwst/transforms/tags/jwst_models.py
Nadia and I were discussing the wcs code and found it failed in a couple of places due to running it in Python 3. First, the dictionary.keys() is now a generator but the code was expecting a list, so added list() around it.  Second, to iterate over a dictionary we need to use dictionary.items() for python 3.
I went through the code in jwst/transforms and jwst/assign_wcs and did not see any other obvious python 3 issues:
- except Exception e:" instead of "except Exception as e", but none found
- print 'here' instead of print('here'), but none found
- integer division, but in all cases the numerator or denominator were float so this should be fine
- str vs byte and encoding, does not seem to affect these packages
- dictionary.iteritems() -> dictionary.items(), two places
- dictionary.keys() …
> wcs python 3 tweaks

- docs/fits_generator/sphinxext/templates.py
Only one change was needed: replace cStringIO with the six version that hides
the difference between Python 2 and 3.
> Update sphinxext for Python 3 compatibility

- jwst/datamodels/properties.py
The __eq__ method, as written, can invoke itself through the line "return self == other", leading to infinite recursion. Although there is a guard against this, it does not always catch this case. I rewrote the code to be simpler and never invoke the == operator on itself.
> Rewrite __eq__ method in ObjectNode to avoid infinite recursion

- jwst/transforms/models.py
Restore `Dircos2Unitless.inverse` which was unintentionally deleted in #69.
> restore inverse

- jwst/assign_wcs/nirspec.py
This reverts the last change in subversion before moving to git. Also it was the last change before packaging B6 which unfortunately broke the IFU mode. It is confirmed now that all B6 nirspec modes work.
> revert svn r4266

- jwst/extract_2d/extract_2d.py
- jwst/flatfield/flat_field.py
- jwst/ipc/ipc_corr.py
- jwst/saturation/saturation.py
Change the default log level in several pipeline step modules from INFO to DEBUG, so that DEBUG level messages will be passed when requested. If set to INFO in the module, no messages at a level lower than INFO will be passed even when explicitly requested by the user.
> Set default log level to DEBUG

- jwst/rscd/rscd_step.py
- jwst/rscd/rscd_sub.py
Updated the get_rscd_parameters function in the RSCD step to check that it found a matching entry in the reference table before blindly trying to apply the correction. If a match is not found, a warning is issued and the step is skipped (output is returned as an unchanged copy of the input). The step completion status is set appropriately.
Also some PEP8 clean-up.
> RSCD check for ref table match

- jwst/persistence/persistence_step.py
The persistence step used to be part of level-2b processing, so the lower level routines were setup to open and work with things like Image, Cube, and MultiSlit data models, which was causing some sort of problem now that the step is part of level-2a processing, where we're always working with Ramp models. So I updated the top-level step module to just immediately return a copy of the input model and set the step status to skipped (until the persistence step gets fully implemented later during Build 7 development).
> Make persistence step skip cleanly for now

- jwst/datamodels/__init__.py
- jwst/datamodels/quad.py
- jwst/datamodels/schemas/quad.schema.yaml
- jwst/datamodels/tests/test_models.py
Level-3 coronagraphic processing requires the use of a data model that is 4-dimensional, but unlike the existing 4D RampModel, only has standard SCI, DQ, ERR arrays as attributes.
In addition to adding the new QuadModel, I updated the portion of the datamodels __init__ that tries to figure out the type of data model to return when calling the generic datamodels.open. The additional logic is intended to distinguish a simple 4D QuadModel from the more complicated 4D RampModel (or MiriRampModel), which have additional specialized data arrays, like GROUPDQ and REFOUT.
> New 4D QuadModel data model

- jwst/datamodels/__init__.py
Initial logic to test for RampModel vs. QuadModel was flawed. Raw (_uncal.fits) RampModel products only contain a SCI extension, with no accompanying ERR, GROUPDQ, or PIXELDQ arrays. Hence a test for the presence of GROUPDQ will always fail for a raw product, causing it to assume it's a QuadModel. As of now, QuadModels are always used for more advanced stages of products, which means they'll always contain populated ERR and DQ arrays (even if they're just zero-filled), so changed the test to look for DQ.
This was causing many of the regression tests to fail, at least the ones that use _uncal.fits products as input.
Really need to come up with a way for input products to identify the type of data model that they are in order to avoid having to make guesses like this.
> Fix logic in datamodels init for QuadModel

- jwst/coron/stack_refs.py
- jwst/coron/stack_refs_step.py
As part of the on-ongoing development of the calwebb_coron3 pipeline, the stack ref psfs step had to be updated to accommodate a new form of input and the ability to work over all integrations within an exposure. The previous version of the step read the ASN table to find the list of input psf exposure names. The upper-level pipeline module now handles this and sends a ModelContainer as input to this step. So now all the step needs to do is actually stack the data in the input models. Furthermore, the operation of copying the input data to an output cube was updated to copy all of the multiple integrations that will be in the input model exposures. Previously the step had assumed the input would contain a single image (ImageModel). Now they are CubeModels that in turn get stacked into an …
> Update coron StackRefs step inputs

- jwst/coron/align_refs_step.py
- jwst/coron/imageregistration.py
- jwst/coron/klip_step.py
- jwst/coron/stack_refs.py
- jwst/pipeline/calwebb_coron3.py
Made several updates and bug fixes to get the baseline version of calwebb_coron3 running. The basic pipeline structure and data flow now work end-to-end. A few updates are still needed to some of the individual steps, such as adding the capability in align_refs to store the computed image shifts somewhere, and adding a switch to outlier_detection to tell it to do its work in native detector space, rather than resampling and blotting all the images back and forth.
> First round of updates to CALCORON3

- jwst/datamodels/schemas/core.schema.yaml
Added step status and reference file keywords for the new calwebb_coron3 steps stack_refs, align_refs, and klip. Align_refs is the only step that uses a CRDS reference file, which is a PSF mask reference file.
> Add keywords for new CORON3 steps

- jwst/ami/ami_analyze_step.py
- jwst/pipeline/__init__.py
- jwst/pipeline/calwebb_ami3.cfg
- jwst/pipeline/calwebb_ami3.py
Renamed the calniriss_ami3 pipeline to be calwebb_ami3. Restructured the calwebb_ami3 pipeline module to mimic the calwebb_coron3 pipeline, including a restructuring of the assumed layout of the input ASN table, so that it too more closely mimics ASN tables for coronagraphic associations.
It would be good in the future to change the ami_average routine to use a ModelContainer set of models as input, rather than a list of file names that it has to load into models, just as is now done with some of the coronagraphic pipeline steps. But the current form still works as required.
> Reworked AMI3 pipeline

- jwst/cal_ver_steps.py
- scripts/get_cal_vers
This PR adds a new module to report on the versions for all calibration pipeline steps, as well as a new script to enable a command-line interface for generating the version report as a JSON file.  The module has been added to the top level of the JWST package to allow it to inspect all sub-packages for any class that ends in 'Step'.  These versions of the file have already been found to be PEP8 compliant (by checking them with 'pep8' task).
> Add version check

- jwst/datamodels/schemas/core.schema.yaml
The folks in SDP are getting warnings when loading level-1b products, because a few of our keyword definitions in the core schema are out of date with their definitions and therefore how they're writing them in the level-1b products.
In particular:
CONT_ID: needs to be integer type
CORONMSK: change the entry 'NULL' in the enum list to 'NONE'
NUMDTHPT: needs to be string type (I know, it's crazy)
S_REGION: needs to be string type
> Update keywords to match KWD

- jwst/cal_ver_steps.py
Fixes the following build error under Python 2.7.
```
File "[...]/jwst/cal_ver_steps.py", line 80
print(e, file=sys.stderr)
^
SyntaxError: invalid syntax
```
> cal_ver_steps: Use print function under python 2.x; Fix whitespace

- jwst/assign_wcs/tests/test_nirspec.py
- jwst/datamodels/schemas/core.schema.yaml
Changes and additions to the core schema to keep in sync with DMS.
Two keywords will be added to the primary header:
MSACONFL - (string) stores the name of the configuration file with open shutter information 
MSAMETID - (number) identifier for the row in the metadata file which is relevant for this exposure.
Another keyword (MSACONID) is not going to be used by the pipeline code so it's not being added to the schema.
> Add MSA configuration keywords to schema

- jwst/pipeline/calwebb_ami3.cfg
- jwst/pipeline/calwebb_ami3.py
- jwst/pipeline/calwebb_coron3.py
Updated the calwebb_coron3 and calwebb_ami3 pipelines to do <product_type> substitutions from the ASN prod name specification when creating output file names.
> Updates to coron and ami pipeline output files

- jwst/assign_wcs/nirspec.py
- jwst/assign_wcs/tests/test_nirspec.py
My best guess of how this should be done.
NRS2 is still way off, looks like it's x/y flipped.
Also this reverts the change of units from meters to microns for the IFU as it broke the IFU pipeline. Currently output wavelengths are still reported in meters.
> improve domain calculation

- jwst/datamodels/model_base.py
The resolver maps uri's contained in references in a schema to filenames. The default list of mappings is hard coded. However one can create different mappings by creating a Resolver object. Previously there was no way to use an alternate resolver when creating a datamodel. This change adds resolver as an optional parameter to __init__. This allows the programmer to provide an alternate resolver and reference schema files in directories other than the defaults.
> Add resolver as an optional parameter when creating a new datamodel

- jwst/datamodels/tests/test_storage.py
- jwst/datamodels/util.py
While the bintable code makes some attempt to make column access independent of the column name case, the code is layered on numpy records, where access is case dependent. In practice, you must supply column names in the correct case. The function gentle_asarray coerces the type of data read from a model into the type given in the schema. However, in the case of numpy records, the field name is a part of the datatype. This leads to erroneious results if the case of the column name mentioned in the schema disagress with the case of the name in the binary table. The fix replaces the column names read from the schema with the column names from binary table.
> Retrieve bintable column names from table instead of datamodels schema

- jwst/datamodels/schemas/core.schema.yaml
- jwst/datamodels/schemas/multislit.schema.yaml
Updated labels for the proper motion related keywords in the core schema. Added keywords to the mutlislit schema for storing source info from the NIRSpec MSA configuration file for each extracted slitlet. Will be needed for #212.
> Keyword schema updates

- jwst/datamodels/schemas/core.schema.yaml
Changed the core schema entry for the NIRSpec GWA tilt sensor temperature from a FITS keyword name of GWA_TILT to GWA_TTIL. Fixes #82.
> Schema update for #82

- jwst/assign_wcs/nirspec.py
- jwst/assign_wcs/tests/test_nirspec.py
- jwst/assign_wcs/tools/nirspec/compute_world_coordinates.py
- jwst/extract_2d/extract_2d.py
The NIRSpec model goes to SCA coordinates. This PR adds another frame called "sca". The name "detector" frame now refers to the DMS coordinates. The Transform from DMS to SCA coordinates was added to the pipelines. 
In addition, passing a wavelength_range to `nirspec.nrs_wcs_set_input` is now optional, it retrieves the default range from the model.
This includes the corresponding changes in extract_2d.
> added dms2sca

- jwst/datamodels/__init__.py
- jwst/datamodels/properties.py
- jwst/datamodels/util.py
Three potential problems were found and fixed. None should happen with
corectly formatted images.
The first change was to datamodels/__init__.py. There is a test on the
dimesnions of the image in open in order to determine the right class
to use. The change uses an explicit extension version in case there is
more than one SCI extension in an image.
The second change is to _cast in datamodels/properties.py. If the
object to be cast is a NDArrayType, then it is lazy and must first be
instantiated with a call to _make_array before calling gentle_asarray.
The third change is to gentle_asarray in datamodels/util.py. The new
code traps any error when calling numpy.asarray on an object that is
not a numpy.ndarray and reports the object as having a bad type.
> Fix problems uncovered by badly formed test image

- jwst/pipeline/calwebb_ami3.py
- jwst/pipeline/calwebb_coron3.py
- jwst/pipeline/calwebb_image3.py
Updated calwebb_coron3 and calwebb_ami3 pipeline modules to use new way of building output product file names from the product name specified in the ASN table. This method assumes the ASN product name is a "bare" root name and needs to have the appropriate product type suffix and extension appended to it.
Still need to update calwebb_image3 to incorporate similar changes.
> Updates to level-3 pipelines for change in ASN product names

- jwst/dark_current/dark_sub.py
Added statements to set the cal_step status to SKIPPED when the dark ref data can't be applied.
> Set dark_current cal_step to SKIPPED when not applied

- jwst/datamodels/tests/test_storage.py
- jwst/datamodels/util.py
Function gentle_asarray coerces datatypes to match the type specified
in the schema. This can lead to a mismatch with the column names in
the table. Something has to give and previously I overrode the schema
column names with the fits record column names. This caused
regressions in the overnight tests. This fix flips the coercion and
updates the fits record column names to match the schema column
names. I hadn't done this before because I though the change was more
difficult.
> Adjust fits record names to match schema

- jwst/datamodels/schemas/core.schema.yaml
MIRI MRS and all NIRSpec modes (possibly others) will use these keywords to transform from V2,V3 to sky.
> Add WCS keywords to  core schema

- jwst/background/subtract_images_step.py
- jwst/datamodels/__init__.py
- jwst/extract_1d/extract_1d_step.py
- jwst/flatfield/flat_field_step.py
- jwst/photom/photom_step.py
The recent change to the datamodels __init__ function, to handle input FITS files that have more than one SCI extension, broke the functionality that had been relied on for detecting that an input dataset is a MultiSlitModel. In the past, a FITS file with more than one SCI extension would throw an error, in which case the model was returned as a plain DataModel. That was used in some cal steps to detect the presence of a MultiSlitModel. After the recent update, files with more than one SCI extension no longer trigger an error, so MultiSlit files were being loaded into an ImageModel, because they are 2-dimensional. This causes all kinds of havoc with the multiple sets of SCI, ERR, DQ extensions not getting passed along in the data model.
So I updated the datamodels __init__ to check for …
> Fix handling of MultiSlitModels

- jwst/datamodels/model_base.py
I am about to deliver a change to asdf which will improve the way that
date tagging is handled. The result of the change is that complex
formats, such as dates, are stored as tagged strings. This is not a
problem, and in fact is an improvement, as that is the format that
both fits and serialized asdf want to see. However, the current
version of asdf stores dates as dates and model_base.py contains a
patch to work around the problem it causes. Because asdf and datamodel
are separatepackages I needed to add some code so that it will work
with both the old and about to be delivered version of asdf, basically
just an if statement.
> Work around for asdf code change

- jwst/associations/association.py
- jwst/associations/generate.py
- jwst/associations/lib/asn_schema_jw_level3.json
- jwst/associations/lib/rules_level2b.py
- jwst/associations/lib/rules_level3_base.py
- jwst/associations/main.py
- jwst/associations/registry.py
- jwst/associations/tests/data/test_image_asn.json
- jwst/associations/tests/test_asn_names.py
- jwst/associations/tests/test_level3_basics.py
- jwst/associations/tests/test_level3_product_names.py
- jwst/associations/tests/test_main.py
- jwst/associations/tests/test_validate.py
- jwst/cube_build/cube_build.py
- jwst/datamodels/container.py
- jwst/pipeline/calniriss_ami3.py
- jwst/pipeline/calwebb_spec2.py
@hbushouse @jemorrison Though target from the associations does not appear to be used anyplace, it is referred to in cube_build and datamodels/container. Review as needed.
Resolves #152
> Replace targname with more generic target

- jwst/datamodels/util.py
Because of a logic error in the gentle_asarray code it is possible to traverse the code without generating an output array and thus return an undefined value. This fix adds an else branch that calls numpy.asanyarray if none of the other branches are executed.
> Add missing else branch to gentle_asarray

- .travis.yml
- jwst/wfs_combine/wfs_combine.py
- jwst/wfs_combine/wfs_combine_step.py
Updated the wfs_combine step to pay attention to the user-supplied output_dir, if there is one, when creating an output file name. Also updates the construction of the output file name to take into account the recent change to ASN product file names that no longer include the product type suffix, so the step needs to add the appropriate suffix (which in this case is 'wfscmb').
With similar recent updates to the calwebb_image3, calwebb_coron3, and calwebb_ami3 pipelines, all level-3 pipelines/steps should now be paying attention to the user-supplied output_dir value, which fixes #162.
> Update wfs_combine to use output_dir

- jwst/datamodels/extension.py
- jwst/datamodels/model_base.py
Up to now there has been no way for other packages to refer to the
schemas in the datamodels package. The miri team requested that the
url http://jwst.stsc.edu/schemas be added, so their schemas could have
references to the datamodels schemas. This commit adds the new class
BaseExtension in datamodels/extension.py and modifies the list of
default extensions, jwst_extensions, in datamodels/model_base.py to
include it.
> Add url mapping for datamodels schemas

- jwst/datamodels/__init__.py
- jwst/datamodels/container.py
- jwst/datamodels/util.py
ModelContainer now opens any type of DataModel that can be handled by `datamodels.open()`.  datamodels.open() code has been relocated from `__init__.py` to `utils.py` to support this.  Finally, any keyword arguments that DataModel takes can now be passed through `datamodels.open()`.  This is useful for the `pass_invalid_values=True` keyword to disable strict schema checking.
> Model container asn open generalize

- jwst/assign_wcs/nirspec.py
- jwst/assign_wcs/tests/test_nirspec.py
- jwst/assign_wcs/tools/nirspec/compute_world_coordinates.py
- jwst/extract_2d/extract_2d.py
I went through the entire NIRSpec WCS pipeline in assign_wcs, slit extraction in extract_2d and wavelength assignment in compute_world_coordinates and checked that +/- 1 pixels exist at the correct places (0- vs 1- based coordinates). Also made sure that `domain` and `subarray.x(y)start` are used consistently within these modules. My testing shows that full frame coordinates are shifted by 1 pixel in x and y directions compared to IDT results. 
`SLITSTR` keywords are 0-base din IDT data (as far as I can tell) but I am not sure this is the difference.
> Nirspec full frame

- jwst/datamodels/model_base.py
The DataModel class implements a copy method and the __copy__ and
__deepcopy__ methods are alaised to it. These two methods are called
by the copy module and the copy.deepcopy method requries that
__deepcopy__ takes a memo argument. When copy.deepcopy is called on a
DataModel object, it fails because of the missing argument. The fix
adds a keyword argument, memo=None, to the copy method and passes that
argument to the invocation of copy.deepcopy that it contains.
> Correct argument list for copy

- jwst/assign_wcs/fgs.py
- jwst/assign_wcs/miri.py
- jwst/assign_wcs/nircam.py
- jwst/assign_wcs/niriss.py
- jwst/assign_wcs/nirspec.py
- jwst/assign_wcs/pointing.py
This code is to be used by steps which resample the data and create a FITS standard WCS keywords. It is assumed that `model.meta.wcsinfo` has been populated with the correct values. The code cretaes a WCS object from these values.
```
from ..assign_wcs import pointing
wcsobj = pointing.create_fitswcs(output_model)
output_model.meta.wcs = wcsobj
```
Need to write tests.
> WCS for resampled data

- jwst/photom/photom.py
Updated the nirspec branch of the photom step to properly handle MSA exposures, which need to be treated the same as IFU (not like fixed-slit). Only loop over individual slits and attach slit-specific flux cal data for fixed-slit mode. IFU and MSA get just one set of flux cal data added.
Fixes #302.
> Update photom to handle NIRSpec MSA properly

- jwst/datamodels/util.py
An error message used the format method but misspelled it fornat. It
went undetected because in Python such mistakes are only caught at
runtime and error branches are not often tested or invoked. The fix
spells the method correctly.
> Rename fornat to format

- .travis.yml
I am seeing this error in travis:
```
Error: HTTPError: 404 Client Error: Not Found for url: https://repo.continuum.io/pkgs/free/osx-64/pillow-3.4.1-py35_0.tar.bz2: https://repo.continuum.io/pkgs/free/osx-64/pillow-3.4.1-py35_0.tar.bz2
```
qt is not needed any more as the plotting code was removed. Hopefully this will fix the builds.
> remove qt from build

- jwst/ramp_fitting/ramp_fit_step.py
I keep getting an error on both my Linux and Mac systems from one line in the ramp_fit_step specification for the save_opt argument. The configobj parser seems to be choking on the fact that there's something included in parentheses within the in-line comment in the argument definition. It's as if it tries to interpret anything and everything contained within parens as part of the argument definition, despite the fact that it's part of the in-line comment (i.e. after the # character). When I remove the parens, it's fine.
The mystery is that this error does not seem to be occurring on other systems, such as jwcalibdev that runs all the daily reg tests, nor have I heard anyone else complain of this problem. So I could understand it (sort of) if it only occurred on one of my systems, which I …
> Fix to ramp_fit_step argument spec

- jwst/assign_wcs/fgs.py
- jwst/assign_wcs/miri.py
- jwst/assign_wcs/nircam.py
- jwst/assign_wcs/niriss.py
- jwst/assign_wcs/nirspec.py
Since different instrument were coded at different times the coordinate frames got different names. This intends to name them consistently as much as possibly.
The output frame is called `world`, the V2,V3 frame is called `v2v3` and the input frame is `detector`.
> name frames consistently

- jwst/datamodels/schemas/core.schema.yaml
- jwst/srctype/__init__.py
- jwst/srctype/srctype.py
- jwst/srctype/srctype_step.py
- jwst/steps.py
Initial version of new step called SourceType, which does the work of the "Point vs Extended Decision" step outlined in the JCCWG calspec3 baseline pipeline (https://confluence.stsci.edu/display/JWSTCC/Vanilla+Point+vs+Extended+Decision).
This initial version so far only works with spectroscopic exposure types that observe a single source (MIRI LRS & MRS, NIRSpec IFU, NIRISS SOSS), in which case the user had a chance to specify a source type in the APT. If the user did so, that choice will be stored in the header keyword "SRCTYPE". If the user did not specify a source type or they selected "UNKNOWN", this routine will reset SRCTYPE to either POINT or EXTENDED based on default rules for each exposure type established by the JCCWG.
This still needs to be expanded to also work on NIRSpec MSA …
> Initial version of new source-type step

- jwst/exp_to_source/exp_to_source.py
- jwst/exp_to_source/tests/test_exp_to_source.py
exp_to_source() produces a dictionary of MultiSlitModels keyed off their slit names, with each MultiSlitModel containing the exposures for that slit.  multislit_to_container() now does the same, only instead of putting them in MultiSlitModels, it puts them in ModelContainers holding ImageModels.
The interface is easy to use as you can pass it ModelContainer object that was created from an association.
```
c = datamodels.open('lots_of_multislit_exposures_asn.json')
d = exp_to_source.multislit_to_container(c)
```
And now the source-based containers can be accessed by slit name:
`d['S200A1']`
@stsci-hack
> multislits to model container

- jwst/photom/photom.py
Modified the photom_io function to only copy the first nelem valid elements of the wavelength and response arrays loaded from the photom table to the RELSENS table stored in the science product. That way the arrays in the science product don't have zero padding at the ends.
> Photom update for writing RELSENS

- jwst/datamodels/model_base.py
The update method has never been properly tested with a data structure that mixes dictionaries and lists until now, when it was asked to update from an association. Several errors were found, which are addressed in this commit, caused by the differences between dictionaries and lists.
> Fix DataModel update method to properly handle embeded lists

- jwst/datamodels/container.py
- jwst/datamodels/fits_support.py
- jwst/datamodels/model_base.py
Binary tables are stored in memory as a type derived from numpy arrays. One has to be careful when copying them to use asanyarray instead of asarray so the`copy has the same type and does not lose the methods and fields of the base type. In this case, the _coldefs attribute, which contains the attributes of a column, was lost, making it impossible to update a column's attributes with the datamodels code.
> Change asarray to asanyarray in _fits_array_writer

- jwst/datamodels/container.py
- jwst/datamodels/model_base.py
The purpose of the flatten method is to iterate over models in a container. The flatten method allows for nested containers, that is, containers holding containers as well as models. The save method on containers was modified to call flatten.
> Add flatten method to models and containers

- jwst/datamodels/schemas/niriss_photom.schema.yaml
Updated the NIRISS photom data model schema to include a new table column for the spectral order number. In partial fulfillment of #339. This completes the necessary updates to the reference file data model. Still have to make updates to the photom step to handle multiple orders of flux conversion data.
> NIRISS photom data model update

- jwst/datamodels/dynamicdq.py
- jwst/datamodels/util.py
For the proper operation of the pipeline, messages should be sent to the logger instead of stdout, which is where print sends them. Three print statements were converted to calls to the python logger.
> Comvert print statements to calls to logger

- jwst/photom/photom.py
Updates to the photom step to use the new version of the NIRISS photom reference table that includes a spectral order value. It is setup to handle two different cases:
1) The multiple spectral orders have NOT been cutout using extract_2d and hence the input is still a simple ImageModel, which contains data for all the orders. For this case, it currently defaults to only loading the flux cal data for order 1.
2) The spectral orders have been separated using extract_2d and hence in the input is a MultiSlitModel. For this case, it loops over all slits and loads the flux cal data corresponding to the order number of each slit. For now it assumes that slit number is equal to order number. This needs to be upgraded in the future to use a meta data value (header keyword) that gives the order …
> Photom updates for NIRISS spectral orders

- jwst/datamodels/container.py
This update to ModelContainer allows the complete association dictionary to be pulled into meta.asn_table upon initialization, so now the container will have available all attributes that are in the input association table.  So for instance, to get the EXPTYPE values, in model container c:
```
In [5]: for m in c.meta.asn_table.products[0].members:
...:     print(m.exptype)
...:     
SCIENCE
SCIENCE
```
@stsci-hack
> generalize import of asn table data into meta.asn_table

- jwst/datamodels/schemas/multislit.schema.yaml
Added entries to the MultiSlit data model schema for 3 new keywords that will be populated for each extracted slit: SRCTYPE (point vs. extended), SRCXPOS (source x position in slit), and SRCYPOS (source y position in slit). SRCTYPE will be populated by the source_type step, while SRCXPOS and SRCYPOS will be populated by the extract_2d step (from data in the MSA config file).
> Additional MultiSlit keyword entries

- jwst/associations/lib/rules_level3_base.py
A value of CLEAR for any attribute was being counted as
a "not set/invalid" value. Fixed
> Fix mis-application of CLEAR being equated to NOT SET

- jwst/associations/lib/rules_level3.py
This check had been removed from other rules; missed this one.
It may come back, but not specifications have been received
concerning this.
> Remove unneeded PATTTYPE check on MIR_LRS-FIXEDSLIT

- jwst/assign_wcs/assign_wcs.py
- jwst/assign_wcs/assign_wcs_step.py
- jwst/assign_wcs/nirspec.py
- jwst/assign_wcs/tests/test_nirspec.py
- jwst/extract_2d/extract_2d.py
- jwst/transforms/models.py
- jwst/transforms/schemas/gwa_to_slit-0.1.0.yaml
- jwst/transforms/schemas/slit_to_msa-0.1.0.yaml
- jwst/transforms/tags/jwst_models.py
- jwst/transforms/tags/tests/test_models.py
Nirspec MSA WCS with new configuration file.
Also the code was refactored so that the same code base is used for the ifu and fs mode.
The only interface difference is the way to get a WCS object for a specific slit now takes only the name of the slit, e.g. 
```
nirspec.nrs_wcs_set_input(input_model, 'S200A1') # fixed slits
nirspec.nrs_wcs_set_input(input_model, 0) # ifu slice number
nirspec.nrs_wcs_set_input(input_model, 58) # msa slitlet id
```
> Nirspec msa conf

- jwst/datamodels/schemas/core.schema.yaml
Added core schema entries for the 3 new NIRSpec flat-field reference file types R_DFLAT, R_FFLAT, and R_SFLAT, which are used for storing the names of the ref files used during processing.
> Add NIRSpec flat ref file keywords to core schema

- jwst/assign_wcs/miri.py
In discussion with @nden , originally it was thought the miri.py file had an issue with the order of V2/V3 that was being calculated.  After some looking it was found that the distortion file used as an input into this routine was the one that was outputting V3/V2 (rather than V2/V3).  This was corrected in PR https://github.com/spacetelescope/jwreftools/pull/13.  
So this PR only has a small correction in the order of the filter offsets which does not appear to make a big difference in the output but should now be correct.
I did some brief testing of this code where I checked the detector to v2v3 transform using:
```
from jwst.datamodels import ImageModel
a = ImageModel('jw93065001002_02105_00001_mirimage_rate_assign_wcs.fits')
tt = a.meta.wcs.get_transform('detector', 'v2v3') …
```
> Fixed shift column/row order

- jwst/assign_wcs/fgs.py
- jwst/assign_wcs/miri.py
- jwst/assign_wcs/nircam.py
- jwst/assign_wcs/niriss.py
- jwst/assign_wcs/nirspec.py
- jwst/assign_wcs/tests/test_wcs.py
- jwst/transforms/models.py
Changed units in V2V3 to degrees.
The transform from V2V3 to sky and the inverse transform use the same class so having the same input units in V2V3 and on sky helps.
> convert v2v3 to deg

- jwst/assign_wcs/pointing.py
- jwst/datamodels/schemas/core.schema.yaml
@hbushouse Please review this.
Without defaults, these are assigned None and code has to populate them in order to create a valid WCS object.
> Add default values to core schema.

- jwst/datamodels/schemas/core.schema.yaml
Removed all keywords in the core schema block "target_acq". Fixes #377.
> Removed target-acq keywords

- jwst/tso_photometry/__init__.py
- jwst/tso_photometry/tso_photometry.py
- jwst/tso_photometry/tso_photometry_step.py
This PR is the initial version of the imaging TSO photometry step.  A notebook of example usage with `/grp/jwst/ssb/bushouse/jwst_data/NIRCam/tsoimg/jw11001001001_01101_00001_NRCA1_calints.fits` can be found here:
https://gist.github.com/larrybradley/f8cbf29560e3d3768f62a98a7bfb7120
One piece of information that I'm still missing is the `(x, y)` position of the source in the image.  In this PR I've simply used the geometric center of the subarray.  However, that doesn't make sense for the `FULL` subarray mode because the center position is located in the `B` detector gaps.  Also, I noticed that the source in `jw11001001001_01101_00001_NRCA1_calints.fits` is centered at ~`(153, 161)`, which is not the center of the subarray.  I'll update the aperture position when we get more information …
> Added imaging TSO photometry step

- scripts/set_velocity_aberration.py
Committing initial version of script to compute velocity aberration scale factor and populate the appropriate FITS keyword, to be applied by SDP to level-1b products. This version uses the RA_REF and DEC_REF values in the image as the "target" location. This could be changed to something else, like TARG_RA/TARG_DEC, if desired. It obviously assumes that RA_REF and DEC_REF have already been populated.
This script just wraps the routine "vel_scale.py" that @philhodge wrote.
> Baseline version of velocity aberration script

- jwst/assign_wcs/nirspec.py
- jwst/assign_wcs/tests/test_nirspec.py
@nden requested that I look into moving the wavelength unit conversion (meters -> microns) earlier in the assign_wcs piece of the pipeline as it was being missed by data with a filter="OPAQUE".  The meter -> micron was moved earlier and tested against a NIRSPEC IFU dataset.
Non-opaque version:
```
from datetime import datetime
from jwst.assign_wcs import nirspec
from jwst import datamodels
a = datamodels.ImageModel('jw00011001001_01120_00001_NRS1_rate_assign_wcs.fits')
a_wcs = nirspec.nrs_ifu_wcs(a)
w1 = a_wcs[0].get_transform('detector', 'v2v3')
x = int( (a_wcs[0].domain[0]['upper'] - a_wcs[0].domain[0]['lower']) / 2 + a_wcs[0].domain[0]['lower'])
y = int( (a_wcs[0].domain[1]['upper'] - a_wcs[0].domain[1]['lower']) / 2 + a_wcs[0].domain[1]['lower'])
print('{}, {} -> {}'.format(x, y, …
```
> Moved wavelength unit conversion earlier

- jwst/assign_wcs/pointing.py
Coordnates are 0-based, while CRPIX are 1-based. Remove 1 from CRPIX before applying the transform.
> crpix is 1-based

- jwst/flatfield/flat_field.py
- jwst/flatfield/flat_field_step.py
These updates address several issues, including #187. Much of the entire structure of handling and applying flat-field to non-NIRSpec exposures has been updated to remove a lot of the old unnecessary infrastructure that was put in place over the past 1-2 years to handle special modes of NIRSpec data. These are no longer needed, because there is a completely separate routine now for all NIRSpec data.
Specifically, non-NIRSpec flat ref files will never be in the form of CubeModel's or MultiSlitModel's - they will always be simple image-like models and hence the flat ref file can be loaded into a FlatModel, which applies the dynamic DQ mapping to the ref file data (thus fixing #187). Not having to worry about Flats in the form of MultiSlitModel's allows for the removal of a lot of old …
> Rework non-NIRSpec flat-field algorithms

- jwst/assign_wcs/nirspec.py
- jwst/assign_wcs/tests/test_nirspec.py
Reverts STScI-JWST/jwst#375
Conversion of wavelengths from meters to microns was moved ahead in the WCS pipeline to
cover the case when filter=OPAQUE and the pipeline stops before the filter wheel.
However, the NIRSpec transform through the filters is chromatic and expects the wavelength to be in meters.
> Revert "Moved wavelength unit conversion earlier"

- jwst/flatfield/flat_field.py
Add a little robustness to recent flat-field updates to handle all the stupid old NIRCam flats that don't have substrtn and subsizen header keywords.
> Flat-field robustness

- jwst/extract_2d/extract_2d.py
@nden @philhodge This PR allows the wcs object to take as input native coordinates of the extracted 2-d slit array.
Before, to get world coordinates at position (x, y) in the slit:
`ra, dec, lambda = slit.meta.wcs(x + slit.xstart - 1, y + slit.ystart - 1)`
Now we simply can call the wcs object with native (zero-based) coordinates of the slit:
`ra, dec, lambda = slit.meta.wcs(x, y)`
and get the same result.  Now functions and methods that use the wcs object can work with the wcs object alone instead of having to work with the full datamodel and needing to read in `xstart` and `ystart`.  This change is made to allow the API of resample and other functions that use the wcs object to be much simpler.  Now the gwcs.WCS object is self-contained, fully describing the slit to which it is …
> Add offset transform to WCS for each slit in extract_2d MultiSlitModel

- jwst/datamodels/schemas/core.schema.yaml
CRDS folks want the R_SPDIST keyword name for the SPECWCS reference file updated to conform (at least more closely) to the usual syntax for these keywords, so we're changing it to R_SPCWCS. Only the keyword name is changing; the data model attribute name (model.meta.ref_file.specwcs.name) is not changing, so hopefully no cal pipeline code updates are necessary to keep up with this change.
> Core schema update

- jwst/assign_wcs/nirspec.py
- jwst/assign_wcs/tests/test_nirspec.py
**_Note:_** This is in reference to #375 which was not implemented quite right.  So, this one should now be fixed. The main thing is the meter -> micron transform is applied at the MSA _only if_ the filter is OPAQUE otherwise it is applied at the OTE. 
@nden requested that I look into moving the wavelength unit conversion (meters -> microns) earlier in the assign_wcs piece of the pipeline as it was being missed by data with a filter="OPAQUE".  The meter -> micron was moved earlier and tested against a NIRSPEC IFU dataset.
Non-opaque version:
```
from datetime import datetime
from jwst.assign_wcs import nirspec
from jwst import datamodels
a = datamodels.ImageModel('jw00011001001_01120_00001_NRS1_rate_assign_wcs.fits')
a_wcs = nirspec.nrs_ifu_wcs(a)
w1 = a_wcs[0].get_transform('detector', …
```
> Moved wavelength unit conversion earlier -- corrected

- jwst/datamodels/schemas/core.schema.yaml
Two more values are needed from the SIAF to compute telescope pointing info. Those will be stored in two new header keywords VPARITY and V3I_YANG. Added these to the core schema. DP will be populating them from the SIAF entries, along with V2_REF and V3_REF.
> Update schema for necessary SIAF keywords

- jwst/cube_skymatch/cube_skymatch_step.py
- jwst/cube_skymatch/skycube.py
This should fix most of the bugs related to expanding schemas in cube skymatching. One major issue left is that input cube's ``meta.filename`` contains cube's actual file name instead of input 2D image file name that was used to create the cube. A follow-up PR will be needed once there is an agreement on how to store these 2D file names.
> Fix bugs related to extending schema for cube sky matching

- jwst/datamodels/model_base.py
- jwst/datamodels/schemas/core.schema.yaml
- jwst/extract_1d/extract_1d_step.py
- jwst/pipeline/calwebb_spec2.cfg
- jwst/pipeline/calwebb_spec2.py
Several updates to move towards enabling everything that's needed for B7 calspec2 operations.
Updated the calwebb_spec2 pipeline module to include calls to cube_build and extract_1d, with a stubbed out entry for now for resamp_spec. This includes updates for saving the various products produced along the way.
Also updated the core schema and the model_base infrastructure to include a meta attribute that gives the datamodel type. The FITS keyword name is "DATAMODL" and the corresponding meta attribute is model.meta.model_type. It is populated when a model is created and is updated before saving a model to disk in case the meta data for the model got overwritten by the meta data of another model through use of the model.update method.
Finally, the extract_1d_step module was updated to no …
> Calspec2 updates for cube_build and extract_1d

- jwst/assign_wcs/miri.py
- jwst/transforms/schemas/lrs_wavelength-0.1.0.yaml
Under @nden 's direction, this will run on both slitless prism exposure and fixed slit files (at least the two that I have:
```
jw00025001001_01107_00002_MIRIMAGE_rate.fits - slitlessprism exposure
jw00035001001_01101_00001_MIRIMAGE_rate.fits - fixed slit
```
> Changes towards MIRI LRS to go to sky coordinates

- jwst/datamodels/model_base.py
- jwst/datamodels/util.py
Updates to the handling of datamodel types. The initial version just stored the class name of the datamodel when saving a model to disk. These updates now add the capability to use that stored class name when reloading a file from disk into a datamodel, so that datamodels.open() returns a model of that type.
The approach isn't pretty, due to the need to know the full class path name, consisting of "jwst.datamodels.<module>.<class_name>" in order to be able to import it, but it works - for now. It uses a dictionary to find the module name that defines a given class, and then hardcodes the "jwst.datamodels" prefix to the full class path. The dict will need to be updated whenever someone adds a new datamodel or changes any class/module names.
> Use model type from input file

- jwst/srctype/srctype.py
Updated the srctype routine to handle stellarity values of -1, which are to be treated as indicating that the source type is unknown. So if stellarity<0, set srctype='UNKNOWN.'
> Handle stellarity of -1

- jwst/extract_1d/extract.py
The methods dict.has_key() and zip() changed in python3.  These updates allow the code to run under both python2.7 and python3+.  @philhodge
> Python3 compatibility

- jwst/dq_init/dq_init_step.py
- jwst/jump/jump.py
- jwst/jump/jump_step.py
Updated the jump step to address two bugs, as documented in #438 and #445.
Changed the reference to "group_integration_time" to "group_time", which is the proper name as currently defined in the core schema.
Added checks to see if the ngroups keyword value is consistent with the actual data array dimensions. If not, throw an error.
Added similar checks for the values of nints and ngroups to the dq_init step, not because it relies on them, but because it's usually the first step in any pipeline processing and hence any problems with the data dimensions will be caught early.
> Jump step bug fixes

- jwst/datamodels/__init__.py
- jwst/datamodels/util.py
Moved population of the datamodel type dictionary to __init__.py, which ensures that all defined model types are included in the dictionary and greatly simplifies the use of it in the util.py open function. When open is called and the specified model_type exists in the dictionary, a new class of that type is returned. If the specified model_type doesn't exist in the dictionary, it falls back to trying to figure out the type using the old logic based on data array shape, etc.
> Rework datamodel type dictionary

- jwst/timeconversion/__init__.py
Reported via email thread.
```
jwst/timeconversion/__init__.py", line 164, in jwst_ephem_interp
raise ValueException(
NameError: global name 'ValueException' is not defined
```
> Replace ValueException with ValueError

- jwst/datamodels/__init__.py
- jwst/datamodels/util.py
The util.open function in datamodels tries to determine the best datamodels class to use when opening an image. The code has always been complex and recently has grown more complex when new code to read the class name from a header keyword was added. This change splits off two new functions, _class_from_model_type and _class_from_shape which encapsulate the code that determines the datamodels class used to open an image from a primary header keyword and from the image shape, respectively.
> Split datamodels.util.open into several functions

- jwst/datamodels/schemas/multiproduct.schema.yaml
Updated the datamodels/schemas/multiproduct.schema.yaml file to contain the same list of meta data definitions as the MultiSlitModel, so that those values can then be copied over from a MultiSlitModel to a MultiProductModel.
> Include metadata in MultiProduct model

- jwst/photom/photom.py
Two updates to the photom step code.
1) Treat NRS_BRIGHTOBJ exposures the same as NRS_FIXEDSLIT. Previously it was defaulting to treating them like IFU and MSA exposures, which uses a slightly different photom ref table format.
2) Check the wavelength array read from the photom reference file and convert the values from meters to microns, when necessary. Eventually I want to find a way to then set the TUNIT keyword for the wavelength column in the output RELSENS extension, but can't seem to do that right now when creating the RELSENS data table from scratch.
> Photom bug fix and wavelength updates

- docs/pipeline/source/description.rst
Updated the pipelines description document to give a detailed list of the calwebb_spec2 steps that are applied to each of the different spectroscopic observing modes.
> Updated calwebb_spec2 pipeline doc

- jwst/flatfield/flat_field.py
Depending on the compination of filter and grating a Nirspec IFU observation may fall completely outside the detector in which case the domain is also outside the detector. The flat fielding step should skip these kind of observations. 
The assign_wcs step should probably also do something about it so that the flat field step may be skipped completely even before starting.
> fix undefined variable

- jwst/assign_wcs/miri.py
- jwst/assign_wcs/nircam.py
New distortion models produce output in arcsec. All V2V3 data should be in deg.
> fix nircam v2v3 units

- jwst/datamodels/schemas/core.schema.yaml
SDP needs to add this keyword to the FITS headers, so adding it to our schema too.
> Add TARGID keyword to core schema

- jwst/pipeline/calwebb_spec2.py
Some NIRSpec filter+grating combinations result in no useable data falling on the detector (usually NRS2), in which case assign_wcs will skip its processing and return. This update to the calwebb_spec2 pipeline checks to see if assign_wcs was skipped and aborts all remaining processing for the exposure, because so many of the downstream steps depend on having valid and useful WCS information. It's easier to abort here in the pipeline rather than having each step check to see if the WCS is valid.
> Update calwebb_spec2 to abort when assign_wcs is skipped

- jwst/assign_wcs/assign_wcs.py
- jwst/assign_wcs/nirspec.py
- jwst/extract_2d/extract_2d.py
This PR implements a check that an open slit/slice is projected on one of the NIRSpec detectors. If it does not fall within a detector it is removed from the list of open slits. If there's no open slit that falls on the detector the assign_wcs step is set to "SKIPPED". 
This works by running the models from the MSA to the detector for each open slit and examining the domain. If the domain shows the slit does not fall on the detector, the slit is removed.
Extract2d was changed to get the list of open slits from one of the transforms in the WCS pipeline ( a cludge but will work for build 7). Since flat field and resample work with outputs fromextract_2d, they don't need to be modified. They also don;t need to check the domain now (flat field may be modified to not check the domain). For IFU …
> Fall off detector

- jwst/datamodels/schemas/core.schema.yaml
Level-1 data processing is failing because the values coming from the database for the FCRLPOS keyword are in the form of a string, but the keyword is currently defined as integer type. So updated the type to string, in order to allow schema validation to succeed.
> Update FCSRLPOS keyword data type

- jwst/dq_init/dq_init_step.py
Updated the array dimension checking in the front end of the dq_init step to allow for a mismatch in SUBSIZE2 (ysize) vs. NAXIS2 when you're dealing with a NIRSpec exposure that uses the IRS2 readout mode. In these cases the actual data array dimension is 3200, while SUBSIZE2 (ysize) is 2048.
> Update dq_init for IRS2 size check

- jwst/refpix/refpix_step.py
The second argument to get_reference_file was changed from 'irs2' to
'refpix'.  See Github issue #506 and JIRA issue JP-115.
> refpix step refers to reftype 'irs2' instead of 'refpix'

- jwst/dark_current/dark_current_step.py
Modified the dark_current_step module to use the generic datamodels.open() method to open the input science data, rather than hardwiring it to open as a RampModel. This was messing up the passing of datamodel components when the input was a MIRIRampModel. The generic open method now uses the datamodel type stored in the datamodel itself to determine whether the input is a plain RampModel or the special case of a MIRIRampModel.
> Update dark step to use generic open for science input

- jwst/assign_wcs/nirspec.py
Fixes a bug in `validate-slits` uncovered in DMS testing where an observation with the prism was not considered.
> account for prism in validating

- jwst/extract_2d/extract_2d.py
New `EXP_TYPE` values were added to `assign_wcs` in build7. These need to be added to `extract_2d` as well.
> add exp_types to extract2d

- jwst/assign_wcs/miri.py
this shold be merged by asdf-standard#135 and gwcs#68
It fixes the backward transform from alpha_beta to detector in the MIRI MRS.
> atol i mrs

- jwst/tweakreg_catalog/tweakreg_catalog.py
This is a minor change to replace the deprecated `photutils.daofind` function with the new `photutils.DAOStarFinder` class.
> Replace deprecated daofind function with new DAOStarFinder class

- jwst/superbias/bias_sub.py
Updated the superbias step to do a more thorough check of computed slice indexes when trying to extract a subarray from the reference file data. There were instances of bad ref files or bad SUBSTRTn values leading to attempts to slice outside the boundaries of the reference data array.
> Update superbias to check ref file subarray

- jwst/pipeline/calwebb_spec2.py
Reverted calwebb_spec2 to NOT call resample_spec for MIRI LRS fixed-slit exposures, because output is still currently garbage or blank. By skipping the step, the unresampled data are fed downstream to extract_1d, so that it can produce reasonable output for the extracted spectrum.
> Revert calspec2 for MIRI LRS fixedslit

- jwst/datamodels/fits_support.py
The function get_hdu first tries to get the hdu using the parameters passed to it. If this fails, it constructs a tuple (hdu_name, 1) on the hypothesis that the get failed becase the hdu_name was not
unique. This second try only makes sense if the hdu_name passed is a string, because all integers are unique. So the test to form the tuple now asks if hdu_name is a string.
The error was uncovered when testing a modification to astropy.io.fits that implements lazy loading. The new code throws a TypeError when it is passed a tuple of the form (int, int), which the get_hdu code does not handle. Since the new code will not create this kind of tuple, the change will no longer affect datamodels.
> Revise tests for constructing tuple in fits_support.get_hdu

- jwst/cube_build/__init__.py
- jwst/flatfield/__init__.py
- jwst/pipeline/__init__.py
- jwst/resample/__init__.py
- jwst/superbias/__init__.py
- jwst/superbias/bias_sub.py
Updated the superbias step to allow it to handle the current batch of NIRCam superbias ref files that don't have SUBSTRTn and SUBSIZEn keywords in them. If the ref data are full-frame, use default values for these keywords.
Also updated the version numbers of a few steps that've been updated in rc6.
> Superbias patch and version updates

- jwst/flatfield/flat_field_step.py
This checks for the case that for NIRSpec data, EXP_TYPE is not one of the supported types, and if it isn't supported the calibration switch will be set to SKIPPED and a copy of the input returned.  This is primarily to trap NRS_IMAGE or similar types.
> Put back the changes for issue #429.

- jwst/datamodels/model_base.py
- jwst/datamodels/properties.py
Datamodels checks each time a metadata value is set and throws an error when the change fails to validate against the schema. It rolls back any change that fails to validate. This is problematic if the
original metadata is invalid, as when more than one metadata value is invalid, they cannot be fixed through datamodels as they can only be changed one at a time and each change will be rolled back because of the other invalid values. Datamodels has been changed to track if the metadata is valid and only throw an error if it changes from a valid to an invalid state. All the significant changes are located in the _validate method in properties.py. There is also a change in the ordering of the metadata set in model_base.__init__ to ensure the validation flag is set before the user's code makes …
> Modify schema validation error handling

- jwst/datamodels/schemas/core.schema.yaml
- jwst/srctype/srctype_step.py
When running the srctype step standalone, it's possible in some circumstances for the input model to get modified in place, without a new model being created for output. The use of a "with datamodels.open" block was causing the updated input_model to be closed by the time it was returned, resulting in an error when stpipe tries to save the returned model to disk. Removing the "with" block and just opening the input model directly allows it to stay open for the return in those circumstances where it's been modified in-place.
> Prevent srctype step from returning closed model

- jwst/cube_build/CubeCloud.py
- jwst/cube_build/cube_build.py
- jwst/cube_build/cube_build_step.py
In the last cube_build merge I tweaked how a cube spaxel's flux was determined from the weighted input pixels. This change was so that this cube_build was more inline with what David Law had for his weighting function. The distance between the input pixel and spaxel is determined and now it is normalized by the plate scale (cube sample size) in each dimension. The code used the wrong normalization factor - this has been fixed with this pull request.
> Fixed error introduced with last Merger

- jwst/photom/photom.py
Fixes a bug inadvertently created by last update to photom #568. This update makes sure that self.grating is initialized before it is referenced.
> Photom bug fix

- jwst/resample/resample_utils.py
The original implementation of this function accepted a list of
input models (or a model container) because it assumed that the
domain of the wcs objects was not populated.  And it turns out
this is true for the current wcs objects created be assign_wcs
for NIRCam.  No domain.  Meanwhile our mocked-up test data has
domains assigned, which is why our tests didn't fail.  Changing
the API back so that current NIRCam data works, until we fix
assign_wcs to add domains.
> change API of make_output_wcs() from wcs list to model list

- docs/pipeline/source/description.rst
Updated the pipelines doc to include a list of the calwebb_ami3 pipeline steps and also fix a few other minor things.
> Add calwebb_ami3 description to pipelines doc

- docs/srctype/source/conf.py
Changed labels/titles in srctype conf.py file. The word "dq_init" is now crossed out, with "srctype" written in crayon.
> Fix labels in srctype docs

- docs/datamodels/source/conf.py
- docs/datamodels/source/devel/attributes.rst
- docs/datamodels/source/devel/metadata.rst
- docs/datamodels/source/devel/models.rst
First attempt at updating datamodels documentation.  More to be done.  Current updates:
- added all the new datamodel types since Build 6
- examples use python 3 print() syntax now
> update datamodels documentation

- jwst/skymatch/__init__.py
- jwst/tweakreg/__init__.py
The __init__.py modules for the tweakreg and skymatch steps were missing an import of the step classes from their respective modules. This is needed in order to reference the step classes directly as "jwst.<step>.<StepClassName>", as is used in their .cfg files.
Fixes #633
> Add step class imports to skymatch and tweakreg

- jwst/assign_wcs/tools/nirspec/compute_world_coordinates.py
- jwst/datamodels/model_base.py
- jwst/datamodels/tests/test_fits.py
- jwst/datamodels/tests/test_history.py
- jwst/datamodels/tests/test_models.py
- jwst/datamodels/tests/test_schema.py
- jwst/datamodels/tests/test_wcs.py
- jwst/outlier_detection/flag_cr.py
- jwst/stpipe/step.py
- jwst/stpipe/tests/data/mkdata.py
The keyword `clobber` has been depreciated in Astropy 1.3 for io.fits.  The keyword `overwrite` is now preferred.  This PR updates all instances in the jwst package.
> Change clobber to overwrite; Astropy 1.3 depreciation

- jwst/ramp_fitting/ramp_fit.py
Temporary array dq_int has data type uint32, while temp_dq has data type
int32, and the code does a bitwise OR between dq_int and temp_dq.  This
used to work, but more recently (e.g. using Python 3.5.2 and numpy 1.11.3)
it fails because of the difference in data type.  Function gls_ramp_fit has
been modified to create temp_dq as data type uint32.  See #632.
> Change data type from int32 to uint32.

- jwst/datamodels/image.py
- jwst/datamodels/photom.py
- jwst/datamodels/schemas/image.schema.yaml
- jwst/datamodels/schemas/mirmrs_photom.schema.yaml
- jwst/photom/photom.py
- jwst/photom/photom_step.py
First set of major updates to implement #611. This changes the operation of the photom step for MIRI MRS exposures such that instead of reading a table of wavelength-dependent flux conversion values from the photom reference file, it loads the new style MRS photom ref file that includes a 2D array of sensitivity factors and a 2D array of pixel sizes.
The MRS photom data model and schema were updated to accommodate the new contents of the reference file. The portion of the photom step that handles MRS exposures was updated to divide the input pixel (SCI and ERR arrays) values by both the sensitivity factors and the pixel size array. Checks and logic have been included to handle NaN's and zeros in both the sensitivity and pixel size arrays, such that those values are reset to 1.0 and …
> Change MIRI MRS flux calibration scheme

- jwst/datamodels/drizproduct.py
- jwst/outlier_detection/blot_median.py
- jwst/outlier_detection/flag_cr.py
- jwst/pipeline/calwebb_image3.py
- jwst/resample/gwcs_blot.py
- jwst/resample/resample.py
- jwst/resample/resample_spec.py
- jwst/resample/resample_spec_step.py
- jwst/resample/resample_step.py
- jwst/resample/resample_utils.py
The commit includes many changes to the codebase for resample
and the code it depends on.  They are:
- Modify resample to use new API for wcs_from_footprints() from
PR #676
- Add compute_output_transform() function. Needs more generalization.
- Remove ambiguously-named method `assign_wcs` from DrizProductModel
- Clean syntax in blot_median
- Modify API for GWCSBlot.extract_image to take a datamodel instead
of just a WCS object, so pixel scale can be pulled from CDELT.
- Fix bug in Image3Pipeline where tweakreg_catalog cleanup fails
when the `--steps.tweakreg_catalog.skip=True` flag is used.
- Scaling params in resample are pulled from CDELT now instead of
the WCS transform.
- Clean up PEP8 issues throughout the code.
> Modify resample to use real WCS objects as in MIRI imaging.

- jwst/datamodels/__init__.py
Seven model class names were missing from __all__.  See Issue #695.
> Missing items in __init__.py

- jwst/datamodels/dynamicdq.py
- jwst/datamodels/fits_support.py
- jwst/datamodels/properties.py
- jwst/datamodels/util.py
This suppresses a warning message about no handler found when running tests.
> Add NullHandler to loggers

- jwst/datamodels/schemas/bunit.schema.yaml
- jwst/datamodels/schemas/cube.schema.yaml
- jwst/datamodels/schemas/ifucube.schema.yaml
- jwst/datamodels/schemas/image.schema.yaml
- jwst/datamodels/schemas/miri_ramp.schema.yaml
- jwst/datamodels/schemas/multislit.schema.yaml
- jwst/datamodels/schemas/quad.schema.yaml
- jwst/datamodels/schemas/ramp.schema.yaml
- jwst/photom/photom.py
Adding BUNIT keywords in the extension headers of science data models that use "data (SCI)" and "err (ERR)" arrays. Also updated the MIRI MRS portion of the photom step to update the BUNIT values after applying the new flux calibration scheme to the data (see #611 and #694).
The BUNIT keyword definitions can't belong to the core schema, because that's currently inherited by all data models, even those that don't use "SCI" and "ERR" extensions in their products. Including them in the core causes empty SCI and ERR extensions to be created in those FITS products, just so the BUNIT keyword value can be recorded. So I've put the definitions, for now, in a separate schema file ("bunit.schema.yaml"), which is then imported into the half-dozen or so science data model schemas in which they're …
> Add handling of BUNIT keyword in data extension headers

- docs/photom/source/main.rst
- docs/photom/source/reference_files.rst
- jwst/photom/photom.py
The NIRISS function in the photom step has been updated to fix the issue described in #677. Briefly, the function now only uses Order as a photom table row selector for the NIRISS spectral modes and does not use it for NIRISS imaging mode exposures.
The photom step docs have been updated to account for this change, as well as updates to the photom step handling for MIRI MRS mode.
> Don't use order for NIRISS imaging-mode photom

- jwst/photom/photom.py
There is a flaw in the logic in the new MRS portion of the calc_miri function in the photom step where pixels flagged as 'NON_SCIENCE' in the reference file DQ array are used to reset the reference data arrays to 1. The flawed logic was inadvertently using the flag value of 512 to reset pixel values in line 512 of the data arrays. The numpy "where" logic has been fixed to handle this properly.
> Fix photom handling of MIRI MRS ref file flags

- jwst/extract_1d/extract.py
- jwst/extract_1d/ifu.py
For IFU data, keyword SRCTYPE is read to determine whether the target
is a point source or extended.  The keyword values were assumed to be
either "point" or "extended"; they are, but upper case.
For an extended source with the IFU, background subtraction is not
supposed to be done.  The code now explicitly turns off background
subtraction for IFU data.
> Keyword was being compared with lower-case value; see issue #710.

- jwst/stpipe/tests/steps/python_pipeline.cfg
- jwst/stpipe/tests/test_pipeline.py
- jwst/stpipe/tests/test_step.py
stpipe tests produce a number of output `.fits` files that are now cleaned up
properly.  Also, the step and pipeline classes with `Test` in the name
were changed to resolve a pytest warning.  Resolves #189.
> Clean up fits files after stpipe tests run.

- docs/datamodels/source/devel/attributes.rst
Add a few missing data models, such as PixelArea and SuperBias, to the docs.
> Add missing data models to docs

- jwst/photom/photom.py
Encountered a NIRCam case from exp_type=NRC_TSIMAGE that did not have a valid AREA reference file in CRDS, which led to an error when save_area_info tried to open a file called 'N/A'. Added check for 'N/A' in the value of the area ref file name before calling save_area_info.
> Photom update for AREA=N/A

- jwst/pathloss/path_loss.py
Modified the path_loss.py module to use the correct meta names for retrieving the estimated source center information from the data model. This addresses issue 1 in #728.
> Pathloss source center bug

- docs/skymatch/source/index.rst
- docs/skymatch/source/skyimage.rst
- docs/skymatch/source/skymatch.rst
- docs/skymatch/source/skymatch_step.rst
- docs/skymatch/source/skystatistics.rst
A few minor updates to skymatch docs, including fixing the file name of "skimage.rst" to "skyimage.rst". This is the first round of updates needed for skymatch docs so that they include more user-level descriptive information, as is done for other pipeline step docs.
> Updates to skymatch docs

- jwst/datamodels/model_base.py
The validate flag controls whether a warning message is sent when a
fits keyword fails to validate. It was changed from False, as CRDS
relies on the validation.
> Set validate flag to True

- jwst/datamodels/container.py
- jwst/datamodels/tests/test_models.py
- jwst/resample/resample_step.py
This PR makes grouping more robust.
- No more unexpected grouping based on filename
- Grouping is strictly done based on `meta` keywords of input datamodels, i.e. for what we expect from NIRCam data
- Warnings are produced if the `meta` keywords are not populated
- Several new unit tests now test ModelContainer generally and grouping specifically
> ModelContainer grouping

- jwst/pipeline/calwebb_spec2.py
Modified the calwebb_spec2 pipeline to skip processing for non-science members listed in the association table, in order to accommodate entries for things like target acq's and NIRSpec autowave and autoflat exposures, which get listed in the ASN, but don't need processing (at least not yet).
Fixes #382.
> Make calwebb_spec2 skip non-science members

- jwst/jump/tests/test_twopoint_difference.py
- jwst/jump/twopoint_difference.py
In PR #581 Mike Regan provided us with an updated and optimized version of the twopoint_different routine used in the jump step. The version included here has had just slight modifications for working within the jwst package environment and just a bit of cosmetic changes. The routine has been tested and compared against the previous version of twopoint_difference and has been found to not only run 2-3x times faster than the previous version, but also properly handles all corner cases of things like saturated groups. It also uses the approach of the original creators of the algorithm in terms of not including the largest outlier of all groups (regardless of whether or not it's above the rejection threshold) when computing the median of group differences.
> New twopoint_difference routine from M. Regan

- jwst/jump/tests/test_twopoint_difference.py
The Travis failures appear to be due to the tests hitting the memory limits of the platform, so I've reduced the sizes of the test arrays from 2048x2048 to 200x200. Only 1 or 2 pixels within the arrays are ever used in any of the tests anyway. Had to make a few minor mods to the tests in places where they used pixels at indexes of 200 or higher. Nature of the tests are still the same - just moved the array locations of the test values.
> Reduce memory usage of jump twopoint_difference unit tests

- jwst/pipeline/calwebb_spec2.py
This fixes a bug that I inadvertently introduced in #747, in which calspec2 checks the value of the "exptype" attribute in the association. For single file/model input, the exptype attribute of the asn was not defined. It is now, and is set to a default of "science."
> calspec2: add exptype to asn template

- jwst/assign_wcs/tools/nirspec/compute_world_coordinates.py
This is an update of the nirspec testing tool for build 7.
The offsets computed in extract2d were included in the WCS in #412 but this script was not updated.
Don't merge yet until the 0- vs 1- based inputs is cleared up.
> compute_world_coordinates for build 7

- jwst/pipeline/calwebb_ami3.py
Updated calwebb_ami3 pipeline to use new product suffixes for output files ("lg" -> "ami"), and use a new entry in the ASN table called "psf_name" for constructing the file name of the averaged PSF fringe data, so that the file name is based on the PSF target name rather than the science target name.
> Calwebb_ami3 updates for product naming

- jwst/assign_wcs/niriss.py
Current and future WCS distortion reffiles for NIRISS imaging mode produce units of arcsec.  We had treated them as units in arcmin before.
> Fix assign_wcs for expected units (arcsec) for NIRISS imaging distortion

- jwst/pipeline/jump.cfg
Updated the default value of the rejection_threshold parameter in the jump.cfg file from 5.0 to 4.0, so that it matches the default value set in the jump_step.py module. Fixes #706.
> Update jump step default rejection threshold

- jwst/assign_wcs/fgs.py
- jwst/assign_wcs/miri.py
- jwst/assign_wcs/nircam.py
- jwst/assign_wcs/niriss.py
- jwst/assign_wcs/nirspec.py
- jwst/assign_wcs/tools/nirspec/compute_world_coordinates.py
- jwst/extract_2d/extract_2d.py
I will keep this open for a while and keep fixing problems as they surface.
`extract_2d`:
- Fixed how `xstart`, `ystart` are reset. Since `bounding_box` uses the edge of the pixel instead of the center, the values need to be converted to the center of the pixel + 1.
`assign_wcs`:
- Added a `bounding_box` to the miri imager. Convert from arcsec to deg since the new ref files are in arcsec.
- The LRS bounding_box uses the edge of the pixel now.
- Added a `bounding_box` to NIRISS imaging.
- Added `bounding_box` to NIRSPEC.
- Added `bounding_box` to FGS. Convert from arcsec to deg since the new ref files are in arcsec.
- Added `bounding_box` to NIRCAM.
> WIP: Fix problems with bounding_box

- jwst/datamodels/schemas/core.schema.yaml
Deleted TARGID (target.id) entry from core schema. Fixes #686.
> Remove TARGID from datamodels core schema

- jwst/assign_wcs/nirspec.py
NIRSpec CDP3 delivery includes the transform from XanYan to V2V3 in the reference files now.
The V2V3 values need to be in arcsec. I need to confirm this is the case before merging this PR.
> Remove hardcoded XYan to V2V3 transform

- .travis.yml
I'm not sure how we missed this, but we're still pulling in `stsci-jwst`, so I'm removing it.
> Remove stsci-jwst dependency

- jwst/datamodels/fits_support.py
- jwst/datamodels/model_base.py
- jwst/datamodels/properties.py
Error handling is now controlled by two keyword parameters in the __init__ method, error_if_invalid and pass_invalid_values. Both are false by default. Error_if_invalid is new.
If error_if_invalid is true, datamodels throws a ValidationError if a fits file does not validate against the schema. It raises a ValidationWarning if error_if_invalid is false. To convert the warning message to a log file message, call "logging.captureWarnings(True)". Datamodels will delay throwing an error when reading a fits file until all the data is checked so that a mesaage is printed for all problems with validation. Howerever, an error will be generated whenever a value is modified after reading, as the code has no way of knowing how many changes will be made.
If pass_invalid_values is true, datamodels will …
> Change error handling in datamodels

- jwst/datamodels/container.py
If metadata to allow grouping is not found in the input datamodels, the property `models_grouped` now behaves as expected.  It has as many groups as there are datamodels in the container.  I.e. no grouping by exposure.
> Default to no groups in ModelContainer if metadata is missing.

- jwst/assign_wcs/fgs.py
- jwst/assign_wcs/miri.py
- jwst/assign_wcs/nircam.py
- jwst/assign_wcs/niriss.py
- jwst/extract_2d/extract_2d.py
Wcs.bounding_box is in reverse order compared to model.bounding_box.
> fix order of inputs in lrs bounding_box

- docs/datamodels/source/devel/fits_files.rst
- docs/datamodels/source/devel/index.rst
This is the start of some docs on the high-level structure and content of science products stored as FITS files. Doesn't really belong under the datamodels developer docs, but needed to put it somewhere for now. Folks who are creating simulated data are asking for this kind of information.
> Docs for FITS science products

- jwst/ramp_fitting/ramp_fit.py
- jwst/ramp_fitting/utils.py
Corrects the misinterpretation of the NFRAMES keyword in the pedestal calculation. NFRAMES is the number of frames averaged per group, excluding the number of skipped frames (which is denoted by the GROUPGAP keyword).
> Rf 040317c

- jwst/datamodels/fits_support.py
- jwst/datamodels/properties.py
The messages now include the filename the error was found in, when available, and only surrounds the value in 'single quotes' if it is a string. This is to distinguish the not uncommon type errors where a numeric value is stored in a fits file as a string.
> Include more information in validation warning / error messages

- jwst/exp_to_source/tests/test_main.py
This skips the always failing tests in exp_to_source when the tests are run under python 2.7. In this way at least the rest o fthe tests get run under this configuration.
> skip failing test

- jwst/assign_wcs/fgs.py
- jwst/assign_wcs/miri.py
- jwst/assign_wcs/nircam.py
- jwst/assign_wcs/niriss.py
- jwst/assign_wcs/util.py
This PR adds support for subarrays for all instruments. Before this only Nirspec supported subarray mode.
In addition this fixes a problem with the order of inputs to the NIRISS SOSS wavelength solution mode
reported by the NIRISS team and debugged by @philhodge .
> add subarray transform

- jwst/pipeline/calwebb_sloper.cfg
The persistence step was recently updated to include definitions of 3 new types of reference files that aren't in CRDS yet, so all executions of calwebb_sloper cause a CRDS prefetch error when trying to find suitable ref files for those new types. So I've temporarily hardwired the calwebb_sloper.cfg to skip the persistence step, which also skips the CRDS prefetch.
> Skip persistence step in calwebb_sloper

- jwst/extract_2d/extract_2d.py
Since the limits of the `bounding_box` are now inclusive the size of the extracted slit needs to be increased by 1.
> correct size of extracted slit

- jwst/persistence/persistence_step.py
Comment out the assignment to reference_file_types so that CRDS will not
look for reference files that haven't been delivered yet.  Set the
calibration switch to 'SKIPPED' and return the input model with no
further change.
> Temporarily disable processing; see JWST issue #595.

- jwst/datamodels/schemas/core.schema.yaml
The keyword dictionary was updated for Build 7 to include 2 new wheel position keywords for NIRISS:
FWCPOS is the filter wheel position
PWCPOS is the pupil wheel position
as documented in https://jira.stsci.edu/browse/JWSTKD-13?jql=project%20%3D%20JWSTKD
Added these same keyword entries to the core schema. They are available as meta attributes instrument.filter_position and instrument.pupil_position.
> Add NIRISS wheel position keywords

- jwst/tests/test_set_telescope_pointing.py
- scripts/set_telescope_pointing.py
Similar code is in assign_wcs. The model there uses the correct units. This was missed when the codde was copied here.
> fix units in computation of roll_ref

- jwst/skymatch/skyimage.py
This addresses issue https://github.com/STScI-JWST/jwst/issues/836: The "origin" (third) argument in the WCS calls was a leftover from the testing times since testing was done using FITS WCS as no test image with a "real" gwcs was available at the time of ``skymatch`` development/testing.
> Fix WCS transform calls

- jwst/tests/test_set_telescope_pointing.py
- scripts/set_telescope_pointing.py
For cases where quaternions are not found in DB:
- PA_V3 is zero, but compute ROLL_REF correctly for the detector at hand
- Use the correct ROLL_REF and V3I_YANG to compute the angle for
use in PC matrix
Correct the parity of the PC matrix
Make log messages a bit more informative.
> Fix PC matrix computation

- jwst/skymatch/skyimage.py
Use `with_bounding_box=False` when computing a footprint on the sky.
> fix a call to WCS

- jwst/extract_2d/extract_2d.py
The subarray offset should be applied before the rest of the transforms. The best test for this is NRS2 observation. On NRS1 this will result in wavelengths being slightly off while on NRS2 the result will be all NaNs.
> fix order of transforms in extract2d

- setup.py
A person trying to build the jwst source code without `sphinx` installed will see this:
```bash
$ python setup.py install
Traceback (most recent call last):
File "setup.py", line 11, in <module>
import sphinx
ImportError: No module named sphinx
```
This change prevents `sphinx` from becoming a hard dependency at compile-time. If the user runs `build_sphinx` and `sphinx` is not installed, the script dies "gracefully".
```bash
$ python setup.py build_sphinx
running build_sphinx
!
! Sphinx is not installed!
!
```
> Prevents build failure if sphinx is not installed

- jwst/datamodels/fits_support.py
- jwst/datamodels/properties.py
Datamodels validates changes against the schema. However, the change itself may not be the actual error if the model is already invalid. Passing thru the message generated by jsonschema ensures the
error message is not misleading.
> Pass thru jsonschema error message after validation error

- jwst/datamodels/schemas/fgs_photom.schema.yaml
- jwst/datamodels/schemas/keyword_photmjsr.schema.yaml
- jwst/datamodels/schemas/keyword_pixelarea.schema.yaml
- jwst/datamodels/schemas/mirimg_photom.schema.yaml
- jwst/datamodels/schemas/mirmrs_photom.schema.yaml
- jwst/datamodels/schemas/nircam_photom.schema.yaml
- jwst/datamodels/schemas/niriss_photom.schema.yaml
- jwst/datamodels/schemas/nirspec_photom.schema.yaml
- jwst/datamodels/schemas/nirspecfs_photom.schema.yaml
Updated the various photom reference file schemas to use the new (non-core) approach. Also added a couple of new keyword_xxxxx schemas that I needed: one for the PHOTMJSR keyword and another for the 2 PIXAR_SR and PIXAR_A2 keywords. 
For the latter, I included the definitions for both keywords in a single schema and hence if we stick to the agreed upon convention for naming these files, it should be "pixelarea.schema.yaml". But because we already have a schema by that name, for the pixel area reference file, I named it "keyword_pixelarea.schema.yaml", even though it contains 2 keyword definitions. We could potentially get around this by renaming the existing pixelarea.schema.yaml (and associated pixearea.py module) to just "area.schema.yaml" (and "area.py").
> Update photom reference file schema [skip ci]

- jwst/datamodels/schemas/flat.schema.yaml
- jwst/datamodels/schemas/nirspec_flat.schema.yaml
- jwst/datamodels/schemas/nirspec_quad_flat.schema.yaml
The subarray schema was added to all three.  In the nirspec_flat and
nirspec_quad_flat schemas, core.schema.yaml was replaced with
referencefile.schema.yaml.  See issue #861.
> Update flat field reference file schemas [skip ci]

- jwst/datamodels/schemas/drizpars.schema.yaml
- jwst/datamodels/schemas/outlierpars.schema.yaml
The other instrument-specific drizpars and outlierpars reffiles do not need to be updated.  This is in support of #861.
> Update reffile schema for drizpars and outlierpars

- jwst/outlier_detection/flag_cr.py
- jwst/outlier_detection/outlier_detection.py
- jwst/pipeline/calwebb_image3.py
- jwst/resample/resample.py
- Prevent flag_cr from writing out the updated dq array to the
input FITS files
- Turn off blendheaders for outlier_detection step
- Turn off 2c names in Image3Pipeline
> Fix bugs in Image3Pipeline

- jwst/datamodels/distortion.py
- jwst/datamodels/schema_editor.py
The DistortionModel type in datamodels is implemented in distortion.py.  It allows the user to override the units of the distortion model through the optional parameters input_units and output_units. The checks which determine whether these optional parameters are set was incorrect and the result was both units were set to None. Fixing the checks resolved the problem.
> Fix overrides of distortion file units

- jwst/assign_wcs/miri.py
- jwst/assign_wcs/tests/test_miri.py
- jwst/transforms/jwextension.py
- jwst/transforms/models.py
- jwst/transforms/schemas/miri_ab2slice-0.7.0.yaml
- jwst/transforms/tags/jwst_models.py
This corrects problems with the MIRI MRS transform from `alpha, beta` to `detector`.
These changes go with spacetelescope/asdf-standard#140 and spacetelescope/gwcs#78 which should be merged before this one.
> MIRI MRS inverse transform

- jwst/datamodels/__init__.py
- jwst/datamodels/level1b.py
- jwst/datamodels/schemas/level1b.schema.yaml
Adding a new data model that is an exact match to the actual level-1b data products from SDP, which means it contains only the SCI and (optionally) ZEROFRAME data arrays, both with integer data type, and the GROUP parameters table. This is to allow for easier creation of simulated level-1b data sets. Using the RampModel means the SCI array gets stored as float data type and also adds all of the other ERR, PIXELDQ, and GROUPDQ arrays, which results in a FITS file that is unnecessarily large, due to the presence of all those extra zero-filled arrays.
> Add Level-1b data model

- jwst/datamodels/schemas/core.schema.yaml
- jwst/outlier_detection/flag_cr.py
- jwst/outlier_detection/outlier_detection.py
- jwst/pipeline/calwebb_image3.py
- jwst/resample/resample.py
- Add the following `meta.cal_step` keywords to the core schema:
- `tweakreg`
- `skymatch`
- `outlier_detection`
- `source_catalog`
- Fix bug in drizpars reffile parsing
- Cleanup of Image3Pipeline code
> Add cal_step keywords to core schema

- jwst/ami/leastsqnrm.py
- jwst/cube_build/cube_build_step.py
- jwst/wfs_combine/wfs_combine.py
Fix routines in the wfs_combine and ami_analyze steps that were causing errors due to the use of floating-point values as slice indexes.
Also temporarily comment out declaration of the new reference file types in cube_build_step, so that pre-fetch is disabled and allows calwebb_spec2 to run.
> Fix slice indexing errors and cubepars error

- jwst/outlier_detection/create_median.py
- jwst/outlier_detection/flag_cr.py
- jwst/outlier_detection/outlier_detection.py
- jwst/outlier_detection/outlier_detection_step.py
The outlier_detection step spec parameters were not getting passed
to the routines that actually do all the work: outlier_detection,
create_median, resample, blot and flag_cr.  Now they do.
Also some general code cleanup in the step.
> Fix outlier_detection so params get passed to subroutines

- jwst/datamodels/schemas/pathloss.schema.yaml
The pathloss step code accesses the value of the EXP_TYPE keyword in the pathloss reference file returned from CRDS, so that keyword needs to be defined in the pathloss ref file schema.
> Add exptype keyword to pathloss ref file schema

- jwst/coron/align_refs_step.py
- jwst/coron/stack_refs_step.py
- jwst/pipeline/calwebb_coron3.cfg
- jwst/pipeline/calwebb_coron3.py
Added temporary stubs to the calwebb_coron3 pipeline module to create fake outlier_detection products and resample products, until those steps are working for coronagraphic data. This will allow the pipeline to at least create all output product types as examples. Set the outlier_detection and resample steps to skip in the default calwebb_coron3.cfg.
Also updated the stack_psfs and align_psfs steps to set the step completion status in the metadata of their output models.
> calwebb_coron3: create fake output products

- jwst/datamodels/properties.py
- jwst/datamodels/schemas/core.schema.yaml
I am proposing removing some of previous changes to `properties._cast`.
The problem I am trying to solve is to serialize numpy arrays directly to asdf files. Note that currently all numpy array serialization in datamodels is to FITS files which calls specialized code.
Serializing ndarrays works with asdf but not with datamodels.
Looking at the code in `properties._cast` removed in this PR, I think it was added to solve an issue with saving Time objects to FITS files using the core schema. I believe there was a bug/typo in the core schema which caused the Time object problems. So here I've also commented out and changed the `date` field in the core schema to use `anyOf` instead of `allOf`.
This is all motivate by work on #888 which is currently stalled until the problem with numpy arrays …
> Save arrays

- jwst/pipeline/calwebb_spec2.py
- jwst/pipeline/tests/test_calwebb_spec2.py
Includes
- When assign_wcs is not done, a bare return was used. Should return the datamodel.
- Setting of save_results flag was bad
> Spec2Pipeline minor bug fixes

- jwst/dark_current/dark_sub.py
This update to the dark_current step fixes the problem identified in #907, by computing the full amount of data available in the dark reference file via its values of ngroups, nframes, and groupgap, with no assumption that nframes=1 and groupgap=0 for dark reference files.
> Fix dark_current nframes problem #907

- jwst/datamodels/model_base.py
A user reported on MacOSX he's getting 
```
OSError: [Errno 24] Too many open files
```
when running assign_wcs with the new WCS models. It turns out that when model.close() is called it only closes the file that was passed to the model. However,  `DataModel._asdf` is a separate instance of `AsdfFile` and it's not closed. Combined with the fact that data is mmapped (which seems to create a file handle for each mmapped block) it's clear why the file handles disappear.
This PR calls Model._asdf.close() which solves the problem. 
This problem was not seen before because assign_wcs used asdf directly to open the reference files.
I have confirmed also that using
```
with DataModel(filename) as f:
do_something
```
now releases the file handles after exiting the `with` statement.
> model.close() should close all components

- jwst/datamodels/fits_support.py
When setting an attribute of a datamodel or writing the datamodel out as a fits file, the code validates the datamodel against its schema. This schema can contain tag fields. When validating a tag field, the code checks for equality between the value of the tag field and the value of the _tag attribute of the corresponding item in the datamodel. You may ask, what is this _tag attribute and how is it set? Previously it was set by calling tag_object in asdf/tagged.py from _cast in datamodels/properties.py and _tag_values in datamodels/fits_support.py.
But, conscientiously tagging our data values was a mistake, as the validation code, in validate_tag in asdf/schema.py, skips the check if the _tag attribute is undefined. Since this check has no value for our use cases, we are creating …
> Remove _tag_values from datamodels/fits_support.py

- jwst/datamodels/model_base.py
- jwst/datamodels/util.py
Currently `DataModel.history=value`  works with FITS files if `value` is a list of strings. It doesn't work with ASDF files as they expect a `HistoryEntry` to be passed.
This PR adds documentation on how to use `DataModel.history` and a new function `util.create_history_entry` which can be used to create a valid `DataModel.history` object which can then be saved to an ASDF file.
> Add history to models

- jwst/datamodels/properties.py
#903 removed code from `properties._cast` that shouldn't have been removed. It casts numpy integer types to python int. This PR restores the removed lines.
> restore casting of numpy scalars to python ints

- jwst/pipeline/calwebb_ami3.py
Updated the calwebb_ami3 pipeline module to populate the ASNPOOL and ASNTABLE keywords in all output products, as requested in #893. Also updated to use latest Asn loading mechanism.
> Update calwebb_ami3 to populate ASN keywords

- jwst/datamodels/tests/test_fits.py
A test in jwst.datamodels was reporting a failure. The values reported were ('string', 1., 2. 3., 4.) and ('string', 1.0, 2.0, 3.0, 4.0). The test should be a success, but was a failure because of how the two records were compared. I wrote a  small function that compares the two records element by element and now the test passes.
> Fix fits test that fails, but shouldn't

- jwst/assign_wcs/nirspec.py
- jwst/assign_wcs/tests/test_nirspec.py
#601 describes the coordinate frame used for the source position in the slit for Nirspec MSA and FS observations. The origin of the frame is the upper left corner of the pixel with positive x to the right and positive y downwards. The position needs to be converted to the frame the Nirspec instrument model uses where the origin is in the center of the slit , +y is up and +x is right. This PR makes the conversion of the cooridnates when the Slit values are read in from the msa configuration file. This means that the wavelength zero-point correction and the path loss correction may use the values directly.
@hbushouse @stscirij 
Another related question (which was briefly discussed) is if this needs to be further transformed because of the DMS vs native coordinates. I am pretty sure the …
> change coord system for source position

- jwst/cube_build/cube_build.py
- jwst/cube_build/cube_build_io_util.py
- jwst/cube_build/cube_build_step.py
- jwst/cube_build/data_types.py
When running single=True the default method of determining the output_file and meta.filename was causing problems when the set of individual IFUCubes where saved as a ModelContainer. 
Reworked out filename in this case is determined. Need a better method long term - but for now this works.
> Output model

- jwst/datamodels/container.py
- jwst/datamodels/model_base.py
The `save` method gets passed a filename.  This gets ignored for ModelContainer, and `meta.filename` is used to write out the file. This change is needed as `stpipe.Step.save_model` method needs the same call signature for all DataModels that are returned from a step.
Also, add a filter to suppress "Card is too long" warnings from `astropoy.io.fits` when writing out a DataModel.  These warning messages are caused by our schemas containing descriptions that are too long for the FITS standard in some cases, and in others by keyword value strings that are very long.  All `DataModel.save` operations produce this warning, so let's suppress it.
> Make ModelContainer.save consistent with DataModel.save

- jwst/pipeline/calwebb_image3.py
- jwst/resample/resample.py
This simplifies the `Image3Pipeline` to take advantage of built-in `stpipe.Step` methods for writing output and makes it more consistent with the `stpipe` refactor in PR #897.
> Make Image3Pipeline consistent with stpipe refactor

- jwst/stpipe/step.py
- Allows know valid suffixes used in the JWST pipeline to be replaced with a new suffix in `Step.make_output_path`
- Resolves #949 
- restores the suffix-replacement behavior of `Step.save_model` from before the `stpipe` refactor
- We may want to automatically generate this suffix list as a suffix registry in the future
> Add valid suffixes for suffix replacement in stpipe.Step class

- jwst/pipeline/calwebb_spec2.cfg
This is a quickfix to get the pipeline to write out all necessary results when run with the default calwebb_spec2.cfg as in DMS.
> Turn on saving _cal results in Spec2Pipeline

- jwst/resample/resample_spec.py
This fixes the failure at `interpolate`, but it doesn't solve the larger issue of pixels being thrown to the wind and not landing in the output frame when we resample.
> Fix for #650, interpolation in building output frame in Spec2Pipeline [skip CI]

- docs/jwst/stpipe/user_pipeline.rst
- jwst/pipeline/tests/test_calwebb_image2.py
- jwst/stpipe/step.py
- jwst/stpipe/tests/steps/__init__.py
- jwst/stpipe/tests/steps/stepwithmodel_hook.cfg
- jwst/stpipe/tests/steps/stepwithmodel_hookreturn.cfg
- jwst/stpipe/tests/test_step.py
Previously, the result of the parent Step was passed directly to the
post hooks. This commit modifies to the calls to the post hooks to
always pass a list. If the parent Step already passes a list, no
modification is made. However, if the parent Step returns a single
item, that item is placed into a list, and this is passed to the post
hooks.
This allows post-hooks to modify the results.
Also a minor fix to the calimage2 tests is included.
> Modify behavior of running post hooks

- jwst/datamodels/schemas/core.schema.yaml
Remove CHRGTIME, GSCENTX, GSCENTY, and JITTERMS keywords from core schema. These are being removed from level-1b product headers by SDP.
Addresses #969 and #971.
> Remove unnecessary keywords from core schema

- conftest.py
- jwst/associations/tests/test_generate.py
- jwst/tests/helpers.py
If running under pytest, a new option has been added, `--runslow`. If
specified, tests marked with the `runslow` pytest marker will execute.
Otherwise those tests are bypassed
In `jwst/tests/helpers.py`, a number of decorators for pytest markers have been added:
- @runslow
As described, tests marked as such will only execute if the `--runslow` command line option
has been specified
- @require_bigdata
Checks for the existence of the environment variable "TEST_BIGDATA". If not found,
the marked test will not execute
- @not_under_travis
Checks for the existence of the environment variable "TRAVIS" and that its
value is "true". Is so, the test will not execute. Use to prevent tests from running
under TravisCI
To use, import the jwst/tests/helpers.py module. On the required test, simply add …
> Add new pytest option runslow and a central helpers module

- jwst/datamodels/schemas/referencecube.schema.yaml
- jwst/datamodels/schemas/referenceimage.schema.yaml
- jwst/datamodels/schemas/referencequad.schema.yaml
Update more reference file schemas in support of #861. These are the reference image, cube, and quad models. I don't think they're in use by any code modules anywhere, but they are used in the datamodels.open utilities to try to open reference files in a generic way.
> Update remaining reference file schemas to use new approach

- jwst/cube_build/cube_build.py
- jwst/cube_build/cube_build_step.py
- jwst/cube_build/data_types.py
- jwst/datamodels/schemas/ifucube.schema.yaml
Fixed an error when running cube_build single=true. No longer is it assumed that the ModelContainer has association info. Also fixed a error in writing the FLUX_EXT, ERR_EXT and WMAP_EXT names to the header. 
@mcara 
@hbushouse
> fixed error when running single = true

- docs/jwst/white_light/arguments.rst
- docs/jwst/white_light/description.rst
- docs/jwst/white_light/index.rst
- docs/jwst/white_light/reference_files.rst
- jwst/pipeline/white_light.cfg
- jwst/white_light/__init__.py
- jwst/white_light/white_light.py
- jwst/white_light/white_light_step.py
Adding draft 0 version of code and docs for the new step "white_light", which will be the final step of the caltso3 pipeline when processing spectroscopic data. It's very barebones for now, but at least creates the integrated flux from the spectrum corresponding to each integration, computes the time of each integration (stolen from the tso_photometry step), and dumps a table of time vs. integrated flux to an .ecsv file.
Addresses #621.
> Initial version of white_light step for caltso3 pipeline

- jwst/datamodels/model_base.py
- jwst/datamodels/schema_editor.py
- jwst/datamodels/tests/test_models.py
- jwst/datamodels/util.py
Several users have reported problems with warning messages from astropy.io.fits about trying to access an hdu after it was closed. I looked at the code and found two places where the handling of hdus can be improved.
In util.open a fits file is opened as a hdulist so the code can determine which class to use when opening a file. If the fits file is opened as a hdulist, as opposed to the hdulist being passed as an
argument, it is now closed before exiting util.open.
In model_base.__init__ fits files are opened as a hdulist. The data in the hdulist is then converted to an asdf file. The hdulist is placed in a list of objects to close when the datamodel is closed. The code
that adds the hdulist to that list was supposed to be inside a try block, in case the open failed. Because of incorrect …
> Close hdulist if it was opened by datamodels.util.open

- jwst/datamodels/util.py
Datamodels.open opens a fits file as a hdulist in order to examine the
header andshape and determine which class to use to open the
file. Since it opens the hdulist, it should also close it. Previously
I had the open function close the hdulist, which was wrong. (What was
I thinking?) The code now appends the hdulist to the list of files to
close when closing the datamodel.
> Change code to close hdulist in datamodels.open

- jwst/datamodels/ndmodel.py
- jwst/datamodels/properties.py
An iterator was defined on the datamodels meta node as part of the effort to provide compatibility with the astropy NDData interface. Because having a way to iterate over nodes in a datamodel is generally useful, the code for the iterator was moved into the parent of MetaNode, ObjectNode. The iterator walks the tree and returns keys from subtrees as dotted names, e.g. "meta.instrument.name".
In addition a new method was added to ObjectNode, items(). It is a generator which returns a (key, value) tuple with each invocation. It invokes the new iterator and so the key in the tuple has the same format.
This request addresses issue #1003
> Add iterators to object nodes in datamodels

- jwst/datamodels/schemas/core.schema.yaml
Update core schema to add the new FGS guiding mode EXP_TYPE's to the enum list for EXP_TYPE. They include FGS_ID-STACK, FGS_ID-IMAGE, FGS_ACQ1,  FGS_ACQ2, FGS_TRACK, and FGS_FINEGUIDE.
In support of #597.
> Add FGS guiding modes to EXP_TYPE

- docs/jwst/ramp_fitting/index.rst
automodapi command in index.rst was missing a white space, causing it to fail.
> Fix typo in ramp_fitting doc index

- jwst/datamodels/model_base.py
The current version of DataModel.__init__ only extracts the filename from the input if the input is a string. This version also extracts the filename if the input is an hdulist. In that case it calls fileinfo to get the filename from the hdulist. This change was needed because in the most usual case the generic open function passes an hdulist to DataModel.__init__, so previously the filename was not
being updated in the metadata.
> Extract filename from hdulist for storage in metadata

- jwst/assign_wcs/util.py
Missed one call to gwcs.get_axes which now returns 3 outputs. Should fix the nightly resample test failure.
> fix another instance of gwcs.get_axes

- jwst/datamodels/schemas/core.schema.yaml
NIRCam is adding a new keyword that indicates the number of detector outputs used when reading out an exposure. The default is 4 outputs, but for some subarrays the user can choose to use just 1 amplifier output.
Implementing as documented in [JWSTKD-28](https://jira.stsci.edu/browse/JWSTKD-28)
> Add NOUTPUTS keyword to core schema

- jwst/cube_build/cube_build_io_util.py
- jwst/cube_build/data_types.py
- jwst/datamodels/container.py
- jwst/datamodels/tests/test_models.py
- jwst/mrs_imatch/mrs_imatch_step.py
- jwst/tweakreg/tweakreg_step.py
- jwst/tweakreg_catalog/tweakreg_catalog_step.py
The iterator that is part of the model container has been rewritten so that at each iteration the current model is opened and the previous model is closed. To support this, the code in model container has been changed so that models are not opened when the container is created and random access checks if the model is open and opens it if it is not. The purpose of this change is to reduce the memory footprint of code that uses model containers.
> Change the model container iterator to open one model at a time

- jwst/source_catalog/source_catalog.py
- jwst/source_catalog/source_catalog_step.py
This fixes #1051 **assuming** the input `DrizProductModel` filename always ends in `_i2d.fits`.  Please let me know if that's not the case and I will generalize this.
This PR also includes a small fix to the masked AB mag assignment.
> Do not include _i2d in source catalog filename

- jwst/pipeline/calwebb_spec2.cfg
- jwst/pipeline/calwebb_spec2.py
- jwst/pipeline/tests/data/calwebb_spec2_basic.cfg
Previously, the pipeline retained results from each product in an
association, saving all only at the end of processing. This was both
memory-inefficient and, if the process crashed, would cause loss of
results.
> Save results from each association product as produced

- jwst/pipeline/calwebb_image2.py
- jwst/resample/resample.py
- jwst/resample/resample_spec.py
- jwst/resample/resample_utils.py
- take out units in `astropy.modeling.models` instances
- compensate for `SourceModelContainer` replacing `ModelContainer`. I.e. when iterating through `SourceModelContainer`, one does not get datamodel instances, instead one gets nodes.
> Fix bugs in resample_spec

- docs/jwst/associations/index.rst
- docs/jwst/introduction.rst
- jwst/associations/lib/rules_level2_base.py
- jwst/associations/load_as_asn.py
- jwst/pipeline/calwebb_image2.py
- jwst/pipeline/calwebb_spec2.py
- jwst/pipeline/tests/test_calwebb_image2.py
Re-enabled use of `output_file` when specifying individual files to the Level 2 pipelines.
> Updates to level 2 pipelines an use of output_file

- jwst/stpipe/crds_client.py
- jwst/stpipe/pipeline.py
- jwst/stpipe/step.py
I refactored the stpipe reference file pre-fetching to enable association (ModelContainer) pre-fetches and to better handle model opening, closing, and garbage collection.  Hopefully it minimizes the pipeline prefetch overhead by sticking to a single open model and garbage collecting only at the top level.  (step.py, pipeline.py).  
Refactored Step methods into focused and nested goals (open a model if needed and garbage collect,  handle containers,  handle overrides and result checking, etc).  I also removed some of the "retreat logic" like "if self.skip: return" by using it to avoid calling the method instead.
I removed the seemingly unused get_reference_file_model() method.  list_reference_files(),  which does not handle associations and containers,  should likewise be considered for …
> Fix association reference file prefetch

- jwst/extract_1d/extract.py
- jwst/extract_1d/ifu.py
- jwst/extract_1d/spec_wcs.py
For each 1-D extracted spectrum, a WCS object is created that includes the right ascension and declination at the nominal center of the slit, plus the wavelength array that is also stored as a column in the output table.
> Create WCS objects for the 1-D extracted spectra.

- jwst/datamodels/guidercal.py
- jwst/flatfield/flat_field.py
- jwst/flatfield/flat_field_step.py
- jwst/pipeline/__init__.py
- jwst/pipeline/calwebb_guider.cfg
- jwst/pipeline/calwebb_guider.py
- jwst/pipeline/guider_cds.cfg
Modified the flat-field step to handle Guide mode data models. Misc other little updates to the guider pipeline, adding its import to the pipeline package, adding a .cfg file for the guider_cds step, etc.
As far as I can tell this really does complete the work on the guider calibration pipeline. All steps now work on all modes of guiding data. All we're missing is mask reference files in CRDS that match the size of the ID mode stacked images.
> Updates for the FGS guiding data calibration

- jwst/datamodels/schemas/core.schema.yaml
- jwst/dq_init/dq_init_step.py
- jwst/dq_init/dq_initialization.py
- jwst/flatfield/flat_field.py
Updates to dq_init and flat_field to handle the case of reference files not matching the weird size of the ID mode images that have the strips stacked into a larger than 2048x2048 shape. Eventually there should be reference files in CRDS to match the size of this mode, but for now these checks will cause the dq_init and flat_field steps to be skipped.
Also minor updates to core schema and some pep8 cleanup.
> A few more updates to FGS guider calibration

- jwst/datamodels/schemas/core.schema.yaml
- jwst/msaflagopen/msaflag_open.py
- jwst/msaflagopen/msaflagopen_step.py
Made a bunch of updates to the core schema to include keywords for new reference file types and calibration step status (also just rearranged the entire two lists of R_xxxxxx and S_xxxxxx keyword entries to put them into something like alphabetical order to make them easier to find). Also fixed the datamodel name for the status attribute in the msa flagging step.
> Core schema updates for ref files and step status

- jwst/pipeline/calwebb_sloper.cfg
Remove "skip = True" in the default calwebb_sloper.cfg so that the persistence step will get executed in normal runs of the calwebb_sloper pipeline.
> Activate persistence step in calwebb_sloper

- jwst/datamodels/schemas/core.schema.yaml
Move remaining V1 axis pointing keywords RA_V1, DEC_V1, PA_V3 from primary to SCI header. Now all pointing related keywords are in the SCI header.
> Move remaining pointing keywords to SCI header

- scripts/set_velocity_aberration.py
Quick-n-dirty update to the set_velocity_aberration script to account for the fact that the RA_REF, DEC_REF, and VA_SCALE keywords have moved from the primary header to the SCI header. In the future this should be updated to use a Level1bModel to access the file, which would make it immune to keyword moves (as has been done for set_telescope_pointing).
The set_bary_helio_times script uses keywords that still reside in the primary header, so it doesn't need updating.
> Update velocity aberration script for relocated keywords

- jwst/datamodels/model_base.py
Under some circumstances, users would get a warning message when closing a model file that said the hdulist was already closed. The warning has been traced to the list of files to close contained in the model. When a model is copied, the same file is on the list of both models, so the same file gets closed twice. The code has been changed to truncate the list of files to close when a model is copied, so the file is only on a single list.
This problem was first reported by @philhodge
> Fix hdulist warning message caused by double close

- jwst/exp_to_source/tests/data/jwst_nod1_cal.fits
- jwst/exp_to_source/tests/data/jwst_nod2_cal.fits
- jwst/exp_to_source/tests/data/jwst_nod3_cal.fits
Recent updates to the ASDF library added more stringent warnings for mismatches between supported tag versions and tag versions found in ASDF files. In general, this is a good thing. However, it caused a lot of new warnings when running the built-in JWST test suite. This PR implements the changes that make the warnings go away.
> Fix asdf version mismatch warnings

- jwst/assign_wcs/nirspec.py
- jwst/assign_wcs/tests/test_nirspec.py
- jwst/datamodels/schemas/multiproduct.schema.yaml
- jwst/datamodels/schemas/multislit.schema.yaml
- jwst/extract_2d/extract_2d.py
- jwst/msaflagopen/msaflag_open.py
- jwst/resample/resample_spec.py
- jwst/transforms/models.py
Remove all occurrences of the NIRSpec MSA catalog_id field in all calspec2 steps, because that field is going away from the MSA metadata files that we use as input. We never did anything with the value other than copy it from the MSA metadata source table to a header keyword for each slit instance created. This removes it from all code modules and also removes it from the keyword schemas in which it appeared.
Fixes #1118
> Remove all occurrences of MSA catalog_id

- scripts/move_wcs.py
This is the initial commit tested on one file only.
Needs more testing and some documentation.
It moves the following keywords:
```
['PA_V3', 'V2_REF', 'V3_REF', 'PA_APER', 'VPARITY',
'RA_V1', 'DEC_V1', 'ROLL_REF', 'RA_REF', 'DEC_REF',
'PCi_j', 'CRVAL', 'CRPIX', CDELT', 'CUNIT', 'CTYPE', 'RADESYS'
```
We should consider moveing the velocity aberration keywords as well. We don't currently correct for this but I imagine we will (similar to HST).
> tool to move WCS keywords from Primary to SCI extension

- jwst/datamodels/schemas/multispec.schema.yaml
- jwst/extract_1d/extract.py
- jwst/extract_1d/ifu.py
The right ascension and declination at the center of the extraction
region are now assigned to these new attributes.  These are the same
values as are returned by the wcs object, which is possible because
the coordinates are independent of row number in the table of extracted
values.  See issue #1034.
Additional metadata attributes have also been added to the MultiSpecModel.
These are based on attributes that were added not very long ago to the
MultiSlitModel, but not all are included in MultiSpecModel.  The extract_1d
step does not actually populate these yet.  See issue #1042.
> Add attributes slit_ra and slit_dec to MultiSpecModel.

- jwst/dq_init/dq_initialization.py
- jwst/flatfield/flat_field.py
- jwst/jump/jump.py
- jwst/lib/reffile_utils.py
- jwst/linearity/linearity.py
- jwst/ramp_fitting/utils.py
- jwst/saturation/saturation.py
- jwst/superbias/bias_sub.py
Fleshed out some more library functions for handling subarray extractions from reference file data. Also updated many (all?) of the steps that had been using private routines to use the new library functions. I believe they include enough error checking to handle all the bad reference files still lurking in CRDS.
All steps first call the function `ref_matches_sci` to see if the reference data match the science data and, if so, just use the reference data directly. This is more appropriate than testing whether the science data are full-frame or subarray (via `is_subarray`), because there are cases where science data can be subarray and yet still have matching (subarray) reference files and hence no extraction is needed. They have to match in more than just size. They must have an exact …
> More subarray library function updates

- docs/jwst/gain_scale/arguments.rst
- docs/jwst/gain_scale/description.rst
- docs/jwst/gain_scale/index.rst
- docs/jwst/gain_scale/reference_files.rst
- docs/jwst/pipeline/description.rst
- jwst/pipeline/calwebb_sloper.cfg
- jwst/pipeline/calwebb_sloper.py
- jwst/pipeline/gain_scale.cfg
- jwst/pipeline/ramp_fit.cfg
- jwst/ramp_fitting/ramp_fit_step.py
Several more updates related to the new gain_scale step.
- Added docs for the gain_scale step
- Updated the pipeline/calwebb_sloper docs to include gain_scale and persistence
- Added a gain_scale.cfg file and added an entry for it to the calwebb_sloper.cfg file
- Modified the ramp_fit step to no longer save the rateints model on its own, but rather return it (along with the rate product model) to the caller. This also means the ramp_fit step no longer applies gain_scale to the rateints model.
- Modified the calwebb_sloper pipeline to receive the rateints model from ramp_fit, apply the gain_scale step to both the rate and rateints models (if both exist), and save the rateints model to an output file
This new arrangement, which has the ramp_fit step return both the rate and rateints models, …
> Updates for gain_scale, including docs

- jwst/lib/reffile_utils.py
Added a patch to the reffile_utils function `ref_matches_sci` for the case of old full-frame reference files in CRDS that don't contain the SUBSTRTn or SUBSIZEn keywords. If those keywords can't be found, but the size of the ref file data array is 2048x2048, then just set the reference file subarray corner to 1x1 and size to 2048x2048. Otherwise it throws an error.
> Patch reffile_utils to handle old full-frame refs

- jwst/datamodels/schemas/core.schema.yaml
- jwst/mrs_imatch/mrs_imatch_step.py
It seems that models that have other WCSes in their meta currently cannot be serialized (reported by @jemorrison @nden and @drdavella). Since saving cube's WCS in input image's meta was a feature designed for the future, we can safely remove it until issues with schemas and asdf are ironed out and/or until there is an express need to save this WCS.
> Remove code that stores cube's WCS for background polynomials

- jwst/lib/reffile_utils.py
Change `log.errr()` to `log.error()` in one of the reffile_utils functions.
> Patch stupid typos in reffile_utils log messages

- jwst/extract_1d/extract.py
- jwst/extract_1d/ifu.py
Attributes such as the slit name, source name, and source location are now
copied from the input file (if it's a MultiSlitModel or MultiProductModel)
to the output MultiSpecModel file.  For other models (except CubeModel),
the slit name will be copied to the output, but other attributes are not
known or are not relevant, so they will not be assigned.  See issue #1042.
> Slit- and source-related keywords are copied to output.

- jwst/outlier_detection/outlier_detection_step.py
- jwst/stpipe/step.py
This pull adds a class level flag to Step named `prefetch_references`. 
Subclasses of Step that wish to skip the reference file prefetch (pre-caching) should define prefetch_references=False.   Other classes don't need to define it,  the default will do.
Also defined prefetch_references=False for OutlierDetectionStep which was the original motivation for this feature and use case.
> Support skipping reference file prefetch, OutlierDetectionStep

- jwst/datamodels/properties.py
All methods which modify the metadata had calls to _validate, except extend. This was an oversight that this fix resolves.
> Add validation to extend method

- jwst/datamodels/model_base.py
Datamodels adds the creation date of a file into the metadata when saving it. The current code adds the date to the metadata and then updates the format. This assumes that saving to the metadata does not  change the format. It's safer to update the format of the date and then add it to the metadata.
> Change creation date code

- jwst/wiimatch/lsq_optimizer.py
- jwst/wiimatch/match.py
This PR improves numerical stability of matching in ``wiimatch`` package by adjusting cutoff value for small Singular Values as a function of input data type.
CC: @jemorrison @hbushouse
> wiimatch: Improve numerical stability of lsq_solve

- jwst/pipeline/calwebb_tso3.py
The 1-D extracted spectra from the calwebb_tso3 pipeline are now
concatenated to an output MultiSpecModel, rather than to a ModelContainer.
See GitHub issue #1191.
Also, trailing blanks were deleted.
> The output model for 1-D extracted spectra should be MultiSpecModel

- jwst/pipeline/calwebb_tso3.py
- jwst/ramp_fitting/ramp_fit.py
The var_p_2d and var_r_2d arrays were too large.  Their allocation has been moved to within a loop over sections.
Some calling sequences have been simplified by eliminating variables that were never reference and by removing some variables from the tuple that is returned.
> Two arrays were the wrong size

- docs/jwst/extract_2d/main.rst
- docs/jwst/ref_file_doc_DMS_653/assign_wcs.rst
- docs/jwst/ref_file_doc_DMS_653/extract_2d.rst
- docs/jwst/ref_file_doc_DMS_653/extract_2d_reference_files.rst
- jwst/datamodels/__init__.py
- jwst/datamodels/image.py
- jwst/datamodels/multislit.py
- jwst/datamodels/schemas/image.schema.yaml
- jwst/datamodels/schemas/wavecorr.schema.yaml
- jwst/datamodels/wcs_ref_models.py
- jwst/extract_2d/extract_2d.py
- jwst/extract_2d/extract_2d_step.py
First cut at nirspec zero-point correction. As agreed on it is part of the extract_2d step. `ImageModel` and its schema were modified to include a `wavelength` array. This will eventually be changed after #1070 and #1031 or variants of these are merged.
Currently this only works on MSA data. Still need to 
[x ] add code for fixed slit  
[x ] make sure this runs only on point source
[ ] deliver reference files
[x ] docs
> Nirspec wavelength zero-point correction

- jwst/outlier_detection/outlier_detection_scaled_step.py
- jwst/outlier_detection/outlier_detection_stack_step.py
- jwst/outlier_detection/outlier_detection_step.py
- jwst/pipeline/calwebb_coron3.py
- jwst/pipeline/calwebb_image3.py
- jwst/pipeline/calwebb_tso3.py
- jwst/stpipe/step.py
Make filename suffixes `<ASN_ID>_crf` or `<ASN_ID>_crfints` to indicate cosmic-ray flagged 2c files.
- `outlier_detection_step` now updates to COMPLETE when finished
- the pipelines only write out 2c files if `meta.cal_step.outlier_detection` is COMPLETE
- calwebb_coron3 now uses `stpipe` `self.log` instead of importing logging separately
- the pipelines now use `stpipe` `self.save_model` to write out datamodel results.  This method has its own logging, so extra logging in the pipeline is not needed.
- remove `mk_filename` and `mk_prodname` from calwebb_coron3, this being replaced by the built-in `stpipe` infrastructure methods `save_model` and `output_basename`.
- add some extra suffixes to `stpipe` SUFFIX_LIST
Resolves #1159
> Correct Level 2c filenames

- setup.cfg
`[tool:pytest]` is a `pytest` 3 feature.
> Bump minversion of pytest to 3

- jwst/pipeline/tests/helpers.py
- jwst/pipeline/tests/test_calwebb_spec2_nrs_msa.py
- jwst/tests/helpers.py
New testing helper decorator `require_crds_context` for tests the require a certain level of crds context.
> Add crds context test check

- jwst/outlier_detection/outlier_detection.py
This set of changes defines correct output names (or at least full FITS filenames) for the intermediate products generated by the outlier_detection step.  It then writes them out to disk for as requested by the user.  
The use of `model.save()` was necessary since the `outlier_detection` class was not a sub-class of `Step`, and therefore did not have access to the `step.save_model()` method used elsewhere.  It also was not entirely appropriate, since these products are not officially supported/defined by the association naming rules anyway.  
This should address #1221.
> Define intermediate product outputs correctly

- jwst/resample/resample.py
This should address the problems originally described in Issue #1219 .
> Fix resample to not corrupt input WCS information

- jwst/stpipe/step.py
Fixes a bug in the Step corner case where input is a single `DataModel` but output is a `ModelContainer`.  Now each member of `ModelContainer` result has its `meta.ref_file` updated with the step-specific reference files when the step finishes.
Resolves #1217.
> Fix bug in Step where ModelContainer meta.ref_file wasn't handled

- jwst/jump/twopoint_difference.py
- jwst/lastframe/lastframe_sub.py
MIRI team members reported oddities in slope results from ramp_fit step, which have been traced back to problems with flagging and jump detection in the jump step. These updates fix the MIRI lastframe step so that it merges (bitwise-or) the DO_NOT_USE dq flag with any other existing dq flags, rather than just setting the DQ value equal to DO_NOT_USE (so that SATURATION flags set earlier don't get wiped out) and also updates the twopoint-difference jump detection method to look for SATURATION flags as part of other flags.
Mike Regan is working on other fixes to the twopoint-difference method that address more substantial problems with how the algorithm handles saturated pixels in general.
> Fix DQ flagging for jump step

- jwst/datamodels/schemas/guider_cal.schema.yaml
- jwst/datamodels/schemas/guider_raw.schema.yaml
- jwst/guider_cds/guider_cds.py
SDP is changing some of the definitions of the table extensions contained in FGS guider data products, so this updates our guider data models to stay in sync. It also updates updates the guider_cds step to copy over the table data from the input raw data model to the output cal data model, so that the table extensions get carried over to our level-2 products.
> Update handling of GS table extensions

- jwst/assign_wcs/util.py
- jwst/datamodels/schemas/multiproduct.schema.yaml
- jwst/datamodels/schemas/multispec.schema.yaml
- jwst/extract_1d/extract.py
- jwst/msaflagopen/msaflag_open.py
- jwst/pathloss/path_loss.py
- jwst/resample/resample_spec.py
- jwst/transforms/models.py
#1214 removes the `Slit.nshutters` attribute and adds `Slit.shutter_state` which is a string combination of `1` - open shutter, `0` - closed shutter, and `x` - main shutter.
This is a follow up PR which adds a function to compute the number of open shutters in a slitlet, `nshutters`, from `Slit.shutter_state` and uses that number in all steps which reference `nshutters` - `resample`, `pathloss`, `msaflagopen`, `extract1d`.
> compute nshutters from shutter_state

- jwst/assign_wcs/niriss.py
- jwst/assign_wcs/util.py
- jwst/lib/catalog_utils.py
- jwst/transforms/models.py
- jwst/transforms/schemas/niriss_grism_dispersion-0.7.0.yaml
- jwst/transforms/tags/jwst_models.py
This includes updates to make the NIRISS and NIRCAM calls into the gwcs object align as well as some sundry bug fixes:
* I changed the NIRISS wcs transforms for the grism traversal to init with the rotation angle instead of just the reference position of the filter wheel. The fwcpos in the input exposure is a known constant and users should not have to specify the value. This simplifies the model and creates the same function signature for the calls in both instruments 
* updates to the `GrismObj` and `SkyObj` tuples to use SkyCoords
> Updates for NIRISS WFSS WCS

- jwst/outlier_detection/outlier_detection.py
- jwst/outlier_detection/outlier_detection_scaled.py
- jwst/outlier_detection/outlier_detection_scaled_step.py
- jwst/outlier_detection/outlier_detection_stack_step.py
- jwst/outlier_detection/outlier_detection_step.py
- jwst/pipeline/resample.cfg
- jwst/resample/blend.py
- jwst/resample/gwcs_blot.py
- jwst/resample/resample.py
- jwst/resample/resample_spec.py
- jwst/resample/resample_spec_step.py
- jwst/resample/resample_step.py
A grab-bag of fixes, mostly to the `resample` modules:
- PEP8 fixes
- Remove `with()` block at beginning of `ResampleSpecStep.process()`
- Make `input_models` not a class attribute
- Make resample_step result var name consistent with other steps
- Write `meta.cal_step.resample` 'COMPLETE' correctly
- Simplify single input to `ResampleStep`
- Simplify single input to `ResampleSpecStep`
> Resample spec fixes

- jwst/datamodels/container.py
This modifies PR #1027 to have `persist=True` as the default when opening a `ModelContainer` of datamodels from disk, so that the following code works as expected:
```
In [7]: container = datamodels.open('mosaic_long_asn.json')
In [8]: container._models
Out[8]: 
['nrca5_47Tuc_primary_dither2_newpos_cal.fits',
'nrca5_47Tuc_primary_dither3_newpos_cal.fits']
In [9]: for model in container:
...:     model.meta.cal_step.resample = 'COMPLETE'
...:     
In [10]: for model in container:
...:     print(model.meta.cal_step.resample)
...:     
COMPLETE
COMPLETE
```
If `persist=False`, as was previously the default, the above code would not work, i.e. outside the `for ... in ...` block, each model in the container would not have any of its attributes updated.  Since this is very common in almost …
> ModelContainer persist=True as default

- jwst/datamodels/schema_editor.py
The title, when it is available in the model schema or keyword database, adds helpful information to the edit prompt. So I have added it. The title is mostly taken from the model schema, but I have used
the title in the keyword database when it is not available.
> Add title to schema editor output

- jwst/pipeline/calwebb_spec2.py
NIRSpec TSO observations, `BRIGHTOBJ`, should not go through `resample` and `pathloss`.
> BOTS in calspec2

- jwst/pipeline/resample_spec.cfg
- jwst/resample/resample_spec_step.py
- Add a `resample_spec.cfg` file for the spec version of the step, as it is has a different `suffix` than the `resample.cfg`
- Fix a bug in the reference file filename not getting passed to the resample routine
> Add .cfg for resample_spec; Fix ref_filename bug

- jwst/assign_wcs/util.py
- jwst/extract_2d/extract_2d.py
- jwst/extract_2d/grisms.py
- jwst/extract_2d/nirspec.py
This implements extract 2D for the NIRCAM and NIRIS grism modes, excluding NRC_TSGRISM since that data does not need to be processed through extract2d.
*note that the process takes too long to test an entire catalog, but specifying just 1 object for which all orders are extracted, the output model writes and validates with expected data.
> Initial grism mode extract2d implementation

- jwst/pipeline/calwebb_detector1.py
This updates the calwebb_detector1 pipeline to skip the persistence correction step for both MIRI and NIRSpec.
Fixes #1247.
> Skip persistence step for MIRI and NIRSpec

- jwst/outlier_detection/outlier_detection_scaled_step.py
- jwst/pipeline/calwebb_coron3.py
- jwst/pipeline/calwebb_tso3.py
These minor changes go along with the changes in PRs #1243 and #1246 to get the CALTSO3 and CALCORON3 regression tests to run successfully again. 
The fixes resolve problems with how the cal_step status was updated for CALTSO3, what variable name actually refers to the real output in a log message in when reporting on blending metadata in CALCORON3, and what gets used to update the output NIRISS MultiSpec model for NIRISS CALTSO3 output.
> Fix l3 regtests

- jwst/assign_wcs/util.py
- jwst/extract_2d/extract_2d.py
- jwst/extract_2d/grisms.py
This fixes a logic error which was extracting boxes calculated from the catalog which were entire off the detector.  I added logic to  `assign_wcs.util.create_grism_bbox` to exlude objects from the returned list which did not fall at least in part on the detector.  This could be updated in the future to  instead add a marker in the `GrismObject` for off detector sources which are still close enough to cast a spectrum onto the detector; this would aid in later contamination removal. For now I'm just excluding them. 
This also fixes an omitted signature parameter from the higher extract_2d call for the grisms.
> fix logic error for grism bounding box locations

- jwst/cube_skymatch/cube_skymatch_step.py
The model containers in cube_skymatch do not need to remain open after a loop, so I added the persist=False flag.
> Mark model containers as not persistent

- jwst/pipeline/calwebb_spec2.py
Updated the calspec2 pipeline to set the cube_build output_type argument to "multi", so that it always produces a single IFU cube. Fixes #1265.
> calspec2 should always create a single IFU cube

- jwst/datamodels/schemas/core.schema.yaml
- jwst/datamodels/schemas/subarray.schema.yaml
This allows `p_subarray` to be included in the `subarray` schema from the `core` schema, so that `datamodels.open(distortinon_file)` works.
@hbushouse We haven't updated the `core` schema to reference the individual schemas. So both the short schemas and their predecessors in the `core` schema exist. Should we update the `core` schema to use the smaller schemas in one of the 7.1 updates or in 7.2 ?
> allow additional properties in subarray

- jwst/extract_1d/extract_1d_step.py
If the input to the extract_1d step is a ModelContainer, extract_1d_step.py
now loops over the objects in the container and creates one MultiSpecModel
for each input.  If there is only one object in the input, the output will
be a MultiSpecModel; however, if the input contains more than one object,
the output will be a ModelContainer with one MultiSpecModel for each input
object.
If the input to the extract_1d step is not a ModelContainer, the step
will write a single MultiSpecModel as it did prior to these changes.
See issue #1264.
> Update extract_1d to handle ModelContainer as input

- jwst/extract_2d/extract_2d.py
- jwst/extract_2d/extract_2d_step.py
- jwst/extract_2d/grisms.py
- jwst/extract_2d/nirspec.py
This updates the extrac2d step to pass a dictionary of reference file names to the lower calls. 
The update passes for grisms, @nden should check I did the correct thing for nirspec
> updated extract2d to use reference file dictionary in step

- jwst/pipeline/calwebb_spec2.py
Quick-n-dirty hack to calwebb_spec2 to force the pipeline to construct the proper exposure-based file name for the s3d files produced by the cube_build step. Right now cube_build is constructing output file names internally by taking the input file name and appending additional fields like channel/band numbers/names (for MIRI) or filter/grating names (for NIRSpec). This is not appropriate for use in the calwebb_spec2 pipeline, where the root names of all products must be the same simple exposure-based root name.
For example, in the case of a MIRI IFUSHORT (channels 1+2) rate image, the output file name created by cube_build is `jw80500018001_02101_00002_MIRIFUSHORT_rate_ch1-2-medium_s3d.fits`. This type of name is only appropriate for level-3 processing. For level-2b, the name should …
> Fix calspec2 cube (s3d) file name

- setup.py
This has bitten me more than once while trying to reinstall the jwst pipeline for testing. This change just makes sure that `setup.py` doesn't attempt to install `scripts/__pycache__` as a script, if it exists.
> Prevent setup.py from trying to install __pycache__

- jwst/stpipe/pipeline.py
This fix addresses an issue with the test_coron3_1.py unit test where the PSF reference file is being overridden...  but CRDS still attempts to assign and precache a reference at the pipeline level which cannot be found.
It adds support for "skip" and "override" to the recent Pipeline level pre-caching change needed to consolidate multiple reference file calls into a single CRDS call per pipeline to improve error reporting.    reference_file_types at the pipeline level is limited to those Steps that are not skipped and those references within Steps that are not overridden.
> Pipeline precache skip override

- jwst/source_catalog/source_catalog.py
These properties will be used by the wide-field slitless spectroscopy pipeline.
CC: @sosey, @hbushouse
> Add sky bounding box properties to source catalog

- jwst/datamodels/fits_support.py
The extra_fits area in a datamodel is intended to hold the information from a file that is not contained in the model schema. It is temporary and should not be persisted to disk in the asdf extension
when saving a model file. This change removes the extra_fits section of a tree after loading the asdf extension from a file and before writing the asdf extension to a file. In addition, it checks to make
sure that the asdf extension is not saved in the extra_fits area.
> Remove extra_fits when readung and writing model file from disk

- jwst/ipc/x_irs2.py
- jwst/persistence/persistence.py
- jwst/refpix/irs2_subtract_reference.py
- jwst/saturation/x_irs2.py
Updated 3 modules in the ipc, refpix, and saturation steps to use new meta attribute names for the NIRSpec IRS2 readout keywords NRS_NORM and NRS_REF, in keeping with recent changes/additions to the core schema for these keywords.
> Update NIRSpec IRS2 keyword attribute names

- jwst/cube_build/ifu_cube.py
IFU cube WCS is saving 0-indexed crpix locations instead of 1-indexed FITS standard, so cube WCS is off by 1 pixel from correct values.  I've added this back into the metadata values, and verified performance against an idealized input array.
> Fix WCS crpix values in cube_build

- jwst/datamodels/irs2.py
- jwst/datamodels/schemas/irs2.schema.yaml
- jwst/refpix/irs2_subtract_reference.py
- jwst/refpix/refpix_step.py
The schema for the IRS2 reference file was changed to specify that the
columns are float32 rather than complex64.  irs2_subtract_reference.py
was modified to convert these values to complex.
See GitHub issue #1277 and JIRA ticket JP-181.
> Convert reference data from float to complex.

- jwst/lib/reffile_utils.py
Add additional logic to the reffile utilities to handle cases where old ref files don't have SUBSTRTn or SUBSIZEn keywords in them, by setting default values in the meta data if the data arrays are full frame.
> Update reffile utils for robustness

- .travis.yml
Travis has continuous problems with OSX testing. Here's a [blog post](https://blog.travis-ci.com/2017-09-22-macos-update) about this.
Since the code is mostly python, I suggest we disable the testing on osx for now. Any objections?
Should we disable python 27 as well and include python 3.6? (Python 3.6 is probably used in the nightly tests.)
> disable osx tests

- jwst/jump/tests/test_twopoint_difference.py
- jwst/jump/twopoint_difference.py
The program was using a wrong index to find the largest non-saturated difference. I added test to recreate the original problem that now work with the fix.
Also, the calculation of the median was not correct since it assumed all pixels in the integration had the same number of non-saturated groups.
An expected to fail test was added for a future feature to flag pixels adjacent to detected jumps.
> Fix for jump detection when there are saturated groups

- jwst/extract_2d/nirspec.py
Create a `MultiSlitModel` product with a single slit as long as exp_type is not `NRS_BRIGHTOBJ`.
`NRS_BRIGHTOBJ` creates a `CubeModel` as output. Still need to run some tests before merging.
> Create a MultiSlitModel when one slit is extracted.

- jwst/datamodels/schemas/multispec.schema.yaml
- jwst/extract_1d/extract.py
- jwst/extract_1d/extract1d.py
- jwst/extract_1d/extract_1d_step.py
Added code to get the spectral order number (needed for GRISM data, at least), and to include it in the call to the wcs function when appropriate.  The spectral order number is now saved in the output file.
Expanded the allowed extraction limits by a half pixel at each endpoint of the extraction width, if the width is the full width (or height) of the input 2-D image.  The previous limits stopped at the centers of the first and last pixels.
> Update to support WFSS/GRISM data

- docs/jwst/assign_wcs/exp_types.rst
- docs/jwst/assign_wcs/main.rst
- docs/jwst/assign_wcs/reference_files.rst
- docs/jwst/extract_2d/main.rst
Initial documentation for the NIRCAM GRISM, TSGRISM, and NIRISS WFSS modes for assign_wcs and extract_2d
> Add docs for the NIRCAM Grism and NIRISS WFSS wcs and extrac2d steps

- jwst/cube_build/cube_build_step.py
- jwst/cube_build/ifu_cube.py
Cube build forms the filenames. Now they are not overwritten by the step function when there are more than one IFUCube produced. 
However, when cube build is run from strun the files were not being saved and the end. So the fix is if
self.save_results =true   then cube_build will save the IFUCube to disk. In the various testing I have done I believe this is only the default case if run from strun - not the calspec2 or calspec3 pipelines. So for build 7.1 I hope this is acceptable.
> Outputnames

- jwst/assign_wcs/assign_wcs.py
Adds a few more spectroscopic modes to skip when calling update_s_region from assign_wcs. These modes just don't work with the current structure of that function (and may not ever).
Fixes #580.
> Skip update_s_region for some spectral modes

- jwst/datamodels/cube.py
- jwst/datamodels/image.py
- jwst/datamodels/schemas/cube.schema.yaml
- jwst/ramp_fitting/ramp_fit.py
- jwst/ramp_fitting/utils.py
Updated ImageModel and CubeModel definitions to use consistent array and extension names for poisson and read noise variance arrays. Also updated ramp_fit to use the new argument names when creating its output rate and rateints models. The current version of the models had an inconsistency in the names that was preventing the appearance of the variance arrays in the rate product.
In support of #596.
> Use consistent variance array names

- jwst/extract_1d/extract.py
There was a test on spectral order, requiring it to be not None and
greater than zero.  However, there are some modes that can have a
negative spectral order, so the test has been changed to allow that.
See issue #1297.
> Allow negative spectral order

- jwst/cube_build/__init__.py
- jwst/cube_build/cube_build_step.py
- jwst/cube_build/data_types.py
If output_dir is provided cube_build now adds that to the output name.
Eventually (build 7.2) we will probably want this to be done in the re-work Jonathan is working on
This address issue #1307 (which got lost in all the file naming updates)
> fix output_dir problem

- jwst/pipeline/calwebb_image3.py
- jwst/resample/resample.py
Syncs the `meta.wcsinfo` block with the `gwcs` object in the output of `Image3Pipeline`.  The FITS WCS keywords now perfectly describe the actual WCS contained in the `gwcs` object.
@larrybradley `source_catalog` step should now produce sources with correct RA and DEC by just reading the FITS WCS keywords.
Resolves #1292 for Level 3 image modes.
> Update FITS WCS keywords in Level 3 resampled image

- jwst/assign_wcs/assign_wcs.py
- jwst/extract_2d/nirspec.py
Only print S_REGION update value if it was actually updated.
Fixes #1355 .
Though how S_Region is updated for spectral data should be revisited for 7.2.
> S_REGION log message

- jwst/extract_1d/extract.py
The right ascension and declination near the middle of the slit were assigned to keywords, and in some cases the values were NaN, which is not valid for keyword values.
> Skip NaNs when finding RA and Dec for keywords

- jwst/datamodels/model_base.py
- jwst/datamodels/tests/test_wcs.py
The calling API for `fits_support.from_fits()` changed in #772.  This catches up with that change, and uncomments and fixes a test for it.
Resolves #1365 .
> Fix set_fits_wcs() so we can roundtrip from meta.wcsinfo to astropy.wcs object

- jwst/datamodels/fits_support.py
- jwst/lib/set_telescope_pointing.py
When a DataModel is loaded it has only the core schema, which happens to be
by a lucky coincidence) containing only Primary header keywords. When the schema
is extended with wcsinfo (or any other schema that points to an extension header), 
it now adds values which should be written to a SCI extension.
`fits_support.to_fits()` first calls `save_from_schema` and passes a "skeleton" HDUlist which 
has only a primary header. So a SCI extension is created in order to populate the wcs keywords.
Then `fits_support.to_fits` calls `_save_extra_fits`  and adds the real SCI extension.
I think this is in general a wrong approach and we were just "lucky" or "unlucky" that we didn't see
the problem so far. I think it would be better to create the complete FITS HDUList
and then run `save_from_schema`. …
> save extra_fits first

- jwst/datamodels/level1b.py
- jwst/datamodels/model_base.py
- jwst/lib/set_telescope_pointing.py
- scripts/set_velocity_aberration.py
The changes in #1370 resolved the issue of having two SCI extensions appear in files updated by set_telescope_pointing, but it still resulted in an output file that had the DATAMODL keyword set to 'DataModel'. This causes failures in the `calwebb_detector1` pipeline (and steps), because they all use the generic `datamodels.open()` function to load their inputs. It was loading them into a DataModel, which doesn't work. They need to load into a RampModel.
These changes have the effect of removing the DATAMODL keyword from the files produced by set_telescope_pointing, so that the subsequent calls to `datamodels.open()` rely on file structure info to correctly determine that they should use RampModel.
This also allowed for a change to set_telescope_pointing to have it use the appropriate …
> More fixes to get set_telescope_pointing to work

- jwst/datamodels/tests/test_level1b.py
- jwst/lib/tests/test_set_telescope_pointing.py
Updated set_telescope_pointing test to create the test file using a Level1bModel, instead of ImageModel, because now that set_telescope_pointing is loading the input into a Level1bModel we get a schema validation error using a file created as ImageModel.
Also set the current Level1bModel zeroframe test as an expected failure, because the model is no longer creating a zeroframe array if one doesn't exist in the input.
> Fix unit tests failures caused by #1372 changes

- jwst/datamodels/dqflags.py
Added a definition for REFERENCE_PIXEL to the list of pixel dq flag definitions, which will be used in MASK reference files to identify reference pixels, so that they can be excluded from downstream operations like resampling.
Note that I think this is the last new definition we can add without having to again bump up the dq datatype from uint32.
In partial fulfillment of #841.
> Add new REFERENCE_PIXEL dq flag definition

- jwst/datamodels/schemas/multislit.schema.yaml
Using `astropy.fits.info(filename)` with `extract_2d` output file does not show the WAVELENGTH extension in the file, although it is present and accessible within the model. This is forces it to show as a FITS extension.
> force WAVELENGTH array to show in fits.info()

- jwst/datamodels/schemas/core.schema.yaml
One more header change to lump in with all the others today. Rename the CAL_SVN keyword to CAL_VCS and update the comment. Fixes #57.
> Update CAL_SVN keyword [skip ci]

- jwst/dark_current/dark_current_step.py
- jwst/dq_init/dq_init_step.py
- jwst/group_scale/group_scale_step.py
- jwst/ipc/ipc_step.py
- jwst/jump/jump_step.py
- jwst/lastframe/lastframe_step.py
- jwst/linearity/linearity_step.py
- jwst/persistence/persistence_step.py
- jwst/pipeline/calwebb_detector1.py
- jwst/ramp_fitting/ramp_fit.py
- jwst/ramp_fitting/ramp_fit_step.py
- jwst/refpix/refpix_step.py
- jwst/rscd/rscd_step.py
- jwst/saturation/saturation_step.py
- jwst/superbias/superbias_step.py
These changes update the `calwebb_detector1` pipeline and (nearly) all of its steps to explicitly open the input data as a `RampModel`, rather than using the generic `datamodels.open()` function. All steps are setup to work only on a `RampModel` in that they either need to use data spread across multiple groups or integrations, or rely on data arrays like `groupdq` and `pixeldq`, all of which are only present in a `RampModel`. There is no way, therefore, that any of these steps could ever be applied to any kind of simpler model, like `ImageModel` or `CubeModel`, hence there's no reason to allow for any kind of input other than `RampModel`.
The only step in the `calwebb_detector1` pipeline that does not work on 4-D `RampModel` data is the final step `gain_scale`, which is applied after the …
> Update calwebb_detector1 and steps to use RampModel input

- jwst/stpipe/crds_client.py
- jwst/stpipe/pipeline.py
- jwst/stpipe/tests/test_crds.py
This is a response to Jeb's performance issues when attempting to multi-process 5 or so MIRI associations concurrently.   I believe any remaining CRDS performance issues are in data model i/o or garbage collection.  This addresses that.   This changes only the crds_client glue code.
**The primary optimization is to cache the header parameters CRDS extracts from incoming data models and uses for bestrefs matching.**   Since the cache is keyed by filenames,  this scheme can be defeated by similar files with different names (pipeline progression?) or by datasets that change in ways that affect bestrefs matching (only original header counts...)   Nevertheless,  potentially it can reduce CRDS data models related file i/o by 3:1,  maybe 4:1.   This does not reduce Step file i/o.   This does not …
> Optimize reference fetch

- .travis.yml
UPDATE: Now that Howard concluded the timeout was Travis' fault. I updated this PR to use Numpy "stable" (this is set by `ci-helpers` to latest Numpy release), astropy dev for PY3 (same as pandokia), and Python 3.6 (why not?). And also `flake8` like #1377 but still as allowed failure.
Python 3.6 change log: https://docs.python.org/3/whatsnew/3.6.html
Numpy 1.13 change log: https://docs.scipy.org/doc/numpy-1.13.0/release.html
~~Similar to #1391 but with some Travis CI voodoo.~~
> ENH: Update Numpy, Python, and use astropy dev for PY3

- jwst/stpipe/crds_client.py
The recent change to optimize CRDS model opens and garbage collection removed the ability for Step.get_reference_file() to handle filenames instead of open models,  intentionally.  Add it back since extract2d is passing filenames and others might be as well.
> crds_client.get_reference_file() support input filenames vs. models

- docs/jwst/extract_1d/description.rst
- docs/jwst/flatfield/main.rst
Support for GRISM data in `extract_1d` was mentioned.  The `flat_field` step can process NIRSpec imaging data and BRIGHTOBJ data.
> Update documentation for extract_1d and flat_field

- jwst/resample/gwcs_blot.py
- jwst/resample/gwcs_drizzle.py
- jwst/resample/resample.py
- jwst/resample/resample_spec.py
- jwst/resample/resample_utils.py
Implements new method for computing the output frame wcs for NIRSpec from the intermediate `slit_frame` in the WCS transform.
Resolves #1006
> Fix NIRSpec resampling output frame

- jwst/srctype/srctype_step.py
#1405 introduced a bug in the srctype_step module. The "result" is not a copy of input_model, hence it goes out of scope when exiting a "with datamodels.open() ..." block, so the return statement ends up returning a closed model, which throws an error in stpipe. Removed the "with" block and just open the input directly. No need to close the input model, because it is the (updated) model that gets returned.
> Fix bug in srctype_step

- jwst/pipeline/calwebb_tso1.cfg
Add a configuration file for the detector1 pipeline that is setup to skip certain steps for TSO exposures. The new cfg file is `calwebb_tso1.cfg.` By default the steps ipc, lastframe, and persistence are skipped.
Fixes #1400.
> Add TSO configuration for calwebb_detector1 [skip ci]

- jwst/pipeline/calwebb_image2.cfg
- jwst/pipeline/calwebb_image2.py
This enables resampling in CALIMAGE2 and now requires a VALID WCS in order for the resampling to work.
> initial version with resample

- jwst/outlier_detection/outlier_detection.py
- jwst/outlier_detection/outlier_detection_scaled.py
- jwst/outlier_detection/outlier_detection_spec.py
- jwst/resample/resample.py
- jwst/resample/resample_spec.py
- jwst/resample/resample_step.py
- jwst/resample/resample_utils.py
- Move `build_driz_weight` out of the `ResampleData` class and into `resample_utils`, reverting it back to being a function so it can easily be called by `outlier_detection` when needed.
- Put `make_output_wcs back` into `resample_utils`.  It had inadvertently been deleted in #1412.
> Move build_driz_weight to resample_utils

- jwst/assign_wcs/assign_wcs.py
- jwst/assign_wcs/niriss.py
- jwst/assign_wcs/util.py
- jwst/extract_2d/extract_2d_step.py
- jwst/extract_2d/grisms.py
- jwst/transforms/models.py
Still testing this out but wanted to run it through travis. The updates generally include:
- some added logging information that's useful
- logic to correct the dispersion directions, though I haven't decided if this is correct yet, still testing
- rejection of completely off-detector orders and marking of partial orders
- rounding for the order bounding boxes to int
- addition of the grism_objects parameter optional parameter to the extract_2d step
> Grism mode updates for extraction

- jwst/pipeline/calwebb_image2.py
Modify calwebb_image2 to only apply the resample step to exposures from the normal science imaging modes of MIRI, NIRCam, and NIRISS. This excludes image-like modes such as coronagraphy, focus, target-acq, etc.
> Limit calimage2 resampling to normal imaging modes

- jwst/pipeline/calwebb_dark.py
Updated the calwebb_dark pipeline to open the input as a RampModel, just as we did in #1389 for the calwebb_detector1 pipeline. Should've made this update along with that PR.
> Update calwebb_dark to open input with RampModel

- jwst/datamodels/schema_editor.py
The schema editor compares the model schemas in the datamodels directory to the keyword databse files and either reports the differences (if list=True) or edits the model schemas to match the keyword database (if list=False.) Previously the schema editor did not add fields in the keyword database to the model schemas, as there was no information about which schema to add the fields to. But the decision was made to all keywords to the core schema, so now the schema editor does that. The code to delete model schema fields, edit them, and rename them is bascially the same as before. However, when modifying the existing code some bugs were found and fixed and a
number of changes to streamline the existing code were made as well. So the code is considerably different from the pervious version.
> Update schema editor to support adding new schema fields

- jwst/lib/reffile_utils.py
The function `ref_matches_sci` has been enhanced to set default values in the reference file data model when the SUBSTRTn or SUBSIZEn keywords are missing from a reference file and the reference file is full-frame, so that subsequent functions like `get_subarray_model` can take advantage of those default values and prevent crashes.
Fixes #1438.
> Make ref_file functions more robust against missing keywords

- jwst/outlier_detection/outlier_detection.py
- jwst/pipeline/calwebb_coron3.cfg
- jwst/pipeline/calwebb_coron3.py
These changes address issue #1184 and will enable 'resampling' in this pipeline with full use of the new unified outlier_detection interface.  The full set of changes in this PR include:
- **BUG FIX:** outlier_detection case where resampling was turned off used references to metadata instead of copies to create median image datamodel. This was fixed to use model.update.  
- PEP8 updates to the formatting of the code (based on Flake8 and pylint checks)
- Change use of outlier_detection to call the unified interface
- Delete 'skip' command from default pipeline config file
These changes were tested interactively against the test_coron3_1 regression test before submission, after turning on resampling in the test.
> Resample coron3

- jwst/datamodels/fits_support.py
Data stored in the extra_fits area can either be an image or a bintable. Previously the code assumed it was an image. This update pulls some code that was in _make_new_hdu into a new function,
_get_hdu_type, and calls it from _make_new_hdu and _make_hdu. This ensures that whenever a new hdu is written, the code first checks the type of the data (if present) and selects the proper class to create the new hdu.
> Get hdu type from value when saving extra_fits data

- jwst/pipeline/calwebb_image2.py
Quick fix for #1449, by calling .update on the resampled result model before saving it in the calwebb_image2 pipeline. A real fix should be done within the resample step itself in the future.
> Update meta data in calimage2 resampled product

- jwst/outlier_detection/outlier_detection.py
This PR corrects the failure seen in the calimage3 regression test where the WCS was not defined for the median image.  
The problem turned out to be caused by relying on update to add the WCS from the input model to the newly created updated datamodel.  However, since the WCS is not defined in the schema for an ImageModel (or any model for that matter), the update operation does not see the WCS attribute and therefore does not copy it over.  This behavior makes perfect sense for model.update() and should simply be documented prominently.
> Add WCS to median_model

- jwst/extract_1d/extract.py
For grism data (only), self.wcs.forward_transform is assigned to local
variable transform outside the loop over pixels, and transform is called
(instead of self.wcs) inside the loop over pixels.  See issue #1468.
> Assign wcs.forward_transform outside the loop

- jwst/pipeline/tweakreg.cfg
`searchunits` is not longer in tweakreg spec, so it should be removed from the default config file.
> Remove searchunits from tweakreg.cfg

- jwst/tweakreg/tpcorr.py
As reported by @jdavies-st , `TPCorr` model does not work with 2D (or higher dimensionality) inputs. This PR takes care of this issue.
> Make TPCorr model to work with n-dimensional inputs

- jwst/transforms/tpcorr.py
- jwst/tweakreg/__init__.py
- jwst/tweakreg/wcsimage.py
@nden suggested moving `TPCorr` to the `transformations` package where it is going to reside with other JWST-specific transformations.
This PR is the first step of actually moving `TPCorr` to the package. Schema update will be done in a separate PR.
> Move TPCorr to transformations package

- jwst/datamodels/model_base.py
- jwst/datamodels/util.py
If the DATAMODL keyword is not found in the primary image header, DataModel and its inheritors add it. If an image is opened with the open() function, and DATAMODL is not set, open() should not set it, because the class it chooses is only a best guess. So this update sets model_type to None after opening the image, so DATAMODL is not written to the header. In addition, when an image is opened with the base class, DataModel, DATAMODL should not be set, as there is no image of
the base type. So this update also sets model_type to None in that case. This update also moves all the code that sets model_type to __init__ from on_save, so that code which calls DataModel can override model_type.
> Unset model_type when opening images as DataModel and with open

- jwst/pipeline/calwebb_tso3.py
This PR fixes a problem with CALTSO3 where the WCS was not getting passed along when the input CubeModel was transformed into a ModelContainer.  The error arose from use of .update() which does NOT include an update for the WCS or any other element not defined explicitly in the schema.  
The update can be seen to work when the regression tests `test_nrc_tso3_1` and `test_nrc_tso3_2` start working again, since they are trying to access the WCS when performing outlier_detection and it was not provided during the conversion performed by CALTSO3.
> Add WCS to CALTSO3 ModelContainer

- .travis.yml
- jwst/transforms/jwextension.py
- jwst/transforms/tags/jwst_models.py
We just moved astropy-specific tag implementations from asdf to the astropy core repository. This required a few minor changes to gwcs and to the JWST pipeline. This PR should account for those changes, assuming that the latest versions of asdf, astropy, and gwcs are pulled in by the travis build.
These changes exposed a minor issue with `JWSTExtension`, which has been addressed in this PR as well.
> Account for recent changes to asdf and astropy

- jwst/transforms/jwextension.py
- jwst/transforms/jwst_types.py
- jwst/transforms/tags/jwst_models.py
- jwst/transforms/tags/tests/test_models.py
Transforms used in the pipeline should inherit now from JWSTTransformType. They don't need to be added to the JWSTExtension any more as this is done automatically.
> define a JWSTTransformType, fix typos, add tests

- jwst/datamodels/schema.py
- scripts/move_wcs.py
A new method `build_schema2fits_dict` added.  It does the mirror image of the `build_fits_dict`.  It creates a dictionary that maps flattened metadata attributes to a tuple containing their FITS keyword and FITS HDU location (if any).
> Add build_schema2fits_dict() method for datamodels

- jwst/persistence/persistence.py
The `get_subarray` method in persistence.py used `if "dq" in ref:` to check whether a reference file model has a dq array.  This no longer works, so it has been changed to `if hasattr(ref, "dq"):`.
> Change syntax for checking for existence of DQ

- jwst/extract_1d/extract.py
The copy_keyword_info function used `if "slitlet_id" in slit:` to check whether a slit object has a keyword corresponding to `slitlet_id`.  This no longer works, so it has been changed to `if hasattr(slit, "slitlet_id"):`.
See issue #1514.
> Change syntax for checking for metadata.

- jwst/extract_1d/extract.py
- jwst/extract_1d/extract1d.py
Remove `from __future__ import ...` statements.
The `round` function was used in two places in function `_extract_colpix` in extract1d.py.  Instead of trying to emulate Python 2 behavior of `round`, `_extract_colpix` was changed to use `math.floor(x + 0.5)`.
> Remove references to Python 2

- jwst/flatfield/__init__.py
I had forgotten this file.  I had a `from __future__ import absolute_import` statement, which has now been removed.
> Remove the import in __init__.py.  See issue #1392.

- jwst/stpipe/__init__.py
- jwst/stpipe/cmdline.py
- jwst/stpipe/config_parser.py
- jwst/stpipe/function_wrapper.py
- jwst/stpipe/hooks.py
- jwst/stpipe/linear_pipeline.py
- jwst/stpipe/log.py
- jwst/stpipe/pipeline.py
- jwst/stpipe/step.py
- jwst/stpipe/subproc.py
- jwst/stpipe/tests/__init__.py
- jwst/stpipe/tests/steps/local.py
- jwst/stpipe/tests/test_crds.py
- jwst/stpipe/tests/test_logger.py
- jwst/stpipe/tests/test_pipeline.py
- jwst/stpipe/tests/test_saving.py
- jwst/stpipe/tests/test_step.py
- jwst/stpipe/utilities.py
Note: The `configobj` folder is third-party code and has been left
untouched. If the need is felt to deal with this, the code should
first be updated from the source.
WIP #1392
> Remove Python2 compatibility from stpipe

- jwst/pipeline/calwebb_detector1.py
The ramp_fit step normally returns two objects.  When ramp_fit is run
in calwebb_detector1, however, the user can specify that the step be
skipped, in which case the step will return just one object, the input
model.  This will fail in the pipeline because the code explicitly
receives two objects from the step, but only one was returned.  This
can be (temporarily) fixed by checking the `skip` flag.  See issue #1532.
> Check whether ramp_fit was skipped

- docs/jwst/coron/main.rst
- docs/jwst/pipeline/description.rst
- jwst/pipeline/calwebb_coron3.py
- jwst/pipeline/calwebb_tso3.py
Pipeline documentation has been updated to include a basic description of the CALTSO3 and CALCORON3 pipelines.  This update included making some PEP8 corrections to calwebb_tso3 while also making the docstrings a little more user-friendly.  
The documentation also implements cross-references to the Step API's for all the steps called by each of the pipelines.  These cross-references will also take advantage of the updates implemented in PR #1516 to provide improved documentation for the outlier_detection steps used by these pipelines.  
Finally, the coron3 step documentation was also updated to provide API references that could be called from the pipeline documentation.
> Update pipeline docs

- jwst/extract_1d/extract.py
The extract_1d step computes the wavelength at each pixel by calling the
WCS function.  If the wavelength attribute (FITS WAVELENGTH extension) exists
and is populated (not all zeros), that should be used for the wavelengths
instead.  See issue #1374.
> Use wavelength array in preference to wcs function.

- jwst/extract_1d/extract.py
When there is no WAVELENGTH extension in the input file, the shape of the
wavelength attribute is apparently (0, 0) rather than being the shape of
the science data.  Using .min() or .max() on such an array fails.
See issue #1374.
> Modify test for nonexistent WAVELENGTH extension

- jwst/assign_wcs/tests/test_miri.py
These were commented out because the CDP-6 reference files were not in CRDS. This PR modifies the tests to match the changes in the CDP-6 ref files and enables them again.
> enable MIRI MRS tests

- jwst/outlier_detection/outlier_detection_step.py
The default suffix defined for outlier detection intermediate products appears to have been mis-assigned previously.  This PR resets the default so that 's2d' is used for spectroscopic data and 'i2d' for imaging, as opposed to the exact opposite assignment delivered in B7.1.
> Correct? default suffixes assigned to TSO output products

- jwst/wiimatch/lsq_optimizer.py
- jwst/wiimatch/match.py
It seems that equations that need to be solved occasionally are poorly conditioned and standard `numpy.pinv` fails to find an accurate solution. This PR adds a new method that solves a better-behaving reduced system of equation using LU decomposition.
This adresses the problems described in https://github.com/STScI-JWST/jwst/issues/1522
When testing this new method, it seems to be slightly more reliable than previous method but it also can be made to fail. It is recommended to keep the polynomial order as low as necessary.
CC: @hbushouse
> Improve the method for solving equations

- jwst/extract_1d/extract.py
If the wavelength attribute (WAVELENGTH extension) exists, zero or negative values are set to NaN in a copy of the array, and `numpy.nanmean` is used to collapse the 2-D wavelength array to 1-D.  See issue #1562.
> Ignore NaNs when converting 2-D wavelength array to 1-D

- jwst/assign_wcs/assign_wcs.py
- jwst/assign_wcs/tests/test_miri.py
- jwst/assign_wcs/tests/test_nirspec.py
- jwst/assign_wcs/tests/test_wcs.py
- jwst/datamodels/schemas/wcsinfo.schema.yaml
This supersedes #1499 with the only difference here is that the newly enabled MIRI MRS tests were fixed to provide default values. #1499 was previously approved.
> second attempt at removing WCS defult values

- jwst/wiimatch/match.py
The default given for parameter `solver` was `LU`.
However, according to comments and code, only `RLU` and `PINV`
are supported.
Though it seems to be just a typo and the intent was for `RLU`
to be default, I went with `PINV` because then the code would
actually run for MRS test data.
> Fix default value for sovler parameter to match_lsq

- jwst/wiimatch/lsq_optimizer.py
When only one (single) image is being matched, `wiimatch.lsq_optimizer.rlu_solve()` crashes instead of returning a banal solution. This PR adds a check for the number of input images and when only one image is detected, `rlu_solve()` will return an array of zeros as coefficients of the background polynomials.
> Make wiimatch work with a single input image when using rlu_solve

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
Adds a description of how to install a release version vs development version.
Adds a small section (needs to be expanded) on how to make contributions as well as what the various branches are used for.
Also adds "code of conduct" statement.
> contributing guidelines and code of conduct

- jwst/transforms/tags/tests/test_models.py
Lim said we should drop this,  believe it is general advice not critical to any specific problem or B7.1 release.
> Remove astropy.test.helper.pytest

- docs/jwst/persistence/description.rst
One of the equations was so long that it was truncated.  Added some alignment and explicit line breaks to try to fix that.  Also, an inline "Delta t" was missing the backslash before "Delta".
> Fix equation

- jwst/pipeline/calwebb_tso3.cfg
The calwebb_tso3 pipeline was updated in the final B7.1 delivery to no longer use separate outlier_detection_scaled and outlier_detection_stacked steps, but the default .cfg file was not updated to reflect this change. The calwebb_tso3 pipeline then fails, when executed using the default .cfg file, because the step outlier_detection_scaled is no longer defined in the pipeline.
This update brings the default calwebb_tso3.cfg file in synch with the latest calwebb_tso3.py pipeline module.
This error wasn't discovered via the calwebb_tso3 regression tests, because the tests were still using an old version of the calwebb_tso3.cfg file that didn't have this problem. Mike Swam discovered the problem during DMS testing of the B7.1 delivery.
> Update calwebb_tso3.cfg to match pipeline

- jwst/datamodels/tests/test_fits.py
- setup.cfg
The storage of the ASDF tree in either an `ImageHDU` or another type of HDU is an ASDF implementation detail, and should not be tested here.  This allows for the proposed change in [ASDF PR 412](https://github.com/spacetelescope/asdf/pull/412) to put the ASDF tree in a `NonstandardExtHDU` instead of an `ImageHDU`.
> Modify datamodels test to not check for ASDF tree in ImageHDU

- jwst/datamodels/wcs_ref_models.py
The MIRI MRS code to create CRDS reference files is crashing using the latest version of the pipeline.  On further investigation, this seems to be because there is no 'populate_meta' function for the RegionsModel MIRI-only reference file within the datamodel.  Since this function exists for all other reference file types I've added it for the Regions files as well, which seems to fix the problem so that MRS reference files can be created again.
> Adding populate_meta to WCS RegionsModel

- jwst/resample/resample.py
This is a quick-n-dirty fix (till @stsci-hack can fix it properly in blendheaders) that gives the proper model_type value to the data model returned from blendheaders, when it's called from the resample step. The resampled output model starts out with the proper model_type, but it appears that blendheaders is replacing it with the model_type of the input image(s) that it's blending. This workaround just saves the output model_type before calling blendheaders and then restores that original value after blendheaders is finished. This has been affecting the resampled output product from the calwebb_image3 and calwebb_coron3 pipelines.
> Fix blendheaders output datamodel value

- jwst/datamodels/model_base.py
Right now, when loading schemas in `datamodels`, the ASDF built-in url mapping is not actually being used. Instead, JWST is inadvertently making use of the `GWCSExtension`, which currently has the same url mapping as ASDF's built-in extension.
The `GWCSExtension` url mapping is about to change, and so JWST needs to actually make sure that ASDF's built-in url mapping is being used when loading schemas. The easiest way to do this is to create an `AsdfFile` object using JWST's list of extensions, and use that object's resolver when loading schemas.
> Make sure ASDF's built-in url mapping is used when loading schemas

- jwst/msaflagopen/msaflagopen_step.py
Quick fix to get regression tests running, while @stscirij works on a permanent fix. This handles the fact that the v2v3 reference file was recently retired from use, but the step was still trying to find a name for it, which is now None.
> Fix msaflagopen for missing v2v3 ref file

- jwst/transforms/tpcorr.py
- jwst/tweakreg/imalign.py
- jwst/tweakreg/tweakreg_step.py
- jwst/tweakreg/wcsimage.py
- jwst/tweakreg/wcsutils.py
This PR adds support for "tweaking" the WCS of groups of images: sets of images that must be adjusted together as one large image. This PR addresses https://github.com/STScI-JWST/jwst/issues/1520 and also adds a couple of bug fixes.
CC @hbushouse
> Add support for tweaking *groups* of images that "move" together

- jwst/jump/yintercept.py
Minor update to the now obsolete yintercept method in the jump step. Fixes #1022.
> Fixed bug in yintercept noise calculation

- jwst/flatfield/flat_field.py
Updated the flat_field step (the part for non-NIRSpec data) so that zeros in the flat reference image are reset to a harmless value of 1.0 and set a NO_FLAT_FIELD DQ flag for the corresponding pixels.
Fixes #857.
> Trap zeros in flat_field reference data

- jwst/srctype/srctype.py
Updated the source_type step to check the setting of the BKGDTARG (background target) keyword and if it's set to True, then set the source type to EXTENDED for NIRSpec IFU exposures.
Fixes #1151.
> Set srctype to extended for NRS_IFU background exposures

- jwst/datamodels/schemas/drizproduct.schema.yaml
- jwst/datamodels/schemas/multiproduct.schema.yaml
- jwst/datamodels/schemas/multislit.schema.yaml
- jwst/extract_2d/grisms.py
- jwst/extract_2d/nirspec.py
- jwst/resample/resample_spec_step.py
Several updates to allow propagation of the BUNIT keyword in the SCI and ERR (where it exists) extensions of spectral _cal and _s2d products. Some steps were already setup to copy the value from the input model, but it wasn't showing up because BUNIT wasn't defined in the output model schema, so those schemas have been updated to include it. Others needed updates to the steps to copy over the input values, especially those that create MultiXXXX products as output.
This seems to now cover all cases mentioned in #63. Any spectral mode that produces a regular ImageModel or CubeModel as output was already copying the values via a call to output_model.update(). Those that produce a MultiSlit or MultiProduct model now work via these updates.
The DrizProduct schema was also updated to include …
> Updates to populate BUNIT in spectral products

- jwst/associations/__init__.py
- jwst/associations/association.py
- jwst/associations/lib/dms_base.py
- jwst/associations/tests/test_level3_basics.py
Preparation for work on issue #1442.
Test setup for ensuring that target acquisitions are included in all associations. However, actual implementation will require a refactor of constraint handling. This will appear later.
> Test setup and minor rule constraint simplification

- jwst/guider_cds/guider_cds.py
- jwst/guider_cds/guider_cds_step.py
Removed python2 dependencies and added a line to update the value of BUNIT in the output product, to reflect the fact that the output data are in count rates (DN/s).
> guider_cds updates for BUNIT and python2 dependencies

- jwst/extract_1d/extract_1d_step.py
Under some conditions (errors), the input model can be returned, and in those cases it is the open model that will be returned.  Otherwise, the input model will be closed before the newly created output model is returned.
> Close the input model.  See GitHub issue #1636.

- docs/jwst/skymatch/README.rst
Document `dqbits` parameter of the `skymatch` step - see https://github.com/STScI-JWST/jwst/issues/1592
> Add doc for dqbits in the skymatch step

- docs/jwst/extract_1d/description.rst
- docs/jwst/extract_1d/reference_files.rst
- jwst/extract_1d/extract.py
In order to support the option to extract more than one spectral order, the reference file can have a "spectral_order" key in addition to the "id" key.  While "id" is still the primary key to be matched for selecting the relevant information, "spectral_order" can now be used as a secondary selection criterion.  If there is an aperture in the reference file for which the "id" key matched, that's considered to be (at least) a partial match.  If there is no "spectral_order" key for this "id", or if "spectral_order" also matches, that's regarded as an exact match.  A spectrum will be extracted only if the match is exact.  If the match is partial, the specified (but not found) spectral order will be skipped; if there's not even a partial match, that's an error.
A new exception has been …
> Allow 1-D spectral extraction for multiple spectral orders.

- jwst/assign_wcs/nirspec.py
- jwst/assign_wcs/tests/test_nirspec.py
The wavelength range for a Nirspec observation is determined by the `filter_grating` combination (the entries are listed in the wavelengthrange reference file. Occasionally, a combination is not in the wavelengthrange file, e.g. `ARGON_G395M`.
Previously, in this case, the full spectral range was used. This leads to incorrect results, e.g. in the above case, because all 5 slits are projected on NRS1, while in reality SB1 is not projected. 
This PR changes the logic and uses the wavelength range of one of the available combinations for the specific grating. With some exceptions (which I think are taken care as special cases in the code) this should be correct, as the wavelength range is determined mostly by the grating.
Fixes #1677.
In addition fixed a Resource warning coming from asdf and …
> fix wavelength range

- jwst/resample/blend.py
- jwst/resample/resample.py
This includes the changes to the resample step to replace use of fitsblender with the new model_blender package.  It can serve as an example of how to use this new code, since the API is slightly different from the interface provided by fitsblender.
> Update to resample step to use model_blender

- jwst/datamodels/fits_support.py
- jwst/datamodels/model_base.py
- jwst/datamodels/properties.py
- jwst/datamodels/tests/test_schema.py
- jwst/datamodels/util.py
This update modifies the interface for creating new datamodels and the generic open function. The new interface has two optional parameters, pass_invalid_values and strict_validation, which control the handling of schema errors. There are also two environment variables PASS_INVALID_VALUES and STRICT_VALIDATION, which if set, override the values of the parameters. The default values of both parameters are False. When the metadata values are read from a FITS file or modified in a script, the value is checked against the schema for that model. If the value does not agree with the schem an exception is thrown if strict_validation is set to True or a warning is issued if strict_validation is set to False. If the value does not match the schema, the metadata is set to that value if …
> Modify error handling for schema validation errors

- jwst/pipeline/calwebb_tso3.py
The calwebb_tso3 pipeline had a couple of problems with the naming of the level-2c (outlier_detection results) products. First, it was using the level-3 product name from the ASN file as the base name. This was due to having self.output_basename populated at the very beginning of the pipeline, which means save_model was using that instead of the value of model.meta.filename in the model that was passed to it. I moved the population of self.output_basename later in the pipeline flow (after outlier_detection), so that save_model now uses the model filename, which is the original level-2b input file name.  Second, we then need to add the association-id from the ASN file as part of the level-2c filename suffix. We now get proper exposure-based level-2c file names for the results of the …
> Fix caltso3 level-2c file names

- jwst/jump/twopoint_difference.py
- jwst/photom/photom.py
Added a log message to jump/twopoint_difference to indicate loop over integrations and updated a log message in photom to include spectral order number along with the slit.
> Additional log info for jump and photom

- jwst/assign_wcs/util.py
- jwst/transforms/models.py
#1659 implemented a change which makes sure that sky footprints always report RA as a positive number .
However it change was implemented in the wrong place. The `V2V3ToSky` model is used also for its inverse and the positive RA (or first coordinate) was enforced also for V2 values when the inverse transforms is run.
This PR moves the positive RA enforcement to the footprint calculation and reverses #1659.
sigh...
> move check for negative ra to footprint calculation

- jwst/pipeline/skymatch.cfg
- jwst/skymatch/skymatch.py
- jwst/skymatch/skymatch_step.py
This PR should address https://github.com/STScI-JWST/jwst/issues/1715 in that now `skymatch` will no longer throw an exception when either images do not intersect at all or when there are no valid (=non-flagged) data in the overlap regions. Instead, `skymatch` will print a warning message and will set sky values to `0.0`.
> Make skymatch quietly report lack of data

- jwst/assign_wcs/util.py
#1722 was not quite right. `WCS.footprint` is a (3, 3) array for spectral observations. Also there was a numerical typo - we are looking for negative value of RA, not values < 360.
> fix s_region

- jwst/associations/__init__.py
- jwst/associations/asn_from_list.py
- jwst/associations/lib/dms_base.py
- jwst/associations/lib/rules_level2_base.py
- jwst/associations/lib/rules_level3_base.py
- jwst/associations/tests/test_asn_from_list.py
When force creating associations with `asn_from_list`, add ability to specify the association candidate. Necessary since Level2 associations only validate with `OBSERVATION` or `BACKGROUND` candidates.
Resolves #1725
> Add association candidate to asn_from_list

- jwst/datamodels/schemas/core.schema.yaml
- jwst/model_blender/tests/test_blend.py
Regression test results highlighted a couple of model blender rules that aren't correct. In particular, don't sum the EFFINTTIM, because the time per integration is constant across all exposures (it's OK to sum EFFEXPTIM). Also don't sum RESETS. The number of resets is also constant per exposure.
> Modify a few model blender rules

- jwst/assign_wcs/util.py
- jwst/pipeline/calwebb_spec2.py
addresses #1738.
This updates the WFSS section of the Spec2 pipeline to look for the name of the source catalog only if the datamodel is not populated with a value for  datamodel.meta.source_catalog.filename, which is read from the SCATFILE FITS keyword. 
Do the science teams have a preference? What if an association is given that has a catalog name AND the datamodel also specifies a catalog name, which should take precedence?
> Allow catalog to be passed to pipeline from datamodel instead of association

- jwst/datamodels/properties.py
- jwst/resample/resample_spec.py
This update corrects and completes the change to validating attributes when they are set. It creates a new node, validates the node, and if the validation does not fail, it sets the attribute. This update
corrects the previous fix by calling custom_tree_to_tagged_tree on the node's data prior to validation. This function converts asdf types into lists and dictionaries which can be validated by the json/yaml parser.
This update also revises the code in resample_spec which builds the metadata structure appended to the datamodel. Because validation is an all or nothing operation, it is important when building the metadata structure to check the result of getattr for None. That indicates the value was not found in the input. Blindly copying the value from input to output without checking …
> Verify individual attributes when getting and setting

- jwst/resample/resample_spec.py
#1747 fixed a problem in datamodels schema validation that was causing the resample_spec step to crash when appending models to its output product. Testing showed a remaining difference in the output from resample_spec, when compared to s2d products that were created before recent changes to both schema validation and datamodels (SlitModel), which was the fact that the RELSENS extensions from the input model were not appearing in the output, and the output was also missing the 2 header keywords SRCXPOS, SRCYPOS from the SCI extension headers.
It appears that these were missing due to the fact that a `for` loop that was being used to copy over attributes from the input model to the output model was hitting an exception somewhere in the midst of looping and then quietly aborting. Thus not …
> Fix resample_spec output model

- jwst/datamodels/multiexposure.py
- jwst/datamodels/slit.py
- jwst/extract_1d/extract.py
- jwst/extract_1d/extract_1d_step.py
- jwst/extract_2d/extract_2d.py
- jwst/extract_2d/nirspec.py
- jwst/photom/photom_step.py
more #1070 related changes
Because the items in `MultiSlitModel.slits`  are now instances of `SlitModel` and not `ImageModel` some models need to check for `SlitModel` as input. 
In addition there are some minor changes in other packages.
This is the result of debugging a problem with resample_spec_step when run on NRS Fs data. The error as seen in the reg tests is:
```
/data4/iraf_conda/bldtmp/pF3k/p/envs/dev/lib/python3.5/site-packages/jwst-0.9.1a0.dev108-py3.5-linux-x86_64.egg/jwst/resample/resample_spec_step.py", line 61, in process
output_product.products[-1].bunit_data = input_models[0].meta.bunit_data
File "/data4/iraf_conda/bldtmp/pF3k/p/envs/dev/lib/python3.5/site-packages/jwst-0.9.1a0.dev108-py3.5-linux-x86_64.egg/jwst/datamodels/properties.py", line 274, in __getitem__
return …
```
> some steps need to work with SlitModel instead of ImageModel

- jwst/extract_2d/nirspec.py
- jwst/flatfield/flat_field.py
Resolves #1332.
Adds slit attributes to SlitModel with NRS_BRIGHTOBJ and "computes"  `s_region`.
> set attributes and compute s_region on SlitModel

- jwst/cube_build/coord.py
- jwst/cube_build/cube_build_wcs_util.py
- jwst/cube_build/ifu_cube.py
- jwst/datamodels/schemas/ifucube.schema.yaml
- jwst/pipeline/straylight.cfg
- jwst/straylight/straylight.py
- jwst/straylight/straylight_step.py
added straylight removal by using Modified Shepard Method to  find the distances of the pixels in the slice gaps. 
This method is set to be used by default, but the other straylight method was kept and can be used
by --method=Nearest. We can probably remove the old method (nearest) at a later date after INS has tested this method. For now I left it.
> Straylight2

- jwst/datamodels/properties.py
- jwst/datamodels/tests/test_schema.py
It was noted that when creating new spectral tables with datamodels the code could not subsequently set the table column characteristics, such as units. This is because numpy records do not support column definitions. In order to fix this prblem a new function, _as_fitsrec was added to datamodels.properties. It converts numpy records into FITS_rec objects and adds column definitions derived from the numpy record. This change modified several test results in test_schema.py,
which were updated to agree with the new code.
> Convert numpy records to fits records when setting properties

- jwst/outlier_detection/outlier_detection.py
- jwst/outlier_detection/outlier_detection_scaled_step.py
- jwst/outlier_detection/outlier_detection_stack_step.py
- jwst/outlier_detection/outlier_detection_step.py
- jwst/resample/resample_utils.py
These changes remove the dependence of the readnoise and gain reference files from the outlier_detection step.  The use of these reference files are replaced with use of the ERR arrays from each of the input files.  This version includes conversion of the ERR arrays to remove NaNs since the current computations still results in NaNs in the ERR array. 
The weighting of the outlier_detection step can eventually be changed to use 'error' instead of 'exptime' to better account (on a pixel-by-pixel basis) for the readout characteristics of each exposure.  However, that will wait until the computation of the error arrays does not include NaNs.  
This PR leaves the reffile interface for the outlier_detection step to support any use of outlier-specific reference files for parameter settings (if …
> New noise model

- jwst/cube_build/cube_build_wcs_util.py
- jwst/straylight/straylight.py
The straylight algorithm uses the gap pixels (pixels between the slices) to determine a straylight correction. This pull request removes checking if these gap pixels have the DO_NOT_USE dq_flag set.
This flag will often be set for the slice pixels - so we need to not use that flags as to whether they should be used in this algorithm
> Straylight na ns

- jwst/outlier_detection/outlier_detection.py
- jwst/resample/resample.py
- jwst/tweakreg/tweakreg_step.py
This set of changes includes:
- updates to resample to correctly apply computed background values
- an update to outlier_detection to recognize when background values are available for use
- an update to tweakreg default parameters to make allow tweakreg to work on a wider range of datasets (including simulated NIRCAM associated images that include uncal files)
This should mostly address issue #925 .
> Initial corrections for background subtraction

- jwst/outlier_detection/outlier_detection.py
- jwst/resample/resample.py
- jwst/resample/resample_spec.py
This addresses #1379 .  See comments in issue regarding the scope of these changes. 
It also includes removal of yet another extraneous import of a stsci package; namely, stsci.tools.bitmask.
> Remove hard-coded dqflag use from resample

- jwst/datamodels/schemas/core.schema.yaml
- jwst/datamodels/schemas/subarray.schema.yaml
Updated the core schema to include 'NULL' as an allowed GRATING name (fixes #1766), and also include new FGS guide star mode SUBARRAY names.
> Update schemas for GRATING and SUBARRAY names

- jwst/gain_scale/gain_scale_step.py
Changed the log level from warning to info in the gain_scale step, when it can't find a gain factor keyword in the gain reference file. This happens when processing data from instruments/modes that use the nominal gain and so it isn't really a problem that the keyword is missing for those.
Fixes #1657.
> Change gain_scale warning to info

- setup.py
Minor change to the imports in setup to fix the local build_sphinx command for doc build, without it:
```
File "setup.py", line 176, in <module>
entry_points=entry_points,
File "/Users/sosey/miniconda3/envs/jwstdev/lib/python3.5/distutils/core.py", line 148, in setup
dist.run_commands()
File "/Users/sosey/miniconda3/envs/jwstdev/lib/python3.5/distutils/dist.py", line 955, in run_commands
self.run_command(cmd)
File "/Users/sosey/miniconda3/envs/jwstdev/lib/python3.5/distutils/dist.py", line 974, in run_command
cmd_obj.run()
File "setup.py", line 44, in run
sphinx.cmd.build.build_main(['-b', 'html', './docs', './docs/_build/html'])
AttributeError: module 'sphinx' has no attribute 'cmd'
```
> Update module import for build_main docs in setup

- jwst/tso_photometry/tso_photometry_step.py
Addresses part of #1619.  Still need to get MIRI aperture parameters.
> Use CRPIX values as the target location for TSO imaging

- jwst/resample/gwcs_drizzle.py
This should address issue #1770 .  
This implements the correct numpy operations for adding a new plane to the CON array when needed to account for when previous CON array is full (>N*32).
> Revise how to append planes to CON array

- jwst/resample/resample_utils.py
Simple change to throw an Exception should either output axis be computed with zero length (after all, who knows what problems may be introduced with a problematic WCS).  
This should address issue #1717 .
> Raise Exception in make_output_wcs

- jwst/datamodels/schemas/core.schema.yaml
- jwst/datamodels/schemas/cube.schema.yaml
- jwst/datamodels/schemas/drizproduct.schema.yaml
- jwst/datamodels/schemas/ifucube.schema.yaml
- jwst/datamodels/schemas/ifuimage.schema.yaml
- jwst/datamodels/schemas/image.schema.yaml
- jwst/datamodels/schemas/level1b.schema.yaml
- jwst/datamodels/schemas/miri_ramp.schema.yaml
- jwst/datamodels/schemas/multiexposure.schema.yaml
- jwst/datamodels/schemas/multiproduct.schema.yaml
- jwst/datamodels/schemas/photometry.schema.yaml
- jwst/datamodels/schemas/quad.schema.yaml
- jwst/datamodels/schemas/ramp.schema.yaml
- jwst/datamodels/schemas/slitdata.schema.yaml
- jwst/photom/photom.py
- jwst/photom/photom_step.py
Modified all applicable data models to move the photometry-related keywords populated by the photom step to the SCI extension header of all products, in order to allow for unique values for data from multiple spectral orders. Updates to the data models were done by creating a new sub-schema `photometry.schema.yaml` for the affected keywords and then including that sub-schema in all science product schemas that need those keywords.
The photom step has also been modified to use the new location of the meta attributes for those keywords. The overall photom step structure and flow has also been modified a bit to make it more generic, now that it has to do different types of operations for different observing modes.
Fixes #1697.
> Move photometry keywords to SCI header

- jwst/datamodels/__init__.py
- jwst/datamodels/extract1dimage.py
- jwst/datamodels/multiextract1d.py
- jwst/datamodels/schemas/extract1dimage.schema.yaml
- jwst/datamodels/schemas/multiextract1d.schema.yaml
- jwst/extract_1d/extract.py
The `extract_1d` step now accepts either a JSON reference file or a `MultiExtract1dImageModel` (FITS file containing one or more images), to specify the extraction and optionally the background regions.  For IFU data, however, only the JSON reference file is currently supported.
See issue #1777.
> Add the option to use a reference image for extract_1d

- jwst/photom/photom.py
Fix a bug introduced in the modified version of the photom step in #1779. Need to pass along the filename of the area reference file to the nirspec function, because it's needed for IFU mode data.
> Photom bug fix for #1779

- jwst/outlier_detection/outlier_detection_step.py
This PR should address #1647 , at least based on using this updated code to successfully process the dataset specified in that issue.  
The outlier_detection step, with this change, will no longer run when only provided with a single input dataset.  Instead, it will return a copy of the input and flag the cal_step.outlier_detection as "SKIPPED" in the returned data's metadata.
> Update logic to correctly flag as skipped

- jwst/datamodels/schemas/specwcs_nircam_grism.schema.yaml
while making example notebooks for the team I realized the orders member was missing from the nircam wfss specwcs datamodel schema...that's been added and it validates correctly now.
> updated the nircam specwcs grism mode

- jwst/extract_1d/extract.py
Function replace_bad_values was added.  Pixels in the science data that are NaN or are flagged in the dq attribute (if that exists) with `DO_NOT_USE` will be set to 0.  The changes are made to a local copy, not to the data in the input model.  See issue #1788.
> Replace NaNs and DO_NOT_USE in science data with 0.

- jwst/flatfield/flat_field.py
For data taken with instruments other than NIRSpec, the wavelengths are not used and the wcs function is not called, so no change was needed for those data.
For NIRSpec data, changes were made to three functions:  (1) `NIRSpec_brightobj` for 'NRS_BRIGHTOBJ' data; (2) `NIRSpec_IFU` for 'NRS_IFU' data; and (3) `do_NIRSpec_flat_field` for all other NIRSpec data.  The change was to increment the pixel coordinates by 1 before calling the wcs function.
See issue #1781.
> NIRSpec WCS input coordinates are 1-based (flat_field)

- jwst/extract_1d/extract.py
- jwst/extract_1d/ifu.py
For NIRSpec data, the pixel coordinates are incremented by 1 before calling the wcs function.  This is done in ifu.py, and in extract.py for the case that the reference file is a JSON file, and also for the case that the reference file is an image.  See issue #1781.
> NIRSpec WCS input coordinates are 1-based (extract_1d)

- jwst/extract_1d/extract.py
- jwst/extract_1d/ifu.py
Function nans_at_endpoints was added.  This flags NaNs in the wavelength array with DO_NOT_USE in the dq array.  If there are NaNs at endpoints of the wavelength array, all the output arrays will be truncated to remove the contiguous NaN elements at either or both endpoints.  If there are any interior points in the wavelength array that are NaN, these will be left as NaN, though still flagged as bad in the dq array.  Prior to this, the output dq array was always zero.  See issue #1803.
> Truncate arrays where wavelength is NaN.

- jwst/extract_1d/extract.py
- jwst/extract_1d/ifu.py
- jwst/photom/photom.py
#1754 provided an update that allows column attributes, like units, to be set for table-based data models that have been created from scratch within software. This takes advantage of that ability by setting column units values for the spec_table's created in the extract_1d step, which are stored in x1d products.
It also includes an update to the photom step to set the units value for wavelength column in the RELSENS tables that are attached to science products.
Those are all the FITS table-based science products that I can think of that should set column units. Can anyone think of any others?  The source catalog, TSO photometry, and TSO white-light tables are all ASDF-based and already specify column units.
> Add TUNIT to table-based products

- jwst/outlier_detection/outlier_detection_ifu.py
This is my interpretation of how to call the 'make_output_path' method for outlier_detection_ifu based on the usage from other modules in the package.  At the very least, this avoids the original error reported in Issue #1814  based on my interactive testing with the original problem dataset.
> Fix output path naming

- jwst/datamodels/fits_support.py
The default format of the history section in ASDF files is changing in 2.0.0 (see https://github.com/spacetelescope/asdf/pull/475). This update ensures that the pipeline takes these changes into account.
> Update to reflect changes to default ASDF history format

- jwst/datamodels/guidercal.py
- jwst/datamodels/guiderraw.py
- jwst/datamodels/schemas/guider_cal.schema.yaml
- jwst/datamodels/schemas/guider_raw.schema.yaml
- jwst/dq_init/dq_init_step.py
- jwst/dq_init/dq_initialization.py
- jwst/flatfield/flat_field.py
- jwst/guider_cds/guider_cds.py
- jwst/guider_cds/guider_cds_step.py
- jwst/pipeline/calwebb_guider.py
First set of updates to guide star processing for #1612. The two main changes are the addition of an ERR array to the data models and a minor update to the column format of one of the table extensions (in order to match what SDP is generating). The guider_cds step has been updated to create an ERR array in the output model. Note that nothing is done yet with the ERR array at any stage of guider processing. It's just there for future expansion and to make it consistent with the SCI, DQ, ERR contents of science products.
Many other changes were made just for general cleanup and to get pep8/flake8 off my back. All of the changes to dq_init are for this purpose only, with no actual changes to the processing.
> Updates to calwebb_guider processing

- scripts/make_header
The make_header script creates an image containing all the required header keywords for a pipeline. The pipeline is selected based on the first three command line arguments: instrument name, mode (imaging or spectral) and pieline level (1, 2, or 3). The 4th command line argument is the name of the output file produced.
> Add make_header script

- jwst/datamodels/model_base.py
- jwst/datamodels/tests/test_models.py
Datamodels has been modified to allow conversion between model types. The method is to open a datamodel of the desired type using a datamodel of another type as its argument. For example,
im = datamodels.open('reference_file.fits')
im = FlatModel(im)
The first line opens the image as a generic reference file. The second line converts it to a flat field reference file.
> Allow conversion between model types in datamodels

- jwst/skymatch/skyimage.py
- jwst/tweakreg/wcsimage.py
All references to 'stsci.sphere' that could be found within the JWST package should have been replaced, with this PR, with references to the newer spherical_geometry package.  This includes the code as well as the docs.
> Initial replacement of code and docstrings

- jwst/datamodels/model_base.py
In some circumstances the code that set meta.model_type would set it to None. This triggered a validation warning or error, because it failed the type check for model_type. The code has been reworked so that this doesn't happen.
> Redo code that sets meta.model_type

- jwst/flatfield/flat_field.py
For NIRSpec spectroscopic data with EXP_TYPE not equal to NRS_IFU, the wavelength array will be copied to a local variable, rather than just being assigned.  This is done in functions `do_NIRSpec_flat_field` and `NIRSpec_brightobj`.  See issue #1862.
> The flat_field step modifies a copy of the wavelength array.

- .travis.yml
Relying on the `jwst` package for dependency resolution is not a viable solution in certain situations.
> Add explicit dependencies to travis.yml

- docs/jwst/introduction.rst
- docs/jwst/pipeline/description.rst
Adding more detailed information to the pipeline docs that shows which pipeline modules get applied to each EXP_TYPE value. Similar to, but more complete than, the info in JDox (https://jwst-docs.stsci.edu/display/JDAT/Modes+of+Observing)
> Add exp_type vs pipeline info

- jwst/assign_wcs/nirspec.py
- jwst/assign_wcs/tests/test_nirspec.py
Fix an issue with converting between PPS and DMS shutter coordinate systems.
The source position in a shutter is reported in the MSA configuration file in a coordinate system associated with the shutter with origin (0, 0) in the upper left corner (PPS system). `x` increases to the right. `y` increases downwards. The DMS uses a shutter coordinate system with origin  (0, 0) in the center of the shutter, with positive `x` to the right and positive `y` upwards.
> slit PPS to slit DMS coordinate conversion

- jwst/datamodels/model_base.py
- jwst/datamodels/util.py
The generic open function in datamodels does not set the meta.model_type attribute because the class it uses to open an image is only a best guess. Previously the code cleared the model_type by
setting it to None. This is not desirable, because if the metadata is re-validated, a value of None with throw a warning or error. This revision deletes the model_type attribute instead. To keep datamodels
from setting the value again, the code in on_save which sets model_type when not found was removed. It was redundant in any case.
> Modify code that clears meta.model_type

- jwst/dq_init/dq_init_step.py
- jwst/jump/jump_step.py
Remove checks of NINTS keyword value vs actual size of data array, in order to support TSO segmented file processing. Removes similar checks of NGROUPS, SUBSIZE1, SUBSIZE2 values too.
In partial fulfillment of #1616.
> Remove checks of NINTS keyword value

- docs/jwst/extract_1d/description.rst
- docs/jwst/extract_1d/reference_files.rst
- jwst/extract_1d/extract.py
Function `locn_from_wcs` was added.  For one column in the dispersion direction (the column in the middle of the WCS bounding box), this function determines the cross-dispersion location (i.e. the pixel in that column) of the target spectrum.  (I'll describe the case for dispersion in the horizontal direction.)  The target right ascension and declination are gotten from keywords TARG_RA and TARG_DEC respectively.  For each pixel in the middle column, the right ascension, declination, and wavelength are obtained via the WCS function.  The cross-dispersion location is the pixel along that column for which the distance from the target coordinates to the computed coordinates is closest to zero.  Unless the pixel closest to the target was at an endpoint of the aperture, the nod/dither offset …
> For extract_1d, find nod/dither offset from the WCS

- jwst/datamodels/schemas/core.schema.yaml
Update core.schema to change data types of GS_EPOCH, GS_SRCJM, GS_SRCHM, and GS_SRCKM keywords from number to string. Fixes #1910.
> Update guide star keyword data types

- jwst/background/background_step.py
Update the background_subtraction step to activate the loading and subtracting of WFSSBKG reference images for WFSS exposures. This simply involves uncommenting lines that were already included in the routine, but were waiting for the ref files to become available.
Fixes #1917.
> Activate WFSS background subtraction

- jwst/extract_1d/extract.py
Another `int(round(width))` was needed.  Also, a check was needed on whether `slit.meta` had a `target` attribute.
> Fix bugs in finding location of spectrum from the WCS

- jwst/extract_2d/nirspec.py
Nirspec units  in V2V3 are now in arcsec and there's no need to convert them to deg when computing the source position.
> keep source position in arcsec

- jwst/datamodels/model_base.py
Datamodels sometimes, but not always, throws an error when trying to access a non-existent metadata value. I've wrapped the access to meta.filename with a try block to catch the error.
> Test for existence of filename in __repr__

- jwst/datamodels/fits_support.py
Datamodels tests were throwing a validation error when writing new history records. It's not clear why we started seeing the errors, perhaps an update to asdf. But the cause is that there were two
different data structures to hold the history records and only one of them passed validation. The solution is to convert the invalid structure to the valid one before serializing the asdf file to its
extension.
> Fix history validation error

- jwst/assign_wcs/pointing.py
- jwst/assign_wcs/tests/test_wcs.py
- jwst/lib/set_telescope_pointing.py
- jwst/transforms/models.py
This is a different fix to the unit problem in #1931. The V2V3 to sky transform works with angles in degrees. Since this is a sequence of rotations the inverse is an analytical one and reuses the same class. This means that a unit conversion in `V23ToSky.evaluate` will not work with the inverse.
One option is to writ ea separate inverse class.
Another approach, implemented here, is to prepend a specific  transform for the unit conversion.
Supersedes #1931.
> fix units by adding a model unit conversion

- jwst/cube_build/coord.py
- jwst/cube_build/cube_build_wcs_util.py
- jwst/cube_build/ifu_cube.py
Fix the IFU cubes parity that I messed up a few months ago.
PC1_1 = -1 is still used but the naxis1 dimension is constructed opposite what is was. 
The naxis1 dimension now increase in the opposite direction as ra does. 
For regression testing we need to establish a new reference IFU cube.
> Cube build parity

- jwst/extract_2d/nirspec.py
The structure of the WCS pipeline was changed in recent updates - `wcs.get_transform("slit_frame", "msa_frame")` returns now a `Slit2Msa` model which should not be indexed.
> fix extract_2d

- jwst/cube_build/blot_cube_build.py
- jwst/cube_build/ifu_cube.py
- jwst/datamodels/schemas/ifucube.schema.yaml
As part of a larger effort to reorganize and clean-up some of the keyword schemas, this updates the IFUCubeModel schema to place all of the cube-specific keyword definitions within a new meta subsection called "ifu". Updates to cube_build modules are also made to point to the new meta tree locations of these keywords.
> Reorganize IFU-specific keywords

- README.md
- Prevents Miniconda2 or Anaconda2 users from implicitly installing Python 2.7 packages into their new development environment.
- Issuing `python=3` selects the latest version of Python 3.x from the `defaults` channel.
Ref: INC0056315
> README: Use python 3.x during environment creation

- jwst/tests_nightly/general/pipelines/test_nis_wfss_spec2.py
This test takes a long time to run, and it is currently not running on the Pandokia/SVN side.  I'm setting it to skip if the `--runslow` option is not used.
> Skip nis_wfss_spec2 regtest via runslow [skip ci]

- jwst/assign_wcs/nirspec.py
- jwst/transforms/models.py
This requires a bugfix in astropy and should be merged after astropy/astropy#7411 is merged.
There are three substantial changes in this PR:
- The computation of slit-y positions was done through fitting a line. This is now replaced 
by linear interpolation.
- Similarly a relationship `lambda(n)`  was established by fitting a line. Now this is replaced with interpolation.
- The equation computing the refraction index from angles was changed to match the one in the  IDT team code.
This improves the prism wavelength computation by several orders of magnitude.
> Nirspec bug fixes

- jwst/assign_wcs/fgs.py
- jwst/assign_wcs/nircam.py
- jwst/assign_wcs/niriss.py
A CubeModel is always treated as a stack (in dimension 1)
of 2D images, as opposed to actual 3D data. In this case
the bounding box is set to the 2nd and 3rd dimension.
This PR is the same as and supersedes #1956 which was approved.
> Bounding box of CubeModel

- jwst/assign_wcs/fgs.py
- jwst/assign_wcs/nircam.py
- jwst/assign_wcs/niriss.py
For a stack of images when the WCS bounding box is retrieved from the shape of the data it should still have length 2 because the input coordinate frame has 2 axes.
> CubeModel bbox should be 2D

- jwst/flatfield/flat_field.py
- jwst/flatfield/flat_field_step.py
Tests were removed from flat_field_step.py that prohibited the step from running (for spectroscopic data) if any of the three NIRSpec flat fields was missing (meaning that the file name was "N/A").  Now, any one or two of the flat field reference files may be missing.  If no flat field reference file is found, however, this is logged as a warning and the step will be skipped.
In flat_field.py, the main change was to add a test at the beginning of each of `fore_optics_flat`, `spectrograph_flat`, and `detector_flat`.  If the respective `f_flat_model`, `s_flat_model`, or `d_flat_model` is None, the function creates an array of ones for the `f_flat` (`s_flat`, `d_flat`) and returns that array, along with None for the dq array.
See also issue #1914.
> Allow one or two of the NIRSpec flat fields to be missing.

- scripts/world_coords
The script is a tool to read in the output of extract2d (FS and MOS) or assign_wcs (IFU) and apply the WCS transforms to all pixels in a slit. For each slit it writes the results as a cube with four planes
(wavelength, ra, dec, y_slit) in a separate fits extension.  The file is saved with a suffix "world_coordinates".
> New script creates world coordinates files from extract2d files

- jwst/assign_wcs/fgs.py
- jwst/assign_wcs/niriss.py
Yesterday's regression tests showed the error:
```
File "/data4/iraf_conda/bldtmp/pMIW/p/envs/dev/lib/python3.5/site-packages/jwst-0.9.3a0.dev176+g5ee05334-py3.5-linux-x86_64.egg/jwst/assign_wcs/fgs.py", line 79, in imaging_distortion
if isinstance(input_model, CubeModel):
EXCEPTION
Type: NameError
Message: name 'CubeModel' is not defined
```
which is due to updates merged in #1966 that added the use of `CubeModel` and `ImageModel` to a few `assign_wcs` modules, but those modules were not importing `CubeModel` and/or `ImageModel`.
> Add CubeModel to assign_wcs imports

- jwst/tests_nightly/general/pipelines/test_nrc_tso3_1.py
- jwst/tests_nightly/general/pipelines/test_nrs_msa_spec2.py
This removes some extraneous pandokia-related baggage from the TSO3 test, while also fixing (based on my testing) the results for the second test defined in this module.
> Fixed TSO3 test and removed pandokia baggage

- jwst/tests_nightly/general/pipelines/test_coron3_1.py
- jwst/tests_nightly/general/pipelines/test_fgs_sloper_1.py
- jwst/tests_nightly/general/pipelines/test_nirspec_dark.py
- jwst/tests_nightly/general/pipelines/test_nrc_image3_1.py
- jwst/tests_nightly/general/pipelines/test_nrs_ifu_spec2.py
Fix regression tests for the following pipelines:
- NIRCam coron3
- FGS detector1
- NIRSpec dark
- NIRCam image3
- NIRSpec IFU spec2
> Fix pipelines for regtests

- jwst/tests_nightly/general/pipelines/test_nrs_msa_spec2.py
- jwst/tests_nightly/general/pipelines/test_nrs_msa_spec2b.py
This addresses the problem with finding the MSAREF file specified in the input file, as well as the incorrect syntax used to start the pipeline (needs .run() instead of .call()).  As a result, both MSA_SPEC2 tests should now run correctly.  
One consequence of this change is that the MSAREF file for the test needs to be moved from the test definition directory to the input data directory.  In the meantime, an issue should be filed to document this problem and spur some thought on a possible solution for the entire pipeline.
> Fix both MSA Spec2 tests

- scripts/make_header
This version of make_header allows you to select coronographic exposure types and if selected will produce a header with keywords used by the corongraphic pipline. The changes to support that are in choose_pipeline.
Testing uncovered a problem with stripping method calls from metadata names. The new code uses a simpler algorithm. It looks for a parenthesis following the name. Changes are to the pattern used in
undefined_metadata and to the function drop_suffix.
I also added additional diagnostic prints in the function log_file. These prints are normally turned off.
> Add support for coronographic pipeline to make_header

- jwst/ramp_fitting/ramp_fit.py
- jwst/ramp_fitting/utils.py
Updates to the ramp_fit computations for segment-specific and integration-specific variances of the slope due to either Poisson noise, readnoise, or both.
2. Updated computations of integration-specific and overall slopes, and weights.
3. Added code to use data from a good initial group in a ramp only if there are not good data in later groups.
4. Added check to ensure that MIRI dataset has a minimum of 2 groups.
5. Updated deprecated logging format
6. Removed obsolete code and variables.
7. Updated code resolves these github issues: 1681, 1683, 1686, 1687, 1714
> Update ramp_fit slope variances

- jwst/tests_nightly/general/pipelines/test_miri_lrs_slit_1b.py
Update the MIRI LRS fixed-slit calspec2 regression test that uses multi-integration inputs and outputs to use the correct `_calints` and `_x1dints` product names again, now that #1992 has fixed the calspec2 pipeline to use the correct names for multi-integration products.
> Update MIRI LRS reg test file names

- jwst/straylight/straylight_step.py
Change '62f' format to '6.2f' (62 was a little excessive for values that are only in the hundreds!)
> Fix straylight typo in log message

- docs/jwst/ami/main.rst
- jwst/ami/NRM_consts.py
- jwst/ami/__init__.py
- jwst/ami/ami_analyze.py
- jwst/ami/ami_average.py
- jwst/ami/ami_normalize.py
- jwst/ami/leastsqnrm.py
- jwst/ami/webb_psf.py
Update ami_analyze to always extract an 80x80 subarray from full-frame data. This is equivalent to the user using the SUB80 subarray in the first place, so the subarray matches the location and size of the SUB80 subarray. Updated docs. This addresses github issue #1837.
> Only extract an 80x80 subarray, if input is full-frame

- jwst/cube_build/ifu_cube.py
- jwst/datamodels/schemas/core.schema.yaml
- jwst/datamodels/schemas/keyword_band.schema.yaml
- jwst/datamodels/schemas/keyword_filter.schema.yaml
- jwst/datamodels/schemas/keyword_grating.schema.yaml
Several fixes related to the recent implementation of model_blender in cube_build:
- Updated the cube_build step itself to only call model_blender when there are multiple inputs. It still leaves in place the error associated with input file names not being in the working directory (@hack is working on a parallel fix for that).
- Changed the comment string on the `CHANNEL` keyword back to its original value, just to avoid a whole lot of regression tests showing differences. It needs to be updated some time in the future, but not right now.
- Added `MULTIPLE` as an allowed value to the keyword-specific schemas for `FILTER`, `BAND`, and `GRATING`, as was done recently for those keywords in the core schema. So now they're in sync again.
> Fix some model_blender issues in cube_build

- jwst/tests_nightly/general/pipelines/test_mrs_spec3.py
This updates the Jenkins-run test to be consistent with how the pandokia test was being run; with the primary correction being that save_results needed to be set for the cube_build step instead of relying on blendmeta to generate the s3d output files.
> Fixes problems with parameter settings for MRS_SPEC3 test

- docs/jwst/ami/main.rst
Reverts some of the changes to the AMI docs that were made incorrectly in #2017 (they undid updates that were put in place in Nov 2017). #2017 must have started from an outdated version of the file.
> Restore inadvertent changes to AMI docs

- jwst/cube_build/ifu_cube.py
- jwst/resample/resample.py
Changes implemented include:
- calling blendmodels in resample and ifu_cube with already opened model instances instead of filenames
- turning on blendmodels use again for ifu_cube
These changes should correct the ERRORS seen in the regression tests on 10-May-2018 and 11-May-2018 due to files not being found.  
This PR should only be merged AFTER PR #2023 has been merged in order to avoid problems with array-based metadata during blending.
> Use models to call blendmodels

- JenkinsfileRT
Updated the CRDS_CONTEXT for Jenkins regression tests from 454 to 456, which includes updated NIRSpec rmaps and an updated NIRISS photom reference file.
> Update Jenkins CRDS_CONTEXT to 456

- jwst/datamodels/model_base.py
- setup.py
Asdf has changed the way it handles asdf extensions. It now loads them using the entry_points attribute to the setup function. I added the BaseExtension class to the setup entry_points and removed the default extension list handling in model_base, as it is no longer needed.
> Remove default extensions from model_base, add them to setup file

- jwst/extract_1d/extract.py
The `input_model` was added to the calling sequence of `find_dispaxis`, and some information (e.g. exposure type) is gotten from `input_model` rather than from `slit`.  In the section for computing wavelengths from the wcs function, grism data are now supported.
See issue #2031.
> In find_dispaxis, regard wavelength = 0 as invalid

- jwst/tests_nightly/general/pipelines/test_nrs_msa_spec2.py
This test was failing because the FILENAME keyword was always going to be different given the way the test was set up.
I took the liberty of cleanup up the `FITSDiff` as well.  All the restructuring of the HDUs in the HDUlist was to avoid comparing the ASDF extension (which is always the last extension).  A little simpler to just prune it off.
> Fix test_nrs_msa_spec2 regression test

- jwst/pipeline/calwebb_image3.py
- jwst/pipeline/calwebb_spec2.py
- jwst/pipeline/calwebb_tso3.py
- jwst/tests_nightly/general/pipelines/test_nis_wfss_spec2.py
- Removed the `runslow` marker from the test, as @hbushouse has pruned the input file so that the test runs in a few minutes.  This now enables this test to run on Jenkins.
- Extended the work of #1982 which didn't catch all (or even most) of the instances of `meta.asn.table_name` being populated with a full path in our pipelines.  This test uses the spec2 pipeline, which had this bug.
> Fix NIRISS WFSS spec2 regression test

- jwst/tests_nightly/general/pipelines/test_nis_wfss_spec2.py
Reverting changes I'd made to this test, as it seems the spec2 pipeline doesn't preserve slit order.  This fix sets the slit order for the test.
> Reorder multislit extensions for NIRISS WFSS spec2 test

- docs/jwst/introduction.rst
- docs/jwst/stpipe/devel_io_design.rst
- jwst/pipeline/calwebb_ami3.py
- jwst/pipeline/calwebb_spec2.py
- jwst/pipeline/tests/test_calwebb_spec2.py
- jwst/pipeline/tests/test_nis_ami3.py
- jwst/stpipe/step.py
- jwst/stpipe/tests/steps/__init__.py
- jwst/stpipe/tests/test_input.py
- jwst/stpipe/tests/test_saving.py
- jwst/stpipe/tests/util.py
Create a parallel API for input as already exists for output. 
This PR is intended as proof-of-concept and promote discussion.
Main documentation is found in `devel_io_design.rst`. Conceptually this is under the `Step I/O Design` section of `STPIPE`. The API includes the methods `Step.open_model` and `Step.make_input_path` now exist, mimicking the `save_model` and `make_output_path` methods.
Note: This PR will only apply the API to a specific case, _TBD_. Once vetted, another issue will track the deployment to the rest of the codebase.
> Define an input API

- jwst/assign_wcs/assign_wcs_step.py
- jwst/assign_wcs/nirspec.py
- jwst/datamodels/schemas/slitdata.schema.yaml
- jwst/extract_2d/nirspec.py
- jwst/flatfield/flat_field.py
- jwst/tests_nightly/general/pipelines/test_nrs_msa_spec2.py
- jwst/tests_nightly/general/pipelines/test_nrs_msa_spec2b.py
* Utilize Step.input_dir to find the MSA metadata file
* Move all reading of the MSA metadata file to assign_wcs step
* Store MSA info needed in flat_field step in each slit instead of rereading MSA file
* Update the MultiSlitModel schema to store `quadrant, xcen, ycen` in each slit
> Handle MSA metadata file only in assign_wcs step using Step.input_dir

- scripts/make_header
An independent review of the script in #2048 found several problems. The script was not treating metadata keywords marked as IRS2 as nirspec specific. Bugs in the code kept it from setting metadata with enumerated values or correctly choosing the instrument that a metadata keyword was associated with. Re-examination of the jwst source code led to some changes to default values used for instrument and modes. And in some cases, defaults depend on exposure type as well as instrument.
> Update make_header script

- docs/jwst/extract_1d/arguments.rst
- jwst/extract_1d/extract.py
- jwst/extract_1d/extract_1d_step.py
- jwst/pipeline/extract_1d.cfg
A verbose argument was added to a number of functions, initially set to True but reset to False after the first integration of a multi-integration exposure.  A new parameter log_increment was added to the step.  This lets the user specify how frequently INFO messages are written during processing of a multi-integration exposure.
See issue #2079.
> extract_1d should not repeat log messages for every integration

- jwst/pipeline/calwebb_ami3.py
- jwst/pipeline/calwebb_coron3.py
- jwst/wfs_combine/wfs_combine_step.py
- strip abspath from ASNTABLE keyword in calwebb_ami3, calwebb_coron3
- use Step.load_as_level3_asn in calwebb_coron3
- use Step.load_as_level2_asn in wfs_combine_step
> Remove absolute file paths from ASNTABLE keyword and assocation tables

- jwst/flatfield/flat_field.py
This is a patch for issue #1981.
> Set slit_nt to None for non-MSA data.

- jwst/flatfield/flat_field.py
The flat_field step now allows NRS_BRIGHTOBJ data to be either 3-D (the "normal" case, multi-integration) or 2-D (averaged over integrations).
See issue #2080 and JIRA issue JP-318.
> For flat_field, process 2-D NRS_BRIGHTOBJ data

- docs/jwst/skymatch/README.rst
This PR adresses some of the issues described in https://github.com/STScI-JWST/jwst/issues/741:
* Fixed `astrodrizzle` link and spacing in issue 1.
* Expanded explanation of who algorithm works (what it does) based on info that I got on JIRA after I requested clarification on what issue 2 is about.
* Issue 3.b - fixed "boldness" of `subtract` parameter.
Issues 3.a and 4 are invalid.
> Improve skymatch documentation

- jwst/firstframe/firstframe_sub.py
- jwst/group_scale/group_scale_step.py
- jwst/lastframe/lastframe_sub.py
- jwst/ramp_fitting/ramp_fit_step.py
- jwst/rscd/rscd_step.py
Fixes some typos, makes some messages more clear, makes them consistent with equivalent messages from other steps, and downgrades warnings from the group_scale step to info, because it's quite normal for that step to be not necessary. Also removed the setting of meta.exposure.gain_factor to None in the ramp_fit step, just to avoid the annoying schema validation warning.
> Clean up some warning messages

- jwst/datamodels/fits_support.py
- jwst/datamodels/model_base.py
- jwst/datamodels/properties.py
- jwst/datamodels/tests/test_schema.py
- jwst/datamodels/util.py
- jwst/datamodels/validate.py
Datamodels allows users to set a metadata keyword to None, which indicates that it should not be written to the fits header. In certain cases datamodels was checking a value of None against the type of the keyword in the schema and throwing a warning. To prevent this from happening this update adds a custom validator for type which skips validation when the keyword value is None.
This update also moves all the validation code from util.py into a new file, validate.py. The amount of validation code in datamodels was large enough to deserve its own file. This also required updating all the places where validation was called, including tests.
> Add a custom validator that checks for None

- JenkinsfileRT
The jwst-edit context tracks the last ReDCaT delivery,  currently jwst_0462.pmap.   
Also updated regression context in 
jwcalibdev:/data1/jwst_rt/pdk_environment 
to jwst-edit.
> Switched CRDS_CONTEXT in JenkinsfileRT to jwst-edit

- jwst/assign_wcs/nirspec.py
When a limited WCS pipeline is run (fitler="OPAQUE") the input is in units of microns and should be converted to meters.
> NRS: fix input units to meters when filter=OPAQUE

- jwst/extract_1d/extract.py
- jwst/white_light/white_light.py
The `white_light` step failed because the original file had been segmented and the code was using `input.meta.exposure.nints` for the number of integrations.  Furthermore, the input can contain several (up to three) tables for each integration, i.e. one for each spectral order.  The section of the code that computes the time for each integration was modified to take into account the possibility that the input contained more than one spectral order.  The number of tables for each spectral order is determined from the input tables, rather than relying on the NINTS keyword.  See issue #2148.
While testing the above change using NIRISS SOSS data, it was noticed that the `extract_1d` step was printing a warning message for every integration (for spectral orders 2 and 3), e.g. "Using RELSENS, …
> white_light should handle segmented data and data with multiple orders

- jwst/assign_wcs/nirspec.py
Change the interpolation points in the wavelength interpolation to match those in the IDT code.
This fixes the mismatch in the wavelength calibration for the prism.
> fix for NRS prism 

- jwst/pipeline/calwebb_spec2.py
- jwst/pipeline/tests/test_calwebb_spec2_nrs_msa.py
Ensure that `calwebb_spec2` raises an exception for a failed or skipped `assign_wcs` step.
Resolves #2151
> Ensure calwebb_spec2 fails when `assign_wcs` fails or is skipped

- jwst/assign_wcs/assign_wcs.py
- jwst/assign_wcs/nirspec.py
- jwst/extract_2d/extract_2d.py
- jwst/extract_2d/nirspec.py
Needs rmaps update to include NRS_AUTOFLAT in order to pick the reference files.
Code was tested local reference files.
**Alternatively**, we can merge this and let the INS team use local reference files during their tests.
The INS team indicates that NRS_AUTOFLAT observations should be processed by assign_wcs and extract_2d as MOS observations.
Fixes #1984.
> process NRS_AUTOFLAT as a MOS observation

- .rtd-environment.yml
- .travis.yml
- Jenkinsfile
- JenkinsfileRT
This prevents `drizzlepac` and `fitsblender` from getting used by RTD, Travis, and Jenkins.
Here's a PR to do the same thing to our `astroconda-dev` recipe:
https://github.com/astroconda/astroconda-dev/pull/137
> Purge unused dependencies

- jwst/datamodels/cube.py
- jwst/datamodels/level1b.py
- jwst/datamodels/multispec.py
- jwst/datamodels/ramp.py
- jwst/datamodels/schemas/image.schema.yaml
- jwst/datamodels/schemas/level1b.schema.yaml
- jwst/datamodels/schemas/multislit.schema.yaml
- jwst/datamodels/schemas/multispec.schema.yaml
- jwst/datamodels/schemas/ramp.schema.yaml
- jwst/datamodels/slit.py
- jwst/extract_1d/extract.py
- jwst/extract_2d/nirspec.py
- jwst/ramp_fitting/ramp_fit.py
- jwst/ramp_fitting/utils.py
- jwst/tso_photometry/tso_photometry.py
- jwst/white_light/white_light.py
The `extract_1d` step was modified to copy the times from the input INT_TIMES table to metadata for the output spectra, but only for TSO data, and only if there is an INT_TIMES table in the input.  PR #1987 included changes to extract_1d, but the current commit fixes some bugs in the earlier version and adds a check for TSO data.
The `ramp_fit` step has been modified to copy the input INT_TIMES table to the output model for integration-specific results for TSO data, and the `extract_2d` step has been modified to copy the input INT_TIMES table to the output model for 3-D NIRSpec NRS_BRIGHTOBJ data.
The `tso_photometry` and `white_light` steps have been modified to copy the times from the INT_TIMES table (if it is present in the input) instead of computing the times directly.
Some of the …
> Update data models and steps for the integration times table.

- jwst/tests_nightly/general/niriss/test_ami_analyze.py
- jwst/tests_nightly/general/niriss/test_ami_pipeline.py
- jwst/tests_nightly/general/pipelines/test_coron3_1.py
- jwst/tests_nightly/general/pipelines/test_nrc_image3_1.py
Lower fitsdiff tolerances so that upstream changes in `numpy` and Anaconda's recipes for building `numpy` do not constantly break these tests.
Revisit these once we check that we're using `np.float64` everywhere it is needed and check with the teams for guidance on needed scientific accuracy of the algorithms for the AMI pipeline.
Separately diff HDRTAB for level 3 pipeline results, so that the binary table column sizes do not produce unexpected diffs.
Resolves #2124.
> Lower relative tolerance on fitsdiff for a few regression tests

- jwst/tso_photometry/tso_photometry.py
tso_photometry.py can write log messages when an INT_TIMES table is used, so now it needs to `import logging`.  See issue #1881.
> Import logging.

- jwst/associations/__init__.py
- jwst/associations/pool.py
`jsviewer` does not take delimiters as keyword arguments, which `AssociationPool` forces. Allow this case to occur cleanly.
> Fix AssociationPool.write to be compatible with jsviewer

- jwst/datamodels/schemas/container.schema.yaml
- jwst/datamodels/schemas/lev3_prod.schema.yaml
- jwst/resample/gwcs_drizzle.py
- jwst/resample/resample.py
- jwst/resample/resample_spec.py
- jwst/resample/resample_spec_step.py
- jwst/resample/resample_step.py
- jwst/tests_nightly/general/pipelines/test_nrs_fs_brightobj_spec2.py
- jwst/tests_nightly/general/pipelines/test_nrs_fs_multi_spec2_1.py
- jwst/tests_nightly/general/pipelines/test_nrs_fs_multi_spec2_2.py
- jwst/tests_nightly/general/pipelines/test_nrs_fs_multi_spec2_3.py
- jwst/tests_nightly/general/pipelines/test_nrs_fs_single_spec2.py
- jwst/tests_nightly/general/pipelines/test_nrs_msa_spec2.py
- jwst/tests_nightly/general/pipelines/test_nrs_msa_spec2b.py
- Remove unnecessary, unused metadata from `ModelContainer` schema
- Remove unnecessary, unused metadata from level 3 product schema
- move population of association metadata up into the `ResampleStep` classes
- update S_REGION correctly for `ResampleSpecStep` outputs
> ModelContainer, Level 3 schema cleanup; resample output metadata updates

- docs/jwst/ami/reference_files.rst
- docs/jwst/dq_init/reference_files.rst
- docs/jwst/flatfield/reference_files.rst
- docs/jwst/fringe/reference_files.rst
- docs/jwst/ipc/reference_files.rst
- docs/jwst/jump/reference_files.rst
- docs/jwst/linearity/reference_files.rst
- docs/jwst/ramp_fitting/reference_files.rst
- docs/jwst/refpix/reference_files.rst
- docs/jwst/reset/reference_files.rst
- docs/jwst/rscd/reference_files.rst
- docs/jwst/straylight/index.rst
- docs/jwst/straylight/reference_files.rst
- docs/jwst/superbias/reference_files.rst
This is the first pull request to move the reference file specifications back into the JWST pipeline documentation from http://jwst-reffiles.stsci.edu/index.html.   These updates are minor and take the following forms:
* format changes 
* adding additional text that appeared in the jwst-reffiles especially referring to files using gain
* fixing the latex in the RCSD reference file
@hbushouse @rizeladiaz @jemorrison @dmggh
> Reference file  specifications part I

- Jenkinsfile
- JenkinsfileRT
The CI utilities library that Jenkins uses to provide the convenience syntax used in the Jenkinsfile has been updated to temporarily honor both `.build_mode` and `.name` as a step towards transitioning to the new property `.name` for clarity. Once all projects using the CI utilities are updated, support for the old `.build_mode` name will be removed.
> Change 'build_mode' to 'name' to reflect CI utils update.

- MANIFEST.in
- conftest.py
- jwst/datamodels/tests/data/collimator_fake.asdf
- jwst/datamodels/tests/test_schema.py
- jwst/datamodels/validate.py
- setup.py
This allows custom tags, like transforms, to be validated. With this fix the WCS  reference files validate against their schemas.
> use tagged tree in validaiton of custom tags

- jwst/source_catalog/source_catalog.py
The `properties_table()` function is deprecated in `photutils`.  The `SourceCatalog.to_table()` method is used instead.
> Remove deprecated photutils.properties_table

- jwst/datamodels/reference.py
- jwst/datamodels/wcs_ref_models.py
The validate methods in reference.py and wcs_ref_models.py have assertions that test their respective reference files. Wrapping the asserts in a try block allows them to be handled according to the user parameter strict_validation, either re-thrown if it is true or converted to a warning if it is false (the default.)
> Catch asserts in validate methods so that they can be handled

- jwst/ami/leastsqnrm.py
The import of `comb` from `scipy.misc` is deprecated.  This updates that import.
> Update deprecated import for scipy.special.comb

- jwst/resample/resample.py
Bug found by @gbrammer where the `update_fits_wcs()` method was only doing the updates on `ImageModel`, but of course the output of `ResampleStep` is a `DrizProductModel`. So this code was never applied and the FITS WCS values were never being updated.  Instead the old values from the first image in the input stack were being retained.
The result was the `SourceCatalogStep` which uses the FITS WCS to write out RA/DEC values was writing them out using the wrong WCS.  Correct `xcentroid, ycentroid` values, but wrong sky coordinates for the sources.
@sosey This should help the grism pipeline.
> Fix update_fits_wcs() to work on DrizProductModels

- conftest.py
- jwst/__init__.py
This should resolve #2205 and allow the ASDF schema tester to run successfully under both `pytest` and `python setup.py test`.
> Re-enable and fix errors with ASDF schema tester

- README.md
Update the README file to correct the instructions for installing a particular release version of the cal pipeline package, using a spec file to list all the particular versions of 3rd party packages.
Fixes #2251
> Update README with release installation instructions

- docs/jwst/tso_photometry/reference_files.rst
The name of the reference file model (i.e. TsoPhotModel) and a list of required FITS keywords and datamodel meta names were added.  See issue #2257.
> Add model name and list of required keywords

- JenkinsfileRT
The machinery internal to the CI support library changed to conform to the prescribed method of handling default argument values in Groovy. Previous attempt was based on faulty documentation, apparently.
Testing indicates this should really do the trick.
| Function argument  | Commit message  | Result |
| ------------- |:-------------:| -----:|
| `['skip_disable':true]` |  `[skip ci]` appears | build proceeds |
| `['skip_disable':true]` | regular commit message | build proceeds |
| none | `[skip ci]` appears | build skipped |
| none | regular commit message | build proceeds |
> Provide CI utils 'skip_disable' argument in correct form

- jwst/datamodels/ifuimage.py
- jwst/datamodels/model_base.py
- jwst/datamodels/multislit.py
- jwst/datamodels/properties.py
- jwst/datamodels/slit.py
- jwst/datamodels/tests/test_models.py
The `__hasattr__` method has been replaced by `hasattr`. It tests to see
if a node has a specified attribute, much like the hasattr function in
Python. However, the hasattr method does not create the attribute
while the hasatter function does. This is a peculiarity of the
implementation of Datamodels nodes and not a general issue for Python.
I added a new test for hasattr and went through the datamodels code to
replace the use of the hasattr function with the new method where that
was appropriate.
> Rewrote the hasattr method in Datamodels

- jwst/datamodels/schemas/core.schema.yaml
- jwst/datamodels/schemas/ifucubepars.schema.yaml
- jwst/datamodels/schemas/miri_resolution.schema.yaml
- jwst/datamodels/schemas/resolution.schema.yaml
- jwst/datamodels/schemas/subarray.schema.yaml
- jwst/datamodels/schemas/wavecorr.schema.yaml
- setup.cfg
This enables the ASDF schema tester for schemas found under `jwst/datamodels/schemas`. It also fixes a number of apparent errors that were exposed by these tests.
Since I'm lacking some context about how the datamodels work, someone should check to make sure the changes I made are in fact valid fixes.
This PR is based on #2240, which should be merged first.
> Enable tests for datamodel schemas and fix errors

- docs/jwst/model_blender/blender_rules.rst
- jwst/model_blender/blendmeta.py
Mostly minor clean-up of model_blender docs, but it does add a usable example of how to run model_blender with in-memory models.
> Add usage examples to blendmeta docs [ci skip]

- jwst/lib/utc_to_tdb.py
- scripts/utc_to_bary.py
A script was written to read the UTC columns (at the start, middle, and end of each integration) from the INT_TIMES table, call the `timeconversion` module to compute the corresponding times at the solar-system barycenter (TDB), and update the columns in the INT_TIMES table.  See issue #1617.
> New script to compute and update TDB columns in INT_TIMES

- docs/jwst/outlier_detection/outlier_detection_ifu.rst
- docs/jwst/outlier_detection/outlier_detection_spec.rst
This eliminates the warnings produced by the outlier_detection docs.  It also adds missing cross-references to a couple of places where ModelContainer and CubeModel were mentioned.
Addresses #2287 (at least partially).
> Eliminate Warnings from outlier docs

- jwst/lib/tests/test_utc_to_tdb.py
The test is actually for lib/utc_to_tdb.py, which is called by utc_to_bary.py.
See issue #1617.
> Add a test for utc_to_bary.py.

- jwst/pipeline/calwebb_tso1.cfg
Update the `calwebb_tso1` cfg file to skip the `firstframe` step and save the corrected ramp product. Fixes #1455.
> Update calwebb_tso1 for skipped steps

- jwst/timeconversion/__init__.py
Fix the problem in `timeconversion` that was caused by a recent addition of a new field to the ephemeris by retrieving only the fields needed. Not sure if the jwst velocity fields are actually needed in the script, but they were retrieved before, so keeping them for now.
Fixes #2238.
> Fix timeconverson for change to ephemeris fields

- jwst/datamodels/irs2.py
- jwst/datamodels/schemas/irs2.schema.yaml
- jwst/tests_nightly/general/nirspec/test_detector1.py
- jwst/tests_nightly/general/nirspec/test_refpix_irs2.py
Updates the IRS2 refpix data model to define only the keywords needed for this reffile, as was done for all other reffile data models in #861. Also adds 2 regression tests that involve the NIRSpec IRS2 mode correction in the `refpix` step (we didn't have any IRS2 tests before).
Related to #2183.
> Update IRS2 data model and add reg tests

- docs/jwst/ramp_fitting/main.rst
- jwst/ramp_fitting/ramp_fit.py
- jwst/ramp_fitting/ramp_fit_step.py
- jwst/ramp_fitting/utils.py
Corrected handling of ramps whose first differences are all NaNs (such as ramps with all groups saturated), segregated code to calculate quantities needed for the optional output product only if the save_opt is selected, updated variance calculations so that their values in the optional output will be 0 for non-existing segments, added code to remove segments having a single group if the ramp has other segments.
> Ramp fit fixes for ramps that are all NaNs

- docs/jwst/ramp_fitting/main.rst
- jwst/ramp_fitting/ramp_fit.py
- jwst/ramp_fitting/ramp_fit_step.py
- jwst/ramp_fitting/utils.py
Reverts spacetelescope/jwst#2289
All regression tests involving ramp_fit seem to be taking hours to complete ever since this was merged. So reverting, at least temporarily, to allow the rest of the reg test suite to get a clean run.
> Revert "Ramp fit fixes for ramps that are all NaNs"

- jwst/source_catalog/source_catalog.py
The function `astropy.stats.sigma_clipped_stats` call signature has changed.  `iters` has become `maxiters`.  This resolves a deprecation warning in `SourceCatalogStep`.
> Change iters to maxiters in source_catalog

- jwst/datamodels/fits_support.py
This enables CRDS certify to issue an error message like this:
Validation error : JWST Data Models: ERROR loading embedded ASDF: newline not found
instead of a less helpful message like this:
Validation error : JWST Data Models: newline not found
Certify options for trapping this robustly are pretty limited, this particular
pull was inspired by a corrupt .fits with bad/missing ASDF extension which
bubbles up to CRDS as "ValueError('newline not found')".
IMHO the datamodels are probably the right place to add explanation since
they're doing the funky embedded ASDF thing.   I guess an alternative would
be to improve the ASDF embed functions.
> Added annotation to embedded ASDF exception message

- jwst/assign_wcs/nirspec.py
When computing the slit_y locations the slit size was set to (-.55, .55).  This is correct in most cases (and in all test cases we've looked so far) but is not correct for slitlets of arbitrary size. This PR uses the slit size recorded in `(Slit.ymin, Slit.ymax)`  to compute the slit_y locations. 
Discovered by @stscirij while debugging a barshadow problem so setting him as a reviewer :smiling_imp: 
The effect of the current (wrong) implementation is that the non-NaN values within the slitlet are limited to the major shutter, i.e the shutter where the source is located while the bounding box and the cutout encompass all three shutters so most of the cutout values are NaN.
There may be a related issue regarding what is considered the origin of the model, i.e. is (0,0) in the center of the …
> Slitlet dimension

- jwst/datamodels/amilg.py
- jwst/datamodels/linearity.py
- jwst/datamodels/model_base.py
- jwst/datamodels/ndmodel.py
Datamodels normally store their most significant data in an array
named 'data'. Datamodels allows this to be changed in a subclass by
overriding the method get_primary_array_name. The base class returns
the name 'data'. I've modified it so that it now checks the schema and
returns the empty string if it is not found. I used the empty string
rather than None in case a user feeds the result directly into
getattr. A value of None will throw an error and both are falsey. The
new code prevents datamodels that contain tables from reporting that
they have a data array.
I've modified the shape method/property to test the result of
get_primary_array_name, which restores the behavior I accidentally
changed when adding the hasattr method.
I've modified the data getter/setter in NDModel to call …
> Fix handling of default data array name

- jwst/transforms/tpcorr.py
This PR adresses issue https://github.com/spacetelescope/jwst/issues/2273 by making `TPCorr` work with `V2` and `V3` angles provided in arcseconds instead of the original degrees.
> Adjust TPCorr to work with V2, V3 angles in arcsec instead of degrees

- jwst/cube_build/cube_build_step.py
#2327 added computes the footprint of an ifu cube and updates `S_REGION` but it was wrong, failing regression tests [here](https://boyle.stsci.edu:8081/job/RT/job/JWST/210/testReport/jwst.tests_nightly.general.pipelines/test_mrs_spec3/test_spec3_pipeline1/).
I thought `Final_IFUCubeModel` is an `IFUCubeModel` because that's what it is after the result is saved to file and loaded. However, it is a `ModelContainer` in the code. The fix was tested locally on a single NRS exposure. Looking at the code I think it should work also for multiple cubes.
> fix footprint assignment in cube_build

- jwst/datamodels/__init__.py
- jwst/datamodels/arrays.py
- jwst/datamodels/container.py
- jwst/datamodels/fits_support.py
- jwst/datamodels/guidercal.py
- jwst/datamodels/guiderraw.py
- jwst/datamodels/level1b.py
- jwst/datamodels/make_header.py
- jwst/datamodels/model_base.py
- jwst/datamodels/pathloss.py
- jwst/datamodels/properties.py
- jwst/datamodels/resolution.py
- jwst/datamodels/schema_editor.py
- jwst/datamodels/schemas/core.schema.yaml
- jwst/datamodels/source_container.py
- jwst/datamodels/tests/test_fits.py
- jwst/datamodels/tests/test_make_header.py
- jwst/datamodels/tests/test_models.py
- jwst/datamodels/tests/test_open.py
- jwst/datamodels/tests/test_schema.py
- jwst/datamodels/util.py
- jwst/datamodels/wcs_ref_models.py
Clean up `flake8` problems pointed out in PR #2340 for datamodels.
- remove lots of unused imports
- remove python 2 code
- remove unused variables; don't use assignments if not needed
- fix bug in `model_base.py::set_fits_wcs()`
- fix bug in `ResolutionModel`
- fix bug in `tests/test_fits.py::test_from_fits()`
- remove two commented-out tests `test_from_fits_to_yaml()` and `test_from_fits_to_json()` that test no-longer-supported functionality
- fix bug in `tests/test_models.py::test_multislit_metadata()` and rename a test that was using the same name
- enable commented-out test `tests/test_schema.py::test_date2()`
- clarify the asserts in `tests/test_schema.py::test_dictionary_like()`
- re-enable and rename `tests/test_schema.py::test_multislit_append_string()`
- remove …
> PEP8 cleanup of datamodels

- jwst/source_catalog/__init__.py
- jwst/source_catalog/source_catalog.py
- jwst/tso_photometry/__init__.py
- jwst/tso_photometry/tso_photometry.py
- jwst/tso_photometry/tso_photometry_step.py
This PR:
* Removes version from `tso_photometry` and `source_catalog` steps (#2352)
* PEP8 fixes in both steps (part of #2340)
> Remove version and PEP8 fixes

- jwst/assign_wcs/nirspec.py
Addresses #2357.
This fixes a fairly serious bug in assign_wcs where the matchinf of slits and models in some transforms was not correct. Models are created for each slit in a given quadrant. This order was not preserved in the final output and the original ordering of the slits was kept. This has not shown in testing sofar because the only tests we have are for one open slitlet.
> Fix slits ordering

- jwst/datamodels/schemas/ifupost.schema.yaml
Testing of the scripts that generate the ifupost file and perhaps stricter checking in the pipeline revealed a problem with the ifupost schema. The schema included `additionalProperties=false` and this prevented a history entry to be added.
There's not problem with the current reference file.
> fix ifupost schema

- jwst/tweakreg/wcsimage.py
tweakreg inserts a new step in the WCS pipeline. It first copies WCS.pipeline and then modifies it. When WCS.pipeline is copied it uses the names of the frames and not the frame objects. This breaks resample because the frame attributes resample uses are missing.
Using strings as frames in GWCS is allowed as convenience. Frame objects are needed for full functionality. In the future this may be fixed in GWCS by implementing `insert_step` method. For now this implements a workaround.
Further resolves #2271
> create wcs frames in tweakreg

- jwst/outlier_detection/outlier_detection_spec.py
This call to `make_output_path` was never updated after an API change to the method, which replace the direct use of `DataModel` with just a `basepath`.
Resolves #2338
> Update for current usage of make_output_path

- jwst/tso_photometry/tso_photometry.py
Fixes #2396.
While debugging this, I also discovered an issue with the test data in
`jwcalibdev:/data4/jwst_test_data/pipelines/nircam_caltso3/`:
`jw93065002001_02101_00001_nrca1_calints.fits`
`jw93065002002_02101_00001_nrca1_calints.fits`
The images are 320x320 pixels, but the CRPIX values are (1024.5, 1024.5).  After discussing this with @hbushouse, I simply corrected the CRPIX values in the test data using the pixel values of the center of the source (which was *not* at the center of the 320x320 subarray).
> Fix error in tso_photometry

- CHANGES.rst
- jwst/datamodels/util.py
The recently introduced warning that is printed when the DATAMODL keyword is not present in a FITS file is a subtle change to the existing interface. This is because it precedes any warning produced when a FITS file is opened and confuses any code that might be trapping warning messages when a datamodel is opened. This update preserves the existing interface by moving the test to after the datamodel is opened, so any error or warning during the open takes precedence over it. This update changes nothing Other than changing the location of the warning in the output.
This change also adds a line about the warning to the CHANGES file.
> Move no model type warning in datamodels

- jwst/tests_nightly/general/pipelines/test_nrc_image3_2.py
Adds another calimage3 regression test that has ``tweakreg`` turned on. The test data use a 6-point dither pattern (3 primary, plus 2 sub-dithers at each primary), but all have the same WCS pointing. ``tweakreg`` is used to successfully recover the actual pointing offsets in the simulated images, using a larger than normal search radius. The data are simulated as a NIRCam GOODS-S field. Input and comparison test data files have been copied to the appropriate test directory on jwcalibdev.
> Add a calimage3 regression test that includes tweakreg

- jwst/datamodels/model_base.py
- jwst/datamodels/schema.py
- jwst/datamodels/tests/test_schema.py
- jwst/model_blender/blendrules.py
This is a proposed fix for the issue described in #2375. It is a bit rough at the moment, and will need to be updated to properly account for `oneOf` as well. It also could use some more thorough tests.
Also, with this fix, it seems like the name `flatten_combiners` is no longer appropriate. The real purpose of this function seems to be to merge external schema file references into a single schema. So maybe `merge_schemas` would be more appropriate.
cc @sosey
> Fix bug in flatten_combiners

- jwst/tests_nightly/general/niriss/test_nirisssoss2_pipeline.py
Fixes the problems with the current NIRISS SOSS calspec2 pipeline regression test. It's currently throwing an error because it can't find the expected type of output product (_calints), because the current data set used in the test has only NINTS=1 and no TSOVISIT keyword (to tell stpipe that it's TSO data). Even with the TSOVISIT keyword, this data set is completely inappropriate for SOSS mode, because of NINTS=1. So the test has been modified to use a new data set with NINTS=50 and TSOVISIT=T. It now produces _calints and _x1dints products, as it should, and is also a true test of the ``calwebb_tso_spec2`` pipeline config. The necessary input/output data files have been uploaded to the jwcalibdev `/data4/jwst_test_data/pipelines/` directory.
> Fix failing NIRISS SOSS spec2 reg test

- CHANGES.rst
- jwst/resample/resample_spec.py
When `resample_spec` creates an output frame, the wavelengths are done via tabular interpolation.  Both the forward transform (pixels to wavelength) and reverse transform (wavelength to pixels) need to be defined.  This fixes a bug in the reverse where for MIRI LRS fixed slit data, the wavelength is descending as a function of pixel index.  For `scipy.interpolate`, which is the underlying interpolation method used in the tabular models, the interpolation points need to be strictly ascending.
Resolves issue #2395.
> Fix bug in resample_spec wavelength reverse lookup table

- jwst/tests_nightly/general/niriss/test_nirisssoss2_pipeline.py
Fix a missing "/" in path to comparison file in the NIRISS SOSS calspec2 regression test.
> Fix typo in regression test

- jwst/pipeline/calwebb_detector1.py
- jwst/tests_nightly/general/miri/test_gain_naming.py
- jwst/tests_nightly/notebooks/gain_naming.ipynb
Ready-to-test #2341
The actual issue in #2341 arose from confusion over what output was being produced when the `gain_scale_step` was requested to save its data. Since the step is called twice, once on the integrated ramp, and once on the non-integrated ramp ("ints"), but without any other file specification, caused the second call to use the same suffix as the first, overwriting the first results.
`calwebb_detector1` is modified to explicitly defines two separate suffixes for the two calls, ensuring that the second does not overwrite the first.
> Explicitly define suffixes for the gain_scale output

- CHANGES.rst
- jwst/pipeline/calwebb_spec2.py
The spec2 pipeline has not had `resample_spec` run on MIRI fixed slit data for almost 2 years.  Now that `resample_spec` can be reliably run on MIRI data, we can now re-enable it, giving us test coverage for this mode as well.
Cleaned up the spec2 pipeline a bit to remove two unnecessary datamodel `copy()` operations and changed some variable names for clarity.
A potential bug was found in the following operations:
```
input.close()
return input
```
Nothing was done with the returned datamodel, but if `process()` did try to do something with it, it would (I believe) fail.  So I have removed the `close()` line.
> Enable resample_spec on MIR_LRS-FIXEDSLIT data in spec2 pipeline

- jwst/refpix/reference_pixels.py
This version of refpix.reference_pixels completely revises the memory usage of the algorithm, while also resulting in improved run-times (from 3m16s to 23s for 250,12,256,2048 NRCALONG simulated observation).
> Revamped refpix to be more efficient

- CHANGES.rst
- jwst/assign_wcs/nircam.py
- jwst/assign_wcs/util.py
- jwst/datamodels/schemas/wavelengthrange.schema.yaml
- jwst/extract_2d/extract_2d.py
- jwst/extract_2d/extract_2d_step.py
- jwst/extract_2d/grisms.py
***DO NOT MERGE THIS PR UNTIL AFTER SNAPSHOT FOR 0.10 IS TAKEN***
closes #1710,  closes #1235
related to #1756
This PR accomplishes several things:
* it reworks` assign_wcs` for the `NRC_TSGRISM` mode to always use the values for `CRPIX1` and `CRPIX2` as the source location. The new way to call the WCS object is:  `wcs(x, y, order)` which prints ra, dec, wavelength, order, where ra,dec is `CRVAL1, CRVAL2`.  The inverse transform is `wcs(wavelength, order)` which prints out x, y, order  using the same ra, dec values. 
* it implements `extract_2d` for the first time for this mode. Since there is a single source location for all exposures, no catalog of sources are needed. Hence, this does not use the same methods that the WFSS modes use to do extraction and is much simpler, and much faster. …
> Implements NRC_TSGRISM with set source location and extraction options

- CHANGES.rst
- jwst/pipeline/calwebb_spec2.py
closes #2459
I'm going to open a separate issue for the `grism_objects` discussed there as I see another bug with call flow for `extract_orders`
> enable extract_2d for NRC_TSGRISM in pipeline [#2549]

- CHANGES.rst
- jwst/extract_2d/extract_2d.py
- jwst/extract_2d/extract_2d_step.py
closes #2462 
local testing shows this is a decent fix, using the jwst-edit context with the updated rmap that the step wants for `nrc_tsgrism`. 
```
strun ../data/nircam/extract_2d.cfg ../data/tso_wcs_assigned_test.fits
2018-09-05 14:26:16,265 - stpipe.extract_2d - INFO - Extract2dStep instance created.
2018-09-05 14:26:16,293 - stpipe.extract_2d - INFO - Step extract_2d running with args ('../data/tso_wcs_assigned_test.fits',).
2018-09-05 14:26:23,133 - stpipe.extract_2d - INFO - EXP_TYPE is NRC_TSGRISM
2018-09-05 14:26:23,155 - stpipe.extract_2d - INFO - Using default order extraction from reference file
2018-09-05 14:26:23,230 - stpipe.extract_2d - INFO - xmin, xmax: 647.9255139717636 1845.7302759243282  ymin, ymax: 0 63.0
2018-09-05 14:26:25,774 - stpipe.extract_2d - INFO - WCS made …
```
> fix extract_2d highlevel call [#2462]

- jwst/pipeline/tests/helpers.py
- jwst/pipeline/tests/test_calwebb_image2.py
- jwst/pipeline/tests/test_calwebb_spec2.py
- jwst/pipeline/tests/test_calwebb_spec2_nrs_msa.py
- jwst/pipeline/tests/test_calwebb_spec3_mir_lrs_fixedslit.py
- jwst/pipeline/tests/test_calwebb_spec3_mir_mrs.py
- jwst/pipeline/tests/test_calwebb_spec3_mir_mrs_dither.py
- jwst/pipeline/tests/test_calwebb_spec3_nrs_msa.py
- jwst/pipeline/tests/test_nis_ami3.py
- jwst/pipeline/tests/test_nis_soss_tso3.py
- jwst/pipeline/tests/test_nrc_coron3.py
- jwst/pipeline/tests/test_nrc_detector1.py
- jwst/pipeline/tests/test_nrc_image3.py
- jwst/pipeline/tests/test_nrc_tso3.py
- jwst/pipeline/tests/test_nrs_spec2_bright_obj.py
- jwst/pipeline/tests/test_nrs_tso3.py
- jwst/pipeline/tests/test_wfs_combine.py
- jwst/stpipe/tests/util.py
- jwst/tests/helpers.py
At some point in PEP8 fixing, a fixture was removed from a number of tests. They are added back in, so that once #2445 is dealt with, there is consistency during the process.
> Add back in fixture mk_tmp_dirs

- CHANGES.rst
- jwst/extract_2d/extract_2d_step.py
- jwst/extract_2d/grisms.py
closes #2466 
* updates the int to integer type spec for extract_height
* fixes type specification for user-override extract_orders
For the `--extract_orders`, this allows the user to specify a list of orders to extract that will be used instead of the default in the reference file. The reference file specifies the orders to be extracted by filter. The override will extract the specified orders for any filter. 
This is currently an option in `NRC_TSGRISM`, the team only wants one order extracted, the reference file specifies the first order, if the user would instead like to extract the second order, the `extract_2d.cfg` file can be updated as such:
```
name = "extract_2d" 
class = "jwst.extract_2d.Extract2dStep"
extract_orders = 2,
```
and order 2 will be extracted for the input model …
> fix for command line extract_2d optional grism inputs [#2466]

- jwst/associations/asn_edit.py
- jwst/associations/tests/test_asn_edit.py
- scripts/asn_edit
This update adds a new command line script, supporting code in the associations directory, and tests to add or remove filenames from an association file. Only json format association files are supported.
> A new script to add or remove filenames from an association file

- jwst/tests_nightly/general/nirspec/test_spec2.py
- jwst/tests_nightly/general/pipelines/test_nirspec_fs_spec3.py
These tests are marked as xfail since the input data is not yet available for them.
Once data is available, they should be enabled.
> Mark xfail 3 NIRSpec regression tests [ci skip]

- CHANGES.rst
- jwst/fits_generator/create_dms_data.py
The GWA_TTIL keyword should be sanitized along with the GWA_XTIL and GWA_YTIL keywords, so that the datamodel doesn't throw a validation error.
Resolves #2493.
> Sanitize GWA_TTIL keyword for NIRSpec

- CHANGES.rst
- jwst/assign_wcs/assign_wcs.py
- jwst/assign_wcs/util.py
This PR adds the computation of the footprint of the entire Nirspec IFU on the sky. Previously the footprint was not computed in assign_wcs. Instead the one computed based on the SIAF model was kept.  The motivation of recomputing it here is to decrease the computational time in `cube_build`. Of course this would not have much effect on the calspec2 pipeline. It takes ~30 sec to compute it so it adds considerable time to cube_build when many observations are processed.
The wavelength range can be used as a spectral footprint. It can be obtained from
`model.meta.wcsinfo.wave_start` and `model.meta.wcsinfo.wave_end`.
@jemorrison
This doesn't need to go in 0.11.
> compute the NRS IFU footprint

- CHANGES.rst
- jwst/flatfield/flat_field.py
- jwst/flatfield/tests/test_find_dispaxis.py
Function `find_dispaxis` was added.  This determines the dispersion direction by comparing the rate at which wavelength changes from pixel to pixel, in the horizontal and vertical directions.  All pixels with non-NaN and non-zero values of wavelength are now used, rather than just three points near the middle of the image.
The function that combines the flat-field images (slowly varying with wavelength) with the tabular flat field (varying more quickly with wavelength) replaces the NaN or zero wavelength values with an average wavelength, to reduce interpolation problems near the edges of the bounding box.
See issue #2487.
> Improve the code for finding the dispersion direction

- jwst/pipeline/calwebb_image3.cfg
- jwst/pipeline/tweakreg.cfg
- jwst/tweakreg/tweakreg_step.py
The low source detection threshold SNR of 3.0 was causing spurious detections in `tweakreg`.  Many spurious sources would be detected and an incorrect alignment was computed.  Better to err on the side of caution and have a high detection threshold of 10.  If there are too few sources found at this higher detection threshold, then the step is skipped, which I believe is a desirable default for pipeline use.
Also made consistent between the .cfg and default spec the parameters
```
enforce_user_order = True
kernel_fwhm = 2.5
searchrad = 1.0
```
Could reviewer(s) confirm that these are reasonable defaults?  The point is to have them be consistent between the default config and the default spec.
Finally, `tweakreg` has been off in our default configuration for a long time.  Time turn turn it …
> Make tweakreg source detection threshold higher

- jwst/jump/jump.py
- jwst/jump/tests/test_twopoint_difference.py
- jwst/jump/twopoint_difference.py
- jwst/jump/yintercept.py
Also, converted `setup_cube()` function used in the two-point diff tests to a pytest fixture.
In support of #2340.
> PEP8 cleanup of jump step

- jwst/datamodels/schemas/guider_cal.schema.yaml
- jwst/datamodels/schemas/guider_raw.schema.yaml
The `bad_centroid_dq_flag` column in the guidestar table extension "FGS Centroid Packet" is actually being populated with Engineering values that are data type string, as opposed to the integer data type currently defined for that table column; updated the 2 guider schema.yaml files to instead accept strings. Addresses github issue: Schema update for guidestar centroid table column (#2416)
> Fix guidestar table bad_centroid_dq_flag column data type

- Jenkinsfile
- JenkinsfileRT
- conftest.py
- setup.py
The purpose here is to allow the integration of `ci_watson` ([repo](https://github.com/spacetelescope/ci_watson)) into our testing environment so that its Artifactory functionality can be used in the near future.
This should have no effect on any of our tests, currently.
The removed `pytest` CLI args `--slow` and `--bigdata` plus the `_jail` fixture are implemented in the `ci_watson` plugin and have identical functionality.
> Add ci_watson as a test build dependency

- jwst/datamodels/tests/test_models.py
- jwst/datamodels/tests/test_open.py
- jwst/datamodels/util.py
Datamodels currently issues a warning message when a new model is opened if that model does not have a DATAMODL header keyword. The code will issue this message even when a model is created from scratch using a shape or numpy array. This update only issues a warning message if the
datamodel is opened from a file or hdu with an associated file.
It also suppresses several warning messages in tests about the missing DATAMODL header keyword.
> Remove warning message when opening a model from a shape or array

- jwst/tweakreg/wcsimage.py
This PR undoes the temporary workaround implemented in https://github.com/spacetelescope/jwst/pull/2404 per https://github.com/spacetelescope/gwcs/pull/174#issuecomment-424439826
> Undo temporary workaround implemented in 2404

- .travis.yml
- jwst/__init__.py
- jwst/barshadow/__init__.py
- jwst/barshadow/bar_shadow.py
- jwst/barshadow/barshadow_step.py
- jwst/cal_ver_steps.py
- jwst/datamodels/schema.py
- jwst/dq_init/__init__.py
- jwst/engdblog/__init__.py
- jwst/engdblog/tests/test_engdblog.py
- jwst/extract_2d/nirspec.py
- jwst/model_blender/blendrules.py
- jwst/msaflagopen/__init__.py
- jwst/msaflagopen/msaflag_open.py
- jwst/pathloss/__init__.py
- jwst/pathloss/path_loss.py
- jwst/pathloss/pathloss_step.py
- jwst/pipeline/tests/helpers.py
- jwst/refpix/__init__.py
- jwst/refpix/irs2_subtract_reference.py
- jwst/refpix/reference_pixels.py
- jwst/resample/tests/test_interface.py
- jwst/tests/helpers.py
- jwst/wfs_combine/__init__.py
- setup.cfg
Ref #2340
These were all trivial so I fixed them in one PR.
After this PR is merged what's left in #2340 is `associations` , `jwpsf`, `ramp_fitting`, `fits_generator` and `exp_to_source`. I'll open a separate issue for them (for now they are ignored in setup.cfg). I'd like to merge this PR followed by #2340 so that Travis starts running the flake8 test. Otherwise every new PR has the potential to introduce new flake8 problems in steps that were already fixed.
> flake8 issues fixed

- jwst/assign_wcs/tests/test_util.py
- jwst/assign_wcs/util.py
- jwst/extract_2d/nirspec.py
- jwst/resample/resample_utils.py
Resolves #2549.
This also puts the calling sequence of `bounding_box_from_shape` back to just needing a shape passed to it instead of the full datamodel, as it was a while back.
I've also taken the liberty of pointing some code in `resample` to this version, and removed a duplicate function in `resample`.
> Fix bug in bounding_box_from_shape

- CHANGES.rst
- jwst/tweakreg/wcsimage.py
Attempt to fix #2548. This PR only adds error messages to the `_check_wcs_structure` method in order to facilitate debugging. I also fixed one "bug" - the way to get the names of all frames in the WCS pipeline is `wcs.available_frames`. The way it was done a list of frame objects was returned.
When I run the regression test now I get a different error. It is looking for a frame called `v2v3corr`. I thought at this point in the code `v2v3corr` should not be in the pipeline but I am not very familiar with the code. @mcara
```
Traceback (most recent call last):
File "scripts/strun", line 26, in <module>
step = Step.from_cmdline(sys.argv[1:])
File "/internal/1/astropy/jwst/jwst/stpipe/step.py", line 162, in from_cmdline
return cmdline.step_from_cmdline(args)
File …
```
> add error messages to check_wcs_structure

- jwst/datamodels/model_base.py
- jwst/datamodels/tests/test_models.py
An issue was raised during a meeting that datamodels was not correctly
validating schema items with the fits_required attribute. I did some
checking and found that fits_required is used in validation when
reading a fits file or deleting a model value. But it was not used in
validation when writing a model. The reason is that when writing the
code traverses the model, not the schema, so fields that are missing
in the model are not detected. I've added a new method,
validate_required_fields, to model_base.py that traverses the schema
and checks all fields where fits_required is true. This method is
called in save() before writing the file. It honors the usual flags,
pass_invalid_values and strict_validation.
I also added two tests to test_models.py to check the handling of
fits_required. …
> Add validate_required_fields to DataModel

- jwst/datamodels/schemas/core.schema.yaml
- jwst/datamodels/schemas/image.schema.yaml
- jwst/datamodels/schemas/lev3_prod.schema.yaml
- jwst/datamodels/schemas/wcsinfo.schema.yaml
Add new keywords requested in #2591 and #2592.
Also update many keyword title/comment fields to conform to the FITS standard recommendation that units appearing in keyword comments should be enclosed in **square brackets** at the **beginning** of the comment field, and use IAU-recommended units strings. This will cause LOTS of regression test failures (sorry about that).
> Keyword additions and changes

- jwst/tests_nightly/general/pipelines/test_nrs_fs_brightobj_spec2.py
Update the test_nrs_fs_brightobj_spec2 regression test module to use the new name of the cfg file, which PR #2639 changed from "calwebb_tso_spec2.cfg" to "calwebb_tso-spec2.cfg".
> Update reg test for new cfg name

- CHANGES.rst
- jwst/assign_wcs/pointing.py
- jwst/cube_build/blot_cube_build.py
- jwst/cube_build/cube_build.py
- jwst/cube_build/cube_build_io_util.py
- jwst/cube_build/cube_build_step.py
- jwst/cube_build/cube_cloud.py
- jwst/cube_build/ifu_cube.py
- jwst/cube_build/instrument_defaults.py
- jwst/datamodels/schemas/ifucube.schema.yaml
- jwst/datamodels/schemas/wcsinfo.schema.yaml
This PR build can create cubes with a nonlinear wavelength dimension. The wavelength bins to use in
the IFU cube are read in from the CUBEPAR reference file.  These types of IFU cubes are created when the input data is from different bands (ie. Ch 1 Short and Ch 1 Medium or for NIRSPEC different filters for the same grating). 
This PR also uses the wavelength ranges given in the CUBEPAR reference file to build cube from
a single band rather than determining the maximum and minimum values from the data. This PR will result in the regression tests failing because the min and max wavelength of the ifucube are slightly different. 
When an ifucube is made from more than 1 band then additional table extensions in the CUBEPARS are used to define the wavelength sampling and the roi to use for …
> Nonlinear wavelength for cube_build

- jwst/datamodels/schemas/core.schema.yaml
Ever since #2595 was merged, the regression test "test_mrs_spec3" has been throwing schema validation warnings concerning the DATE-BEG keyword, which is really odd, because that keyword doesn't even exist yet in any of our data products. Somehow the schema validation problem is also causing a failure later in the pipeline run itself. Removing the "anyOf" block in the definitions of the DATE-BEG and DATE-END keywords and instead defining their data types as just plain string fixes the problem. So those data type defs are being updated in order to avoid the spec3 error. We don't use or need the datetime format specification right now anyway for those 2 keywords.
> Remove schema time format specs

- CHANGES.rst
- jwst/flatfield/flat_field.py
- jwst/flatfield/tests/test_clean_wl.py
Function `combine_fast_slow` now calls a new function `clean_wl`, which returns a copy of the wavelength array with zero or NaN values replaced with an average.  The width of a pixel in wavelength units is computed by subtracting the wavelengths of adjacent pixels, but now this gives better results for pixels that are near the border between good wavelength values and NaN values.  Before calling `g_average`, there's a check that the wavelength is positive.
A check was added to verify that the wavelengths read from the fast-variation table are increasing, and a warning is logged if they are not.
Function `wl_interpolate` (used when computing the fast-variation flat) now returns the first or last element of the flat array if the wavelength is outside the range of the wavelength array. …
> Changed the handling of zero wavelengths for NIRSpec data.

- CHANGES.rst
- jwst/lib/reffile_utils.py
Updated the reffiles library utilities to NOT issue a warning when SUBSIZE2 != data.shape[-2] for the case of NIRSpec IRS2 readouts. It's expected that in this situation SUBSIZE2=2048 while the actual data array is 3200 pixels.
> Remove IRS2 data size warnings

- CHANGES.rst
- jwst/pipeline/calwebb_dark.cfg
- jwst/pipeline/calwebb_dark.py
- jwst/pipeline/calwebb_detector1.py
Updated the order of MIRI steps in level-2a processing to be consistent with JCCWG specs, which boils down to moving `firstframe` and `lastframe` to be ahead of `linearity` and `rscd`. Also updated the `calwebb_dark` pipeline to include the `firstframe` step for MIRI.
Fixes #1454.
> Update MIRI detector1 step order

- CHANGES.rst
- jwst/pipeline/calwebb_image2.py
- jwst/pipeline/calwebb_spec2.py
- jwst/pipeline/tests/test_calwebb_image2.py
- jwst/pipeline/tests/test_calwebb_spec2.py
- jwst/stpipe/step.py
A regression was reported, [JP-440](https://jira.stsci.edu/browse/JP-440), where `Image2Pipeline` no longer returned its primary, or `cal` result, when called programmatically.
This occurred when `Image2Pipeline`, along with `Spec2Pipeline`, was modified to handle associations with multiple products; returning results was removed.
Initial consideration was to remove multi-product handling, #2674. However, this would cause other inconsistencies in interface, usage, etc. In particular, multiple product handling is in use and works as expected when all results are written to files.
So, this PR takes the more direct tack: Before, `Image2Pipeline`, for an input, returned an output. Hence, now that `Image2Pipeline` handles multiple inputs, it should return a list of results.
`Spec2Pipeline` …
> Spec2Pipeline and Image2Pipeline returns results

- jwst/datamodels/schemas/core.schema.yaml
- jwst/datamodels/schemas/keyword_psubarray.schema.yaml
- jwst/datamodels/schemas/subarray.schema.yaml
#2667 removed the FGS subarray names "8X8", "32X32", "128X128", and "2048X64" from the allowed values lists in our schemas, because those names are not in the latest list of "official" subarray names for the PRD. But it turns out the FGS values included in that list only cover the science exposure modes. The names listed above are used for the guiding modes and hence need to be reinstated.
Fixes #2560.
> Reinstate FGS guider subarray names

- jwst/tests_nightly/general/pipelines/test_nrs_msa_spec2.py
#2676 changed the behavior for the saving of cal products from the `calwebb_spec2` (and `calwebb_image2`) pipeline, which caused this regression test to no longer produce a _cal product on disk. Added the output file name to the pipeline param list to fix.
> Fix calspec2 reg test file saving

- jwst/datamodels/container.py
- jwst/datamodels/model_base.py
ASDF just introduced new functionality that causes arrays below a particular threshold size to be automatically stored inline rather than in internal blocks (see https://github.com/spacetelescope/asdf/pull/557).
This has potential performance issues for the pipeline, and it also may affect comparisons with existing reference files. This PR updates the pipeline to make use of the new `inline_threshold` parameter introduced by ASDF to ensure that all arrays continue to be stored in internal blocks for now.
**EDIT**: some initial discussion of this took place in #2692.
> Set default inline threshold for ASDF to 0

- docs/jwst/dark_current/arguments.rst
- docs/jwst/dark_current/dark_selection.rst
- docs/jwst/dark_current/dark_specific.rst
- docs/jwst/dark_current/reference_files.rst
Updated reference file info in the `dark_current` step docs.
In partial fulfillment of #2675.
> Updates to dark step reffile docs

- jwst/datamodels/__init__.py
- jwst/datamodels/nirspec_flat.py
- jwst/datamodels/tests/test_schema.py
- jwst/datamodels/tsophot.py
- jwst/datamodels/wcs_ref_models.py
Since we ran into some bugs with the `validate()` method and the schema for other datamodels, here is a simple test to verify that at a minimum, all datamodels can be instantiated.
The test caught a bug in `TsoPhotModel` where two keywords were being assigned patterns via `__init__`, but the schema for those keywords do not allow those patterns.
Also removed `NRSFlatModel`, which was an intermediate subclass between `DataModel` and `NirspecFlatModel`.  There was a bug in the schema name, and it added no new features to its subclasses.
>  Add test that checks if all datamodels can be initialized

- CHANGES.rst
- jwst/datamodels/photom.py
- jwst/datamodels/schemas/mirimg_photom.schema.yaml
Added a new column "relresperror" to the MIRI Imager/LRS photom reference file schema, to accommodate uncertainties in the wavelength-dependent response values, as requested by the MIRI IDT. They need this update in order to create ref files for their CDP-7 delivery in Nov. 2018. So it should be included in the next available B7.2 patch.
Fixes #2712.
> Add relresperror column to MIRI photom schema

- CHANGES.rst
- jwst/datamodels/photom.py
- jwst/datamodels/schemas/mirimg_photom.schema.yaml
Reverts spacetelescope/jwst#2721. Backing this out for now, because it's causing errors with all the current MIRI PHOTOM ref files in CRDS, which don't have the extra column in the table. Don't need it for 0.12.1. Will reinstate later after B7.2 delivery and we figure out how to get the existing MIRI PHOTOM ref files updated (they may get updated naturally through the team's upcoming CDP-7 delivery).
> Revert "Add relresperror column to MIRI photom schema"

- jwst/cube_build/cube_build_step.py
- jwst/cube_build/ifu_cube.py
When the wavelength dimension  is non-linear the roiw value is actually a table of values and not
a single value. When the wavelength dimension is non-linear self.roiw = None and writing
this value to the header as float(self.roiw) resulted in an error. 
This value is needed in the header when running in 'single' mode to
support background matching and outlier detector (blotting). Single mode will always
produce linear wavelength dimension ifucubes which have a single value in roiw.
This PR populates self.roiw with the mean of the roiw array when the wavelength dimension is non-linear.
> fixed error in writting self.roiw to header

- jwst/tweakreg/wcsimage.py
This is an obvious typo that needs to be fixed. I am not sure though whether this is going to fix https://github.com/spacetelescope/jwst/issues/2746 by itself (though it might, depending on detected points).
CC: @stscieisenhamer
> Fix a typo in branching by number of points

- CHANGES.rst
- jwst/lib/reffile_utils.py
A few more minor updates to the reffile_utils function `ref_matches_sci` for proper handling of NIRSpec IRS^2 readout exposures. The comparison of the science exposure size (2048 x 3200) to the reference file size (2048 x 2048) had been coming back as a mismatch and hence the pipeline thought it had to do a subarray extraction. But this mismatch in array sizes is expected and hence should be considered a match (`ref_matches_sci` returns True). Separated the comparison of x-axis and y-axis sizes, because the IRS2 mode only affects the y-size, just to make the logic for handling IRS2 easier.
> Fix reffile util for NRS IRS2 exposures

- CHANGES.rst
- jwst/assign_wcs/nirspec.py
- jwst/extract_2d/extract_2d.py
assign_wcs should run the imaging WCS pipeline when grating=MIRROR. The specific case in DMS is
```
EXP_TYPE=NRS_LAMP
GRATING=MIRRROR
```
This was processed as a spectral WCS based on EXP_TYPE only.
Related to #2745.
> NRS grating=MIRROR should trigger the imaging pipeline

- JenkinsfileRT
@rendinam, you noticed this inconsistency yesterday.  I'm fixing it today.
This should get the data files from the failed tests uploaded to Artifactory.
> Make pytest basetemp consistent so results upload to Artifactory

- CHANGES.rst
- jwst/flatfield/flat_field.py
There are several components for the NIRSpec flat field.  For each section of the instrument (the fore-optics, the spectrograph, and the detector), there can be both a fast variation (with wavelength) and a slow variation component.  For a given pixel of the science data, it may be that the wavelength of the science data is undefined, or the wavelength might be out of range for one or more components of the flat field, or the pixel can be flagged as bad in the reference file for a component.  In any such case, the flat field to be applied to the data will be set to 1, and the associated data quality array will be non-zero, such as `UNDEFINED_FLAT` or `NO_FLAT_FIELD`.  See issue #2677.
> No extrapolation for NIRSpec flat field

- docs/jwst/ami/reference_files.rst
- docs/jwst/coron/reference_files.rst
- docs/jwst/cube_build/reference_files.rst
- docs/jwst/dark_current/reference_files.rst
- docs/jwst/fringe/reference_files.rst
- docs/jwst/imprint/README
- docs/jwst/ipc/README
- docs/jwst/ipc/index.rst
- docs/jwst/ipc/ipc_selection.rst
- docs/jwst/ipc/reference_files.rst
- docs/jwst/linearity/README
- docs/jwst/linearity/index.rst
- docs/jwst/linearity/linearity_selection.rst
- docs/jwst/linearity/reference_files.rst
- docs/jwst/saturation/reference_files.rst
Updated the reference file info in the `ipc` and `linearity` step docs, for the new consistent formatting of reffile docs.
> Reference file doc updates for IPC and Linearity

- CHANGES.rst
- jwst/tweakreg/imalign.py
- jwst/tweakreg/wcsimage.py
This PR addresses the issue https://github.com/spacetelescope/jwst/issues/2746. However, it will only work (tests will pass *tweakreg* stage) only if https://github.com/spacetelescope/jwst/pull/2796 is merged as well.
Unfortunately this PR makes algorithm a little inefficient when image catalogs contain 1 or two stars. Optimization can be addressed later if need be. For now, IMO, this should be robust enough to work.
CC: @hbushouse @stscieisenhamer @stscicrawford
> Fix logic for computing catalog footprints

- jwst/tweakreg/tweakreg_step.py
This fixes a bug introduced in the last PR: https://github.com/spacetelescope/jwst/pull/2796/files#diff-2e9e74c1671d12f560a63aad166ec226R73 - I forgot to adjust parameter numbering.
CC: @hbushouse
> Fixes a bug in printing a log message introduced in the last PR

- CHANGES.rst
- jwst/lib/suffix.py
- jwst/pipeline/tweakreg.cfg
- jwst/tweakreg/tweakreg_catalog.py
- jwst/tweakreg/tweakreg_step.py
This PR adds two new parameters to `tweakreg_step` star object detection algorithm to allow source selection/filtering by:
1. `peakmax` - maximum peak pixel value for selecting stars.
2. `brightest` - number of brightest objects to keep.
The rationale for these parameters is that `peakmax` could allow automatic exclusion of sources that reach a known saturation level of the detector and `brightest` would keep top `brightest` stars thus eliminating the faintest objects that could be false detections.
CC: @hbushouse @larrybradley
> Add filtering/selection by peakmax and brightest

- jwst/datamodels/reference.py
- jwst/datamodels/schemas/nirspec_flat.schema.yaml
- jwst/datamodels/schemas/superbias.schema.yaml
- Adds P_EXP_TY to NIRSpec Flat reffile
- Adds P_READPA to SuperBias reffile
- cleans up the `self.validate()` method so the warning is useful and the error message is not emitted twice.
Resolves #2684.
> Add missing reference file keywords to reffile schemas

- .travis.yml
- Jenkinsfile
- JenkinsfileRT
- jwst/assign_wcs/niriss.py
- jwst/assign_wcs/nirspec.py
- jwst/csv_tools/csvconvert.py
- jwst/datamodels/schema_editor.py
- jwst/datamodels/tsophot.py
- jwst/emission/emission.py
- jwst/lib/suffix.py
- jwst/pipeline/calwebb_spec2.py
- jwst/tests_nightly/general/nircam/test_nrc_image3_1.py
- jwst/transforms/models.py
It seems masked arrays are broken in some way in `numpy 1.15.3`.  Seeing if this will fix our CI tests.
> Don't use numpy 1.15.3 in testing

- Jenkinsfile
This is to resolve the couple of ssbjenkins CI failures we were seeing on Nov 5, where it was still, for some reason trying to pull in `numpy 1.15.3`.  It seems conda resolving is a moving target.
> Only list numpy once in Jenkinsfile conda dependencies

- jwst/exp_to_source/tests/data/jwst_nod1_cal.fits
- jwst/exp_to_source/tests/data/jwst_nod2_cal.fits
- jwst/exp_to_source/tests/data/jwst_nod3_cal.fits
- jwst/exp_to_source/tests/data/sources/reduce_dataset.ipynb
WCS tags were removed from ASDF in https://github.com/spacetelescope/asdf/pull/593, and they have lived in the `gwcs` package now for a while.  Now they need to be referenced as such.
Test input files here are regenerated using a recent version of `gwcs` and `asdf`.  Now the tags point to GWCS instead of ASDF WCS.
This should fix the current failures in our CI testing.
> Fix test_exp_to_source test data

- CHANGES.rst
- jwst/skymatch/skyimage.py
- jwst/skymatch/skymatch.py
- jwst/skymatch/skymatch_step.py
This PR makes `skymatch` not to fail when images do not overlap. This addresses the failure in `skymatch` reported in  https://github.com/spacetelescope/jwst/pull/2796#issue-226360537 likely occurring either because images have all pixels flagged as bad or the parts that are "good" do not overlap.
After this PR, `skymatch` will "succeed" but it will set `meta.cal_step.skymatch = "SKIPPED"` for images for which sky could not have been computed.
> Make skymatch not fail in match mode when images do not overlap

- jwst/associations/lib/dms_base.py
The exptype NRS_BOTA was removed in #2772, but not here.
This was causing a validation warning in one of our unit tests:
```
jwst/lib/tests/test_pipe_utils.py::test_is_tso_from_exptype[nrs_bota-False]
/Users/jdavies/dev/jwst/jwst/datamodels/validate.py:35: ValidationWarning: While validating type the following error occurred:
'NRS_BOTA' is not one of ['FGS_DARK', 'FGS_FOCUS', 'FGS_IMAGE', 'FGS_INTFLAT', 'FGS_SKYFLAT', 'FGS_ACQ1', 'FGS_ACQ2', 'FGS_FINEGUIDE', 'FGS_ID-IMAGE', 'FGS_ID-STACK', 'FGS_TRACK', 'MIR_4QPM', 'MIR_CORONCAL', 'MIR_DARKALL', 'MIR_DARKIMG', 'MIR_DARKMRS', 'MIR_FLATALL', 'MIR_FLATIMAGE', 'MIR_FLATIMAGE-EXT', 'MIR_FLATMRS', 'MIR_FLATMRS-EXT', 'MIR_IMAGE', 'MIR_LRS-FIXEDSLIT', 'MIR_LRS-SLITLESS', 'MIR_LYOT', 'MIR_MRS', 'MIR_TACQ', 'NIS_AMI', 'NIS_DARK', 'NIS_EXTCAL', …
```
> Remove NRS_BOTA from dms_base

- docs/jwst/assign_wcs/asdf-howto.rst
- jwst/assign_wcs/niriss.py
- jwst/datamodels/model_base.py
This will take effect once https://github.com/spacetelescope/asdf/pull/579 is merged, but there's no harm in making this change now.
This closes #2795.
> Remove soon-to-be-deprecated usage of AsdfFile.open

- docs/jwst/assign_wcs/asdf-howto.rst
- jwst/assign_wcs/niriss.py
- jwst/datamodels/model_base.py
Reverts spacetelescope/jwst#2814
> Revert "Remove soon-to-be-deprecated usage of AsdfFile.open"

- conftest.py
- jwst/conftest.py
- setup.cfg
Having pytest plugins anywhere except the top level `conftest.py` has been deprecated since `pytest 3.5`.  We've been seeing this warning for a while:
```
conftest.py:0: RemovedInPytest4Warning: Defining pytest_plugins in a non-top-level conftest is deprecated, because it affects the entire directory tree in a non-explicit way.
Please move it to the top level conftest file instead.
```
This PR resolves it.
We currently use the `asdf` schema tester pytest plugin to make sure our datamodel schemas are valid YAML.
I'm also adding the `scripts/` subdir to our pytest ignore directory, as in order to parse the `set_bary_helio_times.py` script, the environment variable JPL_EPHEMERIS needs to be set, and one gets a pytest collection error when one doesn't.  We started seeing this collection error …
> Define pytest_plugins in top level conftest.py

- jwst/datamodels/container.py
- jwst/datamodels/fits_support.py
- jwst/datamodels/model_base.py
- jwst/datamodels/tests/test_models.py
Asdf supports two flags, ignore_version_mismatch and gnore_unrecognized_flag, when creating a new asdf file. Part of creating a new datamodel is opening an asdf file, either natively or as embedded in a FITS extension. This update passes these two flags from the DataModel argument list to the call that opens or creates an asdf file. The result is better control of the warning messages produced by asdf.
Resolves #1215.
> Support asdf flags when creating a new datamodel

- jwst/dq_init/tests/test_dq_init.py
Since a `MaskModel` reffile is generated on the fly in 2 of the `dq_init` tests, and it's required keywords such as
```
meta.description
meta.telescope
meta.reftype
meta.author
meta.pedigree
meta.useafter
```
are not populated, we get validation warnings.  These keywords are there for CRDS purposes and are not needed in the test, so let's just filter out these warnings.
> Filter out reffile keyword validation warnings out of dq_init tests

- docs/jwst/saturation/reference_files.rst
- docs/jwst/straylight/reference_files.rst
- docs/jwst/straylight/straymask_selection.rst
- docs/jwst/superbias/reference_files.rst
- docs/jwst/superbias/superbias_selection.rst
Update the reference file docs for the `straylight` and `superbias` steps, for #2675. Also contains a minor fix for the previous updates to `saturation` reffile docs. Reviewers: feel free to only review the docs for your steps.
> Update ref file docs for straylight and superbias

- .travis.yml
- Jenkinsfile
- JenkinsfileRT
`dask` is not a dependency of `jwst`, yet it is listed as one in our CI scripts.  As such, it brings in a bunch of its own dependencies and probably makes our CI builds take longer.  Any ideas why it was added @jhunkeler?
This PR removes it.
> Remove dask dependency

- jwst/tests/base_classes.py
- jwst/tests/compare_outputs.py
- jwst/tests_nightly/general/miri/test_miri_steps_single.py
This implements auto-upload of failed test results files (FITS output files) to Artifactory for our nightly regression tests on Jenkins.  An example of this is here
https://boyle.stsci.edu:8081/job/RT/job/JWST-jdavies/62/
and the artifacts from the failed tests are linked via the Artifactory Build Info link from above
https://bytesalad.stsci.edu/artifactory/webapp/#/artifacts/browse/tree/General/jwst-pipeline-results/2018-11-24/jenkins-RT-JWST-jdavies-62
I've pulled out 2 functions from `ci_watson` and put them here in the `jwst` repository.  Will be modifying them further as we get experience using them.  Eventually, the can go back into `ci_watson` in the updated form if that is useful for other `ci_watson` users.
> Enable test data from failed RT tests to be uploaded to Artifactory

- jwst/datamodels/schemas/nirspec_ifucubepars.schema.yaml
Updated the nirspec_cubepars schema to have the correct name associated with DISPERSER.
The code for reading in the reference file already was updated with DISPERSER.
> fix nirspec cubepars schema

- CHANGES.rst
- jwst/datamodels/schemas/slitdata.schema.yaml
- jwst/extract_1d/extract.py
'NRC_TSGRISM' was added to `WFSS_EXPTYPES`, the list of exposure types that are WFSS/GRISM types.
The `SlitDataModel` schema was modified to specify that the wavelength attribute should be two-dimensional, and that the default value is zero.
See issue #2898.
> Improve support for WFSS data.

- jwst/lib/tests/test_engdb_mock.py
This should get rid of the following warnings we've been seeing in our unit tests for a long time now:
```
jwst/lib/tests/test_engdb_mock.py::test_cache_end_data
./site-packages/astropy/_erfa/core.py:115: ErfaWarning: ERFA function "d2dtf" yielded 1 of "dubious year (Note 5)"
warnings.warn('ERFA function "' + func_name + '" yielded ' + wmsg, ErfaWarning)
```
> Filter out ERFA warnings for times far into the future in engdb test

- CHANGES.rst
- docs/jwst/refpix/description.rst
In the description of IRS2 readout, I had written that it took one microsecond to read one pixel.  The time is actually closer to 10 microseconds.
> Fix mistake in the time to read one detector pixel.

- jwst/ami/ami_analyze.py
- jwst/ami/nrm_consts.py
- jwst/ami/nrm_model.py
- jwst/ami/utils.py
- jwst/ami/webb_psf.py
- jwst/pipeline/calwebb_ami3.py
- jwst/tests_nightly/general/niriss/test_niriss_steps.py
- jwst/tests_nightly/general/niriss/test_niriss_steps_single.py
Also:
-  PEP8 cleanup of the AMI class and module names
- close datamodels in the ami3 pipeline
Addresses #1988 and #2893.
> Use double-precision in AMI analyze and pipeline

- src/tweakreg/carrutils.c
Fixes a `DeprecationWarning` seen in python 3.7:
```
jwst/tests_nightly/general/nircam/test_nrc_image3_1.py::TestImage3Pipeline1::test_image3_pipeline2
/Users/jdavies/dev/jwst/jwst/tweakreg/matchutils.py:74: DeprecationWarning: PyArray_FromDims: use PyArray_SimpleNew.
refxy.astype(np.float32), searchrad)
```
> Use PyArray_SimpleNew instead of deprecated PyArray_FromDims

- README.md
- docs/jwst/introduction.rst
- setup.cfg
- setup.py
In support of #2176 the `author_email` entries have been removed from `setup` and instead the web portal for jwst help has been added to both the README and the introductory doc.
CRDS_CONTEXT numbers have been added to the DMS Build Info table in the README, to address #2744.
> Update help and CRDS_CONTEXT info

- jwst/coron/imageregistration.py
- jwst/coron/klip.py
- jwst/coron/klip_step.py
- jwst/coron/stack_refs.py
- jwst/tests_nightly/general/nircam/test_coron3_1.py
This is a small change to use double-precision floats where they might be needed in key areas of `Coron3Pipeline`.
This also updates the regression test for this module (which is currently failing).
Hopefully the changes here will make the code more robust to upstream changes in numpy, and make the test more reliable.
Seems to resolve #2893.
> Use float64 in coron3 pipeline

- jwst/tests/compare_outputs.py
This changes the behavior of our regression tests by turning off renaming the test output to be the new truth file (which currently overwrites the actual truth file).  This also adds a segregated `truth` directory inside the test output dir.
This will make comparing the test output with the truth much easier, as both will be located in the test output directory for failed tests.
Also cleans up the test log to give abspaths to output and truth files, so they can easily be found in the output traceback.
> Don't rename failed test outputs; segregate truth files in test dir

- src/tweakreg/carrutils.c
This should fix the problems seen in the following regression test:
https://boyle.stsci.edu:8081/job/RT/job/JWST/lastCompletedBuild/testReport/jwst.tests_nightly.general.nircam.test_nrc_image3_1/TestImage3Pipeline1/test_image3_pipeline2/
Fixes #2982.
> Initialize PyArrayObject in carrutils.c

- docs/jwst/reset/description.rst
Added a note to the top of the `reset` step docs to indicate that it's not currently used, but likely to be reinstated in the future.
Fixes #2874.
> Add note to indicate reset step not currently used

- README.md
- ci_watson is now included in the dependencies that get installed
with the `jwst` conda package
- It is more reliable to point TEST_BIGDATA to our artifactory
server, as the state of `/grp/jwst/ssb/jwst_test_data` may or may
not be in sync.  Currently.
- Add info about running specific regression tests and using `--basetemp`
> Update README.md with RT test running info

- CHANGES.rst
- jwst/extract_2d/grisms.py
This fixes #2978 and closes #2979 in favor of using the update method.
> Move update of meta info to the MultiSlitModel instead of the SlitModels it contains

- jwst/tests_nightly/general/niriss/test_nis_wfss_spec2.py
This encourages the test to run again, see https://github.com/spacetelescope/jwst/pull/2988 and accept after it has been merged.
> remove xfail from wfss nightly test

- CHANGES.rst
- jwst/assign_wcs/fgs.py
- jwst/assign_wcs/miri.py
- jwst/assign_wcs/nircam.py
- jwst/assign_wcs/niriss.py
- jwst/assign_wcs/tests/test_util.py
- jwst/assign_wcs/util.py
Currently `assign_wcs.util.subarray_transform` returns a `Shift(xstart) & Shift(ystart)` transform  even for full frame observations (`Shift(0) & Shift(0)`. This transform is prepended to the WCS forward transform, e.g. the distortion. In the case of full frame observations this becomes a problem when the bounding box is attached to the transform in the reference file because then it is overwritten. In addition there are two unnecessary transforms prepended to the pipeline. 
This PR changes the logic to:
- if `subarray.xstart` and `subarray.ystart` are not `None` or `1`
- prepend a transofrm (shift(xtsrat) & Shft(ystart)
- change the bounding box to ((0, xstart), (0, ystart))
- if one of `xstart` or `ystart` is not None or `1` (e.g. `ystart`
- prepend Identity(1) & Shift(ystart)
- change …
> refactor subarray transform

- src/tweakreg/carrutils.c
The fix in #2948 and #2982 fills the newly allocated arrays before checking the returned pointer thus making the check pointless and the code less reliable.
Pointer check should be moved before array fill operation.
> Array should be filled after pointer validity check, not before

- jwst/lib/set_telescope_pointing.py
- jwst/lib/tests/test_set_telescope_pointing.py
Include allow undefined SIAF information in headers when `allow-default` is specified.
> Allow undefined SIAF information

- jwst/tests_nightly/general/miri/test_miri_steps_single.py
The regression test
https://boyle.stsci.edu:8081/job/RT/job/JWST/93/testReport/junit/jwst.tests_nightly.general.miri.test_miri_steps_single/TestMIRISetPointing/test_miri_setpointing/
was failing because pointing mnemonics are not available in the database for the dates of this observation.  A default pointing will be generated based on the target RA/Dec only if `allow_defaults=True` is set.  It is `False` by default.
> Set allow_default=True in set_telescope_pointing regression test

- docs/jwst/assign_wcs/asdf-howto.rst
- docs/jwst/assign_wcs/main.rst
- docs/jwst/associations/association_reference.rst
- docs/jwst/datamodels/metadata.rst
- docs/jwst/datamodels/models.rst
- docs/jwst/extract_2d/main.rst
- docs/jwst/references_general/photom_reffile.rst
- docs/jwst/stpipe/devel_io_design.rst
- docs/jwst/stpipe/user_step.rst
- setup.cfg
Fixes #2806 
I am not familiar enough with the code to fix the remaining issues.
Perhaps @jdavies-st or @stscieisenhamer 
```
067 
068     >>> from jwst.stpipe import cleanup
UNEXPECTED EXCEPTION: ImportError("cannot import name 'cleanup'",)
Traceback (most recent call last):
File "/anaconda3/envs/jwstdev/lib/python3.6/doctest.py", line 1330, in __run
compileflags, 1), test.globs
File "<doctest user_step.rst[0]>", line 1, in <module>
ImportError: cannot import name 'cleanup'
/Users/dencheva/dev/jwst/docs/jwst/stpipe/user_step.rst:68: UnexpectedException
```
@hbushouse or @philhodge for this one? I think an `order` field is missing. What would be 
correct values in this case?
```
__________ [doctest] docs/jwst/references_general/photom_reffile.rst ___________
242  >>> import numpy as np …
```
> fix examples in documentation

- CHANGES.rst
- jwst/assign_wcs/fgs.py
- jwst/assign_wcs/miri.py
- jwst/assign_wcs/nircam.py
- jwst/assign_wcs/niriss.py
- jwst/assign_wcs/tests/test_util.py
- jwst/assign_wcs/util.py
- jwst/extract_2d/grisms.py
- jwst/extract_2d/nirspec.py
- jwst/resample/resample_spec.py
- jwst/resample/resample_utils.py
This PR creates a new function in `assign_wcs.util` called `bounding_box_for_transform` which returns the correctly arranged tuple for attaching to a transform.
It also renames the current `assign_wcs.util.bounding_box_from_shape` to `bounding_box_for_wcs`, which still returns the tuple in (x,y) order.
The names made sense to me, but this is up for discussion.  see #3013
> make bounding_box clearer

- jwst/lib/engdb_tools.py
- jwst/lib/set_telescope_pointing.py
- jwst/lib/tests/test_engdb_tools.py
- jwst/lib/tests/test_set_telescope_pointing.py
A previous PR updated how the engineering database URL can be specified. However, that PR neglected to update the logging of the source URL properly. This fixes that oversight.
Also added is the change of the default database to coincide with the new organization of the strings, moving towards a constant db location.
> Fix DB source logging issue and update default DB url

- CHANGES.rst
- jwst/extract_1d/extract.py
Function find_dispaxis in extract.py was modified to also test whether the difference in wavelengths in the horizontal direction was exactly equal to the difference in wavelengths in the vertical direction.  Closes #3031.
> Check for constant wavelengths

- .rtd-environment.yml
So this fixes the build.  Basically, peg `python` and `numpy` in the conda env, and then do all other dependencies via `pip`.
The build results of this PR are here
https://readthedocs.org/projects/jwsttest/builds/8396900/
> Fix our RTD documentation builds

- README.md
Updated the jwst pkg vs. DMS build table to include info for the B7.2.1 (0.12.3) release.
> Update README for B7.2.1 patch release

- CHANGES.rst
- jwst/tweakreg/linearfit.py
This increases the accuracy of matrix inversion by two orders of magnitude (from ~10 digits to ~12 digits). The fix in this PR is a quick fix.
> Revert to numpy.linalg for matrix inversion

- CHANGES.rst
- jwst/assign_wcs/fgs.py
- jwst/assign_wcs/miri.py
- jwst/assign_wcs/nircam.py
- jwst/assign_wcs/niriss.py
- jwst/assign_wcs/tests/test_util.py
- jwst/assign_wcs/util.py
This PR is a follow-up to https://github.com/spacetelescope/jwst/pull/3014#issuecomment-454909182 and simplifies the code for `transform_bbox_from_datamodel`.
However, I would suggest a further simplification: combine three functions into a single one:
```python
def to_bbox(a, order='yx'):
if order not in ('xy', 'yx'):
raise ValueError("Unsupported 'order' value")
try:
a = a.data.shape
except AttributeError:
pass
bbox = ((-0.5, a[-2] - 0.5), (-0.5, a[-1] - 0.5))
return bbox if order == 'yx' else bbox[::-1]
```
The `try-except` block above can be replaced with an `if isinstance()`.
> Simplify transform_bbox_from_datamodel

- jwst/associations/tests/test_asn_edit.py
Files that tests leave behind should no longer be dumped into `jwst/associations/tests/` now.
Addresses one aspect of #3053.
> Clean up asn_edit tests

- jwst/ramp_fitting/tests/test_ramp_fit.py
Add 3 unit tests motivated by recent test reports, which test MIRI data in which the 1st and last groups are flagged as DO_NOT_USE for the group DQ, tests a ramp having a CR-affected read just after the initial DO_NOT_USE, verifies calculations for a ramp having both a very long segment and very short segment, and verify the results for ramps having their pixeldq = DO_NOT_USE.
> Add MIRI ramp_fit unit tests

- jwst/ramp_fitting/ramp_fit.py
- jwst/ramp_fitting/utils.py
Temporarily suppress benign arithmetic warnings (divide by zero or operating on a NaN) in statements where they are expected to occur, then re-enable as soon afterwards as appropriate.   Calculations from these statements that result in these runtime warnings are already correctly handled in the code, as the results are later reset to the appropriate values. These updates are to reduce the amount of clutter in the log file.
> Temporarily suppress benign arithmetic warnings in ramp fitting

- setup.py
Having `requests_mock` in `install_requires` prevents the conda package from being built.
> Remove redundant requests_mock from install_requires

- jwst/stpipe/crds_client.py
- jwst/stpipe/step.py
Primarily these are changes to crds_client.py and step.py driven by issue #3050.
Rather than hard coding the CRDS library observatory parameter as 'jwst',  it's exposed in the API so that it can be specified or inferred from data.   In theory this makes it possible for other telescopes to use STPIPE with no customization provided they fork/customize CRDS to add their own telescope.
There are 2 additional changes:
1.  I removed exception handling code in crds_client which is now ineffective because of subtle changes to Python-3 exception handling.   It affects tracebacks when references are not found.  They were horrible,  now they're horrible with less code.  We should add fatal errors if we don't have them and call one instead of a horrible traceback for "reference file not found."   But …
> Parameterize CRDS "observatory"

- CHANGES.rst
- jwst/assign_wcs/miri.py
- jwst/assign_wcs/niriss.py
The bounding box of MIRI LRS observations is determined by the wavelength solution in the `specwcs` reference file, in full frame coordinates. This adjust the bounding box when the observation is a subarray.
There's also a minor correction for the NIRISS SOSS mode from the center to the edge of the pixel.
> correct bounding box for subarray in MIRI LRS observations

- jwst/tests_nightly/general/miri/test_miri_steps_single.py
This update is to enable the `test_miri_slitless_wcs` regression test to pass after #3063.
Also general cleanup of other WCS regression tests:
- Use `grid_from_bounding_box` convenience function instead of `np.mgrid`
- Get truth file after `assign_wcs` is run, and segregate it in a `truth` subdir
- Run `assign_wcs` with `save_results=True` so as not to overwrite the input file
- Clarify test result and truth file variable names
Addresses #2941.
> Update MIRI WCS regression tests to not overwrite their input

- CHANGES.rst
- jwst/datamodels/schemas/multispec.schema.yaml
- jwst/extract_1d/extract.py
The schema for `MultiSpecModel` was modified to change the names of the extension-header keywords for the beginning, middle, and end of an integration.  Closes issue #2274 .
> MultiSpec model now uses different keywords for saving time values

- .travis.yml
This removes yet another copy of our `test` and `docs` dependencies from the `.travis.yml` file and instead uses the ones centrally defined in `setup.py`.  We do this by doing a
```
pip install -e .[test]
pip install -e .[docs]
```
in the repo after all the install dependencies have been installed by `conda` for the `test` and `build_sphinx` matrix elements, respectively.  Eventually we may want to do those install dependencies the same way and remove `conda` altogether.  Baby steps.
> Use pip install .[test] and [docs] in travis for dependencies

- docs/jwst/data_products/common_features.rst
- docs/jwst/data_products/file_naming.rst
- docs/jwst/data_products/guidestar_products.rst
- docs/jwst/data_products/index.rst
- docs/jwst/data_products/nonscience_products.rst
- docs/jwst/data_products/product_types.rst
- docs/jwst/data_products/science_products.rst
- docs/jwst/data_products/stages.rst
- docs/jwst/datamodels/fits_files.rst
- docs/jwst/datamodels/index.rst
- docs/jwst/package_index.rst
- docs/jwst/pipeline/calwebb_tso3.rst
Update the docs with more detailed info on the FITS data product formats and contents. First commit includes descriptions of uncal, ramp, rate, rateints, cal, and calints.
> WIP: FITS file formats documentation

- jwst/cube_build/data_types.py
I ran into this a few times - cube_build failed with `TypeError` but it doesn't say what the type is. In all cases the input files had `ImageModel` recorded instead of `IFUImageModel`. This is a simple PR to add a message to the error.
> add error message

- jwst/datamodels/schemas/image.schema.yaml
`relsens_2d` is applied only to IFU data.
> remove relsens_2d from image schema

- jwst/master_background/create_master_bkg.py
- jwst/master_background/expand_to_2d.py
- jwst/master_background/tests/test_create_master_bkg.py
Function `expand_to_2d` was added, to expand a 1-D background file to 2-D.  A utility function `create_background` was also added; this takes 1-D arrays of wavelength and background flux, and copies those values to a table in the appropriate format for a 1-D master background spectrum.
See issue #2308.
> Function to convert 1-D spectrum to 2-D

- jwst/coron/stack_refs.py
Updated the stack_refs routine to update the output data model with meta data from the first input model.
Fixes #2945.
> Update stack_refs to populate output meta data

- jwst/datamodels/schemas/core.schema.yaml
- jwst/master_background/master_background_step.py
- jwst/master_background/tests/test_master_background.py
Change
```
meta.master_background_file
```
to
```
meta.background.master_background_file
```
in the core schema, as the `meta.background` block already exists and is a natural place to put this property.
> Move MASTERBG keyword to background section of schema

- README.md
Updated the README file to include 0.13.0 in the table of deliveries.
> Update README for 0.13.0 delivery [skip ci]

- jwst/lib/set_telescope_pointing.py
- jwst/lib/tests/test_set_telescope_pointing.py
Fixed a typo in the CTYPE definition in set_telescope_pointing. The CTYPE keywords are not used in the pipeline AFAIK but the files will be wrong. There's no urgent need to make a patch delivery for this unless the bug has unexpected consequences.
> fix ctype definition

- .travis.yml
- Jenkinsfile
- JenkinsfileRT
- jwst/cube_skymatch/cube_skymatch_step.py
- jwst/resample/resample_utils.py
- jwst/skymatch/skymatch_step.py
- setup.py
The `image3pipeline` and MIRI MRS `spec3pipeline` regression tests pass with this change.
Resolves #3144.
> Remove stsci.tools dependency; use astropy.nddata.bitmask

- jwst/tests_nightly/general/miri/test_miri_steps_single.py
This fixes the code of this test.  Once #3146 is merged, the truth file can be updated as well.
> Fix set_telescope_pointing regression test so it can find SIAF

- .gitignore
- Jenkinsfile
- setup.py
This changes the `pip`  build/test matrix element for `jwst` on Jenkins to use only released dependencies of `astropy`, `asdf` and `gwcs`.
Addresses #3143.
> Use released versions of astropy, asdf and gwcs for Jenkins builds

- pytest.ini
- setup.cfg
The Jenkins test reporting plugin requires a correctly constructed schema of the report produced by pytest. This `pytest.ini` directive provides that.
Honored as of pytest 2.4.
> Add pytest.ini file to select correct junit test report family 

- jwst/tests_nightly/general/nircam/test_coron3_1.py
The test is currently failing because our CAL_VER changed yesterday.
```
In [7]: hdrtab_new['CAL_VER']
Out[7]: 
chararray(['0.13.1a.dev10+g48b072ec', '0.13.1a.dev10+g48b072ec',
'0.13.1a.dev10+g48b072ec', '0.13.1a.dev10+g48b072ec',
'0.13.1a.dev10+g48b072ec', '0.13.1a.dev10+g48b072ec',
'0.13.1a.dev10+g48b072ec', '0.13.1a.dev10+g48b072ec',
'0.13.1a.dev10+g48b072ec', '0.13.1a.dev10+g48b072ec'],
dtype='<U23')
In [10]: hdrtab_ref['CAL_VER']
Out[10]: 
chararray(['0.13.1a.dev5+g7fd654d4', '0.13.1a.dev5+g7fd654d4',
'0.13.1a.dev5+g7fd654d4', '0.13.1a.dev5+g7fd654d4',
'0.13.1a.dev5+g7fd654d4', '0.13.1a.dev5+g7fd654d4',
'0.13.1a.dev5+g7fd654d4', '0.13.1a.dev5+g7fd654d4',
'0.13.1a.dev5+g7fd654d4', '0.13.1a.dev5+g7fd654d4'],
dtype='<U22')
```
The new CAL_VER string is 1 character longer than the old …
> Make coron3 regression test more robust

- CHANGES.rst
- scripts/move_wcs.py
- scripts/runjwpsf.py
- scripts/set_bary_helio_times.py
- scripts/set_velocity_aberration.py
- scripts/stspec
This adds a call to "sys.exit(1)" if the script fails to be able to compute the converted times. If everything goes OK, it exits with no explicit code, which is assumed to default to 0. Python experts, please comment on whether plain "exit" or "sys.exit" is preferred.
Also includes minor updates to other scripts in the package to remove future import statements (should've been taken out long ago, now that we're requiring Python 3.x for the jwst package), as well as random pep8 updates to other scripts.
Fixes #3196
> Add exit code to set_bary_helio_times script

- .travis.yml
- jwst/ami/nrm_model.py
- Rely on publicly-released dependencies
- Don't use `conda` in Travis CI build/test matrix
- New version of `flake8` founda  bug in the ami code
> Remove conda from Travis CI build

- jwst/tests/base_classes.py
- setup.cfg
- setup.py
This standardizes the location for Artifactory/local data root locations for test inputs and results. It will facilitate in a general manner a request for incremental environment snapshot artifacts to be published at the conclusion of selected regression test runs.
The pytest config items `inputs_root` and `results_root` are supported by `ci-watson` starting in version `0.3`, released recently.
> Pull test data inputs_root and results_root values from pytest config.

- CHANGES.rst
- jwst/__init__.py
- jwst/datamodels/extension.py
- jwst/datamodels/model_base.py
- jwst/datamodels/schema.py
- jwst/datamodels/tests/test_schema.py
- setup.py
Revert #2430 with a few modifications:
- Add back `BaseExtension` to allow the URL mapping of `http://jwst.stsci.edu/schemas/core.schema.yaml` --> the location of `core.schema.yaml` in this package.  And all the other schemas.
-  Define the URL_PREFIX of `http://jwst.stsci.edu/schemas/` in one location in the package.
- Add this extension to `entry_points` in `setup.py` so `asdf` and other packages can access the schemas.
- Use the `entry_points` internally so it gets tested.
- Add a test to test the `entry_points` access from `asdf`, so we don't break this again in the future.
Resolves #3224.
> Add back datamodels BaseExtension

- jwst/datamodels/schemas/dq_def.schema.yaml
This PR makes a simple change to the datatype of the VALUE in  jwst.datamodels.schemas.dq_def.schema.yaml
Currently this is set to a datatype of `int`. But I believe it should be `uint`. 
I found this while attempting to populate the `dq_def` attribute in a MaskModel instance with the official list of DQ flags in `datamodels.dqflags.pixel`. In this case, the final entry in my dq_def list is the tuple: (31, 2147483648, 'REFERENCE_PIXEL', ''). But when I then set that as the dq_def attribute and print the attribute, the flag value is suddenly negative, and tuple is printed as: (31, -2147483648, 'REFERENCE_PIXEL', ''). I think this is due to the integer datatype.
Here's what I was doing when I found the problem:
```
from jwst.datamodels import MaskModel, dqflags
definitions = [] …
```
> Change VALUE datatype in dq_def schema to uint

- README.md
Update the DMS deliveries table in the README to include 0.13.1.
> Update README for 0.13.1 delivery [skip ci]

- CHANGES.rst
- jwst/datamodels/extension.py
- jwst/datamodels/metaschema/fits-schema.yaml
This fixes our current failures of schema validation seen in #3234 when testing this package using `asdf-2.4.0.dev1720`.  This resolves the bugs in this package.  Changes on `asdf` will be required to fully resolve it.
Resolves #3238.
> Fix url_mapper for fits-schema

- .travis.yml
Closes #3209 .
This implements testing with
- python 3.7
- with dev dependences of astropy, asdf and gwcs
The dev dependencies fail because of a change in asdf. The change in asdf actually corrected how schemas are tested so the fix is still probably in datamodels. 
@drdavella
> improve the Travis test matrix

- JenkinsfileRT
Temporarily pin the CRDS_CONTEXT for our regression tests until #3106 is merged.  This is to avoid using the new MIRI LRS reference files before the code handling them is merged.
> Pin CRDS_CONTEXT=jwst_0500.pmap

- CHANGES.rst
- jwst/master_background/tests/test_expand_to_2d.py
The unit tests for `expand_to_2d` are now separate functions, with functions for creating the test and comparison data.
See #3085.
> Modify unit tests for expand_to_2d

- jwst/tests_nightly/general/miri/test_miri_steps_single.py
- jwst/tests_nightly/general/nirspec/test_nirspec_steps_single.py
Closes #3204 
Here is the regression test for NIRSPEC FS. Once I get comments on this I will create a similar test for
NIRSPEC IFU and MIRI LRS. The routine is in test_nirspec_steps_single.py; the test
is test_nirspec_masterbackground_fs_user1d
This test has 3 tests. The first two are used to test the quality of how well the test is working. 
I see them as helping to define truth image. We might want to pull out the first two test later on
and just use the truth image as the sole regression test. 
I have a few figures for test 1.
It takes the output from the MasterBackbround Subtraction step and runs extract1d on the data.
Since this is FS data there are really 4 1-D spectra.
These four 1-D spectra are to compared to the four  1-d spectra produced by running extract 1d on the sci data …
> Master background regression tests

- jwst/tests_nightly/general/associations/test_sdp_pools.py
Resolves failing regressions test caused by not taking into account recent pytest configuration parameters.
> Update to handle new pytest configurations

- JenkinsfileRT
Per request from DMS, this JenkinsfileRT change will publish the output of `conda list --explicit` from within the testing environment to the `jwst-pipeline-results` Artifactory repository after each RT run without failures.
> Publish conda env listing to Artifactory upon failure-free test run.

- CHANGES.rst
- jwst/lib/set_telescope_pointing.py
- jwst/lib/tests/test_set_telescope_pointing.py
Modified `set_telescope_pointing` to convert the pixel scale values loaded from the SIAF from units of arcsec to degrees when storing the values in the CDELTn keywords. Also some random PEP8/flake8 cleanup.
Fixes #3247
> Convert CDELTn to degrees

- Jenkinsfile
- JenkinsfileRT
- Continue using `conda` in our Jenkins RT builds, but avoid using the astroconda-dev channel for the dependencies.  Use astroconda and default channels for released versions of dependencies.  This has the advantage of still allowing a spec file via `conda list --explicit` at the end of the run to be generated.
- Use Anaconda's `numpy nomkl` packages, which allow more efficient parallelization of the test run.  Should be similar to normal `numpy` available via `pip install` which doesn't have on-chip parallelization enabled.  This should be beneficial for DMS in their runs on HT Condor as well.
- The kicker: instead of having our dependencies in 3 places
- setup.py
- astroconda-dev recipe for `jwst`
- Jenkinsfile/JenkinsfileRT
We now only have them in two places.  This PR enables the …
> Use publicly released dependencies for regression tests
