jwst/barshadow/barshadow_step.py
See #2681.  I think bar_shadow.py is in pretty good shape already
=> Added docstrings to barshadow step

docs/jwst/references_general/explain_rmaps.rst, docs/jwst/references_general/index.rst
This pull is for MASTER.  See #2228 for more info,  let me know if I need to redo the pull for a different branch.
=> Explanation of rmaps, issue-2228

jwst/dq_init/dq_init_step.py, jwst/dq_init/dq_initialization.py
=> Added docstrings to dq_init step

docs/jwst/flatfield/dflat_selection.rst, docs/jwst/flatfield/fflat_selection.rst, docs/jwst/flatfield/flat_selection.rst, docs/jwst/flatfield/main.rst, docs/jwst/flatfield/reference_files.rst, docs/jwst/flatfield/sflat_selection.rst
More updates for #2675, this time for the `flat_field` step.
=> Update flat_field reffile docs

docs/jwst/ramp_fitting/main.rst
Updates for error propagation documentation. Fixes #1874 and JIRA ticket JP-230.
=> Update rampfitting docs to clarify error propagation

jwst/datamodels/schemas/miri_resolution.schema.yaml
Updated schema for miri resolution reference file.
May also need to update cubepars reference file schemas to make the capital column names in reference file to the schema names. 
Addresses #2747
=> updated MIRI resolution schema

jwst/assign_wcs/assign_wcs.py, jwst/assign_wcs/nircam.py, jwst/assign_wcs/niriss.py, jwst/datamodels/wcs_ref_models.py, jwst/extract_2d/extract_2d.py, jwst/extract_2d/grisms.py, jwst/lib/catalog_utils.py, jwst/transforms/models.py
see #2681  This includes updates, though not entirely complete, for assign_wcs, transforms, datamodels, lib, and extract_2d
=> docstring updates 

docs/Makefile, docs/make.bat
@nden this cleaned up the old source errors I was getting in the build, specifically, what was mentioned here #2777 and a couple similar ones
=> add cleanup of api dir in docs to remove old source issues

CHANGES.rst, jwst/tweakreg/imalign.py, jwst/tweakreg/linearfit.py, jwst/tweakreg/tweakreg_catalog.py, jwst/tweakreg/tweakreg_step.py, jwst/tweakreg/wcsimage.py
This PR should address issue https://github.com/spacetelescope/jwst/issues/2716. However, that specific test will fail next in `skymatch` because there are not enough data in overlapping area (probably bad WCS or all pixels flagged in DQ). If you want that one to succeed as well, I'll make another PR.
CC: @stscieisenhamer @hbushouse @stscicrawford
=> Make the code more robust with bad catalogs

jwst/tweakreg/imalign.py
Fixes the bug in https://github.com/spacetelescope/jwst/issues/2804.
=> Fix burning bug (undefined i) in tweakreg

docs/jwst/persistence/index.rst, docs/jwst/persistence/persat_selection.rst, docs/jwst/persistence/reference_files.rst, docs/jwst/persistence/trapdensity_selection.rst, docs/jwst/persistence/trappars_selection.rst
Updated the reference files documentation for the `persistence` step, as part of #2675.
=> Update persistence reffile docs

Jenkinsfile
Let's see if Docker lets us do this.
=> Update Jenkinsfile to rely on CI utils library

README.md
=> Add sphinx docs building instructions to README.md

jwst/lastframe/tests/test_lastframe.py
Added tests to test whether the full step properly rejects NIR data and runs for MIR data, resulting in 100% code coverage for lastframe step.
=> Updated lastframe unit test to test NIR data

jwst/firstframe/tests/test_firstframe.py
Updated firstframe test to see if full step properly skips NIR data and runs MIR data to get 100% code coverage.
=> New firstframe unit test added

jwst/dq_init/tests/test_dq_init.py
Adding unit tests for dq_init step. Created by @cracraft and @shanosborne.
Closes #2807.
Resolves #2561
=> Add tests for dq_init step

jwst/datamodels/schemas/rscd.schema.yaml, jwst/datamodels/util.py
Also, make the error message in datamodels a bit clearer.
Resolves #2875.
=> Fix RSCD column name bug in schema

docs/jwst/photom/area_selection.rst, docs/jwst/photom/photom_selection.rst, docs/jwst/photom/reference_files.rst
Updated the reference file information in the `photom` step docs, in partial fulfillment of #2675.
=> Update photom step reference file docs

docs/jwst/refpix/description.rst, docs/jwst/refpix/reference_files.rst, docs/jwst/refpix/refpix_selection.rst, docs/jwst/rscd/README, docs/jwst/rscd/reference_files.rst, docs/jwst/rscd/rscd_selection.rst
Updated the reference file docs for the `refpix` and `rscd` steps, in support of #2675. Reviewers: feel free to only review the updates for your steps.
=> Update reffile docs for refpix and rscd

CHANGES.rst, jwst/assign_wcs/nircam.py, jwst/assign_wcs/niriss.py
Implements #2420 for WFSS modes and NIRCAM TSGRISM
The velocity correction gets called before going into the trace polynomials.
See also discussion here: https://jira.stsci.edu/browse/JP-245
@stscicrawford @nden not sure what milestone to use
=> Added velocity correction to WFSS and Nircam TSO

CHANGES.rst, docs/jwst/refpix/description.rst
An outline of IRS2 processing for the refpix step was added to description.rst.  See issue #2873.
=> Describe IRS2 refpix correction

docs/jwst/cube_build/index.rst, jwst/cube_build/blot_cube_build.py, jwst/cube_build/coord.py, jwst/cube_build/cube_build.py, jwst/cube_build/cube_build_io_util.py, jwst/cube_build/cube_build_step.py, jwst/cube_build/cube_build_wcs_util.py, jwst/cube_build/cube_cloud.py, jwst/cube_build/cube_overlap.py, jwst/cube_build/data_types.py, jwst/cube_build/file_table.py, jwst/cube_build/ifu_cube.py, jwst/cube_build/instrument_defaults.py
Add the doc string to all modules. Also did a general clean up of comments in the code to make it
follow python rules.
=> Update doc strings for cube_build

jwst/assign_wcs/miri.py
This PR splits the spatial transform in the LRS WCS pipeline and creates an intermediate V2V3 frame. It also removes the hard-coded zero point of the wavelength solution for slitless mode in anticipation of the delivery of a new reference file in Dec. The code was tested with the new (to be delivered) reference file. Note that the results will be incorrect with the current reference specwcs file.
=> create v2v3 frame in the LRS pipeline

jwst/fits_generator/create_dms_data.py, jwst/fits_generator/templates/nircam_configuration_fm1.gen.inc
=> Update fits_generator to include recent NIRCAM header changes

docs/jwst/associations/jwst_conventions.rst
Documentation update to correct the table of association types vs. configuration files to use.
=> Update association type <-> configuration table to be accurate [skip ci]

jwst/ramp_fitting/ramp_fit.py, jwst/ramp_fitting/utils.py
Fixes #2848, #2233, #2885, #2832
=> Updates and fixes for ramp fitting for recent PRs and Issues.

jwst/tweakreg/wcsimage.py
This PR should address https://github.com/spacetelescope/jwst/issues/2938
CC: @hbushouse @stscieisenhamer
=> Fix a bug when creating WCSImageGroups from empty catalogs

.rtd-environment.yml, docs/conf.py, docs/jwst/assign_wcs/index.rst, docs/jwst/datamodels/attributes.rst, docs/jwst/model_blender/blender_rules.rst, docs/jwst/model_blender/index.rst, docs/jwst/references_general/camera_reffile.rst, docs/jwst/references_general/collimator_reffile.rst, docs/jwst/references_general/disperser_reffile.rst, docs/jwst/references_general/distortion_reffile.rst, docs/jwst/references_general/explain_rmaps.rst, docs/jwst/references_general/extract1d_reffile.rst, docs/jwst/references_general/filteroffset_reffile.rst, docs/jwst/references_general/fore_reffile.rst, docs/jwst/references_general/fpa_reffile.rst, docs/jwst/references_general/ifufore_reffile.rst, docs/jwst/references_general/ifupost_reffile.rst, docs/jwst/references_general/ifuslicer_reffile.rst, docs/jwst/references_general/msa_reffile.rst, docs/jwst/references_general/ote_reffile.rst, docs/jwst/references_general/regions_reffile.rst, docs/jwst/references_general/specwcs_reffile.rst, docs/jwst/skymatch/README.rst, docs/jwst/stpipe/devel_io_design.rst, docs/jwst/tweakreg/README.rst, jwst/datamodels/wcs_ref_models.py, jwst/dq_init/dq_init_step.py, jwst/model_blender/blendrules.py
Fixes several warnings when building the documentation with Sphinx.
=> fix doc warnings

jwst/pipeline/collect_pipeline_cfgs.py
=> collect_pipeline_cfgs now won't import all pipeline steps

jwst/extract_2d/extract_2d.py
This should fix the logic for  #2968
=> make sure grism_object passed as given

README.md
the previous PR was merged too soon.  This needs to be in there.
=> Add ci_watson back to README.md

docs/conf.py
small change to the docs to conform to template change for `stsci_rtd_theme` and pygments. See also https://github.com/spacetelescope/stsci_rtd_theme/pull/10 and accept this after that PR is merged. I'll push a release for the theme then as well.
=> update docs conf to conform to pygments change

CHANGES.rst, jwst/extract_1d/extract.py, jwst/extract_1d/tests/test_interpolate_response.py
Function `interpolate_response` was modified.  Resolves #3004.
=> Reverse order of RELSENS arrays if the wavelength is not increasing

jwst/tweakreg/wcsimage.py
Resolves #3009. Resolves #3012 
CC: @stscieisenhamer
=> Rely on bounding_box when available

jwst/linearity/tests/test_linearity.py
Contributing the unit tests for the linearity correction from @cracraft
=> Add linearity unit tests

jwst/refpix/tests/test_refpix.py
Here are some unit tests for the reference pixel correction! We still need to include contributions from the NIRSPEC team to get a higher level of coverage but this is a good first pass.
=> Adding refpix tests

.travis.yml
=> Remove namedlist from .travis.yml

docs/jwst/master_background/arguments.rst, docs/jwst/master_background/description.rst, docs/jwst/master_background/index.rst, docs/jwst/master_background/reference_files.rst, docs/jwst/package_index.rst
Initial round of docs for the new master background subtraction docs. Contains high-level overview, but is light on details for now (until the step itself is more fully developed).
Fixes #3086.
=> Step docs for master background subtraction

jwst/datamodels/schemas/core.schema.yaml, jwst/master_background/master_background_step.py, jwst/master_background/tests/test_master_background.py
The keyword for recording a user background file cannot be pronounced or remembered.  This is clearer.
Also made the attribute names in the datamodel clearer.
=> Rename master background keyword MSTRBKGD > MASTERBG

CHANGES.rst, jwst/extract_1d/ifu.py
Follow up on #3157 - local changes I had did not make it into the previous PR.
=> add change log entry and log message

.travis.yml, Jenkinsfile, jwst/tweakreg/tests/test_interface.py
An attempt to fix our broken builds on Jenkins.
=> Refactor CI scripts to fix build issues

README.md
To satisfy one of the requirements that @stscicrawford posted on https://jira.stsci.edu/browse/JUSI-5 .
cc @jhunkeler
=> DOC: Add JupyterHub to README

src/tweakreg/carrutils.c
Fixes compiler errors on Windows (VS compiler). Related to https://github.com/spacetelescope/drizzlepac/pull/258/commits/92f65dee7daa4c864adb1645af393e285120fa81
=> Fix void pointer arithmetic in tweakreg

CHANGES.rst, jwst/extract_1d/tests/test_ifu_image_ref.py
A file containing unit tests for IFU data using a reference image was added to the tests/ directory.
Resolves #3213.
=> Unit tests for extract_1d for IFU data

docs/jwst/associations/overview.rst
Fixes a formatting issue and various spelling issues found during review of PR #3313.
=> Fix note formatting and various spelling errors

CHANGES.rst, jwst/master_background/master_background_step.py
The logic in this step is starting to look like spaghetti code.  I tried to make it a bit more modular.  Any suggestions on cleaning it up would be welcome.
Resolves #3283.
=> Handle nodded data in master background step

CHANGES.rst, docs/jwst/barshadow/description.rst, jwst/barshadow/bar_shadow.py
Updated the ``barshadow`` step to apply the correction array to all of the science data arrays. Also just did a bunch of little stylistic cleanup to make the code more readable (IMHO).
Fixes #1963
=> Update barshadow step to apply correction

.travis.yml, Jenkinsfile, JenkinsfileRT, jwst/assign_wcs/miri.py
This follows and should be **rebased** and merged after #3106.
It corrects a typo in a variable and fixes PEP 8 issues in MIRI LRS distortion code.
=> fix pep8 MIRI LRS

CHANGES.rst
Added entries that I missed earlier for 2 PR's that I recently merged.
=> Backfill CHANGELOG for recent PR's [skip ci]

jwst/datamodels/schemas/image.schema.yaml
Fixes issue discovered in #3323.
=> Remove pathloss_pointsource from ImageModel schema

jwst/tests_nightly/general/nirspec/test_nirspec_steps_single.py
The regression tests for the ``master_background`` step using NIRSpec fixed-slit data and a user-supplied bkg spectrum no longer work correctly, since the merging of #3326. This change sets DQ='DO_NOT_USE' flags in the output 2-D image from ``master_background``, which then causes the ``extract_1d`` step to ignore those pixels when producing 1-D spectra. This is fine and as it should be.
However, parts of the regression test were setup to compare these results against real-time extractions from the original 2-D image that had no background signal added to it. This image has no DQ flags set to DO_NOT_USE, and hence includes a different set of pixels in its output than what's done for the background-subtracted image. This leads to large enough differences in the extracted 1-D spectra to …
=> Update NIRSpec FS master_background reg test

.travis.yml, Jenkinsfile, JenkinsfileRT
Context 502 showed no regression test differences, so moving on to checkout 503.
=> Bump CRDS context to 503 for all test setups

.travis.yml, Jenkinsfile, JenkinsfileRT
Increment context again. 513 is the current latest delivery.
=> Bump CRDS context to 513 for tests

jwst/resample/resample_spec.py, jwst/resample/tests/test_resample_spec.py
Resolves #3394
This PR solves an issue reported by @philhodge 
```
wcs.invert(-1, dec, lam) != wcs.invert(359, dec, lam)
```
=> resample_spec wcs

jwst/group_scale/tests/.coverage, jwst/group_scale/tests/test_group_scale.py
Here is a list of unit test for the group scale step of the pipeline. The tests asked for by the team are in this table https://outerspace.stsci.edu/pages/viewpage.action?spaceKey=JWSTPWG&title=Group+Scale and I also made sure to add some other tests just to get better code coverage.
=> Add unit tests for group scaling

jwst/assign_wcs/assign_wcs.py, jwst/assign_wcs/assign_wcs_step.py, jwst/assign_wcs/nirspec.py, jwst/assign_wcs/tests/test_nirspec.py, jwst/pipeline/assign_wcs.cfg
=> make y-slit range an input parameter

CHANGES.rst, jwst/datamodels/source_container.py, jwst/tests/base_classes.py, jwst/tests/test_infrastructure.py, jwst/tests_nightly/general/nirspec/test_nirspec_msa_spec3.py
=> Treat each exposure in MultiExposure as a model using SourceContainer

jwst/tests/base_classes.py, jwst/tests/test_infrastructure.py
Handling new differences between local artifactory files and from a url.
=> Fix more artifactory globbing weirdness

jwst/assign_wcs/nirspec.py, jwst/extract_2d/nirspec.py, jwst/tests_nightly/general/nirspec/test_calwebb_spec2_nrs_msa.py
fixing failing tests due to MSA meta file changes in #3448
=> fix attribute name

CHANGES.rst, jwst/refpix/reference_pixels.py
=> Fix pixeldq array transformation in refpix step

jwst/tests_nightly/general/associations/conftest.py, jwst/tests_nightly/general/associations/sdp_pools_source.py, jwst/tests_nightly/general/associations/test_sdp_pools.py, jwst/tests_nightly/general/associations/test_standards.py
Incorporates #3162 as a test for #655
Unblocks #655
=> Implement NIRCam WFSS tests from proposal jw00624

jwst/flatfield/flat_field.py
Fix bug introduced in #3493.  Caught by regression tests.
=> Bugfix for calls to create_flat_field()

jwst/associations/lib/rules_level2b.py
Resolves #3550, resolving JP-742
=> Update direct image name with actual Level3 name

jwst/ramp_fitting/tests/test_ramp_fit_cases.py
=> Add MIRI unit tests for ramp fitting

JenkinsfileRT, jwst/tests/base_classes.py
=> Fix base url handling for access to artifactory

CHANGES.rst, jwst/associations/lib/dms_base.py, jwst/associations/lib/rules_level2_base.py, jwst/associations/lib/rules_level3_base.py, jwst/tests_nightly/general/associations/test_sdp_pools.py
=> Ensure target acquisition data is not treated as TSO or integrations

CHANGES.rst, jwst/associations/lib/dms_base.py, jwst/associations/lib/rules_level2_base.py, jwst/associations/lib/rules_level3_base.py, jwst/associations/tests/test_level3_spectrographic.py, jwst/tests_nightly/general/associations/test_sdp_pools.py
=> Add the fxd_slit keyword as the third optical component

jwst/associations/association_io.py
Resolves #3543 
WIP [JP-782](https://jira.stsci.edu/browse/JP-782)
=> Use yaml.safe_load instead of yaml.load

CHANGES.rst, jwst/pipeline/calwebb_tso3.py, jwst/tso_photometry/tso_photometry_step.py
This addresses #3597 (JIRA-766)
=> fixed errors for MIRI TSO Imaging

CHANGES.rst, jwst/associations/main.py, jwst/associations/tests/test_level2_candidates.py, jwst/associations/tests/test_wfss.py, jwst/tests_nightly/general/associations/test_generate.py, jwst/tests_nightly/general/associations/test_main.py
Resolves #2686 
WIP [JP-782](https://jira.stsci.edu/browse/JP-782)
=> Do not, by default, merge Level 2 associations

jwst/extract_2d/grisms.py, jwst/extract_2d/tests/test_grisms.py
=> Update WFSS slit names to use simple integer value (#3623) (JP-776)

JenkinsfileRT
Reverts spacetelescope/jwst#3679
=> Revert "Set TEST_BIGDATA to central store"

jwst/associations/lib/rules_level2b.py
Remove the nam eof the already removed class form `__all__`.
=> remove class for __all__ list

jwst/combine_1d/combine1d.py, jwst/datamodels/properties.py, jwst/datamodels/tests/test_fits.py, jwst/datamodels/util.py
Reverts spacetelescope/jwst#3680
=> Revert "Fix corruption of FITS tables with unsigned int columns on save and load"

jwst/associations/association.py, jwst/datamodels/ndmodel.py, jwst/exp_to_source/exp_to_source.py, jwst/fits_generator/util.py
Reverts spacetelescope/jwst#3709
=> Revert "Remove references to deprecated ABCs that will be removed in Python 3.8"

CHANGES.rst, jwst/flatfield/tests/test_clean_wl.py, jwst/flatfield/tests/test_find_dispaxis.py, jwst/flatfield/tests/test_g_average.py, jwst/flatfield/tests/test_interpolate_flat.py, jwst/flatfield/tests/test_wl_interpolate.py
New unit tests were added for `flat_field`, and some tests were split into multiple functions.
Closes #3702
=> Add new unit tests for flat_field

CHANGES.rst, docs/jwst/extract_1d/description.rst, jwst/extract_1d/extract.py
Parameters were added to `ExtractBase.__init__`.
Documentation was updated for previous changes.
Closes #3216.
=> Refactor extract_1d classes

CHANGES.rst, jwst/associations/lib/rules_level3_base.py, jwst/tests_nightly/general/associations/test_sdp_pools.py
=> Jp829 Do not constrain on uniqueness of the MSACONFIG keyword

scripts/okify_regression_tests.py
https://jira.stsci.edu/browse/JP-854
I had 62 files to update after #3745 and ended up writing a script to parse the Jenkins output and offer files to okify.  The output looks like this:
```
Fitsdiff output:
E            fitsdiff: 3.2.1
E            a: /data1/jenkins/workspace/RT/JWST/clone/test_outputs/popen-gw11/test_coron3_10/jw99999-a3001_t1_nircam_f140m-maskbar_i2d.fits
E            b: /data1/jenkins/workspace/RT/JWST/clone/test_outputs/popen-gw11/test_coron3_10/truth/jw99999-a3001_t1_nircam_f140m-maskbar_i2d_ref.fits
E            HDU(s) not to be compared:
E             ASDF
E            Keyword(s) not to be compared:
E             CAL_VCS CAL_VER CRDS_CTX CRDS_VER DATE FILENAME NAXIS1 TFORM*
E            Table column(s) not to be compared:
E             CAL_VCS CAL_VER CRDS_CTX …
```
=> Create regression test okifying tool

JenkinsfileRT
This bug prevented the regression test build
=> Fix syntax bug in JenkinsfileRT

docs/index.rst, docs/jwst/error_propagation/index.rst, docs/jwst/error_propagation/main.rst, docs/jwst/package_index.rst
Fixes https://jira.stsci.edu/browse/JP-230
=> JP-230 Error propagation documentation

jwst/stpipe/config_parser.py, jwst/stpipe/tests/data/step_parameters/jwst_generic_pars-makeliststep_0001.asdf, jwst/stpipe/tests/data/step_parameters/jwst_generic_pars-makeliststep_0002.asdf, jwst/stpipe/tests/data/step_parameters/jwst_miri_pars-tweakreg_0001.asdf, jwst/stpipe/tests/test_asdf_parameters.py
Resolves JP-861/#3815
Resolves JP-864/#3812
=> Initial inclusion of ASDF as configuration

jwst/datamodels/schemas/core.schema.yaml
=> Add attribute meta.instrument.lamp_mode from keyword OPMODE

setup.py
=> Update dependency to dev version of stsci.image

CHANGES.rst, jwst/tso_photometry/tests/test_tso_photometry.py, jwst/tso_photometry/tso_photometry.py
Unit tests were added to `tso_photometry`.
=> Add unit tests to tso_photometry.

requirements-dev.txt
Fixes
https://travis-ci.org/spacetelescope/jwst/jobs/572502964#L430-L435
=> Fix requirements-dev.txt

CHANGES.rst, jwst/barshadow/bar_shadow.py, jwst/barshadow/tests/test_barshadow.py
=> JP-633 Unit tests were added to `barshadow`

setup.py
...now that a new release of that package is available.
=> Change stsci.image 'dev' dependency to a stable version floor

docs/jwst/firstframe/description.rst, docs/jwst/lastframe/description.rst
Very minor PR.  Updates the documentation for the firstframe and lastframe steps to be consistent with what the code is actually doing.
Addresses #3932.
=> Minor updates to docs

jwst/tests_nightly/general/associations/test_generate.py
Update regression truth value.
=> Update regression truths

jwst/straylight/straylight.py, jwst/straylight/straylight_step.py, jwst/straylight/tests/test_straylight_step.py
Added a simple to test for checking user input options
=> added one more test and a little pep8 clean up

jwst/straylight/tests/test_straylight_step.py, setup.py
Fixes a pep8 failure introduced in #3960 
cc @jemorrison
=> Straylight flake8 fix

jwst/datamodels/tests/test_fits.py, jwst/datamodels/tests/test_schema.py, jwst/datamodels/tests/test_storage.py, jwst/extract_2d/grisms.py
This PR removes unnecessary string-to-string conversions.
Closes #3978
=> Remove unnecessary string-to-string conversions

CHANGES.rst, jwst/tweakreg/tweakreg_catalog.py
=> Fix deprecated call to photutils.detect_threshold

jwst/pathloss/tests/test_pathloss.py
Adding unit tests for the pathloss correction. Have roughly 50% coverage and am working my way through `do_correction` currently.
=> [WIP]: Adding pathloss reference tests

README.md
=> DOC: Clarify installation commands

jwst/cube_build/cube_build_step.py, jwst/cube_build/cube_build_wcs_util.py, jwst/cube_build/ifu_cube.py, jwst/cube_build/instrument_defaults.py
Reverts spacetelescope/jwst#4010
This is being reverted as this did not yet address the problem and created additional regressions.   This should be reviewed further and the root cause of the problem should be address.
=> Revert "Fixes JP-974 Footprint calculation for archive "

jwst/ami/tests/test_ami_analyze.py
These tests are for the ami_analyze pipeline functions that are defined within the utils module. There will be other tests added for the other modules in the pipeline.  See JIRA JP-975 and PR #4003
=> Unit tests for the utils module within the ami_analyze pipeline

jwst/cube_build/cube_build_io_util.py, jwst/cube_build/ifu_cube.py, jwst/cube_build/tests/test_cube_build_step.py, jwst/cube_build/tests/test_miri_cubepars.py, jwst/cube_build/tests/test_nirspec_cubepars.py, jwst/cube_build/tests/test_wcs.py
additional unit tests for cube_build
=> added unit tests for cube_build

jwst/straylight/straylight_step.py
=> updated how straylight step checks power parameter

jwst/ami/tests/test_ami_analyze.py
For functions in the leastsqnrm module in the ami_analyze step, these are the unit tests.  There are 2 functions in that module that I did not write tests - they are custom least squares functions that are too complicated for unit tests, so they may be put into regression tests later.
=> Added tests for the leastsqnrm module

jwst/ami/tests/test_ami_analyze.py
Additional tests for ami_analyze. Other functions in hexee for which I did not write tests are either too trivial or are already tested in elsewhere.
Resolves #4003
=> Unit tests for the hexee module within the ami_analyze pipeline

jwst/datamodels/steppars.py, jwst/stpipe/pipeline.py, jwst/stpipe/step.py
Changes:
- Update `StepParsModel` to remover unnecessary code
- Update docstrings to remove sphinx errors
Notes:
The sphinx errors encountered when running locally are
not what RTD is seeing. Cannot reproduce RTD errors
but maybe this will push things a bit.
=> Update to StepParsModel and minor documentation tweaks

CHANGES.rst, jwst/tweakreg/tweakreg_step.py
Minor bug fix which was introduced in https://github.com/spacetelescope/jwst/pull/1556
=> Fix a bug in tweakreg step in how exception is re-raised

jwst/ami/tests/test_ami_analyze.py
Additional tests for ami_analyze. These test all but a few functions (pending) in the analyticnrm2 module.
=> Unit tests for the analyticnrm2 module within the ami_analyze pipeline

CHANGES.rst, jwst/lib/class_property.py, jwst/stpipe/cmdline.py, jwst/stpipe/pipeline.py, jwst/stpipe/step.py, jwst/stpipe/tests/test_step.py
Resolves JP-1035 and, hopefully, JP-1041
Hate it when documentation build issues point out questionable code...not that defeat has yet been admitted.
=> JP-1035 JP-1041 Make properties pars and pars_models into methods

jwst/mrs_imatch/tests/test_configuration.py
Removes the test that lead to https://github.com/spacetelescope/jwst/issues/4169
=> Remove an unnecessary and invalid test for mrs_imatch

CHANGES.rst, jwst/ami/tests/test_ami_analyze.py
This update includes a test for the webb_psf module, and incorporates earlier reviewer comments. This completes the unit tests for the ami_analyze pipeline.
=> Added test for webb_psf module.

jwst/stpipe/pipeline.py, jwst/stpipe/step.py, jwst/tests_nightly/general/miri/test_miri_spec2pipeline.py
=> JP-1042 Clean up logging of step parameter CRDS retreival

CHANGES.rst
Need someone to approve, no need for tests to pass.
=> changes for 0.14.0

jwst/tests_nightly/general/niriss/test_niriss_steps_single.py, jwst/tests_nightly/general/nirspec/test_nirspec_steps_single.py
=> Fix incorrect regtest names and data locations

docs/jwst/introduction.rst, docs/jwst/stpipe/config_asdf.rst, docs/jwst/stpipe/devel_io_design.rst, docs/jwst/stpipe/user_step.rst, jwst/stpipe/cmdline.py
Resolves #3889/[JP-913](https://jira.stsci.edu/browse/JP-913).
=> JP-913 Update documentation for save-parameters

jwst/engdblog/tests/test_engdblog.py, jwst/stpipe/tests/test_step.py
Fix or better document various unit test failures related to retrieving step parameters from crds work.
=> Fix unit tests related to parameters-from-crds

jwst/extract_2d/nirspec.py
=> Only calculate S_REGION if looking at the sky JP-1115

jwst/regtest/conftest.py
Question:
Would it be better if `want_property` accepted a list and `yield`s each property as they're discovered?
```python
for key, value in postmortem(request, ['output', 'other', 'data']):
```
Or should `want_property` accept a string and only return the value of the property?
```python
prop = postmortom(request, 'output')
if prop:
thing = prop
stuff.append(prop)
```
=> Consolidate property discovery into postmortem function

jwst/guider_cds/tests/test_guider_cds.py
=> Adding guider cds unit tests

requirements-sdp.txt
Should fix https://github.com/spacetelescope/jwst/issues/4261
=> Update requirement for tweakwcs

requirements-sdp.txt, setup.py
=> update asdf's hash

CHANGES.rst
A repeat entry deleted, and an entry moved to the correct location.
=> Fix CHANGES.rst [ci skip]

CHANGES.rst, jwst/tweakreg/tweakreg_step.py
This PR fixes https://github.com/spacetelescope/jwst/issues/4261
=> Improve tweakreg resilience to empty catalogs

CHANGES.rst, jwst/flatfield/flat_field.py
FGS Guider data is not processed by ramp fitting, so has no variances for Poisson noise or read noise.
Should we be computing these variances for these 2-read ramps? @hbushouse 
Resolves #4158 / JP-1074
=> Revision for flat fielding FGS Guider data (JP-1074).

jwst/white_light/tests/test_white_light.py
=> Adding white light unit tests

jwst/regtest/conftest.py, jwst/regtest/regtestdata.py, jwst/regtest/test_infrastructure.py, jwst/regtest/test_miri_image2.py, setup.cfg
=> Finish okify implmentation for regtests

jwst/extract_1d/extract.py
In two places I had a comma where there should not have been one.
=> Fix typos.

jwst/regtest/regtestdata.py, jwst/regtest/test_niriss.py
Resolves #4375/[JP-1196](https://jira.stsci.edu/browse/JP-1196)
=> JP-1196: Implement NIR WFSS Level2b spectral test

jwst/regtest/test_dark.py
The input and truth files have been uploaded to artifactory and the local test run looks fine.
=> JP-1171:  New dark level2a regression test

jwst/regtest/test_fgs.py, jwst/regtest/test_fgs_guider.py
Resolves #4324/[JP-1165](https://jira.stsci.edu/browse/JP-1165)
=> Jp 1165 Implement FGS GUIDER pipeline regression

jwst/regtest/test_miri_mrs.py
Resolves #4385/[JP-1198](https://jira.stsci.edu/browse/JP-1198)
=> JP-1198 Implement MIRI MRS level2b regtest

JenkinsfileRT
This will help us debug CRDS problems easier in our regression tests.  Hopefully.
=> Increase CRDS verbosity in JenkinsfileRT

jwst/cube_build/blot_cube_build.py, jwst/outlier_detection/outlier_detection_ifu.py, jwst/outlier_detection/outlier_detection_step.py
This pr addresses #JP-1161 and closes #4315
=> Fix ifu cube blotting for outlier detection - JP-1161

jwst/cube_build/cube_build.py, jwst/cube_build/cube_build_io_util.py, jwst/cube_build/cube_build_step.py, jwst/cube_build/cube_cloud.py, jwst/cube_build/ifu_cube.py, jwst/cube_build/instrument_defaults.py, jwst/cube_build/tests/test_miri_cubepars.py, jwst/cube_build/tests/test_nirspec_cubepars.py, jwst/datamodels/__init__.py, jwst/datamodels/ifucubepars.py, jwst/datamodels/schemas/miri_ifucubepars.schema.yaml, jwst/datamodels/schemas/nirspec_ifucubepars.schema.yaml
DO NOT MERGE UNTIL NEW CUBEPARS REFERENCE FILES IN CRDS.
The PR addresses #3761 
Updated cube_build to read in the new reference files that contain the information to set up the radial weighting scheme.
=> Ifucube radial weighting and new reference files 

scripts/strun
Now:
```
$ strun --version
0.14.3a1.dev107+gb6b7c008.d20200122
```
Fixes #4467
=> Fix strun --version bug

jwst/regtest/test_miri_mrs.py, jwst/regtest/test_nirspec_ifu.py
Resolves #4451/[JP-1231](https://jira.stsci.edu/browse/JP-1231)
=> JP-1231 Update test data and refactor test

README.md
=> JP-1247: Update regression test location in README

CHANGES.rst, docs/jwst/stpipe/config_asdf.rst, jwst/stpipe/pipeline.py, jwst/stpipe/step.py, jwst/stpipe/tests/test_asdf_parameters.py, jwst/stpipe/tests/test_step.py
=> JP-1244 Fix nesting of sub-step parameters in parameter configuration files

CHANGES.rst, docs/jwst/transforms/index.rst, docs/jwst/transforms/tpcorr.rst, docs/jwst/tweakreg/README.rst, jwst/transforms/__init__.py, jwst/transforms/jwextension.py, jwst/transforms/schemas/stsci.edu/jwst_pipeline/tpcorr-0.7.0.yaml, jwst/transforms/tags/__init__.py, jwst/transforms/tags/jwst_models.py, jwst/transforms/tpcorr.py, setup.py
Reverts spacetelescope/jwst#4491
Until `asdf` validation error is understood.
=> Revert "Remove TPCorr"

docs/jwst/references_general/filteroffset_reffile.rst
=> fix units of filter offset correction in documentation

CHANGES.rst, jwst/outlier_detection/outlier_detection.py, jwst/outlier_detection/tests/test_outlier_detection.py
Resolves #4494 and [JP-1251](https://jira.stsci.edu/browse/JP-1251)
=> Fix subtracted background bug in outlier_detection

README.md
=> Clarify installations instructions

CHANGES.rst, jwst/datamodels/schemas/core.schema.yaml
Add more new values to the PATTTYPE enum list, at the request of SDP.
Fixes #4549 / [JP-1288](https://jira.stsci.edu/browse/JP-1288)
=> JP-1288: More new PATTTYPE keyword values

jwst/coron/tests/test_coron.py, jwst/regtest/test_miri_image_detector1.py
=> Add unit tests for coronagraphic package

docs/jwst/references_general/filteroffset_reffile.rst
=> Ref file doc

CHANGES.rst, jwst/associations/lib/rules_level3.py
Update rules_level3.py 
value=['2_point|4_point_nod|along_slit_nod']
to
value=['2-point-nod|4-point-nod|along-slit-nod']
=> JP-1299 Update PATTTYPE values in ASN rules

CHANGES.rst, jwst/outlier_detection/outlier_detection_ifu.py
Resolves [JP-1231](https://jira.stsci.edu/browse/JP-1231)/#4451.
=> Check for a zero array before sigma clipping

jwst/datamodels/schemas/filteroffset.schema.yaml
Adding input units metadata to filter offset reference file schema per https://jira.stsci.edu/browse/JP-1290
=> Add input units to filteroffset schema

jwst/assign_wcs/tests/test_wfss.py, jwst/extract_2d/grisms.py, jwst/transforms/models.py
Improved performance.
This PR uses the `expected values` in the wfss tests (assign_wcs/tests/test_wfss.py) but changes the calls to the functions to use the new interface.
=> Refactor WFSS transforms

JenkinsfileRT
=> Temporarily just run one test

JenkinsfileRT, JenkinsfileRT_dev
Try with the right jenkins file
=> Quick regtest

CHANGES.rst, JenkinsfileRT, JenkinsfileRT_dev
- Also revert back changes to JenkinsfileRT and JenkinsfileRT_dev
- We had also forgot to turn on testing in `jwst/regtests` directory in our dev build.  This turns it on.
=> Update CHANGES.rst for release 0.15.0

CHANGES.rst, docs/jwst/mrs_imatch/description.rst, jwst/mrs_imatch/mrs_imatch_step.py
When the background polynomial is Nans set poly = None so that cube_build does not try and subtract it and set skip step.
=> JP-1327 mrs_imatch polynomial nan check

CHANGES.rst
Update changelog for the next release.
=> Prepare 0.15.2

CHANGES.rst, docs/jwst/introduction.rst, docs/jwst/stpipe/user_step.rst, jwst/stpipe/cmdline.py, jwst/stpipe/pipeline.py, jwst/stpipe/step.py, jwst/stpipe/tests/test_step.py
Resolves #4389/[JP-1203](https://jira.stsci.edu/browse/JP-1203)
=> Jp 1203 Add command line and environmental options to not retrieve steppars references

README.md
Update the DMS delivery table for the latest 0.15.1 release.
=> Update README for latest DMS delivery

CHANGES.rst, jwst/stpipe/cmdline.py, jwst/stpipe/pipeline.py, jwst/stpipe/step.py
Resolves #4689 
Resolves [JP-1356](https://jira.stsci.edu/browse/JP-1356)
=> Jp 1356 Unhide exceptions during CRDS steppars retrieval

.gitignore
=> Add .sw[op] to gitignore

CHANGES.rst
Update the change log for all the changes contained in #4552
=> Update change log for PR#4552

jwst/lib/exposure_types.py, jwst/regtest/test_nircam_image.py, jwst/regtest/test_nircam_mtimage.py
This is my first regression tests in the new system. Comments welcome.
I'm waiting for artifactory to come back to upload the data.
=> add a regression test for moving target

JenkinsfileRT, jwst/regtest/test_nircam_tsgrism.py
WIP #4757 
WIP [JP-1397](https://jira.stsci.edu/browse/JP-1397)
=> Quick fix for engineering db availabily issues

CHANGES.rst, docs/jwst/outlier_detection/arguments.rst, docs/jwst/references_general/references_general.rst, docs/jwst/resample/arguments.rst, docs/jwst/skymatch/README.rst, jwst/datamodels/dqflags.py, jwst/lib/basic_utils.py, jwst/lib/suffix.py, jwst/lib/tests/test_suffix.py, jwst/outlier_detection/outlier_detection.py, jwst/outlier_detection/outlier_detection_scaled_step.py, jwst/outlier_detection/outlier_detection_stack_step.py, jwst/outlier_detection/outlier_detection_step.py, jwst/pipeline/outlier_detection.cfg, jwst/pipeline/outlier_detection_scaled.cfg, jwst/pipeline/outlier_detection_stack.cfg, jwst/pipeline/outlier_detection_tso.cfg, jwst/pipeline/tests/data/cfgs/outlier_detection.cfg, jwst/pipeline/tests/data/cfgs/outlier_detection_scaled.cfg, jwst/pipeline/tests/data/cfgs/outlier_detection_stack.cfg, jwst/pipeline/tests/data/cfgs/outlier_detection_tso.cfg, jwst/pipeline/tests/data/cfgs/resample.cfg, jwst/pipeline/tests/data/cfgs/resample_spec.cfg, jwst/resample/resample_spec_step.py, jwst/resample/resample_step.py, jwst/resample/resample_utils.py, jwst/resample/tests/test_utils.py
Resolves #3641 
Resolves [JP-787](https://jira.stsci.edu/browse/JP-787)
=> JP-787 Change outlier and resample DQ bit usage

JenkinsfileRT, jwst/lib/suffix.py
=> Suffix repair

CHANGES.rst, jwst/datamodels/flat.py, jwst/datamodels/reference.py, jwst/datamodels/schemas/filteroffset.schema.yaml, jwst/datamodels/tests/test_wcs.py, jwst/datamodels/wcs_ref_models.py
=> add pupil to filteroffset model and schema

CHANGES.rst, jwst/assign_wcs/nirspec.py, jwst/master_background/master_background_step.py, jwst/pipeline/calwebb_spec2.py, jwst/regtest/test_miri_image.py, jwst/regtest/test_miri_lrs_slit_spec2.py, jwst/regtest/test_miri_lrs_slit_spec3.py, jwst/regtest/test_miri_lrs_slitless.py, jwst/regtest/test_miri_mrs.py, jwst/regtest/test_nircam_image.py, jwst/regtest/test_nirspec_masterbackground.py, jwst/regtest/test_nirspec_wcs.py, jwst/stpipe/tests/test_pipeline.py, setup.cfg
Resolves #4737 
Resolves #2328 
Addresses #4662
=> Fix remaining open file issues; turn on pytest-openfiles

README.md
Fix the markdown for section headings (this isn't rst!) that I messed up in #4779 .
=> Fix README section headers

CHANGES.rst, jwst/datamodels/model_base.py, jwst/datamodels/tests/test_models.py, jwst/datamodels/tests/test_schema.py
Resolves #4777 
Resolves [JP-1403](https://jira.stsci.edu/browse/JP-1403)
=> JP-1403 Fix handling of the boolean-like environmental variables PASS_INVALID_VALUES and STRICT_VALIDATION

JenkinsfileRT, JenkinsfileRT_dev
Add crds test cache path to RT setup.
=> Update RT to use test CRDS cache [skip ci]

JenkinsfileRT
This reverts commit 0b29e97e378a98a3989b80bc95a8daf00d443157.
=> Revert "Temporarily disable macos build config (#4780)"

jwst/source_catalog/source_catalog.py
This PR adds two additional concentration indices in the source catalog as requested yesterday by the JWST Photometry Working Group.  Hopefully, this can go in B7.5, but I'll let others set the milestone.
CC: @hbushouse
=> Add additional concentration indices

CHANGES.rst, jwst/rscd/rscd_sub.py
Moved defining param dictionary until the readpatt and subarray is found in the reference file for enhanced algorithm case.
=> RSCD correction JP-1446

CHANGES.rst, docs/jwst/pipeline/calwebb_coron3.rst, jwst/coron/stack_refs.py, jwst/datamodels/cube.py, jwst/datamodels/model_base.py, jwst/datamodels/tests/test_cube.py, jwst/datamodels/tests/test_models.py, jwst/pipeline/calwebb_coron3.py, jwst/regtest/test_nircam_coron3.py
Resolves [JP-1294](https://jira.stsci.edu/browse/JP-1294) / #4556
=> JP-1294 Update coron3 for new outlier detection application

CHANGES.rst, docs/jwst/datamodels/models.rst, jwst/datamodels/model_base.py, jwst/datamodels/tests/test_models.py
Resolves #4579
Resolves #3114
Requires asdf v 2.6.0 (to be released soon).
=> add info and search methods to models

CHANGES.rst, docs/jwst/stpipe/devel_step.rst
Again...
Resolves JP-1148 / #4286
=> [skip ci] Remove further sloper references

CHANGES.rst, jwst/datamodels/schemas/core.schema.yaml
Resolves [JP-1410](https://jira.stsci.edu/browse/JP-1410)
Resolves #4681
=> JP-1410 Add blend rule for detector

README.md
Resolves #4988 / [JP-1474](https://jira.stsci.edu/browse/JP-1474)
=> Update README.md with Windows support info.

CHANGES.rst, jwst/pipeline/calwebb_coron3.cfg, jwst/pipeline/calwebb_coron3.py
Resolves #4985 
Resolve [JP-1472](https://jira.stsci.edu/browse/JP-1472)
=> JP-1472 Blend headers just from each input science model, not every integration

CHANGES.rst, docs/jwst/assign_wcs/exp_types.rst, docs/jwst/assign_wcs/reference_files.rst, jwst/assign_wcs/nircam.py, jwst/assign_wcs/niriss.py, jwst/assign_wcs/tests/test_nircam.py, jwst/assign_wcs/tests/test_niriss.py, jwst/assign_wcs/util.py, jwst/lib/reffile_utils.py
Resolves #4553 / [JP-1292](https://jira.stsci.edu/browse/JP-1292)
=> Enable filteroffset correction for NIRISS and NIRCAM imaging mode

jwst/assign_wcs/nircam.py, jwst/assign_wcs/niriss.py
Apply filteroffset correction only if the correction is present in the reference file.
=> filteroffset correction - fix #2

CHANGES.rst, jwst/combine_1d/combine1d.py
Resolves #4987 
Resolves [JP-1473](https://jira.stsci.edu/browse/JP-1473)
=> JP-1473 Only warn when there are degenerate spectrum in combining

docs/jwst/pipeline/main.rst
Had a recent request to detail how WFS&C processing is controlled, so after digging up the facts I thought I might as well add them to the pipeline docs, for safe keeping.
=> Update pipeline docs for WFS&C processing

jwst/pipeline/calwebb_spec2.py
Fixes a bug accidentally introduced by #5107 and the modification to the `is_tso()` helper function. `calwebb_spec2` needs to determine the appropriate suffix for output products not based on whether an exposure is TSO mode (that's only part of it), but rather on whether the input data contain multiple integrations (i.e. a `CubeModel`). This change makes sure that the "ints" suffix is used on outputs whenever the input data are `CubeModel`.
=> Fix calspec2 multi-ints bug

CHANGES.rst, jwst/assign_wcs/util.py, jwst/source_catalog/source_catalog.py
=> enable gwcs in sourcecatalog

CHANGES.rst, jwst/assign_wcs/util.py, jwst/extract_2d/extract_2d.py, jwst/extract_2d/extract_2d_step.py
Fixes #4919 / [JP-1442](https://jira.stsci.edu/browse/JP-1442)
Fixes #5126 / [JP-1556](https://jira.stsci.edu/browse/JP-1566)
Fixes #4736/ [JP-1385](https://jira.stsci.edu/browse/JP-1385)
=> JP-1442 fix some issues with wfss mode

jwst/ami/ami_analyze.py, jwst/ami/utils.py
As part of JP-1449, this update replaces nans in the input Sci array with the median of surrounding good pixels.
=>  Added nan replacment routine.

CHANGES.rst, jwst/datamodels/dqflags.py, jwst/datamodels/fits_support.py, jwst/datamodels/model_base.py, jwst/datamodels/tests/test_models.py, jwst/datamodels/util.py, jwst/outlier_detection/outlier_detection.py
Resolves #4952 
Resolves [JP-1457](https://jira.stsci.edu/browse/JP-1457)
=> Jp 1457 Add a hash set/check to DataModel I/O to check whether schema traversal is necessary

CHANGES.rst, jwst/datamodels/source_container.py, jwst/outlier_detection/outlier_detection.py
Regression error where changes to the wrapped models in `SourceModelContainer` are not propagated back to the underlying `MultiExposureModel`.
=> Update underlying MultiExposureModel from the SourceModelContainer models

CHANGES.rst, jwst/cube_build/blot_cube_build.py, jwst/cube_build/cube_build_step.py, jwst/cube_build/ifu_cube.py
[Could use some supporting descriptive info here]
Fixes #5130 / [JP-1569](https://jira.stsci.edu/browse/JP-1569)
=> Fix Nirspec blotting to support outlier detection:  JP-1569

CHANGES.rst, jwst/transforms/models.py
Fixes #5148 / [JP-1585](https://jira.stsci.edu/browse/JP-1585) (hopefully - I have not yet got test files).
=> Wrap first angle at 360 in V23ToSky.cartesian2spherical

CHANGES.rst, jwst/transforms/models.py
Reverts spacetelescope/jwst#5185
=> Revert "Wrap first angle at 360 in V23ToSky.cartesian2spherical"

jwst/combine_1d/combine1d.py, jwst/master_background/nirspec_utils.py, jwst/pipeline/calwebb_spec2.py
A few updates to #5220 for log messages and minor bugs.
=> A few minor updates to create_background_from_multislit

jwst/master_background/nirspec_utils.py, jwst/pipeline/calwebb_spec2.py
Implement the `apply_master_background` function in `master_background/nirspec_utils.py`.
Fixes #5223 / [JP-1632](https://jira.stsci.edu/browse/JP-1632)
=> JP-1632: implement apply_master_background function in calwebb_spec2

jwst/srctype/srctype.py
Trivial bugfix in a print statement.
=> Bugfix in print statement

CHANGES.rst, jwst/extract_1d/extract.py, jwst/extract_1d/ifu.py, jwst/extract_1d/tests/test_ifu_image_ref.py
@drlaw1558 
I think this is what we need for 'extract_ifu' still thinking about the 'image_extract_ifu'
Look it over
Fixes #5117 / [JP-1562](https://jira.stsci.edu/browse/JP-1562)
=> JP-1562 - incorrect surface brightness for IFU data in extract 1d

CHANGES.rst, docs/jwst/source_catalog/arguments.rst, docs/jwst/source_catalog/reference_files.rst, jwst/pipeline/source_catalog.cfg, jwst/source_catalog/source_catalog.py, jwst/source_catalog/source_catalog_step.py
The CI threshold criteria were defined in https://jira.stsci.edu/browse/JP-645
I also made a few other minor changes (typos, clean up, etc).
=> Implement algorithm for determining whether a source is a star

CHANGES.rst, jwst/assign_wcs/util.py, jwst/exp_to_source/exp_to_source.py
Fixes #5239 / [JP-1640](https://jira.stsci.edu/browse/JP-1640)
=> JP-1640 Bounding box in resampled images not accounting for center of pixel

CHANGES.rst, jwst/pathloss/pathloss.py, jwst/pathloss/pathloss_step.py, jwst/pathloss/tests/test_pathloss.py, jwst/pipeline/calwebb_spec2.py, jwst/regtest/test_nirspec_fs_spec2.py, jwst/regtest/test_nirspec_ifu_spec2.py, jwst/regtest/test_nirspec_mos_spec2.py
Resolves [JP-1588](https://jira.stsci.edu/browse/JP-1588)
Resolves #5159
=> Jp 1588 Implement inverse of the PathLossStep

CHANGES.rst, jwst/stpipe/crds_client.py
=> JP 1643: Open first science exposure in association for prefetch of pars reference files

jwst/barshadow/bar_shadow.py, jwst/barshadow/barshadow_step.py, jwst/pathloss/pathloss.py, jwst/pathloss/pathloss_step.py, jwst/pipeline/calwebb_spec2.py, jwst/regtest/test_nirspec_mos_spec2.py
Fixes #5161 / [JP-1589](https://jira.stsci.edu/browse/JP-1589)
=> Jp 1589 Implement inverse of the BarShadowStep

jwst/extract_1d/extract.py
Update the branch of the extract_1d step that gets used for level-3 processing of NIRSpec MOS data. In this situation, each slit instance is processed separately within the `calwebb_spec3` flow, so the data enter `extract_1d` as a simple `SlitModel` (as opposed to level-2 processing, where MOS data is a `MultiSlitModel`). The branch that handles this type of input did not get all the updates needed to correctly handle the changes for aperture correction and the use of source coords for centering the extraction aperture.
In addition to fixing the necessary logic, a bunch of changes have also been made to code comments and log messages, just to try to make things easier to follow.
Fixes #5228 / [JP-1635](https://jira.stsci.edu/browse/JP-1635)
=> JP-1635: Fix extract_1d level-3 MOS processing

jwst/extract_1d/extract.py
Fix a bug in `extract_1d` that was introduced in #5250
=> Fix extract_1d bug in #5250

CHANGES.rst, jwst/datamodels/container.py, jwst/mrs_imatch/mrs_imatch_step.py
Resolves [JP-1644](https://jira.stsci.edu/browse/JP-1644)
Resolves #5246
=> Add iscopy to ModelContainer init and update MRSIMatchStep to invoke it.

CHANGES.rst, jwst/flatfield/flat_field.py
This PR fixes the NIRSPEC ALLSLIT and BOTS flat fielding problems. The MOS flat fielding problems are still be researched.
Partially resolves #4157 / [JP-1071](https://jira.stsci.edu/browse/JP-1071)
=> Fixed ALLSLIT and BOTS NIRSPEC flat fielding JP-1071

jwst/assign_wcs/nirspec.py, jwst/master_background/nirspec_utils.py, jwst/pipeline/calwebb_spec2.py
Apply fix to `assign_wcs` that was recently applied to master and add a few additional log messages here and there throughout the process of creating and applying the master background.
=> Update nrsmsb branch for assign_wcs fix and log messages

README.md
Add `pip install jwst` to the README
=> Update README.md with PyPi install instructions

CHANGES.rst, jwst/datamodels/model_base.py, jwst/model_blender/blendmeta.py, jwst/regtest/test_nircam_image.py
Resolves [JP-1665](https://jira.stsci.edu/browse/JP-1665)
Resolves #5297
=> JP-1665 Remove unwarranted closing of datamodels in blendheaders

CHANGES.rst, jwst/cube_build/cube_build_step.py, jwst/cube_build/ifu_cube.py
Fixes [JP-1642](https://jira.stsci.edu/browse/JP-1642)
=> Fix for JP-1642: NIRSpec IFU failure in calwebb_spec2

.travis.yml, jwst/datamodels/model_base.py, jwst/datamodels/tests/test_models.py, jwst/datamodels/tests/test_open.py
Just because this has been annoying enough.
Resolves #2892
=> Allow PurePath objects to initialize/open datamodels

jwst/resample/tests/test_resample_spec.py
Currently these 2 unit tests do not actually check anything.  This makes them at least check that the output WCS round trips.
=> Clean up test_resample_spec

JenkinsfileRT, JenkinsfileRT_dev
Use CRDS in serverless mode for nightly regression tests
=> Use CRDS in serverless mode for nightly regression tests

jwst/jump/tests/test_detect_jumps.py
Added another new jump unit test based on some saturated data that was getting handled incorrectly before #5404 was merged. Also did a lot of general cleanup to the test module and reduced the sizes of many tests, since typically only a few pixel values are being tested anyway.
=> Add another jump unit test

jwst/extract_1d/extract.py
Minor updates to logging and code documentation in the extract_1d step, mostly pertaining to cases where looping over integrations is being done for TSO data. No change to functionality.
=> Updates to extract_1d logging

jwst/flatfield/flat_field.py
Fixes #5445 / [JP-1766](https://jira.stsci.edu/browse/JP-1766)
=> JP-1766: Fixed a bug where NRS_LAMP IFU data caused an exception in flatfielding

jwst/flatfield/flat_field.py
Yet another bug fix for #5462. This time for sure ...
=> Another bug fix for flatfielding

jwst/combine_1d/tests/test_dq.py
Driven by analysis of [JP-1621](https://jira.stsci.edu/browse/JP-1621), a basic test of proper DQ handling in `combine1d_step` has been implemented.
=> Implement test for proper DQ handling

setup.cfg
=> Require stdatamodels from pypi

CHANGES.rst, docs/jwst/associations/index.rst, docs/jwst/associations/level2_asn_rules.rst, jwst/associations/lib/constraint.py, jwst/associations/lib/rules_level2b.py
Resolves [JP-1699](https://jira.stsci.edu/browse/JP-1699)
Resolves #5337 
Changes:
- Places more constraints on when Asn_Lv2NRSLAMPSpectral associations are created.
- Move Level 2 documentation from issue #1188 into the package documentation.
=> JP-1699 Add further constraints to rule Asn_Lv2NRSLAMPSpectral

CHANGES.rst, jwst/wfs_combine/tests/test_wfs_combine.py, jwst/wfs_combine/wfs_combine.py, jwst/wfs_combine/wfs_combine_step.py
Fixes some bugs introduced in #5500 that showed up in the `wfs_combine` regression tests.  Adds some unit tests for the expected behavior.
Resolves #5515 / [JP-1796](https://jira.stsci.edu/browse/JP-1796)
=> JP-1796: Fix wfs_combine bugs; add unit tests

CHANGES.rst, jwst/associations/lib/rules_level2b.py, jwst/associations/tests/test_level2_background.py
Resolves [JP-1802](https://jira.stsci.edu/browse/JP-1802) / #5523
=> JP-1802 Add new dither keyword subpxpts to constraints

setup.cfg
This needs to be updated in order to deliver to PyPI.
=> Update long_description_content_type in setup.cfg

CHANGES.rst, jwst/assign_wcs/tests/test_nirspec.py, jwst/datamodels/schemas/core.schema.yaml, jwst/wavecorr/tests/test_wavecorr.py, jwst/wavecorr/wavecorr.py
Closes #5080
This resolves part of JP-1540, fixing the current implementation.
=> JP-1540: Fix bugs in wavecorr

.github/workflows/ci.yml
You might want to also run the CI on push to release branches. In older branches without a workflow YAML, nothing will happen.
Depends on your backport/release workflows though.
cc @jdavies-st
=> TST: Test on push to release branches

CHANGES.rst, jwst/cube_build/coord.py, jwst/cube_build/cube_build.py, jwst/cube_build/cube_cloud.py, jwst/cube_build/ifu_cube.py
Made a minor tweak to the wavelength preselection in order to address https://jira.stsci.edu/browse/JP-1840
Additionally fixed some typos in comments, and added a few additional comments.
=> Tweak wavelength preselection, add some comments

jwst/cube_build/ifu_cube.py
Bugfix to cube_build wavelength tolerances for non-linear wavelength solutions.  @jemorrison @hbushouse
=> Fix wavelength tolerance for non-linear solutions

jwst/cube_build/cube_overlap.py
Supports #5562 / [JP-1828](https://jira.stsci.edu/browse/JP-1828)
=> fix wavelength when building internal_cal for NIRSpec lamp exposures

README.md
=> Fix actions badge link

CHANGES.rst, README.md
Resolves #5626 / [JP-1857](https://jira.stsci.edu/browse/JP-1857)
=> Update CHANGES.rst and README.md for 0.18.2 release

CHANGES.rst, jwst/lib/engdb_tools.py, jwst/lib/set_telescope_pointing.py
Resolves [JP-1875](https://jira.stsci.edu/browse/JP-1875)
Resolves #5663 
Also changed _EngDB_Value to EngDB_Value, per ticket comment request.
=> JP-1875: Make _get_wcs_values_from_siaf function public for JSDP use

CHANGES.rst, jwst/datamodels/schemas/core.schema.yaml
Resolves [JP-1874](https://jira.stsci.edu/browse/JP-1874)
Resolves #5660
=> JP-1874: Add 'IMAGE' to OPMODE enum list

CHANGES.rst, jwst/associations/lib/rules_level2b.py, jwst/associations/tests/test_wfss.py
Resolves [JP-1795](https://jira.stsci.edu/browse/JP-1795)
Fixes #5514
=> JP-1795 Asn_Lv2WFSS: Add segmentation map exposure

CHANGES.rst, jwst/assign_mtwcs/assign_mtwcs_step.py, jwst/assign_mtwcs/moving_target_wcs.py, jwst/assign_mtwcs/tests/data/test1_cal.fits, jwst/assign_mtwcs/tests/data/test_mt_asn.json, jwst/assign_mtwcs/tests/test_mtwcs.py, jwst/cube_build/ifu_cube.py
Resolves #5717 / [JP-1907](https://jira.stsci.edu/browse/JP-1907)
=> JP-1907 Allow assign_mtwcs to work with MultiSlit models

CHANGES.rst, jwst/assign_wcs/nircam.py, jwst/assign_wcs/niriss.py, jwst/assign_wcs/tests/test_nircam.py, jwst/extract_2d/grisms.py
Resolves [JP-1923](https://jira.stsci.edu/browse/JP-1923)/#5746
Added a spectral axis to coordinate frames where necessary.
Cleaned code.
=> JP-1923 tsgrism and wfss coordinate frames improvement

.github/workflows/cancel_workflows.yml, .github/workflows/ci.yml
Similar to astropy/astropy#11330
cc @jdavies-st 
p.s. I think this should be the last of the Action stuff, so you will probably not get PRs from me no more. Merge this and enjoy the peace!
=> TST: Fix cancel workflow for PR

CHANGES.rst, docs/jwst/data_products/file_naming.rst
Resolves [JP-1908](https://jira.stsci.edu/browse/JP-1908) / #5795
=> JP-1908 Update optional components description

jwst/source_catalog/source_catalog.py
This PR adds a new private module for the starfinder kernel, which prevents importing a fragile private class from `photutils` (which recently moved the private class, breaking code here).  See
https://github.com/astropy/photutils/pull/1173
https://github.com/astropy/photutils/pull/1175
https://github.com/astropy/photutils/pull/1177
cc: @jdavies-st
=> Add module for the starfinder kernel

setup.cfg
See https://github.com/asdf-format/sphinx-asdf/pull/25
=> Upgrade sphinx-asdf to fix readthedocs build

README.md
There were some commands listed in the `README.md` which caused errors when running in the `zsh` shell. To fix this I added escapes around these commands which allow them to be run in the `zsh` shell properly.
Checklist
=> Fixed README so that some commands are `zsh` compatible.

CHANGES.rst, docs/jwst/data_products/science_products.rst, docs/jwst/pipeline/calwebb_image3.rst, docs/jwst/source_catalog/main.rst
Closes #5934 
Resolves [JP-2030](https://jira.stsci.edu/browse/JP-2030)
This PR updates several pages of our documentation to include info about the (relatively new) segmentation map product.
Checklist
=> JP-2030: Add segmentation map info to docs

jwst/ramp_fitting/ols_fit.py, jwst/ramp_fitting/tests/test_ramp_fit.py
Closes #5944
Resolves [JP-2036](https://jira.stsci.edu/browse/JP-2036)
This PR breaks down the large function `fit_next_segment`.  It is long because it processes a series of special cases.  Each case has been moved to its own function.
Checklist
=> JP-2036: refactor `fit_next_segment`

jwst/lib/src/winclip.c
Title says it all. Fixes issues with #5978
=> Fix C compiler compatibility issues with winclip

CHANGES.rst, docs/jwst/source_catalog/main.rst, jwst/source_catalog/source_catalog.py
Closes https://github.com/spacetelescope/jwst/issues/5905
Fixes [JP-2063](https://jira.stsci.edu/browse/JP-2063)
=> JP-2063: Compute aperture-corrected total fluxes and magnitudes for all sources

jwst/source_catalog/source_catalog.py, jwst/source_catalog/tests/test_source_catalog.py
Followup fix to #6011.
I've also added some basic unit tests to catch this type of error.
=> Fix check for only one detected source

CHANGES.rst, jwst/associations/lib/constraint.py, jwst/associations/lib/dms_base.py, jwst/datamodels/container.py, jwst/exp_to_source/exp_to_source.py, jwst/outlier_detection/outlier_detection.py, jwst/outlier_detection/outlier_detection_ifu.py, jwst/outlier_detection/outlier_detection_scaled_step.py, jwst/outlier_detection/outlier_detection_stack_step.py, jwst/outlier_detection/outlier_detection_step.py, jwst/pipeline/calwebb_image3.py, jwst/pipeline/calwebb_spec2.py, jwst/pipeline/calwebb_spec3.py, jwst/resample/resample_step.py
This PR addresses warnings due to ambiguous API references that are causing the documentation build to fail on sphinx 4.0.
Checklist
=> Resolve documentation warnings due to ambiguous targets

CHANGES.rst, docs/jwst/assign_mtwcs/main.rst, docs/jwst/pipeline/calwebb_image3.rst, docs/jwst/pipeline/calwebb_spec3.rst
Closes #5999 
Resolves [JP-2064](https://jira.stsci.edu/browse/JP-2064)
This PR fleshes out the existing step docs for the `assign_mtwcs` step a bit more and also adds references to the step in the calwebb_image3 and calwebb_spec3 docs.
Checklist
=> JP-2064: Update docs to include more info for assign_mtwcs step

jwst/regtest/test_nircam_image.py
Fixes a bug introduced in #6033.
=> Fix test_nircam_image_stage3 regtest

CHANGES.rst, jwst/associations/lib/rules_level3.py, jwst/associations/lib/rules_level3_base.py, jwst/regtest/test_associations_sdp_pools.py, jwst/regtest/test_associations_standards.py
Resolves #5955 [JP-2044](https://jira.stsci.edu/browse/JP-2044)
This PR adds new rule `Asn_MIRMRSAux` to treat MRS backgrounds observations as science.
Checklist
=> JP-2044 Add rule Asn_MIRMRSBackground to treat background as science

CHANGES.rst, README.md
This updates README.md and CHANGES.rst for the current release.
Checklist
=> Update CHANGES and README for 1.2.0 release

CHANGES.rst, jwst/datamodels/schemas/core.schema.yaml
Closes #6080 
Resolves [JP-2107](https://jira.stsci.edu/browse/JP-2107)
This PR makes modifications to core.schema.yaml as outlined in [JP-2107](https://jira.stsci.edu/browse/JP-2107), in order to bring our datamodels schemas in synch with recent changes in the KWD.
Checklist
=> JP-2107: Modify/delete keywords for B7.8

CHANGES.rst, jwst/datamodels/schemas/core.schema.yaml
Closes #6071 
Resolves [JP-2102](https://jira.stsci.edu/browse/JP-2102)
This PR adds several new keywords to the core schema, in order to keep in synch with the JWST Keyword Dictionary at the time of the B7.8 delivery.
Checklist
=> JP-2102: Add new keywords from dictionary

CHANGES.rst, jwst/associations/lib/rules_level2b.py
Resolves JP-2118
Asn_Lv2WFSS did not discriminate on instruments. This adds the necessary constraint.
Checklist
=> JP-2118 Asn_Lv2WFSS: Add instrument constraint

CHANGES.rst, jwst/datamodels/schemas/moving_target.schema.yaml, jwst/lib/set_telescope_pointing.py, jwst/regtest/test_migrate_data.py, scripts/migrate_data
Resolves #6110 / [JP-2125](https://jira.stsci.edu/browse/JP-2125)
Resolves #6111 / [JP-2126](https://jira.stsci.edu/browse/JP-2126)
This PR updates the moving target datamodel schema to match the b7.8 keyword dictionary schema
Checklist
=> JP-2125 Update moving target schema to match b7.8 keyword schema 

CHANGES.rst, jwst/datamodels/schemas/core.schema.yaml, jwst/lib/set_telescope_pointing.py
This PR addresses a hiccup in keyword  change propagation through the system.
Checklist
=> Add back and use "CALCULATED" for ENGQLPTG

CHANGES.rst
This bugfix got put in the wrong location in the changelog.  Fixing it.
=> Correct CHANGES.rst for outlier_detection bugfix

docs/jwst/associations/level2_asn_rules.rst
Closes #6134 
Resolves [JP-2135](https://jira.stsci.edu/browse/JP-2135)
This PR updates the documented status of NRC_GRISM Stage 2 processing.
Checklist
=> JP-2135: Update status of NRC_GRISM Stage 2 processing.

docs/jwst/associations/jwst_conventions.rst, docs/jwst/associations/level2_asn_technical.rst, docs/jwst/associations/level3_asn_technical.rst, docs/jwst/associations/overview.rst, docs/jwst/associations/technote_sdp_workflow.rst, docs/jwst/datamodels/models.rst
Closes #5814 
Resolves [JP-1951](https://jira.stsci.edu/browse/JP-1951)
This PR addresses some of the concerns raised about the Association Documentation; mainly clarification statements.
Checklist
=> JP-1951 Clarify aspects of the Association documentation

CHANGES.rst, jwst/datamodels/__init__.py, jwst/extract_1d/apply_apcorr.py, jwst/extract_1d/extract.py, jwst/linearity/tests/test_linearity.py, jwst/photom/photom.py
Addresses #5380 / [JP-1739](https://jira.stsci.edu/browse/JP-1739)
This PR removes references to the stdatamodels.ndmodel module which is being removed over in [stdatamodels](https://github.com/spacetelescope/stdatamodels/pull/77).  I've also updated code that uses NDData interface methods.
Checklist
=> JP-1739: Remove references to stdatamodels.ndmodel

CHANGES.rst, jwst/associations/pool.py
Closes #6176
Resolves [JP-2201](https://jira.stsci.edu/browse/JP-2201)
This PR fixes a bug which causes an error on test collection (preventing any tests from being run) when using the `main` branch of `astropy`. It should work on the current `astropy` releases and the current astropy `main` branch.
Checklist
=> JP-2201: Fix test collection failure with astropy main branch

jwst/cube_build/src/cube_match_internal.c, jwst/cube_build/src/cube_match_sky.c, jwst/cube_build/src/cube_utils.c
Closes #
Resolves JP-
Move variable definitions in c code to the top of the code. 
Checklist
=> Fix c code for cube_build

README.md
Update the README with the relevant 1.3.0 release info
=> Update README for release 1.3.0

CHANGES.rst
Created a section in `CHANGES.rst` for v1.3.0 and fixed incorrect links to PRs.
=> Changelog for 1.3.0 

jwst/ramp_fitting/tests/test_ramp_fit.py, setup.cfg
Closes #
Resolves JP-
This PR addresses the ramp fitting multiprocessing tests.  These were skipped because the old automated test system didn't support multiprocessing.  The automated test system now runs on github actions.  The multiprocessing tests have been modified to properly work with the new refactored interface of ramp fitting.
Checklist
=> Changing ramp fitting multiprocessing tests

CHANGES.rst, jwst/datamodels/schemas/wcsinfo.schema.yaml
Closes #6276
Resolves [JP-2246](https://jira.stsci.edu/browse/JP-2246)
This PR updates the VELOSYS keyword comment in the datamodels schema, in keeping with updates being made to the JWST keyword dictionary in JWSTKD-464.
Checklist
=> JP-2246: Update VELOSYS keyword comment

CHANGES.rst, README.md
Resolves #6320 / [JP-2273](https://jira.stsci.edu/browse/JP-2273)
This updates the CHANGES.rst and README.md with the 1.3.2 release information.
Checklist
=> JP-2273: Update CHANGES.rst and README.md for release 1.3.2

jwst/regtest/test_miri_setpointing.py
This PR repairs a broken regression test, test_miri_setpointing, broken with PR#6288
Checklist
=> Use default engineering database for regression tests

CHANGES.rst, README.md
Update master with info from the 1.3.3 release.
Checklist
=> Update CHANGES.rst and README.md for 1.3.3 release

JenkinsfileRT, jwst/lib/engdb_tools.py, jwst/lib/tests/test_engdb_mast.py, jwst/lib/tests/test_engdb_mock.py, jwst/lib/tests/test_engdb_tools.py, jwst/lib/tests/test_set_telescope_pointing.py
Resolves [JP-2327](https://jira.stsci.edu/browse/JP-2327)
This PR handles the following:
- Update JenkinsRT to allow testing from the D-string engineering database
- Clean up tests to handle the testing database and better handle MAST version tests
Checklist
=> JP-2327 Clean up ENGDB tests to account for permission and url changes and fix Jenkins environment

.github/workflows/ci.yml, tox.ini
Closes #6438 
Resolves [JP-2323](https://jira.stsci.edu/browse/JP-2323)
Adds Python 3.10 to the test matrix.
Checklist
=> JP-2323: Test with Python 3.10

setup.cfg
This PR attempts to fix a doc build failure caused by a new release of the mistune package.
Checklist
=> Pin mistune package version to resolve doc build failure

CHANGES.rst, jwst/datamodels/schemas/moving_target.schema.yaml
Closes #6470
Resolves [JP-2334](https://jira.stsci.edu/browse/JP-2334)
This PR updates the moving target schema changing mt_detector_x/y to mt_sci_x/y
Checklist
=> JP-2334 updated moving target schema

scripts/migrate_data
This PR updates the `migrate_data` script to allow for changes to the column names in the moving target table that were recently implemented for inclusion in B7.9.
Checklist
=> Update migrate_data script for latest MT table changes

CHANGES.rst
Closes #6445 
Resolves [JP-2326](https://jira.stsci.edu/browse/JP-2326)
This PR simply adds a jwst change log entry for a fix made in stcal.
Checklist
=> JP-2326: Adding changes to the change log due to changes in STCAL bug fix

CHANGES.rst
Closes #
Resolves [JP-2346](https://jira.stsci.edu/browse/JP-2346)
This PR addresses addresses changes made in STCAL due to JP-2346.  Improved special handling for 2 group ramps.
Checklist
=> JP-2346: Adding to change log for changes made to STCAL.

jwst/lib/set_telescope_pointing.py, jwst/lib/tests/test_engdb_mast.py, jwst/lib/tests/test_set_telescope_pointing.py
Resolves [JP-2345](https://jira.stsci.edu/browse/JP-2345)
This PR updates all the docstrings in `set_telescope_pointing` to match the near-final version of the TR the code is based on.
Checklist
=> JP-2345 Update docstrings to match near-final TR

CHANGES.rst, docs/jwst/references_general/filteroffset_reffile.rst
Closes #6530 
Resolves [JP-2368](https://jira.stsci.edu/browse/JP-2368)
This PR updates read-the-docs for FILTEROFFSET for NIRCam Instrument.
Checklist
~~- [ ] Tests~~
=> JP-2368: Update read-the-docs for FILTEROFFSET

CHANGES.rst, docs/jwst/skymatch/README.rst
Closes #6161 
Resolves [JP-2154](https://jira.stsci.edu/browse/JP-2154)
This PR addresses some possibly confusing wording in the skymatch documentation. 
Checklist
~~- [ ] Tests~~
=> JP-2154: Clarify wording in skymatch docs

CHANGES.rst, docs/jwst/introduction.rst
Closes #6100
Resolves [JP-2117](https://jira.stsci.edu/browse/JP-2117)
Reword introduction to direct users to the JWST CRDS website instead of the, internal-only, file cache.
Checklist
=> JP-2117 Update text to point to the JWST CRDS website

CHANGES.rst, docs/jwst/dark_current/description.rst, docs/jwst/jump/description.rst, docs/jwst/linearity/description.rst, docs/jwst/ramp_fitting/description.rst, docs/jwst/saturation/description.rst
Closes #6339 
Resolves [JP-2277](https://jira.stsci.edu/browse/JP-2277)
This PR adds a short statement to step descriptions that call stcal code. This is a bit of a holdover fix until stcal steps are fully documented, after which we might consider some form of external RTD calls?
Checklist
=> JP-2277: Add a blurb to step docs with external calls to stcal

CHANGES.rst, README.md, setup.cfg
=> Prepare changelog for release

README.md
This PR updated the github README to reflect the fact that 1.4.2 is the final release for DMS B7.9.
Checklist
=> Update README for final B7.9 release

CHANGES.rst, jwst/lib/set_telescope_pointing.py
Closes #
Resolves [JP-2509](https://jira.stsci.edu/browse/JP-2509)
This PR updates the default COARSE tracking algorithm, COARSE_TR_202111, to use FGS1 exclusively.
Checklist
=> JP-2509 Update COARSE algorithm to use FGS1 exclusively

CHANGES.rst, docs/jwst/srctype/arguments.rst, docs/jwst/srctype/description.rst
Closes #6162 
Resolves [JP-2155](https://jira.stsci.edu/browse/JP-2155)
This PR completes work needed for JP-2155. The code and tests for JP-2155 were covered by PR#6720
Checklist
=> Update srctype docs per JP-2155 and change log

docs/jwst/resample/main.rst
This PR add references for the drizzle algorithm.
Checklist
=> Add references for drizzle algorithm

requirements-dev.txt
Adds all the various asdf-related package development versions to the JWST development requirements.
Checklist
=> Add relevant asdf development to development requirements.

CHANGES.rst, docs/jwst/associations/asn_make_pool.rst, docs/jwst/associations/commands.rst, docs/jwst/associations/overview.rst, jwst/associations/__init__.py, jwst/associations/lib/dms_base.py, jwst/associations/mkpool.py, jwst/associations/pool.py, jwst/associations/tests/test_mkpool.py, scripts/asn_make_pool
In investigating issues and requests from commissioning, the need for `mkpool` became apparent. However, the API had not been used nor modified since the conception of the association project.
The PR brings the code up-to-date with the current state of associations and implements the command-line tool `asn_make_pool`.
Checklist
=> Formalize the mkpool utility

CHANGES.rst, README.md
=> update for 1.4.5 dev

docs/jwst/assign_wcs/asdf-howto.rst
Resolves [JP-1768](https://jira.stsci.edu/browse/JP-1768)
This PR fixes a minor typo in the ASDF how-to docs.
Checklist
=> JP-1768: Fix typos in ASDF how-to doc

jwst/tweakreg/tests/test_multichip_jwst.py
Fixes failures in regtests due to https://github.com/spacetelescope/jwst/pull/4666
Checklist
=> Fix tweakreg multichip unit test

CHANGES.rst
Related to [JP-2572](https://jira.stsci.edu/browse/JP-2572) and [JP-2574](https://jira.stsci.edu/browse/JP-2574)
This PR just updates the jwst change log to record the fix to ramp fitting that was implemented in stcal.
Checklist
=> Update change log for ramp fit fix in stcal

docs/jwst/introduction.rst, docs/jwst/references_general/references_general.rst
Resolves [JP-2533](https://jira.stsci.edu/browse/JP-2533)
Add a link in the documentation to the step-specific reference file type table.
Checklist
=> Add a link to reference file types table (JP-2533)

CHANGES.rst, docs/jwst/cube_build/main.rst, jwst/cube_build/cube_build_step.py, jwst/cube_build/ifu_cube.py, jwst/cube_build/tests/test_cube_build_step.py, jwst/mrs_imatch/mrs_imatch_step.py
Resolves [JP-2590](https://jira.stsci.edu/browse/JP-2590)
This PR changes the default cube building weight function from EMSM to 3d drizzle, and updates the documentation accordingly.
Checklist
=> Update cube defaults to drizzle, and documentation accordingly

README.md
This PR adds and fixes some entries in the DMS Build table in the repo README
Checklist
=> Fix README DMS build table entries

CHANGES.rst, jwst/datamodels/schemas/flat.schema.yaml
Resolves [JP-2593](https://jira.stsci.edu/browse/JP-2593)
This PR adds additional keywords to the flat schema to be used in the CRDS selectors
`readpatt`, `preadpatt`, `band` - for use by MIRI
Checklist
=> JP-2593: Add more keywords to flat schema

CHANGES.rst
Move the location of the change log entry for PR #6822 to correctly indicate that it was merged *after* the 1.5.0 release.
Checklist
=> Fix change log entry location

CHANGES.rst, jwst/stpipe/core.py
Closes #6486
Resolves [JP-2343](https://jira.stsci.edu/browse/JP-2343)
This PR adds a log message to report the CRDS context by having JwstPipeline report in finalize_result. It adds the same log in JwstStep finalize_result, but is only provided if the step has no parent, i.e. standalone step running vs. a step within a pipeline.
Checklist
=> JP-2343: Add CRDS context log message to JwstStep

CHANGES.rst, README.md
=> JP-2584: prepare release 1.5.1

CHANGES.rst, README.md
This PR adds an entry for the Cal 1.5.2 release to the README, updates other parts of the README to bring them up to 1.5.2 and fixes entries in the change log that got out of alphabetical order.
Checklist
=> Update README and change log

requirements-dev.txt
I would like to add ASDF-standard to the weekly dev testing. This way I can be sure that changes to the standard don't break JWST.
Checklist
=> Add asdf-standard to dev requirements

jwst/regtest/test_miri_coron3.py
This PR adds a coron3 regression test using simulated MIRI 4QPM data provided by the instrument team.
Checklist
=> Add a MIRI coron3 regression test

CHANGES.rst, docs/jwst/ami_analyze/description.rst, jwst/ami/ami_analyze.py, jwst/ami/ami_analyze_step.py
Resolves [JP-2123](https://jira.stsci.edu/browse/JP-2123)
This PR updates the docs for the ami_analyze step to include all of the available step arguments and give a bit more explanation for `rotation_search`.
Checklist
=> JP-2123: Update ami_analyze arguments docs

CHANGES.rst, jwst/tweakreg/tweakreg_step.py
Fixes a bug introduced in #6896.
Checklist
=> JP-2562: Fix code for processing exceptions in tweakreg

.github/pull_request_template.md
=> update pull request template to be more explicit

.github/labeler.yml, .github/workflows/label_pull_request.yml
This GitHub workflow runs a labeler action on new / edited pull requests that scans the filenames of changed files and applies relevant labels. This process is configured in `.github/labeler.yml`, which I copied and modified from https://github.com/spacetelescope/stsynphot_refactor/blob/master/.github/labeler.yml
An example of this labeler working can be seen here: https://github.com/spacetelescope/stsynphot_refactor/pull/153
**Checklist**
=> automatically add labels to pull requests based on changed files

CHANGES.rst
This PR simply fixes some errors and formatting/typo/grammar issues in the change log, which I noticed while compiling release notes for Cal 1.6.2 (DMS 8.1).
=> Fix some errors and typos in the change log

CITATION.cff, README.md
Adds a Zenodo DOI and a citation file based on the current contributors list 
=> add citation and zenodo badge

CITATION.cff
Yes, my name is very common, so this should help.  😅 
=> Add an ORCID to CITATION.cff

CHANGES.rst, jwst/assign_wcs/niriss.py, jwst/assign_wcs/tests/test_niriss.py, jwst/assign_wcs/tests/test_wfss.py, jwst/assign_wcs/util.py, jwst/background/tests/test_background.py, jwst/extract_2d/grisms.py, jwst/transforms/models.py
Closes #6558
Resolves [JP-2375](https://jira.stsci.edu/browse/JP-2375)
Checklist
=> JP-2375: NIRISS V3 of CONF files

CITATION.cff
Super tiny PR, adds ORCID for Thomas Williams in CITATION.cff
=> Add ORCID for Thomas Williams

CHANGES.rst, jwst/lib/engdb_direct.py, jwst/lib/engdb_lib.py, jwst/lib/engdb_mast.py
Continuation of [JP-2865](https://jira.stsci.edu/browse/JP-2865)
This PR updates the HTTP status list to retry on. From the ENG research, 4xx statuses are also possible and should be retried on.
Regression run on previous PR
Issue already closed by previous PR
=> JP-2865 Update HTTP status list to include 4xx issues

jwst/assign_wcs/tests/test_wcs.py, setup.cfg
Updates/Fixes test_sip_approx test for gwcs>=0.18.2
=> Fix test_sip_approx test for gwcs>=0.18.2

.github/workflows/ci_cron.yml
This PR commits a benign change to the setup file for the weekly cron job test against dev dependencies,
just so that I get ownership of the file (instead of James Davies) and hence will also be the one to get the
weekly emails with results.
=> Touch weekly cron test setup

CHANGES.rst, docs/jwst/jump/arguments.rst, docs/jwst/jump/description.rst, jwst/jump/jump.py, jwst/jump/jump_step.py, jwst/jump/tests/test_jump_step.py, setup.cfg
Resolves [JP-2645](https://jira.stsci.edu/browse/JP-2645)
Add parameters to allow flagging of snowballs and showers. Corresponding PR in stcal is https://github.com/spacetelescope/stcal/pull/118
=> JP-2645 - Snowball and Shower flagging in Jump

.github/workflows/publish-to-pypi.yml
This PR applies fixes to the `check` job (that checks `requirements-sdp.txt`) on release.
=> Requirements check

CHANGES.rst, jwst/datamodels/container.py
Fixes a bug introduced by #7022
=> Fix handling of ASN directory path by the ModelContainer

CHANGES.rst, README.md
This PR updates the README table containing Cal version numbers to also include the SDP version number of each release. Also fix a few minor things in the change log.
=> Update README to include SDP version numbers

.github/workflows/cancel_workflows.yml, .github/workflows/changelog.yml, .github/workflows/ci.yml, .github/workflows/ci_cron.yml
This PR updates the actions versions used in the workflow CI
=> update actions versions

jwst/assign_wcs/tests/test_schemas.py, jwst/outlier_detection/tests/test_outlier_detection.py, jwst/wfs_combine/wfs_combine.py
Closes #7128 
Resolves [JP-2822](https://jira.stsci.edu/browse/JP-2822)
This PR fixes 2 deprecations seen in the current unit test suite with pytest and scipy.
```python
jwst/assign_wcs/tests/test_schemas.py: 21 warnings
/Users/jdavies/miniconda3/envs/jwst/lib/python3.8/site-packages/_pytest/python.py:195: PytestRemovedIn8Warning: Passing None has been deprecated.
See https://docs.pytest.org/en/latest/how-to/capture-warnings.html#additional-use-cases-of-warnings-in-tests for alternatives in common use cases.
result = testfunction(**testargs)
```
```python
jwst/wfs_combine/tests/test_wfs_combine.py: 25 warnings
/home/runner/work/jwst/jwst/jwst/wfs_combine/wfs_combine.py:740: DeprecationWarning: Please use `center_of_mass` from the `scipy.ndimage` namespace, the `scipy.ndimage.measurements` …
```
=> Fix test warnings and files left behind

CHANGES.rst, README.md
=> fix changelog after 1.8.3 release

CHANGES.rst
=> Fix change log for v 1.8.4

jwst/jump/tests/test_jump_step.py, setup.cfg
This PR skips tests requiring `opencv-python` if it is not installed.
=> make tests requiring `opencv` conditional

.github/workflows/ci.yml
This PR adds more tests for various Python versions, and makes tests dependent on first running checks.
=> expand CI matrix to test more Python versions

CHANGES.rst, README.md, jwst/lib/tests/test_siafdb.py, jwst/regtest/test_stp_jw00697013.py
Resolves [JP-3020](https://jira.stsci.edu/browse/JP-3020)
This PR addresses an issue with SIAF-related tests and the PRD version changes. The PRD version is fixed for those tests that are not testing for changes.
=> JP-3020 Pin PRD versions for tests that are not testing changes in PRD

CHANGES.rst, jwst/extract_1d/soss_extract/soss_centroids.py, jwst/extract_1d/soss_extract/soss_utils.py
This PR addresses Numpy deprecations in `numpy>=1.24.0`
=> replace usages of `np.int()` with `int()`

JenkinsfileRT, JenkinsfileRT_dev
This PR addresses the analogous issue from https://github.com/spacetelescope/romancal/pull/621 before it can become and issue for the JWST pipeline
=> update version of `conda` used in Jenkins environment

CHANGES.rst, README.md
This PR just updates and cleans up the change log and README for the B9.1 and 9.1.1 releases with additional and corrected information.
=> Clean up change log and README for B9.1 and 9.1.1 releases

requirements-sdp.txt
This PR adds the `sdp` extra to instructions to populate `requirements-sdp.txt`:
https://github.com/spacetelescope/jwst/blob/26cf4098c633f80535e1a37293b58ca2dd9a6020/setup.cfg#L69-L72
=> add SDP extras to `requirements-sdp.txt`

CHANGES.rst, jwst/lib/engdb_mast.py, jwst/tweakreg/astrometric_utils.py
I noticed that the `check-security` CI job started failing recently. This is my attempt to fix this. 
=> Bugfix for failing security checks

CHANGES.rst, docs/jwst/outlier_detection/outlier_detection.rst, docs/jwst/outlier_detection/outlier_detection_spec.rst, docs/jwst/ramp_fitting/description.rst, jwst/lib/engdb_tools.py
Closes #7298 
This PR was primarily created to fix #7298, but also includes a couple other minor doc updates that I ran across recently.
=> Various doc fixes

JenkinsfileRT, JenkinsfileRT_dev
Resolves [SPB-1305](https://jira.stsci.edu/browse/SPB-1305)
use Python 3.11 in regression tests on Jenkins @BGannon2 
=> use Python 3.11 in Jenkins job

README.md
Resolves [JP-3092](https://jira.stsci.edu/browse/JP-3092)
This PR updates the "DMS build map" table in the README, to incorporate the suggestions in JP-3092.
=> JP-3092: Updated DMS build map in README

docs/jwst/data_products/science_products.rst, docs/jwst/data_products/stages.rst, docs/jwst/pipeline/calwebb_tso3.rst, docs/jwst/user_documentation/available_pipelines.rst
Resolves [JP-3172](https://jira.stsci.edu/browse/JP-3172)
Closes #4447 
This PR make updates to the data products docs to fix issues raised in https://github.com/spacetelescope/jwst/issues/4447 and https://github.com/spacetelescope/jwst/issues/4449
=> JP-3172: Update data products docs

CHANGES.rst, docs/jwst/extract_1d/description.rst, docs/jwst/pipeline/calwebb_spec2.rst, docs/jwst/resample/main.rst, jwst/extract_1d/extract_1d_step.py, jwst/flatfield/flat_field.py, jwst/regtest/test_nirspec_fs_spec2.py, jwst/resample/resample_spec_step.py
Resolves [JP-3094](https://jira.stsci.edu/browse/JP-3094)
Closes #
This PR updates flat fielding to be able to process NIRSpec Fixed Slit _rateints input.
=> (JP-3094) NIRSpec FS rateints flat_field processing

jwst/skymatch/region.py, jwst/skymatch/skyimage.py, jwst/skymatch/skymatch.py, jwst/skymatch/skymatch_step.py, jwst/skymatch/skystatistics.py
This PR simply addresses PEP8 issues and also comments out `_calc_sky_orig` function (I just do not have time at this moment to test whether this code can be safely restored. I will do this later but I want to keep it here for convenience.)
I expect no changes to any tests. Most PEP8 issues were line length.
Regression test is running here: https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/635/
=> PEP8 skymatch

jwst/skymatch/region.py, jwst/skymatch/skyimage.py, jwst/skymatch/skymatch.py, jwst/skymatch/skymatch_step.py, jwst/skymatch/skystatistics.py
Reverts spacetelescope/jwst#7532
=> Revert "PEP8 skymatch"

CHANGES.rst, docs/jwst/package_index.rst, docs/jwst/pixel_replace/index.rst
Resolves [JP-3005](https://jira.stsci.edu/browse/JP-3005)
Closes #
This PR addresses some bad docs updates I made, causing the docs build to fail.
=> JP-3005: Fix bad docs update

requirements-max.txt
test the new version of `stdatamodels` with regression tests
=> [CI] bump max version of `stdatamodels`

jwst/ami/tests/test_ami_analyze.py, jwst/resample/resample_utils.py, jwst/scripts/pointing_summary.py, setup.cfg
This PR addresses warnings seen after downstream tests run on gwcs PRs.
=> Fix some warnings

setup.cfg
This PR updates the dependency requirements to use stcal>=1.4.0
=> Point to latest release of stcal

README.md, requirements-max.txt
=> Prepare for 1.11.1 release

CHANGES.rst, jwst/cube_build/ifu_cube.py, jwst/cube_build/src/cube_match_sky_pointcloud.c, jwst/regtest/test_miri_mrs_spec3.py, jwst/regtest/test_nirspec_ifu_spec3.py
Resolves [JP-3354](https://jira.stsci.edu/browse/JP-3354)
Closes #7841 
This PR fixes a bug in cube_build when creating an IFU cube using weighting='emsm'.
https://stsci.service-now.com/nav_to.do?uri=%2Fincident.do%3Fsys_id%3Dced5d8024778b510ec5b9448436d43ac%26sysparm_stack%3Dincident_list.do%3Fsysparm_query%3Dactive%3Dtrue%26sysparm_view%3DJWST%26sysparm_view_forced%3Dtrue
=> JP-3354 Cube build emsm bug

CHANGES.rst, jwst/outlier_detection/outlier_detection_step.py
Resolves [JP-3311](https://jira.stsci.edu/browse/JP-3311)
Closes #7747 
This PR addresses the outlier_i2d file showing up regardless of save_intermediary_results.
=> JP-3311: OutlierDetectionStep producing extraneous outlier_i2d files

CHANGES.rst, jwst/charge_migration/charge_migration_step.py, jwst/charge_migration/tests/test_charge_migration.py
Resolves [JP-3363](https://jira.stsci.edu/browse/JP-3363)
Closes #
This PR addresses test to determine if the data array was changed at all after running the step.
=> JP-3363: Fix behavior of charge_migration step around bad pixels

jwst/regtest/test_nirspec_brightobj.py, jwst/regtest/test_nirspec_mos_spec2_steps.py, jwst/regtest/test_nirspec_steps_spec2.py
This PR fixes regression tests for flat field inversion, following a change to NaN handling for NIRSpec flat correction.
=> Fix regression tests for flat field inversion

README.md
This PR updates the DMS Build info table in the README for B10.0 info.
=> Update README for B10.0 version info

requirements-dev-thirdparty.txt
Fix an inaccurate description in requirements
=> astropy wheel is built nightly, not weekly

CHANGES.rst, jwst/emicorr/emicorr.py
Resolves [JP-3248](https://jira.stsci.edu/browse/JP-3248)
Closes #
This PR addresses a subarray = full bug fix.
=> JP-3248 MIRI Subarrays 390 Hz EMI bug fix 2

CHANGES.rst, jwst/emicorr/emicorr.py
Resolves [JP-3248](https://jira.stsci.edu/browse/JP-3248)
Closes #
This PR addresses fixing bug with subarray=full readpattern=slow
=> JP-3248 MIRI Subarrays 390 Hz EMI bug fix 3

CHANGES.rst, jwst/emicorr/emicorr.py
This PR fixes some remaining issues with the emicorr step when it doesn't find matching mode info in the reference file or have info itself for a given mode, as well as optimizing (and hence speeding up) some of the slower parts of the algorithm.
=> reducing running time for EMICORR step

CHANGES.rst, CITATION.cff, README.md, jwst/emicorr/emicorr_step.py
metadata for PyPI-only release `1.13.4`, with cherry-picked #8171 
This PR should be merged, not squashed
=> metadata for `1.13.4`

CHANGES.rst, CITATION.cff, README.md
=> Release metadata for 1.13.4

CHANGES.rst, docs/jwst/extract_1d/description.rst, docs/jwst/residual_fringe/main.rst
Resolves [JP-3352](https://jira.stsci.edu/browse/JP-3352)
Closes #7836
This PR add documentation explaining the 1-D residual fringe correction. 
=> JP-3352 update residual fringe documentation

docs/jwst/stpipe/config_asdf.rst
Resolves [JP-3590](https://jira.stsci.edu/browse/JP-3590)
=> JP-3590: Fix config_asdf doc entry

jwst/outlier_detection/tests/test_outlier_detection.py
While working on a related issue I noticed a few minor issues with the tso unit test in outlier detection.
- time variability was added to the container data after it was converted to a cube (these don't share memory so the input cube did not have this variability). This PR moves the cube conversion to after the variability is added.
- the test checks that the result and input data match to verify that the input data was not changed. However the input cube and output cube share the same memory. This means any modification of the input data by the step would not cause the test to correctly fail. This PR checks the result against the container used to make the cube (which doesn't share memory).
Importantly these changes don't cause the test to fail so the current step code is both …
=> minor fixes to outlier detection tso unit test

CITATION.cff
The PR adds me (and my orcid) to the citation file.
=> add Brett Graham to citation

jwst/associations/asn_edit.py, jwst/associations/association.py, jwst/associations/pool.py, jwst/fits_generator/main.py, jwst/fits_generator/objects.py, jwst/fits_generator/template.py
=> Remove some unused modules

README.md
Resolves a link in main README
Closes #
This PR addresses CRDS PUB link user documentation in README
=> docs(README): link CRDS PUB

CHANGES.rst, docs/index.rst, docs/jwst/changes.rst
This PR adds the changelog to the sphinx documentation.
https://jwst-pipeline--8716.org.readthedocs.build/en/8716/jwst/changes.html
Adding the file to sphinx revealed many formatting issues in `CHANGES.rst` fixed in this PR.
=> Add changelog to docs

CHANGES.rst, jwst/stpipe/core.py, jwst/stpipe/tests/test_step.py
Reverts spacetelescope/jwst#8760
=> Revert "JP-3729: log version and crds context at end of step/pipeline runs"

jwst/model_blender/_schemautil.py
Fixes: #8783
Github actions regression tests (which will run sonar scan): https://github.com/spacetelescope/RegressionTests/actions/runs/10851716705
=> rename variable to silence sonarscan

CITATION.cff
=> Update citations file for build 11.1

docs/jwst/user_documentation/reference_files_crds.rst
Add some useful information for developers about configuring a local CRDS cache.  
This is a documentation change only, no need to run regtests.
- …
=> Add CRDS cache information for developers

README.md, docs/index.rst, docs/jwst/user_documentation/more_information.rst
Resolves [JP-3691](https://jira.stsci.edu/browse/JP-3691)
Add links to JDox pages to README and top-level readthedocs index page.
- …
=> JP-3691: Add links to JDox

docs/jwst/imprint/description.rst
Resolves [JP-3811](https://jira.stsci.edu/browse/JP-3811)
Add documentation for specifying imprints in spec2 association files.
- …
=> JP-3811: Update imprint documentation to mention association input

.pre-commit-config.yaml, .ruff.toml, jwst/engdblog/__init__.py, jwst/engdblog/engdblog.py
Part of [JP-3917](https://jira.stsci.edu/browse/JP-3917)
Part of #9271
This PR addresses style checks for `engdblog`.
ref: https://github.com/spacetelescope/jwst/wiki/Workflow#updating-a-module-for-code-style
xref #9279
=> JP-3917: Apply code style rules to engdblog

.github/pull_request_template.md
As discussed with @tapastro . No need for change log and no need to run tests.
=> Update suggested milestone in PR template

CHANGES.rst, README.md, changes/9301.tweakreg.rst, changes/9326.barshadow.rst, changes/9337.resample.rst, changes/9338.ramp_fitting.rst
=> Metadata for 1.18.0rc2

docs/jwst/outlier_detection/main.rst
Add mention of MIRI imager TSOs under the TSO modes list
=> Small update to outlier_detection docs

changes/9361.pipeline.rst, jwst/pipeline/calwebb_ami3.py
Partially resolves [JP-3978](https://jira.stsci.edu/browse/JP-3978)
This PR addresses a bug found in testing of the 1.18.0rc2 candidate for NIRISS AMI - our tests do not appear to cover a case where the number of science and psf members in the ami3 association are different. A recent code style update causes errors in this case. This PR reverts the strictness of the list zip in the ami3 pipeline code.
Note that intended behavior is not well-defined; a future PR should change this behavior once that is clarified. Until that point, this PR reverts the recent change such that behavior matches pre-1.18.0 code.
=> JP-3978: Allow unequal number of target and psf exposures in calwebb_ami3

jwst/mrs_imatch/tests/test_configuration.py
Resolves [JP-3912](https://jira.stsci.edu/browse/JP-3912)
This PR changes one of the mrs_imatch unit tests so that the step skip parameter is checked but the step is not run
=> JP-3912: Fix imatch test

changes/9356.flatfield.rst, changes/9356.photom.rst, docs/jwst/flatfield/arguments.rst, docs/jwst/photom/arguments.rst, jwst/flatfield/flat_field.py, jwst/flatfield/tests/test_clean_wl.py, jwst/flatfield/tests/test_combine_fast_slow.py, jwst/flatfield/tests/test_flatfield.py, jwst/flatfield/tests/test_interpolate_flat.py, jwst/photom/photom.py, jwst/photom/tests/test_photom.py
Resolves [JP-3956](https://jira.stsci.edu/browse/JP-3956)
This PR addresses:
* BUG: Fix err and var for inverse steps.
* STY: Minor docstring and style fixes.
Also see:
* #9330
* https://github.com/spacetelescope/jwst/pull/9085
* https://github.com/spacetelescope/jwst/pull/9254
* https://github.com/spacetelescope/jwst/pull/9320
=> JP-3956: Fix error propagation for inverse steps (photom, flatfield)

jwst/assign_wcs/nirspec.py
Resolves [JP-3952](https://jira.stsci.edu/browse/JP-3952)
Closes #9310 
This PR fixes a small bug introduced by numpy 2.0 that caused a log message containing a list of numpy int objects to retain the datatypes of those objects - see issue for details.
This should be a relatively rare bug: it only happens within lists, because the string representation of e.g. `f"{np.int16(100)}"` correctly shows the value `100`.  And it only happens when the list contains numpy datatypes, not for simple ints or floats.
A cursory search of the codebase shows that this is the only instance.
=> JP-3952: Fix log message for assign_wcs get_open_slits

.pre-commit-config.yaml, .ruff.toml, jwst/straylight/__init__.py, jwst/straylight/straylight.py, jwst/straylight/straylight_step.py
Partially resolves [JP-3857](https://jira.stsci.edu/browse/JP-3957)
This PR added the code style changes to documentation for the straylight step. 
Results of regression tests: https://github.com/spacetelescope/RegressionTests/actions/runs/14651780087
=> JP-3857_straylight_code_style

pyproject.toml
Now that PR making standalone steps run by default has been merged
Resolves [JP-3912](https://jira.stsci.edu/browse/JP-3912)
This PR updates the stpipe dependency in pyproject.toml to point to github main.
=> Set stpipe dependence to github main 

docs/conf.py, docs/jwst/associations/asn_from_list.rst, docs/jwst/associations/asn_generate.rst, docs/jwst/associations/association.rst, docs/jwst/associations/association_reference.rst, docs/jwst/associations/design.rst, docs/jwst/associations/generator.rst, docs/jwst/associations/index.rst, docs/jwst/associations/jwst_conventions.rst, docs/jwst/associations/level2_asn_rules.rst, docs/jwst/associations/level2_asn_technical.rst, docs/jwst/associations/level3_asn_rules.rst, docs/jwst/associations/level3_asn_technical.rst, docs/jwst/associations/overview.rst, docs/jwst/associations/pool.rst, docs/jwst/associations/registry.rst, docs/jwst/associations/technote_sdp_workflow.rst
This PR addresses some broken ref I noticed while working on #8806
https://jwst-pipeline--9408.org.readthedocs.build/en/9408/jwst/associations/index.html
Out of scope: #9383
For some reason, sphinx-automodapi is giving me pain building doc of this package locally in WSL2, so I will have to rely on RTD PR build for now.
=> DOC: Fix association doc references, general doc updates

.pre-commit-config.yaml, .ruff.toml, jwst/persistence/__init__.py, jwst/persistence/persistence.py, jwst/persistence/persistence_step.py, jwst/persistence/tests/test_persistence.py
Addresses [JP-3861](https://jira.stsci.edu/browse/JP-3861)
This PR implements style changes for the persistence step
=> JP-3861: Persistence style updates

.pre-commit-config.yaml, .ruff.toml, docs/jwst/align_refs/description.rst, docs/jwst/klip/description.rst, jwst/coron/__init__.py, jwst/coron/align_refs_step.py, jwst/coron/hlsp.py, jwst/coron/hlsp_step.py, jwst/coron/imageregistration.py, jwst/coron/klip.py, jwst/coron/klip_step.py, jwst/coron/median_replace_img.py, jwst/coron/stack_refs.py, jwst/coron/stack_refs_step.py, jwst/coron/tests/test_coron.py
Addresses [JP-3861](https://jira.stsci.edu/browse/JP-3861)
This PR applies style rules to the coron package
=> JP-3861: Style formats for the coron package

changes/9445.white_light.rst, jwst/white_light/tests/test_white_light.py, jwst/white_light/white_light.py
Resolves [JP-3939](https://jira.stsci.edu/browse/JP-3939)
Closes #9286
This PR adds `int_mid_BJD_TDB` to the output ecsv table of the white light step.
=> JP-3939: Add BJD_TDB to white light output table

changes/9478.refpix.rst, jwst/refpix/refpix_step.py
Fix a small bug stemming from code style fixes.  There were a couple malformed log messages in off-nominal refpix use cases.
=> Fix refpix log messages

.pre-commit-config.yaml, .ruff.toml, jwst/mrs_imatch/__init__.py, jwst/mrs_imatch/mrs_imatch_step.py, jwst/mrs_imatch/tests/test_apply_background.py, jwst/mrs_imatch/tests/test_configuration.py
Resolves [JP-3917](https://jira.stsci.edu/browse/JP-3917)
This PR addresses #9271
=> JP-3917: Style fix for mrs_imatch

.pre-commit-config.yaml, .ruff.toml, jwst/photom/__init__.py, jwst/photom/miri_imager.py, jwst/photom/miri_mrs.py, jwst/photom/photom.py, jwst/photom/photom_step.py, jwst/photom/tests/test_photom.py
Addresses [JP-3861](https://jira.stsci.edu/browse/JP-3861)
This PR applies code style changes to the photom package
=> Photom style

docs/jwst/refpix/arguments.rst
=> adding missing argument irs2_mean_subtraction to refpix documentation

jwst/regtest/st_fitsdiff.py
This PR adds the maximum and minimum values to the report for files a and b when doing a table comparison.
=> adding max and min values for files a and b in table comparison

.pre-commit-config.yaml, .ruff.toml, jwst/fringe/__init__.py, jwst/fringe/fringe.py, jwst/fringe/fringe_step.py
Helps to resolve [JP-3857](https://jira.stsci.edu/browse/JP-3857)
This PR addresses up dates the fringe step to add documentation code style changes
=> JP-3857 Fringe Step code style changes

changes/9485.photom.rst, jwst/photom/photom.py, jwst/photom/tests/test_photom.py, pyproject.toml
Resolves [JP-3837](https://jira.stsci.edu/browse/JP-3837)
Requires https://github.com/spacetelescope/stdatamodels/pull/484
Update photom to allow NIRCam imaging to match values by subarray.  If the subarray column is present in the photom reference file, it is used for matching to the input data subarray.  If not, only the current filter and pupil matching criteria are used.
This should allow maximum flexibility while NIRCam prepares the new photom files: current files will work as is, new ones will work when they are delivered.
=> JP-3837: Allow NIRCam image to match subarray in photom table

jwst/regtest/test_nircam_image.py, jwst/regtest/test_niriss_image.py
Partially resolves [JP-3765](https://jira.stsci.edu/browse/JP-3765)
Add regression tests for new likelihood ramp fitting algorithm.
I added tests for NIRISS imaging, since NIRISS is currently considering turning likelihood on by default, and for NIRCam imaging, since it had a test data set with a ZEROFRAME available.  This will be useful for testing [JP-3891](https://jira.stsci.edu/browse/JP-3891).
=> JP-3765: Add regression tests for likelihood algorithm

jwst/source_catalog/source_catalog.py
Add a filter for a divide by zero warning in the source catalog step.
=> Catch divide by zero warning

changes/9523.background.rst, docs/jwst/background_step/arguments.rst, docs/jwst/background_step/description.rst, jwst/background/background_step.py, jwst/background/background_sub_soss.py, jwst/background/tests/test_background_soss.py, jwst/pipeline/calwebb_spec2.py, jwst/regtest/test_niriss_soss.py, pyproject.toml
Resolves [JP-3825](https://jira.stsci.edu/browse/JP-3825)
This PR implements the NIRISS team's algorithm for deriving a background correction from reference zodiacal dust templates provided as part of the new SossBkgModel, see https://github.com/spacetelescope/stdatamodels/pull/492
Two lingering issues: 
- the team requested a command line parameter to set min/max threshold background flux percentiles; we have other instances of using the configobj `float_list` attribute, but it appears as though a default value is not allowed. I need to look into our other specs with `float_list` entries to understand how defaults are used there, if at all. The current implementation is a bit kludgey.
- the reference file is on TEST but not yet on OPS.
=> JP-3825: Implement background subtraction from reference file for NIS_SOSS

jwst/regtest/st_fitsdiff.py, jwst/scripts/stfitsdiff.py
Temporary patch for #9572
Revert STFITSDiff to FITSDiff for comparisons, to work around a critical bug.
=> Revert to FITSDiff for regtest comparisons

jwst/associations/lib/rules_level3_base.py, jwst/pipeline/calwebb_spec3.py
Follow-up to [JP-3931](https://jira.stsci.edu/browse/JP-3931)
This PR updates the Level 3 ASN rules to use the actual target ID instead of a placeholder for WFSS data.
=> Use actual target id instead of placeholder for WFSS level 3 associations

.github/workflows/ci.yml, .github/workflows/tests_devdeps.yml, pyproject.toml
(cherry picked from commit 1e0ec9430a37b441f2abc1776e15783d75d77786)
=> Backport PR #9626 on branch release/1.19.x (Remove python upper pin)

docs/jwst/background_subtraction/description.rst
Follow up to  [JP-3995](https://jira.stsci.edu/browse/JP-3995)
Clarify and add examples for running bkg_subtract as a standalone step.
=> JP-3995: Clarify standalone bkg_subtract input

.github/workflows/ci.yml, CODE_OF_CONDUCT.md, README.md, docs/conf.py, docs/jwst/assign_wcs/asdf-howto.rst, docs/jwst/assign_wcs/main.rst, docs/jwst/background_subtraction/description.rst, docs/jwst/data_products/product_types.rst, docs/jwst/data_products/science_products.rst, docs/jwst/data_products/stages.rst, docs/jwst/mrs_imatch/description.rst, docs/jwst/outlier_detection/outlier_detection_imaging.rst, docs/jwst/refpix/description.rst, docs/jwst/resample/main.rst, docs/jwst/skymatch/description.rst, docs/jwst/source_catalog/main.rst, docs/jwst/tweakreg/README.rst, jwst/associations/lib/rules_level3.py, tox.ini
Closes #9384
This PR adds a link check job. Maybe once I know it works, I would move it to cron (if it is even still used) because you don't have to run this every commit.
No need to run RT.
=> TST: Add linkcheck to CI

CHANGES.rst
This PR addresses a little bit of https://github.com/spacetelescope/jwst/issues/9383 , as seen in https://github.com/spacetelescope/jwst/pull/9666 . This round is only the rendered change log (`CHANGES.rst`). Because change log is supposed to preserve history, I chose not to do live links because those links might break in the future if things get moved around.
No need for RT.
Rendered change log: https://jwst-pipeline--9839.org.readthedocs.build/en/9839/jwst/changes.html
=> DOC: Fix broken refs in static change log

docs/conf.py, docs/jwst/lib/set_telescope_pointing.rst, jwst/lib/engdb_direct.py, jwst/lib/engdb_lib.py, jwst/lib/engdb_mast.py, jwst/lib/set_telescope_pointing.py, jwst/lib/siafdb.py
This PR addresses a little bit of https://github.com/spacetelescope/jwst/issues/9383 , as seen in https://github.com/spacetelescope/jwst/pull/9666 .  This round fixes broken refs in `lib`.
Probably no need for RT but I can run upon request.
=> DOC: Fix broken refs in lib modules
