- Jenkinsfile
- JenkinsfileRT
A space in the `buildConfig.name` attribute is causing problems in the dump of the conda environment spec file.
> Remove spaces from Jenkins build names

- CHANGES.rst
- jwst/datamodels/container.py
- jwst/mrs_imatch/mrs_imatch_step.py
- jwst/tweakreg/tweakreg_step.py
This reverts the complexity in `ModelContainer` introduced in #1027.
- It added complexity to the code with no speed or memory usage benefit.  See discussion in #1027.  The data arrays in opened `DataModels` are memory mapped, so this is expected.
- It made determining the state of `ModelContainer._models` difficult.  Instead of it always being a list of `DataModels`, sometimes it was a list of strings of FITS files, but that depended on the operations done to the `ModelContainer`, i.e. if one had tried to read one of the models.  One could end up in a state were `_models` was a mixed list of strings and open `DataModels`.  Not good.
- Removes the `persist` arg to `ModelContainer`.  When `True`, it just delayed when the model was actually opened and could lead to the half-open list state …
> Revert "Merge pull request #1027 from bernie-simon/jit_container"

- CHANGES.rst
- docs/jwst/extract_1d/index.rst
- docs/jwst/extract_1d/reference_image.rst
- jwst/extract_1d/extract.py
- jwst/extract_1d/ifu.py
The `extract_1d` step can now use a reference image to define the source and optional background regions for IFU data.  The format of this reference image is the same as has been supported for other modes.
Resolves #3213.
Closes #3213.
> Use reference image for IFU data

- CHANGES.rst
- jwst/combine_1d/combine1d.py
The `combine_1d` step failed in the call to wcs.invert because two of the arguments (right ascension and declination) were scalars, but the wavelength was an array.  Right ascension and declination are now stored as arrays, even though their values are constant.
Another bug was that in the files for the test case, the net column was all zeros (because the spectra had been extracted from flux-calibrated data).  The flux was being weighted by the sensitivity (so that the quantity that was accumulated would be in units of counts), but the sensitivity was gotten as the ratio of net to flux; therefore, the weight was being set to zero.  A test has been added to disable including the sensitivity in the weight for flux if the net is zero.
Closes #3270.
> Combine1DStep needed arrays of right ascension and declination

- CHANGES.rst
- jwst/background/background_step.py
This is for #3135 it it covers the checking the calspec2 background step when NIRSPEC data is run.
The GWA_XTILT and GWA_YTILT have to match. 
I did put in a tolerance - of 1e-15. I might need to change that part. 
Fixes #1149.
> Updates to calspec2 background step to check NIRSPEC GWA Tilt values

- CHANGES.rst
- jwst/master_background/master_background_step.py
Modified `MasterBackgroundStep` to be skipped if `BackgroundStep` was already run on the input science data.  A new `force_subtract` parameter is added to the step to override this logic.
Resolves #3135
> Add control flow logic for master background step

- jwst/ramp_fitting/ramp_fit.py
- jwst/ramp_fitting/ramp_fit_step.py
Handles the MIRI case where multiple first groups/frames need to be excluded due to reset effects in the data.
> Ignore contiguous leading groups in which all pixels have been flagged DO_NOT_USE.

- jwst/tests_nightly/general/nircam/test_nrc_image3_1.py
- jwst/tests_nightly/general/nircam/test_tso3.py
Updated 4 NIRCam regression tests - 2 for `calwebb_image3` and 2 for `calwebb_tso3` - to include comparison of the cat.ecsv and phot.ecsv products that they create.
> Update reg tests to compare ecsv files

- CHANGES.rst
- jwst/lib/reffile_utils.py
Updated the reference file utility routines that extract subarrays from reference files so that when errors are encountered due to bad subarray keyword values (e.g. SUBSTRTn, SUBSIZEn) in either the science or reference file, the resulting error messages are more explicit about giving all the 1-indexed SUBSTRTn and SUBSIZEn values for both the science and reference file, and list the computed array slice indexes as python 0-indexed values.
Fixes #3160
> Improve subarray slice error messages

- jwst/tests_nightly/general/miri/test_miri_steps.py
- jwst/tests_nightly/general/nircam/test_nircam_steps.py
- jwst/tests_nightly/general/niriss/test_niriss_steps.py
- jwst/tests_nightly/general/nirspec/test_nirspec_steps.py
- jwst/tests_nightly/general/nirspec/test_spec2pipelines.py
Tests in
```
jwst/tests_nightly/general/nirspec/test_spec2pipelines.py
```
were producing the same output directory names
```
test_nrs_fs_multi_spec2_test_n0
```
when run using `pytest-xdist` and so when uploaded to Artifactory, one would overwrite the other.
This PR shortens names so that each test output dir gets a unique name.  Also, one of the IFU tests was being labeled as a NIRSpec FS test.  Fixes that too.  Shortens test IDs elsewhere too to remove the word "test" redundancy in the output directories.
> Shorten test names so result dirs don't overwrite on Artifactory

- jwst/datamodels/container.py
- jwst/datamodels/filetype.py
- jwst/datamodels/util.py
- jwst/master_background/expand_to_2d.py
- jwst/master_background/master_background_step.py
- jwst/master_background/tests/test_master_background.py
- jwst/tests_nightly/general/miri/test_miri_steps_single.py
In addition to implementing the basic master background creation in `MasterBackgroundStep`, it also allows a `ModelContainer` to be initialized by a list of of files, i.e.
```
from glob import glob
from jwst import datamodels
files = glob('*_x1d.fits')
container = datamodels.open(files)
```
Which is useful for testing and general use.
Resolves #3211.
Depends on #3274 being merged first.
To do:
> Split input in master_background into source and background

- jwst/datamodels/container.py
- jwst/datamodels/fits_support.py
- jwst/datamodels/model_base.py
- jwst/datamodels/util.py
We no longer have to pass around our ASDF extensions internally in the `datamodels` code.  They are always available via `entry_points`.  Following from our discussion in https://github.com/spacetelescope/jwst/pull/3227#pullrequestreview-211491661
Fixes #3231
> Remove DataModel._extensions attribute

- CHANGES.rst
- jwst/tweakreg/tweakreg_catalog.py
- jwst/tweakreg/tweakreg_step.py
This PR fixes the crash described in https://github.com/spacetelescope/jwst/issues/3287 by adding code to weed out sources that lie outside of the domain of definition of data model's WCS.
> Fix a failure in tweakreg when catalogs contain sources outside WCS domain

- docs/jwst/master_background/arguments.rst
- docs/jwst/master_background/description.rst
- docs/jwst/master_background/index.rst
Updated the `master_background` step docs to include more descriptions of how things work for cases of dedicated background target exposures and nodded exposures, including descriptions of the ASN file inputs and what data are used from the input `x1d` products for the different scenarios. Details of exactly how the bkg spectra are combined in `combine_1d` is left to that step's docs.
Fixes #3137
> Update master_background docs

- CHANGES.rst
- jwst/tweakreg/tweakreg_catalog.py
I think the most appropriate exception type here is `TypeError`. Also corrected a typo.
> Change exception type for incorrect input

- CHANGES.rst
- jwst/cube_build/ifu_cube.py
- jwst/master_background/master_background_step.py
- jwst/outlier_detection/outlier_detection_ifu.py
- jwst/pipeline/calwebb_spec3.py
This is a first-cut, crude attempt to add the `master_background` subtraction step to the `calwebb_spec3` pipeline. For sake of simplicity I've put it before the point in the flow where `MultiSlitModel` data get rearranged from exposure-based models to source-based models. We may need to revisit this when attempting to apply to NIRSpec MOS observations.
I noticed that at least the `cube_build` step needs access to the model.meta.asn_table meta info, which apparently is not preserved when using `split_container` or in the `ModelContainer` coming back from `master_background`, so I've got a line in there to copy it manually to the models passed to subsequent steps.
Fixes #3288
> Add master_background step to calspec3 pipeline

- CHANGES.rst
- jwst/srctype/srctype.py
- jwst/srctype/tests/test_srctype.py
Updated the srctype step to apply more logic in certain situations. The new hierarchy is:
- If it's a background target, set SRCTYPE = 'EXTENDED' no matter what (ignore any user input)
- If it's a nodded exposure, set SRCTYPE = 'POINT' no matter what (ignore any user input)
- If neither of those situations apply, use the user input, if it exists
- If all else fails, apply specified defaults
The first 2 allow for correct functioning of down-stream steps, such as `extract_1d`, so that they do the proper thing when deciding how to do their processing.
Note that all of this logic only applies to observing modes that have a single pre-defined target/source, such as MIRI LRS, MIRI MRS, NIRSpec fixed-slit, and NIRSpec IFU. NIRSpec MOS still uses the stellarity values supplied in the MSA meta …
> Update srctype rules

- jwst/master_background/master_background_step.py
- jwst/pipeline/calwebb_spec3.cfg
- jwst/pipeline/calwebb_spec3.py
Fix some issues uncovered after merging PR #3296. The updates eliminate the use of ``split_container`` in ``calwebb_spec3`` if ``master_background`` is called, so that it only gets used once and hence avoids file handle and memory issues. Instead of calling ``split_container`` it simply looks at the ASN member info to see if there are any background members present.
Also updated the ``split_container`` function to use the ``lower()`` method on all string comparisons. This problem was revealed by one of the regression tests that used upper-case "SCIENCE" in an ASN file.
> Fix issues with calspec3 use of split_container

- jwst/datamodels/schemas/guider_cal.schema.yaml
- jwst/datamodels/schemas/guider_raw.schema.yaml
Removed keyword GS_STATE and changed data type of GUIDESTA from number to string in both guide-star data model schemas.
Fixes #3312
> Guide star keyword updates

- docs/jwst/associations/overview.rst
This PR adds a few more links to the association overview page that I think I would have found useful.
They're all to things that are linked elsewhere on the page, but channeling "astronomer who just wants to read the minimum possible", I think these links are important in these specific places.
> Add a few more useful links to the association page

- jwst/assign_wcs/miri.py
- jwst/transforms/jwextension.py
- jwst/transforms/models.py
- jwst/transforms/tags/__init__.py
- jwst/transforms/tags/jwst_models.py
This PR contains modifications to the MIRI LRS distortion model to enable forward/backwards transforms and incorporates subarray bounding boxes in the transform.  Additional changes have been made to the MIRI imaging comments to indicate that the CDP-7 delivery no longer uses the XAN/YAN coordinate frame.
Updated MIRI LRS and imager distortion reference files are being delivered to CRDS for CDP-7 as well, but the new files should not be required for the code updated here to work.
Resolves #2951, #2825
> Update MIRI LRS distortion model for CDP-7

- .gitignore
- docs/conf.py
- docs/jwst/transforms/index.rst
- jwst/transforms/schemas/stsci.edu/jwst_pipeline/grating_equation-0.7.0.yaml
- jwst/transforms/schemas/stsci.edu/jwst_pipeline/gwa_to_slit-0.7.0.yaml
- jwst/transforms/schemas/stsci.edu/jwst_pipeline/logical-0.7.0.yaml
- jwst/transforms/schemas/stsci.edu/jwst_pipeline/lrs_wavelength-0.7.0.yaml
- jwst/transforms/schemas/stsci.edu/jwst_pipeline/miri_ab2slice-0.7.0.yaml
- jwst/transforms/schemas/stsci.edu/jwst_pipeline/nircam_grism_dispersion-0.7.0.yaml
- jwst/transforms/schemas/stsci.edu/jwst_pipeline/niriss_grism_dispersion-0.7.0.yaml
- jwst/transforms/schemas/stsci.edu/jwst_pipeline/niriss_soss-0.7.0.yaml
- jwst/transforms/schemas/stsci.edu/jwst_pipeline/refraction_index_from_prism-0.7.0.yaml
- jwst/transforms/schemas/stsci.edu/jwst_pipeline/rotation_sequence-0.7.0.yaml
- jwst/transforms/schemas/stsci.edu/jwst_pipeline/slit_to_msa-0.7.0.yaml
- jwst/transforms/schemas/stsci.edu/jwst_pipeline/snell-0.7.0.yaml
- jwst/transforms/schemas/stsci.edu/jwst_pipeline/tpcorr-0.7.0.yaml
- jwst/transforms/schemas/stsci.edu/jwst_pipeline/v23tosky-0.7.0.yaml
- setup.py
This PR adds a section to the `transforms` submodule documentation that links to new documentation for each of the transform schemas. The schema documentation is automatically generated using the [sphinx-asdf](https://github.com/spacetelescope/sphinx-asdf) plugin.
> Use sphinx-asdf to automatically generate schema documentation for transforms

- CHANGES.rst
- docs/jwst/pathloss/description.rst
- jwst/datamodels/schemas/image.schema.yaml
- jwst/datamodels/schemas/pathlosscorr.schema.yaml
- jwst/datamodels/tests/test_models.py
- jwst/pathloss/pathloss.py
- jwst/pathloss/pathloss_step.py
- jwst/tests/base_classes.py
- jwst/tests_nightly/general/niriss/test_niriss_steps.py
- jwst/tests_nightly/general/nirspec/test_spec2pipelines.py
- Applies the computed pathloss correction to the `data, err, var_poisson` members of the datamodel
- Applies the `pathloss_pointsource2D` array if `SRCTYPE == "POINT"`, `pathloss_uniformsource2D` if `SRCTYPE == "EXTENDED"` or `None`.
- No longer attaches the various `pathloss_xxx` extensions.  Only a single `pathloss` extension representing the 2D correction applied.
1) ~~For NIRSpec IFU, is the distinction between point source and uniform source meaningful?  I.e. for a point source in the field, some slits will contain it and some won't.  Is this taken care of in the pathloss reffile?~~ This is taken care of in the reffile.
2) ~~It seems like the NIRISS SOSS (non-TSO) version of this step only computes a point source correction.  Should we be checking to make sure SRCTYPE == "POINT" …
> Apply pathloss correction to NIRSpec and NIRISS SOSS data

- jwst/transforms/models.py
This allows to pass `with_bounding_box` to the model.
> add **kwargs to v23tosky model

- conftest.py
- setup.cfg
Currently, our builds against the dev version of `asdf` are failing because the schema tester has become an `entry_points` plugin.  This fixes the `jwst` package so it can get the plugin the old or new way.
> Fix asdf_schema_tester for dev version of asdf

- jwst/barshadow/bar_shadow.py
- jwst/pathloss/pathloss.py
Updated the ``pathloss`` and ``barshadow`` steps to apply their corrections to the readnoise variance arrays, same as Poisson variance.
Fixes #3365.
> Apply corrections to readnoise variance

- jwst/master_background/expand_to_2d.py
- jwst/tests_nightly/general/miri/test_miri_steps.py
- jwst/tests_nightly/general/miri/test_miri_steps_single.py
- jwst/tests_nightly/general/nirspec/test_nirspec_steps_single.py
Fixes a bug found in a regression test (see traceback below).  The DQ indices being flagged were those in a single IFU slice, but the indices need to be in the full detector frame.  So we use the slice boolean mask to pick out the indices in `x` and `y`, which are in full-frame coordinates.
Also, some test cleanup:
- shorten test function names so that the output dirs don't overwrite each other on Artifactory
- make sure that truth files are being pulled to the `truth/` dir in `_jail`.
https://plwishmaster.stsci.edu:8081/job/RT/job/JWST/192/testReport/junit/jwst.tests_nightly.general.nirspec.test_nirspec_steps_single/TestNIRSpecMasterBackground_IFU/_stable_deps__test_nirspec_masterbackground_ifu_user1d/
```
self = <general.nirspec.test_nirspec_steps_single.TestNIRSpecMasterBackground_IFU …
```
> Fix DQ flagging in master background for NIRSpec IFU

- CHANGES.rst
- jwst/lib/set_telescope_pointing.py
- jwst/lib/tests/test_set_telescope_pointing.py
Updated ``set_telescope_pointing`` to convert the input FSM correction values from units of arcsec to radians. Added the switch ``fsmcorr_units`` to allow for the possibility of processing older data that still had these values in radians to begin with.
Fixes #3300.
> Update set_telescope_pointing to convert FSMCORR units

- jwst/tests_nightly/general/miri/test_miri_steps_single.py
The test
```
jwst.tests_nightly.general.miri.test_miri_steps_single.TestMIRIMasterBackgroundLRS.test_miri_masterbackground_lrs_user1d
```
has been failing since #3326 was merged.
This PR removes the part of the test that compares the `extract1d` outputs, as the DQ array affects the wavelengths compared.
Related to #3369.  See comments in that PR for more detail.
> Simplify MIRI LRS master background regression test

- CHANGES.rst
- docs/jwst/extract_1d/arguments.rst
- jwst/extract_1d/extract.py
- jwst/extract_1d/extract_1d_step.py
- jwst/extract_1d/ifu.py
The right ascension and declination of the target are now gotten from keywords TARG_RA and TARG_DEC, and the inverse WCS is used to find the location of that celestial point in the input image.  For a 2-D input image (or a stack of such images), that point is assumed to be the location of the spectrum in the cross-dispersion direction.  For an IFU cube, the forward WCS is evaluated at each pixel in one plane to compute the right ascension and declination (and wavelength), and the location of the target is taken to be the pixel with celestial coordinates that are closest to TARG_RA and TARG_DEC.  The extraction location will actually be shifted to the computed point, except for extended sources, WFSS modes, or (currently) NIRSpec fixed-slit or MOS.
For IFU, the computation of the areas of …
> Use target coordinates to shift extraction location

- docs/jwst/photom/main.rst
- jwst/photom/photom.py
- jwst/tests_nightly/general/nirspec/test_nirspec_steps_single.py
Fix a couple ``photom`` bugs that were in #3359, and update the step docs to indicate that the step now relies on having WCS (wavelength) info available, hence ``assign_wcs`` is a prerequisite.
Also updated one of the NRS MOS ``master_background`` regression tests to only check truth file, with no on-the-fly processing and comparison.
> Fix bugs in updated photom

- jwst/tests_nightly/general/niriss/test_niriss_steps_single.py
One of the NIRISS SOSS regression tests of the ``photom`` step was written before the team started including spectral order number in the NIRISS photom ref files, so it was using a hand-crafted ref file as an override. That was a long time ago. Updated photom ref files now exist, which work just fine with the dataset in the test, so I removed the use of the ref file override.
> Fix failing NIRISS SOSS reg test module

- .travis.yml
- Jenkinsfile
- JenkinsfileRT
Bump up CRDS_CONTEXT from 501 to 502 in all test setup files, now that the new MIRI ref files in 501 have been completely verified. Time to test the next set of new ref files.
> Bump CRDS context to 502 for all tests

- .travis.yml
- CHANGES.rst
- Jenkinsfile
- JenkinsfileRT
- jwst/master_background/expand_to_2d.py
- jwst/photom/photom.py
Update the ``photom`` step to use the spectral order number when calling the ``get_wavelengths`` function for NIRISS SOSS mode, because the SOSS mode WCS is order-dependent. Also update the ``get_wavelengths`` function to make use of the ``order`` parameter when building the WCS transform for SOSS exposures.
Addresses some of the photom-related issues in #3301.
> Update photom to handle NIRISS SOSS

- CHANGES.rst
- jwst/datamodels/schemas/cube.schema.yaml
- jwst/datamodels/schemas/ifuimage.schema.yaml
- jwst/datamodels/schemas/image.schema.yaml
- jwst/datamodels/schemas/slitdata.schema.yaml
- jwst/datamodels/schemas/variance.schema.yaml
- jwst/flatfield/flat_field.py
- jwst/flatfield/flat_field_step.py
This propagates flat field reference file uncertainties to the science data via VAR_FLAT and ERR in `FlatFieldStep` for all modes except NIRSpec spectral modes.
Algorithm is below:
- ur = raw slope
- ff = flat field
- s = slope = ur / ff
- sigma_s^2 = (s^2/ur^2)sigma_r^2 + (s^2/ur^2)sigma_p^2 + (s^2/ff^2)sigma_ff^2
- Hence, the four uncertainties tracked are:
- (s^2/ur^2)sigma_r^2 = sigma_r^2/ff^2
- (s^2/ur^2)sigma_p^2 = sigma_p^2/ff^2
- (s^2/ff^2)sigma_ff^2
- sigma_s^2
Resolves #3307.
>  Propagate flatfield uncertainties into science error and variance arrays

- CHANGES.rst
- jwst/tests/base_classes.py
- jwst/tests_nightly/general/miri/test_miri_steps_single.py
Added four regression tests for masterbackground subtractions.
1. mrs nodded
2. mrs dedicated background
3. lrs nodded
4. lrs dedicated background
These test are done. I might need to reproduce the data once all the changes to extract1d have been finished for the nodded and dedicated background cases. Then I will put the data onto byesalad.
@jdavies-st I did not remove the auto_toggle_docopy because I really do not understand what it is 
trying to do when you run the tests locally. It seems it should always fail. Instead I changed the way
get_data works. Please look at the logical for docopy. I think it is what we want - do exactly what
the user wants and if nothing is given (docopy = None) then default back to the way it worked before
and use self.docopy.
> Master background regression tests for MIRI MRS and LRS

- jwst/transforms/models.py
- jwst/transforms/tpcorr.py
Instead of indexing model.Parameter index the value of the parameter.
This removes ambiguity in the current code where indexing is of a Parameter instance returns one parameter in a model set. With this changes the code works with current astropy.modeling master and the future refactored modeling.
In addition the prepare_inputs/outputs calls were removed as they are not necessary in this case.
A bug in models.V23ToSky was fixed.
Similar to spacetelescope/tweakwcs#85
> change indexing of model parameters

- jwst/flatfield/flat_field.py
Follow-on to #3384 to exclude `GuiderCalModel` from error propogation from `FlatFieldStep`.
The guider pipeline currently does not do anything with errors.  The `err` attribute is not populated and `var_rnoise` and `var_poisson` don't exist in the schema for `GuiderCalModel`.  So there's no way to properly add in the variance due to the flat field.  So we skip it for now.
Tested against the 3 guider pipeline regression tests.  And they all will pass with this PR.
> Exclude GuiderCalModel from flatfield error propogation

- .travis.yml
- Jenkinsfile
- JenkinsfileRT
Increment CRDS context for CI and regression tests from 504 to 508. 508 is the current default, although new ref files have been submitted in even later contexts.
> Bump CRDS context for tests to 508

- CHANGES.rst
- jwst/master_background/expand_to_2d.py
- jwst/photom/photom.py
A new `exp_type` argument was added to get_wavelengths in master_background/expand_to_2d.py, and -- only for WFSS data -- that function calls the wcs function within a loop over pixels.
Closes #3301.
> Loop over pixels in expand_to_2d.get_wavelengths

- Jenkinsfile
- JenkinsfileRT
This is because of
https://github.com/pypa/pip/issues/6434
Closes #3409
> Specify pip<19.1 to avoid PEP 517 breakage

- jwst/background/tests/test_background.py
Unit test for calspec2 background subtraction - testing logic when the data is NISPEC. The GWA x,y values have to be the same between science image and background.
I was not sure if I had to run assign_wcs on the data. I had this in the code at first but when I took
it out it did not seem to matter that is was not run. If I need it for some reason  let me know. If I don't need it I can probably take out all the setting of the wcs values. 
I used the _jail  for the background image since the input to background step is a list of background
filenames - at least I think that is correct.
> unit test for background

- CHANGES.rst
- jwst/combine_1d/combine1d.py
- jwst/combine_1d/combine_1d_step.py
- jwst/datamodels/schemas/combinedspec.schema.yaml
- jwst/datamodels/schemas/multispec.schema.yaml
- jwst/datamodels/schemas/spec.schema.yaml
- jwst/extract_1d/extract.py
- jwst/extract_1d/extract_1d_step.py
- jwst/extract_1d/ifu.py
- jwst/extract_1d/tests/test_ifu_image_ref.py
- jwst/extract_1d/util.py
- jwst/master_background/expand_to_2d.py
- jwst/master_background/master_background_step.py
- jwst/master_background/tests/test_expand_to_2d.py
- jwst/pipeline/combine_1d.cfg
The `photom` step now applies the photometric correction, and `extract_1d` and combine_1d have been updated to accept an input file in units of surface brightness.  `extract_1d` no longer checks for a PHOTOM extension, and the output table has new columns SURF_BRIGHT and SB_ERROR rather than NET and NERROR.  In addition, the BACKGOUND column has been divided by NPIXELS, so the units will be surface brightness.  Previously, the BACKGROUND column contained the values that were subtracted from the gross count rate to get the net count rate.  The `ref_file` attribute has been removed from the step class, `Extract1dStep`; `ref_file` is now a local variable.
The `background` parameter has been removed from the `combine_1d` step.  This is no longer needed, since `extract_1d` divides the …
> Modify extract_1d and combine_1d for change in units

- jwst/associations/exceptions.py
- jwst/extract_1d/extract.py
Exceptions in Python 3 no longer have a `self.message` attribute.  Use `self.args` instead.
> Remove python 2 exception .message references

- CHANGES.rst
- docs/jwst/barshadow/description.rst
- docs/jwst/photom/main.rst
- jwst/barshadow/bar_shadow.py
- jwst/pathloss/pathloss.py
- jwst/photom/photom.py
The correction factors (squared) are applied to the VAR_POISSON and VAR_RNOISE variances in the `barshadow`, `pathloss`, and `photom` steps.  These correction factors (also squared) are now also applied to the VAR_FLAT variance array.
Note that this PR does not close issue #3414, because there are other steps that can follow `flat_field`.
> Apply barshadow, pathloss, and photom correction to VAR_FLAT

- jwst/gain_scale/tests/test_gain_scale.py
Add unit tests to make sure the gain assigned to the header/meta extensions of the data models are applied to the data and error arrays properly.
The only portion of the code we couldn't reach with a test are when the reference files are required if the gain isn't found in the data model.
Closes #3245.
> Add gain_scale unit tests

- CHANGES.rst
- jwst/extract_1d/extract.py
For some types of input data, `extract_1d` sets the keywords that describe the units for output columns FLUX and ERROR to "mJy", but the units are actually "Jy".  Keywords TUNIT2 and TUNIT3 have been corrected.
Closes #3445.
> Change the strings that describe the units for flux.

- CHANGES.rst
- jwst/master_background/master_background_step.py
- jwst/master_background/tests/test_master_background.py
The `spec_table` with the background copied into the flux column was not properly passed along to the `combine_1d` function.
> Fix bug in copy_background_to_flux for master background

- jwst/source_catalog/source_catalog.py
- jwst/source_catalog/source_catalog_step.py
This PR updates the `source_catalog` step to handle non-detections for both the current and upcoming release of `photutils`.
> Update source_catalog step for non-detections

- CHANGES.rst
- docs/jwst/master_background/description.rst
- docs/jwst/master_background/reference_files.rst
- jwst/master_background/create_master_bkg.py
- jwst/master_background/expand_to_2d.py
- jwst/master_background/master_background_step.py
- jwst/master_background/tests/test_create_master_bkg.py
- jwst/master_background/tests/test_expand_to_2d.py
- jwst/master_background/tests/test_master_background.py
The `master_background` step now uses the SURF_BRIGHT column instead of the FLUX column of the 1-D background spectrum.  The `create_background` function in create_master_bkg.py now populates the SURF_BRIGHT column instead of the FLUX column.
> Use the surf_bright column in master_background

- jwst/tweakreg/tweakreg_catalog.py
- setup.py
This PR adds masks for non-imaging regions in the `tweakreg` and `source_catalog` steps based on the `NON_SCIENCE` DQ flag (e.g. MIRI images).
I updated the `photutils` version dependency because the `photutils.DAOStarFinder` `mask` keyword requires `photutils >= 0.6`.
Closes #2062 and #3287.
> Mask non-imaging regions in tweakreg and source_catalog

- jwst/tests_nightly/general/nirspec/test_calwebb_spec2_nrs_msa.py
- jwst/tests_nightly/general/nirspec/test_pipelines.py
Fixes the assert test in a regression test so that the text that's being compared is spelled correctly (and matches the expected output).
> Fix typo in NRS MSA missing test

- CHANGES.rst
- docs/jwst/photom/main.rst
- jwst/photom/photom.py
The photom step has been updated to handle pixels in spectroscopic mode exposures that have wavelengths outside the range of the wavelengths of the calibration reference data. Previously the calibration value for such pixels had been set to 1, by the numpy interpolation routine that's used to interpolate the 1-D reference data into the 2-D space of the exposure. That's been changed to set the conversion values to NaN, and the locations of the NaN's are given a calibration value of zero, so that the pixels end up with a value of zero in the output. That set of pixels is also flagged with DO_NOT_USE in the DQ array. Updated the docs to add this info.
Also fixed a minor bug in the ``save_area_info`` function where it computes the difference between the nominal pixel area values given in the …
> Update photom to handle pixels with no flux cal

- CHANGES.rst
- jwst/model_blender/blendmeta.py
This bug came up when testing #3461.
It is possible to have attributes in a JWST datamodel ASDF tree that are not in the current schema.  Perhaps these attributes have been removed from the schema or the datamodel was created from a schema that referenced our schema and added more attributes.
If this is the case, then `blendmodels` will fail.  This fix allows it to just ignore items that are not the in schema.
If items in the tree are not in the schema, then they won't have a blend rule anyway.
> Allow blendmodels to ignore attributes in asdf tree not in schema

- CHANGES.rst
- jwst/photom/photom.py
The updates in #3475 had a couple of flaws. First, image mode exposures failed, because the if-block containing the setting of ``no_cal`` does not get entered, so that it was undefined when used later. Second, the use of ``no_cal`` in setting flags in the DQ array only worked properly when the DQ array is 2-D (same shape as ``no_cal``), which means it crashed on exposures that use ``CubeModel`` where the DQ array is 3-D. The updates here address both of those problems. If any reviewers know of a more elegant (pythonic) way to do this, please make suggestions.
> Fix bug in latest photom update

- CHANGES.rst
- jwst/assign_wcs/nirspec.py
Resolves #2957 
It's been a while since this ticket was created and I lost track of the test data.
It would be good to get another NRS2 dataset and the corresponding ESA traces to test this fix.
> fix -1 px off for NRS2 coordinates

- jwst/tests_nightly/general/nirspec/test_nirspec_steps_single.py
One of the regression tests for the ``master_background`` step was using the ``net`` column of x1d files. It's been updated to use the ``flux`` column, now that ``extract_1d`` no longer produces a ``net`` column.
> Update masterbg test to use flux column

- CHANGES.rst
- docs/jwst/combine_1d/arguments.rst
- docs/jwst/combine_1d/description.rst
- jwst/combine_1d/combine1d.py
- jwst/combine_1d/tests/test_count_input.py
This PR adds a few unit tests for `combine_1d`.  It also addresses some comments made regarding PR #3412.  The tests are for a simple case.  At some point the algorithm for computing output wavelengths should be improved, and some more realistic unit tests should be written.
Closes #3215.
> Add unit tests for combine_1d

- jwst/jump/tests/test_twopoint_difference.py
- Reduce size of arrays in test fixture from `(2048, 2048)` to `(204, 204)`.  This speeds up the tests by factor of ~75; from taking 53 seconds to 0.6 seconds on my computer.
- Remove `print()` statements in tests
> Speed up twopoint_difference unit tests in jump step

- CHANGES.rst
- jwst/extract_1d/extract.py
The lower limit for an extraction region was negative, due to a nod/dither offset, and this is now reset to zero.
Closes #3496.
> Truncate negative index to zero

- .gitignore
- CHANGES.rst
- jwst/jump/jump.py
- jwst/jump/jump_step.py
- jwst/jump/tests/test_detect_jumps.py
- jwst/jump/tests/test_jump_step.py
- jwst/jump/tests/test_twopoint_difference.py
- jwst/jump/twopoint_difference.py
- jwst/pipeline/jump.cfg
- setup.py
This PR makes a few changes to @mwregan2's very nice #3021.
- Remove `maximum_cores='one'` and make `maximum_cores=None` as the default behavior that SDP expects.  I.e. if `maximum_cores` is not set, no multiprocessing pool is created. 
- Use smaller in the unit test fixtures (instead of full frame) to reduce memory usage and runtime, as is standard for a number of the other pipeline step unit tests where appropriate.  Runtime is reduced because of the `assert` statements in a `for` loop and scales by the number of pixels in the array.
- Parametrize the tests instead of the test fixtures for the multiprocessing tests.  Makes it clearer what is going on.
- Change test fixtures to use `GainModel` and `ReadnoiseModel` instead of custom FITS versions of these to reduce future maintenance.
- …
> Add multi-processing option to jump step

- CHANGES.rst
- jwst/datamodels/photom.py
- jwst/datamodels/schemas/mirimg_photom.schema.yaml
Add the table column "relresperror" to the ``MiriImgPhotomModel`` schema, to accommodate the new column contained in the CDP-7 version of the MIRI Imager photom reference file.
Fixes #3511.
> Update MIRI Imager photom data model

- CHANGES.rst
- jwst/pipeline/ami_analyze.cfg
Update the ami_analyze.cfg file to set the default value of ``rotation`` to zero, which matches the default value in the step "spec" block.
Fixes #3510.
> Update ami_analyze rotation param default

- CHANGES.rst
- jwst/datamodels/model_base.py
- jwst/extern/configobj/validate.py
- jwst/stpipe/config_parser.py
- jwst/stpipe/step.py
- jwst/stpipe/tests/test_model_override.py
- jwst/stpipe/tests/test_overrides.py
Added an stpipe configuration validator function which accepts a string or a datamodel.
Used new validator to enable reference file overrides to accept datamodels.
Added tests.
This PR  is expected enable the usage of DataModels for most steps.   This PR is expected not to affect classic use of filepath strings as overrides.
> JP-345 support data models as reference file overrides

- CHANGES.rst
- jwst/extract_1d/extract.py
- jwst/extract_2d/grisms.py
- jwst/pipeline/calwebb_spec3.py
Change the calwebb_spec3 pipeline to allow processing of WFSS modes.
Also fixed a bug in extract_1d where the shape of the input data was not passed correctly to the extraction code in the case of a single 2D slit.
This was tested on one file from the regression tests - NIS-WFSS. More testing necessary.
Resolves #3415.
> spec3 pipeline for WFSS modes

- jwst/extract_1d/ifu.py
- jwst/outlier_detection/outlier_detection_scaled.py
- jwst/tso_photometry/tso_photometry.py
In `photutils 0.6` the aperture objects have an `area()` method, but in `photutils 0.7` this was changed to an attribute.  This PR updates the `extract_1d`, `tso_photometry`, and `outlier_detection` steps to work with both `photutils` 0.6 and >= 0.7 (including 0.7dev) versions.
Fixes https://github.com/spacetelescope/jwst/issues/3534.
> Update aperture area for photutils API change

- CHANGES.rst
- jwst/flatfield/flat_field.py
- jwst/flatfield/tests/test_flatfield.py
- Add function `nirspec_fs_msa()` to handle the work done originally by `do_nirspec_flat_field()`.  Now `do_nirspec_flat_field()` calls one of 3 functions:
- `nirspec_brightobj()`
- `nirspec_ifu()`
- `nirspec_fs_msa()`
- Propogate error arrays from the FFLAT, SFLAT and DFLAT reffiles into the `err` and `var_flat` arrays in the science data.
Continues work started on #3493.
Resolves #3460.
> Compute var_flat from fflat, sflat and dflat for NIRSpec modes

- CHANGES.rst
- jwst/extract_1d/extract.py
The `master_background/expand_to_2d.get_wavelengths` function is now used to get the 2-D array of wavelengths from the input file, instead of explicitly checking for the existence of the wavelength attribute (an extension in the input file), and evaluating the WCS function if the attribute does not exist or is not populated.
The replace_bad_values function has been modified.  Instead of setting the science data to a fill value (zero) for pixels where the data value was NaN or the data quality flag included DO_NOT_USE, the science data are now set to NaN wherever the wavelength is NaN or the DQ flag includes DO_NOT_USE.
Closes #3223.
> Don't use pixels with wavelength = NaN

- CHANGES.rst
- jwst/pipeline/calwebb_image2.py
This fixes the issue where 3D `_rateints` products that had normal imaging EXP_TYPES were being sent to `resample` in `calwebb_image2`.
Resolves #2899.
> JP-457 Prevent calwebb_image2 from sending 3D data to resample

- jwst/datamodels/schemas/ramp.schema.yaml
- jwst/datamodels/util.py
Add REFOUT attribute to RampModel so that MIRI data can be opened as a RampModel and retain the REFOUT data.  Change datamodels.open so that data with a REFOUT extension are opened as a RampModel instead of a MIRIRampModel.
MIRIRampModel is still available.
> MIRI data to use RampModel instead of MIRIRampModel

- jwst/extract_1d/extract.py
- jwst/lib/wcs_utils.py
- jwst/master_background/expand_to_2d.py
- jwst/photom/photom.py
Resolves #3553
This PR copies the `get_wavelength` function verbatim to `lib/wcs_utils.py` in order to fix an import error and allow tests to run. It may need to be cleaned and generalized in a later PR.
> move get_wavelengths to lib

- jwst/steps.py
- jwst/tests/test_infrastructure.py
Make sure error in #3553 does not happen again.  Putting the check that packages are importable in this repo, not just in the conda package recipe.
Companion to the actual fix #3556.
Also, since `steps.py` is just used as in the conda recipe as a smoke test, and since we are now doing it here as part of our unit tests, can we remove the module and that line in the conda recipe?
https://github.com/astroconda/astroconda-dev/blob/aaad924953d4e608afda22cba7b90f6e6de32a46/jwst/meta.yaml#L76
I would feel more comfortable doing the smoke test in the package instead of in the conda recipe.  @jhunkeler 
Also, it seems the only thing that imports `steps.py` is `cal_ver_steps.py`.  But it seems to do nothing with it (but has a `flake8` override).  And maybe we don't need `cal_ver_steps.py` either? …
> Add test to make sure submodules are importable

- CHANGES.rst
- jwst/skymatch/skyimage.py
This PR essentially re-implements enhancement in `stsci.skypac` in https://github.com/spacetelescope/stsci.skypac/pull/49
> Fix crashes in skymatch when some footprints almost entirely overlap

- jwst/flatfield/flat_field.py
Fixes bug introduced by #3538.  The fore-optics flat FFLAT slow-variation flat error array (from the per-shutter 1D as-a-function-of-wavelength flat) is now interpolated onto the correct grid.
Also, the outside-of-bounds interpolation default value is changed from 1 to 0.
Fixes #3552.
> JP-744 Fix bug NIRSpec fore-optics flat interpolation

- CHANGES.rst
- jwst/assign_wcs/niriss.py
- jwst/pipeline/calwebb_spec2.py
Updated the ``calwebb_spec2`` flow so that errors in ``assign_wcs`` are checked and acted on before calling the ``background`` step, because for WFSS data the ``background`` step needs WCS info (which won't be there if ``assign_wcs`` aborted).
Also added a check for the presence of the FWCPOS keyword in the NIRISS WFSS processing and raise an error if it isn't there.
Fixes #3558
> Fix assign_wcs error handling in calspec2

- CHANGES.rst
- jwst/ami/ami_analyze_step.py
- jwst/ami/tests/test_ami_interface.py
Resolves #2138.
It would be nice to have a more generalized Error class for `stpipe` steps and pipelines, but will require going through step-by-step and pipeline-by-pipeline and coming up with a consistent way of emitting errors by steps and handling them (if possible) in pipelines.  I will file an issue for this.
> JP-326 Improve error message for AMI _calints input

- jwst/tests_nightly/general/miri/test_miri_steps_single.py
The data array in the new `regions` reference file is a 3D array representing pixel maps for different throughput threshold. Which plane to use is hard-coded at the moment in assign_wcs. This PR modifies the WCS test to use the same plane.
> fix MRS WCS test

- CHANGES.rst
- jwst/datamodels/multiexposure.py
- jwst/datamodels/schemas/multiexposure.schema.yaml
Updated the MultiExposure model to include all possible Slit arrays, not just SCI, DQ, and ERR. The lack of arrays like WAVELENGTH in the output was causing problems in downstream steps in ``calwebb_spec3``.
Fixes #3521.
> Update MultiExposure model to include all slit arrays

- CHANGES.rst
- docs/jwst/model_blender/blender_rules.rst
- jwst/datamodels/schemas/core.schema.yaml
- jwst/model_blender/blendrules.py
New model_blender rules have been added for handling dates and times, with initial testing done using:
`strun calwebb_image3.cfg jw87600-o004_20190518t040438_image3_001_asn.json
`
This addresses #3548.
> JP-740 Add datetime rules

- jwst/pipeline/calwebb_coron3.py
- jwst/stpipe/pipeline.py
- jwst/stpipe/step.py
Some members of a coron3 association should not be processed / prefetched.
Modified step.py to expose a `.prefetch()` method which is called just prior to
`.process()` IF `.prefetch_references == True`.   This is the default.
If `.prefetch_references == False`,  `.prefetch()` can still be called explicitly
within `.process()` if needed,  as is done here for `calwebb_coron3`.
To improve customization, changed `Pipeline.reference_file_types`, once defined
in __init__() as an attribute, into a `@property` which is deferred until needed.
Resolves #3549.
> JP-741 Customize reffile prefetch

- jwst/jump/jump.py
- setup.py
This package dependency was added with `jump` multiprocessing support, but is not needed.  Use the built-in functionality of `multiprocessing` in the python core library instead.
This is an issue as `psutil` does not `pip install` properly on older versions of linux.  Tests fail because of a non-existing shared library:
```
E   ImportError: /lib64/libc.so.6: version `GLIBC_2.13' not found (required by /home/jdavies/miniconda3/envs/testtest/lib/python3.6/site-packages/psutil/_psutil_linux.cpython-36m-x86_64-linux-gnu.so)
```
> Remove psutil dependency.  Use multiprocessing.cpu_count() instead.

- CHANGES.rst
- jwst/datamodels/schemas/core.schema.yaml
Removed the enum list in the core schema for the SUBPXPAT keyword. Many new values have been implemented in the front-ends recently and are still in flux. Hence the safest way to achieve validation for now is to have any enum list at all.
This addresses https://jira.stsci.edu/browse/JP-772
Resolves #3617.
> Remove enum list for SUBPXPAT keyword

- CHANGES.rst
- jwst/extract_2d/extract_2d_step.py
- jwst/extract_2d/nirspec.py
- jwst/pipeline/calwebb_spec2.py
Resolves #3422 
Tested on the failing exposures.
`NRS_LAMP` exposures are supposed to be processed like NRS Fixed Slits. This means the zero-point wavelength correction can be applied as well using the `wavecorr` reference file for FS. Currently it is skipped because `NRS_LAMP` is not in the `rmap` for `wavecorr`.
> JP-665 - fix spec2 processing of NRS_LAMP

- jwst/assign_wcs/miri.py
- jwst/tests_nightly/general/miri/test_miri_steps_single.py
Continued testing with simulated data and the new CDP-7 photometric reference files indicates that an 80% throughput threshold gives better performance for mosaiced data than the 50% threshold.  This pull request changes that default.
> Change MRS throughput threshold for assign_wcs

- jwst/assign_wcs/util.py
Pulled out finding the footprint for spectral data from setting S_REGION.
Now a separate routine finds the footprint 
the various modules to updating the s_region are not changed. They just now call the find_footprint_spectral.
> pulled finding footprint from setting s_region

- jwst/datamodels/schemas/container.schema.yaml
- jwst/datamodels/schemas/extract1dimage.schema.yaml
- jwst/datamodels/schemas/guider_cal.schema.yaml
- jwst/datamodels/schemas/guider_raw.schema.yaml
- jwst/datamodels/schemas/lev3_prod.schema.yaml
- jwst/datamodels/schemas/multiextract1d.schema.yaml
This removes trailing spaces and fixes some indentation inconsistencies in the schema files.  The schema editor produces YAML without these quirks, so fixing them in a separate PR will make the diff of schema changes due to the keyword dictionary sync a little cleaner.
> Remove trailing spaces and fix indentation issues in schema files

- jwst/tests_nightly/general/nirspec/test_nirspec_fs_spec3.py
The expected product name is changed because it's based now on source_id instead of slit name.
> fix exp_to_source test

- CHANGES.rst
- jwst/outlier_detection/outlier_detection_scaled_step.py
- jwst/outlier_detection/outlier_detection_stack_step.py
- jwst/outlier_detection/outlier_detection_step.py
- jwst/pipeline/outlier_detection.cfg
- jwst/pipeline/outlier_detection_scaled.cfg
- jwst/pipeline/outlier_detection_stack.cfg
- jwst/pipeline/outlier_detection_tso.cfg
- jwst/pipeline/resample.cfg
- jwst/pipeline/resample_spec.cfg
- jwst/resample/resample_step.py
Pixels with just either of these flags set won't be excluded from weight calculation.
> Changed good_bits from 4 to 6 to exclude SATURATION and JUMP_DET flags (JP-765)

- docs/jwst/model_blender/blender_rules.rst
- jwst/datamodels/schemas/core.schema.yaml
- jwst/model_blender/blendrules.py
- jwst/model_blender/tests/test_blend.py
https://jira.stsci.edu/browse/JP-778
This PR introduces two additional blender rules, `mindatetime` and `maxdatetime`, and has all of the date/time rules return strings in the appropriate format instead of astropy Time objects.
This may be controversial, but I'm also dropping support for the asdf time schema in meta.date and meta.observation.date.  As far as I know there is only one permissible format, so I'm not sure why the schema needs to allow everything in asdf/time/time-1.0.0.  This is relevant because the model blender sees that meta.observation.date can be an object with its own nested fields, so it ignores the blend_* settings (like it does with any object).
Anyway, with these changes the test_ami_pipeline regression test no longer crashes -- it still doesn't pass, but that …
> Update model blender to return strings instead of astropy Time objects

- jwst/assign_wcs/nirspec.py
- jwst/extract_2d/nirspec.py
This fixes an issue discovered in testing #3643 - the source_id of a fixed slit is lost in extract_2d and reset to the default value of 0.
> set source_id correctly in extract_2d

- jwst/flatfield/tests/test_flatfield.py
This PR is a part of the INS migration of unit tests to the pipeline. This test was a request by the NIRSPEC team to check the completion of the flat field step. I added an assertion to an already existing unit test that just confirms the keyword is value `COMPLETE`. If it's necessary, I can make a separate test.
Resolves #3532.
> Confirm Completion Keyword Assignment for Flat Field Correction

- jwst/pipeline/calwebb_tso3.py
If a photometric catalog cannot be created a log message is printed and cleanly finishes calwebb_tso3
> fix for JP-786

- CHANGES.rst
- jwst/extract_1d/extract.py
- jwst/extract_1d/extract_1d_step.py
`extract_1d` now treats each `SlitModel` from an input `SourceModelContainer` as a one-element list of `SlitModels`.  These are then processed by the section of extract.py as for `MultiSlitModels`.
Note that this PR does not close the issue, #3639, because currently `combine_1d` still cannot process the output of `extract_1d`. This problem appears to be related to incorrect handling of FITS bintable columns of type `uint32`.
> JP-785 Modify extract_1d to correctly handle SourceModelContainer

- jwst/associations/main.py
The `asn_generator` option `--no-merge` is the default, but the deprecation message appeared whether the option was specified or not. This fixes the message to only appear if the option is used.
> Fix no-merge deprecation message to not appear on every run

- CHANGES.rst
- jwst/combine_1d/combine1d.py
The DQ column in the input table is now (temporarily) ignored, and a zero-filled array of the correct data type is used instead.
Closes #3665.
> JP-795 Temporarily overwrite DQ column

- CHANGES.rst
- jwst/datamodels/schemas/core.schema.yaml
- jwst/datamodels/schemas/keyword_channel.schema.yaml
- jwst/datamodels/schemas/keyword_pband.schema.yaml
- jwst/datamodels/schemas/keyword_pchannel.schema.yaml
- jwst/datamodels/schemas/keyword_pfilter.schema.yaml
- jwst/datamodels/schemas/lev3_prod.schema.yaml
- jwst/datamodels/schemas/multispec.schema.yaml
Resolves #3624 
This updates the datamodels schema files with new keywords that appeared in the 2019-06-11 dump of the dev keyword dictionary.  I didn't change any titles, but left notes showing where they need an update.  I have some questions about what I did but I'll comment directly on the relevant lines.
> Synchronize datamodels core schema with JWST Keyword Dictionary

- CHANGES.rst
- jwst/associations/generate.py
- jwst/associations/lib/rules_level2b.py
This ensures that associations created after the background
but to which the background should belong becomes a member.
WIP #3434/JP-675
> Reprocess all backgrounds for Level2 associations

- jwst/tests_nightly/general/nircam/test_coron3_1.py
- jwst/tests_nightly/general/nircam/test_nrc_image3_1.py
We need this for the regression tests to pass.  Merge when approved.
> Ignore keywords/cols for fitsdiff of blender table

- jwst/associations/lib/rules_level2b.py
Revert an over-strict test on WFSC associations.
> Loosen the WFSC constraints and only exclude NIS_EXTCAL

- jwst/associations/lib/rules_level2b.py
As per new information in JP-473/JP-282, the image processing of NRS_LAMP should be removed. This removes the association rule that would have setup for NRS_LAMP.
> Remove the Lv2NRSLAMPImage rule

- jwst/combine_1d/combine1d.py
- jwst/datamodels/properties.py
- jwst/datamodels/tests/test_fits.py
- jwst/datamodels/util.py
Addresses #3655 
The problem on save turned out to be less of an astropy bug and more of a missing feature -- the public API doesn't currently allow us to put a FITS_rec into "pseudo unsigned integer" mode.  We were already messing with astropy implementation details by setting `_colrefs` directly, so I don't think it's a big deal to also set `_uint`.
The problem on load is, I think, an astropy bug.  I filed an issue and added a workaround here, which is to overwrite the incorrect FITS_rec dtype.
> Fix corruption of FITS tables with unsigned int columns on save and load

- README.md
- Update README install instruction to use `pip install`
- Update the DMS release table to include `0.13.4` and `0.13.5`.
> Rewrite installation instructions in README

- jwst/associations/association.py
- jwst/datamodels/ndmodel.py
- jwst/exp_to_source/exp_to_source.py
- jwst/fits_generator/util.py
This removes references to collections.* ABCs that have been deprecated since Python 3.3 and won't be available in Python 3.8:
> Changed in version 3.3: Moved Collections Abstract Base Classes to the collections.abc module. For backwards compatibility, they continue to be visible in this module through Python 3.7. Subsequently, they will be removed entirely.
(https://docs.python.org/3/library/collections.html)
> Remove references to deprecated ABCs that will be removed in Python 3.8

- jwst/tests_nightly/general/fgs/test_fgs_sloper_1.py
One `calwebb_detector1` regression test using an FGS image-mode exposure as input consistently takes ~3 hours to execute, which is 1-2 hours longer than all of the remaining regression tests combined. This test needs to be reworked or we need to find better data to use, so that our regression test runs are not hostage to this one test. I'm marking it to be skipped for now, until something can be done to fix or replace it.
> Skip really slow FGS detector1 regtest

- CHANGES.rst
- jwst/associations/lib/asn_schema_jw_level2b.json
- jwst/associations/lib/asn_schema_jw_level3.json
- jwst/datamodels/fits_support.py
It's been [pointed out](https://github.com/spacetelescope/asdf/issues/530#issuecomment-503811670) that jsonschema 2.6 is incompatible with Python 3.8, so at some point we'll need to upgrade.  These changes make jwst compatible with both jsonschema 2.6 and 3.0.
> Changes necessary to support jsonschema 3.x

- CHANGES.rst
- docs/jwst/group_scale/description.rst
- docs/jwst/pipeline/calwebb_detector1.rst
- jwst/group_scale/group_scale.py
- jwst/group_scale/group_scale_step.py
A few minor updates to the `group_scale` step code, to fix formatting of info in log messages, and the step docs (including indicating that the step is not used for TSO exposures), just to try to make everything as clear as possible.
> JP-656: Minor updates for group_scale step

- jwst/lib/engdb_tools.py
Addresses #3742 
The B string engineering database seems to have been wiped out, which is causing tests that depend on live data to fail.  This PR switches the default db to D string.
> Switch engineering database to D-string

- CHANGES.rst
- jwst/datamodels/util.py
This addresses the problem in the regression tests where TUNITn keywords are being dropped from the output.  There are a couple of underlying problems in astropy (casting a FITS_rec to a new dtype drops column fields like unit, columns with character data disagree with FITS_rec on their dtypes) that may need to be resolved, but this PR at least gets us back to where we were.
The fix is to be more surgical about replacing table dtypes with the individual field dtypes.  Previously I was always recreating the table dtype from the fields, now I'm only recreating them if necessary, and even then only replacing signed int with unsigned int.
I ran the following regression tests successfully:
jwst/tests_nightly/general/miri/test_miri_steps.py dark_current_miri2
(to confirm that missing TUNITn …
> Only overwrite FITS_rec dtypes for signed int columns that should be unsigned

- CHANGES.rst
- jwst/datamodels/schemas/wcsinfo.schema.yaml
This works around the issue of `DataModel.update` updating only attributes that have a corresponding FITS keyword.
Resolves #3594
> JP-764 : write siaf_x/yref_sci to FITS keywords

- CHANGES.rst
- jwst/stpipe/step.py
- jwst/stpipe/tests/test_step.py
This `stpipe.Step` method has been broken for a very long time.  It is now fixed with a test.
> Fix Step.print_configspec()

- JenkinsfileRT
Logs are too long when set to DEBUG level as is default in pytest.  Setting the level to WARNING will still print WARNING, ERROR and CRITICAL log messages in the automated runs, but not DEBUG or INFO log messages.
Should make the test results much easier to read, and also for tests that have very verbose DEBUG logging, make the XML results file a reasonable size so Jenkins can slurp it up.
> Set pytest caplog to WARNING or greater in JenkinsfileRT

- jwst/extract_2d/grisms.py
- jwst/extract_2d/tests/test_grisms.py
Due to the addition of computing a wavelength array for each extracted grism cutout in `extract_2d` in #3664 , the runtime of `test_extract_wfss_object()` test increased from ~3 secs to ~5 min.
Before:
```
$ pytest -v jwst/extract_2d/tests/test_grisms.py::test_extract_wfss_object
========================== test session starts ===========================
platform darwin -- Python 3.7.3, pytest-5.0.1, py-1.8.0, pluggy-0.12.0 -- /Users/jdavies/miniconda3/envs/jwst/bin/python
cachedir: .pytest_cache
rootdir: /Users/jdavies/dev/jwst, inifile: setup.cfg
plugins: openfiles-0.3.2, xdist-1.29.0, forked-1.0.2, doctestplus-0.3.0, ci-watson-0.3, requests-mock-1.6.0
collected 1 item                                                         
jwst/extract_2d/tests/test_grisms.py::test_extract_wfss_object …
```
> Speed up test_extract_wfss_object unit test

- JenkinsfileRT
- jwst/associations/tests/helpers.py
- jwst/linearity/tests/test_linearity.py
- jwst/tests/base_classes.py
- setup.py
Plus:
- Set --log-level=INFO in JenkinsfileRT
- Remove pytest-faulthandler dependency; Pytest 5.0 includes it
- Fix regex deprecation in associations test helpers
- Fix reffile validation warning in linearity unit tests; speed them up by using smaller arrays
> Fix usage of ci_watson --env cli arg in BaseJWSTTest class

- jwst/associations/lib/rules_level2_base.py
- jwst/associations/lib/rules_level3_base.py
- jwst/tests_nightly/general/associations/test_level3_product_names.py
Fix deprecations like the following
```
jwst/tests_nightly/general/associations/test_level3_product_names.py:17: DeprecationWarning: invalid escape sequence \d
'(?P<program>\d{5})'
```
> Fix regex deprecations in associations

- jwst/tests_nightly/general/associations/conftest.py
- jwst/tests_nightly/general/associations/test_sdp_pools.py
- jwst/tests_nightly/general/associations/test_standards.py
This will allow passing `--env` to point to a different tag branch on the Artifactory repo, to get the input and truth data appropriate for that tag.
```
pytest --bigdata --slow jwst/tests_nightly/general/associations/test_sdp_pools.py --env=0.13.7
```
This also fixes `--no-merge` deprecation warning produced in the associations regression tests.
```
201907081253:WARNING:jwst.associations.__call__:The "--no-merge" option is now the default and deprecated. Use "--merge" to force merging.
```
> Propagate env to association pool paths in regression tests

- jwst/datamodels/schemas/core.schema.yaml
- jwst/datamodels/schemas/lev3_prod.schema.yaml
- jwst/datamodels/schemas/multispec.schema.yaml
Addresses #3661 
These are the title and enum field updates that we held back when updating the datamodels schemas in #3653.
> Update datamodels schema title and enum fields to match latest keyword dictionary dump

- jwst/resample/resample_spec.py
- jwst/resample/resample_utils.py
Get rid of these expected warnings due to NaNs in the spectral gWCS transforms:
```
$ pytest --bigdata --slow --basetemp=/Users/jdavies/scratch jwst/tests_nightly/ -k test_run_msaflagging
======================================================================== test session starts ========================================================================
platform darwin -- Python 3.7.3, pytest-5.0.1, py-1.8.0, pluggy-0.12.0
rootdir: /Users/jdavies/dev/jwst, inifile: setup.cfg
plugins: openfiles-0.3.2, xdist-1.29.0, forked-1.0.2, doctestplus-0.3.0, ci-watson-0.3, requests-mock-1.6.0
collected 262 items / 261 deselected / 1 selected …
```
> Filter resample RuntimeWarnings due to NaNs in spectral WCS transforms

- CHANGES.rst
- docs/jwst/gain_scale/description.rst
- jwst/gain_scale/gain_scale.py
- jwst/gain_scale/tests/test_gain_scale.py
Updated the `gain_scale` step to apply the correction to the variance arrays, in addition to SCI and ERR. Also updated the unit test to create CubeModels, instead of RampModels, because when the step is applied in the `calwebb_detector1` flow it's working on countrate images/cubes, not 4-D ramps. Updated docs accordingly.
Fixes #3790.
> Update gain_scale step to work on variance arrays

- scripts/okify_regression_tests.py
https://jira.stsci.edu/browse/JP-856
I noticed that one of the regression tests was not okified by the new script.  It turns out fitsdiff may omit the version description line that I used to break up the output by file, and when that happens the script was failing to query the user about one of the files.
This PR fixes that issue.  I tested it on last night's test output and it was able to recognize the busted file.
> Fix bug in okify script when fitsdiff fails to write version description

- CHANGES.rst
- docs/jwst/data_products/file_naming.rst
- docs/jwst/exp_to_source/main.rst
- docs/jwst/gain_scale/description.rst
- jwst/exp_to_source/exp_to_source.py
Updated the `exp_to_source` docs to give a lot more details as to how things work for various modes, and examples of reorganized file names. Also fixed some broken internal references in the `gain_scale` doc. Also added a little bit of logging info to the `exp_to_source` step itself (it's nice to be able to see what's happening, instead of just staring at a blank screen).
Fixes #3773
> JP-842 Update exp_to_source docs

- JenkinsfileRT
Adds a second `BuildConfig` assigned to an OSX host which simply installs the package along with its testing dependencies as is done on Linux so that an environment snapshot can be created which includes the OS-specific differences in the minimal conda environment that serves as a base.
> Enable environment snapshot creation for macos

- jwst/tweakreg/wcsimage.py
Removed temporary workaround that had been put into `tweakreg`, due to a problem in the spherical geometry package. The spherical geometry bug has now been fixed, so the workaround isn't needed anymore.
Fixes #2739
> Remove tweakreg workaround

- jwst/outlier_detection/outlier_detection_scaled.py
This came up in testing the released `jwst 0.13.7` SDP-delivered conda spec file on our 0.13.7 Artifactory input and truth data snapshot.
The dev version of `photutils` no longer has indexable ApertureMasks if there is only one Aperture.
> Update outlier_detection for photutils>=0.7 non-indexable Apertures

- CHANGES.rst
- jwst/assign_wcs/nirspec.py
- jwst/combine_1d/combine1d.py
- jwst/extract_1d/extract.py
- jwst/extract_1d/ifu.py
- jwst/resample/resample_step.py
The changes in this PR are necessary (except the one in resample) for the code to run with the new modeling.
- assign_wcs.nirspec:
Deleted the inverse of a model `M1` which is to be assigned as inverse to a model `M` because modeling checks recursively for "correct" inverses and raises an error even if they are not needed.
- combine_1d:
There's only one  input to the WCS transform and it defines the wavelength. Spatial coordinates are constants.
- extract_1d:
`util.pixel_area` takes as input the shape of the data, constructs input arrays from it and evaluates the WCS. In the case of a `CubeModel` a shape of length 3 was passed in but the WCS takes 2 inputs.
- resample:
Fixed an unclosed file `Warning`.
> works with new modeling

- CHANGES.rst
- jwst/exp_to_source/exp_to_source.py
Update the `exp_to_source` to close the input exposures after it's done rearranging the data into new models, with a minor change to a logging message too.
Fixes #3802.
> JP-858 Close intermediate files

- jwst/lib/tests/test_set_telescope_pointing.py
- jwst/tests/compare_outputs.py
- close 2 FITS files left open in fixtures feeding tests in `set_telescope_pointing`.  Gets rid of the following warnings:
```
jwst/datamodels/schema.py:250
/Users/jdavies/dev/jwst/jwst/datamodels/schema.py:250: ResourceWarning: unclosed file <_io.FileIO name='/var/folders/jg/by5st33j7ps356dgb4kn8w900001n5/T/tmpltx3gjhn/fits.fits' mode='rb' closefd=True>
schema = OrderedDict(schema)
jwst/datamodels/schema.py:250
/Users/jdavies/dev/jwst/jwst/datamodels/schema.py:250: ResourceWarning: unclosed file <_io.FileIO name='/var/folders/jg/by5st33j7ps356dgb4kn8w900001n5/T/tmpq8j0udl9/fits_nosiaf.fits' mode='rb' closefd=True>
schema = OrderedDict(schema)
```
- shorten the _very long_ tracebacks seen in our regression test failures.  Essentially, this will get rid of having all the code of …
> Clean up open file warnings; shorten traceback in regtest failures

- jwst/imprint/tests/test_imprint.py
Adding unit test for the imprint step. This take an image model as the input and imprint model so when the correction is applied the result is zero. Also checks that the correction keyword is added to the metadata.
> Adding imprint unit test

- jwst/associations/lib/rules_level2_base.py
- jwst/associations/lib/rules_level2b.py
The association rules are updated to exclude NIS_EXTCAL exposures. In JWSTDMS-31 the example given is for jw00629 where observation number 9 & 10 are listed as exptype='NIS_EXTCAL'. The new rules exclude those files and is shown in the difference between the updated associations for jw00629_20190624t200638_pool.csv,
grep Only diffs_output_July22.log
121:Only in output: jw00629-o009_wfs-image2_001_asn.json
122:Only in output: jw00629-o009_wfs-image2_002_asn.json
123:Only in output: jw00629-o010_wfs-image2_001_asn.json
124:Only in output: jw00629-o010_wfs-image2_002_asn.json
All the other associations remain the same.
> JP-865 Updated association rules to exclude NIS_EXTCAL eposures

- CHANGES.rst
- jwst/cube_build/cube_build.py
- jwst/cube_build/cube_build_step.py
- jwst/cube_build/cube_cloud.py
- jwst/cube_build/cube_overlap.py
- jwst/cube_build/file_table.py
- jwst/cube_build/ifu_cube.py
- jwst/cube_build/instrument_defaults.py
The PR sets the DQ plane of the IFU cube. The values it sets are:
- 0: good data
- 1: DO_NOT_USE (Hole - should have data but does not)
- 1 + 512 (NON_SCIENCE): no overlapping data with IFU cube
The number of holes for each IFU cube is printed in the logging.
This PR also fixed an error in CRVAL3 (it was off by 1/2 a pixel).
Messages are now printed if data falls outside the min and max wavelength (which is set by the cubepars reference file).
Note: A future update for NIRSpec will use the min and max wavelength of data to set the IFU wavelength ranges.
> JP-349 DQ Flagging for IFU cubes

- CHANGES.rst
- jwst/extract_1d/extract.py
- jwst/extract_1d/ifu.py
- jwst/extract_1d/util.py
- jwst/extract_2d/grisms.py
- jwst/extract_2d/tests/test_grisms.py
The `extract_1d` step was modified to only call `util.pixel_area()` for the first integration of multi-integration data.  Also, that function immediately returns `pixel_solid_angle = None` for WFSS data; for these data the WCS function returns constant values for right ascension and declination, so the angular size of a pixel cannot be determined by this function.
The extract_2d step was modified to compute and populate the `wavelength` attribute for NIRCam TSO data.  This partially addresses JP-845, GitHub #3784, Compute wavelengths for NIRCam TSO data, but only the wavelength attribute is populated, not the variance arrays.  To close this issue, the variance arrays need to be copied from input to output.
> JP-878 Don't try to compute pixel solid angle for WFSS data

- CHANGES.rst
- jwst/datamodels/container.py
- jwst/pipeline/calwebb_spec3.py
Updated `datamodels` to allow for specification of an allowed list of ASN `exptypes` to keep when loading an ASN into a `ModelContainer`, and update `calwebb_spec3` to make use of this feature to keep TA's from processing.
> JP-843 Updates to exclude TA's from calwebb_spec3 processing

- CHANGES.rst
- jwst/associations/lib/rules_level3.py
- jwst/associations/tests/test_level3_basics.py
NIS_IFU bkg observations as level3 spec association. 
Fix unit tests where target acquisitions were left out of associations. test_level3_basics.py  expects at least one member to be a target acquisition.  
Fixes #3824.
> Jp 868: Background target exposures need to create their own science ASN

- CHANGES.rst
- jwst/assign_wcs/niriss.py
Function `wfss` in assign_wcs/niriss.py called `NIRISSForwardRowGrismDispersion` for GR150R data, and it called `NIRISSForwardColumnGrismDispersion` for GR150C data.  Our data are in DMS ("sky") orientation, however, and the spectra for GR150R are oriented vertically, while the spectra for GR150C are oriented horizontally.
Closes #3760.
> JP-832 Row and column were interchanged for NIRISS WFSS

- jwst/tests_nightly/general/associations/test_generate.py
Update the code and test data for the nightly association tests. The failing tests now pass, 
============================= test session starts ==============================
platform darwin -- Python 3.7.3, pytest-5.0.1, py-1.8.0, pluggy-0.12.0
rootdir: /Users/ddavis/src/JWST/scsb/jwst, inifile: setup.cfg
plugins: openfiles-0.4.0, doctestplus-0.3.0, ci-watson-0.3, requests-mock-1.6.0
collected 25 items
jwst/tests_nightly/general/associations/test_standards.py .............. [ 56%]
..........s                                                              [100%]
> JP-919 Updated associations and tests

- docs/jwst/introduction.rst
- docs/jwst/references_general/explain_rmaps.rst
- docs/jwst/references_general/references_general.rst
- docs/jwst/stpipe/config_asdf.rst
- docs/jwst/stpipe/config_cfg.rst
- docs/jwst/stpipe/devel_step.rst
- docs/jwst/stpipe/index.rst
- docs/jwst/stpipe/user_step.rst
Update the documentation to include ASDF as a configuration file format.
> Document usage of ASDF as a configuration file format.

- JenkinsfileRT
Fixes the problem seen in our Jenkins RT MacOS build:
https://plwishmaster.stsci.edu:8081/blue/organizations/jenkins/RT%2FJWST/detail/JWST/350/pipeline/26#step-161-log-66
```
Collecting jplephem>=2.8; extra == "ephem" (from jwst==0.13.8a0.dev142+gda86e52f)
Downloading https://files.pythonhosted.org/packages/14/6f/354fd50e625a66c7be3f08095c0e1fa389c75453858acf2689ffa9c4fc54/jplephem-2.9.tar.gz
Collecting pymssql>=2.1; extra == "ephem" (from jwst==0.13.8a0.dev142+gda86e52f)
Downloading https://files.pythonhosted.org/packages/2e/81/99562b93d75f3fc5956fa65decfb35b38a4ee97cf93c1d0d3cb799fffb99/pymssql-2.1.4.tar.gz (691kB)
ERROR: Complete output from command python setup.py egg_info:
ERROR: /Users/iraf/build/pembry/workspace/RT/JWST/miniconda/envs/tmp_env1/lib/python3.6/site-packages/setuptools/ …
```
> Fix Jenkins RT MacOS build

- .coveragerc
- .gitignore
- .travis.yml
- Jenkinsfile
- JenkinsfileRT
- JenkinsfileRT_Unstable
- README.md
- requirements-dev.txt
- setup.py
Implement `codecov`.
~Note: Not sure at the moment how to do this for `.travis.yml` because it uses a wrapper to handle commands.~
Resolves #3893.
Resolves #135.
Resolves #3880.
Closes #3883.
> Add coverage report and regression test with dev dependencies

- JenkinsfileRT
Tests are taking almost 7 hours.  We had dialed back the number of cores from 30 to 15 thinking we would run the dev ones at the same time.  We are not doing that. So let's bump them back up to 30.
> Switch back to xdist n 30 for regtests

- setup.py
The fix was applied in this commit
https://github.com/astropy/astropy/commits/master/astropy/modeling/tabular.py
This should fix the failing cube_build regression test.
> move astropy hash to fix for tabular inverse

- CHANGES.rst
- jwst/cube_build/ifu_cube.py
- jwst/datamodels/properties.py
- jwst/datamodels/schemas/ifucube.schema.yaml
- jwst/datamodels/tests/test_schema.py
This PR improves the logic in the `datamodels.properties._cast()` function so that now it can handle structured arrays who's fields can be arbitrarily shaped arrays. Previously schemas for structured arrays required a fixed shape to be defined which in turn led to issues such as https://github.com/spacetelescope/jwst/issues/3750
In addition, the new logic also allows specifying the ``ndim`` constrain in the schemas for the fields of structured arrays.
Finally, this PR modified the code for the ``cube_build`` so that wavetables are saved using arrays of appropriate length `=>` DS9 "frame matching by WCS" now should work with cubes.
> Allow variable shape arrays in schemas for structured array fields

- jwst/datamodels/properties.py
Python 3.8 deprecation reintroduced in #3976.
> Fix deprecated Mapping import

- CHANGES.rst
- jwst/datamodels/properties.py
- jwst/datamodels/tests/test_schema.py
A fix for https://github.com/spacetelescope/jwst/issues/3991. When structured arrays are NOT initialized from "native Python types", i.e., `[(), (), ...]`, `_cast()` should skip the code introduced in  https://github.com/spacetelescope/jwst/pull/3976
> Fix an issue in casting numpy arrays to structured array types

- CHANGES.rst
- jwst/flatfield/tests/test_flatfield.py
Function `test_flatfield_step_interface` in test_flatfield.py was disabled by using pytest.mark.skip.
> JP-944 Disable a flat_field test

- CHANGES.rst
- jwst/datamodels/properties.py
Fixes a bug described in https://github.com/spacetelescope/jwst/issues/3999#issuecomment-532276865 This bug was introduced in a bug fix to a bug fix in #3995. Essentially the structured array schema validation AND type coercion code was (incorrectly) skipped when input is already a structured array.
CC: @stscicrawford @jemorrison
> Fix a bug in casting of structured arrays

- Jenkinsfile
We can play around with the settings some if need be.
All tests are ignored, and only the `jwst` package and its `scripts` are audited to avoid needless log-spam produced by repo-level code.
> Add bandit for security auditing

- CHANGES.rst
- jwst/ipc/ipc_corr.py
- jwst/ipc/x_irs2.py
- jwst/lib/pipe_utils.py
- jwst/lib/tests/test_pipe_utils.py
- jwst/refpix/refpix_step.py
- jwst/saturation/saturation.py
- jwst/saturation/x_irs2.py
For science data, the value of the PATTTYPE keyword will contain "IRS2" if and only if the data were read out using IRS2.  Target acquisition data are never read out using IRS2, but PATTTYPE can still contain "IRS2".  Some but not all tests for IRS2 mode already use the image shape rather than the PATTTYPE keyword.
A new `is_irs2` function has been added to lib/pipe_utils.py, and the nearly identical function of the same name has been removed from the x_irs2.py files in ipc and saturation.  This function returns True if one axis of the input image is larger than 2048 (it will be 3200, for the current IRS2 parameters).  Files in refpix, ipc, and saturation have been modified to call the version of `is_irs2` in lib.
> JP-737 Don't use PATTTYPE to check for IRS2 mode

- CHANGES.rst
- jwst/datamodels/schemas/fgsimg_photom.schema.yaml
- jwst/datamodels/schemas/mirimg_photom.schema.yaml
- jwst/datamodels/schemas/nisimg_photom.schema.yaml
- jwst/datamodels/schemas/nrcimg_photom.schema.yaml
#4052 created new data models for imaging-mode photom reference files, in support of JP-1014. That PR, however, forgot to include the CRDS selector keywords - EXP_TYPE, P_EXP_TY, and BAND - the schema, so that they're available in the data models. This PR fixes that omission.
It's likely the case that only the P_EXP_TY keyword is needed in the reference file headers, but it can't hurt to have both EXP_TYPE and P_EXP_TY defined, in case anyone wants to populate EXP_TYPE too.
> Add exptype keywords to new imaging photom data models

- requirements-sdp.txt
This simplifies the logic required to create an environment snapshot after regression test runs.
> [skip ci] Change to alternative VCS syntax in requirements-sdp.txt

- CHANGES.rst
- jwst/datamodels/fits_support.py
- jwst/datamodels/model_base.py
When a file is read with an asdf extension version older than the version it was created with asdf raises a `Warning` like this one:
```
asdf/asdf.py:202: UserWarning: File 'poly.asdf' was created with extension 'astropy.io.misc.asdf.extension.AstropyAsdfExtension' from package astropy-4.0.dev25781, but older version astropy-3.2.1 is installed
warnings.warn(fmt_msg)
```
This type of warning is raised also when reading a FITS file with a datamodel under those circumstances. This is really just an informational warning. Given the level of backwards compatibility and versioning in asdf the usual case is that the file is read and converted correctly. In fact, if it wasn't converted, an `Error` is raised. So given this I suggest we propagate the flag to the pipeline and set it to `True`, i.e. …
> JP-860: filter out asdf warnings related to extension version mismatch

- .gitignore
- .travis.yml
- setup.cfg
If our `requirements-sdp.txt` file contains editable installs of dependencies, `pip` installs those into a local `src` dir within the `jwst` package.  This can mess up pytest's test discovery.  So we should ignore this directory.
Closes #4073
> Ignore src dir for git and pytest

- CHANGES.rst
- jwst/associations/lib/dms_base.py
- jwst/associations/lib/rules_level3_base.py
- jwst/associations/tests/test_asn_from_list.py
Updated rules to have NRS_MIMF exposures processed as WFSC data. The unit tests pass, 
```
pytest ~/src/JWST/scsb/jwst/jwst/associations/tests/ | tee ASN_unittests_Sept30.log
...
-- Docs: https://docs.pytest.org/en/latest/warnings.html
== 133 passed, 2 xfailed, 1 warnings in 395.83s (0:06:35) ==========
```
The regression tests will need truth file updates. 
`====== 3 failed, 103 passed, 14 skipped, 2 xfailed in 2497.03s (0:41:37) =======
`
There are 88 total files to be updated, mainly removing the image2 associations and replacing them with the wfs-image2 and adding the wfs-image3 products for programs jw00629 & jw84600. Example files for jw00629-o004 are shown, 
jw00629-o004_wfs-image2_001_asn.json
```
{
"asn_type": "wfs-image2",
"asn_rule": "candidate_Asn_Lv2WFSC",
"version_id": null, …
```
> Jp 1000 Have NRS_MIMF exposures processed as WFS observations

- jwst/ramp_fitting/tests/test_ramp_fit.py
No need for full-sized arrays in unit test when a single pixel is being tested.   This speeds up the tests significantly.  For example, the slowest:
```
17.08s call     jwst/ramp_fitting/tests/test_ramp_fit.py::TestMethods::test_nocrs_noflux[GLS]
```
And now:
```
0.20s call     jwst/ramp_fitting/tests/test_ramp_fit.py::TestMethods::test_nocrs_noflux[GLS]
```
Overall the runtime on my machine goes from 119 seconds down to 5 seconds.
> Speed up ramp fit unit tests by using smaller arrays

- jwst/associations/tests/test_asn_from_list.py
- jwst/tests_nightly/general/associations/test_generate.py
Update the number of expected associations in nightly tests test_generate from the current 98
to the 99 being created.
> Jp 1036 Update number of associations in test_generate to match number after NRS_MIMF fix (JP1000)

- CHANGES.rst
- jwst/datamodels/__init__.py
- jwst/datamodels/photom.py
- jwst/datamodels/schemas/mirimrs_photom.schema.yaml
- jwst/datamodels/schemas/mirlrs_photom.schema.yaml
- jwst/datamodels/schemas/nissoss_photom.schema.yaml
- jwst/datamodels/schemas/niswfss_photom.schema.yaml
- jwst/datamodels/schemas/nrcwfss_photom.schema.yaml
- jwst/datamodels/schemas/nrsfs_photom.schema.yaml
- jwst/datamodels/schemas/nrsmos_photom.schema.yaml
Baseline version of updated/new spectroscopic mode photom reference file data models, per the specs outlined in JP-1018. The discussion of the specs is not quite finalized, so there may be some further updates before merging.
As with the imaging mode photom data models, a little rearranging of MIRI model class names was necessary to maintain backwards compatibility with the models and reffiles currently in use. The old MIRI MRS model is `MiriMrsPhotomModel`, which uses schema ``mirimrs_photom.schema.yaml``, while the new one is `MirMrsPhotomModel` and uses schema ``mirmrs_photom.schema.yaml`` (note that the only difference in the names is the extra "i" after "Mir" in the old model).
Fixes #4088
> JP-1032: Update spectroscopic photom data models

- MANIFEST.in
- jwst/__init__.py
- jwst/stpipe/step.py
- pyproject.toml
- setup.cfg
- setup.py
Note: 
I retained `__version_commit__` because `stpipe` stores the value as metadata. When not in development mode (i.e. no `.dev#+gHASH.dDATE` exists in `__version__`), the value is left as an empty string. If the string is empty `stpipe` will emit `RELEASE` instead of `unknown`
> Replace RELIC with setuptools_scm

- jwst/__init__.py
- jwst/tests/test_version.py
Fixes the following bug introduced by #4104 :
```
[...]/validate.py:35: ValidationWarning: While validating calibration_software_revision the following error occurred:
('5a2e91e3',) is not of type 'string'
Failed validating 'type' in schema:
{'$schema': 'http://stsci.edu/schemas/asdf-schema/0.1.0/asdf-schema',
'blend_table': True,
'fits_keyword': 'CAL_VCS',
'title': 'Calibration software version control sys number',
'type': 'string'}
On instance:
('5a2e91e3',)
warnings.warn(errmsg, ValidationWarning)
```
Resolves #4106
> Fix __version_commit__ regression

- Jenkinsfile
- JenkinsfileRT
With any luck this will prevent `coverage` from scanning the source directories created by `pip` under `./src` (by default).
> Store pip `-e` source directory outside of tree

- CHANGES.rst
- jwst/assign_wcs/tests/test_nirspec.py
- jwst/assign_wcs/util.py
- jwst/extract_2d/nirspec.py
Resolves #3929 
The footprint is computed using the transform from "slit_frame" to "world" .
TODO: 
[x] Verify the order of corners in `S_REGION`
It looks like th eorder here is correct - clockwise - which means the rest of the footprints are incorrect. I'll open an issue about it.
[ X] Find out what is the best order of corner coordinates for mosviz
~After some off-line discussion it's still unclear what mosviz needs. Best if a new ticket is filed for that work.~ Got a confirmation that this is good for mosviz.
This will produce failures in some regression tests.
> improve slit footprint computation

- jwst/datamodels/schemas/mirlrs_photom.schema.yaml
Initial version of the new `MirLrsPhotomModel` data model schema was missing the ``BAND`` keyword, which is needed as a CRDS selector for all MIRI photom reference files. Added it to ``mirlrs_photom.schema``.
> Add BAND keyword to MirLrsPhotomModel

- docs/jwst/pipeline/calwebb_spec2.rst
Changed the comment about the order of the `extract_2d` and `flat-field` steps to remove the mistaken reference to the `background` step.
> JP-1054: Fix mistake in calwebb_spec2 docs

- CHANGES.rst
- JenkinsfileRT
- requirements-sdp.txt
- setup.py
In addition, `setup.py` has been updated to requiring:
`python>=3.6` <- an astropy requirement
`numpy>=1.16`
Resolves #4124
> Use python 3.7 in regtest builds

- jwst/stpipe/crds_client.py
- jwst/stpipe/pipeline.py
- jwst/stpipe/step.py
Consolidated all direct imports of CRDS modules in the jwst.stpipe.crds_client.   Imports of the crds.core.exceptions module were deferred/delayed behind the crds_client.get_exceptions_module() getter function.
This helps manage the import order of circular CAL and CRDS imports.
The imports are circular due to the CAL dependence on CRDS for best refererences,  and the CRDS dependence on CAL for datamodels support.
> ccd-601 consolidate CRDS imports

- CHANGES.rst
- jwst/stpipe/config_parser.py
- jwst/stpipe/step.py
- jwst/stpipe/tests/steps/__init__.py
- jwst/stpipe/tests/steps/foo_pipeline.cfg
- jwst/stpipe/tests/steps/makelist.cfg
- jwst/stpipe/tests/test_asdf_parameters.py
`Step.call()` was using dictionaries to pass along the step configuration to the final `run()` method, but it really needed to use `ConfigObj` so that the nested merging of configs works.  I tried to pattern it after `step_from_cmdline()`.
Resolves #4079
> jp-1024 Fix config_file merging bug in Step.call

- .travis.yml
- Make `python 3.7.4` our default testing env
- Fix bug that was resulting in wrong version of `numpy` to be used.
For future reference (to my future self) the full semantic version needs to be used with `~=` operator, or else one gets unexpected results:
`pip install numpy~=1.16` will install `numpy==1.17.2`
`pip install numpy~=1.16.0` will install `numpy==1.16.5`
> Add python 3.7.4 to SDP TravisCI test matrix

- CHANGES.rst
- jwst/stpipe/step.py
If `Step.record_step_status()` is called with `success=False`, then also set `Step.skip = True`.
Resolves #4150.
> jp-1066 Add Step.skip=True for Step.record_step_status()

- CHANGES.rst
- jwst/datamodels/__init__.py
- jwst/datamodels/apcorr.py
- jwst/datamodels/schemas/fgsimg_apcorr.schema.yaml
- jwst/datamodels/schemas/mirimg_apcorr.schema.yaml
- jwst/datamodels/schemas/nisimg_apcorr.schema.yaml
- jwst/datamodels/schemas/nrcimg_apcorr.schema.yaml
New data models for the imaging mode aperture correction reference files, according to the specs provided in JP-1022.
Fixes #4145
> JP-1063: Initial version of imaging APCORR ref file models

- CHANGES.rst
- jwst/photom/photom.py
Function save_area_nirspec failed for NIRSpec IFU data because it was trying to assign a value to slit.meta.photometry.pixelarea_arcsecsq, but when running photom the input is a single 2048x2048 array, i.e. there are no slits.
Function photom_io failed for NIRISS extended-source data.  The conversion factor should be divided by the pixel area, but that value was None.
> JP-1053 Fix bugs in photom

- jwst/straylight/tests/test_straylight_step.py
Related to problems found in #4166. 
Removed unit test that:
1) Was getting around Step spec validation by assigning values to the attributes after `__init__`.  Validation will catch this and raise an exception after the merging of #4166 
2) Used an invalid attribute `override_straylight`.  The only `reftype` defined is a `regions` reffile, so this had no effect.
Fixes #4171.
> JP-1085: Remove Straylight interface tests

- CHANGES.rst
- jwst/photom/photom.py
NRS_BRIGHTOBJ data were incorrectly treated the same as fixed-slit, but the data models are actually not the same.  Also, the logic in the function for getting the pixel area for fixed-slit data was incorrect.
> Incorrect model for NRS_BRIGHTOBJ data.

- CHANGES.rst
- jwst/photom/photom.py
- jwst/tests_nightly/general/nirspec/test_pipelines.py
- jwst/tests_nightly/general/nirspec/test_spec2pipelines.py
Some NIRSpec regression tests are not passing because the photom reference file is not being found by CRDS, due (in some cases, at least) to a value of USEAFTER that is more recent than the date of observation.
> Mark some tests with xfail

- jwst/tests_nightly/general/nirspec/test_nirspec_steps_single.py
One more NIRSpec reg test that's failing with differences, because the new NIRSpec photom ref files have a bad USEAFTER date, which is causing the old ref files to get used with the new photom code. Mark as xfail for now, until ref files get fixed.
> Mark a bad NIRSpec reg test as xfail

- .travis.yml
This will be testing `python 3.8` as installed via `venv`.  Right now it is set as an allowed failure.
Resolves #4197
> JP-1101: Add python3.8 build to TravisCI matrix

- README.md
& add python version to end-user conda installation step to avoid unintentional use of newer python.
Since the DMS snapshot installation procedure was modified slightly with the 0.14.0 release, the documentation here was rendered obsolete. To avoid having to maintain it in two locations, this documentation now points to the procedures associated with each snapshot release.
Since python 3.8.0 was recently published as a conda package, the conda create command used without pinning obtains that version of python rather than 3.7.4, which is the latest tested version. Add a variant of the `conda create` command that pins the target python version if the latest is not wanted.
> Update README to avoid duplication of DMS snapshot installation procedure

- requirements-sdp.txt
Now that this is installable from pypi, we can change this from pointing to the tag on Github to actually being a normal `pip install`.
> Change crds dependency pin from hash to 7.4.1.2 in requirements-sdp.txt

- CHANGES.rst
- jwst/photom/tests/test_photom.py
- jwst/resample/tests/test_resample_spec.py
- jwst/rscd/rscd_sub.py
MIRI LRS slitless exposures are now coming out of DMS with SUBARRAY='SLITLESSPRISM' instead of the old 'SUBPRISM' value. Most MIRI reference files now use SLITLESSPRISM too. So this excises the use of 'SUBPRISM' from our code base.
> Remove/replace SUBPRISM in unit tests

- README.md
Also update install and test instructions
- no need to pre-install numpy now, as all dependencies now specify it correctly
- add warning about `pytest --basetemp` wiping the specified path each test run
> Add CRDS CONTEXT 563 to README

- CHANGES.rst
- jwst/datamodels/schemas/core.schema.yaml
- jwst/datamodels/schemas/keyword_coronmsk.schema.yaml
Added new/modified NIRCam values for the CORONMSK keyword.
Fixes #4233  / JP-1127
> JP-1127: Update allowed values for CORONMSK keyword

- JenkinsfileRT
- requirements-sdp.txt
* Specify requirements files in `BuildConfigs`.
* Use non-editable installs in requirements file used to populate build environment.
In addition to simplifying the build environment setup, these changes facilitate an improved environment snapshot process provided by https://github.com/spacetelescope/jenkins_shared_ci_utils/pull/69, namely making the snapshot artifacts produced compatible with the environment creation procedures used by DMS when accepting release deliveries.
> Streamline environment specification

- jwst/assign_wcs/nirspec.py
While debugging `assign_wcs` processing of a problematic I decided to make the messaging a little more complete and informative. No changes at all to actual processing.
Related to problem documented in JP-733.
> Minor changes to MSA messages in assign_wcs

- CHANGES.rst
- jwst/photom/photom.py
- jwst/tests_nightly/general/nirspec/test_nirspec_fs_spec3.py
- jwst/tests_nightly/general/nirspec/test_nirspec_steps_single.py
- jwst/tests_nightly/general/nirspec/test_pipelines.py
- jwst/tests_nightly/general/nirspec/test_spec2pipelines.py
Fix the one remaining line in the `photom` step code that was looking for a "photmjsr" entry in the NIRSpec photom reference files, so that it looks for "photmj" instead, because that's what's used in the new NIRSpec photom ref files.
Also removed the xfails for a number of NIRSpec tests that include the `photom` step. They were set to xfail a while back when the new NIRSpec photom ref files weren't working (or getting selected). Now they are, so we need to test against them again (which would've caught the above error much sooner).
> JP-1139: Fix photom bug for NIRSpec IFU data

- CHANGES.rst
- jwst/white_light/white_light.py
NaNs are  now treated as 0 in the flux sum for each integration in the input.
> Fix for JP-1008: White Light Step does not ignore NaNs in input.

- CHANGES.rst
- docs/jwst/photom/main.rst
- jwst/photom/photom.py
For all instruments other than NIRSpec, the pixel area (solid angle) is not gotten from the photom reference file instead of from the area reference file.
> Get the pixel area from the photom reference file

- jwst/tests_nightly/general/nirspec/test_nirspec_fs_spec3.py
This test should be xfailed until #4269 is addressed.
> Xfail test_nrs_fs_spec3

- .coveragerc
- .travis.yml
- Jenkinsfile
- JenkinsfileRT
- JenkinsfileRT_Unstable
Sets up Codecov flags
- `unittests`
- `nightly`
- `newnightly`
So that our daily coverage testing is being tracked in parallel, and that there are apples-to-apples comparisons.
And only do coverage on the TravisCI builds and the nightly Jenkins RT builds.
Resolves #4264
> Add Codecov flags unittests, nightly, newnightly

- .travis.yml
- Jenkinsfile
Will hopefully resolve issues where a CRDS retrieval from the server fails.  The following:
```
2019-11-18 15:01:02,189 - CRDS - INFO -  Fetching  /home/jenkins/workspace/STScI_jwst_0.14.2x/crds_cache/references/jwst/nirspec/jwst_nirspec_ifuslicer_0003.asdf    2.3 K bytes  (1 / 1 files) (0 / 2.3 K bytes)
2019-11-18 15:01:02,248 - CRDS - ERROR -  Failure downloading file 'jwst_nirspec_ifuslicer_0003.asdf' : Error fetching data for 'jwst_nirspec_ifuslicer_0003.asdf' at CRDS server 'https://jwst-crds.stsci.edu' with mode 'http' : Failed downloading 'jwst_nirspec_ifuslicer_0003.asdf' from url 'https://jwst-crds.stsci.edu/unchecked_get/references/jwst/jwst_nirspec_ifuslicer_0003.asdf' : <urlopen error [Errno 104] Connection reset by peer>
```
leads to
```
_________________________ …
```
> Allow CRDS to retry on CI builds

- .readthedocs.yml
- .rtd-environment.yml
Our readthedocs documentation builds have been failing for a while. This fixes it by removing `conda` from the builds.
Resolves #4262 
Thanks for the pointer @pllim. 
Successful build of this branch here
https://readthedocs.org/projects/jwsttest/builds/9982204/
> Move to RTD version 2 YAML

- CHANGES.rst
- jwst/associations/lib/rules_level3_base.py
- jwst/associations/tests/test_asn_from_list.py
Update the format of the output product name to allow a two digit activity number (base 36).
Testing:
```
pytest  ~/src/JWST/scsb/jwst/jwst/associations/tests
...
==== 133 passed, 2 xfailed, 25 warnings in 274.35s (0:04:34) ====
```
```
pytest -n 3 -ra --bigdata --basetemp=/Users/ddavis/src/JWST/develop/JP-1136/test_Nov19a ~/src/JWST/scsb/jwst/jwst/tests_nightly/general/associations/  --junit-xml=results.xml | tee assoc_tests_JP-1136a.log
============================= test session starts ==============================
platform darwin -- Python 3.7.4, pytest-5.2.2, py-1.8.0, pluggy-0.13.0
rootdir: /Users/ddavis/src/JWST/scsb/jwst, inifile: setup.cfg
plugins: xdist-1.30.0, requests-mock-1.7.0, doctestplus-0.4.0
...
============ 56 passed, 23 skipped, 2 xfailed in 485.14s (0:08:05) …
```
> Jp 1146 Update act_id format to allow base 36 values in product name

- jwst/guider_cds/tests/test_guider_cds.py
Fixes a problem in a pytest fixture where `meta.exposure.type` is not defined, but needed by the `guider_cds` function.  The error:
```python console
$ pytest jwst/guider_cds -k test_table_extensions
============================================================= test session starts ==============================================================
platform darwin -- Python 3.7.4, pytest-5.1.3, py-1.8.0, pluggy-0.13.0
rootdir: /Users/jdavies/dev/jwst, inifile: setup.cfg
plugins: asdf-2.4.3a1.dev13+gc1373db, xdist-1.30.0, requests-mock-1.7.0, doctestplus-0.4.0, openfiles-0.4.0, cov-2.7.1, ci-watson-0.4, forked-1.1.3
collected 9 items / 8 deselected / 1 selected …
```
> Fix bug in guider_cds tests

- jwst/tests/test_infrastructure.py
Fixes current issue in regression tests caused by merging of #3957 
These tests should now work with `--env=dev` and `--env=newdev`.
To reproduce the failure currently in master:
```
$ pytest jwst/tests/test_infrastructure.py --bigdata --env=newdev
============================================================= test session starts ==============================================================
platform darwin -- Python 3.7.4, pytest-5.1.3, py-1.8.0, pluggy-0.13.0
rootdir: /Users/jdavies/dev/jwst, inifile: setup.cfg
plugins: asdf-2.4.3a1.dev13+gc1373db, xdist-1.30.0, requests-mock-1.7.0, doctestplus-0.4.0, openfiles-0.4.0, cov-2.7.1, ci-watson-0.4, forked-1.1.3
collected 11 items …
```
> Use bespoke data for data_glob testing from Artifactory

- .travis.yml
If we set the TravisCI versions like
```yaml
include:
- python: 3.6
- python: 3.7
```
Then we get maybe old, maybe very old versions:
- python 3.6.7 https://travis-ci.org/spacetelescope/jwst/jobs/615155895#L567
- python 3.7.1 https://travis-ci.org/spacetelescope/jwst/jobs/615155896#L567
So let's be explicit that we want all the latest bugfix releases as well.
```yaml
include:
- python: 3.6.9
- python: 3.7.5
```
Fixup from changes made in #3957
> Be explicit in .travis.yml about Python versions

- CHANGES.rst
- jwst/associations/tests/test_asn_from_list.py
- jwst/master_background/master_background_step.py
- jwst/pipeline/calwebb_spec3.py
The level-3 output s2d and x1d files as well as the crf files now have the asn table and asn pool names added to the header. 
```
fkeyprint jw00623-o044_t007_miri_p750l_s2d.fits"[0]" ASN
ASNPOOL = 'jw00623_20191106t132852_pool' / Name of the ASN pool
ASNTABLE= 'jw00623-o044_20191106t132852_spec3_001_asn.json' / Name of the ASN ta
(jwst_dev) bash>fkeyprint jw00623-o044_t007_miri_p750l_x1d.fits"[0]" ASN
ASNPOOL = 'jw00623_20191106t132852_pool' / Name of the ASN pool
ASNTABLE= 'jw00623-o044_20191106t132852_spec3_001_asn.json' / Name of the ASN ta
(jwst_dev) bash>fkeyprint jw00623044001_02103_00002_mirimage_o044_crf.fits"[0]" ASN
ASNPOOL = 'jw00623_20191106t132852_pool' / Name of the ASN pool
ASNTABLE= 'jw00623-o044_20191106t132852_spec3_001_asn.json' / Name of the ASN ta
(jwst_dev) …
```
> Jp 1130 Update to add level 3 asn table names to the products. 

- CHANGES.rst
- jwst/cube_build/blot_cube_build.py
- jwst/cube_build/cube_build.py
- jwst/cube_build/cube_build_step.py
- jwst/cube_build/cube_cloud.py
- jwst/cube_build/file_table.py
- jwst/cube_build/ifu_cube.py
- jwst/outlier_detection/outlier_detection_ifu.py
Fixed outlier detection to correctly call cube_build with the correct channels (MIRI) or gratings (NIRSPEC)
Fixed blot_cube_build.py to correctly blot the median sky cube back to the detector.
In blot_cube_build.py my first attempt was blot_overlap - this took way too long. So I modified the method and created blot_overlap_quick. I can probably delete blot_overlap but I left it in for now.
I think reviewing blot_overlap_quick is sufficient. 
David look at the weighting function in blot_overlap_quick and make sure that is what you want. Also when finding the overlap between the blotting sky and detector I did not search a radius but a distance in x and distance in y. We can change this if you prefer and change it to a radius between the centers (like in cube_build). I was just trying to …
> Outlier Detection and cube blotting in Calspec3

- CHANGES.rst
- jwst/datamodels/model_base.py
When saving `DataModel`s to FITS, there is a core header keyword that is set, `DATAMODL` with the name of the model. This is used as a very strong hint as to what model to create when the file is read back in. However, being part of the model's schema, `meta.model_type`, it is easy to change this value, potentially creating a file of one model type but `DATAMODL` indicates another.
This change simply forces `DATAMODL` to be the current model type on saving.
Note: This is a partial fix for issue [JP-1162](https://jira.stsci.edu/browse/JP-1162) / #4317
> Define DataModel.model_type and force that when saving

- jwst/regtest/conftest.py
- jwst/regtest/test_miri_image2.py
- Fix bug in `diff.report()`
- Use `Step.from_cmdline()` instead of `Image2Pipeline.call()`
> Update template MIRI Image2 regtest

- JenkinsfileRT_new
This will split out the running of the regression tests.  Currently when the 2nd kicks off, it wipes the results of the first on `jwcalibdev`, which makes debugging some issues more difficult.
The `JenkinsfileRT_new` will be run from a separate Jenkins instance (TBD).
> Split old and new regtest JenkinsfileRTs

- jwst/regtest/regtestdata.py
- jwst/regtest/test_infrastructure.py
This convenience method is used to get the remote association JSON file and then iteratively grabs all the members as well.
Resolves #4325
> Add RegtestData.get_asn() to get asn and members from Artifactory

- .codecov.yml
- .travis.yml
Hopefully this will give us a better per-PR codecov report.
> Add .codecov.yml to specify coverage flags unit, nightly, newnightly

- CHANGES.rst
- jwst/pipeline/calwebb_image2.cfg
- jwst/pipeline/calwebb_image2.py
We discovered this in the Hack Day today:
```
strun calwebb_image2.cfg input_rate.fits
```
produces a `_cal` and `_i2d` file for MIRI Imaging mode.  As expected, as this is the way SDP runs the pipeline.
But the following:
```
strun jwst.pipeline.Image2Pipeline input_rate.fits
```
produces only the `_cal` file.  And if we try to explicitly force writing out the resampled file:
```
strun jwst.pipeline.Image2Pipeline input_rate.fits --steps.resample.save_results=True
```
produces the `_cal` file and a `_resample` file, not the `_i2d` file.
From within python:
```
result = Image2Pipeline.call("input_rate.fits")
```
no files were written out, as expected, with the `_cal` product returned to `result` in memory.  But
```
result = Image2Pipeline.call("input_rate.fits", save_results=True)
``` …
> Make Image2Pipeline consistent across different instantiation methods

- JenkinsfileRT
- JenkinsfileRT_new
For some reason, the preferred syntax
```
pytest --ignore=jwst/regtest
```
is not working as a drop-in replacement for
```
ptyest -k "not regtest"
```
on Jenkins.  Not sure why, as it works fine running locally.  So I'm changing it back.  Also, specifying `--env=newdev` for the new test, which I'd overlooked before.
Both these bugs prevent our nightly regression tests from running properly.
> Fix pytest --ignore= bugs in JenkinsfileRT

- jwst/regtest/test_nirspec_image2.py
calwebb_image2 test using a NIRSpec imaging-mode exposure as input (in particular, EXP_TYPE='NRS_CONFIRM'). These kinds of exposures don't get resampled, so the only output is a _cal product, which is compared by the test.
Input and truth files have been uploaded to artifactory, at the locations specified in the test.
> JP-1181: NIRSpec calwebb_image2 regression test

- jwst/tests_nightly/general/miri/test_image2pipeline_1.py
Since we are using `call`, explicitly save the outputs.  Failed due to changes in #4333
> Fix MIRI Image2Pipeline regtest to save results

- jwst/regtest/test_nircam_wfs.py
A new test module that tests both the ``calwebb_wfs-image2`` and ``calwebb_wfs-image3`` pipelines on a pair of dithered NIRCam WFS&C images. The ``calwebb_wfs-image3`` test is performed twice, once with no refinement of the WCS-based image offsets and once with automatic refinement. Separate wfs-image3 ASN files are used for those tests, just to enable unique naming of the output products.
> JP-1183: wfs-image2 and wfs-image3 regression tests

- .coveragerc
- .travis.yml
- scripts/okify_regression_tests.py
- setup.py
Currently, we are inadvertently counting `test_*.py` files in our coverage, which of course, since they get run top to bottom in our test suite, get counted at 100%.  This excludes them from our coverage, so we are only covering production code.
**note: this will cause our coverge to drop from ~62% to ~52% for unit tests, as we are changing the denominator.**  😞 
Also some PEP8 cleanup and adjustment to our `flake8` script to keep it clean.
> Don't count tests in coverage

- jwst/regtest/test_lrs_slit_spec2.py
This is a new regtest for the ``calwebb_spec2`` pipeline applied to MIRI LRS fixed-slit data. It uses an ASN containing a total of 3 exposures, one of which is the primary science exposure and the other two are nodded (PATTTYPE='ALONG-SLIT-NOD') exposures designated as 'background' members. So this also tests the ``background`` step in the pipeline, where it has to average together the data from 2 background exposures and then do the subtraction.
All outputs from all steps are saved and tested in the comparison.
NOTE: While constructing and testing this test, it's been discovered that there must be a bug in the ``resample_spec`` step, such that when it's applied to these data, the resulting ``s2d`` image is filled with zeros. This obviously limits the usefulness of testing the …
> JP-1188: calspec2 regtest for MIRI LRS fixedslit

- jwst/regtest/test_lrs_slit_spec2.py
- jwst/regtest/test_nirspec_mos_spec2.py
New calspec2 regression test of a NIRSpec MOS exposure. Just copied data from an existing test in the old system. Reduced the number of source in the MSA metadata file to only 5, and also edited the stellarity values for 2-3 sources in the MSA metadata file so that they get treated as extended source (thus triggering the barshadow correction and different handling in photom and extract_1d). So it exercises a pretty good chunk of parameter space.
It save results from all intermediate steps and includes them in the comparisons.
Input and truth files have been uploaded to artifactory and I've confirmed that it runs fine locally.
> JP-1195: calspec2 regtest for NIRSpec MOS

- jwst/regtest/test_nirspec_fs_spec2.py
This test module applies the calspec2 pipeline to 3 different flavors of NIRSpec fixed-slit exposures:
1. A full-frame exposure, so all slits will be extracted and processed
2. An ALLSLITS subarray exposure, so all slits will be extracted and processed
3. A S400A1 subarray exposure on the NRS2 detector, so only 1 slit is processed
The test compares all 8 flavors of intermediate and final output products created by each pipeline run.
> JP-1189: NIRSpec FS spec2 regtests

- jwst/tests_nightly/general/nirspec/test_nirspec_steps_single.py
Remove test 1 (of 3) of the regtest that runs the ``master_background`` step on NIRSpec IFU data with a user-supplied master-background spectrum. It was used as a sanity check back when we were first developing the ``master_background`` step and is no longer required. The remaining two parts of the test are sufficient for checking for regressions in the ``master_background`` step itself. It also doesn't work correctly anymore, because NIRSpec IFU data can be in units of flux (MJy) if they're point source, while the test assumes everything is in surface brightness units.
> Remove old NIRSpec IFU masterbkg sanity check regtest

- jwst/regtest/test_miri_image.py
Regression tests that cover ``calwebb_detector1`` and ``calwebb_image2`` for a single MIRI imaging exposure, and then covers ``calwebb_image3`` for an ASN of 4 dithered MIRI images (simulated by MIRISim). All intermediate and final products of all 3 pipelines are checked in the tests.
The simulated images contain a pattern of 5 bright stars that are dithered to 2 different positions. The WCS is pretty accurate, hence the ``tweakreg`` step doesn't come up with any significant updates.
Resolves JP-1180 and #4348
> JP-1180: MIRI imaging regtests

- jwst/regtest/test_nircam_tsimg.py
New regression test that runs the ``calwebb_tso-image2`` and ``calwebb_tso3`` pipelines on a set of NIRCam TS imaging data. The input data are from a simulation from INS of a point source in the SUB64P subarray. I copied the simulated data into 2 uncal files taken from the DMS test suite that also correspond to TSIMG mode on the b1 detector (B module, short-wave detector 1). Processed the uncal's through ``calwebb_tso1``, and the resulting _rateints products are used as input to the ``calwebb_tso-image2`` test. The resulting _calints products are used as input to the ``calwebb_tso3`` test. Having 2 exposures (even though the data are identical) tests the capability of the level-3 routines to handle multiple exposures. The only level-3 product for TSO imaging mode is the photometry catalog …
> JP-1206: NIRCam TSImg tso2 and tso3 regtests

- jwst/regtest/test_niriss_soss.py
This provides ``calwebb_tso-spec2`` and ``calwebb_tso3`` regression tests for NIRISS SOSS mode data. It uses 2 segmented exposures, both of which are processed through ``calwebb_tso-spec2``, but only the results of the first one are checked by the test. Both resulting _calints products are then used as input to a ``calwebb_tso3`` test.
The data were built from some SOSS simulations we obtained a couple years ago from the NIRISS team, transplanting the data arrays into the results of a recent DMS run of the same data mode. It uses only 10 integrations per segment to keep run time reasonable and the actual data arrays are identical in both segment files. Only the INT_TIMES table in each segment makes it look like different integrations.
Input and truth files have been uploaded to …
> JP-1205: NIRISS SOSS level-2b and level-3 regtests

- jwst/assign_wcs/nircam.py
- jwst/assign_wcs/tests/test_nircam.py
- jwst/regtest/test_nircam_tsgrism.py
New regression test that performs ``calwebb_tso-spec2`` and ``calwebb_tso3`` processing on a NIRCam TSO grism (NRC_TSGRISM) exposure. It checks intermediate products from ``calwebb_tso-spec2``, as well as all final products from both pipelines.
The data were assembled from a recent DMS dataset that uses the same instrument setup, and imbedding simulated data into the SCI array. The assembled test data start at the _uncal level.
Note that this PR also includes a critical fix to the NRC_TSGRISM portion of the ``assign_wcs`` step. It had not yet been updated to switch from using the CRPIX1/CRPIX2 keyword values to determine the source location, to using the new XREF_SCI/YREF_SCI keywords instead. This was causing the wavelength array calculations to come out incorrectly, which subsequently …
> JP-1204: NIRCam TSGRISM regression test

- jwst/regtest/conftest.py
- jwst/regtest/test_nircam_image.py
This implements stages 1, 2 and 3 pipelines for Mirage-simulated NIRCam imaging dataset `jw42424001001`.
One `_uncal` file is processed through to the end of calwebb_image3.  The other 5 members of the association are processed from the `_rate` file through stage 2 and 3 pipelines.
Currently the dataset has the wrong pointing info, so the final `_i2d` mosaic doesn't look great.  Will resolve this with fixed input and truth data in the near future.
Also cleaned up the postmortem path handling, which should have no effect on functionality.
Test results:
```
$ pytest --bigdata --env=newdev test_nircam_image.py -v
============================ test session starts ============================
platform darwin -- Python 3.7.5, pytest-5.3.1, py-1.8.0, pluggy-0.13.1 -- …
```
> JP-1179: Create regression test for NIRCam image2 (plus stages 1 and 3)

- JenkinsfileRT_new
- jwst/regtest/test_nircam_coron3.py
This ports over the existing coron3 pipeline regression test to the new system with some data cleanup done - correct file names, `assign_wcs` run on the `_calints` files to get the new NIRCam distortion, clean out `extra_fits`, etc.
This dataset uses the no-longer-existing SUB320 subarray, but the actual data size is
```
1  SCI           1 ImageHDU        49   (158, 158, 33)   float32   
```
Because of this, it needs its own `psfmask` reference file override.
It would be nice to replace this data with something that is less cobbled-together and that uses a standard subarray.
Resolves #4399 / JP-1207
```
$ pytest --bigdata --basetemp=/Users/jdavies/scratch/ --env=newdev jwst/regtest/test_nircam_coron3.py -v
=================================== test session starts …
```
> Add NIRCam calwebb_coron3 regression test

- jwst/regtest/test_miri_image.py
- jwst/regtest/test_nircam_image.py
This fixes the `test_miri_image_stage3_catalog` test that is currently failing
https://plwishmaster.stsci.edu:8081/job/RT/job/JWST_RT_REFACTOR/93/testReport/junit/jwst.regtest/test_miri_image/_stable_deps__test_miri_image_stage3_catalog/
in the new regression test system because it is digging down into the noise of the maskbar to find sources and coming up with `NaN` for x and y centroids.  And of course `nan != nan` so the comparison fails.
The solution is to set the source catalog detection threshold higher to only detect the 5 simulated stars in the field.  It still detects a 6th non-star, but at least this blob has a centroid.
The truth file has already been updated on Artifactory.
```
$ pytest --bigdata --env=newdev jwst/regtest/ -k test_miri_image_stage3_catalog …
```
> Set source_catalog.snr_threshold=20 for MIRI/NIRCam image3 regtests

- jwst/regtest/test_niriss_ami3.py
Resolves #4398 and https://jira.stsci.edu/browse/JP-1208
New ``calwebb_ami3`` test for NIRISS AMI observations. The input association consists of 3 science target and 3 reference PSF target exposures. The datasets were constructed by using recent DMS B7.4 processing results for proposal jw00723 with simulated images from the old regtest embedded into them. Only 1 of the 3 exposure-level results (``ami_analyze`` step output) for each target is tested, while all source-level (combined) products are tested in comparisons.
> JP-1208: NIRISS AMI3 regression test

- CHANGES.rst
- jwst/combine_1d/combine1d.py
For each input spectrum, the array of corresponding pixel numbers in the output, combined spectrum is computed by using the inverse WCS function.  It is possible for some of these pixel numbers (probably only at an endpoint of the input spectrum) to be NaN due to the finite bounding box for the WCS.  A check for NaN was added.
While testing this change, another bug was uncovered.  In the section that tests for the possibility that there was no input data for some output pixel, the error estimate for flux was being assigned to the error estimate for surface brightness.  This has been fixed.
> JP-1152 Check whether the output pixel number is NaN

- jwst/regtest/test_nirspec_mos_spec3.py
Resolves #4403  and https://jira.stsci.edu/browse/JP-1212
``calwebb_spec3`` test on NIRSpec MOS data. Used 3-point dither pattern of simulated MOS images (for both detectors) and embedded the images in SDP files from jw00626 obs30. The MSA metadata file is chopped down to contain only 6 sources, 3 of which result in data on the NRS2 detector (all 6 have data on NRS1), with a mixture of point vs extended source designations and one dedicated background shutter (slitlet #8) thrown in for good measure. The 6 input _cal products result in 6 source-based results, each of which has a cal, crf, s2d, and x1d product. All 24 resulting products are tested.
Inputs and truth files have been uploaded to artifactory.
> JP-1212: NIRSpec MOS spec3 regtest

- jwst/regtest/test_nirspec_brightobj.py
Added a test for nirspec bright obj:
Regression test of calwebb_spec2 pipeline performed on NIRSpec fixed-slit data that uses the NRS_BRIGHTOBJ mode (S1600A1 slit).
Closes #4383
> JP-1200: REGTEST for NIRSpec brightobj

- jwst/regtest/conftest.py
- jwst/regtest/test_miri_lrs_slitless.py
This adds a new-style regression test that applies the "calwebb_tso-spec2" pipeline to a MIRI LRS exposure.  It is similar to the old [test_mirilrs2_slitless.py](https://github.com/spacetelescope/jwst/blob/master/jwst/tests_nightly/general/miri/test_mirilrs2_slitless.py), but additionally includes running the "calwebb_tso3" pipeline.
Addresses https://jira.stsci.edu/browse/JP-1202
> Add MIRI LRS slitless regression tests

- CHANGES.rst
- jwst/wfs_combine/wfs_combine.py
Fixes 2 identical regression test failures when using `scipy 1.4.1`.  The problem is that `scipy.signal.convolve` does not like convolving a `float32` with a `float64`.  The solution is to use `float64` for the internal computations.  Probably a good idea outside of the error from Scipy.
Also, the `smooth_image` function was a 2-liner and obscured more than it helped.  So I removed it.
Resolves #4430 / JP-1228
> Use float64 data arrays in convolve for wfs_combine

- jwst/regtest/test_miri_lrs_fs_spec3.py
Fixes JP-1211 and #4404
Local tests all pass
pytest --env=newdev --bigdata --basetemp=/Users/ddavis/src/JWST/develop/JP-1211/test_Jan06 ~/src/JWST/scsb/jwst/jwst/regtest/ -k test_miri_lrs_fs_spec3
...
================ 2 passed, 219 deselected, 2 warnings in 35.01s ================
This test should have better data as there are several warnings for "All-NaN slice encountered"
> JP-1211 MIRI LRS fixed-slit level3 regression test

- jwst/regtest/test_miri_lrs_dedicated_mbkg.py
- jwst/regtest/test_miri_lrs_masterbg_user.py
- jwst/regtest/test_miri_lrs_nod_masterbg.py
- jwst/regtest/test_miri_mrs_dedicated_mbkg.py
- jwst/regtest/test_miri_mrs_nod_masterbg.py
Tests of the `master_background` step for MIRI data have been created in the new regression test system, using input data copied from the old regtests.  There is a test with a user-supplied background file, a test with each of LRS and MRS data for the case of nodded exposures, and a similar pair of tests for the case of dedicated background exposures.
> JP-1225 MIRI master_background tests copied to new regtest

- jwst/extract_1d/extract.py
- jwst/regtest/test_nirspec_exceptions.py
- jwst/regtest/test_nirspec_fs_spec2.py
- jwst/regtest/test_nirspec_fs_spec3.py
- jwst/regtest/test_nirspec_ifu.py
- jwst/regtest/test_nirspec_mos_spec2.py
- jwst/regtest/test_nirspec_subarray.py
- jwst/regtest/test_nirspec_wcs.py
Add new NIRSpec regression tests to fill holes in coverage from the old set. In particular, this adds tests for FS and IFU WCS computations, as well as exceptions that are often encountered due to no data falling on the NRS2 detector (for some filter+grating combinations) and missing MSA meta data files.
A few existing test modules have been updated to change the directory paths of their input and/or truth files, just to better and more consistently organize the data on artifactory. All necessary changes to artifactory have been made.
A few more holes still need to be filled, including a test of the ``imprint`` step in ``calwebb_spec2``.
> JP-1219: Add missing NIRSpec regtests

- CHANGES.rst
- docs/jwst/assign_wcs/asdf-howto.rst
- jwst/ami/tests/test_ami_interface.py
- jwst/assign_wcs/tests/test_schemas.py
- jwst/datamodels/model_base.py
- jwst/datamodels/util.py
This turns off the memmap=True default when we open FITS files in datamodels. 
This is a potential bandaid fix for #4431/JP-1227.  It doesn't so much fix the problem as avoid the problem by not memory mapping.
Fixes #4431
Addresses some of #2887
> Make memmap=False be the default in datamodels

- jwst/regtest/test_nircam_tsgrism.py
Add a test of the ``set_telescope_pointing`` script to the new regression test system, applied to a NIRCam TSGRISM mode exposure. All old NIRCam regression tests are now covered in the new system. Fixes #4423 and JP-1220.
> Add NIRCam set_telescope_pointing regression test

- CHANGES.rst
- docs/jwst/extract_1d/description.rst
- jwst/extract_1d/extract.py
- jwst/extract_1d/ifu.py
For the case that the target is a point source and the instrument is NIRSpec or NIRISS (SOSS), the input units are megajanskys, and the background was being set to zero.  The extracted background is now divided by the pixel area (solid angle) to convert to units of surface brightness.
> Populate the background column

- jwst/regtest/test_miri_setpointing.py
A regression test of the ``set_telescope_pointing.add_wcs`` function applied to a MIRI level-1b imaging exposure. There aren't any pointing mnemonics in the EngDB that cover the OBSTIME of the test exposure, so no real values are derived for the pointing-related keywords (e.g. CRVALn), but there are valid SIAF entries for the aperture in use, which leads to realistic population of all the other WCS-related keywords (e.g. V2_REF, V3_REF, CRPIXn, CDELTn, etc.). This is a copy of the existing test in the old regtest system. There are more extensive unit tests of the ``add_wcs`` function.
Fixes #4457 and [JP-1235](https://jira.stsci.edu/browse/JP-1235)
> JP-1235: set_telescope_pointing test on a MIRI image

- CHANGES.rst
- jwst/lib/set_telescope_pointing.py
- jwst/regtest/test_miri_lrs_slitless.py
This should fix some regression test failures in the new system:
- Round S_REGION RA/Dec values in `set_telescope_pointing`
- Make `asn.sequence` repeatable in MIRI LRS slitless TSO regtest (it is a `Counter` class)
> Round S_REGION values in set_telescope_pointing

- jwst/regtest/test_miri_image_detector1.py
There is no existing test that creates and compares the ramp_fit optional output product, so modify an existing test to do so. Addresses JP-1236.
> Modify test to create and compare ramp_fit optional product.

- CHANGES.rst
- jwst/pipeline/calwebb_spec2.py
Updated the ``calwebb_spec2`` pipeline module to NOT save the ``cube_build`` result if the step is skipped. The ``extract_1d`` step is already fairly robust at handling situations where it doesn't get the right input (i.e. if ``cube_build`` has been skipped).
Fixes #3771 and [JP-840](https://jira.stsci.edu/browse/JP-840)
> JP-840: Handle cube_build skip in calwebb_spec2

- .travis.yml
Update default builds to python 3.7.6 and use 3.8.1 in the 3.8 build.
> Update python 3.7 and 3.8 versions for TravisCI

- CHANGES.rst
- jwst/pipeline/calwebb_tso3.py
Update the ``calwebb_tso3`` pipeline module to set "overwrite=True" when saving the photometric catalog results from either the ``tso_photometry`` or ``white_light`` steps. This avoids getting an ``astropy`` deprecation warning.
Fixes #4492 and [JP-1250](https://jira.stsci.edu/browse/JP-1250)
> JP-1250: Fix astropy overwrite warning

- CHANGES.rst
- docs/jwst/pipeline/calwebb_ami3.rst
- docs/jwst/pipeline/calwebb_coron3.rst
Removed the offending commas at the ends of some lines in the example ASN files included in the docs for the ``calwebb_coron3`` and ``calwebb_ami3`` pipelines. The presence of the trailing commas was causing an error when using the examples to run the pipeline.
Fixes #4495 and [JP-1252](https://jira.stsci.edu/browse/JP-1252)
> JP-1252: Fix formatting error calwebb_coron3 docs

- CHANGES.rst
- jwst/pipeline/calwebb_tso3.py
- jwst/white_light/white_light.py
The ``astropy.table.vstack`` function used in ``calwebb_tso3`` to merge multiple results from the ``white_light`` step was issuing a MergeConflict warning regarding the table meta attribute "number_of_integrations". The number of integrations was being set in the ``white_light`` step as it processed each exposure segment, but the value can vary from one segment to another. So when ``calwebb_tso3`` tried to merge all the results into a single output table, it had multiple values for that meta attribute - hence the warning.
This change moves the population of "number_of_integrations" out of the ``white_light`` step and puts it into ``calwebb_tso3`` after the final merged table has been created. The value is simply based on the total number of rows of data in the final table, which should …
> JP-1255: Fix calwebb_tso3 merge conflict warning

- CHANGES.rst
- jwst/extract_2d/grisms.py
For NIRCam TSO GRISM data, the variance arrays and the INT_TIMES table are now copied from input to output.  This was overlooked in previous updates.  The related issues are [JP-845](https://jira.stsci.edu/browse/JP-845) (GitHub #3784) to copy the variance arrays, and [JP-1249](https://jira.stsci.edu/browse/JP-1249) (GitHub #4489) to copy the INT_TIMES table.
For NIS_WFSS, NRC_WFSS, or NRC_TSGRISM data, the SLTSTRT1 and SLTSTRT2 keywords now give the start location of the 2-D cutout in the input image.  Previously, these keywords were 1.  The related issue is [JP-903](https://jira.stsci.edu/browse/JP-903) (GitHub #3872).
> Modifications to extract_2d for grism data

- jwst/combine_1d/combine1d.py
Remove cast to float 64 needed for early version of gwcs version < 0.11.
Unit tests pass, 
== 3 passed in 0.83s ==
Some minor issues in reg tests, all precision related e.g.
E              10 different pixels found (0.00% different).
e.g. 
E                 a> 20801.225
E                 b> 20801.504
HDU 10
E                 a> 1862.8383761319246
E                 b> 1862.8663302334871
E              1 different table data element(s) found (0.03% different).
> JP-1216 Remove the temporary cast to float64

- jwst/regtest/test_miri_image.py
- jwst/regtest/test_miri_lrs_slit_spec2.py
- jwst/regtest/test_miri_lrs_slitless.py
- jwst/regtest/test_miri_mrs.py
I updated the first test for the WCS - imager.
I am still working on the other modes and will add those to this PR soon. 
I just wanted to make sure this is all that was needed for WCS testing. 
@hbushouse @jdavies-st
> JP-1234: Add MIRI image2 pipeline wcs regression test

- jwst/regtest/test_nirspec_masterbackground.py
This PR adds NIRSpec MasterBackground tests in the new testing framework.
Fixes #4427 and JP-1226.
> JP-1226: Add nirspec masterbackground tests to the new test framework.

- CHANGES.rst
- jwst/datamodels/schemas/core.schema.yaml
Add the allowed NIRISS values for the dither PATTTYPE keyword to the core schema. Also just rearranged the existing enum list for PATTTYPE to break out the values by instrument/mode.
Fixes #4511 and [JP-1261](https://jira.stsci.edu/browse/JP-1261)
> Update PATTTYPE for NIRISS values

- jwst/regtest/conftest.py
- jwst/regtest/regtestdata.py
- Prevent Jenkins RT build failures when a test fails when pipeline is running and `rtdata.output` is either undefined or the file it refers to does not exist for some reason.
- Upload the `_okify.json` and `_rtdata.asdf` files to `jwst-pipeline-results` Artifactory repo for the OKify script to use.
> Only do post-regtest failure output upload if file exists

- CHANGES.rst
- jwst/photom/photom.py
- jwst/photom/tests/test_photom.py
Resolves #4185 
This PR adds `spectral_order` to the matched fields in the photom reference file for Nircam WFSS mode. 
In addition it implements a function `find_row` which returns a row from a FITS table that matches specific field values. This function replaces all `for-loops` used in the photom step. It's general enough that it can be used in other steps. It's advantage is that it is ~15 times faster. It also does error checking by requiring that only one row is returned.
> Nircam WFSS should use order to match photom info.

- CHANGES.rst
- jwst/photom/photom.py
Modified photom step to use also `spectral_order` when searching the reference table.
> use order to match photom information in tsgrism mode

- CHANGES.rst
- jwst/assign_wcs/nircam.py
- jwst/assign_wcs/tests/test_nircam.py
- jwst/extract_2d/grisms.py
- jwst/extract_2d/tests/test_grisms.py
- jwst/tso_photometry/tests/test_tso_photometry_step.py
- jwst/tso_photometry/tso_photometry_step.py
This PR adds exceptions in cases where `xref_xci` or `yref_sci` are missing in `assign_wcs.nircam.tsgrism`, `extract_2d.extract_tso_object`, and `tso_photomoetry.TSOPhotometryStep`.
Additionally, unit tests were added to test for cases where the exception should be raised.
Resolves #4239 / [JP-1129](https://jira.stsci.edu/browse/JP-1129)
> JP-1129: Add guard for xref/yref; add unit tests

- Jenkinsfile
- JenkinsfileRT
- JenkinsfileRT_dev
Updates `conda` version used by Jenkins jobs from 4.[6,7] to 4.8.2. 
Reason:
The `python` package installed by `conda-4.6.x` errors out claiming `libffi.so` is missing.
> Jenkinsfile*: set conda_ver to 4.8.2

- CHANGES.rst
- docs/jwst/extract_2d/main.rst
- jwst/extract_2d/grisms.py
This implements the fix that was determined for the wavelength scale of NIRCam TSGRISM exposures, as discussed extensively in [JP-1264](https://jira.stsci.edu/browse/JP-1264). The fix is to set the x-shift added to the subarray WCS transform to zero, which corresponds to the fact that the entire x-axis worth of data is included in the subarray extraction. Detailed notes have been included in the code, for future maintenance.
Also cleaned up some of the existing code comments that were originally copied from the `extract_grism_objects` routine, but did not apply (at least not directly) to the `extract_tso_object` routine.
Minor updates to the `extract_2d` docs are forthcoming.
Fixes #4513
> JP-1264: Fix TSGRISM WCS subarray offset

- CHANGES.rst
- docs/jwst/references_general/refpix_reffile.inc
- docs/jwst/refpix/description.rst
- jwst/datamodels/irs2.py
- jwst/datamodels/schemas/irs2.schema.yaml
- jwst/refpix/irs2_subtract_reference.py
The `alpha` and `beta` arrays from the `IRS2Model` reference file were used incorrectly.  The `alpha` arrays are now used for the reference output, and the `beta` arrays are now used for the interleaved reference pixels.
If there is a DQ array in the reference file, this will now be used to set some of the reference pixel values to zero.
> JP-954 Swap alpha and beta arrays; add support for a DQ extension

- jwst/regtest/conftest.py
- jwst/regtest/test_nirspec_wcs.py
This PR continues #4586 and adds some more commits that clean up the already existing NIRSpec IFU and FS tests:
- restructure the inputs on Artifactory to go by instrument/mode instead of `nirspec/test_wcs`
- use `rtdata.output` and `rtdata.truth` in the fixed-slit test so that it is testing something.  Before it was comparing truth to truth, which of course always passes.  It's been like this since Oct 2018.
- add an assertion helper for comparing grids mapped through `wcs` objects.
- make the breadcrumb postmortem more robust to the test run being aborted via Cntrl-C
Closes #4586
Resolves #3479
> Add NIRSpec MOS assign_wcs regression test

- CHANGES.rst
- jwst/refpix/irs2_subtract_reference.py
- jwst/refpix/tests/test_clobber_ref.py
Function `decode_mask` was sometimes returning an ndarray instead of a list.  The readout direction in `decode_mask` was incorrect.  The readout direction in the code that is now in `clobber_ref` was not taken into account for DQ table column `odd_even`.
A unit test for `clobber_ref` and one for `decode_mask` by itself were added.
> JP-1311 Fix bugs; add unit tests

- CHANGES.rst
- jwst/source_catalog/source_catalog_step.py
Update assign_wcs so that only the filename is saved in the keyword SCATFILE.
This is tested in test_niriss_wfss.py and the resulting keyword is listed as 
```
SCATFILE= 'nir_wfss_cat.ecsv'  / Output source catalog filename
```
Fixes JP-1201
Fixes #4387
> JP-1201 Remove full path from SCATFILE keyword

- jwst/datamodels/schemas/camera.schema.yaml
- jwst/datamodels/schemas/collimator.schema.yaml
- jwst/datamodels/schemas/disperser.schema.yaml
- jwst/datamodels/schemas/distortion.schema.yaml
- jwst/datamodels/schemas/distortion_mrs.schema.yaml
- jwst/datamodels/schemas/fore.schema.yaml
- jwst/datamodels/schemas/fpa.schema.yaml
- jwst/datamodels/schemas/ifufore.schema.yaml
- jwst/datamodels/schemas/ifupost.schema.yaml
- jwst/datamodels/schemas/ifuslicer.schema.yaml
- jwst/datamodels/schemas/msa.schema.yaml
- jwst/datamodels/schemas/ote.schema.yaml
- jwst/datamodels/schemas/specwcs.schema.yaml
- jwst/datamodels/schemas/specwcs_nircam_grism.schema.yaml
- jwst/datamodels/schemas/specwcs_niriss_grism.schema.yaml
- jwst/datamodels/schemas/wavecorr.schema.yaml
The schemas in datamodels were updated to use transform version 1.2.0. This fixes the problem with reading the Nirspec disperser reference file [seen here](https://travis-ci.org/spacetelescope/jwst/jobs/653521852#L1455) in our CI testing that uses dev versions of `asdf` and `astropy`.
The schemas in jwst/transforms will be dealt with separately.
> use transform-1.2.0 in schemas

- CHANGES.rst
- jwst/datamodels/model_base.py
- jwst/datamodels/tests/test_fits.py
- jwst/datamodels/tests/test_models.py
DataModel.update() method will now ignore `extra_fits` in the model that is providing the updated metadata, unless requested via keyword arg `extra_fits=True`.
Resolves #4591
> Make DataModel.update no longer update from extra_fits

- README.md
Does this seem a bit clearer.  I.e. it gives the 3 commands one has to run without having to bump back and forth from one area of the docs to another.
It seems people have been sometimes forgetting to `conda activate` the env, because the other 2 steps require interpolating MacOS or Linux filenames into the cut-and-paste commands.
> Clarify DMS install instructions

- jwst/regtest/conftest.py
- jwst/regtest/test_infrastructure.py
- jwst/regtest/test_miri_image.py
- jwst/regtest/test_miri_lrs_slitless.py
- jwst/regtest/test_nircam_image.py
- jwst/regtest/test_nirspec_fs_spec2.py
This allows the MIRI imaging test data with only 5 stars to be run through `tweakreg`.  Also:
- Set `rejection_threshold=200` in `JumpStep` for this dataset.  It was detecting lots of noise.
- break up the pipeline-running fixtures in the MIRI Imaging regtests to be a single fixture for each pipeline stage, so if I only want to run the ramp test, I don't have to run the stage 2 and 3 pipelines.  Makes everything more modular.
- Update the the `diff_astropy_tables` assertion helper to be more assertion-like.
- Clean up parametrization of `test_nirspec_fs_spec2`
> Turn on tweakreg in MIRI imaging regtest

- CHANGES.rst
- jwst/assign_wcs/nirspec.py
- jwst/datamodels/schemas/slitdata.schema.yaml
- jwst/extract_2d/nirspec.py
- jwst/msaflagopen/tests/test_msa_open.py
- jwst/transforms/models.py
Adds `Slit.source_ra` and `Slit.source_dec` for MOS data with values from the MSA metadata file.
These are saved to the headers of FITS SCI extensions as keywords `SRCRA` and `SRCDEC`.
> Add ``source_ra`` and ``source_dec`` to Slit MOS attributes

- CHANGES.rst
- jwst/datamodels/schemas/irs2.schema.yaml
In the schema for the data model `IRS2Model`, the DQ bintable extension has three columns.  Two of these columns had data type int16, but the reference files that were recently installed in CRDS have data type uint8.  The schema has been changed to agree with the reference files.
> JP-1324 Change data type of OUTPUT and ODD_EVEN columns to uint8

- CHANGES.rst
- jwst/regtest/test_nirspec_ifu.py
Update the regtest `test_nirspec_ifu` module to skip the `calwebb_spec3` test that uses a single exposure as input. It takes a long time to run and the results (only applies the `cube_build` and `extract_1d` steps) are completely redundant with the results of those steps applied in the `calwebb_spec2` test that uses the same exposure.
Also entered some missing updates to the change log.
> Skip the NIRSpec IFU single exposure calspec3 regtest

- CHANGES.rst
- jwst/datamodels/schemas/lev3_prod.schema.yaml
#4602 added definitions for the SCATFILE and TCATFILE keywords to core.schema, but failed to remove them from the lev3_prod.schema. This removes them.
Note that the entire lev3_prod.schema will be going away completely when when #4552 gets merged (eventually).
> Remove SCATFILE/TCATFILE from lev3 product schema

- README.md
Currently CRDS context "jwst-edit" is set at 585.
```
$crds list --contexts jwst-edit --mappings | grep pmap
jwst_0585.pmap
```
But the default is still 584 currently.
```
$ crds list --mappings | grep pmap
jwst_0584.pmap
```
Our regression tests ran with 585, so I'm including that in this build table.
> Update README DMS build version map for 0.15.0 [ci skip]

- jwst/regtest/test_nirspec_ifu_spec2.py
- jwst/regtest/test_nirspec_ifu_spec3.py
Split the spec2 and spec3 tests contained in `test_nirspec_ifu.py` into separate test modules, so that they can run in parallel, thus saving execution time for the whole regtest suite (these are the 2 longest running tests of all).
> Split NIRSpec IFU regtests

- jwst/datamodels/schema_editor.py
- scripts/schema_editor
Removed the use of the initialization file. This was way too confusing when running the task.
> Remove the init file usage. Way too confusing

- jwst/jump/tests/test_detect_jumps.py
For new jump step algorithm that flags neighboring pixels, added unit tests for multiprocessing, and adjacent cosmic rays. Minor whitespace changes. See JP-1298, GH issues #4481 and #4569, and GH PR #4297.
> Add unit tests for new jump step algorithm

- .codecov.yml
- JenkinsfileRT
Flags don't work properly right now in codecov (and haven't since we started using it).
https://docs.codecov.io/docs/flags#section-flags-in-the-codecov-ui
And it is making our coverage check not very useful, as it is comparing unit test coverage for a PR to the coverage from the unit tests plus regression tests (which is 20% higher).  Since the nightly tests run nightly, the first PR to be merged every day is being compared to the nightly coverage, not the previous unit test coverage, which always gives a big ❌ .
So this turns off reporting to codecov for nightly tests.  We should try to see if there's a different way to do this, because it would be handy to have this via a link.
Coverage of the regression tests can be found within the runs on `jwcalibdev` for now by running
```
$ …
```
> Remove codecov reporting on nightly flagged builds

- jwst/regtest/conftest.py
- jwst/regtest/test_infrastructure.py
A bug I introduced. Turns out `assert func()` where `func` doesn't actually return anything fails. 🙄 
Resolves issue we were seeing like the following:
```
diff_astropy_tables = <function diff_astropy_tables.<locals>._diff_astropy_tables at 0x1233048c0>
def test_foo(diff_astropy_tables):
table1 = "/Users/jdavies/scratch/test_nircam_image_run_detector1pipeline0/jw42424-o002_t001_nircam_clear-f444w_cat.ecsv"
table2 = "/Users/jdavies/scratch/test_nircam_image_run_detector1pipeline0/truth/jw42424-o002_t001_nircam_clear-f444w_cat.ecsv"
table1 = "/Users/jdavies/scratch/test_miri_image_rtdata_module0/det_dithered_5stars_f770w_cat.ecsv"
table2 = "/Users/jdavies/scratch/test_miri_image_rtdata_module0/truth/det_dithered_5stars_f770w_cat.ecsv"
>       assert diff_astropy_tables(table1, table2)
E …
```
> Fix bug in diff_astropy_tables

- Jenkinsfile
- pyproject.toml
This will allow building the sdist and wheel via
```
python -m pep517.build .
```
replacing
```
python setup.py sdist
python setup.py bdist_wheel
```
> Add build-backend to pyproject.toml so that pep517.build works

- scripts/okify_regtests
Updates the `okify_regtests` script to keep track of how many tests one needs to okify.  The new interface now shows `test n of m`:
```
———————————————————————————————————————————————————— test_full_run[multispec.schema.yaml] ———————————————————————————————————————————————————
jail = local('/data1/jenkins/workspace/RT/JWST/clone/test_outputs/popen-gw27/test_schema_editor0')
schema = 'multispec.schema.yaml'
run_editor_full = 'fixed/schemas_2020_02_29_00'
rtdata_module = {'input': '/data1/jenkins/workspace/RT/JWST/clone/test_outputs/popen-gw27/test_schema_editor0/keyword_db/nirspec.ifu.d...tor0/truth/multispec.schema.yaml',
'truth_remote': 'jwst-pipeline/dev/truth/test_schema_editor/multispec.schema.yaml'}
@pytest.mark.bigdata
@pytest.mark.parametrize(
'schema',
['container.schema.yaml', …
```
> Enumerate tests in okify_regtests script

- jwst/regtest/regtestdata.py
- jwst/regtest/test_infrastructure.py
- jwst/regtest/test_schema_editor.py
This makes `text_diff` an assertion helper for `pytest`.  The benefit here is that the diff output is now encapsulated in the `AssertionError` which means it will get formatted and stored properly for output. Also, it will be available for `okify_regtests`.
Previously the diff was redirected to stdout.
An example of what it now produces
```
>       assert text_diff(rt.output, rt.truth)
E       AssertionError: 
E       --- /private/var/folders/jg/by5st33j7ps356dgb4kn8w900001n5/T/pytest-of-jdavies/pytest-476/test_schema_editor0/fixed/schemas_2020_03_03_00/core.schema.yaml
E       +++ /private/var/folders/jg/by5st33j7ps356dgb4kn8w900001n5/T/pytest-of-jdavies/pytest-476/test_schema_editor0/truth/core.schema.yaml
E       @@ -620,11 +622,11 @@
E                  readpatt:
E …
```
> Make text_diff an assertion helper

- CHANGES.rst
- docs/jwst/stpipe/user_step.rst
- jwst/datamodels/container.py
- jwst/stpipe/pipeline.py
- jwst/stpipe/step.py
Resolves #4607/JP-1322
Changes include:
- Using only the first science member of an association for CRDS STEPPARS determination
- For pipelines, only open the `DataModel` once and pass it to each step for STEPPARS determination.
> JP-1322: Use only a single member of an association for CRDS STEPPARS checking

- CHANGES.rst
- jwst/extract_1d/extract.py
The two sections in `extract_1d` where the wcs function was called in a loop over pixels have been removed, leaving just the calls to `wcs` with array arguments.
This also resolves JP-880, GitHub #3838.  Function `copy_keyword_info` is now called in two more sections, covering `ImageModel`, `DrizProductModel`, `CubeModel`, `SlitModel`.  `copy_keyword_info` also copies new slit attributes `source_ra` and `source_dec`.
> JP-1340 Pixel-by-pixel calls to wcs removed from extract_1d

- CHANGES.rst
- jwst/associations/lib/rules_level3.py
Update the logic for the Asn_IFU so that entries with the PATTTYPE keyword with values of 2-point-nod, 4-point-nod, or along-slit-nod are included in the level 3 associations. 
Closes #4676
> JP-1352 Update asn rules to include nodded observations

- CHANGES.rst
- docs/jwst/srctype/description.rst
- jwst/extract_2d/nirspec.py
- jwst/srctype/srctype.py
- jwst/srctype/tests/test_srctype.py
Update the `srctype` step to use a default value of EXTENDED for NIRSpec IFU exposures, same as MIRI MRS. Added a unit test and updated docs.
Fixes #4652 / [JP-1339](https://jira.stsci.edu/browse/JP-1339) 
Fixes #4623 / [JP-1330](https://jira.stsci.edu/browse/JP-1330)
> JP-1339: Update default SRCTYPE for NRS_IFU to EXTENDED

- jwst/datamodels/schemas/multispec.schema.yaml
- jwst/extract_1d/extract.py
For WFSS and NRC_TSGRISM data, don't try to determine the pixel location of the target spectrum from the wcs.  Also, for NRS_BRIGHTOBJ data, leave `slitname` set to 'NRS_BRIGHTOBJ', rather than changing it to the actual slit name, 'S1600A1'.
> JP-1359 Two recent changes to extract_1d were backed out

- CHANGES.rst
- jwst/associations/lib/rules_level2b.py
Updated level 2 asn rules to exclude dark files. 
All the association tests pass. 
............s                                                            [100%]
==== 56 passed, 12 skipped, 303 deselected, 2 xfailed in 1310.24s (0:21:50) ====
closes #4668
> JP-1344 Exclude dark files from associations

- JenkinsfileRT
- JenkinsfileRT_dev
This will print to the build log the pmap that `jwst-edit` points to.
```
$ echo "CRDS_CONTEXT = $(crds list --contexts jwst-edit --mappings | grep pmap)"
CRDS_CONTEXT = jwst_0587.pmap
```
> Echo CRDS context in regression test build logs

- docs/jwst/assign_mtwcs/index.rst
- docs/jwst/assign_mtwcs/main.rst
- docs/jwst/package_index.rst
- jwst/assign_mtwcs/__init__.py
- jwst/assign_mtwcs/assign_mtwcs_step.py
- jwst/assign_mtwcs/moving_target_wcs.py
- jwst/assign_wcs/util.py
- jwst/datamodels/schemas/core.schema.yaml
- jwst/datamodels/schemas/wcsinfo.schema.yaml
- jwst/lib/exposure_types.py
- jwst/lib/suffix.py
- jwst/pipeline/assign_mtwcs.cfg
- jwst/pipeline/calwebb_image3.py
- jwst/pipeline/calwebb_spec3.py
Resolves #4649
This is a working skeleton of the step - to provide context for questions.
The input is an association and the output is a `ModelContainer`. Is this OK?
The association is read into a `ModelContainer` and each model in the container is modified in place.
*Questions:* 
- The step iterates over `ModelContainer._models`. Is there a better way to do this, i.e. not using private variables?
- When I run the step on the command line it creates 4 new files on disk named `mt_asn_0_assign_mtwcs.fits`. What am I doing wrong or is this expected?
- What keywords define an exposure as a moving target (other than `MT_RA` and `MT_DEC`)?
(EDIT: I found `model.meta.target.type` with a possible value of `moving`)
> Add a step generating WCS for a moving target

- CHANGES.rst
- jwst/associations/lib/rules_level2_base.py
Add default values for the asn header file when using --rule DMSLevel2bBase. This matches what is done when constructing associations using the default DMS_Level3_Base rules.
All the regression tests pass, 
==== 56 passed, 12 skipped, 303 deselected, 2 xfailed in 1352.97s (0:22:32) ====
This closes #4720
> Jp 1380 Update asn_from_list to have default values in the level 2 asn header

- CHANGES.rst
- docs/jwst/master_background/arguments.rst
- docs/jwst/outlier_detection/arguments.rst
- docs/jwst/outlier_detection/index.rst
- docs/jwst/outlier_detection/outlier_detection.rst
- docs/jwst/references_general/drizpars_reffile.inc
- docs/jwst/references_general/drizpars_selection.inc
- docs/jwst/resample/arguments.rst
- docs/jwst/resample/index.rst
- docs/jwst/resample/reference_files.rst
- docs/jwst/source_catalog/arguments.rst
- docs/jwst/tweakreg/README.rst
- jwst/source_catalog/source_catalog_step.py
Update the documentation for several steps, due to missing info about step arguments.
Fixes #4714 / [JP-1373](https://jira.stsci.edu/browse/JP-1373)  - resample arguments
Fixes #4713 / [JP-1374](https://jira.stsci.edu/browse/JP-1374)  - outlier_detection arguments
Fixes #4712 / [JP-1375](https://jira.stsci.edu/browse/JP-1375)  - tweakreg arguments
Fixes #4716 / [JP-1376](https://jira.stsci.edu/browse/JP-1376)  - source_catalog arguments
Fixes #4715 / [JP-1377](https://jira.stsci.edu/browse/JP-1377)  - master_background arguments
In addition to updating the argument list for `resample`, docs describing the `drizpars` reference file were also added.
One unused argument ("output_ext") was removed from the spec list in the `source_catalog` step.
> JP-1373: Documentation updates for step arguments

- jwst/assign_wcs/tests/test_wcs.py
The 1 deg difference in the failing test is due to CDELT=1.
> fix test - should compare 0-based coordinates

- jwst/regtest/test_schema_editor.py
- jwst/source_catalog/source_catalog_step.py
Replace the `source_catalog` `output_ext` param that was mistakenly removed in #4723 and causing 2 regtest to fail due to the output catalog file having the default ".fits" extension, instead of ".ecsv".
Also updated the test_schema_editor regtest code to account for the fact that #4552 replaced the meta data formerly in `slitdata.schema` with the new schema `slitmeta.schema`.
> Fix failing reg tests

- jwst/assign_wcs/tests/test_miri.py
- jwst/assign_wcs/tests/test_nircam.py
- jwst/assign_wcs/tests/test_nirspec.py
- jwst/assign_wcs/tests/test_wcs.py
- jwst/associations/tests/data/rules_level3_set1.py
- jwst/associations/tests/data/rules_level3_set2.py
- jwst/associations/tests/test_asn_names.py
- jwst/associations/tests/test_level2_basics.py
- jwst/associations/tests/test_level3_spectrographic.py
- jwst/background/tests/test_background.py
- jwst/cube_skymatch/skycube.py
- jwst/datamodels/schema_editor.py
- jwst/datamodels/tests/test_wcs.py
- jwst/lib/suffix.py
- jwst/skymatch/skymatch.py
- jwst/transforms/tests/tests.py
- jwst/wiimatch/lsq_optimizer.py
- jwst/wiimatch/match.py
This fixes `DeprecationWarnings` produced by `numpy` and `python` that we've been seeing.
```
/data1/jenkins/workspace/RT/JWST/clone/jwst/skymatch/skymatch.py:235: DeprecationWarning: invalid escape sequence \ 
"""
/data1/jenkins/workspace/RT/JWST/clone/jwst/wiimatch/match.py:173: DeprecationWarning: invalid escape sequence \s
"""
/data1/jenkins/workspace/RT/JWST/clone/jwst/wiimatch/lsq_optimizer.py:171: DeprecationWarning: invalid escape sequence \s
"""
```
```
jwst/lib/suffix.py:330
/data1/jenkins/workspace/RT/JWST/clone/jwst/lib/suffix.py:330: DeprecationWarning: invalid escape sequence \.
fpath, basename_regex='[^_].+\.py$', path_exclude_regex='tests'
```
```
jwst/regtest/test_schema_editor.py::test_limit_datamodels_from_file …
```
> Fix string escape and assert_allclose deprecations

- setup.py
The newest version of Pytest `5.4.1` broke `--basetemp` when used in conjunction with `pytest-xdist`.
See https://github.com/pytest-dev/pytest/issues/6987
This PR pins it for now.  This will fix the issue of failed test artifacts not being pushed to Artifactory (and thus tests not being able to be OKified).
> Pin pytest<=5.3.5 because --basetemp is broken

- jwst/datamodels/container.py
- jwst/stpipe/step.py
- jwst/stpipe/tests/steps/__init__.py
- jwst/stpipe/tests/test_input.py
- jwst/stpipe/tests/test_logger.py
- jwst/stpipe/tests/test_saving.py
- jwst/stpipe/tests/test_step.py
- setup.cfg
This PR resolves `ResourceWarning`s triggered by unclosed files over the course of some pipeline runs. A call to `closeout` was added to the end of `Step.run` to ensure that inputs were properly closed. In addition, a simple `close` method was added to `ModelContainer` in order to close models in the container. 
Resolves #4662 / [JP-1342](https://jira.stsci.edu/browse/JP-1342)
> JP-1342 Fix unclosed file warnings

- setup.py
Pinning `tweakwcs==0.5.3` as it has been until yesterday.  Yesterday we unpinned it, ran the regression tests using `tweakwcs 0.6.1` and saw errors in our regression tests.  The MIRI data failed.
https://plwishmaster.stsci.edu:8081/job/RT/job/JWST/595/testReport/junit/jwst.regtest/test_miri_image/_stable_deps__test_miri_image3_i2d/
Any ideas @mcara?
The NIRCam imaging test showed differences using the new version of `tweakwcs`
https://plwishmaster.stsci.edu:8081/job/RT/job/JWST/595/testReport/junit/jwst.regtest/test_nircam_image/_stable_deps__test_nircam_image_stage3_i2d/
But this I think is just a difference noted in the accuracy of the affine transform fit in the newer version?  The combined image looks good.
We can unpin this when the issues are sorted.  Maybe when #4542 is merged.
> Repin tweakwcs==0.5.3

- .gitignore
- jwst/assign_wcs/tests/test_schemas.py
- jwst/background/tests/test_background.py
- jwst/cube_skymatch/cube_skymatch_step.py
- jwst/datamodels/container.py
- jwst/datamodels/dynamicdq.py
- jwst/datamodels/model_base.py
- jwst/datamodels/properties.py
- jwst/datamodels/tests/test_fits.py
- jwst/datamodels/tests/test_history.py
- jwst/datamodels/tests/test_models.py
- jwst/datamodels/tests/test_open.py
- jwst/datamodels/tests/test_schema.py
- jwst/datamodels/util.py
- jwst/stpipe/tests/steps/__init__.py
- jwst/stpipe/tests/test_input.py
- jwst/stpipe/tests/test_logger.py
- jwst/stpipe/tests/test_pipeline.py
- jwst/stpipe/tests/test_saving.py
- jwst/stpipe/tests/test_step.py
- setup.cfg
This PR is for a branch started a year ago.  I've rebased it and added a few fixes to it, so it is complimentary to #4731 I think.  @jwhite3 have a look.  I don't think it solves the regression test pipeline issues, but it does resolve the unit test issues and allows turning on the `pytest-openfiles` plugin.
Resolves #4737
> Resolve open file issues in unit tests

- setup.cfg
Turning this on in #4740 caught some open file issues in our regression tests.  This turns off the check.  Will fix the pipeline or step open file issues and only then turn on the check in setup.cfg.
> Disable pytest-openfiles in setup.cfg

- jwst/lib/tests/engdb_mock.py
- jwst/regtest/test_nircam_tsgrism.py
Removes unnecessary dependency on any specified ENG_BASE_URL when using the mocking library.
WIP #4757 
WIP [JP-1397](https://jira.stsci.edu/browse/JP-1397)
> Remove dependency on specified eng db url when using the engdb mock

- CHANGES.rst
- jwst/stpipe/cmdline.py
- scripts/strun
PR #4468 removed exception traceback printing from `strun` to avoid double tracebacks on failure. However, the side effect is that any error happening outside of step processing now went unreported, causing silent failures. In particular, config file errors would cease processing without reason.
This refactor restores `strun` but removes the traceback from `cmdline.step_from_cmdline`, ensuring that all errors get reported and avoiding the double traceback.
> JP-1393 Re-enable exeption tracebacks from strun for issues outside step processing

- jwst/regtest/test_miri_lrs_slit_spec3.py
This a modification of the existing MIRI LRS fixed-slit `calwebb_spec3` regression test. The overall structure of the test is the same (input is an ASN containing 4 nodded exposures). The old input cal files had zero-filled SCI arrays. The new inputs are from a set of simulated exposures created by the MIRI team and have had their TARG_RA/DEC and RA/DEC_REF values tweaked to match the actual locations of the (nodded) spectrum in each exposure. It also takes advantage of the recent fix (#4552) that results in spectra showing up in LRS fixed-slit resampled data products.
In summary, this is a drop-in replacement for the existing test using data files with good data in them. All inputs and truth files have been uploaded to artifactory and tested locally.
> Update MIRI LRS fixed-slit spec3 regtest

- CHANGES.rst
- jwst/outlier_detection/outlier_detection_spec.py
- jwst/resample/resample.py
- jwst/resample/resample_spec.py
- jwst/resample/tests/test_resample_spec.py
This PR adds metadata blending to `resample_spec` and therefore the `Spec3Pipeline`
Resolves #4724 / [JP-1383](https://jira.stsci.edu/browse/JP-1383)
> Add metadata blending to resample_spec

- jwst/resample/resample_spec_step.py
This PR fixes a bug where for input NIRSpec data to `ResampleSpecStep`, the `blendheaders` parameter was not being updated correctly, resulting in blending occurring for all NIRSpec inputs.
In addition, empty ERR extensions created during blending are explicitly removed at the end of `ResampleSpecStep`
Resolves  #4773 / [JP-1402](https://jira.stsci.edu/browse/JP-1402)
> Add blendheaders keyword to drizpars; remove err array

- CHANGES.rst
- README.md
- docs/jwst/references_general/apcorr_reffile.inc
- docs/jwst/references_general/apcorr_reffile.rst
- docs/jwst/references_general/apcorr_selection.inc
- docs/jwst/references_general/apcorr_selection.rst
- docs/jwst/references_general/references_general.rst
- jwst/datamodels/__init__.py
- jwst/datamodels/apcorr.py
- jwst/datamodels/schemas/mirlrs_apcorr.schema.yaml
- jwst/datamodels/schemas/mirmrs_apcorr.schema.yaml
- jwst/datamodels/schemas/niswfss_apcorr.schema.yaml
- jwst/datamodels/schemas/nrcwfss_apcorr.schema.yaml
- jwst/datamodels/schemas/nrsfs_apcorr.schema.yaml
- jwst/datamodels/schemas/nrsmos_apcorr.schema.yaml
- jwst/regtest/test_nirspec_fs_spec2.py
New datamodels schemas for spectroscopic aperture correction reference files, as specified in [JP-1049](https://jira.stsci.edu/browse/JP-1049). Still need to add the new models to the reference file docs.
Fixes #4768 / [JP-1401](https://jira.stsci.edu/browse/JP-1401)
> JP-1401: Spectroscopic APCORR data models

- CHANGES.rst
- jwst/exp_to_source/exp_to_source.py
This PR resolves #4725 / [JP-1382](https://jira.stsci.edu/browse/JP-1382) where results from `exp_to_source` did not include any header information from the original exposures. Now, each new `MultiExposureModel` will contain header information from the input `MultiSlitModels`
> JP-1382: Add updates to source models to include header info

- jwst/ramp_fitting/utils.py
In the midst of a conversation with @jdavies-st about DQ flags, I made a search through this codebase for cases where we check for flag presence with `==` instead of `&`.  This is the one example that turned up.
> Use bitwise operator to check for presence of flag

- README.md
Reorganize and rewrite the installation instructions in the README, in an effort to clear up some ambiguities and unanswered questions that many installers had. More information is provided as to why the different methods are the way they are, while at the same time attempting to make all of them as consistent as possible, in order to reduce confusion. A complete set of commands is included for each method, so that folks don't have to jump around looking for different pieces that make up the whole process.
> Rewrite README installation instructions

- JenkinsfileRT
The designated macos build node that allows the environment snapshot to be composed for that OS is offline due to a power failure. Disable that build configuration until it can be brought back online, or until a more graceful timeout behavior can be implemented.
> Temporarily disable macos build config

- requirements-sdp.txt
- setup.py
This PR prevents jwst from pulling in the as-yet-unreleased asdf 2.6.  That release will include a change to validator behavior that will require a small update to jwst/datamodels/fits_support.py.
@jdavies-st did I do the right thing in requirements-sdp.txt?
> Lock down asdf version to < 2.6

- setup.cfg
We need to turn this off for now until we can debug why our regression tests are leaving behind open files when they fail via `FITSDiff`.
> Turn off pytest-openfiles plugin in setup.cfg

- .travis.yml
- jwst/regtest/conftest.py
- setup.cfg
This should solve our issues with FITSDiff leaving behind open files when a difference is found.
Also, this updates the patch versions of python used in TravisCI.
> Turn off memmap for FITSDiff in regtests

- docs/jwst/flatfield/arguments.rst
- docs/jwst/flatfield/main.rst
- docs/jwst/linearity/description.rst
Update the flat-field docs to move/remove old NIRSpec info from the non-NIRSpec section of the docs. Also updated the name of the argument used to save the on-the-fly flat as used in the code. Update the linearity docs to make it explicit that MIRI data do not get bias subtracted before doing linearity correction (or ever).
Fixes #4524 / [JP-1268](https://jira.stsci.edu/browse/JP-1268)
Fixes #4526 / [JP-1271](https://jira.stsci.edu/browse/JP-1271)
> Update flatfield and linearity docs

- CHANGES.rst
- jwst/datamodels/schemas/core.schema.yaml
- jwst/datamodels/schemas/keyword_readpatt.schema.yaml
Add new entries to the READPATT enum list for the new MIRI patterns FASTGRPAVG[8,16,32,64] as outlined in [JSOCINT-367](https://jira.stsci.edu/browse/JSOCINT-367).
Also finally updated the comment for the CHANNEL keyword, which was hardwired to refer to NIRCam, even though it's also used for MIRI. This change has been requested for a while. Unfortunately this is going to cause many, many regtest failures. Thank goodness for `okify_regtests`.
Fixes #4718 / [JP-1379](https://jira.stsci.edu/browse/JP-1379)
> JP-1379: Update READPATT keyword allowed values

- CHANGES.rst
- jwst/pipeline/calwebb_detector1.py
Updated the detector1 pipeline to explicitly copy the variable with the data to a new name, close and then delete the old variable before calling the next step in the pipeline. Monitoring the amount of swap memory used is shows that this decreased significantly over the original pipeline processing.
> JP-1389 Reduce detector1 pipeline memory footprint

- scripts/okify_regtests
Allows one to do OKifying from a different job other than RT/JWST.  Mostly
useful for OKifying from a branch other than master run under a different
job, such as jdavies-dev or eisenhamer-dev.
> Add --job-name option to okify_regtests script

- docs/jwst/references_general/abvega_offset_reffile.inc
- docs/jwst/references_general/abvega_offset_selection.inc
- docs/jwst/references_general/references_general.rst
- jwst/datamodels/__init__.py
- jwst/datamodels/abvega_offset.py
- jwst/datamodels/schemas/abvega_offset.schema.yaml
- jwst/datamodels/tests/data/nircam_abvega_offset.asdf
- jwst/datamodels/tests/test_models.py
This PR adds new imaging-mode Vega magnitude offsets (from AB magnitudes) reference file data models: `FgsImgVegaMagOffsetModel`, `MirImgVegaMagOffsetModel`, `NrcImgVegaMagOffsetModel`, and `NisImgVegaMagOffsetModel`.
The JWST Photometry Working Group (JPWG) has requested both AB and Vega magnitudes in the source catalog.  These new reference files contain a table of the offsets to convert from AB mag to Vega mag for each filter.
There should be only one reference file of this type for each instrument.  Because the level-3 resampled/combined `i2d` image may represents the combination of several detectors, there does not need to be a separate reference file for each detector.  The selectors for each instrument are:
* FGS:  None (it's a single number)
* NIRCam, NIRISS:  `filter`, `pupil`
* …
> Add datamodels for reference files containing AB to Vega mag offsets

- CHANGES.rst
- jwst/wfs_combine/wfs_combine.py
- jwst/wfs_combine/wfs_combine_step.py
DMS reports archive issues with WaveFront Sensing `wfscmb` products due to the fact that the ASNTABLE keyword in the level-3 `wfscmb` product is still a copy of the level-2 ASN table name used to create the input `cal` product. This update sets the ASNTABLE keyword value in the output product from the `wfs_combine` step to the name of the level-3 ASN file used as input to the processing.
Also cleaned up a bunch of little pep8 cosmetic issues (totally benign) and added a few more comments to the code here and there.
Fixes #4848 / [JP-1414](https://jira.stsci.edu/browse/JP-1414)
> JP-1414: Update ASNTABLE in wfscmb products

- CHANGES.rst
- jwst/resample/resample_step.py
Updated the resample step module to by default reject all pixels with DQ flags of NON_SCIENCE, in addition to DO_NOT_USE. This is especially necessary for MIRI Imaging exposures, where the portion of the detector not covered by direct images (e.g. the LRS and 4QPM areas) is flagged as NON_SCIENCE.
Fixes #4850 / [JP-1415](https://jira.stsci.edu/browse/JP-1415)
> JP-1415: Update resample to reject NON_SCIENCE pixels

- docs/jwst/source_catalog/arguments.rst
- docs/jwst/source_catalog/main.rst
- docs/jwst/source_catalog/reference_files.rst
- jwst/pipeline/source_catalog.cfg
- jwst/pipeline/tests/data/cfgs/source_catalog.cfg
- jwst/source_catalog/source_catalog.py
- jwst/source_catalog/source_catalog_step.py
This PR represents a complete rewrite of the source catalog step to incorporate aperture photometry (including aperture corrections) and other source properties as requested by the JWST Photometry Working Group (JPWG) in https://jira.stsci.edu/browse/JP-645.  This PR also closes https://jira.stsci.edu/browse/JP-1368.  The source catalog now contains 52 properties for each source.
The JPWG has not yet determined an algorithm for the `is_star` property, and thus that column contains NaN values.  As a result of this, the aperture-corrected "total" flux and magnitude columns are also set to NaN values because aperture-corrected photometry is only appropriate for stars. 
Also, after discussion with the CALWG, it was decided to set all photometric errors to NaN because the resampled `i2d` data …
> JP-1368:  Update source catalog step to include aperture photometry and other properties

- JenkinsfileRT
- JenkinsfileRT_dev
PR #4819 requires the use of new apcorr ref files that are currently only available on the CRDS test server, in context 595, so I'm temporarily updating the regtest environment to use those. Will revert once these are available on the regular crds ops server.
> Setup regtests to use crds-test and 0595 context

- jwst/refpix/tests/test_refpix.py
Reduces runtime (and memory usage) on my machine from
```
========== 17 passed, 4 warnings in 28.00s ==========
```
to
```
========== 27 passed, 4 warnings in 12.49s ==========
```
There are more tests because the final test is refactored to be parametrized by detector instead of having a loop within the test.
> Reduce runtime of refpix unit tests

- jwst/regtest/test_miri_image.py
- jwst/regtest/test_nircam_image.py
- jwst/regtest/test_nircam_mtimage.py
Temporarily modify the NIRCam and MIRI image regtests to override the abvega_offset ref file used by source_catalog until they're available in CRDS. Copies of the ref files have been added to the appropriate artifactory directories.
Will revert once the ref files are in CRDS.
> Update NIRCam and MIRI image regtests to override abvega

- requirements-dev.txt
It would be good to be testing against `crds` master in our dev builds on TravisCI (allowed failure) and Jenkins RT.
> Add crds to requirements-dev.txt

- CHANGES.rst
- jwst/pipeline/calwebb_spec3.py
Updated the `calwebb_spec3` pipeline module to update the ASNTABLE keyword value in all input models, so that the updated value gets propagated to all output products.
Fixes #4863 / [JP-1419](https://jira.stsci.edu/browse/JP-1419)
> JP-1419: Update ASNTABLE in all calspec3 products

- jwst/regtest/conftest.py
Comment out the comparison of table meta data in `diff_astropy_tables`, because at least some tables (like the new _cat.ecsv table from `source_catalog`) include entries giving code versions, which change frequently and lead to unnecessary failures. Need to enhance the table meta comparison to allow for specification of which entries to compare.
> Disable regtest table comparisons of meta data [skip ci]

- jwst/pipeline/calwebb_spec3.py
#4865 introduced a bug, which this fixes. Variable `result` has no meta data anymore once it's gone through the branch for inputs that get resampled, so we have to use the table_name from the original input.
> Fix a calspec3 bug introduced in PR4865 [skip ci]

- jwst/regtest/test_infrastructure.py
- jwst/resample/resample_spec_step.py
Yet another update needed in order to get the ASNTABLE keyword inserted and updated into `calwebb_spec3` products. For whatever reason, the creation of the `resample_spec` output model does not get the ASNTABLE keyword carried over into it from the inputs, so this change explicitly populates ASNTABLE in the resampled model before returning from `resample_spec`. This succeeds in getting the keyword into the `s2d` products and also then propagates into subsequent `x1d` products (like it should).
Also xfail the `diff_astropy_tables` test on meta data, because the meta comparison has been temporarily deactivated.
Most of the changes to `resample_spec_step` are purely cosmetic (just to add some comments and make the code blocks a little more readable by eye). The only substantive change is …
> Update ASNTABLE in resample_spec products

- JenkinsfileRT
- JenkinsfileRT_dev
Update regtest setup files to now point to crds context 606 on the test server, in order to pick up new MIRI RSCD ref file.
> Update regtest setup to use crds-test 606 [skip ci]

- setup.cfg
This fix ignores pytest collection errors we've seen with the recently released `pytest-doctestplus 0.6` which now raises a collection error if modules in the repo are not importable.  This is probably good behavior, but we have several modules in the repo that are not importable currently:
```
================================================================= ERRORS =================================================================
__________________________________________________ ERROR collecting docs/exts/numfig.py __________________________________________________
docs/exts/numfig.py:1: in <module>
from docutils.nodes import figure, caption, Text, reference, raw, SkipNode, Element
E   ModuleNotFoundError: No module named 'docutils'
______________________________________________ ERROR …
```
> Ignore doctestplus import errors in ramp_fit

- JenkinsfileRT
- JenkinsfileRT_dev
Context 606 has empty filteroffset rmap entries for nircam and niriss, which breaks the cal code. Backing down to 605.
> Change RT crds context to 605

- jwst/regtest/test_miri_image.py
- jwst/regtest/test_nircam_image.py
- jwst/regtest/test_nircam_mtimage.py
Fix the name of the override param in calimage3  regression tests from abvega_offset to abvegaoffset, now that the ref file name has changed.
> regtest: fix override abvegaoffset name

- jwst/assign_wcs/util.py
- jwst/lib/set_telescope_pointing.py
- jwst/lib/tests/test_fgs_pointing.py
- jwst/lib/tests/test_set_telescope_pointing.py
- jwst/resample/resample_utils.py
This PR refactors `wcs_from_footprints` and some functions that it depends on to utilize the `wcs` object from `refmodel` rather than using FITS-dependent keywords. 
Resolves #3250
Resolves #3900 / [JP-921](https://jira.stsci.edu/browse/JP-921)
Resolves #4784
> Refactor wcs_from_footprints to use gwcs.WCS objects instead of FITS keywords

- CHANGES.rst
- docs/jwst/datamodels/metadata.rst
- docs/jwst/srctype/description.rst
- jwst/datamodels/schemas/core.schema.yaml
- jwst/datamodels/schemas/multispec.schema.yaml
- jwst/datamodels/schemas/slitmeta.schema.yaml
- jwst/extract_1d/extract.py
- jwst/pipeline/calwebb_tso3.py
- jwst/srctype/srctype.py
- jwst/srctype/srctype_step.py
Update all necessary datamodel schemas to add the new keyword SRCTYAPT to the primary header and move the SRCTYPE keyword to the SCI and EXTRACT1D headers. Also update the `srctype` step to use SRCTYAPT as input and SRCTYPE as output, with lots of allowances for old datasets that don't have the SRCTYAPT keyword.
A couple of updates were needed in other routines, like `calwebb_tso3` and `extract_1d`, to prevent output files from having empty SCI extensions, just because of the presence of the SRCTYPE keyword defined in the SCI HDU.
This will of course create lots of regtest failures due to the new and relocated keywords, but it's necessary now, because SDP has included SRCTYAPT in their B7.5 code.
Fixes #4883 / [JP-1426](https://jira.stsci.edu/browse/JP-1426)
> JP-1426: Updates for new SRCTYAPT keyword

- JenkinsfileRT
- JenkinsfileRT_dev
- jwst/regtest/test_miri_image.py
- jwst/regtest/test_nircam_image.py
- jwst/regtest/test_nircam_mtimage.py
Update regression test CRDS context to 615, which includes the new abvegaoffset reference files, and remove the overrides for those ref files from the 3 imaging tests that use them.
> Update RT context and remove abvega overrides

- .travis.yml
This is to resolve the following syntax warnings:
And also update the python version used with `requirements-sdp.txt` to match what is being used in our delivery and regression tests.
> Update .travis.yml for syntax and python version for SDP

- .travis.yml
Only install the doc build dependencies in the job where they're needed.
Hopefully this will marginally improve the build speed of our TravisCI builds.
> Move apt-get installs to docs job in TravisCI

- JenkinsfileRT
- JenkinsfileRT_dev
Revert JenkinsRT setup back to using crds ops server and latest context, now that all updates have been migrated from test.
> Revert RT setup back to using CRDS ops

- docs/jwst/references_general/abvegaoffset_reffile.inc
- docs/jwst/references_general/abvegaoffset_selection.inc
- docs/jwst/references_general/references_general.rst
- docs/jwst/source_catalog/main.rst
- docs/jwst/source_catalog/reference_files.rst
- jwst/source_catalog/source_catalog.py
This PR updates the docs for the source catalog step to include the table columns and descriptions.  It also fixes the name of the ABVEGAOFFSET model in the docs.
Followup to https://github.com/spacetelescope/jwst/pull/4906
> Update docs for source catalog

- JenkinsfileRT
- JenkinsfileRT_dev
This should now report the actually used CRDS_CONTEXT whether we have it floating via `jwst-edit` or whether we explicitly set it.  Before this fix, it was just reporting the pmap that `jwst-edit` pointed to.
> Fix CRDS_CONTEXT reporting in regtests

- docs/conftest.py
This will make sure our doctests don't leave behind files in the working dir.
> Fix doctest jail dir behavoir for pytest-doctestplus>=0.5

- jwst/regtest/conftest.py
- jwst/regtest/test_infrastructure.py
Now instead of getting a test failure message like this:
```
>       assert diff_astropy_tables(path1, path2)
E       AssertionError: Column names (or order) do not match
```
we get something like
```
>       assert diff_astropy_tables(path1, path2)
E       AssertionError: Column names (or order) do not match
E       assert ['a', 'b', 'c'] == ['a', 'b', 'c', 'd']
E         Right contains one more item: 'd'
E         Use -v to get the full diff
```
and similar improvements for other diffs.  Should be more useful in evaluating on whether to OKify a test or not.
> Improve AssertionError reporting in diff_astropy_tables

- setup.py
This reverts commit a1ae375a2a441236af071016013784d78d9866c1.
Pytest has now released a fix for this:
https://github.com/pytest-dev/pytest/releases/tag/5.4.2
And running our regression tests locally indicates that it works.  They basically reverted the introduced bug.
> Revert "Pin pytest<=5.3.5 because --basetemp is broken"

- CHANGES.rst
- jwst/associations/lib/dms_base.py
- jwst/associations/lib/product_utils.py
- jwst/associations/lib/rules_level2_base.py
- jwst/associations/lib/rules_level3.py
- jwst/associations/lib/rules_level3_base.py
- jwst/associations/tests/test_level3_basics.py
- jwst/associations/tests/test_level3_spectrographic.py
Updated the asn rules to segregate observations based on the grating in use. This touched many more modules than I expected. 
closes JP-1413, #4845
> Jp 1413 Updates to split grating observations into separate asns

- jwst/engdblog/tests/test_engdblog.py
- jwst/srctype/srctype.py
- jwst/stpipe/subproc.py
The new version of `flake8` has uncovered some long-existing string formatting bugs in our code.  And some new-ish ones.  Seen here
https://travis-ci.org/github/spacetelescope/jwst/jobs/685867988#L216-L220
```
./jwst/stpipe/subproc.py:64:28: F523 '...'.format(...) has unused arguments at position(s): 2
./jwst/srctype/srctype.py:56:29: F541 f-string is missing placeholders
./jwst/srctype/srctype.py:60:25: F541 f-string is missing placeholders
./jwst/engdblog/tests/test_engdblog.py:35:12: F523 '...'.format(...) has unused arguments at position(s): 0
```
And of course these are failing on `master` in our PEP8 check.  This PR fixes them.
> Fix flake8 F523 and F541 bugs dealing with .format() and f-strings

- CHANGES.rst
- jwst/source_catalog/source_catalog.py
- jwst/source_catalog/source_catalog_step.py
This PR adds a fallback background estimation if the background cannot be determined in meshes.  This PR also adds some checks for completely-masked data.
Fixes #4913 / [JP-1440](https://jira.stsci.edu/browse/JP-1440)
> JP-1440: Make source catalog background estimation more robust

- CHANGES.rst
- jwst/datamodels/fits_support.py
- setup.py
The asdf 2.6.0 release includes a validator performance improvement that skips nodes that have already been visited during the current validation pass.  This package relies on the old behavior to ensure that fits headers have been fully populated, so here I'm setting a flag that will cause asdf to continue to revisit nodes.  This flag is not available in earlier versions of asdf so we need to inspect the asdf version before attempting to use it.
Resolves #4864
> Support asdf 2.6.x

- CHANGES.rst
- jwst/pipeline/calwebb_image3.py
Updated the `calwebb_image3` pipeline module to only load `science` and `background` member types from the input ASN (just like `calwebb_spec3`). Verified that this still works properly when the input is a single cal file and not an ASN.
Fixes #4933 / [JP-1448](jw00623020001_06101_00003_mirimage_cal.fits)
> JP-1448: Only load science/bkg members in calimage3

- CHANGES.rst
- jwst/datamodels/schemas/core.schema.yaml
Several updates to core schema to add new keywords, remove one obsolete one, and modify comments for a few others, all of which is to keep in sync with updates to the Keyword Dictionary that SDP is including in B7.5.
Goal is to include this in our next B7.5 release candidate.
This will of course cause LOTS of regtest failures due to changes in keyword comments.
Fixes #4900 / [JP-1433](https://jira.stsci.edu/browse/JP-1433)
> JP-1433: Update core schema for recent JWSTKD changes

- CHANGES.rst
- jwst/pipeline/calwebb_spec2.py
- jwst/regtest/test_niriss_wfss.py
This PR removes the path from the source catalog file before setting it as the `SCATFILE` keyword value in the `Spec2Pipeline`. 
Resolves #4923 / [JP-1444](https://jira.stsci.edu/browse/JP-1444)
> JP-1444: Remove path from SCATFILE keyword for NIRISS WFSS in Spec2Pipeline

- CHANGES.rst
- jwst/mrs_imatch/mrs_imatch_step.py
This PR prevents calling `astropy.stats.sigma_clipped_stats` with an all-zero array while simultaneously asking that all zeros be masked.  This is a known bug in `sigma_clipped_stats` and is already fixed on `master`.  This will be fixed in the next patch release `astropy 4.0.2` which is not released yet.
Tested this on the **jw00623-o020_20200511t191459_spec3_001_asn.json** association, and `Spec3Pipeline` now does not fail at this point.
Fixes #4938 / [JP-1450](https://jira.stsci.edu/browse/JP-1450)
> JP-1450: Fix mrs_imatch call to sigma_clipped_stats

- CHANGES.rst
- jwst/assign_wcs/tests/data/step_SourceCatalogStep_cat.ecsv
- jwst/assign_wcs/util.py
- jwst/background/tests/data/test_cat.ecsv
- jwst/extract_2d/tests/data/step_SourceCatalogStep_cat.ecsv
- jwst/lib/catalog_utils.py
`assign_wcs.util.get_object_info` was resulting in the incorrect reporting of missing columns in an input catalogue due to a set difference being in the wrong order. This has been fixed, and now the correct list of missing columns will be used in the error message
Resolves #4932 / [JP-1447](https://jira.stsci.edu/browse/JP-1447)
> JP-1447: Fix set difference bug in get_object_info

- jwst/source_catalog/source_catalog.py
Minor change to abmag error calculation to be valid for all S/N.  Note that all errors in the source catalog are still reported as NaN (because we don't have errors for the drizzled images yet), so I don't think this needs a changelog entry.
> Update abmag error calculation

- docs/jwst/data_products/nonscience_products.rst
- docs/jwst/data_products/science_products.rst
- jwst/datamodels/schemas/guider_cal.schema.yaml
- jwst/datamodels/schemas/guider_meta.schema.yaml
- jwst/datamodels/schemas/guider_raw.schema.yaml
Updated the guidestar datamodels schemas to include the missing keyword NUMREFST and change the HGA_motion table column data type from integer to string.
Also made a couple additional changes to unrelated docs to fix descriptions of the MIRI REFOUT extension ([JP-987](https://jira.stsci.edu/browse/JP-987))
Fixes #4939 / [JP-1451](https://jira.stsci.edu/browse/JP-1451)
> JP-1451: Guidestar data models updates

- jwst/source_catalog/source_catalog.py
- jwst/source_catalog/source_catalog_step.py
JP-1454 is caused by an invalid "BRIGHT" subarray in the MIRI APCORR reference file.  It should be called "BRIGHTSKY".
This PR raises an error if APCORR reference file data is missing.  It also now catches `RuntimeError` to print a warning message and exit gracefully for reference file errors.
Fixes #4947 / [JP-1454](https://jira.stsci.edu/browse/JP-1454)
> JP-1454:  Exit gracefully if APCORR data is missing

- jwst/tweakreg/tweakreg_step.py
- requirements-sdp.txt
- setup.py
This PR turns off optimization of the order in which catalogs are aligned to GAIA since there is only one "group catalog" and this turns off computation of image footprints on the sky.
Bug fix: the way previous code was written, it would have resulted in `wcs.name` being overwritten (actually lost) in the next loop. This PR fixes that.
If this PR is merged before next release - no changelog entry should be required.
> Performance improvement in GAIA alignment and bug fix wcs name

- CHANGES.rst
- jwst/datamodels/fits_support.py
WIP [JP-1343](https://jira.stsci.edu/browse/JP-1343) / #4663 
Looping was being performed over all available HDU's
to resolve arrays. However, only the maximum EXTVER for
any named HDU need be considered; anything after that will
guarantee no data.
> Limit looping over FITS HDU's for schema arrays

- README.md
0615 was the test server context.  Context 0614 on the production server is the correct context for this release.
> Fix CRDS_CONTEXT in DMS build table [ci skip]

- CHANGES.rst
- jwst/datamodels/container.py
- jwst/datamodels/tests/data/association_w_cat.json
- jwst/datamodels/tests/test_open.py
Populate `meta.asn.table_name` in each member of the association that is loaded into a `ModelContainer`.
Related to #4871 #4865 and #4870.
> Populate meta.asn.table_name when association opened in ModelContainer

- CHANGES.rst
- jwst/photom/photom.py
This PR resolves [JP-1434](https://jira.stsci.edu/browse/JP-1434). 
Fixes a bug where input `MultiSlitModel` `bunit` keys were not being updated with new flux units which resulted in incorrect units in the headers of the individual slit products due to header blending down the line
> Refactor photom to also update multislit models' bunit keys

- CHANGES.rst
- jwst/assign_wcs/nirspec.py
- jwst/assign_wcs/tests/test_nirspec.py
This PR resolves #4291 / [JP-1151](https://jira.stsci.edu/browse/JP-1151) and includes a fix in the conversion from the PPS coordinate frame to the Model frame.
> JP-1151: Fix NIRSpec MOS PPS reference point bug.

- .travis.yml
We have not seen any CI failures with our `jwst-edit` job since adding it as an allowed failure a year ago.  So:
- Remove the allowed failure job that uses `CRDS_CONTEXT=jwst-edit`
- Add `CRDS_CONTEXT=jwst-edit` to the SDP dependencies job
Our nightly tests are set up this way, so this will more closely mirror those now.
If we start seeing problems where we have failures in the SDP job, we can revert this.
> Move Travis jwst-edit job to the SDP job

- CHANGES.rst
- docs/jwst/extract_1d/arguments.rst
- jwst/extract_1d/extract1d.py
- jwst/extract_1d/tests/test_fit_background_model.py
This PR resolves [JP-1462](https://jira.stsci.edu/browse/JP-1462) in which an error was being raised when attempting to construct a polynomial fit with `LinearLSQFittter` and `Polynomial1D` with inputs of length 1. The minimum number of "good points" is now 2.
> JP-1462: Fix bug that results in obscure linear algebra error

- .travis.yml
- docs/Makefile
- docs/conf.py
- docs/jwst/references_general/references_general.rst
- jwst/ami/ami_analyze_step.py
- jwst/ami/ami_average_step.py
- jwst/ami/ami_normalize_step.py
- jwst/assign_mtwcs/assign_mtwcs_step.py
- jwst/assign_wcs/util.py
- jwst/associations/association.py
- jwst/associations/lib/dms_base.py
- jwst/associations/lib/rules_level3.py
- jwst/associations/main.py
- jwst/associations/registry.py
- jwst/skymatch/skymatch.py
- jwst/wiimatch/lsq_optimizer.py
- jwst/wiimatch/match.py
We turned off checking for doc build warnings a while back (my fault), and they have accumulated.  This PR fixes them all (see [here](https://travis-ci.org/github/spacetelescope/jwst/jobs/690207622#L539-L851) for their current state).  It also returns to converting warnings to errors in both user and Travis doc builds, i.e. the equivalent of
```
sphinx-build -W docs docs/_build
```
It also fixes renderings of some equations that got munged by some `DeprecationWarning` fixes a while back (also my fault).
And it removes a number of redundant docstrings in `associations` which are now apparently a no-no since sphinx 2.1 (perhaps there's a different way - i.e. keep them and not index them?)
It's a new day.
> Fix doc build warnings

- CHANGES.rst
- jwst/datamodels/schemas/wcsinfo.schema.yaml
Updated the comment strings for the MT_RA, MT_DEC, MT_AVRA, and MT_AVDEC keywords in `wcsinfo.schema.yaml` to match what was recently implemented for these keywords in the Keyword Dictionary (JWSTKD-358, JWSTKD-359). The original comment strings were shortened so that they won't get truncated when appearing in actual FITS header records.
Should only affect regtest datasets that actually use moving target data (which is a very small number).
> Update MT_RA/DEC keyword comments

- CHANGES.rst
- jwst/pipeline/calwebb_image3.py
This PR refactors `Image3Pipeline` to use the `Step` infrastructure to save results of the included steps and removes extra step logging at the pipeline level (to be more consistent with other pipelines)
Resolves #3829 / [JP-872](https://jira.stsci.edu/browse/JP-872)
> JP-872: Refactor Image3Pipeline to use Step infrastructure

- jwst/skymatch/skymatch.py
- jwst/wiimatch/match.py
Fixes the following warnings in the unit tests (on collection):
```
2020-05-28 22:13:45,601 - stpipe - WARNING - /home/travis/build/spacetelescope/jwst/jwst/skymatch/skymatch.py:29: DeprecationWarning: invalid escape sequence \ 
2020-05-28 22:13:45,706 - stpipe - WARNING - /home/travis/build/spacetelescope/jwst/jwst/wiimatch/match.py:24: DeprecationWarning: invalid escape sequence \s
```
Also verified that the docstrings render correctly in the docs.
> Fix skymatch and wiimatch docstrings

- jwst/regtest/test_nirspec_masterbackground.py
The `test_nirspec_masterbackground.py` module contains 4 datasets and 5 tests.  They are currently all being run in the same jailed directory because `regtest_module` fixture is used.  Better to run these in separate directories as they are separate datasets.
This PR simplifies them to run separately and removes the fixture.  It's a bit simpler now to see what is going on in each test.
Tests pass without any modifications to input or truth files.
> REGTEST: Simplify NIRSpec master background test

- CHANGES.rst
- jwst/assign_mtwcs/assign_mtwcs_step.py
- jwst/assign_mtwcs/moving_target_wcs.py
If any of the input images to the `assign_mtwcs` step are missing the MT_RA or MT_DEC keyword values, issue a warning and skip the step.
Fixes #5014 / [JP-1490](https://jira.stsci.edu/browse/JP-1490)
> JP-1490: skip assign_mtwcs if target coords missing

- CHANGES.rst
- jwst/datamodels/container.py
- jwst/master_background/master_background_step.py
- jwst/pipeline/calwebb_spec2.py
- jwst/pipeline/calwebb_spec3.py
- jwst/pipeline/calwebb_tso3.py
- jwst/regtest/test_nirspec_fs_spec3.py
- jwst/stpipe/pipeline.py
We still have some open file issues, which appeared when running the updated version of `pytest-openfiles` and the latest `astropy` release candidate.
This should now get our nightly regression test builds that use dev dependencies passing (and will make sure that our regular nightly tests pass under `astropy 4.1` when it is released).
Thanks to @eslavich for some help debugging this.
Resolves #4978 / [JP-1468](https://jira.stsci.edu/browse/JP-1468)
> Fix open file issues in master background, tso and spec pipelines

- CHANGES.rst
- jwst/datamodels/schemas/core.schema.yaml
As it will be used as a parkey in CRDS ref file selection and we want there to be a default value even if the OPMODE keyword is missing from the science data headers.  Also added enum list.
> Changes to datamodels to add default value for meta.instrument.lamp_mode

- CHANGES.rst
- jwst/datamodels/container.py
- jwst/datamodels/tests/test_models.py
- jwst/regtest/test_niriss_soss.py
- jwst/stpipe/crds_client.py
- jwst/stpipe/pipeline.py
In our dev nightly regression tests which use the latest dev `astropy` (also happens with `astropy 4.1rc1`), we see open files left behind in `jwst.regtest.test_niriss_soss.py`:
https://plwishmaster.stsci.edu:8081/job/RT/job/JWST_UNSTABLE/272/testReport/jwst.regtest/test_niriss_soss/_unstable_deps__test_niriss_soss_stage2_calints_/
```
E           AssertionError: File(s) not closed:
E             /data1/jenkins/workspace/RT/JWST_UNSTABLE/clone/test_outputs/popen-gw24/test_niriss_soss_run_pipelines0/jw00625023001_03101_00001-seg002_nis_calints.fits
E             /data1/jenkins/workspace/RT/JWST_UNSTABLE/clone/test_outputs/popen-gw24/test_niriss_soss_run_pipelines0/jw00625023001_03101_00001-seg001_nis_calints.fits
/data1/jenkins/workspace/RT/JWST_UNSTABLE/miniconda/envs/tmp_env0/lib/python3. …
```
> Fix dangling file handle when ModelContainer.from_asn() fails

- CHANGES.rst
- jwst/ramp_fitting/ramp_fit.py
PR #4815 was a missing a line to populate the ERR array in the output rateints product for the case of single processor mode. Also added missing change log entry for the addition of multiprocessing to the step.
> Fix a bug in ramp_fit multiprocessing code

- jwst/regtest/test_nirspec_subarray.py
Temporarily xfail the NIRSpec `calwebb_detector1` regtest that throws a bestref error due to an rmap problem, because it appears it's going to be a while yet till the rmap gets fixed. At least we'll get a passing regtest run this way.
> Temporarily xfail regtest that has rmap problem

- jwst/ramp_fitting/tests/test_ramp_fit.py
These 2 tests leave behind FITS files in the repo.  They should not.
> Don't leave behind FITS files in ramp_fitting multiprocessing tests

- CHANGES.rst
- jwst/pathloss/pathloss.py
- jwst/photom/photom.py
This PR fixes the NIRSPEC slices not mapping properly.
A fix was required in pathloss and photom to remove wavelengths with NANs
Resolves #3910 / [JP-932](https://jira.stsci.edu/browse/JP-932)
> Fix NIRSPEC IFU slices problem in JP-932

- CHANGES.rst
- jwst/extract_2d/grisms.py
extract_2d fails when trying to delete the variables subwcs and new_slit in the case that there are no grism spectra extracted. The unit tests pass, 
pytest test_grisms.py
...
= 13 passed, 1 xpassed, 6 warnings in 8.35s=
Some of the regression tests fail due to known precision issues between OS X and unix. 
Fixes #5039 / [JP-1507](https://jira.stsci.edu/browse/JP-1507)
> JP-1507 checks subwcs and new_slit variables exist before trying to delete them

- jwst/regtest/test_nirspec_subarray.py
Now that the NIRSpec readnoise rmap has been fixed in the latest CRDS context, the NIRSpec regtest that had been xfail-ed a couple weeks ago can be reinstated, because ref file retrieval is successful again.
> Reactivate failing NIRSpec regtest

- CHANGES.rst
- jwst/associations/tests/test_asn_from_list.py
- jwst/barshadow/bar_shadow.py
This is a correction for the fact that the yslit values in a 2D science spectrum _decrease_ from bottom to top but in the reference file they _increase_ from bottom to top. 
Fixes #3897 / [JP-918](https://jira.stsci.edu/browse/JP-918)
> Jp 918 Correct bar shadow parity bug for yslit

- CHANGES.rst
- docs/jwst/pipeline/calwebb_tso3.rst
- jwst/lib/pipe_utils.py
- jwst/lib/tests/test_pipe_utils.py
- jwst/pipeline/calwebb_tso3.py
- jwst/tso_photometry/tso_photometry_step.py
A user recently reported that MIRI imaging TSO data were going through the spectroscopic branch of the ``calwebb_tso3`` pipeline, which turned out to be due to the fact that the TSOVISIT keyword was missing. These updates make the ``calwebb_tso3`` pipeline more robust to that kind of obvious problem with the input data and causes it to issue an error message and abort. Also needed to update the ``is_tso`` helper function, because it was assuming that any ``CubeModel`` data were TSO, which is not correct: coronagraphy data is also ``CubeModel``. Also just did a little general clean-up and addition of comments, etc. to the modules involved, as well as adding a description of the keyword logic to the docs.
At some point we should probably also try to figure out how to update the …
> Make calwebb_tso3 more robust

- CHANGES.rst
- jwst/datamodels/schemas/core.schema.yaml
- jwst/datamodels/schemas/multispec.schema.yaml
- jwst/datamodels/schemas/referencefile.schema.yaml
- jwst/datamodels/schemas/steppars.schema.yaml
Update all existing schemas that contain the TIMESYS keyword to also include TIMEUNIT, with specs as outlined in JP-1554 and requested in JWSTKD-97.
Should cause lots of regression test failures, due to extra keyword showing up in all outputs. Warming up okify_regtests now ...
Fixes #5101 / [JP-1554](https://jira.stsci.edu/browse/JP-1554)
> JP-1554: Add TIMEUNIT keyword

- CHANGES.rst
- jwst/outlier_detection/outlier_detection.py
Updated the outlier detection code to save intermediate results when save_intermediate_results = True.
Fixes [JP-1283](https://jira.stsci.edu/browse/JP-1283) , #4540
> JP-1283 Fix bug in outlier_detection to save intermediate results

- CHANGES.rst
- docs/jwst/data_products/science_products.rst
- docs/jwst/pathloss/description.rst
- docs/jwst/pipeline/calwebb_spec2.rst
- jwst/datamodels/ifuimage.py
- jwst/datamodels/image.py
- jwst/datamodels/multiexposure.py
- jwst/datamodels/multislit.py
- jwst/datamodels/schemas/pathlosscorr.schema.yaml
- jwst/datamodels/schemas/slitdata.schema.yaml
- jwst/datamodels/slit.py
- jwst/datamodels/tests/test_models.py
- jwst/pathloss/pathloss.py
- jwst/pathloss/pathloss_step.py
Update all of the `datamodels` schemas that contain a "pathloss" array to now contain both a "pathloss_ps" and "pathloss_un" (point source and uniform, respectively). Update the `pathloss` step to always compute both 2D versions, apply the appropriate one, and store both versions in the output. For NIRISS SOSS, which only has one version of the pathloss correction, store as "pathloss_ps", because it's assumed that only point sources will be observed with that mode.
Fixes #5103 / [JP-1556](https://jira.stsci.edu/browse/JP-1556)
> JP-1556: Store both versions of pathloss correction

- jwst/assign_wcs/util.py
temporary fix for #5120 until gwcs 0.14 is released - #5120 works now with older versions of gwcs.
> use input_frame when creating a gWCS object

- CHANGES.rst
- docs/jwst/master_background/description.rst
- jwst/datamodels/ifuimage.py
- jwst/master_background/expand_to_2d.py
- jwst/master_background/nirspec_corrections.py
- jwst/master_background/tests/test_nirspec_corrections.py
Updated the `expand_to_2d` module to call the new function `correct_nrs_ifu_bgk` when the science data is a point source, in order to apply the point source vs. uniform source pathloss mods to the computed 2D background, before subtracting from the science data.
Fixes #5104 / [JP-1557](https://jira.stsci.edu/browse/JP-1557)
> JP-1557: Update master_background for NRS IFU pathloss

- jwst/ramp_fitting/tests/test_ramp_fit.py
The multi-processing in a couple of the `ramp_fit` unit tests seems to be causing problems in the Jenkins test environment, so set them to skip. They don't behave properly in general.
> Skip ramp_fit multi-processing tests

- CHANGES.rst
- docs/jwst/persistence/arguments.rst
- docs/jwst/persistence/description.rst
- jwst/datamodels/dqflags.py
- jwst/persistence/persistence.py
Added the new DQ flag type "PERSISTENCE" (using up another one of the leftover reserved slots) to the dqflags definitions and change the ``persistence`` step to use that flag for pixels with high persistence instead of "DO_NOT_USE". Updated ``persistence`` step docs accordingly.
Fixes #4535 / [JP-1278](https://jira.stsci.edu/browse/JP-1278)
> JP-1278: Change flag used for high persistence

- CHANGES.rst
- jwst/cube_build/cube_build_io_util.py
- jwst/cube_build/tests/test_miri_cubepars.py
- jwst/datamodels/container.py
- jwst/datamodels/model_base.py
- jwst/datamodels/tests/test_fits.py
- jwst/datamodels/tests/test_models.py
- jwst/exp_to_source/tests/test_exp_to_source.py
- jwst/lib/set_telescope_pointing.py
- jwst/lib/tests/test_set_telescope_pointing.py
- jwst/stpipe/step.py
- jwst/stpipe/tests/steps/__init__.py
- jwst/stpipe/tests/test_pipeline.py
- setup.py
Or, well methinks its nonsensical anyways, but the PR review will indicate otherwise.
In general, when a `DataModel` is opened from a FITS file, the filehandle for the FITS file is held internally until the `DataModel` is `close`ed garbage-collected (maybe). However, ran across this bit of code in which the FITS file is opened in a context manager and the file handled is stored for later closing. This would be the nonsensical point: either a context manager should not be used OR the filehandle should not be stored for later re-closing.
Though having the FITS file open is an integral part of `DataModel` operation, this appears to have not had any operational effect. But, current work on `DataModel` reading efficiency has actually caused the expected "I/O operation on closed file" error. …
> Fix nonsensical premature closing of FITS file of a DataModel

- jwst/datamodels/fits_support.py
- jwst/datamodels/util.py
Necessary because ASDF needs to update to at least 2.6.1. When done so, the default can be reset.
> Disable FITS Hash checking by default

- jwst/stpipe/tests/data/proper_pipeline.asdf
- jwst/stpipe/tests/steps/__init__.py
- jwst/stpipe/tests/test_step.py
Resolves JP-1482
Resolves #5005 
The issue itself was not reproducible. This PR adds the specific test for the condition described.
> Add test to ensure substep configs are read during Step.call

- setup.cfg
The next version of asdf includes a bug fix that makes validation of the schema `default` property more strict.  This breaks several tests in jwst due to property definitions like this example from jwst/datamodels/schemas/amilg.schema.yaml:
```
fit_image:
title: Fitted image
fits_hdu: FIT
default: 0.0
ndim: 2
datatype: float32
```
Since `0.0` is not an ndarray of 2 dimensions, the stricter validation fails.  If we wanted a default that would pass validation, we'd have to do something like this:
```
fit_image:
title: Fitted image
fits_hdu: FIT
default: !<tag:stsci.edu:asdf/core/ndarray-1.0.0>
data:
- [0.0, 0.0, 0.0, 0.0, 0.0]
- [0.0, 0.0, 0.0, 0.0, 0.0]
- [0.0, 0.0, 0.0, 0.0, 0.0]
- [0.0, 0.0, 0.0, 0.0, 0.0]
- [0.0, 0.0, 0.0, 0.0, 0.0]
datatype: float32
shape: [5, 5]
ndim: 2
datatype: …
```
> Disable validation of schema default values

- jwst/extract_2d/extract_2d_step.py
Set wfss_extract_half_height to a default value of 5 pixels as requested by NIRISS team.
> adjust default value for wfss_extract_half_height

- jwst/assign_wcs/util.py
- jwst/extract_2d/tests/test_grisms.py
Fix a bug in the new WFSS extraction region code in assign_wcs functions, which is referring to `model.meta.wcsinfo.dispaxis` instead of the correct `model.meta.wcsinfo.dispersion_direction`. Regression tests caught this error, causing all WFSS level-2b processing to fail.
> Fix bug in new WFSS extraction code

- docs/jwst/source_catalog/main.rst
This adds a note to the Source catalog documentation indicating that the error array is filled with `nan` in the case for resampled data.   This documents the issue highlighted in #5182 
Relates to [JP-1611](https://jira.stsci.edu/browse/JP-1611)
> src_catalog_error_note

- JenkinsfileRT
- JenkinsfileRT_dev
The two files are the same now except for:
```
$ diff -y JenkinsfileRT JenkinsfileRT_dev --suppress-common-lines
jobconfig.enable_env_publication = true			      |	jobconfig.enable_env_publication = false
// Build and test with dependencies specified in requirements |	// Build and test with dependencies specified in requirements
bc0.name = 'stable-deps'				      |	bc0.name = 'unstable-deps'
bc0.pip_reqs_files = ['requirements-sdp.txt']		      |	bc0.pip_reqs_files = ['requirements-dev.txt']
"pytest --cov-report=xml --cov -r sxf -n 30 --bigdata --s |	    "pytest -r sxf -n 30 --bigdata --slow \
bc1.name = 'macos-stable-deps'				      |	bc1.name = 'macos-unstable-deps'
```
> Make stable and unstable JenkinsfileRT consistent

- JenkinsfileRT
- jwst/regtest/test_nircam_tsgrism.py
Made the grism test resilient against database availability. If not available, test is skipped.
Also, reverted the switch to the D1 string DB, since that is under build at the moment. D2 is the side to for the moment.
> Skip grism test if engineering database is unavailable

- CHANGES.rst
- JenkinsfileRT_dev
- jwst/datamodels/fits_support.py
- jwst/datamodels/model_base.py
- jwst/datamodels/util.py
After ASDF > 2.6.1 is available, re-enable FITS-Hash.
> Re-enable FITS-hash by default

- CHANGES.rst
- jwst/associations/lib/rules_level3.py
- jwst/fringe/fringe.py
- jwst/fringe/fringe_step.py
- jwst/pipeline/calwebb_spec2.py
- jwst/pipeline/calwebb_tso-spec2.cfg
- jwst/regtest/test_miri_mrs_tso.py
As part of the minimal processing support for MIRI MRS exposures taken in TSO mode, the calspec2 fringe step has been requested to be applied, as it is for non-TSO MRS data. This updates the fringe step code to allow for both 2D and 3D inputs. In the case of 3D input, the 2D fringe correction is simply broadcast to all planes of the 3D cube.
Fixes #5087 / [JP-1546](https://jira.stsci.edu/browse/JP-1546)
> JP-1546: Updates for MIRI MRS TSO processing

- conftest.py
- jwst/cube_build/cube_build_step.py
- jwst/cube_build/ifu_cube.py
- jwst/cube_build/tests/test_miri_cubepars.py
- setup.py
Pin `pytest<6` because of `pytest-doctestplus` imcompatibility (for now).
This fixes some logging bugs in `cube_build` where `None` objects were getting passed through an `%f` formatter in log messages.
```
$ pytest jwst/cube_build/tests/test_miri_cubepars.py::test_miri_cubepars_multiple_bands
========================================= test session starts =========================================
platform darwin -- Python 3.7.7, pytest-6.0.0, py-1.9.0, pluggy-0.13.1
rootdir: /Users/jdavies/dev/jwst, configfile: setup.cfg
plugins: doctestplus-0.7.0, requests-mock-1.8.0, asdf-2.7.0, ci-watson-0.5, cov-2.10.0, xdist-1.34.0, openfiles-0.5.0, forked-1.3.0
collected 1 item …
```
> Fix logging bugs formerly suppressed by pytest

- docs/jwst/srctype/description.rst
- jwst/srctype/srctype.py
- jwst/srctype/tests/test_srctype.py
Update the srctype step to look at the "DITHOPFR" keyword, instead of "PATTTYPE", when using the dither pattern to decide if a source should be considered point-like.
Fixes #5116 / [JP-1561](https://jira.stsci.edu/browse/JP-1561)
> JP-1561: Update srctype to use DITHOPFR for MIRI MRS

- CHANGES.rst
- docs/jwst/pipeline/calwebb_detector1.rst
- docs/jwst/ramp_fitting/arguments.rst
- docs/jwst/ramp_fitting/description.rst
- jwst/datamodels/util.py
- jwst/model_blender/blendmeta.py
- jwst/outlier_detection/outlier_detection_step.py
- jwst/pipeline/calwebb_coron3.py
- jwst/ramp_fitting/ramp_fit.py
- jwst/ramp_fitting/utils.py
Several updates are contained here, in order to allow NINTS=1 exposures to be used in later stages of the pipeline for coronagraphy observations.
1) Updated the `ramp_fit` step so that it ALWAYS creates a "rateints" product, even when NINTS=1. In this case, the data is the same as the "rate" product, except for the fact that it's stored in a `CubeModel` with the 3rd dimension having length 1. This allows the "rateints" products to flow through `calwebb_image2`, producing "calints" products, which are then used as input to `calwebb_coron3`, with no changes needed to the ASN rules to use different products (e.g. "cal" instead of "calints").
2) Updated parts of the `calwebb_coron3` pipeline and the `outlier_detection` step to properly handle the `CubeModel`s that have NINTS=1. In this case, …
> JP-1296: Updates for NINTS=1 coron exposures

- jwst/pipeline/calwebb_spec2.py
- jwst/pipeline/calwebb_tso-spec2.cfg
- jwst/regtest/test_miri_mrs.py
- jwst/regtest/test_nirspec_ifu_spec2.py
Disable master background by default.
Also mark some Spec2Pipeline tests as slow, so that regtests can be run without always waiting forever.
> Official add master background but disable by default

- jwst/master_background/expand_to_2d.py
- jwst/master_background/nirspec_utils.py
- jwst/pipeline/calwebb_spec2.py
Add the `map_to_science_slits` function to `nirspec_utils` for use in `calwebb_spec2` processing of NIRSpec MOS master bkg. Note that right now the function is a simple 1-line call to the existing `expand_to_2d` function, because `expand_to_2d` is already setup to correctly recognize a `MultiSlitModel` as input and process all slits in it. This means we're expanding the master bkg to ALL slits, including those with extended sources, as well as the background slits themselves (neither of which may be strictly necessary). Hence this may change in a future version, if we want to restrict which slits get the expanded background.
Fixes #5219 / [JP-1631](https://jira.stsci.edu/browse/JP-1631)
> JP-1631: implement master bkg mapping to MOS slits

- CHANGES.rst
- jwst/outlier_detection/outlier_detection.py
- jwst/resample/resample_utils.py
Replacing NaNs with -1 in the pixel mapping for `drizzle` was causing these artifacts.  When this was originally implemented, `drizzle` pixmap barfed when there were NaNs in the pixmap.
And of course the reason this is showing up only in NIRSpec, as that NIRSpec is the only instrument where the WCS produces NaNs for pixels in the WCS bounding box.  This is why we did not see it elsewhere.
See below for what the fix does for single-resampled `s2d` files in `calwebb_spec2` for NIRSpec MOS data:
Resolves #5013 / [JP-1489](https://jira.stsci.edu/browse/JP-1489)
> JP-1489: Allow calc_gwcs_pixmap to compute NaNs for drizzle

- requirements-sdp.txt
I think there will be a release of `gwcs` soon, and that should probably be incremented here when it is released.  @nden 
Also, if `astropy 4.1` gets released soon, it can probably be updated here.
We've been testing both in our dev dependency builds, and there shouldn't be any issues.
> Pin requirements-sdp.txt for Build 7.6

- setup.py
`pytest-doctestplus 0.8` has been released, so we can now use `pytest 6`.
> Allow pytest 6.0 and up

- CHANGES.rst
- jwst/associations/lib/dms_base.py
- jwst/associations/tests/test_level3_spectrographic.py
- jwst/cube_build/cube_build.py
- jwst/cube_build/cube_build_step.py
- jwst/cube_build/ifu_cube.py
This updates the level-3 ASN rules to remove the errant "t" prepended to the grating name for NIRSpec IFU product names that get stored in spec3 ASN files, and updates the part of the `cube_build` step that composes output file names to take into account the fact that the input product base name may already contain the grating (and hence don't add a second one). Rather than having `cube_build` decide whether or not it needs to add a grating name, the existing one is simply removed and then all the remaining logic for adding grating and filter names to the product name remains the same.
Fixes #5212 / [JP-1626](https://jira.stsci.edu/browse/JP-1626)
> JP-1626: Fix NIRSpec IFU product names in spec3 ASN's

- jwst/exp_to_source/exp_to_source.py
- jwst/flatfield/flat_field.py
- jwst/flatfield/flat_field_step.py
- jwst/regtest/test_nirspec_brightobj.py
- jwst/regtest/test_nirspec_ifu_spec2.py
- jwst/regtest/test_nirspec_image2.py
- jwst/regtest/test_nirspec_mos_spec2.py
After many red-herrings and other issues, the inversion of `FlatFieldStep` is (near) ready.
Issues/conditions:
~1. Inversion is not done for any other instrument except NIRSpec. A `NotImplementedError` is currently produced. Just haven't looked that far.~ Done.
2. Question: For the override of the flat field, how should that be recorded in the headers. Reference files are populated, but not sure if the user-supplied file should go into the `FLAT` reference or as something else. Storing in `FLAT` may be misleading, especially for NIRSpec, since that reference file type is not used at all.
> JP-1587 Implement inverse of the FlatFieldStep

- CHANGES.rst
- jwst/exp_to_source/exp_to_source.py
- jwst/pipeline/calwebb_ami3.py
Updated the `calwebb_ami3.py` module to only send PSF and science target members from the input ASN through the processing steps, so as to exclude any other member types, such as target_acquisition. Comparison with previous results shows that "ami" products are no longer created for target_acq members and the results of all other processing are identical.
Fixes #5240 / [JP-1641](https://jira.stsci.edu/browse/JP-1641)
> JP-1641: Update calami3 to exclude targ_acqs from processing

- jwst/flatfield/flat_field.py
- jwst/flatfield/flat_field_step.py
- jwst/pipeline/calwebb_spec2.py
- jwst/regtest/test_nirspec_image2.py
- jwst/stpipe/step.py
Implement the "easy/lazy" method of passing correction parameters around for FlatFieldStep.
Side note: The regressions discovered a dangling-if-without-else condition. See line 293 in flat_field.py. Basically, there was the possibility that NIRSPec-like model could be passed in, but have no flat field applied silently. Do not know if the condition could have happened in real life. However, because of changes where the reference files are no longer always required, the condition became possible. A runtime exception has been added just to ensure that the condition does not go unnoticed.
> Implement correction parameter API for FlatFieldStep

- docs/jwst/cube_build/main.rst
One-character fix for a typo I noticed while reading the docs for cube_build: Currently it says the output units are in "milliJy"/steradian but in fact they are in megaJy/steradian.
> trivial docs typo fix: mJy/steradian should be MJy/steradian in cube_build/main.rst

- CHANGES.rst
- jwst/datamodels/schemas/core.schema.yaml
Update `core.schema.yaml` to add new MIRI LRS pattern names to `PATTTYPE` enum list.
Fixes #5238 / [JP-1639](https://jira.stsci.edu/browse/JP-1639)
> JP-1639: Update PATTTYPE allowed values for new MIRI LRS patterns

- JenkinsfileRT
- JenkinsfileRT_dev
Reverts spacetelescope/jwst#5259 until we get 3.8 problems with installing `pymssql` figured out.
> Revert "Use python 3.8 in nightly regression tests"

- jwst/associations/lib/dms_base.py
- jwst/associations/lib/rules_level2b.py
Update the level-2b FGS ASN constraint that builds normal science `image2` ASN's to exclude any WFSC exposures, so that FGS WFSC exposures result in a `wfsc-image2` ASN, instead of a regular `image2` ASN.
Fixes #5009 / [JP-1485](https://jira.stsci.edu/browse/JP-1485)
> JP-1485: fix level-2b FGS WFSC ASN generation

- jwst/assign_wcs/nirspec.py
- requirements-sdp.txt
- setup.py
This PR sets the version of gwcs in SDP to 0.14.0 and the version of asdf to 2.7.1
It includes some minor changes to the Nirspec pipeline to take advantage of the fact that the WCS pipeline is not a list of `wcs.Step` instances instead of a list of (frame, transform) tuples and the `transform` and `frame` of a step should be accessed as attributes. Indexing the step still works but raises a `DeprecationWarning`.
Update: Bumped the version numbers of gwcs and asdf in setup.py
> use gwcs 0.14.0 for sdp delivery

- CHANGES.rst
- jwst/extract_1d/apply_apcorr.py
- jwst/extract_1d/extract.py
`extract_1d` was failing when trying to process NIRSpec FS or MOS data in a `MultiSlitModel` when trying to compute the pixel scale (converting arcsec from ref file to pixels), because it was trying to use the WCS from the first slit instance in the model for all slits. This was giving null/NaN results for all slits other than the first. So this updates the routine to use the WCS object for the particular slit being processed. Required adding the slit name to the `ApCorr` base class, so that it's available for use.
Fixes #5229 / [JP-1636](https://jira.stsci.edu/browse/JP-1636)
> JP-1636: Fix slit wcs issue in extract_1d apcorr

- JenkinsfileRT
- JenkinsfileRT_dev
- setup.py
Another attempt to update the regtests to use python 3.8, this time with `pymssql-linux` used in place of the generic `pymssql` pkg.
> Try python 3.8 again in the nightly regression tests

- JenkinsfileRT
- requirements-sdp.txt
- setup.py
Add a new Jenkins build string parameter "ARTIFACTORY_ENV" so that the regressions can use a different artifactory environment instead of just "dev".
To setup Jenkins builds, in "Configure", add a new string parameter called "ARTIFACTORY_ENV". Make the default "dev", and set the description to "Set which environment to use from the jwst-pipeline artifactory to test against."
> Add ability to change artifactory environment

- CHANGES.rst
- jwst/cube_build/cube_build_step.py
@drlaw1558 
This should do it. I am checking on what the nightly regression test use for the CRDS context. Once we confirm it includes the new NIRSpec Cube pars reference file we will be able to merge this PR
> JP-1653 changed default weighting to emsm

- .github/workflows/publish-to-pypi.yml
This will enable Github actions to build and publish the `jwst` package to PyPI when a Github release is created in this repository for a new or existing semver-compliant tag.
Further information may be found here:
https://github.com/spacetelescope/action-publish_to_pypi
> Enable PyPI publication service

- README.md
We used to have this documented in our README, but currently don't.
Resolves #5098
> Add stable install instructions to README

- CHANGES.rst
- jwst/assign_wcs/pointing.py
- jwst/lib/set_telescope_pointing.py
Fixes #5148 / [JP-1585](https://jira.stsci.edu/browse/JP-1585). Improves upon #5185 by restoring wrap angle for `V2` to 180 degrees so that inversion polynomials that take from detector to V2V3 frames now can work as designed.
Closes #5195
Closes #5185 
This PR replaces `V23ToSky` model with "standard" models from `astropy` and `gwcs`.
> JP-1585: Wrap first angle at 360 in forward V2V3 to sky and at 180 for inverse.

- .travis.yml
We updated our nightly regression tests to use python 3.8 (see #5271) but forgot to update the Travis build for unit tests.
> Update Travis SDP job to use python 3.8

- requirements-sdp.txt
`crds 7.6.0` was just released, so we should run our regression tests with it and include in the Build 7.6 rc2 delivery to DMS.
> Bump crds==7.6.0 in requirements-sdp.txt

- CHANGES.rst
- jwst/pipeline/calwebb_spec2.py
- jwst/pipeline/tests/test_calwebspec2.py
This includes the traceback of a per-product failure in the final `RuntimeError` message for the spec2 pipeline.
Currently on `master`:
```
E           RuntimeError: One or more products failed to process. Failing calibration.
jwst/pipeline/calwebb_spec2.py:130: RuntimeError
```
This PR:
```
E           RuntimeError: Traceback (most recent call last):
E             File "/Users/jdavies/dev/jwst/jwst/pipeline/calwebb_spec2.py", line 112, in process
E               result = self.process_exposure_product(
E             File "/Users/jdavies/dev/jwst/jwst/pipeline/calwebb_spec2.py", line 172, in process_exposure_product
E               with self.open_model(science_member) as science:
E             File "/Users/jdavies/dev/jwst/jwst/stpipe/step.py", line 1071, in open_model
E …
```
> JP-1666: Include per-product tracebacks for failures in calwebb_spec2

- CHANGES.rst
- jwst/tso_photometry/tests/test_tso_photometry.py
- jwst/tso_photometry/tso_photometry.py
- jwst/tso_photometry/tso_photometry_step.py
Update the `tso_photometry` step to use the number of integrations contained within a given input segment, rather than the whole exposure, when computing integration time stamps. Creating an array of time stamps based on all integrations was causing a mismatch in column lengths with the actual photometry data.
Fixes #5316 / [JP-1680](https://jira.stsci.edu/browse/JP-1680)
> JP-1680: fix tso_photometry int times computation

- CHANGES.rst
- jwst/ramp_fitting/ramp_fit.py
- jwst/ramp_fitting/tests/test_ramp_fit.py
Fix `ramp_fit` to populate the `int_times` attribute in the `rateints` products. I think it got removed during the rework to add multi-processing.
Fixes #5320 / [JP-1681](https://jira.stsci.edu/browse/JP-1681)
> JP-1681: Fix empty int_times table in rateints products

- CHANGES.rst
- jwst/associations/lib/rules_level3.py
- jwst/cube_build/ifu_cube.py
A few different types of MIRI MRS and NIRSpec IFU associations (mostly involving dedicated bkg exposures) are leading to product name templates in the ASN files with the suffix "_clear" attached. The NIRSpec IFU case is fixed here by adding the same product name override to the `IFUGratingBkg` class that's already in the `IFUGrating` class, which overrides the base class product name (which contains "clear" for the optical element). A similar fix in the ASN rules for the MRS bkg case (rule class `Lv3SpecAux`) was not as straightforward, because that same class is also used for NIRSpec dedicated backgrounds and hence a change could cause collateral damage to those. So instead, an update is being made to the `cube_build` function that builds level-3 MRS product names so that it looks for …
> JP-1689: Fix level-3 IFU product names

- CHANGES.rst
- jwst/cube_build/blot_cube_build.py
- jwst/cube_build/cube_build_step.py
- jwst/cube_build/ifu_cube.py
- jwst/outlier_detection/outlier_detection_ifu.py
Clean up of making single cubes and blotted cubes.
1.   If making SINGLE type check the input file sent to cube_build and only use those of the correct channel/grating.
2.  When blotting a median IFUcube back to the detector look at the channel or grating and only blot those files that cover the same channel/grating.
3. If all the data  on the input file has been flagged as DO_NOT_USE (a by product of outlier rejection) skip the file in creating the ifucube.
> jp-1690 calspec3  cube_build clean up 

- CHANGES.rst
- README.md
- jwst/extract_1d/extract.py
Updated the `get_target_coordinates` function in `extract_1d` step so that when the input model is a `SlitModel` it gets the target coords from the slit source_ra and source_dec attributes, instead of defaulting to the generic TARG_RA/TARG_DEC values (which for something like NIRSpec MOS is going to be very wrong).
Fixes #5301 / [JP-1668](https://jira.stsci.edu/browse/JP-1668)
> JP-1668: Fix bug in extract_1d target coords

- CHANGES.rst
- jwst/flatfield/flat_field.py
- jwst/ramp_fitting/ramp_fit_step.py
Updates to the ramp_fit step to store rate product for IFU NRS_AUTOWAVE exposures as an `IFUImageModel` (as is already done for IFU science exposures) and updates to flatfield to treat NRS_AUTOWAVE as an exposure to be processed via the spectroscopic branch.
Fixes #5355 / [JP-1723](https://jira.stsci.edu/browse/JP-1723)
> JP-1723: Flatfield fixes for NRS lamp exposures

- jwst/regtest/test_nirspec_lamp_fs_spec2.py
- jwst/regtest/test_nirspec_lamp_ifu_spec2.py
Adding two NIRSpec lamp regression tests, covering NRS_AUTOWAVE with OPMODE='IFU' and 'FIXEDSLIT'. All inputs and truths have been uploaded to artifactory.
> Add NRS lamp regtests

- CHANGES.rst
- docs/jwst/datamodels/models.rst
- docs/jwst/outlier_detection/arguments.rst
- docs/jwst/resample/arguments.rst
- jwst/datamodels/tests/test_open.py
- jwst/datamodels/util.py
- jwst/lib/basic_utils.py
- jwst/outlier_detection/outlier_detection_step.py
- jwst/pipeline/calwebb_image3.py
- jwst/regtest/test_fgs_guider.py
- jwst/resample/resample.py
- jwst/resample/resample_step.py
- setup.cfg
Resolves [JP-1541](https://jira.stsci.edu/browse/JP-1541)
Resolves #5081 
A predictive memory check is implemented in the `resample` module. The steps `OutlierDetectionStep` and `ResampleStep`, both of which have the potential of building very large images, make use of this check through the parameter `allowed_memory`. The value represents the fraction of available memory to use in instantiating the output data model. `None` means do not check.
If the output is too large, steps will raise `OutputTooLargeError` exception. This exception is subclassed from `RuntimeError`.
There is also an environmental defined, DMODEL_ALLOWED_MEMORY, that is queried if the step parameter is `None`.
> JP-1541 Implement memory check in resample to prevent huge arrays

- CHANGES.rst
- jwst/stpipe/pipeline.py
- jwst/stpipe/tests/steps/__init__.py
- jwst/stpipe/tests/test_pipeline.py
Resolves [JP-1712](https://jira.stsci.edu/browse/JP-1712)
Resolves #5350 
If a `Pipeline` has `prefetch_references == False`, do not attempt to prefetch any reference files for the Pipeline, or its steps.
Reviewers: The fix is the one-liner at pipeline.py:93
> Do not attempt prefetch on pipelines that are set to not allow prefetch

- CHANGES.rst
- jwst/ramp_fitting/ramp_fit.py
- jwst/ramp_fitting/tests/test_ramp_fit.py
- jwst/ramp_fitting/utils.py
Updated the `ramp_fitting` function `utils.fix_sat_ramps` to add the DQ flag 'DO_NOT_USE' to pixels that have all groups flagged as saturated. Also greatly simplified the whole function to get rid of looping over pixels and just use native `numpy` array indexing.
Fixes #5364 / [JP-1731](https://jira.stsci.edu/browse/JP-1731)
> JP-1731: Add DO_NOT_USE to pixels with all groups saturated

- CHANGES.rst
- jwst/flatfield/flat_field.py
- jwst/master_background/master_background_nrs_slits_step.py
Updates to a couple of steps to properly handle NRS_LAMP exposures in MSASPEC mode, which don't have any sources defined in their MSA metadata files. The `assign_wcs` step was already setup to handle this properly, in that any slitlet without a source assigned to it is classified as a background slitlet, so all lamp exposure slitlets get processed as background type. Added some checks to the new NIRSpec master_background step so that it does not compute or apply the master bkg spectrum when there are no background slits available or no source slits to apply it to (as is the case for lamp exposures). Also a fix to `flat_field` to properly classify NRS_LAMP exposures as spectroscopic type, rather than imaging.
Fixes #5365 / [JP-1732](https://jira.stsci.edu/browse/JP-1732)
> JP-1732: NRS MOS updates for lamp exposures with no sources

- CHANGES.rst
- jwst/datamodels/container.py
- jwst/datamodels/model_base.py
- jwst/datamodels/tests/test_models.py
- jwst/dq_init/tests/test_dq_init.py
- jwst/resample/resample_spec.py
- jwst/resample/resample_spec_step.py
From `asdf 2.8` onwards, `None` will not be stripped from the ASDF tree before serialization.  But `jwst.datamodels` currently depends on this behavior for a variety of reasons.
Lots of pipeline steps populate things in `meta` with `None`.  If we don't strip `None`, it causes a validation error for many of the items in our schemas, because `None` is not an allowed type.  The schema is expecting a string or number, not `None`.
So the solution is to strip any `None` values before save, and avoid populating attributes with `None` internally.
Other clean up:
- warnings were being emitted by `ModelContainer` for instruments that were not NIRCam.  A useless warning that I put in several years ago to detect malformed NIRCam simulated data.  No longer needed.
HT: @eslavich for way forward and the …
> JP-1679: Skip serializing None in datamodels

- CHANGES.rst
- jwst/datamodels/ramp.py
- jwst/datamodels/tests/test_open.py
- jwst/lib/basic_utils.py
Resolves [JP-1738](https://jira.stsci.edu/browse/JP-1738)
Resolves #5379 
Original deprecation implementation for `MIRIRampModel` used a function. However, this breaks tests that look for class comparisons. A class decorator, `deprecate_class` has been implement to enable full class deprecation.
> JP-1738 Implement full class deprecator decorator and use for MIRIRampModel

- jwst/ami/lg_model.py
Follow on to #5390 fixing a bug:
```
/Users/jdavies/dev/jwst/jwst/ami/ami_analyze_step.py:60: in process
result = ami_analyze.apply_LG_plus(input_model, throughput_model,
/Users/jdavies/dev/jwst/jwst/ami/ami_analyze.py:68: in apply_LG_plus
affine2d = find_rotation(data[:,:], psf_offset_find_rotation, rotsearch_d,
/Users/jdavies/dev/jwst/jwst/ami/find_affine2d_parameters.py:108: in find_rotation
jw.simulate(fov=npix, bandpass=bandpass, over=over, psf_offset=psf_offset)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <jwst.ami.lg_model.NrmModel object at 0x7fcbd73176a0>, fov = 80, bandpass = array([[1.0e+00, 4.3e-06]]), over = 11
psf_offset = (0.0, 0.0)
def simulate(self, fov=None, bandpass=None, …
```
> Fix ami bug in analyticnrm2.psf() call

- docs/jwst/source_catalog/arguments.rst
Remove `kernel_xsize` and `kernel_ysize` arguments from `source_catalog` step docs, because those params were removed from the step in a recent update.
> Update source_catalog argument list in step docs

- CHANGES.rst
- docs/jwst/saturation/description.rst
- jwst/saturation/saturation.py
- jwst/saturation/tests/test_saturation.py
Rework the way the saturation step handles pixels flagged with NO_SAT_CHECK in the saturation reference file. There are many occasions where pixels are flagged this way because they never actually go into full-well saturation before hitting the 16-bit A-to-D converter limit of 65535 DN (so no full-well saturation threshold can be determine). This leaves pixels unflagged in the science data, even though they have one or more groups in which the values are pegged at 65535. Without flagging, the ramp_fit step tries to do a fit and results in nonsensical slopes. So this change sets the saturation flagging threshold for NO_SAT_CHECK pixels at 65535, so any that are pegged at that value will get flagged as saturated and hence ramp_fit will ignore them.
This is a follow-on to the …
> Rework handling of NO_SAT_CHECK pixels in saturation step

- jwst/ramp_fitting/tests/test_ramp_fit.py
The original version of the test created `int_times` like this:
```
int_times = np.zeros((nints,7))
```
but when this was passed to `np.asanyarray` with the table's dtype, the result was a nints x 7 array of records, each with 7 fields, for a total of 245 numbers.  In other words, the single 0 at each array index was being broadcast to a full record.  I don't think this was the intended result, but we were getting away with it before due to a recently resolved [bug in astropy](https://github.com/astropy/astropy/pull/10768).
The new code:
```
int_times = np.zeros((nints,))
```
results in nints records, each with 7 fields, for a total of 35 numbers.  I confirmed that `test_int_times` now passes with both astropy 4.0.1 and 4.0.2 (the latter contains the bug fix).
Thanks @jdavies-st for …
> Fix construction of int_times table in test

- CHANGES.rst
- jwst/jump/tests/test_detect_jumps.py
- jwst/jump/twopoint_difference.py
Updated the `twopoint_difference` module in the `jump` step to try to eliminate some of the largest memory hogs. The single biggest change with the largest effect on memory usage is moving the flagging of neighbors from the end of the routine (after all integrations have been processed) to being inside the main loop over integrations. This completely eliminates the need for the `all_ratios` array, which was a huge 4-D float array the same size as the 4-D SCI data.
Also eliminated some of the smaller intermediate arrays that were used to do things like storing indexes of bad or saturated pixels. In addition, there's been just a huge amount of cosmetic cleanup to try to make the code more readable and just more efficient overall.
Somehow, these changes actually fixed some previously …
> JP-1735: Reduce jump step memory usage

- CHANGES.rst
- jwst/cube_build/data_types.py
- jwst/datamodels/model_base.py
- jwst/regtest/test_miri_cubebuild.py
- jwst/regtest/test_miri_mrs.py
Resolves [JP-1748](https://jira.stsci.edu/browse/JP-1748)
Resolves #5405 
Refactored `DataTypes` handling of `ModelContainer` to be more simplified and avoid premature closing of models before usage is completed.
> JP-1748 Refactor DataTypes handling of ModelContainer

- CHANGES.rst
- jwst/datamodels/model_base.py
Resolves followup issue with JP-1748.
Since `DataModel.close` is called from `DataModel.__del__`, a `DataModel` that is still open when a Python process closes, it is possible that the logging module is no longer available, resulting in the error
```
ImportError: sys.meta_path is None, Python is likely shutting down
```
Since logging at this point is normally not required, simply remove the logging statement.
> JP-1748 Remove logging from DataModel.close

- jwst/datamodels/tests/data/collimator_fake.asdf
- jwst/datamodels/tests/test_models.py
- jwst/datamodels/tests/test_open.py
Fixes the following recently-introduced warnings in our tests:
```
jwst/datamodels/tests/test_models.py::test_skip_fits_update[False-open-just_fits-None-FGS_DARK]
jwst/datamodels/tests/test_models.py::test_skip_fits_update[False-open-just_fits-False-FGS_DARK]
jwst/datamodels/tests/test_models.py::test_skip_fits_update[False-open-just_fits-True-FGS_DARK]
jwst/datamodels/tests/test_models.py::test_skip_fits_update[True-open-just_fits-None-FGS_DARK]
jwst/datamodels/tests/test_models.py::test_skip_fits_update[True-open-just_fits-False-FGS_DARK]
jwst/datamodels/tests/test_models.py::test_skip_fits_update[True-open-just_fits-True-FGS_DARK]
/Users/jdavies/dev/jwst/jwst/datamodels/util.py:188: NoTypeWarning: model_type not found. Opening …
```
> Fix warnings in datamodels

- CHANGES.rst
- docs/jwst/extract_1d/arguments.rst
- docs/jwst/extract_1d/description.rst
- docs/jwst/references_general/extract1d_reffile.inc
- jwst/extract_1d/extract.py
- jwst/extract_1d/extract1d.py
- jwst/extract_1d/extract_1d_step.py
- jwst/extract_1d/tests/test_extract_src_flux.py
- jwst/extract_1d/tests/test_fit_background_model.py
- jwst/extract_1d/tests/test_ifu_image_ref.py
- jwst/extract_1d/tests/test_wcs.py
- jwst/regtest/test_nircam_tsgrism.py
Updates to the extract_1d step to allow for an EXTRACT1D reference file to be used for NRC_TSGRISM mode, so that necessary column-by-column background extraction and subtraction can be performed. Previously the code was hardwired to not use EXTRACT1D ref file params for NRC_TSGRISM mode, which defaulted to very simplistic extraction with no background subtraction.
In addition to enabling the use of the reference file for this mode, a new parameter `bkg_fit` has been added, which now allows the user to specify whether to perform the default polynomial fit to background values or do simple mean and median computations. Functions to perform the mean and median background computations have been added to the code. Note that even when mean/median are used, the background model is still created …
> JP-1478: extract_1d enhancements for NRC_TSGRISM

- jwst/regtest/test_miri_mrs_spec2.py
- jwst/regtest/test_miri_mrs_spec3.py
- jwst/regtest/test_nirspec_ifu_spec2.py
- jwst/regtest/test_nirspec_steps_spec2.py
Splitting up some of the regtest modules that contain both spec2 and spec3 tests for MIRI and NIRSpec IFU modes, which are notoriously slow to run. Segregated the spec2 and spec3 tests into their own modules and also put the NIRSpec IFU spec2 step-specific tests into their own module (separate from the generic spec2 pipeline test).
> Split up some long-running regtest modules

- CHANGES.rst
- jwst/pipeline/calwebb_image3.py
This PR allows `skymatch` step to run even for a single input image. This essentially will become simple sky background subtraction without matching. Also see helpdesk issue INC0159018.
> Allow skymatch/skysub for one image

- jwst/jump/tests/test_detect_jumps.py
Follow on from #5404 and #5412.
Cleans up `setup_inputs` test fixture in `test_detect_jumps.py` to only return what the tests need, and to reduce redundancy with defaults already in use in the runtime code.
> Simplify test setup fixture in jump detection

- .codecov.yml
- JenkinsfileRT
Make the `nightly` tests flag _carryforward_ so that we can see the coverage of the repo from both unit and nightly tests combined.  This should also only compare CI unit tests to previous coverage of CI unit tests, not to coverage of the nightly tests.  🤞 
Also, make threshold be 0.1% so that when a few lines of code are deleted, the `codecov/project` check doesn't fail because the denominator has gotten smaller.
Resolves #4920
> Use Codecov carryforward flags

- docs/jwst/introduction.rst
- docs/jwst/stpipe/call_via_call.rst
- docs/jwst/stpipe/call_via_run.rst
- docs/jwst/stpipe/index.rst
- docs/jwst/stpipe/user_step.rst
This PR makes some small tweaks/additions to the documentation on the ways to call pipelines and steps from within python. The changes highlight the differences between the `call` and `run` methods and describe how to provide input parameters for each. After numerous questions/errors from users in the building on the details for how to call the pipeline, I was motivated to try and clarify the documentation. 
I realize that there is upcoming work on the methods used to call the pipeline and the details/best practices may change. I figured that these changes will still help people using the pipeline between now and then, and perhaps these changes can be used as a springboard for future documentation updates after any changes to the methods.
Resolves #5425
> Documentation update on ways to call the pipeline

- CHANGES.rst
- jwst/ami/ami_analyze.py
Update the `ami_analyze` module to extract the equivalent of a SUB80 subarray from input images that were taken in full-frame mode.
Fixes #5436 / [JP-1764](https://jira.stsci.edu/browse/JP-1764)
> JP-1764:Update ami_analyze to extract subarray from full-frame images

- CHANGES.rst
- jwst/extract_1d/extract.py
Updated the branch of extract_1d that loops over slit models in an input `SourceContainerModel` to handle the case where there's only 1 `SlitModel` and hence it's not in the form of a list. This can occur in level 3 processing of WFSS observations, for example, when there's only 1 instance of a given source in all of the input exposures.
Fixes #5331 / [JP-1693](https://jira.stsci.edu/browse/JP-1693)
> JP-1693: Fix extract_1d for SourceContainer with 1 slit

- docs/jwst/pipeline/calwebb_detector1.rst
- jwst/pipeline/calwebb_tso1.cfg
Set the `rscd` step to be skipped in the `calwebb_tso1.cfg` pipeline configuration. Update the docs too.
Fixes #5438 / [JP-1765](https://jira.stsci.edu/browse/JP-1765)
> JP-1765: Turn off RSCD step for MIRI TSO

- readthedocs.yml
We've had this lingering V1-style config file which only recently started breaking the readthedocs build.  It seems like they must have changed the order of precedence of the files when multiple are present?  In any case, removing the old config seems to fix the build, here's a pass on this branch:
https://readthedocs.org/projects/jwst-pipeline/builds/12209132/
> Remove V1 readthedocs config file

- CHANGES.rst
- jwst/skymatch/skyimage.py
- jwst/skymatch/skymatch.py
Fixes a bug in `skymatch.skymatch._apply_sky()` that would result in a crash when `skymethod` contains 'global' and input image is a single image group whose sky cannot be computed, e.g., because its images contains no "good" pixels.
This bug was revealed after PR #5423 which permitted processing of single image/group inputs.
Fixes failing test `test_nircam_image.py::test_image3_closedfile`. The test will still be failing for two reasons:
1. Extra keyword 'S_SKYMAT' - that's expected
2. Small differences in many image pixels. This failure is not related to this PR and probably is caused by unrelated changes. This test was not OKified before because it was crashing.
> Fix _apply_sky in skymatch for single group input

- jwst/regtest/test_miri_lrs_slitless.py
The RSCD step was recently set to skip `calwebb_tso1.cfg`, so that step no longer gets execute in the MIRI LRS slitless mode regression test. Updated the test parameters to no longer check the rscd result.
> Remove rscd step from MIRI LRS slitless regtest

- jwst/datamodels/tests/test_open.py
- jwst/datamodels/util.py
JP-1734: Datamodels should be able to read and write ASDF files
Changed datamodel.open to read an ASDF file and instantiate a datamodel class listed in the ASDF file.
Fixes #5153 / [JP-1734](https://jira.stsci.edu/browse/JP-1734)
> JP-1734: Return correct DataModel subclass when reading an ASDF file

- CHANGES.rst
- jwst/datamodels/multiexposure.py
- jwst/datamodels/multislit.py
- jwst/datamodels/schemas/flatcorr.schema.yaml
- jwst/datamodels/schemas/pathlosscorr.schema.yaml
- jwst/datamodels/schemas/photomcorr.schema.yaml
- jwst/datamodels/schemas/slitdata.schema.yaml
- jwst/datamodels/slit.py
Update the slit-related data models to include flatfield and photom correction arrays needed for the NIRSpec fixed-slit master background correction step. All NIRSpec fixed-slit exposures use a `MultiSlitModel` when being processed by calspec2 steps following `extract_2d`. They also get reorganized by the `exp_to_source` step at the beginning of `calwebb_spec3` processing. The arrays are optional and hence only appear in the data models when actually used.
Fixes #5456 / [JP-1774](https://jira.stsci.edu/browse/JP-1774)
> JP-1774: Update datamodels to include flat and photom arrays

- jwst/flatfield/flat_field.py
Fix an error that was introduced in #5462, which was allowing some modes to jump out of an if-else block without actually creating the flat.
> Fix error NIRSpec flat-fielding

- CHANGES.rst
- docs/jwst/flatfield/main.rst
- docs/jwst/photom/main.rst
- jwst/lib/wcs_utils.py
- jwst/photom/photom.py
Updated the NIRSpec fixed-slit/MSA branch of the `photom_io` function to compute both uniform and point source conversion factors for the NIRSpec fixed-slit primary slit when it contains a point source. Both versions of the correction are stored in the output slit instance for use later by the `master_background` step, for applying corrections.
Note that the uniform source correction uses the WCS object to compute an uncorrected wavelength grid for the slit, while the point source correction uses the existing 2D wavelength array, because it contains corrected wavelengths. Once the `wavecorr` step gets updated to include the wavelength correction as another transform in the WCS object, the uncorrected wavelengths will need to be computed from the WCS by excluding that new transform.
Fixes …
> JP-1776: Update photom to compute uniform and ps corrections

- docs/jwst/master_background/description.rst
- jwst/master_background/expand_to_2d.py
- jwst/master_background/nirspec_utils.py
- jwst/master_background/tests/test_nirspec_corrections.py
Update the `master_background` step to apply appropriate flatfield, pathloss, and photom corrections to 2D master background images for NIRSpec fixed slits. For the primary slit it applies all flatfield, pathloss, and photom correction terms, while the secondary slits only get pathloss corrections (because flatfield and photom are identical for secondary slits, which don't have wavelength differences between point and uniform sources).
Fixes #5459 / [JP-1777](https://jira.stsci.edu/browse/JP-1777)
> JP-1777: NIRSpec Fixed-Slit master background corrections

- jwst/datamodels/schema.py
- jwst/model_blender/tests/test_blend.py
- scripts/move_wcs.py
This PR moves a couple of utility functions out of `datamodels.schema` and into the only modules that use them, so that they can be removed from stdatamodels without impacting jwst.
See https://github.com/spacetelescope/stdatamodels/pull/25
> Move utility functions out of datamodels.schema

- jwst/datamodels/tests/test_models.py
These tests are failing now on `master` and test for things that no longer exist in `stdatamodels` thanks to
https://github.com/spacetelescope/stdatamodels/pull/25
This is just to remove them and get `master` tests passing again.  A more thorough cleanup of the tests in `jwst.datamodels` is coming very soon.
> Remove tests for fits_required, get_section, iteritems

- .travis.yml
This PR adds a Python 3.9 job in Travis.
If we decide to deliver Build 7.7 to run in DMS under Python 3.9, then we should make Python 3.9 the default job in the matrix (and in the Jenkins runs) and remove the specific job added here.
> Add Python 3.9 to Travis jobs

- jwst/ami/leastsqnrm.py
- setup.cfg
The use of the `uncertainties` package is optional in the `jwst.ami` code.  But it brings in the unmaintained package `future` that are raising deprecation warnings in python 3.8+.  So let's not use it.
Resolves #5397 / [JP-1745](https://jira.stsci.edu/browse/JP-1745)
> JP-1745: Remove uncertainities dependency

- CHANGES.rst
- docs/jwst/associations/asn_from_list.rst
- docs/jwst/associations/asn_gather.rst
- docs/jwst/associations/commands.rst
- jwst/associations/__init__.py
- jwst/associations/asn_gather.py
- jwst/associations/lib/rules_level3.py
- jwst/associations/load_as_asn.py
- jwst/associations/tests/test_asn_gather.py
- scripts/asn_gather
`asn_gather` is a new API and command-line utility that basically allows one to copy an association, and all its members, from one place to another.
> Add utility asn_gather

- .readthedocs.yml
- .travis.yml
- README.md
- setup.cfg
Since Astropy 4.2 is now dropping support for Python 3.6, we will do the same.
> Drop support for Python 3.6

- .travis.yml
Our dev dependencies job on Travis CI was using released dependencies for the past week since we added `stdatamodels` master to `install_requires`.  It seems having an install from a URL changes the way `pip` resolves dependencies.
Putting the dev dependency install and the package install on separate lines solves this unexpected behavior.
> Fix Travis dev dependencies job

- .travis.yml
- jwst/lib/suffix.py
- jwst/pipeline/calwebb_dark.py
- jwst/pipeline/calwebb_detector1.py
- jwst/pipeline/rscd.cfg
- jwst/pipeline/tests/data/cfgs/rscd.cfg
- jwst/rscd/__init__.py
- jwst/rscd/rscd_step.py
Fixes #5424 to rename RSCD step.
Addresses JP-1755.
> JP-1755: Rename class RSCD_Step to preserve CRDS functionality. (#5424)

- CHANGES.rst
- jwst/tweakreg/tweakreg_step.py
- setup.cfg
Fixes https://github.com/spacetelescope/jwst/issues/3739.
Fixes [JP-820](https://jira.stsci.edu/browse/JP-820)
Also see https://github.com/spacetelescope/tweakwcs/pull/128
> JP-820: Add support for rshift fitting mode in tweakreg

- CHANGES.rst
- jwst/lib/suffix.py
- jwst/lib/tests/test_suffix.py
- jwst/stpipe/step.py
- jwst/stpipe/tests/test_utilities.py
- jwst/stpipe/utilities.py
This is code that is fallout from various other issues, JP-1751, CCD-381, and CCD-783.
The changes are
- `jwst.stpipe.utilities.all_steps`: Return all classes defined in the package that are subclassed from `Step`. This includes a slight refactor of the `suffix` code.
- Bug fix in `jwst.stpipe.Step.get_config_from_reference` to not attempt retrieval of step parameter references files when input is not a `DataModel`.
> Implement utility function all_steps and fix crds reference file retrieval for non-datamodels

- CHANGES.rst
- jwst/lib/set_telescope_pointing.py
- scripts/v1_calculate
Driven by SDP analysis needs, added the logging of the quaternion information to `set_telescope_pointing`.
> Add logging of the found quaternion information to set_telescope_pointing 

- .travis.yml
- scripts/minimum_deps
This will hopefully prevent the "oldest dependency versions" job from failing when a package (like stdatamodels) is being installed from GitHub instead of pypi.
> Allow packages installed from GitHub to pass through the minimum_deps script

- CHANGES.rst
- jwst/wfs_combine/wfs_combine.py
Update DQ handling in `wfs_combine` so that only pixels with the DO_NOT_USE flag are considered bad, rather than any pixel with DQ > 0.
Fixes [JP-1763](https://jira.stsci.edu/browse/JP-1763)
Fixes #5435
> JP-1763: fix dq flag handling in wfs_combine

- jwst/stpipe/tests/test_logger.py
The test in jwst/stpipe/tests/test_logger.py changes the stpipe logging configuration but doesn't set it back, which I think is responsible for some of the issues we've been seeing with pytest-openfiles checks.  This PR adds a fixture that restores the default logging configuration after that test.
> Reset logging configuration after test

- CHANGES.rst
- jwst/assign_wcs/nirspec.py
- jwst/lib/exposure_types.py
- jwst/pipeline/calwebb_spec2.py
- jwst/resample/gwcs_drizzle.py
- jwst/resample/resample_spec.py
- jwst/resample/resample_utils.py
Addresses [JP-1733](https://jira.stsci.edu/browse/JP-1733)
Fixes #5366
> Enable resample_spec for NIRSpec line lamp exposures

- docs/jwst/pipeline/main.rst
Update the exposure-type vs pipeline modules chart in the pipeline docs to show that MIRI LRS slitless exposures with TSOVISIT=False do not receive any level 3 processing. Also fixed the entry for NRS lamp exposures, now that we're capable of processing them through level 2b.
Fixes #5522 / [JP-1801](https://jira.stsci.edu/browse/JP-1801)
> JP-1801: Update MIRI LRS slitless docs

- CHANGES.rst
- jwst/tso_photometry/tests/test_tso_photometry.py
- jwst/tso_photometry/tso_photometry.py
- jwst/tso_photometry/tso_photometry_step.py
This PR updates the `tso_photometry` step for input data units in `MJy/sr`.  The output catalog columns are now astropy `Quantity` objects with units of `Jy`.
Addresses part of https://jira.stsci.edu/browse/JP-1559
CC: @hbushouse, @tapastro
> Fix units in tso photometry catalog

- CHANGES.rst
- docs/jwst/assign_wcs/main.rst
- jwst/assign_wcs/assign_wcs_step.py
- jwst/assign_wcs/tests/test_wcs.py
- jwst/datamodels/schemas/wcsinfo.schema.yaml
- jwst/resample/tests/test_resample_step.py
- jwst/wfs_combine/tests/test_wfs_combine.py
This adds a SIP approximation to the assign_wcs step for imaging modes.
gwcs.to_fits_sip is used to compute the linear & polynomial distortion terms. The degree of the polynomial is not supplied, but chosen from the best fit of degrees <= 6. The PC/cdelt/naxis keywords in wcsinfo are removed, and the CD matrix terms as well as all the polynomial coefficients are added. The updated wcsinfo schema includes these new keywords. 
@cshanahan1 Remaining tasks:
Resolves #4673 / [JP-1347](https://jira.stsci.edu/browse/JP-1347)
> JP-1347: Add SIP approximation to meta.wcsinfo for imaging modes

- jwst/resample/resample.py
- jwst/resample/tests/test_resample_step.py
A follow-on from #5507 to allow `resample` to handle input data that now has CD matrix and SIP coeffs.
Addresses #4673 / [JP-1347](https://jira.stsci.edu/browse/JP-1347)
> Update resample to handle SIP coeffs in input data

- CHANGES.rst
- jwst/lib/set_telescope_pointing.py
Addresses #5453 and [JP-1771](https://jira.stsci.edu/browse/JP-1771)
> Set_telescope_pointing to handle zero values for pointing mnemonics in engineering database

- CHANGES.rst
- jwst/assign_wcs/tests/test_util.py
- jwst/assign_wcs/util.py
Subarray bounding boxes are now the correct size.  Before they were 1 pixel too small.
Resolves #5542 / [JP-1818](https://jira.stsci.edu/browse/JP-1818)
> Fix bug in assign_wcs.util.bounding_box_from_subarray function

- CHANGES.rst
- docs/jwst/saturation/description.rst
- jwst/datamodels/dqflags.py
- jwst/saturation/saturation.py
- jwst/saturation/tests/test_saturation.py
Closes #4690.
Fixes [JP-1357](https://jira.stsci.edu/browse/JP-1357)
One side effect of this update to the saturation check is that values of zero for a group is now flagged as AD_FLOOR and DO_NOT_USE.  This is fine for real data, but for simulated data where it might be common to initialize all the values to zero, this might now cause issues.
> JP-1357: Code, tests, and docs to update saturation step to test for groups at the A/D floor (0 DN)

- CHANGES.rst
- jwst/assign_wcs/nirspec.py
Resolves #5539 / JWSTDMS-461 / [JP-1816](https://jira.stsci.edu/browse/JP-1816)
Mark Nirspec slits which project on less than one pixel as invalid.
> NRS slits should be larger than 1 pixel

- CHANGES.rst
- jwst/ami/ami_analyze.py
- jwst/ami/ami_analyze_step.py
Updates for ami analyze for JP-1742
The two new input parameters are 'set_psf_offset_find_rotation' and 'set_rotsearch_d' 
These seems a bit long. When I was testing I tripped up the exact name of the parameter. Maybe we could use something shorter- maybe 'set_psf_offset'  'set_rotsearch' - suggestions - or just leave it as it is.
Fixes #5388 / [JP-1742](https://jira.stsci.edu/browse/JP-1742)
>  Update Ami analyze to input two new input parameters: JP-1742

- CHANGES.rst
- jwst/skymatch/skyimage.py
Fixes https://github.com/spacetelescope/jwst/issues/5565 (SKYMATCH GLOBAL is NAN)
> Fix a crash in skymatch when using mode on 1 pixel

- jwst/regtest/test_miri_mrs_extract1d.py
Added a new regtest module to run just the `extract_1d` step on a MIRI MRS data cube, with the source type set to POINT, in order to test the point-source branches within `extract_1d`. The data is from a set of simulations created by the MIRI team, which actually contains an extended source, but I just reset the source type value to say POINT.
> Add new extract_1d regtest for MIRI MRS

- requirements-sdp.txt
- setup.cfg
I had removed this in #5569 as we now use a Github action for codecov uploads from our Github CI, but I forgot we still need this for uploading coverage from our regression test runs on Jenkins.  So adding it back.
Funny enough (or not funny?), the step didn't fail, even though the codecov executable was not found.  🤔 
https://plwishmaster.stsci.edu:8081/job/RT/job/JWST/999/execution/node/198/log/
> Add back codecov to dependencies for regtests

- .github/workflows/ci.yml
To catch upstream changes. I guess you might find daily too daunting, so I have it run weekly. If you only want subset of the jobs to run in cron, we can either add a `if` or have a separate YAML.
cc @jdavies-st
> TST: Add weekly cron

- tox.ini
I see that you use the new `--strict` option but it is only available for `twine>=3.3`. This pins `twine` in the setup to prevent developers having older twine in their tox env encountering error. Should be uncontroversial enough?
cc @jdavies-st
> TST: Pin twine for --strict

- CHANGES.rst
- jwst/assign_wcs/tests/test_schemas.py
- jwst/datamodels/schemas/distortion.schema.yaml
- jwst/datamodels/wcs_ref_models.py
In debugging #5543 yesterday, warnings in the `assign_wcs` tests indicated that there was an inconsistency between the distortion model schema and what the `validate()` method for that model was requiring.  `validate()` was requiring that `meta.instrument.channel` be populated, but the `channel` node was not actually in the schema.  And this issue was being masked by the `validate()` code short-circuiting the real validation error message.  So we were seeing the below:
```
$ pytest jwst/assign_wcs/tests/test_schemas.py 
=============================== test session starts ===============================
platform darwin -- Python 3.9.0, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: /Users/jdavies/dev/jwst, configfile: setup.cfg
plugins: asdf-2.7.1, requests-mock-1.8.0, doctestplus-0.8.0, …
```
> Fix distortion reffile schema and unit test

- jwst/combine_1d/combine_1d_step.py
- jwst/cube_build/cube_build_step.py
- jwst/extract_1d/extract_1d_step.py
- jwst/outlier_detection/outlier_detection_step.py
- jwst/pipeline/calwebb_ami3.py
- jwst/pipeline/calwebb_coron3.py
- jwst/pipeline/calwebb_dark.py
- jwst/pipeline/calwebb_detector1.py
- jwst/pipeline/calwebb_guider.py
- jwst/pipeline/calwebb_image2.py
- jwst/pipeline/calwebb_spec2.py
- jwst/resample/resample_spec_step.py
- jwst/resample/resample_step.py
Updated all of the pipeline modules to update the FILETYPE value for at least the main product that they produce, as well as intermediate products that are saved by the pipeline module itself. Several of the major level 3 steps, such as `outlier_detection`, `resample`, and `extract_1d`, have their products created by `stpipe` when the step finishes and returns control to the pipeline module. Hence for those the step module itself has to do the updating, because the product has already been saved by the time control is returned to the pipeline module.
This only updates FILETYPE for standard products that are routinely created and archived during Ops processing. It would be far too messy and complicated to have every step make an update. If anyone has suggestions for alternate FILETYPE …
> JP-1743: Update FILETYPE keyword in standard products

- jwst/cube_build/cube_build_step.py
- jwst/pipeline/cube_build.cfg
This is a follow-on to https://github.com/spacetelescope/jwst/pull/5574 which fixed issues related to param settings in cfg files. @drlaw1558 reported that the default value for `weight_power` should be 2, which it was set to in the `cube_build.cfg` file, but in the step spec it was set to zero. So if the step is ever run without the .cfg file you'd get the wrong value. This updates the default value in the step spec to 2.0 and removes the param from the .cfg file.
> Update cube_build weight_power default value

- jwst/cube_build/cube_build_wcs_util.py
Need a better fix once we figure out how to determine what the units of the wavelength are. Works for now
> Fix internal_cal cubes for NIRSpec Lamp exposures 

- jwst/extract_1d/extract.py
Fixes a bug introduced in the latest `extract_1d` updates. There's a certain corner case (WFSS observations) where the data coming into `run_extract1d` are in a ModelContainer, as opposed to a simple data model, hence trying to access `model.meta.exposure.type` throws an AttributeError, because it needs to be `model[0].meta.exposure.type`.
> Fix bug in latest extract_1d update

- CHANGES.rst
- jwst/lib/set_telescope_pointing.py
- jwst/lib/tests/test_set_telescope_pointing.py
- jwst/regtest/test_nircam_tsimg.py
The set_telescope_pointing script has been updated to populate the XREF_SCI and YREF_SCI keywords for *all* TSO exposures, as indicated by TSOVISIT=T, instead of only populating them for NIRCam TSO grism exposures. They are needed for imaging modes, since the tso_photometry step was recently updated to use them (instead of CRPIX1, CRPIX2).
Fixes #5612 / [JP-1846](https://jira.stsci.edu/browse/JP-1846)
> JP-1846: Populate X/YREF_SCI keywords for all TSO

- CHANGES.rst
- jwst/cube_build/cube_build.py
- jwst/cube_build/cube_build_step.py
This fixes problems that were encountered when trying to run the `calwebb_spec2` pipeline on an ASN file that contains a list of multiple products, in which case the pipeline loops over the processing for each product one at a time. The `cube_build` step was failing on the 2nd iteration (processing for the 2nd product) due to step param values having been modified during the 1st iteration.
Fixes [JP-1560](https://jira.stsci.edu/browse/JP-1560)
Fixes #5115
> fix for running cube build in spec2 on a list of files

- CHANGES.rst
- jwst/cube_build/ifu_cube.py
- jwst/datamodels/schemas/core.schema.yaml
- jwst/datamodels/schemas/referencefile.schema.yaml
Update datamodels schemas for all keyword changes documented in [JP-1799](https://jira.stsci.edu/browse/JP-1799), in order to keep our schemas in sync with the Keyword Dictionary.
Fixes #5610
Fixes [JP-1848](https://jira.stsci.edu/browse/JP-1848)
Fixes [JP-1849](https://jira.stsci.edu/browse/JP-1849)
> JP-1848: Schema updates for new and modified keywords

- .readthedocs.yml
Reverts spacetelescope/jwst#5631
Well that didn't work.  Apparently RTD doesn't support python 3.9 yet.
Approve and merge this at will.
> Revert "Update .readthedocs.yml to use python 3.9"

- CHANGES.rst
- jwst/associations/lib/rules_level2b.py
- jwst/lib/tests/test_engdb_mock.py
Original test hid bug in how the constraints were setup. New case using JW00620, which covers a number of different LAMP modes, has been added to the regression.
Note: When this PR is merged, the regression data found in `jwst-pipeline/jwstdms-420-nolamp/associations` need to replace development data `dev/associations`.
> JWSTDMS-410 Asn_Lv2NRSLAMPSpectral: Break out the negative cases

- scripts/okify_regtests
- setup.cfg
This adds some added functionality to the `okify_regtests` script:
- Hitting the `o` or `s` keys alone is now sufficient to okify or skip a regtest.  No typing `[return]` needed.
- Colored text makes output a bit easier to read.
- Added `q` keystroke to quit script.
Unrelated, add some more classifiers for `jwst` on PyPI.
> Update okify_regtests script

- .github/workflows/ci.yml
Allow skipping and cancelling CI in GitHub Actions.
The skip CI part is demonstrated in this PR. I have `[skip ci]` in the commit message, so the skip CI job would fail and prevent the rest from running.
cc @jdavies-st @eslavich 
Close #5591
> TST: Allow skip and cancel CI

- CHANGES.rst
- jwst/combine_1d/combine1d.py
Resolves [JP-1622](https://jira.stsci.edu/browse/JP-1622)
Resolves #5204
First PR had a code error, using an incorrect index parameter. This fix should create distinct extensions with appropriate wavelength and flux vectors.
> JP-1622: Combine1D should output separate extensions for each spectral order

- jwst/stpipe/jwst.py
- jwst/stpipe/step.py
This creates a `Step.finalize_result` hook that allows `Step` subclasses to set mission-specific metadata on each result before it is saved.  I also moved the `Step.record_step_status` method to `JwstStep` since it's only used in the master background steps and the Roman schemas don't include those metadata fields.
> Add hook to finalize Step results

- CHANGES.rst
- jwst/white_light/white_light.py
Resolves [JP-1831](https://jira.stsci.edu/browse/JP-1831)
Resolves #5566 
Changed a ">=" to a ">" when comparing final integration index to length of array, due to 1-indexing.
> JP-1831: white_light incorrectly rejecting int_times table for multi-segment data

- jwst/stpipe/jwst.py
- jwst/stpipe/step.py
This PR adds a `Step.remove_suffix` method that is then overridden in `JwstStep`.  This breaks away more JWST-specific code from the base `Step` class.
> Add overrideable remove_suffix method to Step

- CHANGES.rst
- jwst/ramp_fitting/ramp_fit.py
- jwst/ramp_fitting/tests/test_ramp_fit.py
- jwst/ramp_fitting/tests/test_ramp_fit_cases.py
Update the function in ramp_fitting that attempts to estimate the max number of segments that will be needed to fit any pixel, given the number of CR and DO_NOT_USE flags that break up each pixel's ramp. Previously the function only looked for CR (JUMP_DET) flags, but a recent update to the saturation step allows for adding DO_NOT_USE flags to groups with values below the A-to-D floor (< 0). So now the ramp for a given pixel can be broken into multiple segments due to both JUMP_DET and DO_NOT_USE flags, so we need to check for both. Checking for only JUMP_DET was causing the data arrays to be created too small to hold data from all segments, leading to an "index out of bounds" error when trying to stuff data into the array.
Fixes #5630 / [JP-1860](https://jira.stsci.edu/browse/JP-1860)
> JP-1860: Fix ramp_fit counting of segments

- CHANGES.rst
- jwst/lib/set_telescope_pointing.py
- jwst/lib/tests/test_pipe_utils.py
Updated the TSO check in set_telescope_pointing to use a combination of the `is_tso()` function and EXP_TYPE values, instead of relying solely on the value of TSOVISIT. This handles corner cases that have TSOVISIT=False and NINTS=1, which would normally come back as False for the TSO test, to come back as True when EXP_TYPE is a hardwired TSO mode.
Fixes #5656 / [JP-1873](https://jira.stsci.edu/browse/JP-1873)
> JP-1873: Fix set_telescope_pointing TSO logic

- CHANGES.rst
- README.md
- docs/index.rst
Update CHANGES.rst and README.md for 0.18.3 release.
Docs landing page now has an installation section at the top:
Resolves #5617 / [JP-1851](https://jira.stsci.edu/browse/JP-1851)
> Add basic installation instructions to docs landing page

- jwst/extract_1d/tests/test_apply_apcorr_ifu.py
These are failing using `asdf` master.  Not sure why they are not failing now, as a table is being accessed after the file is closed.  @eslavich ?
https://github.com/jdavies-st/asdf/runs/1760011694?check_suite_focus=true#step:6:456
> Fix premature closing of file in apcorr reffile tests

- .github/workflows/ci.yml
This is an automated update made by the `batchpr` tool :robot: to because `action-skip-ci` has moved to a proper organization! You can report issues to @pllim.
xref OpenAstronomy/action-skip-ci#8
> MNT: action-skip-ci has moved

- .github/workflows/ci.yml
Action needs long hash now. https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions
You merged #5675 too fast... 😆
> TST: Action needs long hash now

- CHANGES.rst
- docs/jwst/ramp_fitting/description.rst
Resolves [JP-1667](https://jira.stsci.edu/browse/JP-1667)
Resolves #5300 
Added an explanation of the optimal weighting algorithm to the documentation for the ramp_fitting step.
Also fixing bad PR numbers in changelog for older tickets.
> JP-1667: Update documentation for optimal weighting in ramp_fitting Pt. 2

- docs/jwst/ramp_fitting/description.rst
Resolves [JP-1667](https://jira.stsci.edu/browse/JP-1667)
Re: [this page.](https://jwst-pipeline.readthedocs.io/en/latest/jwst/ramp_fitting/description.html)
Needed to make my square root longer.
> JP-1667: Typo in documentation math

- jwst/conftest.py
Missed that there was trailing whitespace in the docstring, causing a failing `flake8` check on master branch.  Fixing and making the docstring a bit cleaner.
A follow-on to #5680
> Update TestDescriptionPlugin docstring

- CHANGES.rst
- jwst/datamodels/schemas/multispec.schema.yaml
- jwst/datamodels/schemas/slitmeta.schema.yaml
- jwst/extract_1d/ifu.py
This address JP-1880 - adding SRCTYPE to x1d products for IFU data. In addition, the datamodels.multispec was added updated to include the x and y center of the extraction region:  extraction_x & extraction_y. 
Fixes #5674 / [JP-1880](https://jira.stsci.edu/browse/JP-1880)
> JP-1880: added source_type, x & y extraction center to extracted 1d spec for IFU data

- CHANGES.rst
- jwst/extract_1d/extract.py
This PR address [JP-1706](https://jira.stsci.edu/browse/JP-1706), GitHub issue #5344
X1d files for NIRISS WFSS data have SCI extensions
The code change will affect other types of data run with extract1d since the change is in do_extract1d in extract.py This should fix the science header being in all the x1d products. IFU data is handled a bit differently but there was already a fix for IFU extract1d data.
> JP-1706 added updating only PRIMARY header of output_file

- jwst/pipeline/calwebb_ami3.py
- jwst/pipeline/calwebb_coron3.py
- jwst/pipeline/calwebb_dark.py
- jwst/pipeline/calwebb_detector1.py
- jwst/pipeline/calwebb_guider.py
- jwst/pipeline/calwebb_image2.py
- jwst/pipeline/calwebb_image3.py
- jwst/pipeline/calwebb_spec2.py
- jwst/pipeline/calwebb_spec3.py
- jwst/pipeline/calwebb_tso3.py
- jwst/step.py
- jwst/stpipe/cmdline.py
- jwst/stpipe/entry_points.py
- jwst/stpipe/integration.py
- jwst/stpipe/step.py
- jwst/stpipe/tests/conftest.py
- jwst/stpipe/tests/steps/__init__.py
- jwst/stpipe/tests/steps/dummy_with_alias.cfg
- jwst/stpipe/tests/test_entry_points.py
- jwst/stpipe/tests/test_integration.py
- jwst/stpipe/tests/test_step.py
- jwst/stpipe/tests/test_utilities.py
- jwst/stpipe/utilities.py
- setup.cfg
This PR:
- Adds support for a `class_alias` class attribute that allows steps/pipelines to define a short name (like "calwebb_detector1") that can be used in lieu of a class name.  This can be used in the "class" field of a config file or as an argument to strun.
- Sets `class_alias` on all existing pipelines to the name of the config file without the .cfg extension.
- Adds a new `jwst.step` module that imports all non-Pipeline steps available to the user.
- Adds an entry point that stpipe uses to gather a list of installed Step subclasses.
> Add entry point for registering lists of step classes and implement Step.class_alias

- jwst/datamodels/container.py
- jwst/stpipe/jwst.py
- jwst/stpipe/pipeline.py
- jwst/stpipe/step.py
- jwst/stpipe/tests/steps/__init__.py
It turns out, stpipe only uses ModelContainer in its capacity as a sequence -- iterating over the component models and performing operations on them.  This PR makes ModelContainer a subclass of collections.abc.Sequence and changes stpipe to perform `isinstance(foo, Sequence)` checks instead of `isinstance(foo, ModelContainer)`.  This should be enough to allow us to leave ModelContainer behind when we move stpipe to an independent package.
Regression test run: https://plwishmaster.stsci.edu:8081/job/RT/job/eslavich-dev/59
> Break stpipe dependence on ModelContainer

- CHANGES.rst
- jwst/extract_1d/extract1d.py
Updated the `fit_background_model` function in extract1d.py to check for zero weights before calling `LinearLSQFitter` to fit background values in a given image column. When the total weight of all pixels is zero, it causes an error return from the fitter.
Also includes some flake8 clean-up and other cosmetic changes.
Fixes #5625 / [JP-1856](https://jira.stsci.edu/browse/JP-1856)
> JP-1856: Trap zero-weight columns in extract_1d

- jwst/stpipe/function_wrapper.py
- jwst/stpipe/hooks.py
- jwst/stpipe/jwst.py
- jwst/stpipe/pipeline.py
- jwst/stpipe/step.py
- jwst/stpipe/subproc.py
This is a sneaky dependence on `JwstStep` that I hadn't noticed before.  I updated `Step.datamodels_open` to use the parent class's implementation if available, which allows the hook subclasses to be mission-agnostic.
> Use parent datamodels_open method if available

- CHANGES.rst
- jwst/ramp_fitting/ramp_fit.py
- jwst/ramp_fitting/tests/test_ramp_fit_cases.py
Updated the low-level `fit_2_group` function in ramp_fitting to properly handle the situation where NGROUPS=2 and the group 2 is saturated, but group 1 is OK. Hence the group 1 value can be used to compute a countrate. The problem in the existing code was that the variance for a pixel like this was being set to 0 in `fit_2_group`, but when those results got returned to the calling function it was throwing out all results with variance=0, so slopes and other quantities were not getting computed.
I've simply set the variance to 1 in this function, which allows for the proper computation of slope, variances, and error once it returns to the calling routine.
Fixes #5715  / [JP-1910](https://jira.stsci.edu/browse/JP-1910)
> JP-1910: Fix ramp_fit handling of saturated ngroups=2 data

- CHANGES.rst
- jwst/datamodels/schemas/core.schema.yaml
Resolves [JP-1886](https://jira.stsci.edu/browse/JP-1886)
Resolves #5690 
Added '1LOS' to PATTTYPE enum list in core.schema datamodel.
> JP-1886: Add '1LOS' to PATTTYPE enum

- .github/workflows/ci.yml
See https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/
> TST: Remove custom CI skip

- .github/workflows/ci.yml
- conftest.py
- jwst/conftest.py
- scripts/echo_crds_context
- tox.ini
- Set CRDS_CONTEXT=jwst-edit in tox instead ci.yml
- Add a header line to the pytest report to show the used CRDS_CONTEXT.
$ pytest jwst/datamodels/tests/test_validation.py 
============================== test session starts ==============================
platform darwin -- Python 3.9.1, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
crds_context: jwst_0672.pmap
rootdir: /Users/jdavies/dev/jwst, configfile: setup.cfg
plugins: requests-mock-1.8.0, cov-2.11.1, ci-watson-0.5, xdist-2.2.1, asdf-2.7.2, openfiles-0.5.0, forked-1.3.0, doctestplus-0.9.0
collected 3 items                                                               
jwst/datamodels/tests/test_validation.py ...                              [100%]
=============================== 3 passed in 0.81s ===============================
Resolves …
> Fix CRDS_CONTEXT setting in CI workflow

- CHANGES.rst
- jwst/associations/lib/rules_level2b.py
Resolves [JP-1876](https://jira.stsci.edu/browse/JP-1876)
Resolves #5664 
Added new association rule, modified regression test results for two association pools.
NOTE: This PR requires edits to the regtest truth files.
> JP-1876: Add new Lvl2 association rule for NRSLAMPImage

- docs/jwst/data_products/product_types.rst
A user pointed out that there was no mention of the calwebb_tso1 pipeline config in the data products page, so I added it.
> Add calwebb_tso1 to data products docs

- JenkinsfileRT
- JenkinsfileRT_dev
- jwst/datamodels/model_base.py
- jwst/datamodels/tests/test_models.py
- jwst/datamodels/util.py
- setup.cfg
To support Roman storing astropy.time.Time objects in meta.date, the code that automatically maintains that attribute will be removed from stdatamodels starting in version 0.2.0 (not yet released).  This PR re-implements that feature in JwstDataModel using a new hook that we added to the base DataModel class.
This PR should *not* be merged before jwst 0.18.0 is released, since stdatamodels 0.2.0 will include other changes that may cause trouble for jwst.  I'm mainly opening the PR now so I don't forget about it.
> Add automatic meta.date management to JwstDataModel

- CHANGES.rst
- jwst/srctype/srctype.py
This update to the srctype step simply unsets the value of the global target-based source_type in the data model when processing NIRSpec MOS exposures, so that it can't mistakenly get used later on, because MOS mode data should always and only use the slit-specific value of srctype. This was triggering a problem downstream in the photom step, which was making use of the model.meta.target.source_type value and ignoring the slit-specific values.
Fixes #5714 / [JP-1906](https://jira.stsci.edu/browse/JP-1906)
> JP-1906: Fix handling of SRCTYPE for MOS

- CHANGES.rst
- jwst/datamodels/util.py
- jwst/stpipe/core.py
This PR 
- defines a default `output_ext` from the base `stpipe.Step` class to `JWSTStep` to prevent romancal from writing FITS files by default. I tested this on one step using `strun`.
- Unpinned stdatamodels and tested with the latest release - 0.2.
- This revealed a straggler `Model._files_to_close` attribute which was replaced with the new `FileReference` object.
This PR depends on spacetelescope/stpipe#17
> move output_ext to jwst.Step

- jwst/regtest/test_nirspec_mos_spec2.py
- jwst/regtest/test_nirspec_mos_spec2_steps.py
Reorganizing these tests as the the step-level test should not be using the module-scoped fixture as they use different datasets.  Moving these to a separate module as well.
> Reorganize NIRSpec MOS spec2 regression tests

- CHANGES.rst
- jwst/photom/photom.py
- jwst/regtest/test_nirspec_ifu_spec2.py
Update the function in the photom step that handles NIRSpec IFU data, so that it checks for SRCTYPE='EXTENDED' and converts the calibration given in MJy to MJy/sr, and update all necessary keyword values appropriately. Previously it had been just applying the point-source calibration (in MJy) to all IFU data, regardless of source type.
Fixes #5735 / [JP-1919](https://jira.stsci.edu/browse/JP-1919)
> JP-1919: Fix photom handling of NRS IFU extended sources

- CHANGES.rst
- jwst/assign_wcs/fgs.py
- jwst/assign_wcs/miri.py
- jwst/assign_wcs/nircam.py
- jwst/assign_wcs/niriss.py
- jwst/assign_wcs/nirspec.py
- jwst/assign_wcs/pointing.py
- jwst/assign_wcs/tests/test_nircam.py
- jwst/assign_wcs/tests/test_niriss.py
- jwst/assign_wcs/tests/test_pointing.py
- setup.cfg
This PR adds support for velocity aberration correction in WCS. It needs thorough review.
It was decided, after a couple of iterations, that DVA correction will be applied as a separate transformation from the `v2v3` frame to a new, VA-corrected, `v2v3` frame that will be called `'v2v3vacorr'` in WCS pipeline.
The code applies a constant scale DVA correction in the (almost-)tangent plane `v2-v3` at Colin Cox suggestion. However, for when non-linear effects may become important, this PR also includes commented out full set of transformations from the spherical `v2,v3` coordinates to a tangent plane and then applying constant scale transformation in that plane and then backward transformation to the (DVA-corrected) spherical coordinates `v2,v3`.
> JP-1762: Add VA correction to WCS

- CHANGES.rst
- jwst/group_scale/group_scale.py
- jwst/group_scale/group_scale_step.py
- jwst/group_scale/tests/test_group_scale.py
- jwst/regtest/test_miri_dark.py
Partially resolves [JP-1805](https://jira.stsci.edu/browse/JP-1805)
Blocked by [AL-456](https://jira.stsci.edu/browse/AL-456)
Main issue is inappropriate context manager usage in `group_scale_step`.
Secondary issue is that `stdatamodels.model_base.DataModel` does not manage opened file resources across shallow copies.
> JP-1805 Fix premature model closing in group_scale_step

- jwst/associations/lib/diff.py
This makes the failure traceback reporting much more compact in Pytest by not printing the full code of the assertion helpers when a test fails.  If `compare_asn_files()` is used outside of Pytest, this has no effect.
There may be more of these assertion helpers, but these are the ones I came across.
Traceback with this PR:
```
___________________ TestSDPPools.test_against_standard[jw00626_20190605t025021_pool] ____________________
self = <jwst.regtest.test_associations_sdp_pools.TestSDPPools object at 0x7ff6d04f0a90>
pool_path = 'sdp/pools/jw00626_20190605t025021_pool.csv', slow = False
def test_against_standard(self, pool_path, slow):
"""Compare a generated association against a standard
Success is when no other AssertionError occurs.
"""
pool = Path(pool_path).stem
proposal, version_id …
```
> Silence traceback of associations diff test helpers

- CHANGES.rst
- jwst/assign_wcs/fgs.py
- jwst/assign_wcs/miri.py
- jwst/assign_wcs/nircam.py
- jwst/assign_wcs/niriss.py
- jwst/assign_wcs/nirspec.py
This PR changes the case of V2-V3 axes for NIRSPEC from `V2`->`v2` and adds axes names for `v2v3` frames for other instruments. This takes care of https://github.com/spacetelescope/jwst/pull/5602#discussion_r577934002 and item `#4` in https://github.com/spacetelescope/jwst/issues/5746#issue-807568325
This PR also fixes units for the `v2v3` frame for NIRCAM (`u.deg`->`u.arcsec`) as described in item `#2` in https://github.com/spacetelescope/jwst/issues/5746#issue-807568325.
However, I have noticed many other (than `v2v3`) frames also do not have axes names.
Resolves #5770 / [JP-1931](https://jira.stsci.edu/browse/JP-1931)
> JP-1931: Add/Rename V2-V3 frame axes names

- CHANGES.rst
- jwst/cube_build/cube_build.py
- jwst/cube_build/cube_build_step.py
- jwst/cube_build/data_types.py
- jwst/cube_build/file_table.py
- jwst/cube_build/ifu_cube.py
- jwst/cube_build/instrument_defaults.py
This PR closes JP-1828. An update to the NIRSpec cube_pars reference file is required that sets up the default spectral and spatial scaling to use in building the for NIRSpec lamp mode data. This reference file update is being tracked by CRDS-401. Once the reference file has a row for each NIRSpec lamp mode filter/grating combination (opaque + G140M, G140H, G235M, G235H, G395M or G395H) this PR will be able to read this reference file and create internal_cal type IFU cubes. 
Partially resolves #5562 / [JP-1828](https://jira.stsci.edu/browse/JP-1828). Requires [CRDS-401](https://jira.stsci.edu/browse/CRDS-401) for a complete solution.
> JP-1828 cube_build creating NIRSPEC lamp mode IFU data

- CHANGES.rst
- jwst/associations/lib/rules_level2_base.py
- jwst/regtest/test_associations_sdp_pools.py
- jwst/regtest/test_associations_standards.py
Resolves [JP-1936](https://jira.stsci.edu/browse/JP-1936) / #5779 
JP-1903 #5721 introduced a warning when duplicate associations product names are found. For Level 3 this is a crucial warning. However, for Level 2, this warning is meaningless; duplicate product names are expected, since all product names are just exposure names. Hide the warning while processing Level 2 associations.
Side note: the duplicate products are filtered out, regardless of the warning level.
> JP-1936 Ignore duplicate product names while handling Level 2 associations

- CHANGES.rst
- jwst/associations/lib/rules_level3.py
Resolves [#1918](https://jira.stsci.edu/browse/JP-1918)
Resolves #5732 
In the end, the solution to the errant x1dints entry in the initial association was to have it removed with a new constraint, as it was a background exposure. This caused a duplicate association warning, as the group association entries now exactly overlapped with the coronography association. The end result removes an association from the output of asn_generate.
> JP-1918: Remove errant background exposures from Coron3 associations

- jwst/regtest/test_fgs_image2.py
The pipeline was being run 3 times in this regtest.  Instead, it should be run once, with the tests parametrized.
This won't changes the results of the test.  Only make it more efficient.  And the `suffix` labeling will make it easier to read the results.
> Streamline FGS image2 pipeline regtest

- CHANGES.rst
- JenkinsfileRT
- JenkinsfileRT_dev
- jwst/datamodels/schemas/core.schema.yaml
- jwst/outlier_detection/outlier_detection.py
- jwst/outlier_detection/outlier_detection_scaled.py
- jwst/outlier_detection/outlier_detection_scaled_step.py
- jwst/outlier_detection/outlier_detection_spec.py
- jwst/outlier_detection/outlier_detection_stack_step.py
- jwst/outlier_detection/outlier_detection_step.py
- jwst/resample/gwcs_drizzle.py
- jwst/resample/resample.py
- jwst/resample/resample_spec.py
- jwst/resample/resample_step.py
- jwst/resample/resample_utils.py
- jwst/resample/tests/test_resample_step.py
- jwst/resample/tests/test_utils.py
This adds `weight_type="ivm"` as the default weight scheme for `ResampleStep`.
This will obviously cause changes in the _s2d.fits, _i2d.fits, _x1d.fits and _cat.ecsv outputs in our regression tests.  Further, some of the input _rate.fits files (NIRSpec MOS) do not have `var_rnoise`, so when it is accessed, it is all zeros, which gives zero weight to everything in the output.  So those will have to have dummy `var_rnoise` arrays added to the input files.
Resolves #800 / [JP-1657](https://jira.stsci.edu/browse/JP-1657)
> JP-1657: Make ivm default weight_type for resample

- requirements-sdp.txt
Pulls in the bugfix release `asdf 2.7.3` into `requirements-sdp.txt`.  Previously, the `asdf` library was writing out unreadable FITS files for numpy arrays that were views over a larger arrays and were stored in as `AsdfInFITS`.
Resolves #5699 / [JP-1911](https://jira.stsci.edu/browse/JP-1911)
> JP-1911: Bump asdf==2.7.3 in requirements-sdp.txt

- .github/workflows/ci.yml
- .github/workflows/ci_cron.yml
We are not running unit tests using `requirements-dev.txt`.  This remedies that problem by running it at least weekly.  If it fails, it will not interfere with approval of PRs, though we will get emails about it.  And it can also be triggered manually if needed.
> Add dev dependencies workflow as weekly cron

- CHANGES.rst
- jwst/associations/lib/rules_level3.py
Resolves [JP-1883](https://jira.stsci.edu/browse/JP-1883)
Resolves #5683 
Removing the constraint disallowing PATTTYPE='none' fixes the pool provided in the ticket, and existing pools with no PATTTYPE provided also generate spec3 associations. 
The mistyped EXP_TYPE in the provided ticket will create a spec3 association despite the included exposures all being external flats - this is being addressed in [JSDP-1749](https://jira.stsci.edu/browse/JSDP-1749)
> JP-1883: Remove PATTTYPE constraint for undithered MIRI MRS

- jwst/assign_wcs/util.py
Resolves [JP-1863](https://jira.stsci.edu/browse/JP-1863)
Resolves #5640 
This changes the center of the extraction bounding box from: 
- an average in grism pixel space 
to:
- the sky position, transformed to the grism pixel space.
This has **not** fixed all offset issues, but my best guess in location of the remaining error would be in some combination of source astrometry and transform polynomials. Would like feedback from INS team.
> JP-1863: Correct offset in cross-dispersion axis for NIRISS WFSS extraction boxes 

- .github/workflows/ci.yml
- .readthedocs.yml
Pro: RTD gives you rendered doc preview on the PR.
Con: There is no way to manually cancel jobs on RTD.
cc @jdavies-st 
**Requires**
> TST: Move doc check to RTD

- CHANGES.rst
Managed to sneak a PR through without a requisite changelog entry - this adds the entry for #5809.
> JP-1863: Modify evaluation of grism bounding box center - Changelog

- CHANGES.rst
- jwst/lib/set_telescope_pointing.py
This PR address JP-1939
"update_mt_kwds" function in the "set_telescope_pointing" script populates the TARG_RA/TARG_DEC keywords with the same values computed for the MT_RA/MT_DEC keywords.
> JP-1939 update target ra,dec for moving targets

- jwst/srctype/srctype.py
Trivial update to add logging info when setting SRCTYPE values for WFSS exposures, as is already done for MOS mode.
> Add logging to srctype WFSS branch

- jwst/pathloss/tests/test_pathloss.py
This addresses #3962.  The test passes and I checked the operation of the function by hand and it is working as intended.
> Removed skip for test_interpolate_onto_grid, function works as designed

- jwst/stpipe/tests/steps/python_pipeline.cfg
- jwst/stpipe/tests/test_pipeline.py
The following unit tests
```
jwst/stpipe/tests/test_pipeline.py::test_pipeline
jwst/stpipe/tests/test_pipeline.py::test_pipeline_commandline
```
leave behind some FITS files after you run the unit tests which show up as untracked files
```
$ git status
On branch pep8-more-checks
Your branch and 'upstream/master' have diverged,
and have 14 and 2 different commits each, respectively.
(use "git pull" to merge the remote branch into yours)
Untracked files:
(use "git add <file>..." to include in what will be committed)
jwst/stpipe/tests/output.fits
jwst/stpipe/tests/steps/DUMMY.fits
nothing added to commit but untracked files present (use "git add" to track)
```
The bug is because these tests are so old, they don't actually test properly the current `stpipe` infrastructure.  They each use a …
> Clean up stpipe unit tests that leave behind files

- jwst/ramp_fitting/ramp_fit.py
Addresses #5701 / [JP-1887](https://jira.stsci.edu/browse/JP-1887)
This is one in a series of PR's designed to refactor ramp fitting to make it more readable, maintainable, and reusable.  
This PR is used to break down the function `ols_ramp_fit`.  It is over 700 lines long, but has four distinct steps, which have been encapsulated in four different functions that `ols_ramp_fit` calls.  
- `ramp_fit_miri_multigroups()`, deals with the special case of MIRI data with multiples groups in an integration, resizing the data for discarded groups.
- `ramp_fit_first_pass()`, does the "first pass" over the data to compute the initial values related to slope computation.
- `ramp_fit_second_pass()`, does the "second pass" over the data using the intermediate results from the first pass to compute …
> JP-1887: Refactoring `ols_ramp_fit` into smaller more manageable functions

- jwst/source_catalog/source_catalog.py
The PR removes an outdated and unneeded docstring in a private method (as mentioned in a comment in https://jira.stsci.edu/browse/JP-1839).  The CI calculation is fully described starting on line 1003 in the `concentration_indices` method.
> Remove outdated docstring

- CHANGES.rst
- jwst/cube_build/cube_build_step.py
This PR fixes [JP-1957](https://jira.stsci.edu/browse/JP-1957) the typo in the cube_build_step spec is fixed. Fixes #5830
> JP-1957 fix typo in cube_build spec

- CHANGES.rst
- jwst/datamodels/schemas/core.schema.yaml
Updated the keyword titles for several of the NIRSpec GWA (grating wheel assembly) keywords, to keep in synch with JWSTKD values. Triggered by [JWSTKD-423](https://jira.stsci.edu/browse/JWSTKD-423).
Resolves [JP-1959](https://jira.stsci.edu/browse/JP-1959)
Resolves #5834
> JP-1959: Update NIRSpec GWA tilt keyword comments

- setup.cfg
Having removed this line in #5837, it seems we need it there, as our nightly regression tests are recursing into `jwst/timeconversion` and throwing the following error:
```
jwst/timeconversion/time_conversion.py:53: in <module>
EPHEMERIS_PATH = os.environ['JPL_EPHEMERIS']
../miniconda/envs/tmp_env0/lib/python3.8/os.py:675: in __getitem__
raise KeyError(key) from None
E   KeyError: 'JPL_EPHEMERIS'
During handling of the above exception, another exception occurred:
jwst/timeconversion/__init__.py:1: in <module>
from .time_conversion import compute_bary_helio_time
jwst/timeconversion/time_conversion.py:55: in <module>
raise KeyError('Environmental variable JPL_EPHEMERIS not found')
E   KeyError: 'Environmental variable JPL_EPHEMERIS not found'
```
> Ignore timeconversion in pytest collection

- jwst/regtest/test_nirspec_masterbackground.py
This PR addresses a problem I recently noticed in the master bkg regression tests for the NIRSpec MOS mode. First, the existing test that used a user-supplied master bkg spectrum was still running the calspec3 master bkg step, instead of using the new NIRSpec-slit-specific version of the master bkg step that gets called from calspec2. I removed that entire test and replaced it with one that runs the data through calspec2, along with a user-supplied mbkg spectrum. I also fixed the naming and location of truth files for the equivalent test that runs MOS data through calspec2 and computes the mbkg spectrum from available bkg slits in the exposure.
All necessary input files and truth files for the new test have been uploaded to artifactory and the location of truth files for …
> Update and fix NIRSpec MOS master bkg regtests

- CHANGES.rst
- docs/jwst/associations/level2_asn_rules.rst
- docs/jwst/associations/level2_asn_technical.rst
- docs/jwst/associations/level3_asn_rules.rst
- docs/jwst/associations/level3_asn_technical.rst
- docs/jwst/associations/technote_sdp_workflow.rst
- jwst/associations/lib/rules_level2b.py
Closes #5893 
Resolves [JP-2005](https://jira.stsci.edu/browse/JP-2005)
This PR fixes the problem of having NIRISS WFSS grism exposure spec2 ASN's associate a direct image that uses a different filter than the grism image. The level-2b WFSS ASN rule has been updated to make sure the associated direct image has the same PUPIL value as the grism image, in the same way the NIRCam WFSS images must have the same channel value.
Finally managed (with much effort) to get new truth files for association regtests loaded into place properly in artifactory. When looking for WFSS-related parts of association docs to update I noticed the use of the DMS-specific "level" terminology, which I changed to the public-facing "stage" terminology. So this is all ready to go now.
Checklist
> JP-2005: Update NIS WFSS ASN rules for matching filter

- CHANGES.rst
- docs/jwst/tweakreg/README.rst
Closes #5841 
Resolves [JP-1963](https://jira.stsci.edu/browse/JP-1963)
This PR updates the "tweakreg" step docs to add the "rshift" option to the list of allowed values for the "fitgeometry" param. It also expands the list of allowed values to add a brief description of the meaning of each value.
Checklist
> JP-1963: Add rshift fitgeom option to tweakreg docs

- jwst/stpipe/tests/test_step.py
This test has been failing when run with asdf master due to the change in behavior around serializing `None` values.  This PR will allow the test to pass under both asdf 2.7.x and the upcoming asdf 2.8.
Checklist
> Fix test that fails with asdf master

- CHANGES.rst
- jwst/coron/align_refs_step.py
This fixes a call to `coron.align_refs_step.interpret_bit_flags` which I missed in #5898.
> Fix a call to interpret_bits in coron3

- requirements-dev.txt
This PR adds `stpipe` and `stcal` to the dev dependencies listed in `requirements-dev.txt`.  This file is used to specify dev dependencies in our weekly dev run of the regression tests in the RT/JWST-devdeps Jenkins job.
Checklist
> Add stpipe and stcal to dev deps

- CHANGES.rst
- jwst/assign_wcs/nirspec.py
- jwst/flatfield/flat_field.py
Closes #5807 
Resolves [JP-1949](https://jira.stsci.edu/browse/JP-1949)
This PR addresses a bug found when validating slits in the assign_wcs/nirspec code. Near-duplicate code had a missing slit_id shift caused by 0- vs 1- indexing of fixed slits vs msa slitlets - a slit on the edge of the detector in one bounding box was off the detector when calculated correctly. This near-duplicate code has also been cleaned up by calling a common function instead.
Note: Have not yet checked existing regtests, but could reasonably expect this to cause issues, as this moved the bounding box by ~2.5 pixels. Checking on this. 
Note2: Checked, the two nirspec_mos_spec2 regtests run without error.
Checklist
> JP-1949: MOS 0-sized bounding box extraction bug

- CHANGES.rst
- jwst/assign_wcs/nirspec.py
Closes #5938 
Resolves [JP-2033](https://jira.stsci.edu/browse/JP-2033)
This PR adds a quick check to make sure slits is not empty before sending it to validate_open_slits, which would fail on the slit_to_msa call if slits were empty.
Checklist
> JP-2033: Logic to send no open slits data to error message

- CHANGES.rst
- docs/jwst/refpix/description.rst
- jwst/refpix/reference_pixels.py
Closes #5936 
Resolves [JP-2032](https://jira.stsci.edu/browse/JP-2032)
This PR addresses JP-2032.  JP-1929 introduced a bug into the refpix step for 1-amp readout NIR subarrays.  This PR fixes it.  Unit tests and regression test now run.
Checklist
> JP-2032: Fix bug introduced when adding 4-amp subarray processing in refpix step

- JenkinsfileRT
This PR fixes an insecure interpolation warning seen in the upgraded Jenkins version we are running.  Single quotes make sure this line doesn't get echoed to the log.
Warning is here
https://plwishmaster.stsci.edu:8081/view/all/job/RT/job/JWST/1163/
The fix in this branch is here
https://plwishmaster.stsci.edu:8081/view/all/job/RT/job/jdavies-dev/230/
Ignore the failing Codecov checks below, as I only ran `pytest jwst/datamodels` tests to have it complete quickly on `plwishmaster`.  I only wanted to make sure the interpolation issue was fixed and that the codecov report worked.  The fact that the actual coverage of the repo went down is expected as I only ran a fraction of the tests.
> Fix insecure interpolation in Jenkinsfile

- CHANGES.rst
- jwst/resample/resample_spec_step.py
- jwst/resample/tests/test_resample_step.py
Addresses #5798 
Addresses [JP-1944](https://jira.stsci.edu/browse/JP-1944)
This PR allows propagation of the variance arrays of the inputs to `ResampleSpecStep`.  Previously these were being dropped on the floor when converting an `ImageModel` into a `SlitModel`, which happens in the case of MIRI LRS.
Regression tests pass on this branch.
This is of course needed if we are to use the variance arrays for weighting and to compute uncertainties in the resampled products.
> Propagate variance arrays into SlitModel used as input for ResampleSpecStep

- jwst/assign_wcs/nirspec.py
Closes #5921 
Resolves [JP-2022](https://jira.stsci.edu/browse/JP-2022)
This PR changes the slit validation requirement from needing one pixel in wavelength extent to two.
Checklist
> JP-2022: Fix flat field crash when given slit with single pixel wavelength range

- CHANGES.rst
- jwst/assign_mtwcs/tests/test_mtwcs.py
- jwst/outlier_detection/tests/test_outlier_detection.py
- jwst/regtest/test_nircam_image.py
- jwst/resample/resample_spec.py
- jwst/resample/resample_spec_step.py
- jwst/resample/tests/test_resample_step.py
Closes #5564
Resolves [JP-1829](https://jira.stsci.edu/browse/JP-1829)
This PR fixes the case where the WCS of the input images spans RA=0.
> JP-1829: Fix resample_spec output size from input images crossing RA=0

- CHANGES.rst
- docs/jwst/introduction.rst
Missed one place in earlier documentation updates where the new segmentation map product needed to be added. This is in the pipeline introduction, which gives a table listing all data product types. Added "segm" to the list.
Checklist
> Add segm to list of data products

- CHANGES.rst
- docs/jwst/background_step/arguments.rst
- docs/jwst/background_step/description.rst
- jwst/background/background_step.py
- jwst/background/background_sub.py
- jwst/regtest/test_miri_lrs_slit_spec2.py
Closes #3746
Resolves [JP-824](https://jira.stsci.edu/browse/JP-824)
This PR adds the option to save the combined background image model, in a method pulled directly from the optional flat_field output. Currently will not work as written, oops. Do we really need to close that bkg_model?
Checklist
> JP-824: Add option to save combined background image

- jwst/regtest/test_niriss_soss.py
This PR addresses an issue in the calwebb_tso3 regression test using NIRISS SOSS data. Recent updates to the outlier_detection step algorithm resulted in massive numbers of false positive detections in the particular dataset used in the regression test, just due to unrealistically noisy data. This update simply increases the value of the "snr" parameter in the outlier_detection step used in the test to reduce the number of detections.
Checklist
> Update NIRISS SOSS tso3 regression test

- CHANGES.rst
- jwst/refpix/tests/test_refpix.py
- jwst/regtest/test_nircam_subarray_4amp.py
Closes #5959
Resolves [JP-2046](https://jira.stsci.edu/browse/JP-2046)
Added regression test and unit test for NIR 4-amp readout subarrays.
This PR addresses JP-2046
Checklist
> Jp-2046: Refpix subarray 4amp tests

- .github/workflows/ci.yml
- .github/workflows/ci_cron.yml
- .github/workflows/publish-to-pypi.yml
- JenkinsfileRT
- JenkinsfileRT_dev
- jwst/stpipe/tests/test_config.py
Closes #5957 
Closes #5747
Resolves [JP-2045](https://jira.stsci.edu/browse/JP-2045)
This PR does the following:
- use Python 3.9 for SDP CI and nightly regtest builds
- ~add Python 3.10-dev to the CI matrix~ Oops, the numpy folks accidentally prevented their code from being built under Python 3.10 because they pinned `wheel` version in pyproject.toml
- remove pip caching in CI workflow (it masks build issues, see #5744 )
- add `asdf` install so `crds` caching works in CI workflow
Checklist
> JP-2045: Use Python 3.9 for SDP CI and regtests

- .gitignore
- CHANGES.rst
- jwst/lib/src/winclip.c
- jwst/lib/tests/test_winclip.py
- pyproject.toml
- setup.cfg
- setup.py
- tox.ini
This PR adds an algorithm for clipping multiple rectangles to clipping windows. Rectangles to be clipped must have sides parallel to coordinate axes. `get_clipped_pixels()` returns indices of the clipped pixels and their area.
This PR is to support commit https://github.com/spacetelescope/jwst/commit/af1d903e1aeff917397e86b65e26b8733df8f2c8 in #5508
CC: @hbushouse @nden
> Algorithm for clipping rectangles to rectangular windows

- CHANGES.rst
- docs/jwst/source_catalog/main.rst
- jwst/source_catalog/source_catalog.py
- jwst/source_catalog/source_catalog_step.py
This PR can be merged despite the resampled total-error array still being work-in-progress.  The `model.err` arrays are currently all zeros, so the photometry errors in the source catalog will be zeros until `model.err` is populated with the resampled total-error array.
Fixes #5182 / [JP-1611](https://jira.stsci.edu/browse/JP-1611)
> JP-1611: Calculate photometric errors using resampled total-error array

- jwst/source_catalog/source_catalog_step.py
This is a followup to #5997.  In that PR, I changed the `coverage_mask = np.isnan(model.err)`.  However, `model.err` is currently an array of all zeros (until @jdavies-st completes updates to `model.err`), thus i2d pixels with no data are not being masked (until `model.err` is populated).  In this PR, I've updated the coverage_mask to also include pixels where `model.wht == 0`, which fixes this issue (and should work fine after the upcoming updates).
I've tested this with `det_dithered_5stars_f770w_i2d.fits`.
> Fix source catalog coverage mask

- CHANGES.rst
- jwst/resample/resample_step.py
- jwst/resample/tests/test_resample_step.py
WCS keywords ra/dec/roll/v2/v3_ref are removed from im.meta.wcsinfo after ResampleStep.
Fixes #2225 / [JP-2039](https://jira.stsci.edu/browse/JP-2039)
> removing wcs keywords after resample

- jwst/source_catalog/source_catalog.py
This PR is a followup fix to #5998 where a source catalog with only 1 detected source would raise an error.
> Fix nn_label for only 1 detected source

- CHANGES.rst
- jwst/cube_build/cube_build_step.py
- jwst/cube_build/cube_build_wcs_util.py
- jwst/cube_build/ifu_cube.py
- jwst/pipeline/calwebb_spec2.py
This is the push of code to try and improve the cube_build speed.
In a separate PR #5969 - reworked NRS ifu wcs set_input to make it more efficient and faster. Also meta.wcsinfo.spectral_region is now filled in assign_wcs. That value along with meta.wcsinfo.s_region can be used to determine the initial size of the IFU to cover all the input data.
Using the above enhancements Cube_build now runs faster. A slight improvement in how the dq plane for MIRI data is determined was added. The calspec2 pipeline was changed and skip_dqflagging is set to True.  The DQ plane for calspec2 output contains all zeros. 
There may be further improvements, so I have left timing information in debug statements.
> Improve Cube build speed - JP 364

- CHANGES.rst
- jwst/assign_wcs/nircam.py
- jwst/extract_2d/grisms.py
- jwst/extract_2d/tests/test_grisms.py
Closes #4572 
Resolves [JP-1300](https://jira.stsci.edu/browse/JP-1300)
- Replace FITS WCS keywords in TSGRISM mode with RA/DEC_REF
- Add Spectral system info to slits in WFSS mode
Checklist
> JP-1300:TSGRIM and WFSS improvements

- CHANGES.rst
- jwst/tweakreg/tweakreg_step.py
Fixes #4601 / [JP-2079](https://jira.stsci.edu/browse/JP-2079)
> JP-2079: Fix a bug in tweakreg due to grouped models not being a list

- CHANGES.rst
- jwst/assign_wcs/util.py
- jwst/cube_build/cube_build_wcs_util.py
- jwst/cube_build/ifu_cube.py
- jwst/resample/resample_spec.py
This PR fixes a bug in the s_region value calculated in assign_wcs for data at ra = 0 (border)
The wrap_ra routine in cube_build was moved to assign_wcs. The import statement in resample_spec to use wrap_ra is not moved to point to assign_wcs.util
This work also supports JP-364 - improving the speed of cube_build by using the values in s_region
Closes #6019 
Resolves [JP-2076](https://jira.stsci.edu/browse/JP-2076)
> JP-2076 moved wrap_ra to assign_wcs

- CHANGES.rst
- jwst/assign_wcs/util.py
Fix problem  in wrap_ra when ra is a list instead of an array - which is the case for NIRSpec
> wrap_ra when input is list

- jwst/outlier_detection/outlier_detection.py
- jwst/outlier_detection/outlier_detection_spec.py
- jwst/regtest/test_fgs_image2.py
- jwst/regtest/test_miri_lrs_slit_spec2.py
- jwst/regtest/test_nircam_image.py
- jwst/regtest/test_nircam_mtimage.py
- jwst/regtest/test_nirspec_fs_spec3.py
- jwst/regtest/test_nirspec_mos_spec3.py
- jwst/regtest/test_nirspec_verify.py
- jwst/resample/gwcs_drizzle.py
- jwst/resample/resample.py
- jwst/resample/resample_spec.py
- jwst/resample/resample_step.py
- jwst/resample/resample_utils.py
Addresses #5798 / [JP-1944](https://jira.stsci.edu/browse/JP-1944)
This PR should be uncontroversial.  It doesn't change anything user-facing.  It does some necessary cleanup of the resample code, without changing any of the core functionality nor test results.  Highlights:
- Make calling of `ResampleData` and `ResampleSpecData` both return the resampled datamodel(s).  Before only one returned anything.
- Remove `single` as kwarg from `GWCSDrizzle` class init.  It doesn't do anything there.
- Always apply the DQ array, even if weighting is not specified (no effect now, as we always apply weight).  But we may want to not apply any weights in stage2 resampling.  Weighting has no meaning with a single input, but currently we do weight, which may have bad floating point …
> JP-1944: resample cleanup

- CHANGES.rst
- jwst/cube_build/cube_build_step.py
Closes #6029 
Resolves [JP-2081](https://jira.stsci.edu/browse/JP-2081)
This PR Removes unneeded WCS keywords from IFU cube output: ['v2_ref', 'v3_ref', 'ra_ref', 'dec_ref', 'roll_ref',
'v3yangle', 'vparity']
Checklist
> JP-2081 remove unneeded wcs keywords from IFU Cube 

- CHANGES.rst
- jwst/regtest/test_nirspec_ifu_spec3.py
- jwst/resample/resample.py
- jwst/resample/resample_step.py
Addresses #5798 / [JP-1944](https://jira.stsci.edu/browse/JP-1944)
This PR adds resampled variance and error arrays for imaging data run through `resample`.  The new error arrays in the resampled `i2d` files have the same names as in the `cal` files:
- `ERR`
- `VAR_RNOISE`
- `VAR_POISSON`
- `VAR_FLAT`
This PR also:
- Refactors `ResampleData` to split out the processing of `single` resampling, which is used for `outlier_detection` from the case used in stage2 and stage3 `ResampleStep`, where 1 or more inputs get resampled to a single output.
- Fixes a bug in the computation of total effective exposure time.
- Removes unused `ResampleData.update_driz_outputs` method (it's never been used as far back as we've been on Github)
- Marks the NIRSpec IFU regtest as `slow`, same as …
> JP-1944: Resample error and variance arrays for imaging data

- CHANGES.rst
- jwst/resample/resample.py
- jwst/resample/resample_spec.py
- jwst/resample/resample_spec_step.py
- jwst/resample/resample_step.py
- jwst/resample/tests/test_resample_step.py
Resolves #5798 / [JP-1944](https://jira.stsci.edu/browse/JP-1944)
This PR adds resampled variance and error arrays for spectral data run through `resample_spec`.  The new error arrays in the resampled `s2d` files have the same names as in the `cal` files:
- `ERR`
- `VAR_RNOISE`
- `VAR_POISSON`
- `VAR_FLAT`
This PR also:
- Makes the calling of drizzle from `ResampleStep` and `ResampleSpecStep` much more similar.
- Use the refactored code already implemented in `ResampleData` by subclassing it for `ResampleSpecData`.  In a future PR, we will get rid of `ResampleSpecData` altogether and have spectral/imaging differences handled at the top level by the `Step` code.
- No longer delete `bunit_err`.  We need it.
This branch contains all the changes from #6036, so that should be …
> JP-1944: Resample error and variance arrays for 2D spectral data

- jwst/regtest/test_nircam_align_to_gaia.py
Closes https://github.com/spacetelescope/jwst/issues/6034
Resolves [JP-2084](https://jira.stsci.edu/browse/JP-2084)
This is a follow-on to changes in downstream packages that fix #5455 
Dataset is the LMC calibration field, simulated in `mirage`.
> JP-2084: Add a regression test for aligning to GAIA

- CHANGES.rst
- jwst/source_catalog/source_catalog.py
Closes #5904
This PR depends on the metadata added in #6044.
> Scale circular apertures for non-native pixel scales in resampled data

- CHANGES.rst
- jwst/datamodels/schemas/core.schema.yaml
- jwst/lib/set_velocity_aberration.py
- jwst/lib/tests/test_utc_to_tdb.py
- jwst/lib/tests/test_velocity_aberration.py
- jwst/lib/utc_to_tdb.py
Closes #6048 
Resolves [JP-2087](https://jira.stsci.edu/browse/JP-2087)
This PR makes updates for recent changes in the KWD and SDP to the JWST position/velocity keywords, in particular the movement of the JWST_[XYZ] and JWST_[DXYZ] keywords from the primary header to the SCI extension header. Scripts that use these keywords have been updated to account for that change. The core datamodel schema has also been updated to move those keywords to the SCI header, and to add the new OBSGEO-xyz keywords. The OBSGEO-xyz keywords give the JWST position and velocity in the geocentric frame (in units of meters and meters/sec), while the old JWST_xyz keywords are being changed to give the position and velocity in the barycentric frame (in units of km and km/s). Note that the datamodel …
> JP-2087: Updates for JWST_XYZ keyword changes

- jwst/jump/jump.py
Jump detection wants a string to set the max number of cores used ('half', 'all', etc...). The default is 'none' but the code was checking for None type instead of the string.
> small fix for type of maximum_cores in jump detection

- .github/workflows/ci.yml
This doesn't let codecov uploads fail silently.
> Fail CI if codecov upload fails

- CHANGES.rst
- pytest_crds/plugin.py
- setup.cfg
- tox.ini
This PR makes the CRDS context reporting pytest plugin disabled by default, to prevent errors in unrelated test suites when CRDS is not configured.
Checklist
> Add --report-crds-context pytest option

- CHANGES.rst
- jwst/combine_1d/combine1d.py
- jwst/datamodels/schemas/combinedspec.schema.yaml
- jwst/datamodels/schemas/multicombinedspec.schema.yaml
Closes #6000 🎉 
Resolves [JP-2066](https://jira.stsci.edu/browse/JP-2066)
This PR adds source_type information to combine1d extensions of c1d.fits files, pulled from the x1d inputs to the Combine1D step.
Checklist
> JP-2066: Add srctype to Combine1D headers

- CHANGES.rst
- jwst/datamodels/schemas/core.schema.yaml
- jwst/lib/set_telescope_pointing.py
Closes #6078 
Resolves [JP-2106](https://jira.stsci.edu/browse/JP-2106)
Update the enum lists for a few keywords to bring them into synch with what's in the KWD for B7.8
Checklist
> JP-2106: Update keyword schema enum lists

- CHANGES.rst
- jwst/combine_1d/combine1d.py
Closes #6002 
Resolves [JP-2067](https://jira.stsci.edu/browse/JP-2067)
This PR adds units to the CombinedSpecModel table output of the Combine1D step. Flux and SB units are checked from the input spectra, while wavelength units are set to um.
Checklist
> JP-2067: Add units to combine1d product table

- CHANGES.rst
- jwst/associations/lib/rules_level2b.py
Closes #6084
Resolves [JP-2108](https://jira.stsci.edu/browse/JP-2108)
Checklist
> JP-2108 Asn_Lv2NRSLAMPSpectral: Allow msaspec only if msametfl is available.

- CHANGES.rst
- jwst/lib/set_telescope_pointing.py
This PR is a follow on to https://github.com/spacetelescope/jwst/pull/6081/ and JP-2106, which changed the allowed list of values for the ENGQLPTG keyword. The simple value "CALCULATED" is no longer allowed, so the set_telescope_pointing script is being updated to instead use the new allowed value of "CALCULATED_ORIGINAL".
Checklist
> Fix ENGQLPTG value populated by set_telescope_pointing

- jwst/lib/tests/data/calc_deltas_truth.ecsv
- jwst/lib/tests/data/v1_calc_truth.ecsv
- jwst/lib/tests/test_pointing_summary.py
- jwst/lib/tests/test_v1_calculate.py
Resolves #6003 / [JP-2068](https://jira.stsci.edu/browse/JP-2068)
This PR fixes 2 truth tables that have `dtype=object` in the ECSV headers.  That is apparently no longer allowed in astropy dev.  Changing it to `string` solves the problem.
The failing `Table.read()` call was also causing open file handle errors, which probably means that the internals of that function are not quite handling files correctly.  Will file an issue in `astropy` for both of these.
Also cleaned up reading of the FITS files with a context manager.  Apparently there is no `with` context manager for `Table.read`.
> JP-2068: Fix invalid ECSV test data headers

- jwst/assign_mtwcs/moving_target_wcs.py
- jwst/datamodels/container.py
- jwst/datamodels/tests/test_models.py
Closes #6095
Resolves JP-2112
assign_mtwcs gets as input a ModelContainer object and needs to modify the science exposures. instead it worked on all models in the container.l This PR 
- adds a method to ModelContainer which returns the indices of models with a certain "asn_exptype" in modelContainer._models.
- Modifies assign_mtwcs to work with the "science" exposures only.
The DMS failing test passes now. The assign_mtwcs step is still skipped because the data lacks the necessary keywords.
Checklist
> JP-2112 : assign_mtwcs should work on science asn_exptype only

- CHANGES.rst
- jwst/regtest/test_nircam_image.py
- jwst/tweakreg/tweakreg_step.py
Addresses #6039 /  [JP-2085](https://jira.stsci.edu/browse/JP-2085)
This PR
- ~avoids a bug in `asdf` which was making `_crf.fits` files unreadable due to the attaching of an `astropy.table.Table` object to the datamodel as an attribute not indicated in the schema in `TweakregStep`.  The solution is to delete the table before ending the step.~
- Regression test added, and added `use_output_model=True` as a default for this step so that output naming of saved results is based off the input name and not a stream of indices.
- Fixes a bug where sources outside of the bounding box of the WCS were not being masked.
Checklist
> JP-2085: Remove attached tweakreg catalog from datamodel

- CHANGES.rst
- jwst/outlier_detection/outlier_detection.py
Resolves #6116 / [JP-2128](https://jira.stsci.edu/browse/JP-2128)
This PR replaces the default interpolator ('linear') in blot (used in `outlier_detection`) used when interpolator is not specified with `'poly5'`. The `'poly5'` interpolator is the default one used in `drizzlepac` and it is extensively used (~= tested).
This PR does not solve the underlying issue in the `drizzle` package but should alleviate the issue described in #6116.
NOTE to maintainers. This is not a bug in the `outlier_detection` step per se and so I did not add the `bug` label but feel free to classify it as you wish.
> JP-2128: Switch default interpolation method in blot to poly5 instead of linear

- .github/workflows/ci.yml
- .github/workflows/ci_cron.yml
- jwst/regtest/test_nircam_mtimage.py
- tox.ini
Addresses #6126 / [JP-2134](https://jira.stsci.edu/browse/JP-2134)
- Fix CRDS caching between CI workflows
- Parallelize CI jobs via `pytest-xdist` across both cores of each worker
Checklist
> JP-2134: Speed up CI by a factor of 2

- CHANGES.rst
- jwst/ami/ami_analyze.py
- jwst/ami/ami_analyze_step.py
- jwst/ami/tests/test_ami_analyze.py
- jwst/ami/utils.py
Resolves #6122 / [JP-2132](https://jira.stsci.edu/browse/JP-2132)
Resolves #6108 / [JP-2123](https://jira.stsci.edu/browse/JP-2123)
This PR fixes a sign error in calculation of the pupil phase.
Also, it makes the logging of the rotation search parameters more clear.
Merging this will require the ami_analyze regression tests to be okified.
Checklist
> JP-2132: Fix AMI pupil phases sign error

- .github/workflows/cancel_workflows.yml
This changes the duplicate workflow canceling in Github Actions to only cancel duplicates of commits on PRs.  So if you rapid-fire commits to your PR, it will only have CI running on the latest commit, not several concurrently.  Previous runs are cancelled.
Currently this cancelling also happens on merges into `master`.  So if two major PRs get merged into `master` in short order, the 2nd will cancel CI of the first, making it not run to completion, and not report coverage for that commit on `master`.  If a new PR is opened, branched from that commit, then there will be no reported or accurate coverage to check the new PR against.  This PR prevents this from happening.
h.t. @pllim 
Checklist
> Only cancel duplicate CI on PRs, not merges into master

- CHANGES.rst
- jwst/outlier_detection/outlier_detection.py
This reverts commit 0a692e80572d1f9daa18894b12b3f0e19b975838.
Resolves #6116 / [JP-2128](https://jira.stsci.edu/browse/JP-2128)
This reverts the blotting interpolation to linear in `outlier_detection`.
This will cause some changes in regression tests, flagging more outliers in `outlier_detection` for 2D data, i.e. _crf, _s2d and _i2d and subsequent catalogs and segmaps that use them.
Checklist
> Switch default interpolation method in blot back to linear

- jwst/regtest/test_nircam_tsgrism.py
- jwst/regtest/test_nircam_tsimg.py
This PR makes the names of these tests unique.  If they both fail, because they have the same name, it makes OKifying them a 2-step process as the artifacts overwrite each other when pushed to artifactory.
Checklist
> Change names of NIRCam TS setpointing regression tests

- jwst/lib/suffix.py
- jwst/pipeline/emission.cfg
- jwst/pipeline/outlier_detection_stack.cfg
Resolves #4754 / [JP-1395](https://jira.stsci.edu/browse/JP-1395)
Resolves #3278
This removes `emission.cfg` for the no-longer-existing emission step that was removed in #4253.
Checklist
> JP-1395: Remove emmision.cfg

- docs/jwst/stpipe/user_pipeline.rst
- docs/jwst/stpipe/user_step.rst
This PR removes references to the `stspec` CLI tool from the documentation.  `stspec` is provided by the stpipe package, but is being removed in the next release.  The `strun --save-parameters` option and the `Step.export_config` method are available to users who need to know what parameters are available.
Checklist
> Remove references to stspec

- CHANGES.rst
- jwst/assign_wcs/niriss.py
This PR fixes a problem we saw in a unit test where the `specwcs` reffile was incompletely downloaded from CRDS and so `asdf.open()` failed.  When it failed, it was not closed, as it never went through `__exit__`.
~Not sure if this is a problem with the `with` context manager in `asdf.open()`, i.e. is heavy-lifting happening in `AsdfFile.__init__` that should be happening in `AsdfFile.__enter__`?  Not sure.~
~Regardless, in this case, as soon as `asdf.open(file)` was called, it opens it without using `__enter__`.  Is this a bug or feature in `asdf` @eslavich ?  Or just a small bug here.~
Separate issue filed in https://github.com/asdf-format/asdf/issues/1006
Also cleaned up a try/except block below.  `velosys` is guaranteed to be an attribute as it is in the schema.
Checklist
> Open specwcs reffile with context manager

- docs/jwst/extract_1d/description.rst
- docs/jwst/references_general/extract1d_reffile.inc
Resolves [JP-844](https://jira.stsci.edu/browse/JP-844)
This PR updates the extract_1d step docs to state that all reference file parameter values that give pixel indexes, such as `xstart`, `xstop`, `src_coeff`, `bkg_coeff`, are in the frame of the current image, not the frame of a larger image from which the data may have been extracted.
Checklist
> JP-844: Update extract_1d docs

- CHANGES.rst
- jwst/regtest/test_nircam_wfss_contam.py
- jwst/wfss_contam/observations.py
- jwst/wfss_contam/sens1d.py
- jwst/wfss_contam/wfss_contam.py
- jwst/wfss_contam/wfss_contam_step.py
Closes #6015
Resolves [JP-2074](https://jira.stsci.edu/browse/JP-2074)
This PR addresses updates the baseline wfss_contam step code to process all available spectral orders in a given grism exposure. Some restructuring of the underlying INS code was necessary to do this in a simple way, such that the initialization of the Observation class for the grism exposure no longer does anything that's order-dependent. All of the order dependencies are now contained in the functions that actually create the dispersed spectra.
Also includes some code cleanup and adds hooks for saving 2 kinds of intermediate data files.
Checklist
> JP-2074: Update wfss_contam to process multiple orders

- CHANGES.rst
- docs/conf.py
- jwst/pipeline/calwebb_spec2.py
- jwst/wfss_contam/wfss_contam_step.py
- setup.cfg
Closes #6181 
Resolves [JP-2173](https://jira.stsci.edu/browse/JP-2173)
This PR adds the `wfss_contam` step to the `calwebb_spec2` pipeline module, so that it can be applied to WFSS exposures. Note that until the step has gone through more rigorous testing and review by INS, it is being set to be skipped by default. A user has the option to apply the step, when/if desired.
Checklist
> JP-2173: Add wfss_contam step to calwebb_spec2

- CHANGES.rst
- jwst/extract_1d/extract.py
- jwst/extract_1d/extract_1d_step.py
Closes #6208 
Resolves [JP-2198](https://jira.stsci.edu/browse/JP-2198)
This PR fixes a problem with the SRCTYPE keyword not getting copied over to the x1d output of the extract_1d step when processing resampled MIRI LRS fixed-slit exposures. The problem lies in the fact that the `source_type` attribute is defined in the core schema within the `target` tree of meta data and also defined in the slitmeta.schema (for `SlitModel`). When the `resample_spec` step is applied to MIRI LRS fixed-slit exposures, the input is an `ImageModel` with SRCTYPE defined within the `target` part of the meta tree, but the output of `resample_spec` is a `SlitModel`, which is created without the SRCTYPE value getting copied to the `SlitModel`. The `extract_1d` is clever enough to look for SRCTYPE …
> JP-2198: Handle MIRI LRS SRCTYPE keyword in extract_1d

- CHANGES.rst
- docs/jwst/references_general/dark_selection.inc
- docs/jwst/references_general/dark_specific.inc
- jwst/datamodels/schemas/dark.schema.yaml
- jwst/datamodels/schemas/keyword_noutputs.schema.yaml
Closes #6168 
Resolves [JP-2166](https://jira.stsci.edu/browse/JP-2166)
This PR adds the NOUTPUTS keyword to the `DarkModel` schema for DARK reference files, at the request of the NIRCam team. Also updated the relevant sections of the DARK docs (*not* part of the dark web ...)
Checklist
> JP-2166: Add NOUTPUTS to DarkModel schema

- CHANGES.rst
- jwst/datamodels/dark.py
- jwst/datamodels/darkMIRI.py
- jwst/datamodels/schemas/dark.schema.yaml
Closes #5775
Resolves [JP-1932](https://jira.stsci.edu/browse/JP-1932)
This PR updates the DQ array definition in the DARK ref file data model schema to be uint32, instead of the old uint16. This model apparently got missed when all the others were updated to uint32.
Checklist
> JP-1932: Update DARK model schemas to use uint32 for DQ

- docs/conf.py
- jwst/ramp_fitting/tests/check_gls_stats.py
- setup.cfg
This PR attempts to resolve the doc build failure due to changes in sphinx_astropy 1.5.0.
Checklist
> Replace sphinx_astropy sphinx extension with pytest-doctestplus

- CHANGES.rst
- jwst/source_catalog/_wcs_helpers.py
- jwst/source_catalog/source_catalog.py
This PR fixes an issue where non-finite (NaN) positions can be calculated for garbage sources due to invalid 2D image moments, which in turn causes the source catalog step to fail.
Fixes #6180
Fixes #6220
Resolves [JP-2172](https://jira.stsci.edu/browse/JP-2172)
Resolves [JP-2203](https://jira.stsci.edu/browse/JP-2203)
> JP-2172: Fix issue with non-finite aperture positions

- CHANGES.rst
- jwst/datamodels/schemas/core.schema.yaml
Closes #6214 
Resolves [JP-2200](https://jira.stsci.edu/browse/JP-2200)
This PR adds 4 new dither pattern values to the PATTTYPE keyword enum list for MIRI Coronagraphic flats, as outlined in https://jira.stsci.edu/browse/JSOCINT-590
Checklist
> JP-2200: Add new MIRI Coron PATTTYPE values

- CHANGES.rst
- jwst/wfss_contam/wfss_contam.py
Closes #6231 
Resolves [JP-2211](https://jira.stsci.edu/browse/JP-2211)
This PR fixes a bug in the `wfss_contam` step when processing NIRISS WFSS grism exposures. The filters used in NIRISS WFSS are physically located in the PUPIL wheel, so you have to use the PUPIL keyword value for the filter name everywhere in the step code where the filter name is needed.
Checklist
> JP-2211: Fix wfss_contam handling of filter names

- CHANGES.rst
- docs/jwst/wfs_combine/arguments.rst
- docs/jwst/wfs_combine/main.rst
- jwst/wfs_combine/tests/test_wfs_combine.py
- jwst/wfs_combine/tests/test_wfs_combine_step.py
- jwst/wfs_combine/wfs_combine.py
- jwst/wfs_combine/wfs_combine_step.py
Closes #5974 
Resolves [JP-2051](https://jira.stsci.edu/browse/JP-2051)
This PR addresses JP-2051 that refers to the location of the combined image when WFS-COMBINE is run. The changes are to always shift the images in the positive x pixel direction. If the calculated offset is negative the first image will be shifted rather than the second image.
While making the changes for JP-2051, I added test cases for the refine option. This showed that the baseline code's cross correlation algorithm was not correct. It was unable to find the correct offset. I updated the algorithm to be correct, added 27 new unit tests, and updated the output FITS header and logs to contain the calculated shifts.   
Checklist
> JP-2051: WFS combine align dithers and Update Refine

- setup.cfg
@hbushouse pointed out that we need at least pytest-doctestplus 0.10.0 to build the docs.
Checklist
> Set pytest-doctestplus minimum version

- CHANGES.rst
- jwst/wavecorr/tests/test_wavecorr.py
- jwst/wavecorr/wavecorr.py
Closes #6074 
Resolves [JP-2103](https://jira.stsci.edu/browse/JP-2103)
In Nirspec FS mode the wavecorr step computes the position of the source in 
the aperture using `meta.dither.x_offset` and `meta.dither.y_offset` but did not update `slit.source_xpos` and `slit.source_ypos`. This PR updates the two attributes with the computed [position of the source in the slit.
Checklist
> JP-2103 : Update slit.source_x(y)pos (NRS FS mode) after computing them in wavecorr

- jwst/extract_1d/extract.py
- jwst/regtest/test_miri_lrs_slit_spec2.py
Addresses (but does not close) #6105 
Addresses [JP-2120](https://jira.stsci.edu/browse/JP-2120)
This PR adds test coverage for ImageModel inputs to Extract1dStep. **WIP**
Checklist
> JP-2120: Increase test coverage for ImageModel through Extract1dStep

- CHANGES.rst
- jwst/tweakreg/tests/test_tweakreg.py
- jwst/tweakreg/tweakreg_step.py
Resolves #6154 / [JP-2152](https://jira.stsci.edu/browse/JP-2152)
This PR adds an upper tweak threshold to `TweakregStep`.  I.e. any tweaks larger than 10 arcsec are probably due to poor data, poor catalogs, or both, and should be rejected.
This hard codes the threshold to be 10 arcsec.  But honestly, we could also use the existing `self.threshold` parameter in tweakreg of 1.0 arcsec as well.  Thoughts?  I don't want to add a separate parameter yet, as I don't think this is something users need to play with right now.  There are already too many knobs in this step to play with.
Checklist
> JP-2152: Add an upper tweak threshold to tweakreg

- CHANGES.rst
- jwst/resample/resample.py
- jwst/resample/tests/test_resample_step.py
Resolves #6154 / [JP-2152](https://jira.stsci.edu/browse/JP-2152)
This PR fixes the extreme memory consumption seen in resampling of variance arrays.  For the dataset that triggered this issue, memory consumption goes from ~29GB down to ~1.6GB.
This also fixes a bug in how the the resampled variances were combined previously.  Previously the combined variances were being over-estimated.
Checklist
> JP-2152: Refactor resample_variance_array to use less memory

- .github/workflows/ci.yml
- .github/workflows/ci_cron.yml
This turns off Github Actions caching between jobs.  It has not been working correctly lately, and seems to be causing issues as well.
Using a cache only seems to work on common branches, i.e. so `master` can use caches created on `master`, but not those created on branches on forks.  See the following:
https://github.community/t/actions-cache-cache-not-being-hit-despite-of-being-present/17956
These issues need to be resolved before it is turned on again.
Checklist
> Don't cache CRDS reffiles between Github Actions jobs

- CHANGES.rst
- jwst/assign_wcs/nirspec.py
Closes #5736 
Closes #2958 
Resolves [JP-488](https://jira.stsci.edu/browse/JP-488) and [JP-1920](https://jira.stsci.edu/browse/JP-1920)
The `bounding_box` for NIRSpec is sometimes significantly oversized in height (`y` direction). This was because the `~jwst.assign_wcs.compute_bounding_box` was very naive in how it computed the range of acceptable `y` values. The changes here take the bounding box "guessed" by this naive method and evaluate the transform, and then finds the exact bounds of where the spectral trace actually lands (the non-NaN values). These bounds are then used to compute an improved bounding box.
Checklist
> JP-488 and JP-1920: NIRSpec `bounding_box` is sometimes too large.

- CHANGES.rst
- jwst/wavecorr/tests/test_wavecorr.py
- jwst/wavecorr/wavecorr.py
Follow up of #6243 
Part of [JP-2103](https://jira.stsci.edu/browse/JP-2103)
This PR checks if the metadata (`meta.dither` ) necessary for `wavecorr` to work are populated and if not skips the step.
Checklist
> Guard against missing wavecorr metadata

- CHANGES.rst
- jwst/outlier_detection/outlier_detection.py
Closes #6145
Resolves [JP-2140](https://jira.stsci.edu/browse/JP-2140)
This PR adds logging of the number of new DO_NOT_USE pixels found in `OutlierDetectionStep`.
Also some general code cleanup to reduce the number of double negatives, unnecessary casting, improved docstrings, comment strings, etc.
Logging now looks like:
```
2021-08-03 10:13:45,375 - stpipe.Image3Pipeline.outlier_detection - INFO - Performing outlier detection on 4 inputs
2021-08-03 10:13:47,393 - stpipe.Image3Pipeline.outlier_detection - INFO - Drizzling (2048, 2048) --> (2071, 2050)
2021-08-03 10:13:50,942 - stpipe.Image3Pipeline.outlier_detection - INFO - Drizzling (2048, 2048) --> (2071, 2050)
2021-08-03 10:13:54,479 - stpipe.Image3Pipeline.outlier_detection - INFO - Drizzling (2048, 2048) --> (2071, …
```
> JP-2140: Log number of flagged outliers in outlier_detection

- setup.cfg
Follow-on to #6089
This reverts a change to the `[ephem]` extras dependencies that are causing
```
pip install jwst[ephem]
```
to fail.
Checklist
> Revert change pymssql dependency

- CHANGES.rst
- jwst/pipeline/calwebb_tso3.py
Closes #6174 
Resolves [JP-2170](https://jira.stsci.edu/browse/JP-2170)
This PR adds more robust checking to the end of the calwebb_tso3 pipeline to handle the case where all the results coming back from the `tso_photometry` step are null/None. This happens when the step is invoked for multiple exposures, but is skipped for all of them (due to issues like no TSOPHOT ref file found). This allows the pipeline to shutdown cleanly, without creating an output `phot` product, instead of crashing when trying to create that product from null data. Usually only happens we get NIRCam engineering mode exposures taken with one of the grism subarrays, which has the EXP_TYPE reset by the front-end to look like it's TSO mode, when it really isn't.
Checklist
> JP-2170: Make calwebb_tso3 more robust to null photometry results

- CHANGES.rst
- README.md
This PR updates the README and CHANGES to be in sync with the 1.3.1 patch that was a cherry-pick release off the `1.3.x` branch.
> Update README and CHANGES for 1.3.1 release

- jwst/lib/pointing_summary.py
Closes #6285
Resolves [JP-2252](https://jira.stsci.edu/browse/JP-2252)
This PR fix `jwst.lib.pointing_summary` docstring example to work under `astropy 5.0`.  `Table.__repr__` has changed between `astropy 4.3` and the dev version of `astropy 5.0`, so avoid using it in the documentation example.
Our weekly regression tests against dev dependencies (`requirements-dev.txt`) will pass once this is merged.
Checklist
> JP-2252: Fix jwst.lib.pointing_summary docstring example

- jwst/regtest/test_nirspec_lamp_fs_spec2.py
This PR adds `resample_spec` processing to our NIRSpec lamp regression test so that it is tested.
Truth file is on bytesalad and test passes locally.
Checklist
> Resample NIRSpec lamp data in regression test

- CHANGES.rst
- jwst/resample/resample_spec.py
- jwst/resample/resample_utils.py
Addresses #5931 / [JP-2027](https://jira.stsci.edu/browse/JP-2027)
This PR refactors `build_interpolated_output_wcs()` method in `resample_spec.ResampleSpecData`.  This method has grown too complex, and in order to fix #5931 / JP-2027 it needs a refactor.
This first refactor separates out the building of a rectified output WCS for a single input slit where the WCS maps only to the msa plane, not to sky, as is the case for line lamp data.  This is the most simple use case.  This is essentially a refactor of functionality added in #5484.
The regression test
```
$ pytest --bigdata jwst/regtest/test_nirspec_lamp_fs_spec2.py -v
```
tests the lamp portion of the code.
The remaining non-lamp data is tested by
```
$ pytest --bigdata jwst/regtest/test_nirspec_fs_spec* -v
```
All …
> JP-2027: resample_spec refactor for lamp data

- CHANGES.rst
- docs/jwst/source_catalog/arguments.rst
This PR fixes the source catalog `bkg_boxsize` type (from float to integer) in the documentation.  Reported in [JP-2260](https://jira.stsci.edu/browse/JP-2260).
Closes #6299 
Resolves [JP-2260](https://jira.stsci.edu/browse/JP-2260)
> Fix source catalog bkg_boxsize type in docs

- CHANGES.rst
- jwst/associations/lib/dms_base.py
- jwst/associations/lib/rules_level2b.py
Closes #6227
Resolves [JP-2209](https://jira.stsci.edu/browse/JP-2209)
This PR updates the level-2b ASN creation rules for NIRSpec lamp exposures, so that only modes that *can* be calibrated to level-2b get ASN's created for them. Others will not have ASN's created and hence processing won't be triggered.
Checklist
> JP-2209: Update NIRSpec Lamp ASN rules

- CHANGES.rst
- jwst/assign_wcs/tests/test_nirspec.py
- jwst/assign_wcs/util.py
This PR adds a function specific to NIRSpec IFU which given arbitrary RA, DEC, LAM computes which ones project on the detector as part of a specific slice. Needed for blotting in outlier detection. Algorithm confirmed by INS.
Checklist
> Nirspec: compute which ra,dec,lam project within a given IFU slice

- CHANGES.rst
- docs/jwst/master_background/description.rst
- jwst/lib/suffix.py
- jwst/master_background/__init__.py
- jwst/master_background/master_background_mos_step.py
- jwst/pipeline/calwebb_spec2.py
- jwst/regtest/test_nirspec_masterbackground.py
- jwst/step.py
- jwst/stpipe/integration.py
Closes #5910
Resolves [JP-2012](https://jira.stsci.edu/browse/JP-2012)
This PR addresses issues caused by JP-2012 to the regression tests - namely, that step parameter reference files link to the old naming scheme and refer to the MasterBackgroundNrsSlitsStep as master_background, while this had changed to master_background_nrs so that step_def names could match the aliases introduced. To fix this bug (as well as modify the existing name that no longer applies), this PR clears up some naming discrepancies but also changes MasterBackgroundNrsSlitsStep to a more reasonable MasterBackgroundMosStep.
Checklist
> JP-2012 Bug fix: Change MasterBackgroundNrsSlitsStep name

- CHANGES.rst
- docs/jwst/master_background/description.rst
- jwst/lib/suffix.py
- jwst/master_background/__init__.py
- jwst/master_background/master_background_nrs_slits_step.py
- jwst/pipeline/calwebb_spec2.py
- jwst/regtest/test_nirspec_masterbackground.py
- jwst/step.py
- jwst/stpipe/integration.py
Reverts spacetelescope/jwst#6321
The current CRDS server setup restricts modifications to jwst that would break the backward compatibility of the current OPS CRDS server state with jwst release b7.8.2. This PR requires edits to step parameter reference files that would break the compatibility of OPS with b7.8.2, so needs to be reverted until either b7.9 or a new CRDS server configuration is created.
> Revert "JP-2012 Bug fix: Change MasterBackgroundNrsSlitsStep name"

- CHANGES.rst
- jwst/assign_wcs/tests/test_nirspec.py
- jwst/assign_wcs/util.py
- jwst/cube_build/blot_cube_build.py
- jwst/cube_build/ifu_cube.py
- jwst/outlier_detection/outlier_detection_ifu.py
- jwst/outlier_detection/outlier_detection_step.py
Partially resolves [JP-2050](https://jira.stsci.edu/browse/JP-2050)
There was a bug in the NIRSpec IFU blotting. An new routine was added to assign_wcs.util.in_ifu_slice that determines which ra, dec, lambda of the median cube fall in a NIRSpec slice. blot_cube_cube.py was updated to use this information
Checklist
> Nirspec  improvements in blotting for outlier detection, JP-2050 

- CHANGES.rst
- jwst/flatfield/flat_field.py
Closes #6268 
Resolves [JP-2224](https://jira.stsci.edu/browse/JP-2224)
This PR addresses JP-2224.  The cutout of the S-flat component of the flatfield was calculated incorrectly by not including the slit offset as well as the subarray offset. 
Checklist
> JP-2224: Fixed a bug in flatfield for brightobj mode

- jwst/regtest/test_nirspec_brightobj.py
This PR adds another regression test to the NIRSpec BOTS test suite to test the interpolated flat created for a BOTS exposure on NRS1, which was the problematic case reported and fixed in [JP-2224](https://jira.stsci.edu/browse/JP-2224).
Checklist
> Add NRS BOTS interpolated flat regtest

- CHANGES.rst
- jwst/pipeline/residual_fringe.cfg
- jwst/residual_fringe/residual_fringe_step.py
Resolves JP-1273 - fixing a typo in spec in #6211
The 'suffix' for the step was defined incorrectly in PR6211. This pr fixes it. 
Checklist
> fixed setting suffix in residual_fringe step

- CHANGES.rst
- jwst/residual_fringe/residual_fringe_step.py
Resolves JP-1273
The PR 6211 for adding the residual fringe step to the pipeline  did not work correctly if the input was a filename instead of an association.
This PR allows the input to be a filename.  Now the residual_fringe step can take either an association or a filename.
This PR also fixed an error in how suffix was initially defined. 
Checklist
> Residual Fringe fix for applying step on a file instead of an asn

- CHANGES.rst
- jwst/refpix/irs2_subtract_reference.py
- jwst/refpix/refpix_step.py
Closes #6282 
Resolves [JP-2250](https://jira.stsci.edu/browse/JP-2250)
This PR refactors the parts of the refpix step used to correct NIRSpec exposures using the IRS2 readout mode, in order to reduce the memory usage. The major change is to the `subtract_reference` function in irs2_subtract_reference.py to replace all of the repeated loops over "sectors" (regions of the data readout by the 4 different amps) with one big loop that computes and applies the correction to one "sector" at a time, so that you're not always carrying along the data for all 4 sectors all the time. Other more minor changes, such as moving the copy of input_model -> output_model to the end of the step, because only the SCI (data) array is needed for all of the computations, hence you're not carrying …
> JP-2250: Refactor refpix IRS2 to reduce memory usage

- CHANGES.rst
- jwst/datamodels/schemas/residual_fringe.schema.yaml
- jwst/residual_fringe/residual_fringe.py
…rmat
Continued work on  JP-1273
Two new MRS residual fringe correction files have been delivered to STScI from the MIRI instrument team. These files are for IFUSHORT and IFULONG. The format of the files was a little different and required a change the data models for these reference files and slight change in the residual_fringe code to access the  data in the tables. 
These files have not yet be added to CRDS. Misty Cracraft has the delivered files and will get them into CRDS. In the meanwhile, to test the residual fringe code the files can be found at:
/grp/jwst/ssb/morrison/MIRI_MRS_FRINGEDATA/
Checklist
> MRS Residual Fringe Correction update of reference file data model

- CHANGES.rst
- jwst/cube_build/ifu_cube.py
…ifu cube
Closes #
Resolves JP-2263
This PR addresses fixes the problem that all the input models were sent to the blender routine instead of just the input models used to create the IFU cube. This resulted in final exposure times reported in the IFU header as being in correct. 
Checklist
> JP-2263 Update the input model list sent to blenders 

- CHANGES.rst
- jwst/datamodels/wcs_ref_models.py
Resolves JP-2289
This PR fixes a bug in wcs_ref_models where SpecwcsModel was not of type ReferenceFileModel, causing validation to attempt to compare against astropy standard models instead of JWST specwcs models.  Also add an on_save setting of self.meta.reftype that was missing and causing validation errors, and add some missing allowed BAND values for MIRI MRS distortion and regions files.  Fix an incorrect comment on FilteroffsetModel.
> JP-2289: Fix specwcs in wcs_ref_models

- CHANGES.rst
- docs/jwst/refpix/description.rst
Closes #6293
Resolves [JP-2257](https://jira.stsci.edu/browse/JP-2257)
This PR fixes the link in the `refpix` step docs that points to information in JDox about the NIRSpec IRS2 readout mode.
Checklist
> JP-2257: Fix bad link in refpix docs

- .github/workflows/ci.yml
This PR turns off the MacOS job in our CI workflow.  Github `macos-latest` runners are notoriously slow and these jobs fail more than 50% of the time, which is not good for reliable CI.  We should re-enable these when Github sorts out their MacOS runners to be more reliable.
Hopefully this won't bite as, as almost every developer is developing and running all these tests locally on MacOS.
Checklist
> Turn off MacOS job in CI

- CHANGES.rst
- docs/jwst/data_products/science_products.rst
- jwst/dark_current/dark_class.py
- jwst/dark_current/dark_current_step.py
- jwst/dark_current/dark_sub.py
- jwst/dark_current/tests/test_dark_sub.py
- jwst/skymatch/skyimage.py
Resolves [AL-578](https://jira.stsci.edu/browse/AL-578)
This PR removes internal dependence on data models in order to move the code to STCAL.  The files `dark_sub.py` and `dark_class.py` can be moved to STCAL with no change and `dark_current_step.py` only needs to have the import path to `dark_sub` updated.  The import paths for `tests/test_dark_sub.py` will need to be updated as well, when the above files get moved to STCAL.
All unit tests and regression tests pass.
Checklist
> Al 578: Prepping dark current code for move to STCAL

- CHANGES.rst
- docs/jwst/ramp_fitting/description.rst
Related to https://github.com/spacetelescope/stcal/pull/59 and [JP-2293](https://jira.stsci.edu/browse/JP-2293)
**Description** Changes in ramp fitting in STCAL now sets VAR_POISSON to zero for pixels with negative median rates. (https://github.com/spacetelescope/stcal/pull/59)
Checklist
> AL-595: Add documentation for ramp fitting computation of VAR_POISSON
