spacetelescope/jwst

jwst/tweakreg_catalog/tweakreg_catalog.py
jwst/tweakreg_catalog/tweakreg_catalog_step.py

Update TweakregCatalogStep imports for new jwst package structure

---

jwst/jump/jump_step.py

I changed the absolute "jwst" import to a relative one.
This is as part of our lunch time working session.

jwst absolute import to relative import

---

jwst/tweakreg/tweakreg_step.py

added models  to datamodels

---

jwst/resample/resample.py
jwst/resample/resample_step.py

cc @jdavies-st 
Also updated references to classes in models.

Updated imports for datamodels

---

jwst/outlier_detection/blot_median.py
jwst/outlier_detection/flag_cr.py
jwst/outlier_detection/outlier_detection.py
jwst/outlier_detection/outlier_detection_step.py

update imports for outlier_detection

---

jwst/tweakreg/tweakreg_step.py

fixing import

---

jwst/assign_wcs/__init__.py
jwst/assign_wcs/assign_wcs_step.py
jwst/assign_wcs/miri.py
jwst/assign_wcs/nirspec.py
jwst/assign_wcs/pointing.py

change import statements in assign_wcs

---

jwst/imprint/imprint_step.py

change import statements in imprint

---

jwst/jump/jump_step.py
jwst/jump/twopoint_difference.py
jwst/jump/yintercept.py

fix imports

---

jwst/linearity/linearity.py
jwst/linearity/linearity_step.py

change import statements in linearity

---

jwst/superbias/bias_sub.py
jwst/superbias/superbias_step.py

change imports in superbias

---

jwst/resample/resample.py
jwst/resample/resample_step.py

Using correct syntax for relative imports of datamodels.  Worked interactively...

Fixed datamodels import

---

jwst/skymatch/skymatch_step.py

fix models import

---

jwst/ami/ami_analyze.py
jwst/ami/ami_analyze_step.py
jwst/ami/ami_average.py
jwst/ami/ami_average_step.py
jwst/ami/ami_normalize.py
jwst/ami/ami_normalize_step.py
jwst/ami/webb_psf.py

import updates and pep8 changes for ami step

---

jwst/dark_current/dark_current_step.py
jwst/dark_current/dark_sub.py

@hbushouse updated imports of datamodels in dark_current

updated import for datamodels

---

jwst/outlier_detection/flag_cr.py

Noticed this bad import during my travis-ci testing

Fix quickDeriv import

---

.gitignore

Added stuff to gitignore

---

jwst/extract_1d/extract.py
jwst/extract_1d/extract_1d_step.py

@mcara Please review these changes.  Thanks.

X extract 1d

---

jwst/pipeline/calniriss_ami3.py
jwst/pipeline/calwebb_dark.py
jwst/pipeline/calwebb_image2.py
jwst/pipeline/calwebb_image3.py
jwst/pipeline/calwebb_sloper.py
jwst/pipeline/calwebb_spec2.py

@stsci-hack Please check these updates.

Updated all pipeline modules to use new datamodels imports

---

README.md

Travis image url was broken. This should take care of it.

Fix typecasing for image url

---

jwst/flatfield/flat_field.py

@hbushouse Please check these changes.  Thanks.

Check for flat being all bad; see jwst-trac #374

---

jwst/combine_1d/combine1d.py

@rij Please take a look at this file.  Thanks.

modified the import for datamodels

---

jwst/flatfield/flat_field.py

@hbushouse I just noticed some debug code (print statements) that I had forgotten were still in flat_field.py.  Could you check the diff for this file?  Thanks.

Removed some debug code.

---

jwst/associations/tests/test_level3_wfs.py

Lets try this one more time...file case sensitivity repairs.

Fix file case sensitive test not testing

---

MANIFEST.in
setup.py

Fix exclusion of *.yaml files at install-time

---

setup.py

Include .json files

---

jwst/stpipe/crds_client.py
jwst/stpipe/linear_pipeline.py
jwst/stpipe/pipeline.py
jwst/stpipe/step.py
jwst/stpipe/subproc.py
jwst/stpipe/tests/test_crds.py
jwst/stpipe/tests/test_pipeline.py
jwst/stpipe/tests/test_step.py

The import statements for the models package had been properly updated to import datamodels, but none of the actual uses of the models package in the code had been updated yet. They're all updated to "datamodels" now.

Updated all stpipe instances of models to datamodels

---

jwst/transforms/models.py

@nden should check it out and let me know about changes :)

added snell law for nirspec prism

---

jwst/associations/association.py
jwst/associations/lib/rules_level2b.py
jwst/associations/lib/rules_level3.py
jwst/associations/tests/test_associations.py
jwst/associations/tests/test_generate.py
jwst/associations/tests/test_validate.py

Implement validation against a ruleset

---

jwst/assign_wcs/assign_wcs.py

Fixed remaining occurence of jwst_pipeline

---

jwst/transforms/jwextension.py
jwst/transforms/tags/tests/test_models.py

Add additional ASDF types defined in this package and a test.

Model types

---

jwst/assign_wcs/nirspec.py

In the case of filter='OPAQUE' (used by the team for calibration), the Nirspec WCS pipeline should go only between detector and MSA.

stop NRS pipeline after MSA if filter is 'OPAQUE'.

---

jwst/assign_wcs/nirspec.py
jwst/assign_wcs/pointing.py

This PR adds the final transform (V2, V3 --> RA, DEC (,LAM)) to the NIRSPEC WCS pipelines.

add pointing transform to NIRSPEC modes

---

jwst/ami/NRM_Model.py
jwst/dq_init/dq_initialization.py
jwst/pipeline/calniriss_ami3.py
jwst/refpix/reference_pixels.py
jwst/saturation/saturation.py
jwst/skymatch/skyimage.py

@hbushouse None comparison updates

Updates for trac ticket #389 (Fix comparisons to None in step code)

---

jwst/lastframe/lastframe_step.py
jwst/lastframe/lastframe_sub.py

Updates for trac ticket #335 (MIRI last frame correction updates)

---

jwst/assign_wcs/tests/test_miri.py

Miri mrs test

---

jwst/assign_wcs/tools/nirspec/compute_world_coordinates.py

…code
Sent to the INS team to use it for testing build 6.

Nirspec world coords

---

.travis.yml

Similar to astropy/astropy#5107

PEP8 tests now use pycodestyle

---

jwst/datamodels/schemas/core.schema.yaml

Core schema updates to match KWD

---

jwst/coron/__init__.py
jwst/coron/align_refs_step.py
jwst/coron/imageregistration.py
jwst/coron/klip.py
jwst/coron/klip_step.py
jwst/datamodels/schemas/core.schema.yaml
jwst/pipeline/__init__.py
jwst/pipeline/align_refs.cfg
jwst/pipeline/calwebb_coron3.cfg
jwst/pipeline/calwebb_coron3.py
jwst/pipeline/stack_refs.cfg

Added the reference file keyword "R_BADSHR", which will be used to record the name of the NIRSpec bad shutter reference file that was used during calibration.

Add NIRSpec bad shutter ref file keyword to core schema

---

docs/associations/source/association.rst
docs/associations/source/conf.py
docs/associations/source/index.rst
docs/associations/source/level3_associations.rst
docs/associations/source/pool.rst

WIP #168 
Target is to satisfy a requirement for OPS to document the association file format.

Initial version of the associaiton file format documentation

---

jwst/associations/lib/rules_level3.py
jwst/associations/tests/test_level3_spectrographic.py

Fix NIRSpec acronym name in rules

---

jwst/associations/lib/rules_level3.py
jwst/associations/lib/rules_level3_base.py
jwst/associations/main.py
jwst/associations/tests/test_asn_names.py
jwst/associations/tests/test_level3_basics.py
jwst/associations/tests/test_level3_product_names.py
jwst/associations/tests/test_level3_wfs.py

Association and Level3 product names with correct association ids

---

jwst/dark_current/dark_current_step.py
jwst/dark_current/dark_sub.py

Updated the dark step to do more thorough checking for valid values of nframes and groupgap between science data and dark reference file data. If they aren't compatible, it returns the input data model unchanged. Also just a bit of other general code cleanup.
Fixes #178.

Dark updates for #178

---

jwst/dark_current/dark_sub.py

Data array does NOT appear as a meta attribute. D'oh!

Bug fix for dark_current

---

jwst/assign_wcs/nirspec.py

Units in V2, V3 and OTEIP frame are degrees. IN future deliveries it is expected these will be in arcsec.

fix call to nrs_wcs_set_input and change units

---

jwst/assign_wcs/nirspec.py
jwst/assign_wcs/tests/test_nirspec.py

This is @brechmos-stsci unit change from #237 with squashed commits.

scale wavelength by 1e6 to convert from meters to microns

---

jwst/associations/main.py
jwst/associations/tests/test_io.py
jwst/associations/tests/test_main.py

Save orphaned exposures in a table

---

.travis.yml

All Travis jobs are failing. Attempting a fix.

fix version of qt to 4

---

jwst/associations/association.py
jwst/associations/lib/rules_level3_base.py

Sequence counter tracks with association type

---

jwst/coron/imageregistration.py

remove unused import statement

---

jwst/assign_wcs/nirspec.py

This PR masks out locations in the NIRSpec cutout which don't belong to the slit by setting the value to `NaN`. Needed by flat fielding and cube building @philhodge @jemorrison

mask slits

---

jwst/extract_2d/extract_2d.py

Correct for 1-indexing in xsize and ysize.

---

jwst/associations/association.py
jwst/associations/main.py
jwst/associations/pool.py
jwst/associations/registry.py
jwst/associations/tests/test_io.py

Add YAML as an association format

---

docs/associations/source/index.rst
docs/associations/source/level3_asn_rules.rst
docs/associations/source/level3_asn_technical.rst
docs/associations/source/level3_associations_index.rst

Doc update to include assoication product types

---

jwst/transforms/models.py
jwst/transforms/schemas/niriss_soss-0.1.0.yaml
jwst/transforms/tags/jwst_models.py

NIRISS SOSS WCS model.
@brechmos-stsci

Add a NIRISS SOSS model schema

---

jwst/pipeline/__init__.py
jwst/pipeline/calwebb_sloper.cfg
jwst/pipeline/calwebb_sloper.py
jwst/pipeline/calwebb_sloper_b6.cfg
jwst/pipeline/calwebb_sloper_b6.py

Renamed the B7 SloperPipeline to be the new default SloperPipeline. Kept the old default SloperPipeline labeled as B6, in case anyone wants to use it yet.

Setting B7 sloper pipeline to be default

---

jwst/cube_skymatch/__init__.py
jwst/cube_skymatch/cube_skymatch_step.py
jwst/cube_skymatch/skycube.py
jwst/cube_skymatch/skymatch.py

This is initial implementation of sky background matching for cubes. The algorithm has been minimally tested to work with some made-up (by me) cubes without WCS. I expect the algorithm to work with high confidence when WCS is available.

Initial implementation of sky background matching for cubes

---

jwst/assign_wcs/niriss.py
jwst/transforms/models.py
jwst/transforms/tags/jwst_models.py

In discussion with @nden , this is the current code for NIRISS SOSS assign_wcs.  I can assign a WCS to the input data based on the wavelength lookup file. We are not sure if the input science file and wavelength lookup file are consistent with each other and we will look into that when we have more information from the NIRISS team.
@nden @hbushouse

NIRISS SOSS assign_wcs

---

jwst/assign_wcs/fgs.py
jwst/assign_wcs/miri.py
jwst/assign_wcs/nircam.py
jwst/assign_wcs/niriss.py
jwst/assign_wcs/nirspec.py
jwst/assign_wcs/pointing.py
jwst/assign_wcs/tests/test_miri.py
jwst/assign_wcs/tests/test_nirspec.py
jwst/assign_wcs/tests/test_wcs.py
jwst/datamodels/schemas/core.schema.yaml
jwst/transforms/models.py
jwst/transforms/schemas/v23tosky-0.1.0.yaml
jwst/transforms/tags/jwst_models.py

This should be merged after #286 is resolved in some way (or the inconsistency of units in the output should be dealt with tentatively here).

add v23tosky model

---

jwst/srctype/srctype.py

Added another section to the srctype module to handle NIRSpec MSA exposures. It opens the MSA configuration file, loads the Source table, finds stellarity values in the table for each source_id in the MultiSlit data model, and stores the stellarity value in the slit meta data. Includes a hook to abort if the stellarity column isn't in the Source table. Could probably use more clever methods for searching for and matching source_id's with stellarity values in the table, but it works.

Srctype step updates for MSA mode

---

jwst/associations/lib/rules_level3.py
jwst/associations/tests/test_level3_product_names.py
jwst/associations/tests/test_level3_spectrographic.py

Give MIRI MRS associations their own type: MIRIFU

---

jwst/datamodels/container.py
jwst/datamodels/fits_support.py
jwst/datamodels/model_base.py

Revert "Change asarray to asanyarray in _fits_array_writer"

---

jwst/pipeline/calwebb_dark.cfg
jwst/pipeline/calwebb_dark.py

Updated the calwebb_dark pipeline and cfg file to conform to the reordering of steps that was implemented for the Build 7 version of the calwebb_sloper pipeline and the inclusion of the new MIRI RSCD step.

Updated dark pipeline for new B7 flow and steps

---

jwst/srctype/srctype.py

Removed the section of code that read stellarity values from the MSA config file, because that will now be done by the extract_2d step. Instead, it now uses those stellarity values already loaded into the slit instances to set the point/extended type for each source. The choice of point vs extended is based on comparing the stellarity value against a threshold for each exposure type, which will eventually come from a reference file. For now the threshold is hardwired at 0.75.

Updates to source_type step for MSA mode

---

jwst/pipeline/calwebb_spec2.py
jwst/srctype/srctype.py

Updated calwebb_spec2 pipeline to include the new source_type step right after flat-fielding. Also updated the srctype module to handle input exp_type's that aren't applicable to the step.

Added srctype step to calwebb_spec2

---

jwst/assign_wcs/fgs.py
jwst/assign_wcs/miri.py
jwst/assign_wcs/nircam.py
jwst/assign_wcs/niriss.py

More unit conversion to arcsec in V2V3. (#286).

V2v3 units

---

jwst/datamodels/properties.py

Datamodels.properties was not validating appends, the call to _validate was commented out. I removed the comment, restoring the validation step.

Validate list appends against schema

---

jwst/associations/generate.py
jwst/associations/lib/rules_level3_base.py
jwst/associations/main.py

Resequence Level3 associations

---

jwst/assign_wcs/nirspec.py

Nirspec to v23

---

jwst/assign_wcs/pointing.py

fix bugs reported by @jemorrison

fix wcs of a resampled cube

---

jwst/associations/__init__.py
jwst/associations/association.py
jwst/associations/main.py

Document software version in the association

---

docs/ami/source/index.rst
docs/ami/source/main.rst
docs/ami/source/reference_files.rst

Added reference_files.rst doc module and updated all of the text for some recent changes.

Updated AMI tasks docs

---

docs/jump/source/index.rst
docs/jump/source/main.rst
docs/jump/source/reference_files.rst

Updated the jump step docs to include the gain and readnoise ref file info in a separate doc file.

Updated Jump step docs

---

docs/photom/source/reference_files.rst

Updated all the reference file selection and format information in the photom step docs.

Updated photom reference file docs

---

jwst/cube_build/CubeCloud.py
jwst/cube_build/InstrumentDefaults.py
jwst/cube_build/cube.py
jwst/cube_build/cube_build.py
jwst/cube_build/cube_build_io.py
jwst/cube_build/cube_build_step.py
jwst/cube_build/cube_model.py
jwst/datamodels/schemas/ifucube.schema.yaml
jwst/pipeline/cube_build.cfg

save celts as degrees
added weighting option  to speed up MIRI cube building
removed print statements
handle units from assign_wcs correctly

Determine cube type

---

scripts/set_velocity_aberration.py

Updated velocity aberration script with additional function to calculate RA/Dec offsets. Based on Kepler code from @dmggh, which was apparently originally based on code from @philhodge (the circle is now complete).

Velocity aberration RA/Dec offsets

---

scripts/set_telescope_pointing.py

This PR computes and populates `ROLL_REF`.
In addition it populates these keywords:
`RA_REF`, `DEC_REF`, `WCSAXES`.
We need to find out whether SDP is populating `CTYPE`, `CUNIT` and `RADESYS`.

Roll angle

---

jwst/datamodels/schemas/core.schema.yaml

MSACONFL --> MSAMETFL

---

jwst/assign_wcs/nirspec.py
jwst/assign_wcs/pointing.py
jwst/datamodels/schemas/core.schema.yaml
jwst/transforms/models.py
jwst/transforms/schemas/refraction_index_from_prism-0.1.0.yaml
jwst/transforms/schemas/snell-0.1.0.yaml
jwst/transforms/tags/jwst_models.py

This implements the transforms through the NIRSpec prism. Wavelength comparison with IDT data is off by ~10**-9, however if tests pass I am merging this to allow prism data to pass through the pipeline and will open an issue to fix the remaining problems.

NIRSpec prism 

---

jwst/cube_build/cube_build.py
jwst/cube_build/cube_build_io.py
jwst/cube_build/cube_build_step.py
jwst/cube_build/cube_model.py

Fixed the output filename when cube_build is called with a model.
Now populating the output header with input header info

Fixed output names and populatin header with input info

---

jwst/cube_build/cube.py
jwst/cube_build/cube_build_io.py
jwst/cube_build/cube_build_step.py
jwst/cube_build/cube_model.py

Fixed an error that when cube_build is called using a model that program does not over write the original data, but just the final IFUCubeModel is returned. 
In addition, if cube_build is called with an association table or fits file then self.output_file is filled in and the output file is written out

Fixed returning model and writing out final IFUCube

---

jwst/assign_wcs/util.py

@hbushouse 
gwcs.wcs.output_frame returns the object now.

fix comput_fiducial

---

jwst/assign_wcs/fgs.py
jwst/assign_wcs/miri.py
jwst/assign_wcs/nircam.py
jwst/assign_wcs/niriss.py
jwst/assign_wcs/nirspec.py

An attempt to update the list of exp_types in assign_wcs.
@hbushouse Could you take a look and suggest additions, corrections or if any of these modes should go through assign_wcs.
I want to get these correct before updating CRDS rules.

Update exp type

---

docs/pipeline/source/description.rst
docs/user_guide/source/main.rst

Updated old links and brought info up to date with B7 status.

Updates to Users Guide and other docs

---

docs/pipeline/source/description.rst
docs/stpipe/source/user/logging.rst

Small corrections and additions to user's guide and pipeline docs.

Doc udpates

---

jwst/resample/resample.py
jwst/resample/resample_step.py

apply sky value (computed by skymatch) when resampling with drizzle.

Resample step updated to report status as COMPLETE when finished and to

---

jwst/assign_wcs/nirspec.py
jwst/assign_wcs/tests/test_nirspec.py

Closes #463 
`NRS_BRIGHTOBJ` mode is a time series mode resttricted to `S1600A1`.
Also added processing of `NRS_LAMP` with all fixed slits opened. This has to be confirmed by the ins team and possibly changed.

fix processing of nirspec mode NRS_BRIGHTOBJ

---

jwst/resample/resample_utils.py

Bring code up to dat e with gwcs.

bring up-to-date with gwcs

---

jwst/lib/engdb_tools.py
jwst/lib/tests/engdb_tools_tests.py
jwst/timeconversion/__init__.py
scripts/set_bary_helio_times.py

Fixes for the bary/helio correction to handle the ephemeris appropriately.
Also, first implementation of the toolset for accessing the JWST engineering RESTful interface.

bary/helio correction fixes & engDB tools

---

jwst/lib/engdb_tools.py
jwst/lib/tests/engdb_tools_tests.py
scripts/set_telescope_pointing.py
tests/test_set_telescope_pointing.py

Incorporated engineering db into pointing.

---

jwst/datamodels/schemas/group.schema.yaml

Added bary and helio time columns

---

jwst/dq_init/dq_init_step.py

because there are just so many bad test data files out there.
Added more checks to make sure SUBSIZEn keyword values agree with actual data array dimensions.

Yet more data checks in dq_init

---

jwst/transforms/models.py

Logical model now handles NaNs in the input

---

jwst/assign_wcs/nirspec.py
jwst/datamodels/schemas/core.schema.yaml

Added checks and log messages for missing keywords.

JP-101, JP-100

---

jwst/assign_wcs/nirspec.py

Somehow I missed S200B1 from the list of open slits on NRS2.

add S200B1 to open slits

---

docs/cube_build/source/arguments.rst
docs/cube_build/source/main.rst

Updating IFU

---

jwst/pathloss/__init__.py
jwst/pipeline/calwebb_spec2.cfg
jwst/pipeline/calwebb_spec2.py
jwst/pipeline/pathloss.cfg

Added version number to pathloss step init file. Updated calwebb_spec2 module and cfg to include the pathloss step (only for NIRSpec exposures for now).

Integrate pathloss step into calwebb_spec2

---

jwst/pipeline/calwebb_spec2.py
jwst/resample/resample_spec.py
jwst/resample/resample_utils.py

Sample dataset jw00035001001_01101_00001_MIRIMAGE_rate.fits now runs through calwebb_spec2 to the end without crashing.  Still seeing a bug in he pixmap mapping which is passed to cdrizzle.tdriz().

Full implementation of MIRI LRS resampling

---

jwst/resample/resample_spec.py

Clean up debugging code

---

jwst/pathloss/path_loss.py
jwst/pathloss/pathloss_step.py
jwst/pipeline/calwebb_spec2.py
jwst/srctype/srctype.py

Updated the calwebb_spec2 pipeline module, the pathloss step, and the source_type step to handle NRS_BRIGHTOBJ exposures the same as NRS_FIXEDSLIT.
Fixes #513

Updates for NRS_BRIGHTOBJ mode

---

jwst/cube_build/__init__.py
jwst/flatfield/__init__.py
jwst/superbias/__init__.py

A few more updates to version numbers for last minute changes that are going into a build that will be rc7.

Version updates for b7rc7

---

jwst/datamodels/fits_support.py

It was reported that the TUNIT keyword was not being updated when a table was opened using the datamodels package and a column's units was changed. The problem was in fits_support._fits_array_loader. That code will convert the datatypes of the table columns when they do not agree with the schema. That conversion involves a copy and the copy loses the listeners which update the header keywords when a change is made to a column's attributes. Code was added to copy the listeners from the original data to the copy of the data so that column units are
updated.

Update TUNIT when column units are changed

---

docs/assign_wcs/source/reference_files.rst

Added a column with instruments using the ref types.

add a column with instruments

---

docs/assign_wcs/source/reference_files.rst

@nden  Here is the PR to check over etc.

WIP: WCS documentation

---

docs/assign_wcs/source/reference_files.rst

tweaks to the ref files docs.

---

docs/cube_build/source/conf.py
docs/cube_build/source/main.rst
docs/straylight/source/main.rst
docs/straylight/source/reference.rst
jwst/cube_build/CubeCloud.py
jwst/cube_build/cube_build.py
jwst/cube_build/cube_build_step.py

Updated Cube Build Documentation
Updated Straylight Documenation
Fixed an error with NIRSPEC Issue#543. The x,y bounds of the slice boundaries are indexed starting at 0. The code was assuming the indexing started at 1. For NIRSPEC 2 the x boundary always starts at 0 so the code thought no valid data was falling on the detector. 
Also updated the weighting function to be more inline with what David Law was doing. An input parameter on the power of the distance between point cloud member and spaxel center was added.

Nirspec noifudata

---

docs/associations/source/overview.rst

An updated overview with programmatic usage

---

jwst/photom/photom.py

Updated the Nirspec MSA branch of photom to loop over all the slits contained in an MSA science product, attaching a RELSENS table for each slit. Fixes #567.

Make photom loop over NRS MSA slits

---

docs/cube_build/source/arguments.rst
docs/cube_build/source/main.rst

Fixed errors in the formatting of the Cube Build documentation. Cleaned up how the weighting is done in the description.

Updated Cube Build doc

---

docs/ami/source/main.rst
docs/ami/source/reference_files.rst

Updated the docs for the ami package steps and the calwebb_ami3 pipeline, as they currently exist in the B7 delivery.

Update docs for AMI steps and pipeline

---

docs/coron/source/main.rst

Updated the main docs that explain each task in the B7 version of the coron package. The stack_refs and align_refs steps are new (or at least heavily modified), as well as the calwebb_coron3 pipeline.

Update coron pkg docs for new B7 tasks

---

jwst/datamodels/tests/association.json
jwst/datamodels/tests/test_open.py
jwst/datamodels/util.py

Remove file name dependency from datamodel.open

---

jwst/datamodels/util.py

For the sake of backwards compatibility the test to see if a fits file is a ramp file need to be done ahead of the test for a generic reference file. So I have moved the tests into _class_from_ramp_type
and added a call to he new function to datamodels.open.

Move ramp file check in datamodels.open into new function

---

docs/ami/source/main.rst
docs/coron/source/main.rst

Minor updates to fix formatting issues.

Formatting updates for AMI and CORON docs

---

jwst/saturation/saturation.py

xrange -> range

---

jwst/lib/engdb_tools.py

The URL can be specified in ENGDB_BASE_URL
Resolves #541

Add environmental control over the database service url

---

docs/pipeline/source/description.rst

Yet more minor formatting updates to the pipeline doc page. I promise to get it right, some day.

More pipeline doc updates

---

jwst/engdblog/__init__.py
jwst/engdblog/engdblog.py
jwst/engdblog/tests/test_engdblog.py
jwst/lib/engdb_tools.py
jwst/lib/tests/test_engdb_tools.py
jwst/pipeline/engdblog.cfg
setup.py

Initial implementation of new step EngDBLogStep

---

jwst/stpipe/step.py

Fixes stspec to run under Python3

---

jwst/tests/test_velocity_aberration.py
scripts/set_velocity_aberration.py

Fix divide-by-zero when velocity is zero

---

jwst/cube_build/CubeCloud.py
jwst/cube_build/CubeD2C.py
jwst/cube_build/CubeOverlap.py
jwst/cube_build/InstrumentDefaults.py
jwst/cube_build/coord.py
jwst/cube_build/cube.py
jwst/cube_build/cube_build.py
jwst/cube_build/cube_build_io.py
jwst/cube_build/cube_build_step.py
jwst/cube_build/cube_model.py

cube_build now allows the user to set the output file name: --output_file = filename 
Removed some looping that was not needed
removed some values not needed in spaxel class to reduce memory issues 
Using Ben's plate scale and dispersion values for the 12 MIRI bands.

Cubebuild efficient

---

jwst/assign_wcs/miri.py

Add XanYan to V2V3 transform

---

docs/pipeline/Makefile
docs/pipeline/source/description.rst

Add model names to the output product listing

---

jwst/cube_build/CubeCloud.py
jwst/cube_build/cube.py
jwst/cube_build/cube_build.py
jwst/cube_build/cube_build_io.py
jwst/cube_build/cube_build_step.py
jwst/cube_build/cube_model.py

Removed storing the Point Cloud. Now a detector pixel is mapped from cloud to cube and then find ROI all in one step.

Removed storing Point Cloud

---

jwst/assign_wcs/util.py

The original version of this function assumed the WCS scheme is similar to the one on HST imagers.
Since this is not valid now and currently JWST does not use FITS WCS keywords, it has be modified.
The input is now a list of models. The scaling model uses CDELTn values and the rotation uses ROLL_REF.
@jdavies-st @stsci-hack This may require further tweaks. Please review.

wcs_from_footprints

---

jwst/resample/resample_spec.py

Fix bug introduced in PR #693.

Fix bug in initializing self.blank_output.wcs in resample_spec

---

jwst/associations/registry.py

Changed to debug for, you know, debugging.

Remove an unnecessary logging.error statement

---

jwst/associations/__init__.py
jwst/associations/asn_from_list.py
jwst/associations/association.py
jwst/associations/lib/rules_level3.py
jwst/associations/lib/rules_level3_base.py
jwst/associations/lib/template_asn.json
jwst/associations/load_asn.py
jwst/associations/registry.py
jwst/associations/tests/test_asn_from_list.py
scripts/asn_from_list

`asn_from_list` will create a properly formatted association from a list of files.  There is very little validation of the created association, since this essentially short-circuits the whole association creation process. But, if the user knows what they are doing...
The default structure for the association is the Level 3 association structure.

New shell command: asn_from_list

---

jwst/assign_wcs/miri.py

Add a function which returns the wavelength range of a MIRI MRS observation , used to create the WCS object. The function needs access to the reference file which was used by `assign_wcs`.
Added docstrings.

Wave range miri mrs

---

jwst/extract_1d/ifu.py

For IFU data (only), keyword BUNIT is checked to see whether flux
calibration has been done.  If it has, the extracted data will be
written to the flux column; if not, the extracted data will be written
to the net column.
This also closes #648.

Check BUNIT for IFU data.  #718

---

jwst/associations/lib/asn_schema_jw_level2b.json
jwst/associations/tests/data/asn_level2.json
jwst/associations/tests/test_level2_basics.py

Update Level2 schema to match current pipeline usage

---

jwst/pipeline/calwebb_spec2.py

Several updates to the calwebb_spec2 pipeline module, including:
- handling members that do not have "bkgexps" or "imprint" attributes
- saving extracted spectra from multi-integration exposures as "x1dints" files
- ability to handle a single data model as input
- general updates to the input handling and asn template construction
The input routine "Lvl2Input" is now capable of handling
- an ASN file name
- a single exposure file name
- a single exposure data model

calspec2 updates

---

docs/skymatch/source/description.rst
docs/skymatch/source/functions.rst
docs/skymatch/source/index.rst
docs/skymatch/source/region.rst
docs/skymatch/source/skyimage.rst
docs/skymatch/source/skymatch.rst
docs/skymatch/source/skymatch_step.rst
docs/skymatch/source/skystatistics.rst

A few more updates to skymatch docs to give them an organization more akin to other pipeline step docs. Real content will need to be provided by @mcara. In partial fulfillment of #741.

More skymatch doc updates

---

docs/associations/source/reference/level3_asn_rules.rst
docs/associations/source/reference/level3_asn_technical.rst
jwst/associations/lib/rules_level3.py
jwst/associations/lib/rules_level3_base.py
jwst/associations/tests/test_level3_basics.py
jwst/associations/tests/test_level3_spectrographic.py

Refactor of association types

---

jwst/datamodels/model_base.py
jwst/datamodels/properties.py

Erik Tollerud requested this modification.The motivation is that it will be easier to develop software that works across different telescopes if the data format they use all adhere to a common api,
which is defined in the NDDataBase class. No, it's not a database, it's the base of the NDData class. This abstract class defines six properties that its subclasses must implement. These have been added to datamodels.model_base.py. The meta property required the most work, as it is a flat dictionary in NDData and has a hierachical structure in datamodels. The code which creates a facade for the meta propery to implement the behavior NDData expects has been added to
datamodel.properties.py. None of the existing interfaces to datamodels have been modified, all code that uses datamodels should …

Make Datamodels a subclass of astropy.NDData

---

jwst/assign_wcs/niriss.py

enable ami mode

---

scripts/set_bary_helio_times.py

Read ra/dec from TARG_RA/TARG_DEC instead of PROP

---

jwst/extract_1d/extract.py

If bounding_box is present in the wcs, this will be used.  If it is
not present, domain will be used.

Use wcs.bounding_box instead of wcs.domain.  See JWST issue #769.

---

jwst/flatfield/flat_field.py

If bounding_box is present in the wcs, that will be used; if not,
domain will be used.

Use bounding_box instead of domain; see JWST issue #770.

---

jwst/skymatch/region.py
jwst/skymatch/skymatch.py
jwst/skymatch/skymatch_step.py

This resolves several bugs in skymatch and turns on some features that were turned off in the previous release. Also changes have been made on how background level is saved in the image model.

Fix bugs in skymatch

---

jwst/cube_build/CubeCloud.py
jwst/cube_build/cube_build.py
jwst/cube_build/cube_build_io.py

@jemorrison This makes the switch from `domain` to `bounding_box`. Please review and merge when appropriate.

switch domain with bounding_box

---

jwst/assign_wcs/util.py
jwst/resample/resample_spec.py
jwst/resample/resample_utils.py

Please don't merge yet, more changes coming.
@nden could you look at the updates to `assign_wcs.util.wcs_from_footprints()`?

Add support in resample for gwcs.WCS.bounding_box

---

jwst/associations/lib/association_rules.py

Quick fix to re-include the old level2 schema

---

jwst/extract_1d/extract.py

For SOSS data, call niriss_soss_set_input to specify the order number.

Specify spectral order number for NIRISS SOSS data; see jwst issue #813.

---

jwst/cube_skymatch/cube_skymatch_step.py
jwst/datamodels/schemas/core.schema.yaml
jwst/skymatch/skymatch_step.py

This addresses https://github.com/STScI-JWST/jwst/issues/788#issuecomment-292516180 and https://github.com/STScI-JWST/jwst/issues/788#issuecomment-292569709

Add BKGLEVEL to the core schema.

---

jwst/associations/asn_from_list.py

Updated for typical usage for level3 mosaics showing required parameters.

Update asn_from_list usage string

---

docs/jwst/associations/level2_asn_technical.rst
docs/jwst/associations/level3_asn_technical.rst
jwst/associations/lib/asn_schema_jw_level2b.json
jwst/associations/lib/asn_schema_jw_level3.json

This is in prep for modifying the whole output scheme used by the
pipeline, to clarify the dependency on the `name` of each of the
products.
WIP #678

Revise down more schema restrictions and document the changes

---

jwst/datamodels/schemas/dark.schema.yaml
jwst/datamodels/schemas/darkMIRI.schema.yaml
jwst/datamodels/schemas/keyword_groupgap.schema.yaml
jwst/datamodels/schemas/keyword_nframes.schema.yaml
jwst/datamodels/schemas/keyword_ngroups.schema.yaml
jwst/datamodels/schemas/keyword_preadpatt.schema.yaml
jwst/datamodels/schemas/keyword_readpatt.schema.yaml

add more keyword schemas [skip ci]

---

jwst/datamodels/schemas/linearity.schema.yaml
jwst/datamodels/schemas/saturation.schema.yaml
jwst/datamodels/schemas/superbias.schema.yaml

Updates for the linearity and suberbias reference file schema
No changes were necessary for the saturation schema

datamodels.schemas update for linearity and superbias 

---

jwst/datamodels/schemas/gain.schema.yaml

Updated gain schema per ticket #861,

Added subarray schema. See ticket #861.

---

jwst/associations/lib/lv2_v1_to_v2.py

Fixed output json formatting and command line usage

---

jwst/datamodels/schemas/mask.schema.yaml
jwst/datamodels/schemas/pathloss.schema.yaml

pathloss and mask schema updates

Schema updates for issue #861

---

jwst/datamodels/schemas/fringe.schema.yaml
jwst/datamodels/schemas/nirspec_ifucubepars.schema.yaml
jwst/datamodels/schemas/rscd.schema.yaml
jwst/datamodels/schemas/straylight.schema.yaml

updated reference file schema for 
Fringe.schema.yaml, straylight.schema.yaml, rscd.schema.yaml for ticket #861 
addd nirspec_ifucubepars.schema.yaml

Updated Fringe, straylight, rscd ref schema

---

jwst/assign_wcs/miri.py

Second try at updating miri.py; I've migrated all of my changes to now incorporate the changes Nadia made for Jeb in the master.
The changes here alter some of the structure of the transforms and remove the v2v3 file.  They will need new reference files in order to be tested properly.

Updated miri.py

---

.travis.yml
jwst/assign_wcs/miri.py

We should be catching this kind of errors with Travis. I added a test option with numpy 1.12.

fix indexing errors

---

jwst/assign_wcs/miri.py

Use datamodels to open MIRI WCS reference files.

use data models - MIRI

---

jwst/pipeline/calwebb_spec2.py

Spec2Pipline modified to place background processing before wcs check

---

jwst/associations/__init__.py

Bump association version

---

jwst/associations/lib/dms_base.py
jwst/associations/lib/rules_level2_base.py
jwst/associations/tests/notebooks/asn_from_list.ipynb
jwst/associations/tests/test_asn_from_list.py

Remove the unneed complaint about program

---

jwst/extract_1d/extract.py
jwst/flatfield/flat_field.py
jwst/pathloss/path_loss.py
jwst/srctype/srctype.py

Updated the log messages in several calspec2 steps, mainly for the case of processing a NIRSpec MSA exposure. When there are many slits to process, it's nice for the user to see some progress messages, rather than just waiting 10-20 minutes to see that the step has completed. Also changed some info messages to debug, because they really aren't needed on a regular basis.

Updates to calspec2 steps logging

---

docs/jwst/associations/association_reference.rst
docs/jwst/associations/level2_asn_technical.rst
docs/jwst/associations/level3_asn_technical.rst
docs/jwst/associations/pool.rst
jwst/associations/__init__.py
jwst/associations/lib/rules_level2_base.py
jwst/associations/lib/rules_level2b.py
jwst/associations/lib/rules_level3.py
jwst/associations/lib/rules_level3_base.py
jwst/associations/main.py
jwst/associations/pool.py
jwst/associations/tests/data/asn_level2.json
jwst/associations/tests/data/pool_001_candidates_lower.csv
jwst/associations/tests/helpers.py
jwst/associations/tests/test_asn_from_list.py
jwst/associations/tests/test_associations.py
jwst/associations/tests/test_case.py
jwst/associations/tests/test_level2_basics.py
jwst/associations/tests/test_level3_product_names.py
jwst/associations/tests/test_level3_spectrographic.py
jwst/pipeline/calwebb_image2.py
jwst/pipeline/calwebb_spec2.py

Pool contents are now normalzed to lowercase, and all rules are based on this. Output associations will now have all keywords and values lowercase also.
Resolves #757

Make associations case-agnostic

---

jwst/stpipe/step.py
jwst/stpipe/tests/test_saving.py

Not saving step results if step is skipped

---

jwst/datamodels/wcs_ref_models.py

fix reftype

---

jwst/cube_build/cube_build.py
jwst/datamodels/schemas/core.schema.yaml

added to core schema cal_step.cube_build with fits_keyword = S_IFUCUB
updated cube_build code to write this out to every output product produced by  cube_build
@hbushouse 
@stscieisenhamer

Added COMPLETED to cube_build status

---

jwst/cube_build/cube_build.py
jwst/cube_build/file_table.py

Resolves #951 
Apologies for the bazillion diffs; emacs fixes all.
The relevant diff is in file `cube_build.py` line 156: Arguments to `set_file_table` had the models and filenames swapped.

Fix argument swap to call of set_file_table

---

jwst/pipeline/source_catalog.cfg
jwst/source_catalog/source_catalog.py
jwst/source_catalog/source_catalog_step.py

Fixes the flux comparison bug reported #976.  The other issue reported in #976 will require updated NIRCam reference files from the instrument team.

Fix flux calculation in source catalog

---

jwst/photom/photom.py

Updates to the save_area_info function in photom, so that the nominal pixel area values stored in keywords in the pixel area reference file take priority over the same keyword values in the photom reference file. Instead of not copying any pixel area values to the output (science data model) when the two sets of pixel area values don't agree, just issue a warning about the discrepancy and still copy the values from the pixel area reference file, so that there are values to work with in later steps, such as source_catalog.
Addresses #976 and related to #981.

Updates to photom to address #976

---

scripts/set_bary_helio_times.py

Allow script to execute if a GROUP extension does not exist

---

docs/jwst/package_index.rst
docs/jwst/wiimatch/LICENSE.rst
docs/jwst/wiimatch/README.md
docs/jwst/wiimatch/index.rst
docs/jwst/wiimatch/lsq_optimizer.rst
docs/jwst/wiimatch/match.rst
docs/jwst/wiimatch/utils.rst
jwst/cube_skymatch/skymatch.py
jwst/mrs_imatch/__init__.py
jwst/mrs_imatch/mrs_imatch_step.py
jwst/steps.py
jwst/wiimatch/__init__.py
jwst/wiimatch/lsq_optimizer.py
jwst/wiimatch/match.py
jwst/wiimatch/utils.py

This PR adds new and improved (compared to ``cube_skymatch``) background matching algorithm. This algorithm computes parameters of the background polynomials (of arbitrary degree - but don't go crazy 😄) by minimizing the total sum of errors. The core algorithm is located in the package ``wiimatch`` which can also handle arbitrary data dimensionality. The new step is called ``mrs_imatch``.
CC: @hbushouse

New generalized and optimized MIRI MRS cube background matching algorithm

---

docs/jwst/package_index.rst
jwst/datamodels/schemas/core.schema.yaml

Updates and adds entry to the core schema for all of the keywords listed in #974.
Also adds an entry to the docs package index for the new white_light step.

Update core schema for #974

---

jwst/associations/association.py
jwst/associations/generate.py
jwst/associations/lib/dms_base.py
jwst/associations/lib/format_template.py
jwst/associations/lib/rules_level2_base.py
jwst/associations/lib/rules_level3_base.py
jwst/associations/tests/test_associations.py
jwst/associations/tests/test_main.py
jwst/pipeline/calwebb_spec3.cfg
jwst/pipeline/calwebb_spec3.py
jwst/pipeline/tests/data/calwebb_spec3_default.cfg
jwst/pipeline/tests/data/calwebb_spec3_mock.cfg
jwst/pipeline/tests/mock_steps.py
jwst/pipeline/tests/test_calwebb_spec3_mir_mrs.py
jwst/pipeline/tests/test_calwebb_spec3_nrs_msa.py

Includes new utility, `product_format`, to properly format product names found in associations.

Include source naming in product output

---

jwst/datamodels/model_base.py

Datamodels can be opened in two ways: first by calling the generic open function and second by creating a new DataModel object. Several different kinds of input can be used to open a model. One is another model. When a model is used to open another model the code makes a copy of the previous model. Previously it made a deep copy. Now it makes a shallow copy, meaning that only the top level attributes of the original image are copied. This is faster and uses less memory, particularly in the case of the pipeline code, where the pipeline opens the input file and the input file is re-opened by each step. The copy method of DataModel still does a deep copy, which agrees with how
the copy method is used by the code. The revised code sets an internal attribute, _iscopy, to True if the model is a …

Use a shallow copy when opening an image from another image

---

jwst/datamodels/schemas/camera.schema.yaml
jwst/datamodels/schemas/collimator.schema.yaml
jwst/datamodels/schemas/disperser.schema.yaml
jwst/datamodels/schemas/distortion.schema.yaml
jwst/datamodels/schemas/distortion_mrs.schema.yaml
jwst/datamodels/schemas/fore.schema.yaml
jwst/datamodels/schemas/fpa.schema.yaml
jwst/datamodels/schemas/ifufore.schema.yaml
jwst/datamodels/schemas/ifupost.schema.yaml
jwst/datamodels/schemas/ifuslicer.schema.yaml
jwst/datamodels/schemas/msa.schema.yaml
jwst/datamodels/schemas/ote.schema.yaml
jwst/datamodels/schemas/specwcs.schema.yaml
jwst/datamodels/schemas/wavelengthrange.schema.yaml
jwst/datamodels/wcs_ref_models.py

No cal code is affected at the moment, so skipping Travis tests.

fix issues with nirspec ref files

---

jwst/pipeline/tests/test_calwebb_spec3_mir_lrs_fixedslit.py
jwst/pipeline/tests/test_calwebb_spec3_mir_mrs.py
jwst/pipeline/tests/test_calwebb_spec3_nrs_msa.py

test updates that had been neglected earlier.

Spec3: more tests

---

jwst/datamodels/filetype.py

This is not needed for how the function is currently used. But ignoring this case in the past has caused me problems, so it's best to handle the case of a non-existent file now when I remember it.

Get file type from extension if file does not exist

---

jwst/assign_wcs/pointing.py
jwst/datamodels/reference.py
jwst/datamodels/wcs_ref_models.py

tweaks to nirspec reference file models

Fix nirspec models

---

docs/jwst/associations/technote_sdp_workflow.rst

Add Field Guide to File Names section to workflow document

---

jwst/assign_wcs/pointing.py

Should be merged after spacetelescope/gwcs#92

adress alpha-beta cube issues

---

jwst/lib/convert_to_uncal.py

[skip ci]
This utility takes a 'cal' based file and creates the equivalent
level1b file from it. Not very sophisticated; more of an example.

Add utility convert_to_uncal

---

jwst/assign_wcs/pointing.py
jwst/assign_wcs/tests/test_wcs.py

Resolves #1054, fixes other bugs in constructing a GWCS object from  FITS WCS keywords saved in a data model.

fix bug in frame_from_model

---

jwst/assign_wcs/nirspec.py

fix problems discovered by nightly tests [skip ci]

fix nirspec with new ref files

---

jwst/tso_photometry/tso_photometry_step.py

Rename tso_photometry product name to '_phot'

---

.gitignore
docs/jwst/mrs_imatch/LICENSE.rst
docs/jwst/mrs_imatch/README.rst
docs/jwst/mrs_imatch/index.rst
docs/jwst/mrs_imatch/mrs_imatch_step.rst
docs/jwst/package_index.rst
docs/jwst/skymatch/README.rst
docs/jwst/skymatch/description.rst
docs/jwst/skymatch/index.rst
docs/jwst/skymatch/region.rst
docs/jwst/skymatch/skyimage.rst
docs/jwst/skymatch/skymatch.rst
docs/jwst/skymatch/skymatch_step.rst
docs/jwst/skymatch/skystatistics.rst
docs/jwst/wiimatch/index.rst
jwst/mrs_imatch/__init__.py
jwst/mrs_imatch/mrs_imatch_step.py
jwst/skymatch/__init__.py
jwst/skymatch/skyimage.py
jwst/skymatch/skystatistics.py

This PR addresses the issue https://github.com/STScI-JWST/jwst/issues/741 for `skymatch` and also adds documentation for `mrs_imatch`.

updated docs for skymatch and mrs_imatch

---

jwst/associations/lib/update_path.py
jwst/associations/tests/test_associations.py
jwst/associations/tests/test_update_path.py

This utility allows for easy modification of file paths in
associations.  Currently API only; command line to come later.

Add utility module update_path

---

jwst/dark_current/dark_current_step.py
jwst/dark_current/dark_sub.py

Changes:
- Document flag
- If specified, will write out either the averaged dark or
the dark model from the reference file.
Resolves #1017

Document dark_output config parameter

---

jwst/resample/resample_utils.py

Fix issue #947

---

jwst/white_light/white_light_step.py

Rename white light suffix to 'whtlt'

---

jwst/lib/catalog_utils.py
jwst/source_catalog/source_catalog.py
jwst/source_catalog/source_catalog_step.py
jwst/tso_photometry/tso_photometry_step.py
jwst/white_light/white_light_step.py

This PR moves this function from `source_catalog` to `lib`.

Add catalog naming function to lib

---

jwst/pipeline/calwebb_spec2.cfg
jwst/pipeline/calwebb_spec2.py
jwst/pipeline/tests/data/calwebb_spec2.cfg
jwst/pipeline/tests/data/calwebb_spec2_basic.cfg
jwst/pipeline/tests/data/calwebb_spec2_save.cfg
jwst/pipeline/tests/test_calwebb_spec2.py
jwst/pipeline/tests/test_calwebb_spec2_nrs_msa.py

Include updated tests and configurations.
WIP #644

Incorporate msa flagging into calwebb_spec2

---

jwst/stpipe/step.py

Arrrggghhhhh....argggghhhhh
arggghhhhhhh
and one more....arrrrgggghhhhh
Resolves #1128

Allow dash as a calibration suffix indicator

---

jwst/persistence/persistence.py

The generic get_subarray function was replaced with two model-specific functions, get_subarray_trapdensity and get_subarray_persat.  The test for the existence of the dq attribute of a reference file model was not working, and this has been fixed.  See issue #1129.

Problems with subarrays in the persistence step.

---

jwst/mrs_imatch/mrs_imatch_step.py

Docs have not been building, traced to this one line in a comment.
Ya, this was fun. I really enjoyed the experience...

Comment documentation to deal with sphinx error [skip-ci]

---

jwst/pipeline/calwebb_image2.cfg
jwst/pipeline/calwebb_image2.py
jwst/pipeline/calwebb_spec2.cfg
jwst/pipeline/calwebb_spec2.py
jwst/pipeline/tests/data/calwebb_image2_save.cfg

Add background subtraction to Image2Pipeline

---

jwst/stpipe/crds_client.py

Attempting to modify behavior with py.test and interpretation of assertions vs. exceptions.

Switched crds_client.reference_uri_to_cache_path() from AssertionError to CrdsError

---

docs/jwst/package_index.rst

Add an entry for the gain_scale step docs to the package index.

Add gain_scale docs to package index

---

docs/jwst/ramp_fitting/main.rst
jwst/ramp_fitting/ramp_fit.py
jwst/ramp_fitting/ramp_fit_step.py
jwst/ramp_fitting/utils.py

New version of changes committed in #1166 in order to resolve conflicts that appeared (somewhat mysteriously) in that PR. This is a direct copy of the files committed in that PR, which adds computation of slope variances based on read noise and Poisson noise to the ramp_fit step.

Ramp_fitting error propagation

---

jwst/lib/catalog_utils.py
jwst/source_catalog/source_catalog_step.py

Fix ecsv typos

---

jwst/tso_photometry/tso_photometry_step.py

Optionally write TSO photometry exposure-level catalogs

---

jwst/stpipe/step.py

Don't die if an output file cannot be found

---

jwst/assign_wcs/nirspec.py
jwst/assign_wcs/tests/test_nirspec.py
jwst/datamodels/schemas/multislit.schema.yaml
jwst/extract_2d/extract_2d.py
jwst/transforms/models.py

add Slit.shutter_state

---

jwst/pipeline/calwebb_coron3.py

Some changes got made in fc659f9cef646a1a91cac4e499fc0cbac0ba431f and then undone by 964fefc4a1272f7d0edde60feb293fae18ba1456
This fixes those conflicts.

Remove mk_prodname call in calwebb_coron3

---

jwst/pipeline/calwebb_tso3.py

- fix bug populating asn pool name in final output
- reorder some logging messages
- rename variables for clarity

Populate asn pool name correctly in final output

---

jwst/datamodels/schema_editor.py

The schema editor has been changed in order to better report differences between the keyword database and model schemas. There are fewer false differences and the matching is better, as it now tries to match on both the fits keyword name and model schema name.

Schema editor changes

---

jwst/assign_wcs/nircam.py

assign_wcs for NRC_TSGRISM mode is implemented. **Before merging** I need some more information on the source location in the subarrays. Is the source pixel location saved in the meta information somewhere, or is it a known value for each subarray? @hbushouse ?

NRC_TSGRISM mode initial implementation for assign_wcs

---

jwst/cube_build/blot_cube_build.py
jwst/cube_build/cube_build.py
jwst/cube_build/cube_build_io_util.py
jwst/cube_build/cube_build_step.py
jwst/cube_build/cube_build_wcs_util.py
jwst/cube_build/data_types.py
jwst/cube_build/file_table.py
jwst/cube_build/ifu_cube.py

@hbushouse 
@stscieisenhamer 
Finished looping over cube_build to make a set of default IFU Cubes. In the spec2 pipeline we want to make only 1 single IFUCube so we need to use --ouput_type = 'multi'
In the spec3 pipeline a set of IFUCube are returned from cube_build_step. These IFUCubemodels are stored in a ModelContainer. 
Cube_build creates all the filenames for each IFUCube.

Single band

---

jwst/pipeline/calwebb_tso3.py

PR #1231 changed a variable name to one that was already in use elsewhere, inadvertently braking the writing out of Level 2c files.  This fixes that bug.

Fix input_models var name bug

---

jwst/cube_build/__init__.py
jwst/cube_build/cube_build_step.py
jwst/cube_build/ifu_cube.py

Added bunits to ifucube and the error units 
Fixed a bug in how NIRSPEC name was formed

added units and fixed NIRSPEC bug

---

jwst/cube_build/cube_build.py
jwst/cube_build/cube_build_step.py
jwst/cube_build/data_types.py
jwst/cube_build/ifu_cube.py

This fixes issue #1285 
Also updated the way the out put file name is created, added an option 'pipeline' if 'pipeline =2' then uses calspec2 rules. No need to use the output_type='multi' in calspec2. If pipeline=2 then internally output_type= 'multi'

Blendheaders

---

jwst/background/background_step.py
jwst/background/background_sub.py
jwst/pipeline/background.cfg
jwst/pipeline/calwebb_spec2.py

Instead of directly using the limits in the source catalog, call `create_grism_bbox`, with the source catalog and the `wavelengthrange` reference file.  Then get the limits of the bounding box from the returned list.

Use an assign_wcs function

---

jwst/source_catalog/source_catalog.py
jwst/source_catalog/source_catalog_step.py

Handle case when no sources are found

---

jwst/jump/tests/test_twopoint_difference.py

Fix jump test module so that it'll execute in the jwst package environment.

Fix jump test module

---

jwst/fits_generator/templates/miri_imaging_dither_pattern.gen.inc
jwst/fits_generator/templates/miri_lrs_dither_pattern.gen.inc
jwst/fits_generator/templates/nircam_dither_pattern.gen.inc
jwst/fits_generator/templates/target_information.gen.inc
jwst/fits_generator/templates/visit_information.gen.inc

FITS files created by create_data can now be opened as datamodels

Modified default values for keywords VISITYPE, PROPEPOC and NUMDTHPT

---

jwst/stpipe/step.py

A previous commit expanded the results list
to treat incoming `ModelContainer`s as an iterable,
resulting in filenames being overwritten by the indexed version.
The list is recreated forcing a `ModelContainer` to be witin the list
as opposed to representing the list.
This is actually a component of PR #1316, but has warranted its own PR.  Should really have been so in the first place.

Fix step.run itiration bug when saving

---

jwst/photom/photom.py

Updates the nirspec branch of the photom step to not assume that all fixed-slit data will come in the form of a MultiSlitModel, because NRS_BRIGHTOBJ are CubeModel. It now handles BRIGHTOBJ exposures separately from NRS_FIXEDSLIT exposures. So once #1329 is fixed, such that BRIGHTOBJ data make it to the photom step in calwebb_spec2, it should work OK. I've already verified that extract_1d handles the CubeModel properly.
Fixes #1331

Update photom to handle NRS_BRIGHTOBJ CubeModel

---

jwst/extract_1d/extract.py

Rename dunderdel to reset

---

jwst/flatfield/flat_field.py

NIRSpec BRIGHTOBJ data are in a CubeModel, which wasn't previously supported for NIRSpec data.

Support NIRSpec BRIGHTOBJ data

---

jwst/pipeline/mrs_imatch.cfg

Created a mrs_imatch.cfg file.
Fixes #1287.

Added mrs_imatch cfg file [skip ci]

---

jwst/assign_wcs/util.py
jwst/datamodels/schemas/wcsinfo.schema.yaml

Set the default to " " in the core schema. Updated the order of vertices reported in assign_wcs.

default value of S_REGION

---

jwst/flatfield/flat_field.py

For NRS_BRIGHTOBJ data, there was an error in the test for deciding whether
to get the wavelengths from the wavelength attribute, or from the wcs
function, or to skip the step.  See issue #1401.

Wavelengths might not be determined correctly.

---

jwst/lib/set_telescope_pointing.py

This adds CTYPE3 and CUNIT3 values if `WCSAXES==3`. 
It may be moved to SDP processing for build 7.2.

Add ctype and cunit for the spectral axis

---

jwst/exp_to_source/exp_to_source.py
jwst/resample/resample_spec_step.py

Preserve slit order in exp_to_source

---

jwst/pipeline/calwebb_image2.py

PR #1419 added the resample step to the calwebb_image2 pipeline. Resampling has to be skipped for any time-series (TSO) exposures. Not only is resampling not wanted for TSO data, it also crashes in the resample step, because it doesn't know how to handle 3-D data arrays.

Don't resample TSO exposures in calwebb_image2

---

jwst/cube_build/cube_build_step.py

Added a description to the spec options

Option info

---

jwst/pipeline/calwebb_image2.py
jwst/resample/resample.py

Populate metadata from _cal to _i2d in image2 pipeline

---

jwst/resample/resample.py

Change index on input_model for resample

---

src/tweakreg/carrutils.c

This PR handles the issue of compile warnings in `carrutils.c` file - see https://github.com/STScI-JWST/jwst/issues/1224 for more details.

Fix C compile warnings in carrutils.c

---

jwst/resample/resample.py

Merging this PR into master since it looks like there won't be another delivery to dms.

0.8.1 bug fix

---

jwst/transforms/tpcorr.py

Move TPCorr to transformations package - follow-up

---

jwst/outlier_detection/outlier_detection.py
jwst/outlier_detection/outlier_detection_ifu.py
jwst/outlier_detection/outlier_detection_spec.py
jwst/outlier_detection/outlier_detection_step.py

Fix outlier_registry keyword

---

jwst/transforms/jwextension.py
jwst/transforms/schemas/tpcorr-0.7.0.yaml
jwst/transforms/tags/jwst_models.py
jwst/transforms/tpcorr.py

CC: @nden Please review this PR.

Add schema to support tangent plane WCS corrections

---

docs/jwst/persistence/description.rst

A description of how trap capture and decay are calculated has been added
to description.rst.  See issue #1492.

Update documentation for persistence

---

jwst/datamodels/model_base.py

Several metadata keywords: date, model_type, and filename are set when a model is opened and saved and should not be overwritten whan one model is updated from another. This code change checks keywords against this list and doesn't update them if they are on it.

Modify the update method to not copy certain protected keywords

---

jwst/stpipe/crds_client.py

1. Cached dataset headers are constrained to simple Python values to preclude
complex memory leaks.
2. Exception-based header and results caching is modified so that the uncached
calls do not occur within the "not already cached" exception,  a cache miss is not really an exception.   This prevents confusing error messages where the original exception is driven by the cache miss and the real exception is secondary and nested,  caused by the real work used to fill the cache.

Crds client optimization updates

---

jwst/outlier_detection/__init__.py
jwst/outlier_detection/outlier_detection.py
jwst/outlier_detection/outlier_detection_ifu.py
jwst/outlier_detection/outlier_detection_scaled.py
jwst/outlier_detection/outlier_detection_scaled_step.py
jwst/outlier_detection/outlier_detection_spec.py
jwst/outlier_detection/outlier_detection_stack_step.py
jwst/outlier_detection/outlier_detection_step.py

Remove python 2 compatibility code from outlier_detection

---

jwst/extract_1d/ifu.py
jwst/extract_1d/spec_wcs.py

I missed two files when I did this earlier:  ifu.py and spec_wcs.py.

Remove 'from __future__ import ...'

---

docs/jwst/pipeline/description.rst

Updated the pipelines summary doc to include B7.1 changes in level-2a and level-2b pipelines and new level-3 pipelines.

Updated pipeline docs for B7.1 changes

---

jwst/flatfield/flat_field.py

When looping over input slits for NIRSpec data, and for the case that an
output file with the computed flat fields will be written, set the flat field
to a constant 1 and data quality to 0 for any input slit for which processing
is skipped.  Also set the output wavelength attribute to constant 0.
See issue #1547.

Correct potential problem with indexing in flat_field

---

docs/jwst/background/description.rst

Describe how the step does the background subtraction for WFSS data,
and describe (briefly) the two reference files.  Also note that the
code to do this processing is currently commented out because there
are no background reference files yet.  See issue #1545.

Add a description of background subtraction for WFSS data

---

jwst/flatfield/flat_field.py

When there is no WAVELENGTH extension in the input file, the shape of the
wavelength attribute is apparently (0, 0) rather than being the shape of
the science data.  Using .min() or .max() on such an array fails.
See issue #1374.

Modify test in flat_field for nonexistent WAVELENGTH extension

---

docs/jwst/ami/main.rst
docs/jwst/introduction.rst
docs/jwst/photom/main.rst
docs/jwst/photom/reference_files.rst
docs/jwst/pipeline/description.rst
docs/jwst/srctype/description.rst
docs/jwst/white_light/description.rst
docs/jwst/white_light/reference_files.rst

What started out as updates to the introductory pipeline document has expanded into additional updates to the pipelines description document, as well as updates to the docs for several steps.

Doc updates for pipelines and steps

---

jwst/dq_init/dq_init_step.py

Recent updates to datamodels now cause a TypeError when a GuiderRawModel data model, loaded via the calwebb_guider pipeline, is passed as input to the dq_init step when it tries to open the input as a regular RawModel. So I added some traps to handle the different cases of either a GuiderRawModel being passed in in memory, as well as a guider-mode file being passed in. The dq_init step should now detect those cases and, when necessary, reload the input as a GuiderRawModel.

Update dq_init to handle Guider raw data as input

---

jwst/assign_wcs/assign_wcs.py
jwst/assign_wcs/tests/test_nirspec.py
jwst/assign_wcs/tests/test_wcs.py
jwst/datamodels/schemas/wcsinfo.schema.yaml

Reverts STScI-JWST/jwst#1499
It broke master.

Revert "remove defaults"

---

docs/jwst/cube_build/main.rst
docs/jwst/cube_build/reference.rst
jwst/cube_build/cube_build.py
jwst/cube_build/cube_build_io_util.py
jwst/cube_build/cube_build_step.py
jwst/cube_build/ifu_cube.py

Fix for NIRSPEC bug when creating "single" type IFU Cubes. 
Various updates to documentation

Straylight

---

README.md

Add STScI and Astropy badges

---

jwst/datamodels/container.py

- Minimally specify the keywords that allow figuring out which files are of the same exposure and which are of different exposures.
- Give a more useful error message if grouping can't be done based on the metadata.
- Don't check if group names have already been made.
- If metadata for grouping is not available in the files, default to assuming they are different exposures.
Resolves #1590.

Make ModelContainer exposure grouping more robust across instruments

---

docs/jwst/assign_wcs/reference_files.rst
jwst/assign_wcs/assign_wcs_step.py

update description of distortion reference file

---

docs/jwst/cube_build/main.rst
docs/jwst/cube_build/reference.rst

Jane- I've made some suggested modifications here regarding the overall cube build process documentation.  I haven't really touched the details of the cubepar reference files though since these are slated to be updated soon anyway.

Tweaks to cube building documentation

---

README.md

Fix #198
c/c @rendinam @jhunkeler

Replace nightly doc build with RTD

---

docs/jwst/assign_wcs/asdf-howto.rst
docs/jwst/assign_wcs/reference_files.rst

Clarify thatthe inputs to the distortion file ar ein DMS coordinates (suggested by an INS team).

improve ref file docs

---

jwst/mrs_imatch/__init__.py
jwst/mrs_imatch/mrs_imatch_step.py

Updated the mrs_imatch step to set the step completion status in the input images, add a log message when applying the background subtraction, and remove python 2 dependencies.

Remove py2 dependencies and add step completion status

---

jwst/assign_wcs/nirspec.py

fix nirspec slit validation code

---

jwst/assign_wcs/pointing.py

fix units in compute_roll_ref

---

jwst/transforms/models.py

do not allow negative RA

---

docs/jwst/guider_cds/arguments.rst
docs/jwst/guider_cds/description.rst
docs/jwst/guider_cds/index.rst
docs/jwst/guider_cds/reference_files.rst
docs/jwst/package_index.rst
docs/jwst/pipeline/description.rst

Added a description of the calwebb_guider pipeline to the pipeline doc, and added docs for the guider_cds step.

Add docs for guider pipeline

---

docs/jwst/pipeline/description.rst

Fixed a problem with a table display of the steps in the calwebb_guider pipeline.

Fix error in calwebb_guider description

---

setup.py

@jhunkeler The only way I can get `transform/schemas/*` installed from the new location is to add
`install_package_data` to `setup`. Does this look right?

install schemas

---

jwst/persistence/persistence.py

The function `predict_saturation_capture` for predicting the number of charges trapped during the saturated portion of a ramp is now called with a mask to include only pixels for which at least part of the ramp is saturated (in the sense of being greater than the persistence saturation limit).  See issue #1599.

Only call the function for saturated data if some groups are saturated.

---

jwst/datamodels/properties.py
jwst/datamodels/tests/test_models.py

fix ObjectNode iterator

---

jwst/persistence/persistence.py

The slope is set to zero for pixels in the persistence saturation limit reference file that are flagged with `DO_NOT_USE`.  The trap density is set to zero for pixels in the trap density reference file that are flagged with `DO_NOT_USE` (resulting in no increase in the number of filled traps).  See issue #1635.

Use DQ extensions of persat and trap_density

---

jwst/assign_wcs/nirspec.py
jwst/datamodels/multislit.py
jwst/datamodels/slit.py
jwst/photom/photom_step.py

Make sure the wcs object is stored with the slit after extract_2d.
Fix copy and paste error.

fix problems created by #1070

---

jwst/datamodels/schemas/slitdata.schema.yaml

allow 3d arrays in slits

---

jwst/cube_build/cube_build_wcs_util.py
jwst/flatfield/flat_field.py

fix test failures 

---

jwst/flatfield/flat_field.py

fix last known error from reg tests

---

jwst/assign_wcs/assign_wcs.py
jwst/extract_2d/nirspec.py

gracefully skip extract_2d if assign_wcs was skipped

---

jwst/photom/photom.py

Updated the photom step so that it loops over all slit instances in a NIRCam WFSS (grism) exposure, attaching a RELSENS for each slit. Had updated a while back to do this same thing for NIRISS WFSS, but failed to include NIRCam at that time.

Update photom for NIRCam WFSS

---

setup.py

Let's see if this works.
xref sphinx-doc/sphinx#4623
p.s. I used GitHub web interface to open this PR. To my chagrin, as a result, it kicks off two different Travis runs per commit. I cancelled the second one ("push" event) because it is redundant.

DOC: Fix Sphinx build on Travis CI

---

jwst/outlier_detection/outlier_detection.py

This should address the problem outlined in issue #1771 .

Fix problem with no background values

---

jwst/assign_wcs/tools/nirspec/compute_world_coordinates.py
jwst/extract_2d/nirspec.py

The Nirspec WCS expects 1-based coordinates.
Related to #1732.

use 1-based cooridnates with the NRS WCS

---

jwst/pipeline/calwebb_ami3.py

Blend actual input models instead of blended products

---

jwst/cube_build/ifu_cube.py

Fixed a bug when making MIRI alpha-beta IFU cubes.

Fixed bug when making alpha-beta cubes

---

jwst/cube_build/cube_cloud.py
jwst/cube_build/ifu_cube.py

This does not fix the nirspec wcs from 0 based to 1 based. This pr just removes some unnecessary code involving determining the x,y values for a NIRSPEC slice.

removed some unnecessary code

---

jwst/pipeline/tests/test_nrc_image3.py

Apparently something else fixed this issue (#1316 possibly).
Resolves #1537

Added test for single file input to calwebb_image3

---

jwst/datamodels/schemas/dark.schema.yaml
jwst/datamodels/schemas/keyword_gainfact.schema.yaml
jwst/datamodels/schemas/linearity.schema.yaml
jwst/datamodels/schemas/readnoise.schema.yaml
jwst/datamodels/schemas/saturation.schema.yaml
jwst/datamodels/schemas/superbias.schema.yaml
jwst/gain_scale/gain_scale_step.py
jwst/ramp_fitting/ramp_fit_step.py

Schema and step change to add additional support for GAINFACT and to change the data models path for reference files from meta.gain_factor to meta.exposure.gain_factor.  See issue #1810.

Update reference file gain_factor schema,  #1810

---

docs/jwst/outlier_detection/index.rst
docs/jwst/outlier_detection/outlier_detection.rst
docs/jwst/outlier_detection/outlier_detection_ifu.rst
docs/jwst/outlier_detection/outlier_detection_spec.rst
docs/jwst/outlier_detection/outlier_detection_step.rst
docs/jwst/resample/resample.rst
docs/jwst/resample/resample_step.rst
jwst/resample/resample_utils.py

Fairly extensive update to the outlier_detection step documentation to try to make it a little more user-friendly (read that: human readable as opposed to strictly describing the API).  
This should address many of the points raised in #1731 .

Update outlier docs

---

README.md

Adds a mapping between JWST release versions and DMS builds

add versions map

---

jwst/pipeline/tests/test_calwebb_spec3_mir_mrs_dither.py
jwst/ramp_fitting/ramp_fit_step.py

Mischievously rejected from PR #1070 by PR #1316
and caught red-handed doing so.

Re-introduce patch for IFUModelImage

---

jwst/datamodels/__init__.py
jwst/datamodels/schemas/wfssbkg.schema.yaml
jwst/datamodels/wfssbkg.py

Add definitions for the WfssBkgModel, for use with WFSS master background reference files. Fixes #1827.

Add WfssBkgModel data model

---

jwst/transforms/models.py

fix computation of prism refraction index

---

jwst/model_blender/blendmeta.py
jwst/resample/resample_spec_step.py
jwst/resample/resample_utils.py

Fix resample output frame offset

---

jwst/lib/pipe_utils.py
jwst/pipeline/calwebb_spec2.py
jwst/pipeline/tests/test_nrs_spec2_bright_obj.py

Implement more robust TSO checking

---

docs/jwst/photom/main.rst
docs/jwst/photom/reference_files.rst

#983 updated the photom step to fix #976. This now (finally) updates the photom docs to bring them up to date with those code changes.

Update photom docs for PIXAR_nn handling

---

jwst/outlier_detection/outlier_detection_step.py

OutlierDetection returns input rather than a copy of input for singletons

---

jwst/assign_wcs/pointing.py
jwst/assign_wcs/tests/test_wcs.py

@jemorrison reported that cubes in the alpha_beta frame cannot be saved any more.
Fixed in this PR, tests added.

fix custom frame serialization

---

jwst/assign_wcs/nirspec.py
jwst/assign_wcs/tests/test_nirspec.py
jwst/assign_wcs/tools/nirspec/compute_world_coordinates.py
jwst/extract_1d/extract.py
jwst/extract_1d/ifu.py
jwst/extract_2d/nirspec.py
jwst/flatfield/flat_field.py

Related to #1781. Implements the chnage in one place - ~assign_wcs.nirspec.detector_to_gwa()`

Nirspec: 1- vs 0- based pixel coordinates

---

jwst/skymatch/skyimage.py

Fixes error introduced in https://github.com/STScI-JWST/jwst/issues/1858
CC: @stsci-hack @pllim @hbushouse

Remove extraneous spherical_geometry occurence

---

jwst/datamodels/model_base.py

The update method does not validate its changes after they are applied. This change adds a call to validate so that they are validated. This call addresses issue #1824.

Add validation to update method

---

jwst/datamodels/model_base.py

The __init__ function of model_base is an ungainly beast that I've tried to tame. The current code is correct, but I've re-arranged it and added comments. There's one improvement: intializing a datamodel from a shape fails if the model has no data section, as it should. I catch the confusing attribute error and raise a more explanatory type error instead.

Clean up datamodels model_base __init__

---

README.md

Added a few more details and updated info to jwst tag vs. DMS build info table.

Update DMS build info in README

---

README.md

An update to the installation instructions to the README to point to using conda to install and maintain the software and its dependencies.

Install readme

---

docs/jwst/rscd/description.rst
docs/jwst/rscd/reference_files.rst
jwst/cube_build/cube_build_step.py
jwst/datamodels/schemas/rscd.schema.yaml
jwst/rscd/rscd_step.py
jwst/rscd/rscd_sub.py

Updated RSCD correction algorithm. I updated some of the documentation. 
This update requires a new reference file. Misty Cracraft is going to get them into CRDS but
this might take a little time. So we need to be careful when this is merged.

Updated RSCD correction and docs

---

jwst/stpipe/pipeline.py

Implementation resolving #1900.

Added INFO log message to pipeline prefetch to report exposure filenames

---

jwst/assign_wcs/tests/test_wcs.py
jwst/lib/set_telescope_pointing.py
jwst/transforms/models.py

This fixes a regression introduced in #1911.

Fix units n V2V3 to sky

---

jwst/persistence/__init__.py
jwst/persistence/persistence_step.py
jwst/pipeline/tests/test_nrc_detector1.py

Add configuration parameter save_trapsfilled to the persistence step

---

jwst/rscd/rscd_step.py
jwst/rscd/rscd_sub.py

Added a check that the correct entry in the reference file is found. If it is not found then throw an exception. I also updated the Imager RSCD reference file and sent it to Misty who will get it in CRDS, then this step will work for SUBPRISM data (the reference file assumed it was SLITLESSPRISM)

Rscd error

---

jwst/assign_wcs/fgs.py
jwst/assign_wcs/niriss.py

Fixes a problem reported on basecamp. Tested locally.

fix and clean niriss and fgs bbox

---

jwst/tests_nightly/general/pipelines/test_coron3_1.py
jwst/tests_nightly/general/pipelines/test_image2pipeline_1.py
jwst/tests_nightly/general/pipelines/test_miri_lrs_slit_1b.py
jwst/tests_nightly/general/pipelines/test_nirspec_dark.py
jwst/tests_nightly/general/pipelines/test_nrs_msa_spec2.py
jwst/tests_nightly/general/pipelines/test_nrs_msa_spec2b.py

This only updates the tests under 'general/pipelines' so that they will run to completion and perform comparisons on all products from each test.

Regtest poc

---

jwst/tests_nightly/general/nirspec/test_bias_drift.py
jwst/tests_nightly/general/nirspec/test_dark_step.py
jwst/tests_nightly/general/nirspec/test_dq_init.py
jwst/tests_nightly/general/nirspec/test_extract2d_msa_8slits.py
jwst/tests_nightly/general/nirspec/test_extract_1d.py
jwst/tests_nightly/general/nirspec/test_extract_2d.py
jwst/tests_nightly/general/nirspec/test_flat_field.py
jwst/tests_nightly/general/nirspec/test_group_scale.py
jwst/tests_nightly/general/nirspec/test_imprint.py
jwst/tests_nightly/general/nirspec/test_jump.py
jwst/tests_nightly/general/nirspec/test_linearity.py
jwst/tests_nightly/general/nirspec/test_nrs1_fs_wcs.py
jwst/tests_nightly/general/nirspec/test_nrs1_ifu_wcs.py
jwst/tests_nightly/general/nirspec/test_nrs1_ifu_wcs_2.py
jwst/tests_nightly/general/nirspec/test_nrs2_ifu_wcs.py
jwst/tests_nightly/general/nirspec/test_photom.py
jwst/tests_nightly/general/nirspec/test_ramp_fit.py
jwst/tests_nightly/general/nirspec/test_saturation.py
jwst/tests_nightly/general/nirspec/test_superbias.py

This only updates the tests under 'general/nirspec' so that they should run to completion and perform comparisons on all products from each test.

Updates to nirspec regtests

---

jwst/cube_build/coord.py
jwst/cube_build/cube_cloud.py

@hbushouse @drlaw1558
This keeps xi running in the opposite direction as ra. This pull request fixed the backwards transform

add xi=-xi when going from xi,eta to ra-dec - backwards transform

---

jwst/msaflagopen/msaflag_open.py

Fixes problem when masflagopen is run on NRS_IFU data

---

jwst/tests_nightly/general/pipelines/test_image2pipeline_2.py
jwst/tests_nightly/general/pipelines/test_image2pipeline_2b.py
jwst/tests_nightly/general/pipelines/test_nis_wfss_spec2.py

Now there is no `[ci skip]` from the commit so that Jenkins will kick off the build.

Fix docstrings

---

jwst/tweakreg/wcsimage.py

I have accidentally discovered a minor bug in the tweakreg code. This PR fixes this bug.

Fix a minor bug in tweakreg due to a copy/paste error

---

docs/jwst/associations/asn_from_list.rst
docs/jwst/associations/index.rst
docs/jwst/associations/level2_asn_technical.rst
docs/jwst/associations/level3_asn_technical.rst

WIP #168 
[WIP JP-299](https://jira.stsci.edu/browse/JP-299)

Update association documentation for asn_from_list [ci skip]

---

jwst/datamodels/container.py

Strip abspath from ASNTABLE keyword value

---

jwst/datamodels/schemas/core.schema.yaml
jwst/datamodels/schemas/ifucube.schema.yaml

A bunch of keyword updates in the core schema, to bring things into sync with Keyword Dictionary. Several new keywords and a few modifications to existing ones. Some of the new ones are still being worked in SDP and hence don't yet show up in DMS products, but we'll be ready for them when they do.

Keyword updates

---

jwst/stpipe/step.py

Move initial Step logging to beginning of run

---

scripts/schema_editor

I added a short script that inokes the schema editor to the scripts directory.

A new script to invoke the schema editor

---

docs/jwst/straylight/arguments.rst
docs/jwst/straylight/main.rst
docs/jwst/straylight/reference.rst
jwst/straylight/straylight.py
jwst/straylight/straylight_step.py

Updated new straylight algorithm. This closes #1873

update to stray-light algorithm

---

jwst/straylight/straylight_step.py

fixed comments for method,roi and power

fixed method comment

---

jwst/cube_build/cube_build.py
jwst/cube_build/cube_build_step.py
jwst/cube_build/cube_build_wcs_util.py
jwst/cube_build/ifu_cube.py
jwst/datamodels/schemas/core.schema.yaml
jwst/pipeline/cube_build.cfg

Added model blender to cube_build.
I still need to add functions to override some of the values (for example, Channel)
@hbushouse 
@stsci-hack

add model blender

---

jwst/model_blender/blendmeta.py

This fixes the errors that showed up in the evening regression tests after merging PR #2024.

Fix using models

---

jwst/extract_1d/extract.py

The `find_dispaxis` function used the wavelengths to determine which is the dispersion axis.  The wavelengths may be taken from the wavelength attribute (extension in the input file), or they may be computed by using the wcs function.  Wavelengths are not necessarily defined over the entire data range, and the previous assumption that the wavelength would be NaN for pixels for which the wavelength could not be determined was not always correct; sometimes the wavelength is 0.  `find_dispaxis` has been modified to treat both 0 and NaN as invalid.
Also in `find_dispaxis`, it was necessary to explicitly set the value of the spectral order for NIRISS SOSS data.
See issue #2031.

In find_dispaxis, regard wavelength = 0 as invalid

---

JenkinsfileRT

Updating regression tests to latest CRDS context.

Update Jenkins CRDS_CONTEXT to 460

---

JenkinsfileRT

For NIRSPEC SFLAT NRS_AUTOWAVE handling.

Update regression context to jwst_0461.pmap

---

jwst/datamodels/fits_support.py

This fix allows programs to read compressed image extensions from fits files and update them. The main change has been to how the code determines the type of an extension. It no longer assumes that anything that's not a binary table is a regular image extension. The code that reads and writes compressed images is layered on top of the astropy fits library code.
This fix addresses issue #1915

Add support for compressed image extensions to datamodels

---

jwst/pipeline/tests/test_nrs_tso3.py

WIP #2069
Just adding the test used to verify operation.

Add test for NRS TSO3 data

---

jwst/associations/lib/dms_base.py
jwst/associations/lib/rules_level3_base.py

Add NRC_WFSS as an exposure type

---

jwst/rscd/rscd_step.py
jwst/rscd/rscd_sub.py

fixed error on FASTGRPAVE data

---

jwst/pipeline/calwebb_ami3.cfg
jwst/pipeline/collect_pipeline_cfgs.py
jwst/pipeline/tests/test_nis_ami3.py
scripts/collect_pipeline_cfgs

Resolves #2047 
Also, upgraded script `collect_pipeline_cfgs` so that is now an API and can be used for things like testing.

Ensure ami_avg products are saved as default

---

jwst/wfs_combine/wfs_combine_step.py

This resolves a small issue from #2082.

Make association reader level 3 for wfs_combine_step

---

jwst/assign_wcs/assign_wcs.py
jwst/assign_wcs/assign_wcs_step.py
jwst/assign_wcs/fgs.py
jwst/assign_wcs/miri.py
jwst/assign_wcs/nircam.py
jwst/assign_wcs/niriss.py
jwst/assign_wcs/nirspec.py
jwst/assign_wcs/util.py

The only change other than docstrings here is that the units are correctly set to "arcsec" in V2V3, now that the reference files and code provide transforms in arcsec. This has no effect on the computations because the coordinate frames are only for information and not used in the computation.

update docstrings and comments

---

jwst/assign_wcs/assign_wcs_step.py

skip assign_wcs if the MSAMETFL keyword is not populated correctly

---

jwst/transforms/models.py
jwst/transforms/tpcorr.py

The attribute name in modeling has changed so make the change in transforms as well.
This has no effect on the pipeline but may be useful for data analysis tools.

update the _separable attribute of models

---

docs/jwst/extract_2d/main.rst
jwst/extract_2d/extract_2d.py
jwst/extract_2d/extract_2d_step.py
jwst/extract_2d/nirspec.py

extract_2d docs

---

jwst/assign_wcs/nirspec.py

Implements [this comment](https://github.com/STScI-JWST/jwst/pull/2110#issuecomment-393901280) - the msa metafile  is now opened in a `try ... except` block .

check for valid fits msa metafile in function

---

jwst/tests_nightly/general/pipelines/test_nis_wfss_spec2.py

Xfail test_nis_wfss_spec2 regression test

---

jwst/assign_wcs/nirspec.py

Revert "NRS: fix input units to meters when filter=OPAQUE"

---

jwst/pathloss/path_loss.py

Fix out-of-bounds issue in pathloss step in #2094

---

jwst/stpipe/cmdline.py
jwst/stpipe/step.py

Better guessing at input/output filenames when running steps from scripts

---

jwst/assign_wcs/nirspec.py

Wavelength units of inputs to `wcs.invert` should be microns in the case of `fitler=OPAQUE`.
Alternative implementation of #2134

WIP: fix wavelength units of inverse transform

---

jwst/assign_wcs/nirspec.py

Revert "WIP: fix wavelength units of inverse transform"

---

jwst/assign_wcs/assign_wcs_step.py
jwst/assign_wcs/nirspec.py
jwst/assign_wcs/tests/test_nirspec.py
jwst/assign_wcs/util.py

raise an error if msa metafile is missing

---

jwst/extract_1d/extract.py

There's now a default of `None` for the dispersion axis, primarily so that the initial value (along with other parameters) can be logged without crashing.
The function that finds the dispersion axis from the wavelengths uses either `log.warning` or `log.debug` to write the value from the log file and the value determined from the wavelengths, depending on whether there was a discrepancy or not.
If the dispersion direction could not be determined, spectral extraction will be skipped.  Extraction will also be skipped if the spectral order is 0, unless the data were taken with a prism.
See issue #2102.

Skip spectral extraction if dispaxis could not be determined

---

jwst/assign_wcs/util.py

Round S_REGION RA/Dec values to 9 decimal places

---

jwst/tests_nightly/general/pipelines/test_nrs_msa_spec2b.py

I broke this test by uncommenting some old code in #2181.  Removing that code.

Fix test_nrs_msa_spec2b

---

jwst/extract_1d/extract.py

Method `offset_from_offset` was modified to include slit as a new argument.  If `slit` is defined, some of the parameters (e.g. v2_ref) will now be gotten from `slit`; otherwise, those parameters will be gotten from `input_model`.  Checks were added for the existence of attributes.  For NIRSpec data, if `v3yangle` or `vparity` is not defined in the input, a default value is used.
See issue #1894.

For extract_1d, find nod/dither offset from XOFFSET, YOFFSET

---

README.md

Update README: Travis badge URL

---

jwst/pipeline/calwebb_image2.py

Strip folder path from table and pool name keywords

---

docs/jwst/rscd/description.rst
docs/jwst/rscd/reference_files.rst

updated RSCD documentation

---

jwst/assign_wcs/nirspec.py

Better error handling for missing entry in wavelengthrange file.

---

jwst/pipeline/calwebb_spec2.py
jwst/pipeline/tests/test_calwebb_spec2_nrs_msa.py

Show full tracebacks when a product errors.

---

jwst/refpix/reference_pixels.py
jwst/refpix/refpix_step.py

Refpix subarrays

---

jwst/datamodels/__init__.py
jwst/datamodels/schemas/core.schema.yaml
jwst/datamodels/schemas/tsophot.schema.yaml
jwst/datamodels/tsophot.py

This adds a data model and schema for a new reference file type tsophot for `tso_photometry`.  See issue #1619.

New model and schema for tsophot

---

jwst/transforms/jwst_types.py

remove six from transforms

---

jwst/rscd/rscd_sub.py

Update the core slope-fitting function used in the RSCD step to use array-based calculations, instead of looping over pixels. This speeds up the calculations by about 20x.

RSCD update to array-based math

---

jwst/pathloss/path_loss.py

Pathloss step: fixes wavelength array out of bounds error

---

docs/jwst/fits_generator/template.rst

Rewrite, take out obsolete words and references

---

jwst/pipeline/calwebb_tso_image2.cfg
jwst/pipeline/calwebb_tso_spec2.cfg

Implement TSO-specific Level2 configs

---

docs/jwst/transforms/tpcorr.rst
jwst/transforms/tpcorr.py

fix warnings in transforms

---

docs/jwst/refpix/description.rst

Added description for subarray processing.

Updated docs for refpix step

---

README.md

Update the README file to list the 0.10.0 release in the DMS build info table.

Update README to include 0.10.0 release info

---

jwst/assign_wcs/nirspec.py
jwst/assign_wcs/tests/test_nirspec.py

fix get_open_slits

---

README.md

Adds instructions on how to set up CRDS outside the STScI network.

Update Readme with CRDS configuration

---

jwst/fits_generator/create_data.py
jwst/fits_generator/main.py
jwst/fits_generator/tests/dotfile/._05181.prop
jwst/fits_generator/tests/okfile/05181.prop
jwst/fits_generator/tests/test_fitsgen.py

Fitsgen dotfiles

---

jwst/combine_1d/__init__.py
jwst/combine_1d/combine1d.py
jwst/combine_1d/combine_1d_step.py
jwst/combine_1d/temp_wcs.py
jwst/extract_1d/__init__.py
jwst/extract_1d/extract1d.py
jwst/flatfield/__init__.py
jwst/flatfield/flat_field.py
jwst/flatfield/flat_field_step.py
jwst/ipc/__init__.py
jwst/persistence/__init__.py
jwst/persistence/persistence.py
jwst/persistence/persistence_step.py

This fixes PEP8 problems with the following steps:  `combine_1d`, `extract_1d`, `flat_field`, `ipc`, and `persistence`.

PEP8 changes

---

jwst/model_blender/blendmeta.py
jwst/model_blender/tests/test_blend.py

Minor cleanup of model_blender step to meet PEP8 standards outlined in #2329 in support of #2340.

Fix PEP8 issues in model_blender

---

jwst/rscd/rscd_sub.py

Small pep8 change for rscd step

pep8 change

---

jwst/fringe/__init__.py
jwst/fringe/fringe.py
jwst/fringe/fringe_step.py

This PR:
* Removes version from fringe steps (#2352)
* PEP8 fixes fringe steps (part of #2340)

fixes flake8 problems in fringe step

---

docs/jwst/cube_build/reference.rst

Updated the information about the cube parameter reference files

Update Reference file description

---

CHANGES.rst
jwst/barshadow/bar_shadow.py

Barshadow nan fix

---

jwst/gain_scale/__init__.py
jwst/group_scale/__init__.py
jwst/group_scale/group_scale_step.py
jwst/guider_cds/__init__.py
jwst/imprint/__init__.py
jwst/jump/__init__.py
jwst/jump/jump_step.py
jwst/jump/tests/test_twopoint_difference.py
jwst/jump/twopoint_difference.py
jwst/jump/yintercept.py
jwst/linearity/__init__.py
jwst/linearity/linearity.py
jwst/linearity/linearity_func.py
jwst/photom/__init__.py
jwst/photom/photom.py
jwst/saturation/__init__.py
jwst/srctype/__init__.py
jwst/srctype/srctype.py
jwst/srctype/srctype_step.py
jwst/superbias/__init__.py
jwst/superbias/bias_sub.py
jwst/white_light/__init__.py
jwst/white_light/white_light.py

PEP8 fixes and version removal for gain_scale, group_scale, guider_cds, imprint, jump, and linearity steps. More to come.
See #2340.

Pep8 and version fixes

---

jwst/cube_build/__init__.py
jwst/cube_build/blot_cube_build.py
jwst/cube_build/coord.py
jwst/cube_build/cube_build.py
jwst/cube_build/cube_build_io_util.py
jwst/cube_build/cube_build_step.py
jwst/cube_build/cube_build_wcs_util.py
jwst/cube_build/cube_cloud.py
jwst/cube_build/cube_overlap.py
jwst/cube_build/data_types.py
jwst/cube_build/file_table.py
jwst/cube_build/ifu_cube.py
jwst/cube_build/instrument_defaults.py
jwst/cube_build/spaxel.py

The increase_speed pr got too confusing for me with conflicts and travis failures.
I decided to go back to master and take the cube_build code and just do the pep8 changes.
I did not do many of the speed enhancements in the last PR anyway. Nadia pointing me a  direction
where I think I can make larger improvements. I am going to start fresh with a cleaned up
version of the code and try her suggestions

Pep8 cubebuild

---

jwst/cube_build/cube_build_step.py
jwst/cube_build/cube_cloud.py

Fixed an incorrect log.info statement 
The determination of x,y for NIRSPEC data was incorrectly commented out in the last pr. Fixed t.

Final ifu cube error

---

docs/jwst/introduction.rst
docs/jwst/reference-file-formats-documentation.rst

I am trying to add some missing documentation that was part of the jwst-reffiles.stsci.edu document but was not transferred here. More additions will come later.

First updates to the reference files documentation

---

jwst/firstframe/tests/test_firstframe.py

Added 2 tests, swapped x and y and updated for PEP 8.

Updated test for firstframe step.

---

jwst/datamodels/schemas/core.schema.yaml
jwst/datamodels/schemas/keyword_coronmsk.schema.yaml
jwst/datamodels/schemas/keyword_exptype.schema.yaml
jwst/datamodels/schemas/keyword_grating.schema.yaml
jwst/datamodels/schemas/wcsinfo.schema.yaml

Keyword definition updates

---

jwst/lastframe/tests/test_lastframe.py

Created new directory and added lastframe unit tests.

Added lastframe unit tests

---

JenkinsfileRT

The old JenkinsfileRT had drifted out of date.

Update RT config to take advantage of conda machinery in Jenkins

---

jwst/pipeline/__init__.py
jwst/pipeline/calwebb_ami3.py
jwst/pipeline/calwebb_coron3.py
jwst/pipeline/calwebb_dark.py
jwst/pipeline/calwebb_detector1.py
jwst/pipeline/calwebb_guider.py
jwst/pipeline/calwebb_image2.py
jwst/pipeline/calwebb_image3.py
jwst/pipeline/calwebb_spec2.py
jwst/pipeline/calwebb_spec3.py
jwst/pipeline/calwebb_tso3.py
jwst/pipeline/linear_pipeline.py
jwst/pipeline/tests/helpers.py
jwst/pipeline/tests/test_calwebb_image2.py
jwst/pipeline/tests/test_calwebb_spec2.py
jwst/pipeline/tests/test_calwebb_spec2_nrs_msa.py
jwst/pipeline/tests/test_calwebb_spec3_mir_lrs_fixedslit.py
jwst/pipeline/tests/test_calwebb_spec3_mir_mrs.py
jwst/pipeline/tests/test_calwebb_spec3_mir_mrs_dither.py
jwst/pipeline/tests/test_calwebb_spec3_nrs_msa.py
jwst/pipeline/tests/test_nis_ami3.py
jwst/pipeline/tests/test_nis_soss_tso3.py
jwst/pipeline/tests/test_nrc_coron3.py
jwst/pipeline/tests/test_nrc_detector1.py
jwst/pipeline/tests/test_nrc_image3.py
jwst/pipeline/tests/test_nrc_tso3.py
jwst/pipeline/tests/test_nrs_spec2_bright_obj.py
jwst/pipeline/tests/test_nrs_tso3.py
jwst/pipeline/tests/test_wfs_combine.py

Applied all necessary changes to make flake8 happy and removed all instances of `__version__`.

PEP8 fixes for pipeline package

---

docs/jwst/introduction.rst
jwst/assign_wcs/nirspec.py
jwst/assign_wcs/util.py
jwst/associations/tests/test_main.py
jwst/pipeline/calwebb_spec2.py
jwst/tests_nightly/general/nirspec/test_spec2.py
scripts/strun

Return special exit status when an exposure has no science in it.

---

CHANGES.rst
jwst/associations/__init__.py
jwst/associations/tests/test_version.py
jwst/datamodels/make_header.py

Set association code version to the jwst package version

---

CHANGES.rst
jwst/stpipe/step.py
jwst/stpipe/tests/test_input.py

Allow not being able to find a default input file name

---

jwst/pipeline/calwebb_spec2.py

Fixes bug introduced in #2456.

Turn off resample of CubeModel in Spec2Pipeline

---

CHANGES.rst

Inclusion of pull requests and updates to the change log in preparation for 0.11.0.

update CHANGES.rst for 0.11.0

---

CHANGES.rst
jwst/assign_wcs/nirspec.py

make sure the Nirspec WCS bounding_box includes the edges

---

CHANGES.rst
jwst/associations/lib/rules_level2_base.py
jwst/associations/lib/rules_level3_base.py
jwst/datamodels/container.py
jwst/jump/jump_step.py
jwst/lib/set_telescope_pointing.py
jwst/pipeline/calwebb_image2.py
jwst/pipeline/calwebb_spec2.py
jwst/pipeline/calwebb_spec3.py
jwst/ramp_fitting/gls_fit.py
jwst/stpipe/tests/test_logger.py
jwst/timeconversion/__init__.py

Change log.warn to log.warning

---

CHANGES.rst
jwst/lib/set_telescope_pointing.py
scripts/set_telescope_pointing.py

Fix logging configuration to be DEBUG verbose

---

jwst/tests_nightly/general/pipelines/test_nirspec_fs_spec3.py

The data for this test is now available.
Resolves #2478.

Un-xfail tests_nightly/general/pipelines/test_nirspec_fs_spec3.py

---

CHANGES.rst

Adding the major changes from 0.10.0 for completeness to the change log for changes since Build 7.1.3 for Build 7.2

adding the changes from version 0.10.0

---

jwst/mrs_imatch/__init__.py
jwst/mrs_imatch/mrs_imatch_step.py

mrs_imatch: flake8 fixes

---

jwst/extract_2d/nirspec.py

All the NIRSpec MSA and FS regression tests were failing because of this bug.
Resolves #2517.

Fix extract_2d cutout size bug

---

jwst/dq_init/dq_init_step.py

Add ValueError check when opening RampModel in dq_init

---

jwst/datamodels/schemas/core.schema.yaml

(datamodel.meta.instrument.band) enumeration list
Fixes #2398

Added short/medium/long combinations to BAND

---

CHANGES.rst
jwst/assign_wcs/nircam.py
jwst/assign_wcs/niriss.py
jwst/assign_wcs/util.py

* in `assign_wcs.util.get_object_info` QTable input wasn't being forwarded

Fix minor bugs found in testing

---

CHANGES.rst
docs/jwst/pathloss/description.rst
docs/jwst/pathloss/reference_files.rst
jwst/datamodels/schemas/image.schema.yaml
jwst/pathloss/path_loss.py
jwst/pathloss/pathloss_step.py
jwst/pipeline/calwebb_spec2.py

Added pathloss correction for NIRISS_SOSS data

Pathloss niriss

---

jwst/tests_nightly/general/pipelines/test_nrs_fs_brightobj_spec2.py

Use renamed tso-spec2 config file in regression test

---

jwst/stpipe/crds_client.py

This is part of dropping Python-2 support and associated cleanup.

Removed python23 dependency in stpipe/crds_client.py

---

jwst/datamodels/properties.py
jwst/datamodels/storage.py
jwst/fits_generator/input_file_types.py
jwst/fits_generator/objects.py
jwst/fits_generator/pyparsing.py
jwst/lib/signal_slot.py
jwst/refpix/reference_pixels.py

Remove inheritance from object

---

jwst/tweakreg/wcsimage.py

This PR addresses two minor issues:
1. Cleans up the code from the https://github.com/spacetelescope/jwst/pull/2590 fix
2. Defines the frame for the V2V3 correction transformation using the same frame as used in the `WCS` pipeline for the `'v2v3'` transformation (but renames it). This way the pipeline will use frame objects instead of string names and "re-using" `'v2v3'` frame will preserve the same frame type as it used to be in the original (uncorrected/not "tweaked") WCS pipeline.

Use frames instead of str in GWCS pipeline and code reformat WCS validation code

---

CHANGES.rst

First round of updates to get the CHANGELOG ready for the 0.12.0 release.

Update CHANGELOG for 0.12.0 release

---

docs/jwst/refpix/description.rst

Specify method used to calculate clipped mean (scipy.stats.sigmaclip) in refpix step
