spacetelescope/jwst

README.md
Closes #6409
Resolves [JP-2307](https://jira.stsci.edu/browse/JP-2307)
This PR reverts #6411, as all dependencies now support python 3.10.0.
(Revert button didn't work, something about changes to files since that PR was merged)
Checklist
=> Revert JP-2307: Remove explicit versioning of python, 3.10.0 now supported

jwst/stpipe/tests/test_step.py
Closes #4115 
Resolves [JP-1043](https://jira.stsci.edu/browse/JP-1043)
This PR removes the forced XFAIL on a test, which now attempts a CRDS retrieval for a step config given a (now updated) miri data file. 
Checklist
=> JP-1043: Add CRDS retrieval test for get_config_from_reference

CHANGES.rst, docs/jwst/barshadow/arguments.rst, docs/jwst/flatfield/arguments.rst, docs/jwst/pathloss/arguments.rst, docs/jwst/pathloss/description.rst, docs/jwst/photom/arguments.rst, docs/jwst/pipeline/calwebb_spec2.rst, docs/jwst/references_general/pathloss_reffile.inc, docs/jwst/references_general/pathloss_selection.inc, jwst/datamodels/__init__.py, jwst/datamodels/pathloss.py, jwst/datamodels/schemas/image.schema.yaml, jwst/datamodels/schemas/mirlrs_pathloss.schema.yaml, jwst/pathloss/pathloss.py, jwst/pathloss/pathloss_step.py, jwst/photom/photom.py, jwst/pipeline/calwebb_spec2.py, jwst/regtest/test_miri_lrs_slit_spec2.py
Closes #6277
Resolves [JP-2243](https://jira.stsci.edu/browse/JP-2243)
This PR implements a pathloss correction for MIRI LRS fixed-slit exposures. It builds on the existing pathloss routines for NIRSpec slit-like modes. A new datamodel, `MirLrsPathlossModel`, is also implemented, because the form of the reference file data is different than those for NIRSpec or NIRISS SOSS (tabular instead of image-based). The `calwebb_spec2` pipeline is also updated to enable the pathloss step for LRS fixed-slit mode.
Note that a number of minor cosmetic changes have also been made to some of the existing pathloss functions for other modes, to clean up old errors in text and comments.
Checklist
=> JP-2243: Implement MIRI LRS pathloss correction

docs/jwst/introduction.rst, docs/jwst/stpipe/call_via_call.rst, docs/jwst/stpipe/user_logging.rst, docs/jwst/stpipe/user_step.rst
Closes #3217 
Resolves [JP-579](https://jira.stsci.edu/browse/JP-579)
This PR adds documentation for the stpipe change that adds the keyword `logcfg` to Step and Pipeline .call().
NOTE: This shouldn't be merged until stpipe pushes a new release including [stpipe PR #32](https://github.com/spacetelescope/stpipe/pull/32) (if I understand how updates to stpipe trickle down to user installs?)
Checklist
=> JP-579: Include logcfg keyword in docs where appropriate

CHANGES.rst, jwst/dark_current/dark_current_step.py, jwst/regtest/test_nircam_image.py
Closes #6402 
Resolves [JP-2304](https://jira.stsci.edu/browse/JP-2304)
This PR changes the arguments provided to the DarkCurrentStep's make_output_path, such that the step parameter `dark_output` will now provide the frame-averaged darks in the filename specified, as per the documentation.
Aside: is anyone utilizing this output? With this sitting broken for so long, does this mean there are no tests verifying the contents of this file? 😨 
Checklist
=> JP-2304: Fix arguments to DarkCurrentStep's make_output_path

CHANGES.rst, jwst/assign_wcs/nirspec.py, jwst/assign_wcs/tests/test_nirspec.py, jwst/barshadow/bar_shadow.py
Closes #6365
Resolves [JP-2291](https://jira.stsci.edu/browse/JP-2291)
This PR fixes a bug in the barshadow step that was leading to the correction array being calculated incorrectly for slitlets in which the source is indicated as being off-center (in the spatial direction) in the slitlet. The bar-shadow correction only applies to extended/uniform sources in the first place, which are assumed to fill the slitlet (or at best the distribution is not known), hence the correction should not depend at all on any information from the MSA meta data that indicates which shutter within the slitlet contains the center of the source. It should be completely independent of source location in the slitlet. The fix removes all effects on the calculation of the correction that were due …
=> JP-2291: Fix bug in barshadow for off-center sources

CHANGES.rst, jwst/skymatch/region.py
Closes #5304
Closes #6439
Resolves [JP-1670](https://jira.stsci.edu/browse/JP-1670)
Fixes issues in `skymatch` reported in #5304 and #6439 which are due to old `region.py` file used in the pipeline compared to the one in `stsci.skypac` which includes improvement and bug fixes that address the crashes reported in the above mentioned issues.
Bug fixes applied in `stsci.skypac` that are being ported to `jwst.skymatch.region` are:
- https://github.com/spacetelescope/stsci.skypac/pull/55
- https://github.com/spacetelescope/stsci.skypac/pull/52
Checklist
=> Update region.py in skymatch

CHANGES.rst, jwst/assign_wcs/assign_wcs_step.py
Resolves [AL-607](https://jira.stsci.edu/browse/AL-607)
This PR fixes a bug in `assign_wcs` due to which WCS elements (`CD` matrix, `CDELT`, ...) are removed _after_ header has been updated with the new header from `to_sip_fits()`. Instead this clean-up, if needed, should happen before header is updated.
Checklist
=> Fix incorrect removal of PC and CDELT info from FITS WCS

CHANGES.rst, jwst/barshadow/bar_shadow.py
Resolves [JP-2291](https://jira.stsci.edu/browse/JP-2291)
This PR adds a minor tweak to the `bar_shadow` updates implemented in PR #6454. In the original PR, small changes were made to the bar shadow correction array even for slits that contained a centered source, while the update was intended to fix only slits that have off-center sources. So this adds an extra hook to first check to see if the source position is at the center of the slitlet shutter list and, if it is, don't modify the original `yslit` data. This has the benefit of keeping regressions to a minimum and also keeps us in sync with the NIRSpec team results for slitlets that have a centered source (otherwise there is a small difference).
Checklist
=> JP-2291: minor tweak to barshadow update

JenkinsfileRT, setup.cfg
Resolves [JP-2329](https://jira.stsci.edu/browse/JP-2329)
This PR addresses adds `pysiaf` to the SDP dependencies.
Also, the list of SDP dependencies is now `sdp`, instead of just `ephem`.
Checklist
=> JP-2329 Add pysiaf to SDP dependency

CHANGES.rst, jwst/flatfield/flat_field.py
Closes #6461
Resolves [JP-2332](https://jira.stsci.edu/browse/JP-2332)
This PR adds an extra check on NRS_LAMP exposures that route lamp_mode=IMAGE to the imaging portion of FlatFieldStep, where an additional check was needed such that if no flat is given or provided, the step will be skipped.
Checklist
=> JP-2332: Ensure NRS_LAMP imaging data properly skips flatfielding

CHANGES.rst, jwst/wfs_combine/wfs_combine_step.py
Closes #6463 
Resolves [JP-2333](https://jira.stsci.edu/browse/JP-2333)
This PR changes the wfs_combine step (pipeline?) to use the Step.load_as_level3_asn() method rather than datamodels.load() for ingesting the association - this allows for operations on the contents of the association file without requiring all listed files in the association to be present.
Checklist
=> JP-2333: Load level3 ASN using method rather than force-load with datamodels

CHANGES.rst, jwst/datamodels/schemas/guider_cal.schema.yaml, jwst/datamodels/schemas/guider_raw.schema.yaml
Closes #3801 
Resolves [JP-857](https://jira.stsci.edu/browse/JP-857)
This PR corrects the ordering of columns in the planned reference stars table inside guider_cal and guider_raw schemas to match the order used by SDP, to hopefully clear up some errors found in the nightly SDP Auto run.
Will need to upload new artifacts to fix regtest data with new order after merge.
Checklist
=> JP-857: Reorder columns in guider schemas to match SDP structure

CHANGES.rst, jwst/transforms/models.py, jwst/wavecorr/tests/test_wavecorr.py, jwst/wavecorr/wavecorr.py
Closes #6074
Resolves [JP-2103](https://jira.stsci.edu/browse/JP-2103)
Closes #6287
Resolves [JP-2253](https://jira.stsci.edu/browse/JP-2253)
This PR corrects the computation of the position of the source in the NRS fixed slit.
It also removes `vparity` from the transform from Ideal to V2V3 which was found to be incorrect.
The method `absolute2fractional` was removed because the returned `source_xpos` position is essentially
the fractional position.
Checklist
=> JP-2103: Fix calculation of source_xpos in wavecorr

CHANGES.rst, jwst/lib/set_telescope_pointing.py
Resolves [JP-2339](https://jira.stsci.edu/browse/JP-2339)
This PR moves the use of the default method to the function that actually needs to use a method: calc_transforms
This should address an incompatibility introduced in a previous PR.
Checklist
=> JP-2339 Move setting of the default method to `calc_transforms`

CHANGES.rst, jwst/residual_fringe/residual_fringe.py
This PR fixes a bug in the residual fringe code; one instance of ResidualFringeModel was missed previously when the change was made to use FringeFreqModel.
Without this change, the pipeline returns 
AttributeError: module 'jwst.datamodels' has no attribute 'ResidualFringeModel'
With this change, the residual fringe step runs ok.
=> Fix residual fringe data model name

jwst/wavecorr/tests/test_wavecorr.py
This PR fixes the tests in the wavecorr package, failing because new reference files were delivered.
The order of `wavelength` and `source_xpos` in the reference files was swapped (row vs column), which changed the values in the test results. 
Checklist
=> fix test failure due to change in reference files

CHANGES.rst, jwst/datamodels/schemas/core.schema.yaml
Closes #6498 
Resolves [JP-2347](https://jira.stsci.edu/browse/JP-2347)
This PR fixes the names of several keywords related to the new NIRISS SOSS extract_1d operation. The old names were longer than 8 characters and hence illegal.
Checklist
=> JP-2347: Fix names of SOSS extraction keywords

jwst/regtest/test_nirspec_lamp_fs_spec2.py, jwst/regtest/test_nirspec_lamp_ifu_spec2.py
This PR makes a temporary change to 2 NIRSpec lamp exposure regression tests, to avoid a failure caused by recent updates to CRDS ref files. The NIRSpec team recently submitted new pars-spec2pipeline ref files that enable the extract_1d step for lamp exposures, but skip the aperture correction. The CRDS bestref that runs at the beginning of pipeline instantiation doesn't know apcorr is going to be skipped and hence tries to find an appropriate APCORR ref file and fails (there aren't any for lamp modes). This will be fixed, but not for a while yet. So in the meantime I've modified the 2 failing regtests to skip the extract_1d step for lamp exposures. This can be reactivated once CRDS updates are in place (post-B7.9?).
Checklist
=> Temp fix for failing NRS lamp regtests

setup.cfg
This PR restricts sphinx-automodapi to < 0.14.0 to avoid https://github.com/astropy/sphinx-automodapi/issues/141 which is causing the jwst doc build to fail.
Checklist
=> Try restricting sphinx-automodapi

CHANGES.rst, jwst/linearity/tests/test_linearity.py
This PR is to support JP-2311  and STCAL PR [#65](https://github.com/spacetelescope/stcal/pull/65)
The linearity step on STCAL was updated to deal with the case where all the linearity coefficients =0. It has been assumed that  this is a mistake in the reference file. If the linearity term of the linearity correction is zero then the resulting data will be zero. PR 65 on STCAL checks if the linear term is zero and if it is it sets the value to 1 and sets the DQflag in the linearity model to "NO_LIN_CORR'.  These pixels will have no linearity correction applied to them and their DQFlag will include NO_LIN_CORR. 
One of the CI tests is to run the unit test for the linearity step in the JWST Pipeline.
This PR fixes cases where the test did not set the linear term to a value. …
=> Update linearity test  in jwst pipeline caused by changes in  STCAL PR 65 

docs/jwst/model_blender/blender_rules.rst, jwst/model_blender/blendrules.py, setup.cfg
Reverts spacetelescope/jwst#6520
Instead of pinning automodapi, just don't try to import everything.
Because I am lazy, I am using GitHub interface. I will fix the `__all__` in subsequent commit.
=> DOC: Blender rules need __all__

CHANGES.rst, docs/jwst/dark_current/description.rst, docs/jwst/resample/arguments.rst
Closes #6523 
Closes #6526 
Resolves [JP-2364](https://jira.stsci.edu/browse/JP-2364)
Resolves [JP-2366](https://jira.stsci.edu/browse/JP-2366)
This PR updates the docs for dark_current step, to add information regarding the unique way MIRI dark data are subtracted (per integration), and the resample step, to indicate that the default value for weighting is now "ivm".
Checklist
=> Updates to resample and dark_current docs

docs/conf.py, docs/jwst/datamodels/new_model.rst, setup.cfg
Remove `distutils` because it is deprecated. Using `packaging` for version check.
I did not see anything affected by astropy/astropy#12633 though it was my original intent.
=> MNT: Remove distutils

CHANGES.rst, docs/jwst/datamodels/models.rst
Closes #6380 
Resolves [JP-2298](https://jira.stsci.edu/browse/JP-2298)
This PR addresses outdated documentation that instructed users to call create_history_entry() from jwst.datamodels.util; it is now located in stdatamodels.util. Docs updated to reflect this. 
Checklist
=> JP-2298: Update docs to show create_history_entry() moved to stdatamodels

CHANGES.rst, jwst/resample/resample_spec.py
Closes #6479
Resolves [JP-2340](https://jira.stsci.edu/browse/JP-2340)
It seems that the original code intended to swap X<->Y axes when the X-slope was close to 0 (when determining the size of the output image and constructing output WCS) in the `ResampleSpecData.build_interpolated_output_wcs()` function was buggy and did not create correct mapping for the inverse transformation and did not use the Y-slope to estimate image size (when axis swap was needed).
Checklist
=> JP-2340: Fix incorrect output WCS and image size in ResampleSpecData

CHANGES.rst, jwst/datamodels/schemas/psfmask.schema.yaml
Closes #6511 
Resolves [JP-2352](https://jira.stsci.edu/browse/JP-2352)
Adds EXP_TYPE to PsfMaskModel schema (JP-2352). This is a required matching keyword for CRDS.
This PR addresses JP-2352
Checklist
=> JP-2352: Add EXP_TYPE to PsfMaskModel schema

CHANGES.rst, jwst/assign_wcs/niriss.py
Resolves [JP-2153](https://jira.stsci.edu/browse/JP-2153)
This uses the new astropy compound bounding box in order to enable usage of spectral order as a direct input to the wcs in NIRIS SOSS mode.
Note this PR requires the changes from #6205 (so that it passes with the recent changes to gwcs) and spacetelescope/gwcs#375 (to enable the use of compound bounding boxes in gwcs).
Checklist
=> JP-2153: Enable spectral order as input to WCS in NIRIS SOSS mode.

CHANGES.rst, jwst/associations/lib/rules_level3.py, jwst/regtest/test_associations_sdp_pools.py
Closes #6538
Resolves [JP-2371](https://jira.stsci.edu/browse/JP-2371)
Do not add MIR_FLATMRS exposures to the Level 3 associations for MIRI MRS observations.
Checklist
=> JP-2371 Remove MIR_FLATMRS from Asn_Lv3MIRMRS rule

jwst/jump/tests/test_detect_jumps.py
temporarily commenting out a test in jump detection that will fail before PR #72 in stcal is merged.
I'll open up a PR that reinstates this test (which passes when i run it) with some modifications once the stcal PR is merged.
=> temporarily remove a test in jump detection

CHANGES.rst, jwst/extract_1d/extract_1d_step.py
Related to [JP-1550](https://jira.stsci.edu/browse/JP-1550) and #5091 
This PR turns off the ATOCA SOSS extraction algorithm by default, as more testing with the photom step turned off will be required before we can verify reasonable results. The algorithm can be activated using a temporary extract_1d step parameter soss_atoca, which defaults to False and triggers box extraction. Additionally, this removes the source_type attribute from the ATOCA output to prevent creation of an extraneous SCI extension in the x1dints output.
Checklist
=> JP-1550: Turn off ATOCA by default

CHANGES.rst, jwst/jump/tests/test_detect_jumps.py
Fixes unit test `test_nirspec_saturated_pix` for jump detection to account for changes in https://github.com/spacetelescope/stcal/pull/72
In this test, a test dataset is constructed and four pixels ((1, 1), (2, 2), (3, 3), 4,4)) are given test scenarios to see if flagging for saturated pixels is done correctly. 
The tests for pixels (1, 1) and (3, 3) did not have different results - while the internal calculations changed based on changes to the code, the resulting pixels flagged as jumps ended up being the same.
for the test case of pixel (2, 2), 5 of the 7 groups in the test data are set to be saturated, meaning there is only one non saturated diff so no jumps should be flagged. previously, it was incorrectly flagging the 3rd group as a jump when NO groups should have been flagged, so …
=> Fix jump tests

JenkinsfileRT
SPB-778 Added a failure threshold so that failed regressions do not trigger an update during the build process
Resolves [SPB-778](https://jira.stsci.edu/browse/SPB-778)
This PR fixes the creation of python dependency files by jwst regression test runs, so that the dependency files are only created and uploaded to artifactory when there were no failures in the regression test run. Right now they're being created for every run.
Checklist
=> SPB-778 Bugfix: JWST dependency uploads occuring with failed regressions

CHANGES.rst, jwst/cube_build/cube_build_step.py, jwst/outlier_detection/outlier_detection_ifu.py
Closes #6578 
Resolves [JP-2386](https://jira.stsci.edu/browse/JP-2386)
This PR adds the cross-band MRS options 'short-medium', 'short-long', 'medium-short', 'medium-long', 'long-short', 'long-medium' outlier_reject (outlier_rejection_ifu.py). Outlier rejection will call cube_build using these band to build a cube. The spec defining 'band' in cube_build also had to be updated to include these options. 
Checklist
=> JP-2386: Added MIRI-MRS cross band options to outlier detection

CHANGES.rst, docs/jwst/skymatch/README.rst, jwst/skymatch/skymatch_step.py
Closes #5923 
Resolves [JP-2024](https://jira.stsci.edu/browse/JP-2024)
This PR addresses background subtraction issues found in the resample step due to its interaction with the default skymatch step parameter skymethod being set to 'global+match'. This was found to have a simple solution of changing the default to 'match'.
Checklist
=> JP-2024: Update default value of skymatch's 'skymethod' step parameter

CHANGES.rst, jwst/associations/lib/rules_level2b.py
Closes #5655 
Resolves [JP-2495](https://jira.stsci.edu/browse/JP-2495)
This PR prohibits the creation of level 2b associations if `dms_note` is `wfsc_los_jitter` and `exptype` = `nrc_image`, rather than the first implementation that prohibited associations for  `exptype` = `nrc_tacq`.
Checklist
=> JP-2495: Change restriction on Level-2b association creation to nrc_image instead of nrc_tacq

jwst/associations/lib/rules_level2b.py
Closes #5655 
Resolves [JP-2495](https://jira.stsci.edu/browse/JP-2495)
This PR moves the added, then edited, constraint that excludes NRC_IMAGE + "DMS_NOTE":"WFSC_LOS_JITTER" pool members from generating a 2b association. The initial constraint was being applied to members with exp_type NRC_TACQ, which if not constrained would generate a Lv2ImageNonScience asn. The change to exp_type changed which asn to constrain - now Lv2WFSC.
Checklist
=> JP-2495: Move jitter exclusion constraint from Lv2ImageNonScience to Lv2WFSC

CHANGES.rst, jwst/associations/lib/rules_level2_base.py, jwst/associations/lib/rules_level3_base.py, jwst/associations/tests/test_level3_basics.py
Closes #6680 
Resolves [JP-2494](https://jira.stsci.edu/browse/JP-2494)
This PR adds the file extension to the `asn_pool` entry in associations during their creation. I tested this with asn_generate locally, but I don't know that I've covered all cases.
Checklist
=> JP-2494: Change association 'asn_pool' to include file extension

CHANGES.rst, jwst/associations/lib/dms_base.py
Closes #6686 
Resolves [JP-2497](https://jira.stsci.edu/browse/JP-2497)
This PR adds the NRS_LAMP equivalent valid optical paths to validate associations using the combination of grating, lamp, and detector.
Checklist
=> JP-2497: Create valid lamp paths with lamp<->filter equivalency

CHANGES.rst, docs/jwst/ramp_fitting/description.rst
Closes #6308 
Resolves [JP-2266](https://jira.stsci.edu/browse/JP-2266)
This PR updates the last section of the ramp_fit docs to describe in better detail exactly what's stored in the various VAR_xxx and ERR extensions of each output product and link them to the detailed equations that show the variance calculations.
Checklist
=> JP-2266: Clarify ERR calculations in ramp_fit docs

docs/conf.py
This PR addresses the doc build failures due to a change in the location of the scipy and numpy intersphinx inventory files.
Checklist
=> Update scipy and numpy intersphinx inventory URLs

CHANGES.rst, jwst/cube_build/ifu_cube.py, jwst/cube_build/src/cube_dq_utils.c, jwst/cube_build/src/cube_match_sky_pointcloud.c
Closes #6694 
Resolves [JP-2502](https://jira.stsci.edu/browse/JP-2502)
This PR fixes a bug in how the DQ flag for NIRSpec IFU cubes are set. 
Checklist
=> JP-2502 NIRSpec Cube Build DQ flag bug fix

jwst/srctype/srctype.py, jwst/srctype/srctype_step.py, jwst/srctype/tests/test_srctype.py
Closes #6162
Resolves [JP-2155](https://jira.stsci.edu/browse/JP-2155)
This update allows the SRCTYPE to be overridden on the command line when processing exposures that contain a single pre-defined target, i.e. MIR_LRS-FIXEDSLIT, MIR_LRS-SLITLESS, MIR_MRS, NRC_TSGRISM, NRS_FIXEDSLIT, NRS_BRI
GHTOBJ, and NRS_IFU. Other EXP_TYPEs will be ignored. The change log and documentation will soon also be updated. This PR supersedes #6692 .
Checklist
=> Add ability to override source type in Source Type step (JP-2155)

CHANGES.rst, jwst/extract_1d/ifu.py
Closes #
Resolves https://jira.stsci.edu/browse/JP-2516
This PR fixes a bug in MRS Extract1D where the sigma_clipped_stats algorithm is applied to a wavelength range of the IFU data cube that can contain no valid data when run in spec2 mode.  sigma_clipped_stats has started reporting excessive warnings in this case, which now overflows thousands of pages of the pipeline log.  This PR now checks if the relevant array has non-zero size before computing statistics.
Checklist
=> JP-2516: Add catch for no data case in MRS Extract1D statistics

CHANGES.rst, jwst/cube_skymatch/cube_skymatch_step.py, jwst/skymatch/skymatch_step.py
Resolves [JP-2524](https://jira.stsci.edu/browse/JP-2524)
This PR enables mnemonic DQ codes to be passed via the 'dqbits' param of the skymatch step. It also resets the default value.
Checklist
=> JP-2524: Enable use of mnemonic DQ codes in skymatch "dqbits" param

jwst/lib/tests/engdb_mock.py, jwst/regtest/test_miri_setpointing.py, jwst/regtest/test_nircam_tsimg.py
Resolves an issue with regression tests and a recent change to `set_telescope_pointing` introduced in PR#6735
Checklist
=> Repair miri and nircam setpointing tests to use actual mock engineering database

jwst/jump/tests/test_detect_jumps.py
Closes #6563 
Resolves [JP-2381](https://jira.stsci.edu/browse/JP-2381)
Add jump step tests for future debugging. These test measure the jump step execution time for datasets having the dimensions of simulated MIRI datasets. Much longer execution times may be indicate bugs. The comparison times for these tests will be updated once they have been run during regular testing,
This PR addresses JP-2381
Checklist
=> Add jump tests for future debugging (JP-2381)

CHANGES.rst, jwst/extract_1d/extract.py
Closes #6723 
Resolves [JP-2514](https://jira.stsci.edu/browse/JP-2514)
This PR addresses spec2 failures when providing a _rateints input file with nints=1, i.e. the input data shape was (1, n, m). This was being collected along with 2D input data and leaving the integration number unused, while slightly separate behavior is required. Now the 3D data is sliced on the integration axis, providing a 2D data array to be extracted.
Checklist
=> JP-2514: Bug in extract_1d, processing 3D input data with dim1 of length 1.

CHANGES.rst, jwst/datamodels/schemas/keyword_nints.schema.yaml, jwst/datamodels/schemas/reset.schema.yaml, jwst/reset/reset_sub.py, jwst/reset/tests/test_reset_sub.py
Resolves [JP-2536](https://jira.stsci.edu/browse/JP-2536)
This PR updates the reset model to be in line with what CRDS is expecting. The reset model is an integration and group dependent correction. CRDS is expected the NINTS and NGROUPS keywords as part of the reset model. This was discovered as J Morrison was creating new reset reference files to be delivered to CRDS.
There are also updates to the reset step to use the NINTS and NGROUP instead of the shape of the data to determine how many integration and groups there are to be corrected. 
Checklist
=> JP-2536 Reset model updates 

docs/jwst/references_general/distortion_reffile.rst
This PR modifies the documentation page for distortion reference files. It adds PUPIL to the selection criteria for the NIRCam distortion reference file. This was previously missing in the list of selection criteria.
=> Add pupil to NIRCam distortion reffile selection criteria

CHANGES.rst, jwst/source_catalog/source_catalog.py
Resolves [JP-2526](https://jira.stsci.edu/browse/JP-2526)
This PR fixes the KDTree calculation to use only non-finite source positions to prevent memory issues on Linux systems. It also filters a RuntimeWarning for non-finite source positions.
Checklist
=> JP-2526: Fix kdtree memory issues on Linux systems

CHANGES.rst, jwst/source_catalog/source_catalog.py
This PR is a follow-on to #6765.  While investigating that issue, I found that the sharpness and roundness parameters are using the source peak position instead of its centroid.  This PR fixes that.  Sources that have non-finite centroid positions will have `np.nan` for these parameters.
Checklist
=> Fix sharpness and roundness to use source centroid instead of peak

jwst/outlier_detection/tests/test_outlier_detection.py, jwst/refpix/irs2_subtract_reference.py
`scipy` has deprecated the `scipy.ndimage.filters` namespace.  Instead `scipy.ndimage` should be used.  This namespace works for all `scipy` versions supported by this package.
Checklist
=> Fix scipy.ndimage.filters deprecation

CHANGES.rst, jwst/datamodels/tests/test_open.py, jwst/datamodels/util.py, jwst/lib/set_telescope_pointing.py, jwst/lib/tests/test_set_telescope_pointing.py, scripts/set_telescope_pointing.py
Resolves [JP-2530](https://jira.stsci.edu/browse/JP-2530)
PR#6735 allowed any datamodel to be modified, with warnings if an unexpected model was found. This had the unintended side effect in ground processing for failing on certain observatory products that were not intended to be used. This PR re-instates some of the restrictions, but allow the option of modifying anything.
Checklist
=> JP-2530 Further restrict default models that can be updated

CHANGES.rst, jwst/regtest/test_miri_residual_fringe.py
This PR is part of JP-2344 - the parent ticket of the residual fringe correction 
This PR adds a regression test for the residual fringe corrrection. Ground test data was converted to DMS format. The ground test data is a good example of data with fringes.  The input and truth files have been added to artifactory
Checklist
=> Residual fringe regression test

jwst/resample/tests/test_resample_step.py
Fixes failing `test_custom_wcs_resample_imaging` due to a bad test parameter. Changes in `astropy` master are less tolerant to bad parameters.
Checklist
=> Fix failing resample unit test

CHANGES.rst, jwst/datamodels/schemas/rscd.schema.yaml
Resolves [JP-2555](https://jira.stsci.edu/browse/JP-2555)
This PR updates the RSCD schema  to increase the size of the rscd_group_skip_table. The readpatt column size needs to be increased to allow values of FASTR1, SLOWR1, or FASTR100. A new set of RSCD reference files include values for the number of groups to skip for the baseline RSCD correction for a readpatt of FASTR1, SLOWR1, and FASTR100.  The flight data will have a readpatt of either FASTR1 or SLOWR1.
Checklist
=> JP-2555 update rscd model to take FASTR1, SLOWR1

CHANGES.rst, jwst/resample/resample_spec.py
Resolves [JP-2027](https://jira.stsci.edu/browse/JP-2027)
This PR fixes the horizontal displacement of resampled spectra for MIRI-LRS. 
This is not a complete re-design of the `build_interpolated_output_wcs()` function but just a patch to fix horizontal displacement.
Checklist
=> JP-2027: Fix horizontal centering of resampled MIRI-LRS spectra

CHANGES.rst, jwst/lib/set_telescope_pointing.py, scripts/set_telescope_pointing.py
Resolves [JP-2561](https://jira.stsci.edu/browse/JP-2561)
This PR adds the command-line option `--force-level1bmodel` for the situation where an input file
does not define the DATAMODL keyword and, instead of attempting to guess at the model type,
force the file to be opened as a `Level1bModel`.
Checklist
=> JP-2561 Add option --force-level1bmodel

CHANGES.rst, jwst/datamodels/schemas/slitmeta.schema.yaml, jwst/resample/resample_spec.py, jwst/resample/tests/test_resample_step.py
Closes #6032 #6324
Resolves [JP-2083](https://jira.stsci.edu/browse/JP-2083)
This PR significantly re-designs the algorithm for computing output WCS for `resample_spec` for NIRspec. It solves issues described in https://jira.stsci.edu/browse/JP-2083 with resampled spectra: unexplained shifts and features in the resampled spectra.
The fundamental idea is the same as in https://github.com/spacetelescope/jwst/pull/6324 but with enhanced algorithms and bug fixes.
CC: @hbushouse @nden @jmuzerolle 
Checklist
=> JP-2083: Re-design algorithm for NIRspec output WCS for resample step

CHANGES.rst, jwst/resample/resample_spec.py
Resolves [JP-2083](https://jira.stsci.edu/browse/JP-2083)
#6747 introduced a re-designed algorithm for computation of the output WCS for the ``resemple_spec`` step for ``NIRSpec`` data. Unfortunately, due to how target position is reported in the `model.meta`, the algorithm had issues with multi-slit observations. This PR fixes those issues and another bug in centering of the output spectrum.
Checklist
=> JP-2083: Fix issues with resampling multi-slit observations

CHANGES.rst, docs/jwst/pipeline/calwebb_spec2.rst, jwst/pipeline/calwebb_spec2.py, jwst/regtest/test_niriss_wfss.py
Closes #3860
Resolves [JP-898](https://jira.stsci.edu/browse/JP-898)
This PR updates the WFSS processing branch of the calwebb_spec2 pipeline to allow it save an optional intermediate product that is a version of the grism image converted to units of e-/sec. The image is saved immediately after the flat-field step, before extract_2d has been applied, so that it is the full grism image before any extractions of spectra have been done. The image data are converted to units of e-/sec by loading the gain reference file, computing the mean gain from the reference data, and multiplying the grism image by the mean gain. The units of the variance and error arrays are also converted. The resulting image is saved as new "esec" product type.
Creating and saving this image is optional …
=> JP-898: Update calwebb_spec2 to create WFSS e/sec product

CHANGES.rst, jwst/associations/generate.py, jwst/associations/lib/constraint.py, jwst/associations/pool.py
Resolves [JP-2565](https://jira.stsci.edu/browse/JP-2565)
A necessary operation during generation is the deep copying of rows from the `AssociationPool`. However, because `AssociationPool` is subclassed from`astropy.table.Table`, each row has a pointer back to the table it belongs to, each row deep copy would copy the whole table. This causes exponential memory use as the tables grow in length.
A new class, `PoolRow`, is implemented to return a stripped-down version of each row, without the extra baggage.
Checklist
=> JP-2565 Implement PoolRow to avoid deep copy of the AssociationPool table

CHANGES.rst, jwst/tweakreg/tests/test_tweakreg.py, jwst/tweakreg/tweakreg_step.py
This PR is basically a maintenance edition. Here I make method `fit_quality_is_good()` of the `tweakreg` step private (I do not think there is a reason for it to be public) and also I rename it to something that is better suited for what it tests. This function was first introduced in https://github.com/spacetelescope/jwst/pull/6252
@hbushouse Please let me know if you think I should officially deprecate this method instead of renaming it right away. IMO, it is highly unlikely anyone would have used it since it was introduced.
Checklist
=> Make fit_quality_is_good private and rename it

CHANGES.rst, jwst/reset/reset_sub.py
Resolves [JP-2564](https://jira.stsci.edu/browse/JP-2564)
This PR fixes the reset step to work with segmented data. The reset step is integration dependent. There is a correction for the first integration and then a correction for all other integrations. In the case of segmented data, the first integration in the file is not necessarily the first integration in the exposure. The integration number in the exposure needs to be use in the step rather than the assuming the first integration in the file is the first integration in the exposure. 
Checklist
=> JP-2564 Update Reset Step to work with segmented TSO data

setup.cfg
This PR pins the astropy min version to 5.0.4
Checklist
=> Pin astropy min version to 5.0.4

CHANGES.rst, docs/jwst/extract_1d/arguments.rst, jwst/extract_1d/extract_1d_step.py, jwst/extract_1d/soss_extract/soss_extract.py, jwst/photom/photom.py, jwst/photom/photom_step.py, jwst/photom/tests/test_photom.py, jwst/pipeline/calwebb_spec2.py, jwst/pipeline/calwebb_spec3.py, jwst/pipeline/calwebb_tso3.py
Closes #6710 
Resolves [JP-2511](https://jira.stsci.edu/browse/JP-2511)
This PR modifies the behavior of both calwebb_spec2 and photom, such that for NIS_SOSS exposures photom is run after extract_1d, on extracted 1D spectra. This PR also removes the spec flag put in to toggle ATOCA on and off, as the toggle doesn't affect the Spec2Pipeline reordering, which would cause incorrect output if used.
Note to SOSS IDT: Please check at your convenience for expected output behavior! @loicalbert @AntoineDarveau 
Checklist
=> JP-2511: Reorder spec2 for SOSS, alter photom behavior for SOSS input as 1D spectra

CHANGES.rst, jwst/flatfield/flat_field.py
Closes #6707
Resolves [JP-2510](https://jira.stsci.edu/browse/JP-2510)
Set DQ flags of pixels with at least 1 bad component (fflat, dflat, sflat)
to DO_NOT_USE and NO_FLAT_FIELD.  Also set flat value to 1.0 for those
pixels.
Checklist
=> JP-2510: Change DQ flags for NIRSpec flatfield where 1 or more component flats bad

CHANGES.rst, jwst/resample/resample_spec_step.py, jwst/resample/resample_step.py
Resolves [JP-2566](https://jira.stsci.edu/browse/JP-2566)
This PR makes changes to the resample and resample_spec steps to allow for proper use of user-supplied parameter values. In the case where there's no DRIZPARS parameter ref file from which to load parameter values (as is the case for NIRSpec), the old code was hardwiring parameters to default values, thus ignoring any user-supplied parameter values. The function `_set_spec_defaults` has been drastically modified to fix this situation. The current flow is to first initialize the values in `kwargs` from the default values specified in the step "spec". It then applies values retrieved from the active params, thus passing along any user-supplied param values for items like `pixfrac`, `fillval`, and `weight_type`. No …
=> JP-2566: Fix resample_spec parameter handling

jwst/datamodels/ramp.py
Closes #
Resolves [JP-2506](https://jira.stsci.edu/browse/JP-2506)
This PR addresses creating the ZEROFRAME array when desired in the RampModel.  A conditional has now been added to the `__init__` function to check if the model is being created with a tuple or the `self.meta.exposure.zero_frame` flag is set to `True`.
Checklist
=> JP-2506: Adding a conditional to the creation of the ZEROFRAME array.

CHANGES.rst, docs/jwst/pipeline/calwebb_dark.rst, jwst/pipeline/calwebb_dark.py
Resolves [JP-2577](https://jira.stsci.edu/browse/JP-2577)
This PR adds the reset step back into calwebb_dark for MIRI exposures.
Checklist
=> JP-2577: Add reset step back into calwebb_dark

CHANGES.rst, jwst/ami/ami_average_step.py, jwst/resample/resample_step.py
Closes #5197
Resolves [JP-1618](https://jira.stsci.edu/browse/JP-1618)
This PR allows a user to `strun jwst.ami.AmiAverageStep file1.fits file2.fits` - previously, this would cause an error due to formatting of the function input. This required a bit more input handling to preserve functionality in an interactive python session.
Checklist
=> JP-1618: Allow AmiAverageStep to be run on list in CLI 

CHANGES.rst, jwst/resample/resample_spec.py
Partially Resolves [JP-2582](https://jira.stsci.edu/browse/JP-2582)
Use 0-based indexing for axes.
Checklist
=> JP-2582: Use 0-indexed spectral axis number

CHANGES.rst, jwst/skymatch/skyimage.py
@stsci-hack reported - see [#65](https://github.com/spacetelescope/stsci.skypac/issues/65) - that in a small number of cases there still are some crashes due to accuracy loss in the spherical geometry package. The workaround to this loss of accuracy issue was to identify two polygons as being identical if their vertices are within a specific proximity to each other. @stsci-hack reports that increasing tolerance by 2x would solve the issue for those HST data sets for which current tolerance was too small.
In my estimates, for ACS/HRC detectors with 0.025'' pixel scale, increasing tolerance to 1e-8 would be an equivalent to a tolerance of about 0.08 pixels in input image pixels.
This is a port of https://github.com/spacetelescope/stsci.skypac/pull/66 to JWST
Checklist
=> Increase tolerance for considering two polygons to be identical

jwst/stpipe/core.py, jwst/white_light/white_light_step.py
Closes #4031
Resolves [JP-998](https://jira.stsci.edu/browse/JP-998)
The Step parameter output_ext has the following description:
Default type of output
The parameter only changes the extension of the output file, not necessarily the type.  Update the description to be more accurate.
Checklist
=> Description of output_ext attribute misleading ( JP-998 )

CHANGES.rst, docs/jwst/tweakreg/README.rst, jwst/tweakreg/tweakreg_step.py
Partially Resolves [JP-2569](https://jira.stsci.edu/browse/JP-2569)
This PR updates ``searchrad``, ``tolerance``, and ``separation`` parameters for the ``trweakreg`` step to, hopefully, be more balanced. Also ``separation`` should be larger than ``tolerance``.
Checklist
=> JP-2569: Made defaults for some tweakreg parameters more robust

jwst/regtest/test_nircam_wfss_spec2.py
Related to [JP-2570](https://jira.stsci.edu/browse/JP-2570)
Now that updated pars-spec2pipeline ref files are available in CRDS, the custom pars file can be removed from the calwebb_spec2 regression test for a NIRCam WFSS exposure.
Checklist
=> Update WFSS spec2 regression test

jwst/source_catalog/source_catalog_step.py, jwst/source_catalog/tests/test_source_catalog.py
In https://github.com/spacetelescope/jwst/pull/6813, I removed a `try/except` block to catch for missing APCORR or ABVEGAOFFSET reference data.  This PR reverts that.  It catches the error, issues a warning, a exits gracefully.
Checklist
=> Issue warning and exit gracefully if reference file data is missing

CHANGES.rst, setup.cfg
`scikit-image` is required by `photutils` to perform source deblending in the `source_catalog` step.  By default, `deblend=False`, but if a user or an instrument team turns it on (via parameter reference files) the step will raise an `ImportError` if `scikit-image` is not installed.  I thought this used to be in the required dependencies, but perhaps not.
Checklist
=> Add scikit-image to dependencies

CHANGES.rst, jwst/cube_build/ifu_cube.py
This PR fixes a failure of mrs_imatch to properly use the drizzle algorithm for Single type cubes as reported in comments to https://github.com/spacetelescope/jwst/pull/6820
Tests well on jw01024_o001
Checklist
=> JP-2590: Implement drizzle core wrapper for Single type cubes used by mrs_imatch

CHANGES.rst, jwst/assign_wcs/miri.py, jwst/assign_wcs/nircam.py, jwst/assign_wcs/niriss.py, jwst/assign_wcs/tests/test_wcs.py
Closes #
Resolves [JP-2597](https://jira.stsci.edu/browse/JP-2597)
This PR fixes a typo in parsing the `filteroffset` file for nircam and niriss which resulted in the WCS not using this file.
Checklist
=> JP-2597: Fix call to filteroffset in assign_wcs

docs/jwst/cube_build/arguments.rst
Resolves [JP-2588](https://jira.stsci.edu/browse/JP-2588)
This PR fixes a couple of minor typos in the `cube_build` arguments doc.
Checklist
=> JP-2588: Fix typos in cube_build docs

CHANGES.rst, jwst/extract_1d/soss_extract/soss_centroids.py
Closes #
Addresses [JP-2603](https://jira.stsci.edu/browse/JP-2603)
This PR addresses an issue found when attempting to process SOSS data without any discernible source and/or bad pixel values - a divide by zero was causing issues.
Checklist
=> JP-2603: Replace infinite values with NaNs to complete SOSS processing

CHANGES.rst, jwst/datamodels/schemas/filteroffset.schema.yaml
This PR adds entries for the FILTER and PUPIL keywords to the datamodels schema for the FILTEROFFSET reference file. Those keywords are selectors for NIRISS filteroffset ref files.
Checklist
=> Add pupil and filter to filteroffset schema to support niriss

CHANGES.rst, docs/jwst/tweakreg/README.rst, jwst/tweakreg/tweakreg_step.py
Resolves [JP-2562](https://jira.stsci.edu/browse/JP-2562)
Resolves [JP-2569](https://jira.stsci.edu/browse/JP-2569)
At the CalWG meeting it was requested that the default value for ``fitgeometry`` be changed from its current value of `'general'` to `'rshift'`.
I want to note here that the 'general' setting is required for solving exact mathematical equations needed to solve for mis-alignments containing caused by just shifts and/or rotations. However, CalWG believes that keeping the number of degrees of freedom low is more important for the type of alignment that will be encountered in the pipeline. 
Checklist
=> JP-2569: Change fitgeom default value from general to rshift

CHANGES.rst, jwst/extract_1d/extract_1d_step.py, jwst/extract_1d/soss_extract/soss_extract.py, jwst/pipeline/calwebb_spec2.py
Closes #
Addresses [JP-2603](https://jira.stsci.edu/browse/JP-2603)
This PR addresses two more bugs found in SOSS testing - one which ends processing prematurely for F277W data, and one which was caused by noise in a SUBSTRIP96 subarray configuration.
Checklist
=> JP-2603: Exit SOSS Extract_1D gracefully for F277W data, avoid SUBSTRIP96 bug

CHANGES.rst, jwst/dark_current/dark_current_step.py
Resolves [JP-2596](https://jira.stsci.edu/browse/JP-2596)
This PR removes the copy operation from input to output models in the event the lower-level dark subtraction routines end up skipping processing. A copy is already being made in the lower-level routines, so this eliminates yet another (unnecessary) copy of the whole input data model, thus saving memory.
Checklist
=> JP-2596: Eliminate duplicate copies in dark step

CHANGES.rst, jwst/lib/tests/test_siafdb.py
This PR updates the expected results for one of the SIAF unit tests, due to changes in the SIAF DB that were included in a recent release of the pysiaf package (see https://github.com/spacetelescope/pysiaf/pull/236).
Checklist
=> Update SIAF unit test for recent pysiaf release

CHANGES.rst, jwst/datamodels/schemas/filteroffset.schema.yaml
Reverts spacetelescope/jwst#6839
`pupil` and `filter` are not selectors for NIRISS after all.
=> Revert "Add pupil and filter to filteroffset schema to support niriss"

CHANGES.rst, jwst/linearity/linearity.py
Resolves [JP-2613](https://jira.stsci.edu/browse/JP-2613)
The `ZEROFRAME` array is all zeros after the linearity step.  This is caused by an error in calling the `linearity_correction` function in STCAL.  The `zframe` parameter is defaulted to `None`.  The default value was being passed, instead of the `ZEROFRAME` array when present.
Checklist
=> JP-2613: ZEROFRAME is all zeros after the linearity step

CHANGES.rst, jwst/ramp_fitting/ramp_fit_step.py, jwst/ramp_fitting/tests/test_ramp_fit_step.py
Resolves [JP-2614](https://jira.stsci.edu/browse/JP-2614)
This PR modifies the top-level ramp_fit_step module to remove the code that had been put in place about a year ago that only copies over the INT_TIMES table content if the exposure is TSO mode. It doesn't hurt to have this info in the rateints products for all exposures.
Checklist
=> JP-2614: Fix ramp_fit to copy int_times content

CHANGES.rst, jwst/extract_1d/soss_extract/soss_centroids.py, jwst/extract_1d/soss_extract/soss_extract.py
Closes #
Resolves [JP-2603](https://jira.stsci.edu/browse/JP-2603)
This PR addresses a prior fix that caught infinite values to also catch negative infinity, and it implements a generic try/except to catch errors raised during an optional spline fit to instead use a generic array of estimate values.
Checklist
=> JP-2603: SOSS errors for negative infinity, spline fit

CHANGES.rst, jwst/straylight/straylight_step.py, jwst/straylight/tests/test_straylight_step.py
Resolves [JP-2587](https://jira.stsci.edu/browse/JP-2587)
This PR checks that the input data to the straylight step has a data model type = IFUImageModel. If it does not, then the step is skipped. 
Checklist
=> JP-2587 Check spec2 data is IFUImageModel for straylight step 

CHANGES.rst, jwst/resample/resample_spec.py
Resolves [JP-2612](https://jira.stsci.edu/browse/JP-2612)
This PR modifies the method of estimating sampling wavelengths in `resample_spec` to make it faster at the expense of not reproducing more accurately sampling wavelengths of the input/reference image.
Checklist
=> JP-2612: Speed up algorithm for computing sampling wavelengths

CHANGES.rst, jwst/pipeline/calwebb_spec3.py, jwst/pipeline/calwebb_tso3.py
Addresses [JP-2603](https://jira.stsci.edu/browse/JP-2603)
This PR addresses a bug, found earlier in Spec2Pipeline, which was missed but was also present in Spec3 and Tso3. The new SOSS algorithm currently cannot process data taken through the F277W filter and returns None; if this is passed on in pipeline flow, errors will occur. Gracefully avoid photom processing of None in the pipeline code.
Checklist
=> JP-2603: Catch None return from SOSS F277W in Level3

CHANGES.rst, docs/jwst/ami_average/description.rst, jwst/ami/ami_analyze.py, jwst/ami/ami_average.py, jwst/ami/lg_model.py, jwst/ami/nrm_core.py, jwst/ami/utils.py, jwst/regtest/test_niriss_ami3.py
Resolves [JP-2624](https://jira.stsci.edu/browse/JP-2624)
This PR updates the ami_average step to be able to handle inputs coming from the ami_analyze step that have different sizes (from exposure to exposure) for the `fit_image` and `resid_image` images. It gets around this by averaging to the minimum size of all the inputs, trimming extra rows/cols from inputs that are larger. Because they all have the target at the center of each image, this still keeps the target aligned in the averaging process, because the images are trimmed symmetrically from all edges.
Also updated the ami_analyze step to only include the primary header when it calls `model.update()` on the output image, so that the outputs don't end up with empty SCI extensions. The SCI extensions don't belong in …
=> JP-2624: Update ami_average for different size inputs

jwst/assign_wcs/tests/test_nircam.py
This PR temporarily xfails a couple of unit tests in assign_wcs, which are failing (different results) due to new NIRCam specwcs ref files installed in CRDS recently. They will soon be replaced by yet newer versions. So xfail the tests for now, so that CI tests can pass again.
Checklist
=> xfail NIRCam grism tests until ref files are fixed

CHANGES.rst, jwst/extract_1d/soss_extract/soss_extract.py
Closes #
Resolves [JP-2606](https://jira.stsci.edu/browse/JP-2606)
This PR addresses one more SOSS error raised if F277W is used - a previous PR dealt with the CubeModel branch, but I missed that a similar error is raised in a separate code branch for ImageModel inputs (i.e. rate files).
After seeing this ticket, I did a quick search for other errors being raised in ATOCA, and there are many. Considering a separate PR that prevents SOSS from hitting the eject button during OPS processing - maybe a JIRA ticket first.
Checklist
=> JP-2606: Catch two more SOSS errors raised.

CHANGES.rst, jwst/lib/set_telescope_pointing.py, jwst/lib/siafdb.py
Triggered by help desk issue INC0178097 and JWSTDMSDR-5801
This PR includes
- When using `pysiaf`, no defaults were used for non-critical missing SIAF values. The same defaults are implemented that are used when using the operation's PRD version of the SIAF
- Factor out the creation of the direction cosine matrix formula into is own function and refactor `set_telescope_pointing` to use this function.
Checklist
=> Fix SIAF default handling for missing SIAF values using pysiaf

CHANGES.rst, jwst/datamodels/container.py, jwst/skymatch/skyimage.py, jwst/skymatch/skymatch.py, jwst/skymatch/skymatch_step.py
This PR reduces memory usage when running `skymatch` step when input to the step is an ASN table. This is accomplished by saving large image and mask arrays to temporary files and retrieving them on demand. This PR will have no effect when input to the step is a list of already loaded into memory data models.
NOTE: Modifications to `jwst/datamodels/container.py` were designed by @stsci-hack who provided the file to me. I made minor adjustments, I think to `models_grouped`.
Checklist
=> Reduce memory usage in skymatch

CHANGES.rst, jwst/flatfield/flat_field.py
Closes #
Resolves [JP-2016](https://jira.stsci.edu/browse/JP-2016)
Set the DO_NOT_USE DQ bit in the flatfield if the NO_FLAT_FIELD dq bit is set.  This will ensure the flatfield value is set to 1.0 at those pixels.
Code now agrees with the documentation
Checklist
=> JP-2016: Flat_field step should ignore flatfield pixels with NO_FLAT_FIELD DQ bit set

CHANGES.rst, jwst/cube_build/ifu_cube.py
Closes #
Resolves [JP-2647](https://jira.stsci.edu/browse/JP-nnnn)
This PR fixes a bug in the cube_build step when  when reading values from in the cube parameter reference file. The cube pars reference file contains tables for defined wavelength ranges which hold  the parameters for how to run cube build. Based on the input data the program determines the  regions in the table to pull out. This PR fixes a bug when the region selected includes the last row in the table. The program was trying to pull out one beyond the last row. This bug was just found because a new cube parameter reference file was delivered with tables exactly covering the data. Previously the tables had some padding and went beyond the last wavelength of the data. 
Checklist
=> JP-2647 Fixed bug in selecting values from cubepars reference file

CHANGES.rst, jwst/source_catalog/source_catalog_step.py
Closes #
Resolves [JP-2650](https://jira.stsci.edu/browse/JP-2650)
This PR fixes a bug when using standalone SourceCatalogStep while providing the step a filename as input - the code was passing along the filename and not an opened datamodel.
Checklist
=> JP-2650: Fix SourceCatalogStep bug with input filename

CHANGES.rst, jwst/tweakreg/tweakreg_step.py
Skip tweakreg step when multiple matches to a single reference source are detected. This PR would reduce number of crashes even when match parameters are sub-optimal by skipping `tweakreg` step altogether. See [JP-2562](https://jira.stsci.edu/browse/JP-2562).  Also addresses issues listed in [DMSOPS-445](https://jira.stsci.edu/browse/DMSOPS-445).
Checklist
=> JP-2562: Skip tweakreg step when multiple matches to a single reference source are detected

CHANGES.rst, jwst/extract_1d/ifu.py, jwst/master_background/master_background_step.py
Resolves [JP-2653](https://jira.stsci.edu/browse/JP-2653)
This PR fixes incorrect variance propagation for surface brightness computations in IFU Extract 1D.
Checklist
=> JP-2653: Fix IFU variance propagation in extract_1d

CHANGES.rst, docs/jwst/saturation/description.rst, jwst/saturation/saturation.py
Resolves [JP-2611](https://jira.stsci.edu/browse/JP-2611)
This PR updates the NIRSpec IRS2 branch for handling pixels flagged as NO_SAT_CHECK in the saturation reference file DQ array or have thresholds of NaN in the saturation reference file. These pixels used to have their internal thresholds set to the A-to-D limit of 65535, but some pixels can attain that value and hence would get flagged when we don't want them to be. So now the internal threshold is set above the A-to-D limit, ensuring that they'll never get flagged (because no pixels can ever have values above the 65535 limit). Also updated the documentation to reflect this change.
The corresponding change for non-IRS2 data has been made in the `stcal` package in https://github.com/spacetelescope/stcal/pull/106 …
=> JP-2611: Update saturation handling of NO_SAT_CHECK

CHANGES.rst, jwst/datamodels/schemas/core.schema.yaml
Resolves [JP-2665](https://jira.stsci.edu/browse/JP-2665)
This PR updates core.schema to add the new MIRI dither pattern "SCAN-CALIBRATION" to the list of allowed values for the PATTTYPE (dither.primary_type) keyword.
Checklist
=> JP-2665: Add MIRI dither pattern SCAN-CALIBRATION

CHANGES.rst, docs/jwst/source_catalog/arguments.rst, jwst/source_catalog/source_catalog_step.py
This PR updates the default background boxsize and minimum number of pixels in the source catalog step:
* The background boxsize was increased to prevent oversubtraction of the background in sources smaller than the boxsize.  A larger size gives a more "global" vs. "local" background and prevents oversubtraction.  I recently observed this in simulated ERS (CEERS) data.
* The number of pixels was increased to prevent the detection of many tiny sources (which may not be real sources).
Ideally the source catalog default parameters would be instrument/detector specific and set by parameter reference files, but I don't think those have been delivered yet by the instrument teams.
Checklist
=> Update default parameters for source catalog step

jwst/regtest/test_nircam_tsgrism.py, jwst/regtest/test_niriss_soss.py
This PR removes the use of a user-supplied extract1d reference file in the NIRCam TSGrism regression tests. It was put there originally because a suitable ref file was not yet available in CRDS. Now there is (and has been for some time). So from now on the test will use the CRDS ref file.
Checklist
=> Update NIRCam TSGrism regtest

CHANGES.rst, jwst/cube_build/src/cube_match_sky_driz.c, jwst/extract_1d/ifu.py, jwst/master_background/master_background_step.py
Closes #
Resolves [JP-2652](https://jira.stsci.edu/browse/JP-2652)
In IFU data there can be regions in the IFU s3d cube with no valid data. If the IFU cube is built from MRS data of more than 1 channel (as in spec2) the regions between the channels have no valid data. Extract_1d  has been updated to set the DQ flag to DO_NOT_USE if no valid data is found in the extraction aperture. This then allows the master_background step to ignore those regions in combine_1d. Also a fix was made to all the master_background step option, save_background to write the background out.
Checklist
=> JP 2652  Set DQ flags in  extract 1d for IFU data

CHANGES.rst, jwst/datamodels/schemas/core.schema.yaml
Closes #
Resolves [JP-2633](https://jira.stsci.edu/browse/JP-2633)
This PR adds the unit (MJD) to the barycentric and heliocentric start, mid and end time header keyword comment strings.
Checklist
=> JP-2633: Add unit to time keyword comment strings

CHANGES.rst, jwst/pipeline/calwebb_spec3.py
Closes #
Resolves [JP-2664](https://jira.stsci.edu/browse/JP-2664)
This PR adds a check on the source_id created in calwebb_spec3, and modifies values that fall outside 0-99999. The wording in the JP ticket indicated this is a temporary fix, so it has been worded/coded as such; if I misinterpreted the level of 'hotfix' involved, I can edit the addition.
Checklist
=> JP-2664: Fix NRS-MOS source ids to be 5 digits and positive

jwst/regtest/test_miri_cubebuild.py, jwst/regtest/test_miri_image.py, jwst/regtest/test_miri_mrs_spec2.py
Resolves: a LONG-standing personal desire to get better data into our regression tests. Replaces the old test datasets used in MIRI imaging and spectroscopic tests with some real on-sky exposures. Input and truth files have been loaded to artifactory.
Checklist
=> Update some regtests with real data

setup.cfg
`certifi` has an issue with `pip freeze` (see https://github.com/conda/conda/issues/11580) that fails the DMS build pipeline on Jenkins (see https://plwishmaster.stsci.edu:8081/job/Releases/job/JWSTDP/62/console)
Thus, `certifi` should be pinned to a previous version until this issue is resolved.
**Checklist**
=> pin `certifi` to `2022.5.18.1`

CHANGES.rst, jwst/source_catalog/source_catalog.py, jwst/source_catalog/tests/test_source_catalog.py
Resolves [JP-2676](https://jira.stsci.edu/browse/JP-2676)
This PR fixes the units on the error array used in the source catalog step to calculate photometric errors. The unit-conversion function was written before the `i2d` data contained an `err` array and unfortunately wasn't updated subsequently to apply the MJy/sr to Jy unit conversion to the error array.
I'm not sure how to milestone this.  Do you want to get it in B8.1?
**Checklist**
=> JP-2676: Fix units of source catalog error array

CHANGES.rst, jwst/resample/resample.py, jwst/resample/resample_spec.py, jwst/resample/resample_spec_step.py, jwst/resample/resample_step.py
Resolves [JP-2580](https://jira.stsci.edu/browse/JP-2580)
The PR updates the resample_step to use the values read in from the drizpars reference file. The parameters in the reference file: pixfrac, weight_type, kernel, and fillval need to have defaults of None in the step spec. If they are not None, then the code assumes that the user has overridden the values.  In addition, the code was expecting pixel_scale_ratio to be in the drizpars reference file, instead of wht_type (weight_type). Since the reference file and data model expect the name of weight_type to be wht_type., self.wht_type was added and set to self.weight_type.
Checklist
=> JP-2580 update loading of drizpars table

CHANGES.rst, jwst/skymatch/skymatch_step.py
Closes #6920
This PR fixes the bug due to which `skymatch` step was not saving changes to the data models (computed/subtracted sky levels) when inputs are ASN files.
CC: @astroferreira
**Checklist**
=> Fix: skymatch not saving subtracted values for input ASN

CHANGES.rst, jwst/skymatch/skymatch_step.py
Resolves [JP-2688](https://jira.stsci.edu/browse/JP-2688)
Memory saving features introduced a bug in the `skymatch` step due to which background value is not subtracted from image model data even though step parameter `subtract` is set to True. This is due to how data now are written/saved to temporary files and the machinery involved in this. Due to these changes, the background was subtracted from a copy of the datamodel's array instead from original array.
This PR makes sure that model data are updated with matched/subtracted data values at the end of the step upon successful completion of the step.
**Checklist**
=> JP-2688: Skymatch - Update datamodel data when subtract is True

CHANGES.rst, jwst/datamodels/container.py, jwst/outlier_detection/outlier_detection.py, jwst/outlier_detection/outlier_detection_step.py, jwst/outlier_detection/tests/test_outlier_detection.py, jwst/resample/gwcs_drizzle.py, jwst/resample/resample.py, jwst/resample/resample_spec.py, jwst/resample/resample_step.py
Closes #
Resolves [JP-2527](https://jira.stsci.edu/browse/JP-2527) <Implement memory-saving improvements in outlier_detection>
The changes included here update the **outlier_detection** and **resample** steps in order to minimize the memory usage by processing the **ImageModels** on disk instead of memory.  This required updates to the **ModelContainer** class in datamodels to support **ImageModels** on disk rather than keeping them all open in memory.  The initial updates to the **ModelContainer** were implemented in #6874.  The **outlier_detection** step was also modified to compute the median image section-by-section as well.  Finally, new parameters were added to the **outlier_detection** step to control whether or not to process inputs in memory as originally …
=> JP-2527: Improve memory usage in outlier_detection and resample

CHANGES.rst, docs/Makefile, docs/conf.py, jwst/assign_wcs/__init__.py, jwst/assign_wcs/assign_wcs_step.py, jwst/assign_wcs/util.py
Resolves [JP-2690](https://jira.stsci.edu/browse/JP-2690)
Numerous users both on Slack and in the helpdesk are asking about updating FITS WCS info from the current GWCS stored in data model's `meta.wcs`. This PR adds a convenience function `update_fits_wcsinfo()` to `assign_wcs.util` module and modifies `assign_wcs` to call this convenience function.
**Checklist**
=> JP-2690: Convenience function for updating FITS WCS info

CHANGES.rst, jwst/tweakreg/tweakreg_step.py
Resolves [JP-2691](https://jira.stsci.edu/browse/JP-2691)
Resolves [JP-2586](https://jira.stsci.edu/browse/JP-2586)
This PR implements `FITS WCS` update at the end of `tweakreg` step if the `GWCS` of a data model was "tweaked" by `tweakreg`.
This PR will need to be rebased after #6935 is merged. It depends on that #6935. Initially unit tests will fail because of this.
**Checklist**
=> JP-2691: Update FITS WCS wcsinfo field at the end of tweakreg

CHANGES.rst, jwst/datamodels/schemas/core.schema.yaml, jwst/datamodels/schemas/mirlrs_pathloss.schema.yaml, jwst/datamodels/schemas/wcsinfo.schema.yaml
Resolves [JP-nnnn](https://jira.stsci.edu/browse/JP-1754)
Closes #1754
This PR addresses  inconsistencies between the descriptions (titles) of keywords in FITS files and their descriptions in the Keyword Dictionary. In many cases, the data models schemas are updated to match the KWD. In other cases, the keyword titles are written by astropy.io so are left unchanged.
**Checklist**
=> (JP-1754) Match FITS keywords to KWD

CHANGES.rst, jwst/datamodels/schemas/dark.schema.yaml
Resolves [JP-2656](https://jira.stsci.edu/browse/JP-2656)
Closes #2656
This PR simplifies the creation of reference files regarding multiple subarray values, by adding the ability to add these values into the header of the file when using the DarkModel.
**Checklist**
=> Add P_SUBARR to the DarkModel schema (JP-2656)

CHANGES.rst, jwst/tweakreg/tweakreg_step.py
Occasionally, converting a GWCS to FITS WCS in the `tweakreg_step` may fail due to poor convergence. Instead of raising an exception, the code should log the error and tweakreg step should proceed without updating FITS WCS.
**Checklist**
=> tweakreg should proceed on errors when  updating FITS WCS

CHANGES.rst, jwst/resample/resample.py
This PR fixes a bug in how resampled variances are computed due to which resampled error array tends to have an excessive number of zero-valued pixels. By this I mean that even though there were multiple images contributing to one output pixel in SCI, the corresponding pixel in the ERR extension was 0. The reason for this was that current algorithm computes a sum of inverse variances from each resampled image. If variance of a pixel in an input image is 0 then `1/variance` would be `np.inf`. Even if other input images have valid pixels and contribute to the output pixel, their variances, even if finite and >0 cannot clear `np.inf`. In the end, the final error array computed as `1/sum(1/variances)` resulting in the final value being 0 (for resampled variance). That is, something like this …
=> JP-2707: Fix excessive zeroes in resampled variance

CHANGES.rst, docs/jwst/datamodels/models.rst, docs/jwst/introduction.rst, docs/jwst/outlier_detection/arguments.rst, docs/jwst/resample/arguments.rst, docs/jwst/stpipe/parameter_files.rst, docs/jwst/stpipe/user_step.rst
This PR clarifies when CRDS environmental variables should be defined when using Python scripts.
**Checklist**
- ~updated or added relevant tests~
=> Add details on when crds environmentals be defined

CHANGES.rst, jwst/master_background/master_background_step.py
This PR fixes an issue where the sigma-clipped background isn't being used as intended for the master background step when the source type is undefined (see https://jira.stsci.edu/browse/JP-2797)
**Checklist**
=> JP-2797: MRS sigma-clipped master background fix

CHANGES.rst, jwst/cube_build/ifu_cube.py
Resolves [JP-2672](https://jira.stsci.edu/browse/JP-2672)
Resolves [JP-2673](https://jira.stsci.edu/browse/JP-2673)
This PR removes code that is only triggered if all three subchannels are present in cube building a channel's cube, i.e. short+medium+long. The code likely was not working as intended, and it will no longer add any dashes apart from the pre-existing dash between channel and subchannel, i.e. ch1-shortmediumlong. If dashes are wanted between the subchannel names, that could be added but doesn't seem necessary.
After realizing I reproduced the bug in JP-2673, I added that to this PR and sorted the subchannel list by inverse alphabetical order so that the presented order is increasing in wavelength (aesthetics?).
**Checklist**
=> JP-2672: Remove trailing dash from end of full subchannel listing

CHANGES.rst, jwst/tweakreg/tweakreg_catalog.py
This PR updates the detection threshold calculation to mask `NON_SCIENCE` pixels (e.g., MIRI).
xref: INC0180066
**Checklist**
=> Mask NON_SCIENCE pixels when calculating the detection threshold

CHANGES.rst, jwst/tweakreg/tweakreg_step.py
Refactor code along the lines of https://github.com/spacetelescope/jwst/pull/6939 and increase SIP approximation accuracy by a factor of 2: make it < 0.01 pixels for the forward transformation.
**Checklist**
=> Refactor code for updating FITS WCS and increase SIP accuracy

setup.cfg
Due to a bug in the `drizzle` version `1.13.5`, I am modifying `setup.cfg` to require use of bug-fixed version `1.13.6`. For more details, see https://github.com/spacetelescope/drizzle/pull/85
**Checklist**
=> Require drizzle>=1.13.6

CHANGES.rst, jwst/extract_1d/extract.py, jwst/extract_1d/soss_extract/soss_extract.py, jwst/pipeline/calwebb_tso3.py
Resolves [JP-2677](https://jira.stsci.edu/browse/JP-2677)
This PR adds back the int_times keywords to SOSS spectral products that have gone missing since the implementation of the ATOCA algorithm.
**Checklist**
=> JP-2677: Copy int_times keywords to output spectrum extensions for SOSS ATOCA

CHANGES.rst, jwst/ami/instrument_data.py, jwst/ami/matrix_dft.py, jwst/ami/utils.py
Poppy was recently updated to change the sign convention used in exponents in the Fourier transform calculation. This update reverts the ami_analyze code to use an earlier code, in the matrix_dft.py module.
Resolves [JP-2618](https://jira.stsci.edu/browse/JP-2618)
**Checklist**
=> Revert Fourier Transform code to avoid Poppy's recently updated sign convention (JP-2618)

CHANGES.rst, jwst/tweakreg/tweakreg_step.py
Resolves [JP-2687](https://jira.stsci.edu/browse/JP-2687)
This PR addresses the issue of `tweakreg` step exiting when only one input image is provided. This behavior was the desired one when there was only one "relative alignment" stage in `tweakwcs`. With the addition of alignment to Gaia stage, it now makes sense to bypass first stage and allow single images to align to GAIA. This PR enables this logic.
**Checklist**
=> JP-2687: Allow alignment of a single image/group to Gaia bypassing first alignment stage

CHANGES.rst, jwst/cube_build/cube_build_wcs_util.py, jwst/cube_build/ifu_cube.py, jwst/cube_build/src/cube_dq_utils.c, jwst/cube_build/src/cube_match_sky_driz.c
Resolves [JP-2654](https://jira.stsci.edu/browse/JP-2654)
Resolves [JP-2662](https://jira.stsci.edu/browse/JP-2662)
This PR is a duplicate of [PR 6957](https://github.com/spacetelescope/jwst/pull/6957). That PR was made before all the flake8 changes. There were too many conflicts once that PR was rebased with master, so I pull in the relevant changes from that PR and put them here.
This PR addresses a bug in the C code used by cube_build that sets the DQ flag for NIRSpec IFU data. After a review of the code it was determined the flagging was not being done correctly. I re-wrote the code to make it easier to follow. In the process of re-writing the code I fixed the segmentation fault error. 
When the above bug was fixed, a second bug was discovered. The NIRSpec data for this ticket is …
=> JP-2654 JP-2662: Fix bug in NIRSpec IFU DQ flagging and handling of moving target exposures

CHANGES.rst, jwst/cube_build/cube_build_wcs_util.py, jwst/cube_build/ifu_cube.py, jwst/cube_build/src/cube_dq_utils.c, jwst/cube_build/src/cube_match_sky_driz.c
Reverts spacetelescope/jwst#6971 because we're getting C compiler errors, at least on Linux, that didn't exist before.
=> Revert "JP-2654 JP-2662: Fix bug in NIRSpec IFU DQ flagging and handling of moving target exposures"

CHANGES.rst, jwst/tweakreg/tweakreg_catalog.py
Resolves [JP-2814](https://jira.stsci.edu/browse/JP-2814)
This PR addresses this comment: https://github.com/spacetelescope/jwst/pull/6940#issuecomment-1212045272 from #6940
=> JP-2814: Exclude pixels flagged with DO_NOT_USE from source finding

CHANGES.rst, jwst/cube_build/ifu_cube.py
Resolves [JP-2811](https://jira.stsci.edu/browse/JP-2811)
This PR updates the wcs naxis3 value if wavelength planes have been removed from the IFUcube because only values of zero were contained in the planes (i.e. no valid data in wavelength plane) 
https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/383/#showFailuresLink
Failure for imager modes not related to this PR.
=> JP-2811  Update wcs naxis3  when removing wavelength planes from cube

CHANGES.rst, jwst/cube_build/cube_build_wcs_util.py, jwst/cube_build/ifu_cube.py, jwst/cube_build/src/cube_dq_utils.c, jwst/cube_build/src/cube_match_sky_driz.c
Resolves [JP-2654](https://jira.stsci.edu/browse/JP-2654)
Resolves [JP-2662](https://jira.stsci.edu/browse/JP-2662)
This PR was tried in   https://github.com/spacetelescope/jwst/pull/6957 and https://github.com/spacetelescope/jwst/pull/6971   PR (6957) was made before all the flake8 changes. There were too many conflicts once that PR was rebased with master, so I pull in the relevant changes from that PR and put them here. PR(6971) had to be reverted because of syntax errors in the C code that did you show up on MAC OS but did on linux system in testing. 
This PR addresses a bug in the C code used by cube_build that sets the DQ flag for NIRSpec IFU data. After a review of the code it was determined the flagging was not being done correctly. I re-wrote the code to make it easier to follow. …
=> JP-2654 JP-2662 Fix bug in NIRSpec IFU DQ flagging and handling of moving target exposures (new try) 

CHANGES.rst, jwst/master_background/master_background_step.py
Resolves [JP-2808](https://jira.stsci.edu/browse/JP-2808)
This PR fixes the retrieval of the SRCTYPE value in the master_background step for the case of NIRSpec IFU data. The input background spectra (from x1d products) are always in the form of a `SpecModel` or `MultiSpecModel`, in which case the SRCTYPE must be read from the "spec" attribute of the data model, not from the generic `model.meta.target.source_type` attribute (which is None for these kinds of models).
=> JP-2808: Fix handling of SRCTYPE in master background

setup.cfg
The issue that caused `pip freeze` to provide an invalid version definition for `certifi` when in a `conda` environment (https://github.com/spacetelescope/jwst/pull/6927) seems to be resolved with the latest version. I tested this by running `pip freeze` locally.
=> update `certifi` dependency version to use new version (now works with `pip freeze`)

CHANGES.rst, setup.cfg
This PR addresses a recent issue with unit tests that appears to be causing unit and regression tests to fail. This is possibly related to a new release of `jsonschema` to version `4.10.0`.
=> pin `jsonschema` below `4.10.0` to fix issues with unit and regression tests

CITATION.cff
Currently, the `CITATION.cff` file is not parsed by GitHub as it is not in [Citation File Format](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files): <img width="1226" alt="image" src="https://user-images.githubusercontent.com/16024299/184956404-8fd5c7a7-5fa0-4a79-8869-c077d8de90a9.png"> 
This PR updates the file to be in the correct format.
=> update citation with Citation File Format

CHANGES.rst, jwst/ramp_fitting/tests/test_ramp_fit_step.py
…es and their corresponding DQ flags.  The rateints product will have all NaNs set to zero with the corresponding DQ flag set to DO_NOT_USE.
Resolves [JP-2669](https://jira.stsci.edu/browse/JP-2669)
This PR addresses testing changes needed due to updates in [STCAL PR 112](https://github.com/spacetelescope/stcal/pull/112), which updates the way the rateints gets computed.  NaNs in the rateints products are converted to 0. and the corresponding DQ value has the `DO_NOT_USE` flag set.
**Checklist**
=> JP-2669: Updating tests due to new STCAL behavior for NaNs in rateints product.

CHANGES.rst, docs/jwst/jump/arguments.rst, docs/jwst/jump/description.rst, jwst/jump/jump.py, jwst/jump/jump_step.py, jwst/jump/tests/test_detect_jumps.py
Resolves [JP-2693](https://jira.stsci.edu/browse/JP-2693)
This PR implements the enhancement to the jump step where groups after detected jumps are flagged do_not_use. This "corrects" transients that have been seen to make the slope after a jump different than before. This PR allows for flagging to be different for two different jump thresholds.
The main changes are in `stcal` and this PR provides the needed interface for `jwst`.
**Checklist**
=> JP-2693: Flag groups do_not_use after detected ramp jumps

CHANGES.rst, jwst/resample/resample_spec_step.py, jwst/resample/resample_step.py
Resolves [JP-2803](https://jira.stsci.edu/browse/JP-2803)
Closes #
This PR adds assignment of `model.meta.asn.pool_name` and `{...}.table_name` to level 2b i2d products - this required propagating these keywords through an intermediate ModelContainer in the resample step.
There was discussion in the JIRA ticket of propagating values from the first contained model if any ModelContainer was found have no assigned values, but I felt that this covers the issue more cleanly - if there is a need for other behavior, please let me know.
NB: If a user runs e.g. `strun calwebb_image2 some_rate.fits`, the i2d output will have values of 'singleton' for both of these keywords. If using a MAST-provided level2 asn, the values propagate as expected.
[How to run regression …
=> JP-2803: Propagate asn keywords to resample output products for level 2 processing

CHANGES.rst, docs/jwst/error_propagation/main.rst
Resolves [JP-2595](https://jira.stsci.edu/browse/JP-2595)
This PR makes a small update to the Error Propagation section of the docs, adding info about the variance array used by the resample step.
=> JP-2595: Update error propagation docs

CHANGES.rst, docs/jwst/outlier_detection/outlier_detection.rst, jwst/datamodels/container.py, jwst/outlier_detection/outlier_detection_step.py, jwst/resample/resample.py
Resolves [JP-2816](https://jira.stsci.edu/browse/JP-2816)
Resolves [JP-2820](https://jira.stsci.edu/browse/JP-2820)
This PR updates the documentation related to the memory model implemented under #6904 for [JP-2527](https://jira.stsci.edu/browse/JP-2527).  The changes include:
- Adding a section to the outlier_detection algorithm discussion on the overall memory model. 
- Updated the ModelContainer docstring to add Notes describing the optional parameters defined and used for the outlier_detection memory improvements
- Added a Note to the ResampleStep docstring to describe the new ``in_memory`` parameter.
- Updates initialization of the ModelContainter based on ``in_memory`` parameter. [JP-2820] …
=> JP-2816: Update outlier docs

CHANGES.rst, jwst/tweakreg/tests/test_multichip_jwst.py, jwst/tweakreg/tweakreg_step.py, setup.cfg
This PR updates code that uses `tweakwcs` to use newest classes instead of the deprecated ones. For a full list of changes in `tweakwcs 0.8.0` - see https://github.com/spacetelescope/tweakwcs/releases/tag/0.8.0. Most changes are about changing class and module names to better represent what they actually do.
This PR updates `drizzlepac` code in order to avoid deprecation warnings.
Regression test link: https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/402/
=> Update code to use tweakwcs 0.8.0

CHANGES.rst, jwst/cube_build/ifu_cube.py, jwst/cube_build/src/cube_match_sky_driz.c
Resolves [JP-2859](https://jira.stsci.edu/browse/JP-nnnn)
Closes #
This PR fixes a bug in cube_build when the user provided the spatial scale to use when building the IFU cube. 
https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/399/
=> JP-2859 Bug fix for cube_build when user changes input spatial scale to use for IFU cube 

jwst/regtest/test_niriss_wfss.py
This PR updates the NIRISS WFSS regression test to use recent in-flight data and the latest "specwcs" calibrations as part of the WCS. All input and truth files have been uploaded to artifactory and runs successfully when tested standalone.
Also just restructured the way the test modules themselves are written (cuz I just didn't like the old style!)
=> Update NIRISS WFSS regtest with in-flight data

CHANGES.rst, jwst/lib/engdb_direct.py, jwst/lib/engdb_mast.py, jwst/lib/engdb_tools.py, jwst/lib/tests/data/test_from_models_mast.ecsv, jwst/lib/tests/data/test_over_time_mast.ecsv, jwst/lib/tests/test_engdb_tools.py
Resolves [JP-2865](https://jira.stsci.edu/browse/JP-2865)
This PR addresses an issue discovered in OPS. For unknown reasons, the engineering database service
will fail to provide mnemonics. This causes tasks such as `set_telescope_pointing` to fail.
It has been found that these are transient situations and that adding retry/timeout parameters to the network calls, the above situation would be mitigated. This PR adds these capabilities to the `ENGDB_Service`.
=> JP-2865 Add retries and timeout parameters to engineering access calls

jwst/assign_wcs/tests/test_wcs.py
@jdavies-st  reported that pytest jwst/assign_wcs/tests/test_wcs.py::test_sip_approx was failing and my investigation showed that it happened after recent changes in `gwcs` reporting SIP fit errors from arcseconds to pixels (since fit quality is specified in pixels so it was good to be consistent). The only parameter that is different is `sipmxerr` and the test is expected to fail when using master branch of `gwcs`. Once there is a release of `gwcs`, this test will need to be updated.
=> Fix failing assign_wcs test due to gwcs changes

CHANGES.rst, jwst/wfss_contam/disperse.py, jwst/wfss_contam/observations.py
Resolves [JP-2906](https://jira.stsci.edu/browse/JP-2906)
This PR updates the attribute names for the subarray corner offsets in the WCS transform used in the `wfss_contam` step for grism images, as described in JP-2906. It should be backwards compatible, by first trying to use the old attribute names and then using the new ones if that fails.
=> JP-2906: Fix wcs attribute names in wfss_contam step

CHANGES.rst, docs/jwst/tweakreg/README.rst, jwst/tweakreg/tweakreg_step.py
1. This PR fixes a bug from PR #6987 which introduced `abs_minobj` parameter which should have _replaced_ `min_gaia` but it inadvertently left it in the step `spec` and also in the code.2. 
2. This PR renames `gaia`-specific parameters to be in line with the new convention (`abs`) adopted in #6987. This is continuation of the work started in #6946. In particular, @hbushouse see https://github.com/spacetelescope/jwst/pull/6946#discussion_r944534937.
Specifically, this PR renames: ``gaia_catalog``->``abs_refcat`` and ``save_gaia_catalog``->``save_abs_catalog``.
``save_abs_catalog`` is used to save used GAIADR? catalogs to disk (but it will also re-save user-supplied reference catalogs if users choose to do so - hopefully they won't).
This PR also removes `align_to_gaia` boolean step …
=> Remove min_gaia and rename gaia->abs parameters

CHANGES.rst, jwst/assign_wcs/assign_wcs_step.py
Fixes reported crashes in the pipeline during testing. (Reported by @nden)
=> Fix crashes in assign WCS due to uncaught SIP convergence exceptions

CHANGES.rst, jwst/coron/median_replace_img.py, jwst/regtest/test_nircam_coron3.py
Resolves [JP-2913](https://jira.stsci.edu/browse/JP-2913)
This PR updates the median image replacement routine used in the coronagraphic "align_refs" step so that it rejects and replaces pixels that are NaN in addition to pixels that are flagged as bad (some NaNs are not flagged, which is another issue).
The presence of NaN's causes the various FFT routines used for alignment and shifting to return updated images that are all NaN (which is not a good thing).
=> JP-2913: Fix the coron median replace algorithm

.github/workflows/publish-to-pypi.yml
This change ensures that `requirements-sdp.txt` has requirements in it (non-commented lines) before allowing the PyPI publish to occur. This can hopefully prevent releases without SDP requirements.
=> check whether `requirements-sdp.txt` is empty before publishing to PyPI

CHANGES.rst, jwst/source_catalog/source_catalog.py, jwst/source_catalog/source_catalog_step.py, jwst/source_catalog/tests/test_source_catalog.py
A copy of the input model is not made in SourceCatalogStep since there is no return model (just the table). In the step, the units of the data/err arrays are converted and the background is subtracted from the data. If someone attempts successive runs of the step, it will fail because of these changes to the input.
This PR resets the model's data/err arrays and metadata information about units so that the input remains unchanged.
Resolves [JP-2694](https://jira.stsci.edu/browse/JP-2694)
=> JP-2694: reset input model after Source Catalog Step

CHANGES.rst, jwst/resample/resample.py, jwst/resample/resample_step.py, jwst/resample/tests/test_resample_step.py
(This PR is replacing #6999 )
The parameter 'pix_scale_ratio' was not being passed to ResampleData, so the default of 1.0 was always being used - this PR fixes that. Additionally, if 'pixel_scale' is provided, it overrides 'pix_scale_ratio' -  in this case, the header value for `pixel_scale_ratio` was not being recalculated to reflect the absolute pixel scale passed in. The source_catalog step uses this value from the header, so it needed to be accurately calculated. 
Resolves [JP-2627](https://jira.stsci.edu/browse/JP-2627) and [JP-1757](https://jira.stsci.edu/browse/JP-1757)
Closes #5426
=> JP-2627: Fixes to pixel scale in resample and photometry keywords

CHANGES.rst, jwst/resample/resample_step.py, jwst/resample/tests/test_resample_step.py
Fixes an error introduced by #7033 where the pixel scale ratio was incorrectly defined - it is now correctly computed as a ratio of pixel areas. 
=> fix definition of pixel ratio

CHANGES.rst, jwst/regtest/test_migrate_data.py, jwst/resample/resample_spec.py
Resolves [JP-2918](https://jira.stsci.edu/browse/JP-2918)
This PR fixes the calculation of resampled output frames for NIRSpec slit data (either fixed-slit or MOS) by making the algorithm less sensitive to the presence of negative spectral traces in the input images (which occurs when nodding is used to do background subtraction).
=> JP-2918: Fix bad resampled frames for NRS MOS

CHANGES.rst, jwst/lib/set_telescope_pointing_cmdline.py, scripts/set_telescope_pointing.py
Resolves [JP-2940](https://jira.stsci.edu/browse/JP-2940)
During SDP testing, it was noted that `set_telescope_pointing` was not exiting with a non-zero status when execution stopped prematurely. This PR ensures that any unexpected exception will set the status to greater than 0.
=> JP-2940 Return non-zero status from the set_telescope_pointing command-line when an error occurs

CHANGES.rst, jwst/datamodels/schemas/core.schema.yaml, jwst/datamodels/schemas/keyword_noutputs.schema.yaml
Resolves [JP-2946](https://jira.stsci.edu/browse/JP-2946)
This PR updates the datamodels schemas that contain the NOUTPUTS keyword definitions to add "5" to the list of allowed values.
=> JP-2946: Update NOUTPUTS allowed values

CHANGES.rst, jwst/lib/siafdb.py, jwst/lib/tests/test_siafdb.py
Resolves [JP-2970](https://jira.stsci.edu/browse/JP-2970)
This PR addresses an issue found in SDP in the logic of how `set_telescope_pointing` was determining the source of the siaf XML files. `set_telescope_pointing` was using the internal, `pysiaf`-delivered, XML files when PRD_VER was found, ignoring the setting of `XML_DATA` environment variable.
This PR fixes this, so that, if `XML_DATA` is defined, that folder will be used as the source of the XML files.
=> JP-2970 Allow XML_DATA usage to override PRD specification

CHANGES.rst, docs/jwst/data_products/science_products.rst, jwst/resample/gwcs_drizzle.py
This forces the context array to be in sync with the products `con` attribute.
Resolves [JP-2971](https://jira.stsci.edu/browse/JP-2971)
This PR addresses an issue found in by a user where the output of `calwebb_image3` had a context array that made no sense. The issue was that the context array was being calculated but not attached to the output model.
=> JP-2971 Make the GWCSDrizzle.outcon attribute a property with setter

docs/jwst/source_catalog/main.rst, jwst/source_catalog/source_catalog.py
This PR updates the docs to add a note about the source catalog centroid pixel indexing.  I've also added this to the column descriptions in the output catalog metadata.  A few users (e.g., help desk tickets) have been confused about the pixel indexing.
=> Add note about source catalog pixel indexing

CHANGES.rst, jwst/associations/main.py
Resolves [JP-2910](https://jira.stsci.edu/browse/JP-2910)
Closes #
This PR move printing the association text dump to the screen from "info" to "debug", i.e., the text dump now occurs when using the `-D` option, instead of the `-v` option.
=> JP-2910: Moving associations dump from info to debug.

CHANGES.rst, jwst/datamodels/schemas/filteroffset.schema.yaml
Resolves [JP-2975](https://jira.stsci.edu/browse/JP-2975)
Closes #7299 
This PR adds subarray.schema and keyword_p_subarray.schema to the filter offset file. 
=> JP-2975 Update MIRI Imager Filteroffset schema 

CHANGES.rst, jwst/assign_wcs/util.py, jwst/extract_2d/grisms.py
Resolves [JP-2982](https://jira.stsci.edu/browse/JP-2982)
This PR updates the extract_2d step so that it skips processing of any 2D cutouts that are defined with a length of <1 pixel in either of their dimensions, as computed from the WCS-related info for the cutout.
=> JP-2982: Fix extract_2d to skip zero-length cutouts

CHANGES.rst, jwst/resample/resample_spec.py
Resolves [JP-2931](https://jira.stsci.edu/browse/JP-2931)
Closes #7293
This PR fixes a crash observed in some datasets caused by the presence of almost the same points in the list of wavelengths in output spectral WCS.
Regression tests *are still running*: https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/450/
=> JP-2931: Guard against nearly identical points in nirspec resampled WCS

CHANGES.rst, jwst/lib/wcs_utils.py
Resolves [JP-2934](https://jira.stsci.edu/browse/JP-2934)
Closes #7275 
This PR addresses a crash in `photom` due to circular imports. photom imports `assign_wcs.niriss` and then `lib.wcs_utils`, which in turn imports `assign_wcs.niriss`. The import of `assign_wcs.niriss` in `lib.wcs_utils` is to use a niriss specific funciton which returns a WCS object for a specific order so that it can be evaluated to generate a wavelength array. This function is not needed any more since the WCS object for NIRISS SOSS mode can be directly evaluated using non-coordinate inputs, like order. One simple calls the WCS object as in `WCS(x, y, spectral_order)`.
[How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Br …
=>  JP-2934: Fix circular import causing crash in photom

CHANGES.rst, jwst/associations/lib/rules_level3_base.py
Resolves [JP-2989](https://jira.stsci.edu/browse/JP-2989)
Closes #
This PR addresses a residual c1xxx level 3 association created despite containing members from only one observation. The c1xxx association was of type 'background', while only 'group' types were being subjected to the additional requirement added in #6886. Additionally, a function used to prevent background associations from being generated was turned off ~3 years ago but never removed, so this tidies that up as well.
=> JP-2989: Add 'background' to asn types requiring multiple group contributions

docs/jwst/assign_wcs/main.rst
Resolves [JP-2987](https://jira.stsci.edu/browse/JP-2987)
Closes #
This PR addresses a missing part of documentation - how we make corrections to the WCS to account for spacecraft motion. Looking for any comments on if what I've written is correct, clear, and sufficiently detailed. Could add references?
=> JP-2987: Add documentation on WCS corrections due to spacecraft motion

CHANGES.rst, jwst/datamodels/schemas/core.schema.yaml
jsonschema draft 4 (used by asdf) states that enum values MUST be unique. This was unchecked prior to a recent commit python-jsonschema/jsonschema@2db9c58
[core.schema.yaml](https://github.com/spacetelescope/jwst/blob/master/jwst/datamodels/schemas/core.schema.yaml#L1061) contains duplicate dithering types for the different instruments (for example CYCLING for NIRSpec IFU and MIRI imaging)
This commit removes the duplicates in a way that might impair user readability of the file (as types are no longer logically grouped to instrument).
=> remove duplicate enum values from core.schema.yaml

CHANGES.rst, jwst/photom/photom.py
Resolves [JP-2996](https://jira.stsci.edu/browse/JP-2996)
Closes #
This PR addresses an issue seen when corrections to the NRS_IFU pixel area reference file were tested. Changes to the pixel area of scale N were seen applied to the data array at scale N**2, indicating that the pixel areas were being divided out twice.
In testing edits to the code, it was noticed that the pixel area was being divided out of all NRS_IFU data, but because the current dummy files are filled with values of 1, it went unnoticed. Additionally, the pixel area division was being done in units of square arcseconds, which required adding a factor of A2_TO_SR to the code where the pixel area is divided out slice-by-slice. 
The duplicate removed was dividing the conversion factor by the mean pixel area across all …
=> JP-2996: Remove duplicate application of pixel area to NRS_IFU extended data

CHANGES.rst, docs/jwst/cube_build/main.rst, jwst/cube_build/ifu_cube.py, jwst/extract_1d/ifu.py
Resolves [JP-2997](https://jira.stsci.edu/browse/JP-2997), implements switch from zero-fill to nan-fill IFU data cubes.
This PR also fixes multiple parts of the IFU Extract1D code that crash once the s3d data cubes contain nan values, largely because aperture_photometry and the native 'sum' commands do not cleanly handle nans.
=> JP-2997: Implement nan-filled padding for zero-coverage regions around IFU data cubes

CHANGES.rst, docs/index.rst, docs/jwst/introduction.rst, docs/jwst/pub_deprecation.rst
Resolves [JP-2986](https://jira.stsci.edu/browse/JP-2986)
Closes #7322 
This PR documents the deprecation of the CRDS PUB server, providing direction on how to transition away from CRDS PUB.
=> JP-2986 CRDS PUB deprecation notice and transition documentation

CHANGES.rst, docs/jwst/pub_deprecation.rst
This PR addresses fixes some copyedit issues and brings the deprecation notice in-line with what is on the PUB server.
=> update deprecation notice with copyedit changes

CHANGES.rst, docs/jwst/error_propagation/main.rst, docs/jwst/flatfield/main.rst, docs/jwst/guider_cds/description.rst, jwst/flatfield/flat_field.py
Resolves [JP-2993](https://jira.stsci.edu/browse/JP-2993)
Closes #2993
This PR updates the flat-field step's ERR computation for the FGS guider mode exposures. The recent update in #7309, which added computation of ERR values for guide star exposures in the guider_cds step, necessitates this update in the flatfield step to make use of those ERR values when computing the total ERR for the flat-fielded data.
=> (JP-2993) Update flat-field ERR computation for FGS guider

CHANGES.rst, docs/jwst/introduction.rst, docs/jwst/pub_deprecation.rst
Resolves [JP-3003](https://jira.stsci.edu/browse/JP-3003)
This PR addresses issues users are having managing their local CRDS cache by updating various points in documentation on how to create and maintain caches.
=> JP-3003 Clarify how to manage a local CRDS cache

CHANGES.rst, jwst/associations/lib/rules_level3.py, jwst/associations/tests/test_level3_spectrographic.py
Resolves [JP-2984](https://jira.stsci.edu/browse/JP-2984)
Closes #7315 
This PR makes a trivial change to the NIRISS WFSS level-3 ASN rule so that unique ASN's and products are created for each of the gr150r and gr150c grisms.
=> JP-2984: Update ASN rules for NIS_WFSS to keep grisms separate

CHANGES.rst, setup.cfg
Resolves [JP-2991](https://jira.stsci.edu/browse/JP-2991)
Closes #
This PR requires the asdf transform version to be at least 0.3.0, by updating setup.cfg. This was prompted by a user unable to open files from MAST using the JWST data models .
=> (JP-2991) Require asdf-transform-schemas greater than 0.3.0

JenkinsfileRT, JenkinsfileRT_dev, requirements-sdp.txt, setup.cfg
Resolves [SPB-1023](https://jira.stsci.edu/browse/SPB-1023)
applies changes, suggested by @jdavies-st in https://github.com/spacetelescope/jwst/issues/7334#issuecomment-1317137651, to ensure the latest version of `certifi` is installed without incurring the issue with `pip freeze` and `certifi` in a `conda` environment
=> use `pip` instead of `conda` to install `certifi`, to solve `pip freeze` issue

jwst/regtest/test_nirspec_ifu_spec2.py
This PR fixes the regression test that was updated in #7349. When running in the Jenkins tests the individual photom and extract_1d tests were searching for truth files of the wrong name. @stscieisenhamer suggested this was due to scope being set to the module level, so the multiple tests were clobbering the contents of `rtdata_module`, leading to incorrect file names being used in the `is_like_truth` convenience function. This change removes the module-level scope to (hopefully) fix the problems.
=> Fix recently updated regression test

README.md, docs/getting_started/install.rst
Resolves [JP-3012](https://jira.stsci.edu/browse/JP-3012)
Closes #
This PR addresses an installation issue found by some help desk users on MacOS Mojave in a python 3.10 environment. The dependency ``opencv-python`` has no stable build and will prevent successful installation.
~~- [ ] added entry in `CHANGES.rst` within the relevant release section~~
~~- [ ] updated or added relevant tests~~
=> JP-3012: Add note for install issue on Mojave

CHANGES.rst, jwst/__init__.py
JWST requires Python 3.8 or higher. However, Python 3.5 is specified in __init__.py.
Closes #
- ~updated or added relevant tests~
- ~updated relevant documentation~
- ~Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)~
=> Wrong Python version expected in __init__.py

jwst/datamodels/tests/test_schema_against_crds.py, setup.cfg
Closes #
Is it time to replace the CRDS PUB server from a datamodels test with the OPS server? Noticed because of an issue with the JWST-devdeps job.
=> remove CRDS PUB server from test

.github/workflows/ci.yml, .github/workflows/ci_cron.yml, tox.ini
This PR re-enables caching of the CRDS_PATH for the CI workflows, after having been turned off in #6165.  It should make the per-PR CI much more reliable (no failed reffile downloads) and slightly faster overall.
This takes advantage of @zacharyburnett 's excellent tox.ini refactor in PR #7323 (with some minor additions), and uses the new clean structure to distinguish which tox envs are running unit tests which use CRDS and which are not.
Here we use the CRDS_CONTEXT as the cache key.  The context will change more often than the contents of CRDS_PATH itself, but that's pretty much the only way to do it that makes sense, as we are trying to cache the snapshot of reffiles that are pulled during the running of the unit tests, and thus need a proxy for the contents of this snapshot before …
=> Cache CRDS_PATH reffile contents in CI workflows

jwst/datamodels/tests/test_fits.py, setup.cfg
When resaving a model to fits, asdf loses track of array-hdu links and saves arrays in both hdu and as internal blocks in the asdf tree. This can make an asdf tree that is larger than what can be stored in a fits hdu.
See asdf issue: https://github.com/asdf-format/asdf/issues/1232
This test is skipped as it fails with the current asdf version.
=> Add test for duplicate data when resaving model to fits

CHANGES.rst
This PR simply adds an entry to the jwst change log to document a bug fix in the dark_current step in the low-level code contained in stcal, which was included in Build 9.0.
=> Add missing change log entry for stcal update

CHANGES.rst, jwst/resample/resample_spec.py
Resolves [JP-2802](https://jira.stsci.edu/browse/JP-2802)
Closes #7265
This PR fixes a bug in the definition of the NIRSpec resampled WCS. Fundamentally, the bug was that for the forward transformation the horizontal position in the slit was incorrect. This PR fixes horizontal position to 0 - center of the slit. I expect regression tests to fail.
Regression test: https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/469/
=> JP-2802: Fix a bug in the definition of NIRSpec resampled WCS

CHANGES.rst, jwst/pipeline/tests/helpers.py, pyproject.toml, setup.cfg, tox.ini
`ruff` is an in-development Python linter written in Rust that aims for parity with combined Flake8 and Black: https://github.com/charliermarsh/ruff
It has several advantages over `flake8`, including significant speedups in linting and support for `pyproject.toml` configuration and PEP517 / PEP621.
=> use `ruff` in place of `flake8`

CHANGES.rst, jwst/extract_2d/grisms.py, jwst/extract_2d/tests/test_grisms.py
Resolves [JP-3007](https://jira.stsci.edu/browse/JP-3007)
Closes #3007
This PR populates the slit-specifc keywords "SRCRA, SRCDEC" (whose meta attributes "source_ra, source_dec") for WFSS extractions.
(https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/474/#showFailuresLink)
(https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)
=> (JP-3007) Add keywords for source RA and Dec for WFSS extractions.

jwst/associations/tests/test_level3_wfscmb.py, jwst/outlier_detection/tests/test_outlier_detection.py
Resolves [JP-3009](https://jira.stsci.edu/browse/JP-3009)
This PR adds fixtures to a few tests so that those tests do not leave files generated and saved while running the tests behind. The unit tests for JWST should not leave behind "artifacts" after running as this could interfere with re-running tests and/or lead to those files accidentally being picked up by git.
=> JP-3009: Add cleanups for files left behind while running tests

CHANGES.rst, docs/jwst/extract_1d/description.rst, docs/jwst/references_general/extract1d_reffile.inc, jwst/extract_1d/extract.py
Resolves [JP-2998](https://jira.stsci.edu/browse/JP-2998)
Closes #
This PR addresses when a user modifies an extract1d json reference file (which contains format errors) and used this file in  extract1d step. The errors returned were not helpful to understanding that the bug was in the json reference file. The organization of reading in the possible types of extract1d reference file formats (json, fits, asdf) now uses the last 4 characters of the file to assist in reading the file. Checks were put in if an error is encountered in reading the file and possible solutions returned in the log messages. In addition , in the documentation a section was added concerning  modifying the extract1d json files.  …
=> JP-2998 Extract1D using custom json files

CHANGES.rst, jwst/assign_wcs/nirspec.py
Resolves [JP-2969](https://jira.stsci.edu/browse/JP-2969)
Closes #7227 
This PR makes a simple update to the function in the assign_wcs step that does all the parsing of info from the MSA metadata file for NIRSpec MOS exposures. There are now instances where the source_id in the meta data is only set to a non-zero value for the one shutter that contains the primary source, rather than having the same source_id entry for all shutters contained in the slitlet. So this changes the code that retrieves the source_id for a given slitlet to use the value from the primary shutter, rather than just taking it from the first shutter in the slitlet (which can now be zero).
[How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression …
=> JP-2969: Fix MOS handling of source IDs

.github/workflows/ci.yml
The previous expansion of the CI matrix into multiple Python versions (#7378) might have been a bit overkill, as now it takes the testing stage far longer to produce a usable result 😅
This PR addresses redundancy in the CI matrix pointed out by @jdavies-st (https://github.com/spacetelescope/jwst/pull/7378#pullrequestreview-1209875099) that can be collapsed by running  `toxenv`s in less patterns
=> consolidate duplicated job blocks into `include:` in initial test matrix

CHANGES.rst, jwst/associations/lib/process_list.py, jwst/associations/registry.py
This PR addresses a bug in `associations/registry.py` seen in python 3.11 testing and discussed here
https://github.com/spacetelescope/jwst/pull/7333#issuecomment-1322253629
The failure was in unit test `jwst/associations/tests/test_asn_from_list.py::test_level2_from_cmdline`.
It's not clear to me this is the desired fix.  It does fix it, but given that the generated rules produced in the test produce the following rules (produced by adding `print(rule_name, obj)` at line 322 in registry.py):
```
Association <class 'jwst.associations.association.Association'>
RegistryMarker <class 'jwst.associations.registry.RegistryMarker'>
AsnMixin_Lv2Image <class 'jwst.associations.lib.rules_level2_base.AsnMixin_Lv2Image'>
AsnMixin_Lv2Nod <class …
```
=> Fix associations ListCategory enum bug

CHANGES.rst, docs/jwst/user_documentation/pub_deprecation.rst
Resolves user incident report INC0184702
This PR addresses yet another typo in the naming of the CRDS_PATH environment variable.
Developer cannot be trusted to write documentation...
=> Update deprecation notice to name the CRDS_PATH variable appropriately

CHANGES.rst, docs/jwst/cube_build/main.rst, jwst/cube_build/ifu_cube.py
Resolves [JP-3019](https://jira.stsci.edu/browse/JP-3019)
Given other updates in the past couple years this is no longer necessary, and always producing cubes of known size is helpful for both science analyses and MAST.
=> JP-3019: Remove code trimming zero-valued cube planes

CHANGES.rst, jwst/datamodels/slit.py
JP-2671 has four issues and this PR resolves only first issue:  LRS data does not have a value for var_flat for s2d or x1d. 
Resolves  only part 1 pf [JP-2671](https://jira.stsci.edu/browse/JP-2671)
Closes a portion of #7223 
This PR adds var_flat to the slit.py model, which appears to have been unintentionally omitted. The products after the cal files now contain valid var_flat values.
=> JP-2671 Update slit model to include var_flat

jwst/tweakreg/tweakreg_step.py
This is a simple PR to replace a print statement in the tweakreg step with a `log.info()`. IMO no changelog is need but let me know if you want me to update the change log.
=> Use log instead of print in tweakreg

CHANGES.rst, jwst/outlier_detection/outlier_detection_scaled.py
Resolves [JP-3034](https://jira.stsci.edu/browse/JP-3034)
This PR changes the import for several photutils routines, to keep up with changes in the photutils pkg.
=> JP-3034: Change import for photutils CircularAnnulus

CHANGES.rst, jwst/cube_build/src/cube_match_internal.c, jwst/cube_build/src/cube_match_sky_driz.c, jwst/cube_build/src/cube_match_sky_pointcloud.c, jwst/cube_build/src/cube_utils.c
This PR addresses fixes several bugs in how C code used by the cube builder may attempt to deallocate unallocated memory resulting in core dump. This happens when memory allocation fails for one array and then code attempts to deallocate several other arrays never allocated before. Due to this bug a memory allocation error is never raised but instead the whole process exits.
This PR also fixes a bug in `alloc_flux_arrays()` due to which 1 is not returned on memory allocation failure resulting in the code not detecting memory allocation failures.
Help desk issue INC0184892.
=> Fix incorrect deallocation attempts of unallocated memory in cube builder

CHANGES.rst, jwst/associations/tests/helpers.py, jwst/conftest.py
resolves [SCSB-53](https://jira.stsci.edu/browse/SCSB-53)
This PR addresses the Pytest deprecations introduced in 7.2 ahead of the 8.0 release.
=> fix deprecation warnings introduced by Pytest `7.2`

CHANGES.rst, jwst/associations/lib/rules_level2b.py
WIP [JP-2013](https://jira.stsci.edu/browse/JP-2013)
This PR addresses the association creation portion of JP-2013. There were two problems with the rule Asn_Lv2NRSIFUNod:
- Mistakenly other dithers and mosaic tiles were being included in the association
- Leakcals/imprint were not included in assocations
The rule has been modified to
- Include leakcal/imprint exposures
- Limit the science/backgrounds to just the nodded dithers for a particular pointing.
=> JP-2013 Fix NIRSpec IFU NOD background subtract and include leakcal in the Level2 associations

CHANGES.rst, docs/jwst/assign_wcs/main.rst, jwst/assign_wcs/assign_wcs.py, jwst/assign_wcs/assign_wcs_step.py, jwst/assign_wcs/niriss.py, jwst/assign_wcs/tests/test_nircam.py, jwst/assign_wcs/tests/test_niriss.py, jwst/assign_wcs/util.py, jwst/extract_2d/tests/test_grisms.py
Resolves [JP-2921](https://jira.stsci.edu/browse/JP-2921)
Closes #7286 
This PR adds the approximated FITS WCS keywords to WFSS files. The WCS is associated with a corresponding direct image and is NOT the spectral WCS associated with the grism image which is stored, as usual, in the GWCS object.
Regression tests - failures are expected or inherited.
https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/515/
=> JP-2921: Add FITS WCS keywords to WFSS mode

CHANGES.rst, jwst/associations/generate.py, jwst/associations/lib/rules_level2_base.py, jwst/associations/main.py, jwst/regtest/test_associations_sdp_pools.py
Resolves [JP-3028](https://jira.stsci.edu/browse/JP-3028)
This PR addresses an issue found in pre-integration testing by SDP. When the `asn_generate` command is run on both 'o'-level and 'c'-level candidates, often the observation candidates did not get created when they should have been. The issue was a redundant method that was meant to remove Level 2 'c'-level candidates when those candidates are not BACKGROUND candidates. The reprocessing list from those associations were deleted along with the associations. These reprocessing lists contained the necessary info to produce the 'o'-level associations.
=> JP-3028 Do not clobber reprocessing lists when Level 2 rules are operating on 'c' type candidates

.github/workflows/ci.yml
This PR runs the coverage job in parallel; this reduces the execution time of `test-cov` from ~1 hour to ~30 minutes
=> run coverage in parallel

.github/workflows/ci.yml, jwst/jump/tests/test_jump_step.py, setup.cfg, tox.ini
Addresses #7409
related to https://github.com/spacetelescope/stcal/pull/136
This PR runs the tests requiring `opencv` in a separate `toxenv` with `opencv-python` installed, to test whether conditional usage of ellipse construction is handled gracefully.
=> test opencv functionality separately

jwst/regtest/test_nirspec_masterbackground.py, jwst/regtest/test_nirspec_mos_spec2.py
This PR swaps fake data for real in-flight data for a couple of NIRSpec MOS regtests. One is the full calwebb_spec2 pipeline, using a spec2 ASN as input that contains nodded exposures, which allows the background subtraction step to occur. The other processes just a single MOS exposure that has a couple of dedicated bkg slitlets defined and hence is able to exercise the master_background_mos step. All input/truth files have been loaded to Artifactory and have been confirmed to work.
=> Update NIRSpec MOS regtests with flight data

CHANGES.rst, jwst/assign_wcs/util.py
This PR merges `fits_wcsinfo` and `update_fits_wcsinfo` functions (`fits_wcsinfo` introduced in https://github.com/spacetelescope/jwst/pull/7373) into a single function, basically expanding capabilities of the original `update_fits_wcsinfo` function. 
=> Merge the two update_wcsinfo functions into one

CHANGES.rst, jwst/tweakreg/tests/test_multichip_jwst.py, setup.cfg
This PR fixes a unit test failure in `tweakreg` step and pins `tweakwcs=0.8.1`.
https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/521/
=> Pin tweakwcs version to 0.8.1 and update tweakreg unit test

CHANGES.rst, docs/jwst/user_documentation/reference_files_crds.rst
Resolves [JP-3040](https://jira.stsci.edu/browse/JP-3040)
This PR addresses an issue where references to the CRDS PUB server have reappeared in the documentation. This PR removes those references.
=> remove references to pub server

CHANGES.rst, jwst/cube_build/ifu_cube.py
Resolves [JP-3043](https://jira.stsci.edu/browse/JP-3043)
Closes #
This PR addresses a bug for NIRSpec IFU when trying to select the wavelength ranges to make the IFU cube. The code was not using these parameters for NIRSpec data. 
=> JP-3043 user option to select wavelength range of IFU cube not working for NIRSpec 

jwst/regtest/test_miri_coron3.py
Partially resolves [JP-2928](https://jira.stsci.edu/browse/JP-2928)
This PR updates the MIRI coron3 regression test (test_miri_coron3) to use in-flight data. All input and truth files have been uploaded to artifactory and run successfully locally.
=> JP-2928: Update MIRI coron3 test with flight data

CHANGES.rst, jwst/regtest/test_nirspec_brightobj.py, jwst/regtest/test_nirspec_fs_spec2.py, jwst/regtest/test_nirspec_fs_spec3.py
Partially resolves [JP-2928](https://jira.stsci.edu/browse/JP-2928)
Closes #
This PR updates the NIRSpec fixed slit regression tests for spec2 and spec3 pipelines to use in-flight data.
EDIT: added BOTS regtest update.
=> JP-2928: Update regtests to use flight data (NRS_FS)

jwst/regtest/test_niriss_ami3.py
Partially resolves [JP-2928](https://jira.stsci.edu/browse/JP-2928)
This PR updates the test_niriss_ami3 regtest module to use recent in-flight data as input. Note that the `test_ami_average_with_sizes` test is no longer needed, because the one main test now also covers the case where dithering of the target and/or psf source(s) leads to outputs of different sizes that need to be averaged. All new input and truth files have been uploaded to artifactory and the new tests pass when run locally.
=> JP-2928: Update NIRISS AMI3 regtest with flight data

.github/workflows/ci.yml, tox.ini
Closes #7383 
This PR addresses the issue raised in #7383 
=> changes for `tox>=4.0` release

CHANGES.rst, jwst/imprint/imprint_step.py
Resolves [JP-3081](https://jira.stsci.edu/browse/JP-3081)
This PR ensures that for an imprint to be subtracted from either a background or science image the observation number and dither position number must match.
=> JP-3081 NIRSpec Imprints improvement - constrain by observation number

CHANGES.rst, jwst/associations/lib/dms_base.py, jwst/associations/lib/rules_level2_base.py, jwst/associations/lib/rules_level2b.py, jwst/associations/lib/rules_level3.py, jwst/associations/lib/rules_level3_base.py, jwst/associations/main.py, jwst/associations/tests/test_main.py, jwst/regtest/test_associations_sdp_pools.py
Resolves [JP-3079](https://jira.stsci.edu/browse/JP-3079)
This PR addresses the issue that not all imprint exposures that should be associated with science exposures were being associated. The bug was that imprints were not being reprocessed so that they can be matched against associations created after the imprints were processed.
=> JP-3079 Ensure all imprint exposures are include in associations

JenkinsfileRT
This PR addresses the issue where MacOS artifacts have not been uploaded since October. The MacOS job was commented out because of an issue where `sed` was not available on `boyle`, which caused the regression tests to hang and fail. The `sed` issue has since been resolved.
=> uncomment MacOS in Jenkins

CHANGES.rst, jwst/lib/set_telescope_pointing.py, jwst/lib/siafdb.py, jwst/lib/tests/test_set_telescope_pointing.py, jwst/lib/tests/test_siafdb.py
Resolves [JP-2821](https://jira.stsci.edu/browse/JP-2821)
This PR addresses an issue where MIRI_TACQ exposures with aperture MIRIM_TAMRS has incorrect CRPIX* calculated. This is because the aperture definition is for a subarray. However, the actual readout includes the full detector, not the subarray. `set_telescope_pointing` is modified to account for this descrepancy. 
=> JP-2821 Correct WCS determination for aperture MIRIM_TAMRS

jwst/datamodels/tests/test_api.py
pytest-xdist can fail if tests get reordered between runners. This can happen when reading packages out of the environment with `pkgutil`. These are used to parameterize the tests, which results in possibly different orderings
`pytest-xdist` can fail if tests get reordered between runners. This can happen when reading packages out of the environment with `pkgutil`. These are used to parameterize the tests for the datamodels API synchronization, which results in possibly different orderings. This is precisely what happens on the machine running our regression tests because there are so many runners used to run the regression tests.
=> Fix the regtests

CHANGES.rst, jwst/transforms/resources/manifests/jwst_transforms-0.7.0.yaml
This reverts commit bf7d3c9bc9d08b56103a68c37444c0f44a7c9edd.
This #7450 was incomplete, and needs to be reworked. See https://github.com/spacetelescope/jwst/issues/7401#issuecomment-1416921842 for details.
=> Revert "Fix typo in SOSS transform schema (#7450)"

CHANGES.rst, jwst/transforms/converters/jwst_models.py, jwst/transforms/converters/tests/data/niriss_soss.asdf, jwst/transforms/converters/tests/test_models.py, jwst/transforms/resources/manifests/jwst_transforms-0.7.0.yaml
Fixes #7401
This PR updates the manifests and the converts so the the niriss soss schema warning issue is resolved. Note that this adds a few tests to ensure the `NirissSOSSModelConverter` is tested outside the regression tests.
This is a follow up to the initially proposed fixes in #7450, which were reverted by #7454.
=> Properly fix niriss soss schema not found warning

CHANGES.rst, jwst/scripts/minimum_deps.py, setup.cfg
Currently the `oldestdeps` job is failing, this likely because the `minimum_deps` script is using `pkg_resources` which is no longer supported. This PR refactors `minimum_deps` to use supported packaging functionality
=> Refactor `minimum_deps` script

CHANGES.rst, jwst/photom/photom.py, jwst/photom/tests/test_photom.py, jwst/pipeline/calwebb_spec2.py
Resolves [JP-3083](https://jira.stsci.edu/browse/JP-3083)
This PR fixes the logic in the photom step that handles NIRSpec fixed-slit data, so that it uses the correct source type for each slit, which was assigned up-stream in the srctype step. This is important, because point sources are left in units of MJy, while extended sources are converted to surface brightness (MJy/sr).
=> JP-3083: Fix photom handling of NRS FS source types

CHANGES.rst, docs/jwst/resample/arguments.rst, jwst/regtest/test_miri_lrs_slit_spec3.py, jwst/resample/resample.py, jwst/resample/resample_spec.py, jwst/resample/resample_spec_step.py, jwst/resample/resample_step.py, jwst/resample/resample_utils.py, jwst/resample/tests/test_resample_step.py
Resolves [JP-3078](https://jira.stsci.edu/browse/JP-3078)
This PR adds``output_wcs`` argument to the ``resample_step`` and ``resample_spec_step`` that allows users to provide their own reference GWCS to the resample step. 
https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/554/
=> JP-3078: Add support custom reference WCS for the resample step

requirements-dev.txt
The JWST Jenkins devdeps build is failing because astropy from master does not build. Following the example in spacetelescope/drizzlepac#1502 this uses the astropy nightly builds
=> Use astropy nightly build in devdeps Jenkins job

setup.cfg
This PR pins `stdatamodels` to `1.0.0`
=> pin `stdatamodels` to new release

CHANGES.rst, docs/jwst/extract_1d/arguments.rst, docs/jwst/extract_1d/description.rst, docs/jwst/references_general/extract1d_reffile.inc, jwst/extract_1d/extract.py
Resolves [JP-3095](https://jira.stsci.edu/browse/JP-3095)
This PR updates the logic in the lower-levels of the extract_1d code to properly handle the various ways the "use_source_posn" can be specified, including command line overrides and from within the extract1d reference file. The previous logic was automatically turning the param on for certain exposure types, such as MIRI MRS and LRS fixed-slit, and NIRSpec IFU and slits, too high up in the code, before the information from the extract1d ref file had been loaded, thus overriding any settings in the ref file (if present). These changes move the logic down lower, so that the automatic override is only applied after the ref file params have been loaded and checked. The new logic how honors the appropriate hierarchy of precedence, in …
=> JP-3095: Fix extract_1d usage of use_source_posn param

CHANGES.rst, jwst/photom/photom.py
Resolves [JP-3084](https://jira.stsci.edu/browse/JP-3084)
Closes #
This PR addresses an inconsistency in how the scalar conversion factor in the `photom` step is passed through various point vs. extended source conditionals, leading to a 2D conversion array stored in `model.slits[i].photom_uniform` not containing a conversion to MJy/sr. 
=> JP-3084: Separate photometric calibration factors for point vs. uniform use

requirements-sdp.txt
Resolves [JP-3109](https://jira.stsci.edu/browse/JP-3109)
https://github.com/spacetelescope/stcal/pull/126 and https://github.com/spacetelescope/stcal/pull/136 made `opencv-python` an optional dependency (as built binaries are not available on all user platforms). This PR adds `opencv-python` to the instructions for creating `requirements-sdp.txt`, to ensure the environment has `opencv-python` installed.
=> include `opencv-python` in instructions to generate SDP requirements

CHANGES.rst, jwst/residual_fringe/residual_fringe.py
Fixes an issue with MRS Residual Fringe crashing on input NaN values (https://jira.stsci.edu/browse/JP-3106) caused by recent merges of https://jira.stsci.edu/browse/JP-3014 and https://jira.stsci.edu/browse/JP-3087
Convert NaN values to zero at the start of this routine, then repopulate as NaN at the end since the Bayesic routines don't handle either NaN or zero well, but there is already infrastructure in place to deal with input zeros.
=> JP-3106: Fix input NaNs in residual fringe

jwst/regtest/test_miri_lrs_slit_spec3.py
This PR fixes the currently flawed logic in the test_miri_lrs_slit_spec3 regression test module. The problem is that the spec3 pipeline is run multiple times on the same input data, using different specifications for how to create the output/combined image WCS, but all of those different runs get saved using the same s2d product file name. That's fine for most of the tests, because most result in a combined image of the same size, but the very last iteration creates a bigger image. When the "okify_regtests" script is used to update truth files, that last s2d file, which is different size, gets used to update the truth files for all tests, leading to subsequent failures. This PR updates the test module to save the result of the last iteration in a different output file, so that it doesn't …
=> Fix logic in MIRI LRS spec3 regtest

CHANGES.rst, jwst/cube_build/src/blot_median.c, jwst/cube_build/src/cube_match_internal.c, jwst/cube_build/src/cube_match_sky_driz.c, jwst/cube_build/src/cube_match_sky_pointcloud.c, jwst/lib/src/winclip.c, jwst/straylight/src/calc_xart.c
Resolves [JP-3086](https://jira.stsci.edu/browse/JP-3086)
Resolves [JP-3128](https://jira.stsci.edu/browse/JP-3128)
This PR fixes memory leaks in C code due to incorrect reference count of returned arrays. This PR addresses a part of #7483 (other improvements in that PR should be merged after that PR is re-based after this PR is merged). Affected packages are: ``cube_build``, ``wfss_contam``, and ``straylight``.
This PR implements the recommendation from https://numpy.org/doc/stable/user/c-info.how-to-extend.html:
> The [Py_BuildValue](https://docs.python.org/3/c-api/arg.html#c.Py_BuildValue) (format_string, c_variables…) function makes it easy to build tuples of Python objects from C variables. **Pay special attention to the difference between ‘N’ and ‘O’ in the format string or you can …
=> JP-3128: Fix memory leaks in C code

CHANGES.rst, jwst/assign_wcs/miri.py, jwst/assign_wcs/tests/test_miri.py
Resolves [JP-3127](https://jira.stsci.edu/browse/JP-3127)
This PR fixes a problem with the computation of the bounding box of a MIRI MRS TSO observation. The bounding box is defined by the shape of the data. The code assumed an MRS observation, the input to assign_wcs is always a 2D image and used the shape of the data array in a simplistic way to determine the bounding box. Since TSO observations are cubes this created very small bounding boxes. Fixed by calling the correct function, `transform_bbox_from_shape`, already available in assign_wcs/utils.py
=> JP-3127: Fix bounding box in MRS TSO observations

CHANGES.rst, docs/jwst/ramp_fitting/appendix.rst, docs/jwst/ramp_fitting/description.rst, jwst/ramp_fitting/ramp_fit_step.py, jwst/ramp_fitting/tests/test_ramp_fit.py
Resolves [JP-3029](https://jira.stsci.edu/browse/JP-3029)
Closes #
This PR calculates a readnoise variance that can be used by the resampling step, using UNDERSAMP-groups that have been flagged by the undersampling_correction step.   This PR supersedes PR #7443, which will be closed.
=> (JP-3029) Update ramp fitting to calculate separate readnoise variance

CHANGES.rst, jwst/tweakreg/tests/test_multichip_jwst.py, jwst/tweakreg/tweakreg_step.py
Resolves [JP-3129](https://jira.stsci.edu/browse/JP-3129)
`tweakreg_step` has code that "validates" the fit by checking that corrections (as measured by the change of the positions of image boundary vertices before and after WCS corrections) are smaller than `10*tolerance`. This is wrong check since valid corrections can be larger than `10*tolerance` since usually the magnitude of corrections is dependent on `searchrad` parameter as well and usually `searchrad >> tolerance`. Any correction smaller than `searchrad` but larger than `10*tolerance` is a valid correction when `use2dhist=True`. Alternatively, `xoffset` and `yoffset` can determine the magnitude of corrections. magnitude of corrections. The origin of the factor `10` in `10*tolerance` is unexplained too.
This PR combines the two …
=> JP-3129: Fix WCS correction validation

CHANGES.rst, jwst/pipeline/calwebb_detector1.py
Resolves [JP-3141](https://jira.stsci.edu/browse/JP-3141)
Closes #
This PR adds a call to the undersampling_correction step to the calwebb_detector1 pipeline.
=> JP-3141: Add undersampling_correction call to calwebb_detector1 pipeline

JenkinsfileRT, JenkinsfileRT_dev
This PR installs the latest commits of `stcal`, `stdatamodels`, ~~and `stpipe`~~ in the Jenkins regression tests
=> regtests: install main branch commit of `stcal` and `stdatamodels`

JenkinsfileRT_dev
This PR fixes the issue where `bc0` was not changed to `bc1`
=> fix MacOS job syntax error

.github/workflows/ci.yml, .github/workflows/ci_cron.yml
This PR abstracts CI workflows to the OpenAstronomy workflows; this should reduce maintenance for updating and maintaining actions. Additionally, these changes move the majority of MacOS jobs to the weekly scheduled workflow. This should alleviate the issue where the limited MacOS runners for the organization are not available for CI jobs.
=> use OpenAstronomy workflows and move MacOS jobs to schedule

CHANGES.rst, jwst/regtest/test_niriss_image.py
Resolves [JP-3138](https://jira.stsci.edu/browse/JP-3138)
Closes #
This PR adds a regression test for niriss image calwebb_detector1 for testing the undersampling_correction  output, and testing the rampfitting output (which contains ramps flagged by the undersampling_correction step ). Documentation for the calwebb_detector1 pipeline will be updated in a separate ticket.
=> (JP-3138) Add regtest for calwebb_detector1 for undersampling correction

CHANGES.rst, jwst/associations/lib/rules_level2_base.py, jwst/regtest/test_associations_sdp_pools.py
Resolves [JP-3147](https://jira.stsci.edu/browse/JP-3147)
This PR addresses and issue with coronographic observations found while investigating JWSTDMS-770 and documented in JP-3147. The issue is that the PSF observations Level 2 associations were not including their linked background observations. Technically, this is because PSF Image 2 associations were being processed by the rule {{Asn_Lv2ImageSpecial}}, which specifically disallows background candidates.
The solution is that, for Level 2 associations, PSF observations can be treated as normal science, which is handled by the rule {{Asn_Lv2Image}}. This is done by changing the exposure type from "psf" to "science". …
=> JP-3147 Treat PSF exposures as science for Level 2 association processing

CHANGES.rst, jwst/extract_1d/extract.py
Resolves [JP-3159](https://jira.stsci.edu/browse/JP-3159)
Closes #
This PR edits the surface brightness unit strings so that astropy.units can parse them properly.
=> JP-3159: Update surface brightness unit strings for astropy unit parsing

CHANGES.rst, jwst/tweakreg/tweakreg_catalog.py, jwst/tweakreg/tweakreg_step.py
Resolves [JP-3148](https://jira.stsci.edu/browse/JP-3148)
This PR simply adds a try/except block to the tweakreg step code where it attempts to build source catalogs for each input image. This addresses situations where something goes wrong in the source catalog generation (e.g. all pixels flagged as bad, etc.), preventing it from completing successfully. Instead of aborting with an error, it now emits a warning and just skips the rest of the tweakreg step. The subsequent pipeline steps can proceed without it.
=> JP-3148: Trap source catalog errors in tweakreg

JenkinsfileRT
This PR uses Python 3.9 in the normal regression tests, just to make sure the regtests match the environment in OPS which currently uses Python 3.9
=> use Python 3.9 in non-devdeps regression tests

CHANGES.rst, jwst/lib/set_telescope_pointing.py
Resolves [JP-3101](https://jira.stsci.edu/browse/JP-3101)
Closes #
This PR addresses TARG_RA and TARG_DEC values of 0.0 for pure parallel observations without target information, resulting in poor MAST observation placement. This PR fills TARG_{RA/DEC} values with {RA/DEC}_REF values if the target values are 0.0.
=> JP-3101: Fill TARG_RA/DEC with RA/DEC_REF if empty at end of set_telescope_pointing

CHANGES.rst, jwst/tweakreg/tweakreg_step.py
Fixes a crash in the tweakreg step when aligning a single image (due to which relative alignment is skipped) and the attempt to align to Gaia fails due to not having enough sources in the Gaia catalog overlapping with the input image.
Resolves [JP-3160](https://jira.stsci.edu/browse/JP-3160)
=> JP-3160: Fix a crash on absolute catalog alignment failure

CHANGES.rst, docs/jwst/jump/arguments.rst
Resolves [JP-3126](https://jira.stsci.edu/browse/JP-3126)
Closes #
This PR clarifies the text in the ReadTheDocs for the arguments in the jump step, and corrects typos.
=> (JP-3126) Clarify text in Jump docs

CHANGES.rst, jwst/cube_build/src/cube_dq_utils.c
Resolves _N/A_ 
Closes #6466, closes #6905
Related: #5578, https://github.com/spacetelescope/crds/issues/790#issuecomment-1261891494
This replaces two variable length array declarations that are preventing Microsoft CL from succeeding. (Refer to #6466 above.)
I tested locally with:
- Windows 10 Pro
- MSVC 2022
- Mambaforge
```
$ pytest -rsv jwst/cube_build/
============================= test session starts ==============================
platform linux -- Python 3.10.9, pytest-7.2.2, pluggy-1.0.0
crds_context: jwst_1064.pmap
rootdir: /home/jhunk/Downloads/omg/jwst, configfile: setup.cfg
plugins: asdf-2.14.3, requests-mock-1.10.0, openfiles-0.5.0, doctestplus-0.12.1, cov-4.0.0, ci-watson-0.6.1, jwst-1.9.5.dev37+g73135ae5b.d20230313
collected 16 items …
```
=> Windows: MSVC: Allocate wave_slice_dq array using mem_alloc_dq()

CHANGES.rst, jwst/resample/resample.py
Closes #7514
This PR addresses a small bug in the output error arrays, that in MIRI data these will often include the coronagraph observations even if this is not included in the output science array
=> Use correct bits in resample_variance_array

setup.cfg
Resolves [JP-3166](https://jira.stsci.edu/browse/JP-3166)
This PR addresses the following warnings in coverage tests:
```
2023-04-03 10:15:22,990 - stpipe - WARNING - /data1/jenkins/workspace/RT/JWST/miniconda/envs/tmp_env0/lib/python3.9/site-packages/coverage/report.py:113: CoverageWarning: Couldn't parse '/data1/jenkins/workspace/RT/JWST/clone/test_outputs/popen-gw11/test_nirspec_missing_msa_fail0/jwst_nirspec_fflat_0017.rmap': No source for code: '/data1/jenkins/workspace/RT/JWST/clone/test_outputs/popen-gw11/test_nirspec_missing_msa_fail0/jwst_nirspec_fflat_0017.rmap'. (couldnt-parse)
coverage._warn(msg, slug="couldnt-parse")
2023-04-03 10:15:22,990 - stpipe - WARNING - /data1/jenkins/workspace/RT/JWST/miniconda/envs/tmp_env0/lib/python3.9/site-packages/coverage/report.py:113: …
```
=> omit data files from coverage tests

jwst/assign_wcs/tests/test_nirspec.py, jwst/background/tests/test_background.py, jwst/resample/tests/test_resample_step.py, jwst/residual_fringe/tests/test_configuration.py
Resolves [JP-3164](https://jira.stsci.edu/browse/JP-3164)
Closes #
This PR removes some unnecessary xfails in the unit tests, and fixes one test to run properly.
=> JP-3164: Fix some xfails that are no longer necessary

jwst/skymatch/region.py, jwst/skymatch/skyimage.py, jwst/skymatch/skymatch.py, jwst/skymatch/skymatch_step.py, jwst/skymatch/skystatistics.py
This PR simply addresses PEP8 issues and also comments out `_calc_sky_orig` function (I just do not have time at this moment to test whether this code can be safely restored. I will do this later but I want to keep it here for convenience.)
I expect no changes to any tests. Most PEP8 issues were line length.
Regression test is running here: https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/636/
=> Cleanup skymatch code and fix PEP8 issues

jwst/ramp_fitting/tests/test_ramp_fit.py
Resolves [JP-3164](https://jira.stsci.edu/browse/JP-3164)
Closes #
This PR addresses a partial resolution of JP-3164 for ramp fitting CI tests.  There were skipped tests in JWST that are already handled in STCAL, so they are unneeded duplicates.
=> JP-3164: Removing tests that are already handled in STCAL or are unneeded.

CHANGES.rst, setup.cfg
`pytest-openfiles` has been deprecated and is interfering with the use of fixtures in our test code (ones that handle files). This PR switches `ResourceWarnings` into errors which will catch almost all cases of files left open. The only cases it does not catch is if an open file handle is assigned to a global variable as the "warning" will not be emitted until python stops running, which occurs after pytest has completed.
Similar to spacetelescope/romancal#666
=> Remove pytest-openfiles

CHANGES.rst, jwst/photom/photom.py
Resolves [JP-3156](https://jira.stsci.edu/browse/JP-3156)
Closes #
This PR addresses an inconsistency noted between PHOTMJ photom scalar conversion units and the unit labels in the spec_table output for NIRISS SOSS data. To keep the units consistent across exposure types, the correction applied here is to the labels, to consistently store spectral point-source data in units of MJy rather than Jy.
=> JP-3156: Fix SOSS-specific spec_table unit labels

jwst/skymatch/skymatch_step.py
This PR enables memory saving code in the `skymatch` step first introduced in https://github.com/spacetelescope/jwst/pull/6874. Unfortunately, I do not think that the pipeline allows steps to pass ASN file names as inputs and outputs and so that memory-saving code was disabled in https://github.com/spacetelescope/jwst/pull/6922.
Unfortunately, the way the code was disabled does not allow for the memory-saving code to be covered by unit tests.
This PR allows enabling this code at the time of step object initialization but it is still disabled by default and there is no step argument to enable it. However, this change allows unit testing and experimental usage of this feature for development purpose. …
=> Enable memory saving code in skymatch

jwst/assign_wcs/tests/test_nircam.py, jwst/regtest/test_nircam_image.py
Partially resolves [JP-2928](https://jira.stsci.edu/browse/JP-2928)
Partially resolves [JP-3164](https://jira.stsci.edu/browse/JP-3164)
Closes #
This PR removes some unnecessary xfails in unit testing, and it updates NIRCam imaging regression tests to use in-flight data.
=> JP-3164 & JP-2928: Update unit and regression tests

CHANGES.rst, JenkinsfileRT, setup.cfg
`codecov` was yanked from PyPi the morning of April 12, 2023. This is causing installs for testing `jwst` to fail. This PR is an attempt to fix that.
- [N/A] ~updated or added relevant tests~
- [N/A] ~updated relevant documentation~
- [N/A] ~added relevant milestone~
- [N/A] ~Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)~
=> Remove `codecov` dependency

JenkinsfileRT, JenkinsfileRT_dev
MacOS regression tests have numerical differences from the Linux ones; additionally, the Boyle Jenkins machine is currently unstable.
- [N/A] ~added entry in `CHANGES.rst` within the relevant release section~
- [N/A] ~updated or added relevant tests~
- [N/A] ~updated relevant documentation~
- [N/A] ~added relevant milestone~
- [N/A] ~Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)~
=> disable MacOS regression tests on Jenkins

JenkinsfileRT
This PR addresses the discrepancies in truth files from the change in #7544 ; it appears that using an additional call to `pip install -r requirements-sdp.txt` within the build command is a valid workaround for the previously stated issue.
- [N/A] added entry in `CHANGES.rst` within the relevant release section
- [N/A] updated or added relevant tests
- [N/A] updated relevant documentation
- [N/A] added relevant milestone
- [N/A] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)
=> re-add latest-commit installs of stdatamodels and stcal

JenkinsfileRT, JenkinsfileRT_dev
Resolves [SCSB-63](https://jira.stsci.edu/browse/SCSB-63)
This PR addresses the issue where override requirements were overridden themselves during the Jenkins regression test build.
- [N/A] ~added entry in `CHANGES.rst` within the relevant release section~
- [N/A] ~updated or added relevant tests~
- [N/A] ~updated relevant documentation~
- [N/A] ~added relevant milestone~
- [N/A] ~Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)~
=> SCSB-63 inject dependency overrides after build

JenkinsfileRT, JenkinsfileRT_dev
Currently the regression test log shows installs after the `pip freeze`. This makes it so that it is difficult to determine the dependency state for the actual regression tests.
This PR adds a `pip list` to output a nicely formatted pip environment table as part of running the actual tests.
=> List pip environment prior to running regression tests

CHANGES.rst, docs/jwst/pipeline/calwebb_spec2.rst, docs/jwst/pixel_replace/arguments.rst, docs/jwst/pixel_replace/index.rst, docs/jwst/pixel_replace/main.rst, docs/jwst/pixel_replace/reference_files.rst, docs/jwst/references_general/references_general.rst, jwst/lib/suffix.py, jwst/pipeline/calwebb_spec2.py, jwst/pixel_replace/__init__.py, jwst/pixel_replace/pixel_replace.py, jwst/pixel_replace/pixel_replace_step.py, jwst/pixel_replace/profile_fitting.py, jwst/reset/tests/test_reset_sub.py, jwst/step.py, jwst/stpipe/integration.py
Resolves [JP-3005](https://jira.stsci.edu/browse/JP-3005)
Closes #
This PR implements an algorithm to estimate values for flagged DO_NOT_USE pixels before spectral extraction takes place. The algorithm creates a median profile from neighboring slices in the dispersed 2d spectrum, then scales the median profile to slice with a bad pixel to estimate its value.
WORK IN PROGRESS: Currently implemented for ImageModel inputs (LRS-FS, others?), and possibly working for MultiSlitModels as well. Testing and coding in progress.
=> JP-3005: Pixel replacement for flagged pixels before spectral extraction

CHANGES.rst, jwst/assign_wcs/pointing.py, jwst/assign_wcs/util.py, jwst/datamodels/container.py, jwst/model_blender/blender.py, jwst/outlier_detection/outlier_detection.py, jwst/outlier_detection/outlier_detection_ifu.py, jwst/outlier_detection/outlier_detection_scaled.py, jwst/outlier_detection/outlier_detection_spec.py, jwst/pipeline/calwebb_image2.py, jwst/resample/resample_spec.py, jwst/stpipe/core.py
Closes #
This PR addresses an issue with data model inheritance. Models inheriting from `stdatamodels.jwst.DataModel` do not register as instances of `DataModel`. For example `isinstance(SlitModel(), stdatamodels.jwst.datamodels.DataModel` returns `False`. Since `stdatamodels.jwst.datamodels.DataModel` is deprecated n favor of `stdatamodels.jwst.datamodels.JwstDataModel` I've replaced any occurrence of `DatModel` with `JwstDataModel`. 
regression tests: https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/695/
=> Fix inheritance of data models

CHANGES.rst, jwst/tweakreg/tweakreg_step.py
Closes #7577
This PR fixes a bug in the `tweakreg` step that would result in a `TypeError` when user enables custom catalogs and uses ASN file name as input.
Thanks @dkmagee for reporting the bug and proposing a solution which is implemented in this PR!
=> Fix a bug in tweakreg when using user catalogs with ASN file name inputs

.github/workflows/ci.yml, .github/workflows/ci_cron.yml
This PR uses the new `pytest-results-summary` keyword in the OpenAstronomy reusable workflow to display test summaries on the job page. Here is an example from https://github.com/spacetelescope/romancal/pull/691:
If tests fail, the [`test-summary` action](https://github.com/marketplace/actions/testforest-dashboard) will create a Markdown table of failures:
- [N/A] ~added entry in `CHANGES.rst` within the relevant release section~
- [N/A] ~updated relevant documentation~
- [N/A] ~added relevant milestone~
- [N/A] ~ran regression tests, post a link to the Jenkins job below.
[How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)~
- [N/A] ~Make sure the JIRA ticket is [resolved …
=> add a table of failing unit tests to the CI workflow summary page

CHANGES.rst
While composing the public release notes for B9.2 I noticed a number of errors in the change log. Some were dramatic (e.g. changes being listed under the wrong release version), while others are just updates for clarity and grammar.
=> Fix errors in change log

CHANGES.rst, docs/jwst/cube_build/main.rst, docs/jwst/photom/main.rst, jwst/extract_1d/ifu.py, jwst/photom/photom.py
Resolves [JP-3163](https://jira.stsci.edu/browse/JP-3163)
Closes #
This PR changes the photom step for NIRSpec IFU point source data to save it in units of surface brightness (MJy/sr). This change was made because cube_build was designed to work in surface brightness units. The extract_1d step for NIRSpec IFU point source data also had to be updated to convert the extracted data from surface brightness units to flux units.
https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/704/
=> JP- 3163 nirspec for Point Source data saved in surface brightness 

jwst/regtest/test_miri_dark.py
Supports the resolution of [JP-3111](https://jira.stsci.edu/browse/JP-3111)  The actual code updates that resolves JP-3111 are in https://github.com/spacetelescope/stcal/pull/165
This PR adds a regression test that runs the dark_current step on a MIRI segmented exposure, to verify that the proper integration-dependent dark frames are applied to the science data. The example segmented exposure is the 3rd segment in a larger series and hence tests whether the last available integration from the dark reference file is applied to all integrations in the science segment.
=> JP-3111: Add MIRI segmented dark subtraction test

CHANGES.rst, jwst/cube_build/cube_build_io_util.py, jwst/cube_build/ifu_cube.py, jwst/cube_build/instrument_defaults.py
Resolves  part 2 of [JP-3047](https://jira.stsci.edu/browse/JP-3047) (Homogenize the use of the wavemin/wavemax parameters defining output cubes between MIRI and NIRSpec. ....NIRSpec to use cubepar to define default wavelength ranges.)
Closes #
NOTE an update to stdatamodels (#162) is required to be merged before this PR is merged. Stdatamodels PR 162 updated the NIRSpec cubepar data model to read in 3 wavelength arrays when the drizzle weighting method is used. In order to use this updated stdatamodels the requirement in the jwst package that stdatamodels could be higher than 1.4.0 was removed from
requirements-max.txt
Also **before this PR can be merged** the new NIRSpec cubepars reference file need to delivered to CRDS.
This PR modifies cube_build to use data from the cubepars …
=> JP-3047 Change how NIRSpec wavelengths are set in ifucube

CHANGES.rst, jwst/srctype/srctype.py, jwst/srctype/tests/test_srctype.py
Resolves [JP-3098](https://jira.stsci.edu/browse/JP-3098)
Closes #
This PR changes the order of the precedence of the rules for setting the src_type for 'MIR_LRS-FIXEDSLIT', 'MIR_LRS-SLITLESS', 'MIR_MRS', 'NRC_TSGRISM', 'NRS_FIXEDSLIT', 'NRS_BRIGHTOBJ', 'NRS_IFU']. The SRCTYPE has precedence over the PATTTYPE. 
=> JP-3098 switch order of precedence between PATTTYPE and SRCTYAPT in the srctype step

CHANGES.rst, jwst/background/background_sub.py
Resolves [JP-3234](https://jira.stsci.edu/browse/JP-3234)
Closes #
This PR addresses a bug in the calculation of the mean background value when NaN values are present.
=> JP-3234: Mask NaN values for background subtraction of "robust mean"

CHANGES.rst, jwst/tweakreg/tests/test_utils.py, jwst/tweakreg/utils.py
Resolves [JP-3227](https://jira.stsci.edu/browse/JP-3227)
This PR adds functionality similar to HST's `tweakback` task to be able to transfer an alignment solution from a file to another.
=> JP-3227: Add analog of HST's tweakback tool

CHANGES.rst, jwst/tweakreg/tests/test_utils.py, jwst/tweakreg/utils.py
This PR is a follow up to #7573. It imports data models from stdatamodels.
It increases one variable name by 2 characters to improve readability.
=> fix import in tweakback

CHANGES.rst, jwst/assign_wcs/nirspec.py, jwst/assign_wcs/tests/test_nirspec.py, jwst/associations/tests/test_mkpool.py, jwst/outlier_detection/tests/test_outlier_detection.py, jwst/residual_fringe/tests/test_background_fit.py
jwst downstream tests have been failing in stdatamodels because of numerous `pytest.PytestUnraisableExceptionWarning` warnings as a result of `ResourceWarning` warnings from unclosed files.
https://github.com/spacetelescope/stdatamodels/actions/runs/5215436542/jobs/9412973900
jwst does not currently convert these `PytestUnraisableExceptionWarning` warnings into errors but the warnings can be seen in the log files for CI runs:
https://github.com/spacetelescope/jwst/actions/runs/5157043601/jobs/9288891837#step:10:169
The changes in this PR are mostly to tests to close opened files but also includes a minor change to `get_open_msa_slits` to close a file prior to raising an exception.
This does not address all of the warnings as some are due to code in stdatamodels. A corresponding …
=> close files in tests and before raising exception in get_open_msa_slits

CHANGES.rst, jwst/flatfield/flat_field_step.py
Resolves [JP-3229](https://jira.stsci.edu/browse/JP-3229)
This PR updates the handling of log messages for reporting the reference file(s) used by the step. Previously, a user-supplied ref file was not report at all, and CRDS ref files were only reported at the debug level. Now all ref files are reported at info level.
=> JP-3229: <Fix a bug> added the user-supplied flat reference file to the log

JenkinsfileRT, JenkinsfileRT_dev
analogous to https://github.com/spacetelescope/romancal/pull/711#pullrequestreview-1462883026
> Currently the `pip freeze` happens after the initial dependency install, but before the `OVERRIDE_REQUIREMENTS` option is handled by Jenkins. This makes it difficult to see if Jenkins has successfully installed an overriden requirement for the test run. This PR adds an additional `pip list` (same as `pip freeze` just more nicely formatted as a table) after the `OVERRIDE_REQUIREMENTS` are applied so that one can check in the Jenkins job log to make sure overriden requirements have successfully installed.
=> [CI] run `pip list` after installing override requirements in Jenkins

CHANGES.rst, jwst/flatfield/flat_field_step.py
Reverts spacetelescope/jwst#7592
Rats! I *knew* we should've run regression tests before merging this, but I assumed that simple changes to logging would be safe. Shame on me!
Line 109 in flat_field_step.py needs to be changed to include a format specifier, i.e.
`self.log.info('Using flat field reference file: %s', flat_ref_file)`
otherwise it results in a crash.
=> Revert "JP-3229: <Fix a bug> added the user-supplied flat reference file to the log"

CHANGES.rst, jwst/flatfield/flat_field_step.py
Resolves [JP-3229](https://jira.stsci.edu/browse/JP-3229)
This PR updates the handling of log messages for reporting the reference file(s) used by the step. Previously, a user-supplied ref file was not report at all, and CRDS ref files were only reported at the debug level. Now all ref files are reported at info level.
=> JP-3229: update ref file logging in flat_field step

CHANGES.rst, jwst/pixel_replace/pixel_replace_step.py
Resolves [JP-3268](https://jira.stsci.edu/browse/JP-3268)
This PR fixes the `pixel_replace` step code so that it properly updates the step status keyword on completion. Previously a data model object was being updated that was not the model returned from the step, so the update was lost.
=> JP-3268: Fix pixel_replace step status error

docs/conf.py, docs/jwst/user_documentation/datamodels.rst
Remove comment that made it's way into the data models docs and link to the now published stdatamodels docs.
Addresses comment: https://github.com/spacetelescope/jwst/issues/7656#issuecomment-1611746940
Fixes: [JP-3280](https://jira.stsci.edu/browse/JP-3280)
Link to updated datamodels docs built with this PR: https://jwst-pipeline--7657.org.readthedocs.build/en/7657/jwst/user_documentation/datamodels.html#jwst-datamodels
=> fix stdatamodels datamodels link in documentation

CHANGES.rst, docs/getting_started/quickstart.rst, docs/jwst/associations/overview.rst, docs/jwst/model_blender/main.rst, docs/jwst/stpipe/user_step.rst, docs/jwst/user_documentation/datamodels.rst
It appears https://github.com/spacetelescope/jwst/pull/7657 was incomplete as while looking at other docs I found another broken link to and malformed comment about stdatamodels. I believe this PR should fix all the broken links and erroneous comments.
=> fix more missing links to stdatamodels docs

CHANGES.rst, docs/jwst/extract_2d/main.rst
Resolves [JP-3254](https://jira.stsci.edu/browse/JP-3254)
Closes #7654 
This PR updates the docs for the extract_2d step, in particular the sections that describe the details of how WFSS grism object lists are created, modified, and used to extract sources from a WFSS image. It fixes some inconsistencies in the existing write up and adds some additional descriptions of some of the details, to hopefully make it more clear for users.
=> JP-3254: Update extract_2d docs for WFSS

CHANGES.rst, jwst/scripts/adjust_wcs.py, jwst/tweakreg/utils.py
Resolves [JP-3285](https://jira.stsci.edu/browse/JP-3285)
This PR fixes a bug in the `adjust_wcs` _script_ that would prevent setting angles to negative numbers in the engineering format (a limitation of `argparse`). This PR also adds support for units for angles. For example, now the scrpt can be invoked like this:
```
adjust_wcs in_file.fits -f out_file.fits --overwrite -r 1.2 arcsec -d -4.5e-6 -s 1.0001
```
When angle units are not provided (as for the DEC angle correction above), the angles are still assumed to be in degrees.
Finally, this PR adds functions from the `tweakreg.utils` module to the `__all__` variable thus publishing the docstrings of these functions in the `jwst` documentation. …
=> JP-3285: Allow negative angles in engineering format. Add support for angle units

CHANGES.rst, docs/jwst/associations/association_reference.rst, docs/jwst/associations/overview.rst
While looking through the associations docs I found a few minor formatting typos.
overview misconfigured code-block:
- before: https://jwst-pipeline.readthedocs.io/en/latest/jwst/associations/overview.html#usage
- after: https://jwst-pipeline--7694.org.readthedocs.build/en/7694/jwst/associations/overview.html#usage
misconfigured doctest-skip:
- before: https://jwst-pipeline.readthedocs.io/en/latest/jwst/associations/association_reference.html#rule-registration
- after: https://jwst-pipeline--7694.org.readthedocs.build/en/7694/jwst/associations/association_reference.html#rule-registration
=> Fix some minor formatting typos in associations docs

CHANGES.rst, setup.cfg
This PR removes the mistune dependency (and pin).
This pin appears to have been added to deal with sphinx-asdf 0.1.1 not pinning mistune and a new version of mistune being released which broke the docs.
https://github.com/spacetelescope/jwst/pull/6490
The pin was also added to sphinx-asdf 0.1.2 so bumping the minimum version of sphinx-asdf 0.1.2 means the mistune pin is no longer needed in jwst. This PR increases the minimum version of sphinx-asdf to 0.1.2
Removing this pin allows sphinx-asdf 0.2.0 to be installed which removes many of the deprecated call warnings when building the docs.
As can be seen by comparing this docs build log for this PR
https://readthedocs.org/projects/jwst-pipeline/builds/21213123/
to a build log for a PR where sphinx-asdf<0.2.0 is used: …
=> remove mistune pin and increase minimum sphinx-asdf version

.github/workflows/ci.yml, jwst/lib/tests/test_siafdb.py, requirements-dev.txt, tox.ini
Related to [SCSB-69](https://jira.stsci.edu/browse/SCSB-69)
This PR ensures that `scipy`, and `numpy` are all tested with the latest `pre` wheels
[How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)~
=> test against pre-built binaries of `scipy` and `numpy`

CHANGES.rst, docs/jwst/refpix/arguments.rst, docs/jwst/refpix/description.rst, jwst/refpix/irs2_subtract_reference.py, jwst/refpix/refpix_step.py, jwst/refpix/tests/test_rm_intermittent_badpix.py
This PR resolves a potential crash due to an empty list. Also added a factor to mitigate the overcorrection due to suspicious intermittently bad reference pixels.
=> Refpix bug fix

CHANGES.rst, jwst/flatfield/tests/test_flatfield.py
The `test_flatfield_step_interface` was unskipped in https://github.com/spacetelescope/jwst/pull/7615 right before the frequent but unpredictable failures for FlatField.
This test modifies `FlatFieldStep.reference_file_types` (and does not undo the modification). Subsequent tests (in the same process) that use `FlatField` may fail (and not consider f/s/dflats) which would explain the errors seen in regression tests following the merge of the above changes.
This minimal regression test run (2 tests in one process) will hopefully help to explain the error:
https://plwishmaster.stsci.edu:8081/blue/organizations/jenkins/RT%2FJWST-Developers-Pull-Requests/detail/JWST-Developers-Pull-Requests/799/tests
The order of tests was controlled so that `test_flatfield_step_interface` was called prior to …
=> Modify `test_flatfield_step_interface` step to not interfere with other tests

CHANGES.rst, jwst/datamodels/__init__.py, jwst/scripts/move_wcs.py, jwst/scripts/schemadoc.py
[stdatamodels.jwst.datamodels.schema](https://github.com/spacetelescope/stdatamodels/blob/master/src/stdatamodels/jwst/datamodels/schema.py) is an out-of-date duplicate of [stdatamodels.schema](https://github.com/spacetelescope/stdatamodels/blob/master/src/stdatamodels/schema.py). Uses of the stdatamodels.jwst.datamodels.schema were converted to stdatamodels.schema and the automatic shadowing of stdatamodels.jwst.datamodels.schema to jwst.datamodels.schema was removed.
**This removes jwst.datamodels.schema from the api.**
Regression tests run at: https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/794/
=> remove uses of stdatamodels.jwst.datamodels.schema

CHANGES.rst, jwst/resample/gwcs_drizzle.py, jwst/resample/resample.py, jwst/resample/resample_utils.py
Resolves [JP-3317](https://jira.stsci.edu/browse/JP-3317)
Closes #7761
Resample step has two branches: one for resampling of the science image (SCI extension in the FITS file) and one for resampling error and variance arrays (ERR, VARIANCE_* extensions). The logic in the branch for processing the science image ignores the bounding box from the input images' WCS while the logic for processing ERR, VAR* arrays does take it into account.
Both science and error images should be processed (resampled) using the same limits for input image pixels.
This PR solves this issue by using the same algorithm for computing resample limits (in input image coordinates) to science, error, and variance arrays from input image shape and input WCS' bounding box.
[Regression test …
=> JP-3317: Use same logic for resample limits for SCI, ERR, and VAR* images

CHANGES.rst, jwst/pipeline/calwebb_spec2.py
Resolves [JP-3320](https://jira.stsci.edu/browse/JP-3320)
This PR addresses a bug reported by users setting pixel_replace to run and save results - this caused the default file_cal.fits output to go missing, as a result of incorrect ordering inside calwebb_spec2. This fixes the issue by running pixel_replace before setting metadata and suffix name for the datamodel that the pipeline returns.
=> Run pixel_replace before finalizing cal output in calwebb_spec2

docs/rtd_environment.yaml
Readthedocs is attempting to build the docs with a version of sphinx_rtd_theme from 2019 (version 0.4.3).
This PR updates the readthedocs environment to require a newer version (>1.2.0).
=> require min version of sphinx_rtd_theme for readthedocs

setup.cfg
This PR resolves an issue in the regression test build where the build fails upon attempting to build `pymssql`, which is part of the `sdp` dependency extra, as seen here: https://plwishmaster.stsci.edu:8081/blue/organizations/jenkins/RT%2FJWST/detail/JWST/2500/pipeline#step-125-log-371
=> remove `pymssql` dependency from `sdp` to resolve build issues

CHANGES.rst, docs/jwst/outlier_detection/outlier_detection.rst, jwst/outlier_detection/outlier_detection.py, jwst/resample/resample.py
This PR addresses very long, redundant file names in `outlier_detection` intermediate products which appears to be a bug in the call to `Step.make_output_path()` with the arg `basename` is used instead of `basepath`.  Currently, blot produces files from standard science associations by default with names like:
```
jw02234-o010_20230627t013403_image3_00001_asn_o010_jw02234010001_02101_00001_nrcalong_blot.fits
jw02234-o010_20230627t013403_image3_00001_asn_o010_jw02234010001_02101_00001_nrcblong_blot.fits
jw02234-o010_20230627t013403_image3_00001_asn_o010_jw02234010001_02101_00002_nrcalong_blot.fits
jw02234-o010_20230627t013403_image3_00001_asn_o010_jw02234010001_02101_00002_nrcblong_blot.fits
jw02234-o010_20230627t013403_image3_00001_asn_o010_jw02234010001_02101_00003_nrcalong_blot.fits …
```
=> Fix outlier blot filenames

CHANGES.rst, jwst/residual_fringe/fitter.py, jwst/residual_fringe/utils.py
While looking at the regression tests. I noticed that `test_residual_fringe_cal` is one of the slower tests.
Running just that test took ~2566 seconds:
https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/817
Profiling the test locally revealed that the majority of the time is spent in 2 functions:
- [new_fit_1d_fringes_bayes_evidence](https://github.com/spacetelescope/jwst/blob/7556988f110205042334d00c1c9d351c4bfb7773/jwst/residual_fringe/utils.py#L572)
- [fit_1d_background_complex](https://github.com/spacetelescope/jwst/blob/7556988f110205042334d00c1c9d351c4bfb7773/jwst/residual_fringe/utils.py#L391C5-L391C30)
This PR aims to improve the second function `fit_1d_background_complex` by:
- replacing the [ChiSqOutlierRejectionFitter](https://github.com/spacetelescope/ …
=> use scipy directly instead of astropy modeling for residual fringe fit

CHANGES.rst, jwst/pathloss/pathloss.py, jwst/pathloss/tests/test_pathloss.py
Resolves [JP-3323](https://jira.stsci.edu/browse/JP-3323)
Closes #7781 
This PR fixes an error in the interpolation method for point source pathloss corrections.  The bilinear weights for the pixels to the top and right of the base pixel were accidentally swapped.  This PR brings the bilinear interpolation into agreement with other implementations (e.g. scipy.interpolate.griddata).
=> JP-3323: Fix pathloss bilinear interpolation coefficients

CHANGES.rst, jwst/assign_wcs/nirspec.py, setup.cfg
I noticed the CI fail on the main branch due to likely a ruff update (which caused a new E721 rule violation due to a comparison using a type instead of use of `isinstance`) and the oldest deps failing (due to the asdf dependency, jsonschema, updating).
This PR switches the type comparisons to calls to `isinstance` and increases the lower asdf version to 2.14.4.
=> CI fixes: Replace type comparison with isinstance and increase lower pin for asdf

jwst/regtest/test_nircam_image.py
This PR fixes a problem in the way the Detector1 and Image2 pipelines were being called back-to-back in the NIRCam imaging mode regtest. The Image2 test was doing a call to `get_data()` on the rate file created by the Detector1 test, so instead of using the output rate file created by Detector1, it was pulling an old version of the rate file from Artifactory. D'oh. The modification no longer call `get_data()` for that file, but just uses the file already sitting in the working directory.
=> Fix NIRCam imaging regtest

CHANGES.rst, jwst/lib/tests/test_engdb_tools.py
The test_environmental test when not run on the vpn will fail to contact the alternative engineering database server. This results in the test taking ~10 minutes waiting for a response before turning into a skip.
This commit adds some lines of code that were removed in PR #3022 which changed the skip from a decorator to a pytest.skip when the exception/timeout occurs. This should allow the test to skip quickly when the host is not accessable (and instead skips in <1 second). The pytest.skip call during the except block is left to deal with cases when the host resolves but the url fails to resolve.
As the alternative host appears unresponsive for github CI runs (which run tests in parallel with 2 workers) this should free up one of the workers that without this PR sits waiting for ~10 …
=> re-add quick check for alternative engineering database test

CHANGES.rst, jwst/associations/lib/rules_level3.py, jwst/associations/lib/rules_level3_base.py
Resolves [JP-3232](https://jira.stsci.edu/browse/JP-3232)
Closes #7730 
This PR adds an override for the construction of the level-3 product name for NIRCam coronagraphic associations that are to be processed as regular imaging, i.e. through the image3 pipeline. The data are also processed as a coron3 ASN, which previously resulted in identical "i2d" level-3 product names being created: one from coron3 and one from image3. This update breaks the file name degeneracy by simply adding the additional suffix "-image3" to the optical element field of the product name for the data processed as regular imaging.
=> JP-3232: Fix NRC coron duplicate product names

jwst/regtest/test_associations_sdp_pools.py
This PR removes the XFAIL setting in the asn regtests for the program jw00016 pool, now that JP-3230 and JP-3232 have been completed. The first regtest run will result in differences, which can then be okified.
=> Remove regtest XFAIL for fixed ASN rule

CHANGES.rst, jwst/assign_wcs/assign_wcs.py, jwst/assign_wcs/util.py
Resolves [JP-3343](https://jira.stsci.edu/browse/JP-3343)
Closes #7820 
This PR addresses a help desk inquiry regarding missing FITS SIP approximations for a NIRSpec TAcq image. These values were not filled during assign_wcs because the bounding_box was never defined. This PR is an experiment to see if saving a bounding box to imaging WCS objects of size {data.shape}, when one does not already exist, will break things.
=> JP-3343: Add bounding_box to imaging WCS objects without one

CHANGES.rst, jwst/associations/lib/dms_base.py, jwst/associations/lib/rules_level2b.py
Resolves [JP-3151](https://jira.stsci.edu/browse/JP-3151)
Closes #7775 
This PR updates the spectroscopic level-2 ASN rules used for NIRSpec IFU exposures to exclude exposures using filter/grating combos that are known to produce no data on the NRS2 detector, so that they don't get any level-2b processing.
=> JP-3151: Don't make Lv2 ASNs for empty NRS2 exposures

CHANGES.rst, docs/jwst/jump/arguments.rst
Resolves [JP-3090](https://jira.stsci.edu/browse/JP-3090)
Closes #7840 
This PR addresses the missing argument descriptions in the documentation of the jump step.
=> JP-3090: Jump parameters missing from documentation

jwst/pixel_replace/pixel_replace.py
This PR addresses a linting warning from `ruff`.
=> fix false comparison

CHANGES.rst, jwst/extract_2d/tests/test_grisms.py
This PR addresses changes to test results after NIRCam WFSS transforms were updated - some source positions have moved on/off detector, altering the expected traces found and extracted during testing.
=> Fix grism tests after transforms update

CHANGES.rst, jwst/associations/lib/diff.py, jwst/associations/lib/prune.py, jwst/associations/lib/tests/test_diff.py
Resolves [JP-3356](https://jira.stsci.edu/browse/JP-3356)
This PR addresses resolves an issue found during regression testing of another PR.
The issue is that the success/failure of an association difference check is dependent on the
order of the associations. This PR resolves that bug while refactoring/removing redundant code.
=> JP-3356 Remove order dependency on association diffing

jwst/regtest/test_miri_mrs_tso.py
Related to [JP-3359](https://jira.stsci.edu/browse/JP-3359)
This PR updates the MIRI MRS TSO regression test to temporarily skip the MRS time-dependent correction in the photom step of the spec2 pipeline, because that algorithm can't handle 3D MRS data right now. Previously, the test had been working OK, because the DATE-OBS in the input file was pre-flight, such that an old photom ref file was used, which did not contain the time-dependent corrections, so no error occurred. This, however, allowed that error to get through our B9.3 testing and into operations. So I've updated the DATE-OBS in the test input file to use the most recent ref files, which will trigger the error, until it gets fixed by JP-3359. …
=> Update MIRI MRS TSO regtest

.readthedocs.yaml
RTD no longer supports any `system_packages` setting:
https://blog.readthedocs.com/drop-support-system-packages/
=> remove unsupported system_packages from rtd config

CHANGES.rst, jwst/photom/miri_mrs.py
This PR fixes the issue documented in https://jira.stsci.edu/browse/JP-3359 where the MRS time-dependent correction crashes for TSO mode data.
Resolves [JP-3362](https://jira.stsci.edu/browse/JP-3362)
Closes #7872 
=> JP-3362: Fix MRS time dependent correction for TSO

CHANGES.rst, docs/jwst/jump/arguments.rst, jwst/jump/jump_step.py, jwst/jump/tests/test_jump_step.py, setup.cfg
This PR allows the new maximum_cores values to be accepted to be able to pass the value to the STCAL jump.py routine. Read_the_docs was updated to match the new options. 
=> Jump step num cores doc update

jwst/regtest/test_miri_mrs_tso.py
Now that #7869 has been merged, which fixes a bug in the application of the time-dependent flux correction to MIRI MRS data taken in TSO mode, that correction can be turned back on the MRS TSO regression test.
Updated test runs locally without crashing, but of course results in differences in final outputs.
=> Re-enable photom correction in MIRI MRS TSO regtest

JenkinsfileRT
Related to [DADSJWST-2059](https://jira.stsci.edu/browse/DADSJWST-2059?jql=text%20~%20%22python%203.11%22)
This PR tells the `RT JWST` job to use Python 3.11
=> use Python 3.11 in regtests

CHANGES.rst, jwst/associations/lib/lv2_v1_to_v2.py, jwst/associations/tests/notebooks/lv2_v1_to_v2.ipynb, jwst/scripts/make_header.py, setup.cfg
jsonschema was previously installed by asdf and stdatamodels. However, jsonschema is used directly for association processing. This commit adds jsonschema as a dependency by listing it in setup.cfg.
Closes #
=> add jsonschema to setup.cfg

jwst/regtest/test_nirspec_ifu_spec3.py, jwst/regtest/test_nirspec_ifu_spec3_emsm.py
This PR splits the 2 tests contained in test_nirspec_ifu_spec3 into separate test moduels, so that they can run in parallel. This is the longest running module in the entire regtest fleet (~1hr:50min)
=> Split NRS IFU spec3 regtest in two tests

CHANGES.rst, JenkinsfileRT, docs/jwst/extract_1d/arguments.rst, jwst/assign_wcs/assign_wcs.py, jwst/assign_wcs/miri.py, jwst/extract_1d/extract.py, jwst/master_background/tests/test_master_background.py
Resolves [JP-3244](https://jira.stsci.edu/browse/JP-3244)
Resolves [JP-3245](https://jira.stsci.edu/browse/JP-3245)
Closes #7677
Closes #7681 
This PR addresses extraction region issues for NIRSpec modes by utilizing source_xpos/ypos metadata to center the extraction region.
=> JP-3244: Use source_{x,y}pos for NRS_FIXEDSLIT and NRS_MSASPEC

JenkinsfileRT, JenkinsfileRT_dev
This PR tests setting `pytest -n auto` to `pytest -n 4` in the regtests, to see if that fixes the recent threading / out of memory issues
=> reduce the parallelism of xdist in the regtests

CHANGES.rst, docs/jwst/user_documentation/running_pipeline_python.rst
This PR fixes an error the docs regarding the name of the ramp_fitting module. Reported by a user via Help Desk ticket INC0193177.
=> Fix ramp_fit reference in docs

JenkinsfileRT, JenkinsfileRT_dev
In the midst of all the issues with the Jenkins regtest jobs, #7796 set the python version back to 3.9 for RT test runs. This reverts that change, so that python 3.11 is used.
=> Reset python back to 3.11 for JenkinsRT

jwst/refpix/reference_pixels.py
Resolves [JP-3372](https://jira.stsci.edu/browse/JP-3372)
This PR addresses a typo found in a log statement.
=> JP-3372: Fix typo in refpix log statement

CHANGES.rst, jwst/pixel_replace/pixel_replace.py
Resolves [JP-3366](https://jira.stsci.edu/browse/JP-3366)
Closes #7878 
This PR addresses a bug in the pixel replacement code that prevented successful replacement for pixels with extremal values, i.e. lying on the core of the spectral trace. The fitting procedure implicitly included a fit to a normalization value of 1, which is not correct if the fitted profile is missing its extremal value.
=> JP-3366: Apply fit to normalized profile before rescaling

CHANGES.rst, docs/jwst/extract_1d/arguments.rst, jwst/extract_1d/extract.py, jwst/extract_1d/extract_1d_step.py, jwst/extract_1d/ifu.py
Resolves [JP-3355](https://jira.stsci.edu/browse/JP-3355) and Resolves [JP-3340](https://jira.stsci.edu/browse/JP-3340)
Closes #7846 and #7815
This PR allows the user to override the srctype and perform POINT source extraction for IFU data. 
https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/962/
=> JP-3355 added parameter to extract 1d to override srctype and  use point source extraction 

CHANGES.rst, jwst/extract_1d/extract_1d_step.py, jwst/regtest/test_miri_mrs_extract1d.py, jwst/regtest/test_miri_mrs_spec3.py
Fix a bug in JP-3355 that does not check the input model type. 
Closes #
This PR addresses the fact that the Level-3 s3d product passed to extract_1d is actually a modelcontainer of s3d cubes, hence we need to pull out the meta.exposure.type from the first model in the container (all the s3d will be from the same instrument exp type). 
https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/968/
=> Check input mode type for JP-3355 extract_1d options 

CHANGES.rst, jwst/lib/set_telescope_pointing.py, jwst/lib/tests/data/test_from_models_mast.ecsv, jwst/lib/tests/data/test_over_time_mast.ecsv, jwst/lib/tests/test_engdb_mock.py, jwst/lib/tests/test_v1_calculate.py
Resolves [JP-3424](https://jira.stsci.edu/browse/JP-3424)
Closes #7963 
This PR addresses an issue discovered during Build 10.0 integration with WCS determination in set_telescope_pointing. A new algorithm for the various guider products has been implemented, which require more engineering coverage than science exposures. Turns out that not enough leeway being given. This PR extends the coverage time to use when retrieving engineering data.
- ~updated relevant documentation~
=> JP-3424 Extend engineering coverage time for guiding modes

CHANGES.rst, jwst/outlier_detection/outlier_detection.py, jwst/outlier_detection/outlier_detection_step.py
Resolves [JP-3422](https://jira.stsci.edu/browse/JP-3422)
Closes #7959 
This PR addresses another intermediate file not properly cleaned up by `outlier_detection` if `save_intermediate_results` is set to False. The median file has a variable output name, depending on if the step resamples the data or not. If resampling occurs, the name is not constructed from an input model filename but a drizzled model. 
=> JP-3342: add median file to outlier_detection cleanup block

CHANGES.rst, jwst/assign_wcs/nirspec.py, jwst/assign_wcs/tests/test_nirspec.py, jwst/wavecorr/tests/test_wavecorr.py
Resolves [JP-3365](https://jira.stsci.edu/browse/JP-3365)
Closes #7877 
This PR addresses edge effects in resampling MOS slit cutouts by adding a couple extra pixels of WCS coverage at the top and bottom of each slit.
=> JP-3365: Increase MOS cutout margin

CHANGES.rst, jwst/lib/set_telescope_pointing.py, jwst/lib/tests/data/add_wcs_default_acq1.fits, jwst/lib/tests/test_set_telescope_pointing.py
Resolves [JP-3431](https://jira.stsci.edu/browse/JP-3431)
Closes #7981 
This PR addresses the issue that if WCS information for guiding modes cannot be determined from engineering, that no default information is saved to the exposure. The basic information that is found from engineering are the CRPIX values. If they cannot be determined, CRPIX are set to 0.
- ~updated relevant documentation~
=> JP-3431 Ensure that default WCS information is set for Guiding modes that fail pointing determination

CHANGES.rst, jwst/flatfield/flat_field.py, jwst/flatfield/tests/test_combine_fast_slow.py
Resolves [JP-3429](https://jira.stsci.edu/browse/JP-3429)
Closes #7973 
This PR updates flat propagation methods to account for 1D errors from fast variation components. This is needed to support upcoming NIRSpec flats, which will include errors on the 1D F-flats.  Missing errors are handled as zero-error components, so these changes should be backwards-compatible.
=> JP-3429: Flat error propagation

CHANGES.rst, jwst/flatfield/flat_field.py
Resolves [JP-3350](https://jira.stsci.edu/browse/JP-3350)
Closes #7834 
For NIRSpec data, any new DO_NOT_USE pixels generated during the flat field process are set to NaN. This addresses a cosmetic issue, where data that has not been flat-fielded is many orders of magnitude higher than data that has been corrected.  The pixels are already ignored in further processing, but can be confusing to look at in intermediate data products.
=> JP-3350: Set all DO_NOT_USE pixels to NaN after flat field

CHANGES.rst, jwst/associations/lib/rules_level3.py, jwst/associations/tests/test_level3_basics.py, jwst/associations/tests/test_level3_spectrographic.py
Resolves [JP-3308](https://jira.stsci.edu/browse/JP-3308)
Closes #7739 
This PR addresses a calwebb_tso3 crash when processing a TSO3 association from a group candidate, which attempted to combine two observations. The formation of the int_times table is not currently feasible for observation combinations, leading to failure. This PR prevents the creation of assocations combining TSO observations to avoid the failure.
=> JP-3308: Prevent creation of level 3 TSO group associations

CHANGES.rst, docs/jwst/pipeline/calwebb_spec2.rst, docs/jwst/pixel_replace/main.rst
Resolves [JP-3433](https://jira.stsci.edu/browse/JP-3433)
Closes #7985 
This PR implements the minor docs updates requested in the referenced JP ticket.
=> JP-3433: pixel_replace doc updates

CHANGES.rst, docs/jwst/references_general/filteroffset_reffile.rst
Resolves [JP-3430](https://jira.stsci.edu/browse/JP-3430)
Closes #7975 
This PR makes updates to the FilterOffset ref file docs, as requested in JP-3430.
=> JP-3430: Updates for FilterOffset docs

CHANGES.rst, jwst/cube_build/cube_build_step.py, jwst/cube_build/data_types.py, jwst/cube_build/file_table.py, jwst/cube_build/tests/test_cube_build_step.py
asdf previously had a bug where contents from a closed file could be accessed. See:
https://github.com/asdf-format/asdf/issues/1539
The cube build step was relying on this bug, closing models before the wcs was fully read (this is lazy loaded).
This commit prevents the early model closure. A unit test (using fake `nirspec` data) is added that replicates the issue and passes with the changes in this PR.
=> keep cube build input models open to allow reading wcs

CHANGES.rst, jwst/refpix/irs2_subtract_reference.py, jwst/refpix/tests/test_clobber_ref.py
Resolves [JP-3440](https://jira.stsci.edu/browse/JP-3440)
Closes https://github.com/spacetelescope/jwst/issues/8008
This PR reverts a change associated with JP-3321, PR 7745, setting two additional detector columns next to bad reference pixels to zero.  Depending on the bad reference pixel location, the additional columns set to zero might have been adjacent interleaved reference pixels, or might have been science data.  If science data, the effect is clear in the rate files: the affected data appear as bad rows with near-zero values.
=> JP-3440: Revert change clobbering extra pixels near bad reference pixels

CHANGES.rst, setup.cfg
asdf 3.0 is compatible with jwst and is released on pypi and conda forge
This PR increases the asdf upper pin to `4` as asdf follows semantic versioning and all `3.x` releases will be backwards compatible.
Regression tests run with no errors: https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1014/
=> increase asdf upper pin

jwst/jump/tests/test_detect_jumps.py
As seen in the CI run for a recent PR (and for others at seemingly random times):
https://github.com/spacetelescope/jwst/actions/runs/6562032419/job/17823126182?pr=8010#step:10:182
the `test_exec_time_0_crs` test fails due to a seemingly slow github mac runner:
```
>       assert t_elapsed < MAX_TIME
E       assert 18.11580204963684 < 10
```
This PR updates the test to:
- use [time.monotonic](https://docs.python.org/3/library/time.html#time.monotonic)
- increase the threshold to 60 seconds for mac osx runners on github (which sets the `CI` environment variable)
=> allow for slow github mac runners

.github/workflows/ci.yml
Github actions requesting python `3.x` (which is often the default for reusable workflows) now use python 3.12 instead of python 3.11. This is impacting the `check` jobs:
https://github.com/spacetelescope/jwst/blob/59c853ce59cd4eade004a3aa90cdcc84d4c9e661/.github/workflows/ci.yml#L47-L53
This PR updates the reusable workflow defining a `default_python` of 3.11.
Additionally, this PR adds a python 3.12 run to the CI (which is expected to fail in part because of the current scipy pin):
https://github.com/spacetelescope/jwst/blob/59c853ce59cd4eade004a3aa90cdcc84d4c9e661/setup.cfg#L44
https://github.com/spacetelescope/jwst/pull/8033 is a start at testing if removing the pin is problematic.
As this PR only modifies github actions configuration regression tests were not run.
**Checklist for …
=> Fix CI for `3.x` now using python 3.12 and add python 3.12 tests to CI

JenkinsfileRT, JenkinsfileRT_dev
This PR updates the jenkins configuration files to limit what files are considered for uploading during the `Upload artifacts` step. The changes here are the same as those applied in this romancal PR:
https://github.com/spacetelescope/romancal/pull/950
If/when jwst adds `astroquery` (or `webbpsf` which depends on `astroquery`) the jenkins runs will fail on the `Upload artifacts` step due to searching files beyond those that are generated when attempting to upload test results to artifactory. This search will fail due to finding the [mission_results.json](https://github.com/astropy/astroquery/blob/5add2e3b0ff5b56630840a0f57196c19054f5c01/astroquery/mast/tests/data/mission_results.json#L5) file in the astroquery package.
This PR limits the files searched to those generated during the pytest …
=> limit regression test result search to jwst files

CHANGES.rst, docs/jwst/resample/arguments.rst, jwst/model_blender/blendmeta.py, jwst/resample/gwcs_drizzle.py, jwst/resample/resample.py, jwst/resample/resample_spec.py, jwst/resample/resample_step.py, jwst/resample/tests/test_resample_step.py
Resolves [JP-3035](https://jira.stsci.edu/browse/JP-3035)
Closes #7668
Closes #7390
This PR re-designed how resample computes photometric keywords `PIXAR_*` as well as corrects image data so that the flux of the resampled image (when image intensity is multiplied by PIXAR_SR) matches the flux of the input image. In my brief testing on NIRCAM images, flux error could have been up to 1.6% using previous computations and now it is down to about 0.005% (difference between the computed flux in the input and output images).
This required undoing some of the changes made in #5389.
I expect a large number of regression (and some unit) tests to fail due to this PR. I will will deal with failing unit tests in next commits.
This PR also allows some additional info to be passed with custom …
=> JP-3035: Fix computation of the photometric keywords PIXAR_* and scale resampled intensities according to actual pixel scale ratio.

.github/workflows/ci.yml, CHANGES.rst, setup.cfg
jwst cannot yet support python 3.12 due to an upper pin on scipy:
https://github.com/spacetelescope/jwst/blob/7f1c5cadabd8890aa535116ba46592a44ea7b662/setup.cfg#L44
This is proving problematic to remove in part due to different output from `scipy.signal.medfilt` (see: https://github.com/spacetelescope/jwst/pull/8033).
This PR removes python 3.12 support and the consistently failing python 3.12 CI job (which fails to install and produces no additional useful output) to make reviewing other changes easier.
A follow-up PR (possibly #8033) will add python 3.12 support. If this PR is approved and merged a tracking issue will be opened for adding python 3.12 support.
[How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression …
=> drop python 3.12 support

jwst/scripts/okify_regtests.py
This PR attempts to address an issue in `okify_regtests` where the Jfrog query crashes the server process with a 500 error.
=> use `--props` instead of `--build` in `okify_regtests`

CHANGES.rst, jwst/tweakreg/tests/test_tweakreg.py, jwst/tweakreg/tweakreg_step.py
Resolves [JP-3442](https://jira.stsci.edu/browse/JP-3442)
Closes #8011
The code used to create group names in tweakreg fails when input models have file names of different lengths (see help desk ticket INC0194239 for more details). This PR addresses this usage and also improves how edge cases are handled.
=> JP-3442: Improve image group name construction

README.md
This PR follows from https://github.com/spacetelescope/jwst/pull/8042, and attempts to warn/instruct users to specify a python version when creating a fresh environment. Environment generation will default to python 3.12, which will fail to install jwst. This should be reverted when https://github.com/spacetelescope/jwst/pull/8042 is reverted. Suggestions on better wording are welcome.
=> Add warning in README regarding python 3.12

CHANGES.rst, jwst/resample/resample_utils.py
Resolves [JP-3457](https://jira.stsci.edu/browse/JP-3457)
Numpy 2.0 now raises exceptions when values do not fit in the min/max range for the destination type (i.e., converting Python's `-1` `int` to `np.uint32`).
=> Numpy 2.0 compat: signed/unsigned conversion in context and mask utilities

CHANGES.rst, jwst/extract_1d/soss_extract/atoca_utils.py
Resolves [JP-3451](https://jira.stsci.edu/browse/JP-3451)
Closes #8037 
This PR addresses regression test errors for NIRISS SOSS after a recent delivery of updated reference files. This fix allows the difference calculation inside the bad dispersion direction method to see zero-valued pixels, which will allow it to overwrite them before throwing an error.
=> JP-3451: Include zero-valued pixels in difference calculation

CHANGES.rst, docs/index.rst, docs/jwst/user_documentation/reference_files_crds.rst
Resolves [JP-3466](https://jira.stsci.edu/browse/JP-3466)
This PR removes all the in-line notifications about the CRDS PUB server. The server has not been available for over a year; there is no more reason for the in-your-face notifications.
However, for historical and the one potential user that may still have used it, the notification notice itself has been left in the index, though moved to the last position.
- ~updated or added relevant tests~
=> JP-3466 Remove the CRDS PUB notices througout the documentation

CHANGES.rst, jwst/source_catalog/source_catalog.py
This PR makes the source catalog meta data flexible for planned changes of the version key name in `photutils`.  Note that I reverted the key name change in `photutils` (https://github.com/astropy/photutils/pull/1652) so that it does not affect the pipeline.  However, I will re-apply it for the the 1.11.0 release.
I did not add a changelog entry because this is not a user-facing change.
=> Make meta data flexible for photutils changes

CHANGES.rst, docs/jwst/extract_2d/main.rst, jwst/extract_2d/nirspec.py
Resolves [JP-3223](https://jira.stsci.edu/browse/JP-3223)
Closes #7865
This PR addresses a crash of Spec2 when the parameter slit_name was provided as integer for MOS data. The pipeline now expects a string for this value, and the extract_2d code will make the corresponding value type conversions to make sure that both values in the comparison are the same type. 
The documentation was modified to explain that for MOS data the value is expected as a string, e.g. slit_name='67'
=> JP-3223: Extract_2d 'slit_name' parameter fails for NRS_MSASPEC slits

CHANGES.rst, jwst/extract_1d/ifu.py
Resolves [JP-3469](https://jira.stsci.edu/browse/JP-3469) by replacing a nanmedian calculation with a numpy masked median calculation.
=> JP-3469: Replace nanmedian with masked array median in ifu_autocen

CHANGES.rst, jwst/associations/association.py, jwst/scripts/migrate_data.py, jwst/stpipe/tests/test_config.py
The PR replaces uses of `utcnow` to avoid `DeprecationWarning` messages seen in python 3.12:
```
/home/runner/work/jwst/jwst/jwst/associations/association.py:567: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
timestamp = datetime.utcnow().strftime(
```
See this run log for more details:
https://github.com/spacetelescope/jwst/actions/runs/6723984874/job/18275278424?pr=8033
Regression tests running at: https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1059/
[How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches …
=> replace utcnow to avoid deprecation warnings in python 3.12

CHANGES.rst, docs/conf.py, docs/jwst/mrs_imatch/index.rst, docs/jwst/mrs_imatch/mrs_imatch_step.rst, docs/jwst/skymatch/index.rst, docs/jwst/skymatch/region.rst, docs/jwst/skymatch/skyimage.rst, docs/jwst/skymatch/skymatch.rst, docs/jwst/skymatch/skymatch_step.rst, docs/jwst/skymatch/skystatistics.rst, docs/jwst/tweakreg/astrometric_utils.rst, docs/jwst/tweakreg/index.rst, docs/jwst/tweakreg/tweakreg_catalog.rst, docs/jwst/tweakreg/tweakreg_step.rst, docs/jwst/tweakreg/utils.rst, jwst/tweakreg/astrometric_utils.py
Resolves [JP-3471](https://jira.stsci.edu/browse/JP-3471)
Closes #8085
This PR adds a custom `AttributeDocumenter` subclass to control the formatting of the long `Step.spec` string in the sphinx documentation.
For one example see the OutlierDetectionStep spec:
https://jwst-pipeline.readthedocs.io/en/latest/api/jwst.outlier_detection.OutlierDetectionStep.html#jwst.outlier_detection.OutlierDetectionStep.spec
and with this PR:
https://jwst-pipeline--8101.org.readthedocs.build/en/8101/api/jwst.outlier_detection.OutlierDetectionStep.html#jwst.outlier_detection.OutlierDetectionStep.spec
To update the formatting outside of `api` a few uses of `automodule` are replaced with `automodapi`:
- tweakreg: https://jwst-pipeline--8101.org.readthedocs.build/en/8101/jwst/tweakreg/index.html
- skymatch: …
=> JP-3471 improve Step.spec attribute formating in docs

.gitignore, CHANGES.rst, jwst/__init__.py, jwst/associations/pool.py, pyproject.toml
Currently, JWST makes use of the long deprecated (since python 3.3) module `pkg_resources`. This module was officially removed for Python 3.12+ by python/cpython#98040. This PR removes all remaining uses of `pkg_resources` from JWST, replacing the version generation with `setuptools_scm` generating a hidden python file during install, which is the standard practice for using a git tag/commit versioned python project now.
=> Remove the use of `pkg_resources`

CHANGES.rst, jwst/photom/miri_imager.py, jwst/photom/photom.py, jwst/photom/tests/test_photom.py
Resolves [JP-3455](https://jira.stsci.edu/browse/JP-3455)
Closes #8048 
This PR is related to proposed changes to the PHOTOM step for the MIRI Imager (and coronographs). We add a time-dependent correction to the PHOTOM value.
=> JP-3455: Updated MIRI imager photom step

CHANGES.rst, docs/jwst/photom/main.rst, docs/jwst/references_general/photom_reffile.inc, jwst/photom/photom.py
Related to [JP-3455](https://jira.stsci.edu/browse/JP-3455)
This PR fixes a bug introduced in #8096 , where the photom correction for MIRI imaging data was mistakenly applied twice to the data arrays. It was applied first right after finding the matching row of data in the ref file table, and then again after determining whether the time-dependent correction existed or not. This PR eliminates the first application and leaves only the one after the check for time-dep coeffs. It still gets applied exactly once, regardless of whether or not the time-dep coeffs exist.
=> JP-3455: Fix bug in new MIRI imager photom correction

README.md, jwst/lib/suffix.py, jwst/nsclean/lib.py
This PR fixes a failing unit test, due to the recent addition of the new "nsclean" step.
=> Fix suffix list test for new nsclean step

CHANGES.rst, jwst/pixel_replace/pixel_replace.py
Closes #
This PR addresses a bug found with recent MIRI LRS reference file deliveries - a row of pixels filled with NaN values but DQ=0 causes a crash. This should catch that issue and pass on replacing pixels from that row.
=> Pixel Replace - catch profiles with no valid pixel values

CHANGES.rst, docs/jwst/pathloss/description.rst, jwst/pathloss/pathloss.py
- only for slits with exactly 2 shutters
Resolves [JP-3357](https://jira.stsci.edu/browse/JP-3357)
Closes #
This PR addresses an issue found in testing the original fix in #8106 - the average of 1x1 and 1x3 uniform corrections is only to be done for slits that have exactly 2 shutters, not for slits that have only 1 open shutter adjacent to the fiducial (like for point sources).
=> Fix for 2 shutter uniform correction 

jwst/step.py, jwst/stpipe/integration.py
This PR adds entries for the new emicorr step to a couple of infrastructure files, in order to get unit tests to pass everywhere.
=> Update infrastructure files to include emicorr

jwst/stpipe/tests/test_integration.py
As discussed in #8137 (see https://github.com/spacetelescope/jwst/pull/8137#issuecomment-1857973863)
This PR adds 2 unit tests to:
- confirm that all subclasses of `JwstStep` are listed in `jwst.step.__all__` (except for `JwstPipeline` which is a subclass of `JwstStep`)
- confirm that all subclasses of `JwstPipeline` are listed in `jwst.pipeline.__all__`
~This PR is currently not based of main so this PR can be evaluated for it's ability to catch the omission fixed in #8137 Once this is approved the PR can be rebased prior to merge.~ EDIT: today I learned that `actions/checkout` merges the source PR branch into the target so it doesn't matter that this branch is out-of-date, the tests will still run with the changes in #8137 I opened a test PR …
=> add unit test to confirm step and pipeline __all__

CHANGES.rst, docs/jwst/references_general/emi_reffile.inc, jwst/emicorr/emicorr.py, jwst/emicorr/emicorr_step.py, jwst/emicorr/tests/test_emicorr.py
Resolves [JP-3248](https://jira.stsci.edu/browse/JP-3248)
Closes #
This PR addresses emicorr crashing with readpatt values other than FASTR1 or SLOWR1.
=> JP-3248: MIRI Subarrays 390 Hz EMI bug fix

README.md
This PR adds caveats back into the README, warning users that they need to create an environment using python < 3.12
=> Update README to exclude Python 3.12 from supported versions.

CHANGES.rst, docs/conf.py, pyproject.toml
This PR removes `sphinx-asdf` as a requirement. It's primary purpose is to render asdf schemas in the docs. As jwst no longer contains schemas (those were moved to `stdatamodels`) the requirement for `sphinx-asdf` is no longer needed.
This fixes the current issue where the docs are rendered with a side/navigation menu that does not scroll when it overflows.
=> remove sphinx-asdf requirement

CHANGES.rst, docs/getting_started/install.rst, docs/getting_started/quickstart.rst, jwst/tweakreg/tweakreg_step.py
This PR addresses an issue raised in Help Desk ticket [INC0196726](https://stsci.service-now.com/nav_to.do?uri=incident.do%3Fsys_id=d88e80c49733b15023a2fe971153af66%26sysparm_stack=incident_list.do%3Fsysparm_query=active=true) where there was no mention of the fact that we are currently limited to installing jwst with python<=3.11. So I've updated all the places where "conda create" is mentioned.
=> Update RTD installation instructions

CHANGES.rst, jwst/photom/photom.py
Resolves [JP-3088](https://jira.stsci.edu/browse/JP-3088)
Closes #7792 
This PR was described in JP-3088 as "`exp_to_source` is copying wrong and/or incomplete meta information."  For a multislt data model the model.meta.bunit_data had a different value than model.slit[*].meta.bunit_data. 
This even occurs in the cal file after calspec2.  So I think the issue is related to calspec2.
The multslitmodel is create in extract_2d/nirspec.py:
output_model = datamodels.MultiSlitModel()
output_model.update(input_model)
The slit bunit values are copies of output_model (L95-96) in nirspec.py
new_model.meta.bunit_data = input_model.meta.bunit_data
new_model.meta.bunit_err = input_model.meta.bunit_err
In the photom step the slit bunit values are updated (starting L903) but not the upper datamodel. I …
=> JP-3088 updated bunit_data for the top multislit model

CHANGES.rst, docs/jwst/extract_1d/arguments.rst, jwst/extract_1d/ifu.py
Resolves [JP-3509](https://jira.stsci.edu/browse/JP-3509)
Closes #8193 
This PR addresses JP-3509 by ensuring that only cube wavelengths shortward of 26 microns are used for the IFU autocentroiding.
=> JP-3509: Cut cube collapse for autocentroiding short of 26 microns

pyproject.toml
Related to [JP-3468](https://jira.stsci.edu/browse/JP-3468)
This PR updates the minimum required version of tweakwcs, in order to take advantage of recent bug fixes, in particular the one described in JP-3468.
=> Update min version of tweakwcs to 0.8.6

CHANGES.rst, jwst/cube_build/ifu_cube.py
Helps alert users to cases found in [JP-3517](https://jira.stsci.edu/browse/JP-3517). But it does not resolve [JP-3517]
Closes #
This PR addresses adds a warning message to log is not valid data is on the detector. This indicates that something is wrong with the processing and the user should be warned about  this event. 
=> Add a warning message in Log  to cube_build if not valid data is found on detector

jwst/regtest/conftest.py
pytest 8.0 (the current version) includes a fix:
https://github.com/pytest-dev/pytest/pull/11594
for issue:
https://github.com/pytest-dev/pytest/issues/11282
the `conftest.py` in `jwst/regtest` relied on the above bug:
https://github.com/spacetelescope/jwst/blob/bddb39c6efb2ec949a36398d21819de2abd2118b/jwst/regtest/conftest.py#L27-L30
and with pytest 8 test runs which don't use the options defined in the jwst `pyproject.toml` file result in failures:
```
>           inputs_root = pytestconfig.getini('inputs_root')[0]
E           TypeError: 'NoneType' object is not subscriptable
```
see the full log in stdatamodels: https://github.com/spacetelescope/stdatamodels/actions/runs/7701806178/job/20988725161?pr=253#step:10:172
Although a `pyargs` tox factor is defined for jwst it appears to be …
=> update regtest conftest for pytest 8

jwst/resample/tests/test_resample_step.py
Currently there's a warning when running one of the resample unit tests.
```
$ pytest jwst/resample/tests/test_resample_step.py::test_nirspec_wcs_roundtrip
========================================================== test session starts ===========================================================
platform darwin -- Python 3.12.0, pytest-7.4.4, pluggy-1.3.0
crds_context: jwst_1188.pmap
rootdir: /Users/jdavies/dev/jwst
configfile: pyproject.toml
plugins: ci_watson-0.6.2, asdf-3.0.1, cov-4.1.0, jwst-1.13.4.dev36+g5a0835817, doctestplus-1.1.0, requests-mock-1.11.0, xdist-3.5.0
collected 1 item                                                                                                                         
jwst/resample/tests/test_resample_step.py . …
```
=> Silence resample test warning by using non-zero data

CHANGES.rst, jwst/residual_fringe/utils.py
Resolves [JP-3532](https://jira.stsci.edu/browse/JP-3532) by properly masking zero or negative-valued spectra instead of only zero-valued spectra.
Closes #8260 
=> JP-3532: MRS 1d residual fringe treatment of negative values

CHANGES.rst, docs/jwst/photom/main.rst, jwst/photom/photom.py
Resolves [JP-3247](https://jira.stsci.edu/browse/JP-3247)
Closes #7732 
This PR addresses retrieving the values of PIXAR_A2 and PIXAR_SR from area reference file
instead of photom reference file to avoid missmatching values.
=> JP-3247: Retrieve pixel area from AREA reference file

CHANGES.rst, jwst/datamodels/container.py
`models_grouped` property of a `ModelContainer` should return file names instead of opened models when input are lists of files names under some circumstances. However, due to an incorrect indentation of a `if-block`, `models_grouped` *always* returns a list of opened (loaded in memory) data models.
This PR fixes the above.
=> Fix: models_grouped always return opened data models

jwst/regtest/test_niriss_image.py
This PR modifies the test_niriss_image regtest module to look for the input file in the appropriate folder in artifactory and expands the detector1 test to test the output of all intermediate steps. All necessary input/truth files are in place in artifactory. Ran the new version of the test module locally and all comparisons passed.
=> Fix NIRISS imaging regression test

CHANGES.rst, docs/conf.py, docs/jwst/jump/arguments.rst, docs/jwst/jump/description.rst, docs/jwst/ramp_fitting/appendix.rst, docs/jwst/ramp_fitting/arguments.rst, docs/jwst/ramp_fitting/description.rst
Resolves [JP-3525](https://jira.stsci.edu/browse/JP-3525)
Closes #8248 
This PR makes extensive updates to the organization of the ramp_fitting docs, in order to synch up the information with what's included in stcal/docs. The vast majority of the step info is now in the jwst docs, with only the low-level explanation of core algorithms remaining in stcal/docs. The info in stcal/docs is linked from the jwst/docs using an external reference.
=> JP-3525: Update jump and ramp_fitting docs to merge with stcal docs

jwst/tweakreg/tweakreg_step.py
This PR fixes a bug when using the new `SourceFinder` (via segmentation) starfinder in tweakreg which was added in #8203.  ConfigObj option always returns a string, and that causes problems when one wants options that are ints or floats.  They need to be specifically cast to the correct type.
Another reason to stop using `ConfigObj`.  ;-)
The bug is the following:
```
TweakRegStep.call(files_to_tweak, save_results=True, suffix="cal",
File "/home/jdavies/miniconda3/envs/jwst/lib/python3.11/site-packages/stpipe/step.py", line 653, in call
return instance.run(*args)
^^^^^^^^^^^^^^^^^^^
File "/home/jdavies/miniconda3/envs/jwst/lib/python3.11/site-packages/stpipe/step.py", line 479, in run
step_result = self.process(*args)
^^^^^^^^^^^^^^^^^^^
File …
```
=> Convert tweakreg segmentation connectivity to integer

CHANGES.rst, jwst/extract_1d/apply_apcorr.py
Resolves [JP-3539](https://jira.stsci.edu/browse/JP-3539)
Closes #8282
This PR replaces the deprecated interp2d function with RectBivariateSpline in extract_1d.  This turns out to be the only instance of interp2d in the code base.
[Jenkins run here](https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1223/)
=> JP-3539: replace all instances of deprecated scipy interp2d

CHANGES.rst, jwst/source_catalog/detection.py, jwst/tweakreg/tweakreg_catalog.py
Currently `TweakRegStep` logs lots of warnings like the following:
```
2024-02-26 14:09:45,740 - stpipe.tweakreg - WARNING - /Users/jdavies/miniconda3/envs/jwst-dev/lib/python3.11/site-packages/photutils/background/background_2d.py:273: AstropyUserWarning: Input data contains invalid values (NaNs or infs), which were automatically masked.
2024-02-26 14:09:45,740 - stpipe.tweakreg - WARNING -   warnings.warn('Input data contains invalid values (NaNs or '
2024-02-26 14:09:45,740 - stpipe.tweakreg - WARNING - 
2024-02-26 14:09:46,597 - stpipe.tweakreg - INFO - Detected 106 sources in jw01345002001_14201_00002_nrcalong_cal.fits.
2024-02-26 14:09:46,608 - stpipe.tweakreg - WARNING - /Users/jdavies/miniconda3/envs/jwst-dev/lib/python3.11/site-packages/photutils/background/background_2d.py:273: …
```
=> Suppress warnings about NaNs in input data from TweakRegStep

CHANGES.rst, docs/jwst/refpix/arguments.rst, jwst/refpix/irs2_subtract_reference.py, jwst/refpix/refpix_step.py, jwst/refpix/tests/test_refpix.py
Resolves [JP-3529](https://jira.stsci.edu/browse/JP-3529)
Closes #8254 
This PR allows interleaved reference pixels in NIRSpec IRS2 mode to be preserved in the output from the refpix step.  This is needed for calibration reductions, to produce new bias reference files, but should not be used for science reductions.
=> Add option to preserve reference pixels after IRS2 processing

CHANGES.rst, jwst/pixel_replace/pixel_replace.py
Resolves [JP-3423](https://jira.stsci.edu/browse/JP-3423)
Closes #7960
This PR addresses a bug that would cause crashes when the mingrad algorithm for pixel replacement was applied to NIRSpec data. The error was due to an inappropriate assumption about the input array shape, which was fixed in a single line.
=> JP-3423: fixed array shape mismatch in pixel_replace mingrad algorithm

pyproject.toml
pytest 8.1 broke doctestplus https://github.com/scientific-python/pytest-doctestplus/issues/239
This PR pins pytest to < 8.1 until this (and possibly other plugins: https://github.com/pytest-dev/pytest/issues/12069) can be fixed.
See the recent scheduled run where all jobs fail at pytest plugin registration (and no tests are run):
https://github.com/spacetelescope/jwst/actions/runs/8138291984
=> pin pytest <8.1

CHANGES.rst, jwst/resample/resample.py
This PR repaces `check_memory_allocation` in `resample`.
The replaced function allocates a large array, then measures the size of the array to determine if it's safe to allocate an array of that size. See https://github.com/spacetelescope/stdatamodels/issues/272 for more details.
The replacement instead allocates a small (1x1) array to get the expected dtype then computes the expected size of the upcoming array allocation.
=> replace check_memory_allocation in resample

jwst/lib/basic_utils.py, jwst/resample/resample.py
`resample` uses `bytes2human` from `jwst.lib.basic_utils` which imports this function from `stdatamodels.jwst.library.basic_utils`.
This PR updates the import to get `bytes2human` from stdatamodels directly and removes `bytes2human` and `deprecate_class` from `basic_utils`. These are internal functions that don't occur in `basic_utils.__all__` or the docs. A follow-up PR will deprecate and eventually remove `deprecate_class` from `stdatamodels`.
=> import bytes2human directly from stdatamodels

CHANGES.rst, docs/jwst/resample/arguments.rst, jwst/resample/gwcs_drizzle.py, jwst/resample/resample.py, jwst/resample/resample_step.py, jwst/resample/resample_utils.py, jwst/resample/tests/test_resample_step.py, jwst/resample/tests/test_utils.py
Resolves [JP-3465](https://jira.stsci.edu/browse/JP-3465)
Closes #8073 
This PR adjusts the way exposure time weighting is computed in the resample step to use the new measurement_time keyword from [JP-3449](https://jira.stsci.edu/browse/JP-3449) instead of the exposure time.
[Jenkins job](https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1185/)
=> JP-3465: Use TMEASURE in resample step

CHANGES.rst, jwst/charge_migration/charge_migration.py, jwst/charge_migration/tests/test_charge_migration.py
Resolves [JP-3560](https://jira.stsci.edu/browse/JP-3560)
Closes #8331 
This PR addresses CHARGELOSS flagging.  The original implementation assumed an integration ramp that has a group above the CHARGELOSS threshold will have all remaining groups in the ramp above the CHARGELOSS threshold, so will also get the CHARGELOSS flag.  This is not true.  Additionally, the charge migration step flags nearest neighbors, the four pixels to the north, south, east, and west, with CHARGELOSS in the groups flagged in the ramp of interest.  All subsequent groups in nearest neighbors also need to be flagged with CHARGELOSS and DO_NOT_USE.
The charge migration step has been changed to find the first group in an integration ramp that is above the CHARGELOSS threshold and not flagged as DO_NOT_USE, then it …
=> JP-3560: Updating CHARGELOSS Flagging 

CHANGES.rst, jwst/tweakreg/astrometric_utils.py, jwst/tweakreg/tests/test_amutils.py
Resolves [JP-3541](https://jira.stsci.edu/browse/JP-3541)
Closes #8286 
This PR addresses a bug that caused tweakreg to fail when the bounding box of the input image was too small to find any sources in the GAIA catalog.  This PR ensures that the appropriate warning (Not enough sources (0) in the reference catalog...), which was already implemented, is hit instead, and the step completes successfully.
[Regression test run here](https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1271/).
=> JP-3541: fixed tweakreg step KeyError due to empty gaia catalog

CHANGES.rst, docs/jwst/skymatch/arguments.rst
Resolves [JP-3534](https://jira.stsci.edu/browse/JP-3534)
Closes #8269 
This PR addresses corrects the spelling of the parameter options 'usigma' and 'lsigma'.
=> JP-3534 update to Sky Match docs

jwst/stpipe/utilities.py
Fixes https://github.com/spacetelescope/jwst/issues/8348
`test_suffix.py` tests that call `jwst.stpipe.utilities.find_suffixes` are skipped in unit test runs due to `importorskip` calls in the regtests (like):
https://github.com/spacetelescope/jwst/blob/bf3b06fcefae0baa54c9d9f62243038a06f4254e/jwst/regtest/test_stp_jw00697013.py#L30
`pysiaf` is not installed for CI unit test runs and the call to `find_suffixes` results in an attempt to import every `.py` file in the `jwst` directory structure that is not in a `test` folder (so `regtest` is included). This results in an attempt to import for example the above referenced file, the importorskip is called and the test (in this case one in `test_suffix`) is skipped.
This PR updates the regex to also exclude the `regtest` directory.
As a …
=> update load_local_pkg exclude regex with regtest pattern

jwst/stpipe/tests/test_crds.py, pyproject.toml
The pytest pin added in:
https://github.com/spacetelescope/jwst/pull/8328
can be removed as `pytest-doctestplus` now supports `pytest==8.1.1`
The automated PR that attempted this bump:
https://github.com/spacetelescope/jwst/pull/8346
showed a new failure in one unit test:
```
FAILED jwst/stpipe/tests/test_crds.py::test_crds_step_override - ValueError: Empty filename: None
```
This PR  updates the test to use a fixture instead of `global` variables to allow it to pass.
=> Remove upper pytest pin, switch globals use to fixture in stpipe test

CHANGES.rst, docs/jwst/outlier_detection/outlier_detection_ifu.rst, jwst/outlier_detection/outlier_detection_ifu.py
Resolves [JP-3527](https://jira.stsci.edu/browse/JP-3527)
Closes #8250
This PR updates the IFU outlier docs. I also updated some comments in the ifu_outlier code to make things more clear.
=> JP-3527 Update to docs for IFU outlier detection

CHANGES.rst, jwst/emicorr/emicorr.py
This PR addresses a bug in the emicorr step that was discovered after merging #8270. The bug affected the matching of dataset subarray and readpatt values to ref file entries, which was causing no matching entry to be found and hence the step was skipped.
=> Fix bug in emicorr logic for finding matching ref file info

CHANGES.rst, jwst/ami/instrument_data.py, jwst/assign_wcs/tests/test_schemas.py, jwst/associations/lib/rules_level2_base.py, jwst/background/background_sub.py, jwst/datamodels/tests/test_model_container.py, jwst/extract_1d/apply_apcorr.py, jwst/extract_1d/soss_extract/atoca.py, jwst/extract_1d/soss_extract/soss_centroids.py, jwst/photom/photom.py, jwst/ramp_fitting/ramp_fit_step.py, jwst/regtest/test_nircam_coron3.py, jwst/resample/resample_spec.py, jwst/resample/resample_step.py, jwst/resample/resample_utils.py, jwst/stpipe/tests/test_step.py, jwst/tweakreg/tweakreg_catalog.py, jwst/wfs_combine/wfs_combine.py, pyproject.toml
Resolves [JP-3546](https://jira.stsci.edu/browse/JP-3546)
Closes #8296 
This PR addresses replacing all deprecated code inside jwst, and replacing all instances of warnings.simplefilter("ignore") with more specific warnings like warnings.filterwarnings("ignore", category=RuntimeWarning, message="Divide by zero"). A few other easy-to-fix warnings were also fixed or suppressed.
There were two instances of warnings.simplefilter("ignore") which, when removed, did not create any additional warnings, making it difficult to track down the warnings that the filters were intended to handle.  These were rules_level2_base.py line 565, and photom.py line 476.  These filters were removed; however, it's possible that they should still be there, but the test coverage was inadequate to trip the warnings. …
=> JP-3546: fix deprecations and improve warning filtering

jwst/ami/lg_model.py, jwst/ami/oifits.py, jwst/ami/utils.py
closes #8390 
This PR addresses issues flagged by SonarQube (https://plsonarqube.stsci.edu/project/issues?resolved=false&inNewCodePeriod=true&types=BUG&id=jwst&open=AY54FDbH6KYUncGRZ448)
=> fix issues flagged by SonarQube

CHANGES.rst, jwst/associations/lib/rules_level2_base.py, jwst/associations/lib/rules_level2b.py, jwst/regtest/test_associations_sdp_pools.py
Resolves [JP-3518](https://jira.stsci.edu/browse/JP-3518)
Closes #8215
This PR addresses mismatches between NIRSpec science and imprint members in level2 spectral associations.
=> JP-3518: Match imprint and science association members by mosaic and dither position

CHANGES.rst, jwst/ami/leastsqnrm.py, jwst/extract_1d/soss_extract/atoca.py
Resolves [JP-3589](https://jira.stsci.edu/browse/JP-3589)
Closes #8400
This PR addresses a few loose-end code deprecations from the new AMI suite and from the numpy 2.0 update.
=> JP-3589: fixed deprecated code from numpy 2.0 release

CHANGES.rst, jwst/datamodels/__init__.py
Resolves [JP-3585](https://jira.stsci.edu/browse/JP-3585)
Closes #8382 
This PR enforces removal of the deprecated stdatamodels model types DrizProductModel, MIRIRampModel, and MultiProductModel.  Most of the changes are in stdatamodels; [see PR here](https://github.com/spacetelescope/stdatamodels/pull/171).  On the jwst side, the only change is to remove the model types from the deprecated list.
=> JP-3585: remove deprecated datamodel types

CHANGES.rst, jwst/regtest/test_miri_residual_fringe.py, jwst/residual_fringe/residual_fringe.py
Resolves [JP-3288](https://jira.stsci.edu/browse/JP-3288)
Closes #3937 
This PR adds a check on the DQ array in the residual fringe correction. If the pixel has a value of DO_NOT_USE it is not used in the correction. 
https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1366/
=> JP-3288 use DQ plane in residual_fringe code

CHANGES.rst, docs/jwst/outlier_detection/outlier_detection.rst, jwst/outlier_detection/outlier_detection.py, jwst/outlier_detection/outlier_detection_step.py, jwst/resample/resample.py, jwst/resample/resample_spec.py
This PR adds the association identifier (if available) to filenames used to store `outlier_i2d` products used during outlier detection.
This should partially address an issue that occurs during operations where multiple parallel runs of pipeline use the same working directory (which is used as the output directory). If the parallel runs process the same input files (when they are present in both associations) it is possible that one run can overwrite or delete `outlier_i2d` files that are in-use by the other run due to the filenames not containing the association identifier.
Regression tests run at: https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1390/
show 1 unrelated (common) failure `test_duplicate_names` likely due to lost log messages.
**Checklist for …
=> JP-2943: add asn_id to outlier_i2d filename

jwst/jump/jump_step.py, jwst/ramp_fitting/ramp_fit_step.py, jwst/wfss_contam/observations.py
Fixes: https://github.com/spacetelescope/jwst/issues/8306
Without setting a multiprocessing start method (using the default) on linux with python 3.12 results in a `DeprecationWarning`.
Warnings for python 3.12:
```
jwst/jump/tests/test_detect_jumps.py: 9 warnings
jwst/jump/tests/test_jump_step.py: 24 warnings
/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/multiprocessing/popen_fork.py:66: DeprecationWarning: This process (pid=2483) is multi-threaded, use of fork() may lead to deadlocks in the child.
self.pid = os.fork()
jwst/ramp_fitting/tests/test_ramp_fit.py::test_multiprocessing
jwst/ramp_fitting/tests/test_ramp_fit.py::test_multiprocessing2
jwst/ramp_fitting/tests/test_ramp_fit_step.py::test_ramp_fit_step[2]
jwst/ramp_fitting/tests/test_ramp_fit_step.py::test_ramp_fit_step[2] …
```
=> remove global multiprocessing.set_start_method

pyproject.toml
The current `pyproject.toml` enables asdf schema tests for 2 directories that do not exist:
https://github.com/spacetelescope/jwst/blob/77c4966a836e03f34939d3de6ba805bc0934a7d6/pyproject.toml#L226-L228
As the directories do not exist, no tests are run.
These could have been disabled in: https://github.com/spacetelescope/jwst/pull/7439 which moved the schemas to `stdatamodels` (where they are [tested](https://github.com/spacetelescope/stdatamodels/blob/60d8dc7749708363a49648a8d393cd8740ab76a0/pyproject.toml#L143))
This PR removes the configuration in `pyproject.toml` that enables the asdf schema tests.
=> Remove configuration for non-existant schema tests

CHANGES.rst, jwst/tweakreg/tests/test_tweakreg.py, jwst/tweakreg/tweakreg_step.py
It has been reported when an user used custom file names with the same common file name in several groups of images (i.e., with different `group_id` in the asn files). The algorithm for computing group names (`_common_name()`) may fail to produce a unique name for some groups resulting in these groups not being aligned.
This is not an issue for pipeline runs on original JWST file names but may affect grouping when user renames input models.
This PR is a further improvement on #8012
=> Fix a bug in how a image group name is determined

CHANGES.rst, docs/jwst/user_documentation/running_pipeline_python.rst
Resolves [JP-2980](https://jira.stsci.edu/browse/JP-2980)
Closes #7308 
This PR addresses needed documentation requested in several help desk tickets. This is connected to GitHub issues:
https://github.com/spacetelescope/jwst/issues/8404
https://github.com/spacetelescope/jwst/issues/8306 
=> JP-2980 Documentation improvement for multiprocessing: a script which spawns processes on import will cause system failure

CHANGES.rst, jwst/dark_current/dark_current_step.py
This PR addresses JP-3463, adding a message to the log.info when users specify a value for average_dark_current to make clear that the value is being used.
=> JP-3463: Add log message to dark step

jwst/regtest/test_miri_image.py
This PR changes the test of the average_dark capability in the calwebb_detector1 pipeline so that it no longer uses one of the same datasets that's already used in another test in the same regtest module. That causes issues with outputs clobbering one another. All the new input/output files have been loaded to Artifactory and the new regtest passes locally.
=> Fix miri avg_dark regtest

jwst/assign_wcs/tests/test_niriss.py
The `jwst/assign_wcs/tests/test_niriss.py::test_filter_rotation` test is failing on main with the new CRDS context (1228).
The new context contains updated `specwcs` reference files which are leading to the test failure when a 20 degree "rotation" is tested. This appears to be the rotation of the filter (relative to the reference position). A 20 degree rotation seems unlikely given the wheel has a quoted repeatability of 0.1585 degrees (taken from: https://jwst-docs.stsci.edu/jwst-near-infrared-imager-and-slitless-spectrograph/niriss-instrumentation/niriss-pupil-and-filter-wheels#gsc.tab=0).
The test was updated to instead test a rotation that is 10x the quoted repeatability.
However, this test failure may point to other issues with the niriss wcs transforms (which I am not familiar …
=> limit rotation test to 10x the angular repeatability

.github/workflows/ci.yml
This PR adds the `workflow_dispatch` trigger to the `ci.yml` workflow. This will allow manually triggering runs of the ci (which I was hoping to do to sort out why `jwst/assign_wcs/tests/test_niriss.py::test_filter_rotation` is failing on PRs) and matches several of the other workflows that already have this trigger.
=> add workflow dispatch trigger to ci

CHANGES.rst, jwst/extract_1d/extract1d.py, jwst/extract_1d/tests/test_extract_src_flux.py, jwst/extract_1d/tests/test_fit_background_model.py
Resolves [JP-3601](https://jira.stsci.edu/browse/JP-3601)
Closes #8431 
This PR fixes a crash in an extraction background edge case, in which both lower and upper limits for the background region are outside the valid area for some data range.
=> JP-3601: Fix background interval edge case

CHANGES.rst, docs/jwst/resample/main.rst, jwst/resample/resample.py, jwst/resample/resample_utils.py, jwst/resample/tests/test_resample_step.py
Resolves [JP-3569](https://jira.stsci.edu/browse/JP-3569)
Closes #8344 
Variance arrays from input data are now resampled individually, then combined with weights that match the science weight type, instead of being self-weighted.  Input variance values equal to zero are propagated as zeros, rather than as NaN.  In the final combined error array, values for which all input error components are NaN are set to NaN instead of zero.  NaNs are otherwise ignored in the sum over variance components.
=> JP-3569: Update variance handling in resample step

CHANGES.rst, jwst/ami/ami_analyze.py, jwst/regtest/test_niriss_ami3.py
This allows `ami_analyze` to run on cal files. A regression test is added (input and truth files will be added and a run started when the files are approved).
This is an alternative to https://github.com/spacetelescope/jwst/pull/8448 and instead of using the generic `DataModel` converts the input `ImageModel` to a `CubeModel` before the dimension expansion.
Regression tests run at:
https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1411/
Showed 1 unrelated error in `[stable-deps] test_filter_rotation – jwst.assign_wcs.tests.test_niriss` which is also failing on main:
https://plwishmaster.stsci.edu:8081/job/RT/job/JWST/2869/testReport/junit/jwst.assign_wcs.tests/test_niriss/_stable_deps__test_filter_rotation/
The regtest added in this PR passed.
**Checklist for …
=> allow ami_analyze step to run on cal files

.github/pull_request_template.md
This PR changes `maintainers` to `PR authors` in the PR template to clarify who should fill out the checklist. I never thought it was me :)
This PR also adds a new item to the checklist:
- ~[ ] added entry in `CHANGES.rst` within the relevant release section~
- ~[ ] updated or added relevant tests~
- ~[ ] updated relevant documentation~
- ~[ ] ran regression tests, post a link to the Jenkins job below.
[How to run regression tests on a PR](https://github.com/spacetelescope/jwst/wiki/Running-Regression-Tests-Against-PR-Branches)~
- ~[ ] Make sure the JIRA ticket is [resolved properly](https://github.com/spacetelescope/jwst/wiki/How-to-resolve-JIRA-issues)~
=> clarify checklist in PR template

CHANGES.rst, jwst/flatfield/flat_field.py, jwst/regtest/test_nirspec_steps_spec2.py
Resolves [JP-3613](https://jira.stsci.edu/browse/JP-3613)
Closes #8460
Update the error and variance arrays to NaN whenever science data is set to NaN.  Impacts the flat field step and products up through the cal file, for all NIRSpec modes.
=> JP-3613: Update error arrays to match NaN in data

CHANGES.rst, docs/jwst/extract_2d/main.rst, jwst/assign_wcs/nircam.py, jwst/assign_wcs/tests/test_nircam.py, jwst/extract_2d/grisms.py, jwst/extract_2d/tests/test_grisms.py, jwst/regtest/test_nircam_tsgrism.py
Resolves [JP-3595](https://jira.stsci.edu/browse/JP-nnnn)
Closes #[8420](https://github.com/spacetelescope/jwst/issues/8420)
This PR adds support for extraction of spectra in NIRCam GRISM TSO mode when an Offset Special Requirement is specified, which manifests as a nonzero dither XOFFSET.  This is handled in `extract_2d`.  A unit test was added covering the function that computes this offset.
One unit test of `assign_wcs` was also modified so that its xfail could be removed.
=> JP-3595: handling for NIRCam GRISM Time Series Pointing offset SR

CHANGES.rst, jwst/tweakreg/tweakreg_step.py
Resolves [JP-3604](https://jira.stsci.edu/browse/JP-3604)
Closes #8435
This PR improves handling of exceptions in the absolute alignment stage that could result in crashes when image catalogs contain no sources.
Regression test: https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1410/
=> JP-3604: Fix possible crashes in the alignment to abs catalog

CHANGES.rst, jwst/extract_1d/extract.py, jwst/extract_1d/tests/test_extract_1d_step.py
Resolves [JP-3616](https://jira.stsci.edu/browse/JP-3616)
Closes #8469 
When NIRSpec fixed slit data is extracted as a SlitModel, take the slit name from the name attribute if possible.
Also adding a couple basic unit tests to exercise the extract1d step for NIRSpec FS and MOS modes, including testing the output slit name.
=> JP-3616: Fix NIRSpec FS spec3 slit name

jwst/stpipe/tests/test_saving.py, jwst/stpipe/tests/test_step.py
Several tests call [Step.closeout](https://github.com/spacetelescope/stpipe/blob/d20b6429cafe0a4ca846fd43af7b6a61241e632c/src/stpipe/step.py#L1160) with no arguments. This results in a single call to `gc.collect` (since both `to_close` and `to_del` were not provided).
This PR removes the calls to `Step.closeout`. These were not replaced with calls to `gc.collect` (as python should manage that itself). Removing the usage in the tests will allow `Step.closeout` to be removed (as it is otherwise unused).
=> remove calls to Step.closeout in tests

CHANGES.rst, jwst/regtest/test_niriss_image.py
Related to [JP-3604](https://jira.stsci.edu/browse/JP-3604)
This PR adds a regression test to verify the solution for the failure in JP-3604
regression tests: https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1433/
=> Regression test for JP-3604

CHANGES.rst, jwst/outlier_detection/outlier_detection.py, jwst/outlier_detection/outlier_detection_spec.py, jwst/outlier_detection/outlier_detection_step.py, jwst/outlier_detection/tests/test_outlier_detection.py, jwst/regtest/test_miri_lrs_slit_spec3.py, jwst/regtest/test_nirspec_fs_spec3.py, jwst/resample/resample.py, jwst/resample/resample_spec.py, jwst/resample/tests/test_resample_step.py
Resolves [JP-3311](https://jira.stsci.edu/browse/JP-3311)
Closes #
This PR adds tests for changes made in [https://github.com/spacetelescope/jwst/pull/8464](https://github.com/spacetelescope/jwst/pull/8464,)
=> adding tests for changes in JP-3311 and minor fixes

CHANGES.rst, jwst/assign_wcs/util.py, jwst/datamodels/container.py, jwst/tweakreg/tests/test_tweakreg.py, jwst/tweakreg/tweakreg_step.py
This PR reorganizes operations within the `tweakreg` step to work towards improving image3 performance.
Changes include:
- Refactor how custom catalogs are resolved (the behavior should be the same although at the the moment there appear to be no tests for this feature, this PR adds tests). This will allow removal of special handling of `tweakreg_catalog` in `ModelContainer` (one of the reasons that class opens all models when constructed).
- use `wcs_from_footprints` on the in-memory wcs objects to compute the combined wcs for limiting the GAIA query (at the moment I also see no tests for this feature). This required a minor backwards-compatible change in `assign_wcs.util`.
- Refactor catalog/corrector and model linking to instead use the catalog/corrector index and model index. These …
=> JP-3603: reorder tweakreg to reduce iterations through models

jwst/regtest/test_niriss_image.py
This PR addresses an issue where a regression test may fail even though the code is working as expected (I think).
=> Fix failure in niriss tweakreg test

CHANGES.rst, docs/jwst/tweakreg/README.rst, jwst/tweakreg/tweakreg_catalog.py, jwst/tweakreg/tweakreg_step.py
Resolves [JP-3625](https://jira.stsci.edu/browse/JP-3625) by switching the code default starfinder for use in tweakreg to IRAF starfinder instead of DAO starfinder.
=> JP-3625: Switch to IRAF starfinder default

jwst/coron/tests/test_coron.py
Resolves [JP-3614](https://jira.stsci.edu/browse/JP-3614)
Closes #8465 
This PR addresses a unit test failure in `jwst/coron/tests/test_coron.py::test_align_array` on Mac only with the latest scipy version.  Similarly to [this PR](https://github.com/spacetelescope/jwst/pull/8439), the problem was caused by changes in the scipy leastsq function, which is used [here](https://github.com/spacetelescope/jwst/blob/3df35ef10cbfda904a7bfee947d8fd5e87e2092d/jwst/coron/imageregistration.py#L42).  The change does not seem to cause any qualitative problems, so simply increasing the tolerance is seemingly fine.
I don't know what the "rules" are for needing a changelog entry, but I feel like this deserved the no-changelog-entry-needed tag, as there are no changes to the way the pipeline functions, nor …
=> JP-3614: relaxed tolerance for coron unit test

CHANGES.rst, jwst/ramp_fitting/ramp_fit_step.py, jwst/ramp_fitting/tests/test_ramp_fit.py
Resolves [JP-3121](https://jira.stsci.edu/browse/JP-3121)
This PR addresses the C extensions.  In particular, tests need to ensure the `dtypes` of `ndarrays` are what is to be expected in a RampModel.  Tests have been changed to ensure proper typing, as well as simplified.
=> JP-3121: Updating JWST Ramp Fit Code to Work with New C Extension 

CHANGES.rst, docs/jwst/ramp_fitting/arguments.rst, jwst/ramp_fitting/ramp_fit_step.py
Resolves [JP-3632](https://jira.stsci.edu/browse/JP-3632)
Closes #8501 
This PR addresses the ability to select the C extension implementation of ramp fitting or the python implementation.
=> JP-3632: Change the Spec of Ramp Fitting to Select Algorithm

CHANGES.rst, jwst/resample/resample_spec.py
Resolves [JP-3624](https://jira.stsci.edu/browse/JP-3624)
Closes #8485
Closes #8484
Regression test: https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1479/
=> JP-3624: Fix a source of errors in resampled spec WCS

CHANGES.rst, docs/jwst/tweakreg/README.rst, jwst/regtest/test_niriss_image.py, jwst/tweakreg/tests/test_tweakreg.py, jwst/tweakreg/tweakreg_step.py
This PR adds a check that `(abs_)separation` > `sqrt(2) * (abs_)tolerance` input parameters to the `tweakreg` step. It also adds a comment in the docstring about these parameters.
=> Add a check for separation and tolerance in tweakreg

CHANGES.rst, jwst/assign_wcs/nirspec.py, jwst/assign_wcs/tests/test_nirspec.py, jwst/master_background/master_background_mos_step.py, jwst/master_background/nirspec_utils.py, jwst/master_background/tests/test_nirspec_corrections.py
Resolves [JP-2922](https://jira.stsci.edu/browse/JP-2922)
This PR addresses two minor issues with PR #8442.
- Add default fallback values for an edge case in NIRSpec MSA handling: when a source is specified in the SHUTTER_INFO table, but not found in the SOURCE_INFO table.  These cases used to be handled as background sources, but background sources now have their own separate handling.  This case is unlikely to be encountered in operations; this handling would mostly only be needed to gracefully handle a hand-edited MSA file.
- Add a function to check whether a slit contains a background source, and update the test from checking for "background" (old-style background source names) to "BKG" (new-style) in the slit.source_name attribute.
**Checklist for PR authors (skip items if you don't …
=> JP-2922: Minor fixes for MSA source names

jwst/wfs_combine/wfs_combine_step.py
This PR replaces usage of [name_format](https://github.com/spacetelescope/jwst/blob/f2c9e93e873e9cce64588075183379f53d6c2f35/jwst/wfs_combine/wfs_combine_step.py#L32) in wfs_combine with make_output_path. The resulting filenames saved by the step are the same (as is tested in the [test_nircam_wfs_image](https://github.com/spacetelescope/jwst/blob/f2c9e93e873e9cce64588075183379f53d6c2f35/jwst/regtest/test_nircam_wfs.py#L59) regression test). This PR removes the only use of name_format to allow its removal in stpipe to work towards simplifying the file naming code.
Regression tests show only unrelated errors and no failures of `test_nircam_wfs_image`.
https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1502/
**Checklist for PR authors (skip items if you don't have …
=> remove name_format usage in wfs_combine

jwst/regtest/test_miri_lrs_slit_spec3.py
This PR fixes the setup in the MIRI LRS slit spec3 regression test, to avoid problems that arise when things intentionally change. The problem is related to the fact that the test has 4 iterations to it, generating the same s2d product each time. At the same time it was using one of the truth files as WCS input information, from which to generate some of the later iterations of s2d products. So when the pipeline code or ref files change, the test was still using the WCS from the old truth file to generate the new s2d products. Then when "okify_regtests" tries to use the new s2d products to update the truth, it's using a result that was generated from the old truth file and hence doesn't actually accomplish the appropriate update.
So I've changed the mechanics of the test to use the WCS …
=> Fix MIRI LRS spec3 regtest setup

CHANGES.rst, docs/jwst/assign_wcs/arguments.rst, docs/jwst/assign_wcs/main.rst, docs/jwst/tweakreg/README.rst, jwst/assign_wcs/assign_wcs_step.py, jwst/assign_wcs/tests/test_wcs.py, jwst/assign_wcs/util.py, jwst/tweakreg/tests/test_tweakreg.py, jwst/tweakreg/tweakreg_step.py
Resolves [JP-3567](https://jira.stsci.edu/browse/JP-3567)
Closes #8341 
These changes align the default parameters for WCP SIP approximation in the three places they are used: the assign_wcs step, the tweakreg step, and the underlying `update_fits_wcsinfo` function defaults.  New step parameters are added for tweakreg, matching the ones in assign_wcs, so that the parameters used in both steps can be modified together.
The new defaults for assign_wcs should result in better accuracy in the output FITS WCS.
=> JP-3567: SIP coefficient accuracy and consistency

README.md
This PR updates the DMS Build info table in the jwst README, to coincide with the installation of B10.2.x today in Ops.
=> Update README for B10.2 install in Ops

jwst/outlier_detection/outlier_detection_tso.py, jwst/regtest/test_miri_lrs_slitless.py
Resolves [JP-3584](https://jira.stsci.edu/browse/JP-3584)
Closes #8378
This PR fixes a bug in implementation of JP-3584 that was causing crashes when save_intermediate_results was set True for TSO data. 
=> JP-3584-bugfix: fixed failed save for intermediate (median) files

CHANGES.rst, jwst/outlier_detection/outlier_detection.py, jwst/outlier_detection/tests/test_outlier_detection.py, jwst/regtest/test_nircam_align_to_gaia.py, jwst/resample/resample.py, jwst/resample/tests/test_resample_step.py
Resolves [JP-3635](https://jira.stsci.edu/browse/JP-3635)
Closes #8509
This PR addresses a small bug in outlier detection: resample accounted for the difference between the nominal pixel area in steradians used for the photometric calibration (img.meta.photometry.pixelarea_steradians) and the as-computed pixel area from the WCS when resampling cal files.  That wasn't performed in reverse when blotting median images back to match those individual cal files.  This PR applies that reverse ratio so that the total flux is conserved between input models and blotted models. …
=> JP-3635: Account for pixel area ratio in outlier detection blotting

CHANGES.rst, jwst/associations/lib/dms_base.py, jwst/associations/lib/rules_level2b.py, jwst/associations/lib/rules_level3.py
Resolves [JP-3617](https://jira.stsci.edu/browse/JP-3617)
Closes #8472 
Update to TSO stage 2b and 3 association rules to skip processing for an uncalibrated filter for NIRISS SOSS.
=> Add check for uncalibrated filters for NIRISS SOSS

JenkinsfileRT, requirements-max.txt
The `requirements-max.txt` file contains 2 upper pins:
https://github.com/spacetelescope/jwst/blob/380dc5eb082c6c5d4e024a9337999f69cd5b8443/requirements-max.txt#L3-L4
and is used in the main (non-dev) jenkins file:
https://github.com/spacetelescope/jwst/blob/380dc5eb082c6c5d4e024a9337999f69cd5b8443/JenkinsfileRT#L77
This appears to be run after the `pip list` in the job which may mean that our regtests have been using a version of stcal that is lower than our minimum version listed in `pyproject.toml`:
https://github.com/spacetelescope/jwst/blob/380dc5eb082c6c5d4e024a9337999f69cd5b8443/pyproject.toml#L37
As `requirements-max.txt` is not used for the GA regression tests (and at the moment only show differences due to different machines) this PR removes the file (and the use in the jenkins …
=> remove requirements-max.txt

JenkinsfileRT, JenkinsfileRT_dev
* The version (24.x) installed by miniforge is sufficient. 22.x is too old.
Ref: https://github.com/spacetelescope/jenkins_shared_ci_utils/pull/94
=> Do not set conda version in Jenkinsfile(s)

CHANGES.rst, jwst/master_background/expand_to_2d.py
Resolves [JP-3523](https://jira.stsci.edu/browse/JP-3523) by having IFU master background default to zero background values beyond the wavelength range of the input backgrounds, instead of automatically NaN-ing out all such wavelength and causing crashes in cube building.
Closes #8244 
=> JP-3523: Use zero background instead of NaN background where undefined

docs/jwst/outlier_detection/arguments.rst, docs/jwst/outlier_detection/outlier_detection_imaging.rst, docs/jwst/outlier_detection/outlier_detection_tso.rst, jwst/outlier_detection/outlier_detection_step.py
Reverts spacetelescope/jwst#8595
See
https://github.com/spacetelescope/jwst/pull/8595#issuecomment-2191513545
Although these parameters are unused by the step they are unfortunately defined in the parameter reference files:
https://jwst-crds.stsci.edu/browse/jwst_miri_pars-outlierdetectionstep_0054.asdf
This PR just reverts #8595 a follow-up PR will mark these as deprecated.
=> Revert "remove unused nlow nhigh parameters from outlier detection"

CHANGES.rst, docs/jwst/outlier_detection/arguments.rst, docs/jwst/outlier_detection/outlier_detection_imaging.rst, docs/jwst/outlier_detection/outlier_detection_tso.rst, jwst/outlier_detection/outlier_detection_step.py
This is a follow-up to https://github.com/spacetelescope/jwst/pull/8602 and:
- adds a deprecation comment to the nlow and nhigh parameters
- removes nlow and nhigh from the documentation
- fixes the spec values in the docs
The spec values in the docs do not match the step (see the below linked issue). This PR removes the datatypes and defaults from the "arguments" docs page and adds a link to the spec (which will automatically stay up-to-date with the step).
Link to the updated docs: https://jwst-pipeline--8603.org.readthedocs.build/en/8603/jwst/outlier_detection/arguments.html
Fixes https://github.com/spacetelescope/jwst/issues/8599 …
=> deprecate nlow nhigh, fix incorrect spec values in docs

CHANGES.rst, docs/jwst/ramp_fitting/arguments.rst, jwst/ramp_fitting/ramp_fit_step.py
Resolves [JP-3671](https://jira.stsci.edu/browse/JP-3671)
Closes #8605 
This PR changes the default ramp fitting algorithm to Ken's new C implementation of the ordinary least-squares algorithm.  The original Python implementation is still selectable, but no longer the default.
=> JP-3671: make OLS_C the default algorithm for ramp fitting

jwst/lib/engdb_direct.py, tox.ini
Ruff 0.5 removed `ruff <path>` in favor of `ruff check <path>`.
https://astral.sh/blog/ruff-v0.5.0#removed-deprecated-features
This change broke our style check
https://github.com/spacetelescope/jwst/pull/8600#issuecomment-2195456616
This PR fixes the check and adds a `noqa` to jwst/lib/engdb_direct.py for a new F811 failure.
=> fix ruff style check

.readthedocs.yaml
Resolves [JP-3549](https://jira.stsci.edu/browse/JP-3549)
Closes #
This PR fixes the `__version__ `returned by `setuptools_scm` to include the tag associated with the commit. RTD's default checkout behavior creates a shallow clone and removes tag objects from the local repo. This "unshallows" the clone and restores the object associations.
See: https://docs.readthedocs.io/en/stable/build-customization.html#unshallow-git-clone
=> RTD: Restore tags for all branches

docs/index.rst
Resolves [JP-3549](https://jira.stsci.edu/browse/JP-3549)
See #8299 #8633 
Removing the `stable` branch and allowing RTD to build its own stable documentation has one drawback: the release version (visible under the STScI logo) is replaced with "stable". The release information is written to the HTML `<title>...</title>` tag, so it is _technically_ visible to the user, but only barely.
This PR displays the release version on the index page. When the stable documentation is generated it will continue to write "stable" below the logo above the navigation pane, however, the user will not need to hunt through the page's source code to find the actual version the documentation relates to.
Demo: https://jwst-pipeline--8642.org.readthedocs.build/en/8642/
**Checklist for PR authors (skip items if …
=> Adding version information to the landing page

jwst/associations/tests/test_level3_duplicate.py, jwst/regtest/test_nirspec_exceptions.py, jwst/tests/helpers.py
The tests updated in this PR randomly fail (likely due to our complex logging and the pytest `caplog` fixture only using the root logger).
This PR removes the caplog fixture (from only these tests) and replaces it with a monkeypatch of the logger that emits the checked message.
Regression tests running (with jwst_1242.pmap since the new context is causing spec2 failures):
https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1581/
show 0 failures.
=> refactor msa fail/nofail and association duplicate tests to not use caplog

CHANGES.rst, jwst/msaflagopen/tests/test_msa_open.py, jwst/outlier_detection/outlier_detection.py
Resolves [JP-3687](https://jira.stsci.edu/browse/JP-3687)
Closes #8640
This PR addresses a bug that occurs when the `outlier_detection` step is run outside the pipeline, i.e., loading the datamodel from file instead of passing it in as a `ModelContainer`.  In that case, the `wcs.array_shape` attribute sometimes does not get saved (saving of this attribute was added to gwcs within the past year, so the behavior is version-dependent). This PR sets the `wcs.array_shape` explicitly.
=> JP-3687: fix outlier_detection failures when run outside pipeline

.readthedocs.yaml
Closes #
The last build (#8642) produced:
```
Version: 1.15.2.dev10+g2d15511ca.d20240712
```
RTD modifies indexed files in the repository prior to building the documentation. This change should prevent `setuptools_scm` from returning a dirty version (`.dXXXXXXXX` suffix).
See: https://docs.readthedocs.io/en/stable/build-customization.html#avoid-having-a-dirty-git-index
=> RTD: Clear the dirty git index flag

CHANGES.rst, jwst/ami/ami_average_step.py, jwst/ami/tests/test_ami_average.py
The step spec for `AmiAverageStep` contains an invalid entry:
https://github.com/spacetelescope/jwst/blob/7d97170f080771ef1f7a6276052f250089adf3bb/jwst/ami/ami_average_step.py#L14-L16
which leads to an error when attempting to construct the step:
```python
ValidationError: Config parameter 'skip': missing
```
This PR fixes the spec and adds a very basic unit test to verify the step can be instantiated.
=> fix bug in AmiAverageStep spec that prevents step creation

jwst/tests/helpers.py
Small PR to make LogWatcher reusable for multiple messages.
Using this helper to develop tests for #8669, I found it's convenient to use the same watcher to check for different messages, but the flag needs to be reset between calls.  I can do it manually, but that's failure prone. With this change, I can do something like:
```
log_watcher.message = 'test 1'
function_call()
log_watcher.assert_seen()
log_watcher.message = 'test 2'
function_call()
log_watcher.assert_seen()
```
=> Reset 'seen' flag in log watcher after check

CHANGES.rst, jwst/emicorr/emicorr.py
This PR addresses a corner case where MIRI EMICORR can sometimes fail to construct a noise model and return NaNs, resulting in data passed out of the step containing NaNs.  EMICORR is now set to first do no harm, and make a zero correction anywhere it was unable to come up with a good model (for any of multiple reasons).
=> JP-3696: Ensure EMICORR correction is never NaN

CHANGES.rst, pyproject.toml
`stsci.image` is listed as a dependency:
https://github.com/spacetelescope/jwst/blob/de39de07b6f0380860caa86e8485666b4cef35c2/pyproject.toml#L40
but is unused:
https://github.com/search?q=repo%3Aspacetelescope%2Fjwst%20stsci.image&type=code
Regression tests with this PR show that stsci.image is not installed (so it is also not a non-primary dependency): https://plwishmaster.stsci.edu:8081/blue/organizations/jenkins/RT%2FJWST-Developers-Pull-Requests/detail/JWST-Developers-Pull-Requests/1611/pipeline#step-192-log-94
and all tests passed.
Fixes: #3576
=> Remove stsci.image dependency

CHANGES.rst, docs/jwst/data_products/science_products.rst, docs/jwst/master_background/description.rst, docs/jwst/outlier_detection/outlier_detection_coron.rst, docs/jwst/outlier_detection/outlier_detection_imaging.rst, docs/jwst/package_index.rst, docs/jwst/pipeline/calwebb_spec2.rst, docs/jwst/pipeline/calwebb_spec3.rst, docs/jwst/pixel_replace/main.rst, docs/jwst/resample/arguments.rst, docs/jwst/resample/index.rst, docs/jwst/resample/main.rst, docs/jwst/resample/resample.rst, docs/jwst/resample/resample_step.rst, docs/jwst/resample_spec/arguments.rst, docs/jwst/resample_spec/index.rst, docs/jwst/resample_spec/main.rst, docs/jwst/resample_spec/reference_files.rst, docs/jwst/resample_spec/resample_spec.rst, docs/jwst/resample_spec/resample_spec_step.rst, jwst/regtest/test_miri_lrs_slit_spec3.py, jwst/resample/resample_spec_step.py, jwst/resample/resample_step.py, jwst/resample/resample_utils.py
Resolves [JP-3679](https://jira.stsci.edu/browse/JP-3679)
Closes #8621 
Remove inheritance link between ResampleSpecStep and ResampleStep, so that the resample_spec step can have a different step parameter spec.
Remove parameters and options from the new spec for resample_spec that are only appropriate for imaging data.
=> JP-3679: Separate resample_spec parameters from resample step

.github/workflows/build.yml
cibuildwheel is now (attempting) to build for python 3.13.
However our dependencies (and likely code) is not yet ready.
This is currently leading to build failures due to an attempt to build scipy from source.
This PR restricts the build job to only build for python 3.10, 3.11 and 3.12 (the listed supported versions in [pyproject.toml](https://github.com/spacetelescope/jwst/blob/be80530a4531c0d9cb33d72e294746f48257b6d0/pyproject.toml#L16)).
Closes #8690
=> don't build for python 3.13

jwst/assign_wcs/tests/test_schemas.py
This PR adds a filter to ignore a deprecation warning for an upcoming asdf deprecation:
https://github.com/asdf-format/asdf/pull/1819
`ignore_version_mismatch` has done nothing since asdf 3.0.0. However it is currently set in stdatamodels:
https://github.com/spacetelescope/stdatamodels/pull/313
Deprecating the feature in asdf will cause 1 jwst test to fail which turns all warnings into errors:
https://github.com/spacetelescope/jwst/blob/89f126a035751674f29a9027e2deae11b3e63fca/jwst/assign_wcs/tests/test_schemas.py#L57
This PR ignores the upcoming deprecation warning to allow the test to continue to pass. The trigger for the warning is being addressed in the above stdatamodels PR but would otherwise require a new stdatamodels release (with the above PR). Filtering this warning seems like …
=> update test to allow easier deprecation of `ignore_version_mismatch`

.github/workflows/ci.yml, .github/workflows/ci_cron.yml, .github/workflows/tests_devdeps.yml
Resolves [SCSB-169](https://jira.stsci.edu/browse/SCSB-169)
[<img width="333" alt="image" src="https://github.com/user-attachments/assets/dafc1eab-00ad-4d9d-ae5d-81e30820a012">](https://github.com/zacharyburnett/jwst/actions/workflows/ci.yml)
=> [SCSB-169] add user input to specify `CRDS_CONTEXT`

.github/workflows/build.yml, pyproject.toml
Resolves [SCSB-170](https://jira.stsci.edu/browse/SCSB-170)
=> [SCSB-170] pin Python<3.13

requirements-dev-thirdparty.txt
This PR takes advantage of https://github.com/astropy/photutils/pull/1834 . And might as well grab pyerfa-dev from the same place while you are at it?
=> TST: Use photutils nightly wheel

docs/jwst/data_products/guidestar_products.rst
This PR addresses a typo found in our guide star pipeline data products page.
=> Documentation typo

jwst/ami/leastsqnrm.py, jwst/assign_wcs/assign_wcs_step.py, jwst/associations/association.py, jwst/dark_current/dark_current_step.py, jwst/extract_1d/extract.py, jwst/extract_1d/extract1d.py, jwst/lib/set_telescope_pointing.py, jwst/lib/tests/stp_v1.py, jwst/pipeline/calwebb_spec2.py, jwst/pixel_replace/pixel_replace_step.py, jwst/scripts/adjust_wcs.py, jwst/scripts/set_telescope_pointing.py, jwst/scripts/v1_calculate.py, jwst/tweakreg/tweakreg_step.py
This PR updates any log messages currently containing newlines, replacing them instead with multiple log messages.  This is a pre-requisite to removing the problematic MultiLineLogger (e.g. #8694), which automatically splits these messages into multiple log messages.
To find these messages, I reviewed every instance of '\n' in the jwst code base and updated code for any that appeared in log messages.  I have tested most of the changes from the command line to make sure they look right, and will run regression tests to make sure they don't break anything.
=> Update log messages containing newlines

CHANGES.rst, jwst/associations/lib/dms_base.py, jwst/associations/lib/rules_level3_base.py, jwst/associations/tests/test_level3_product_names.py
Resolves [JP-3702](https://jira.stsci.edu/browse/JP-3702)
Closes #8688
Restore slit names to level 3 filenames for NIRSpec products that do not get planned as fixed slit reductions.  This primarily impacts BOTS mode, which has a FXD_SLIT defined, but does not get planned for spec3 with Asn_Lv3NRSFSS rules: these data are planned for tso3 with Asn_Lv3TSO rules.  It also impacts background targets for fixed slit, planned with Asn_Lv3SpecAux rules.
In JP-3233 (#7879), association rules were changed for fixed slits to allow S200A1 and S200A2 targets to be reduced together in spec3.  Part of this change removed a check for fixed slit as one of the 'opt_elem' fields in the filename.  This had the unintended effect of removing the fixed slit from the name for BOTS and auxiliary NIRSpec data.
The …
=> JP-3702: Fix filenames for level3 NIRSpec

CHANGES.rst, jwst/resample/resample_spec.py, jwst/resample/tests/test_resample_step.py
Resolves [JP-3547](https://jira.stsci.edu/browse/JP-3547)
Fixes an issue discovered during testing for #8596.
For MIRI, when there are multiple input files and pixel_scale_ratio is set to something other than 1.0, the output array size was being computed incorrectly: the pixel_scale_ratio was applied twice.  This PR fixes that issue and adds a unit test for the multiple input case.
=> JP-3547: Fix MIRI array sizing for multiple inputs and pixel ratio != 1

CHANGES.rst, docs/jwst/outlier_detection/outlier_detection_spec.rst, jwst/outlier_detection/imaging.py, jwst/outlier_detection/outlier_detection_step.py, jwst/outlier_detection/spec.py, jwst/outlier_detection/tests/test_outlier_detection.py, jwst/resample/resample.py, jwst/resample/resample_spec.py, jwst/resample/tests/test_resample_step.py
Resolves [JP-3719](https://jira.stsci.edu/browse/JP-3719)
Closes #8734 
For spectral modes with resampling, intermediate files from outlier detection are not being written correctly.  There should be files written to the output directory with suffix 'outlier_s2d'.  Instead, there are currently files written to the **current** directory with suffix 'outlier_**i2d**', and some duplicate files written to the output directory with suffix 'outlier__outlier_s2d.fits'.  
This PR should fix these issues by:
- removing the duplicate file saving mechanism in the spectral outlier detection method, in favor of the native one in the resampler
- modifying the resampling step to store the suffix 'i2d' for imaging and 's2d' for spectral data
- passing the output directory to the resampler in the spectral …
=> JP-3719: Fix names for intermediate spectral outlier detection files

CHANGES.rst, docs/jwst/mrs_imatch/description.rst, jwst/cube_build/ifu_cube.py, jwst/mrs_imatch/mrs_imatch_step.py, jwst/mrs_imatch/tests/test_configuration.py
Resolves [JP-3649](https://jira.stsci.edu/browse/JP-3649)
Closes #8538 
This PR addresses a bug in cube_build when it was called from  mrs_imatch. Mrs_imatch  is not used in standard processing. A deprecation warning has been added if mrs_imatch is called and the step has been set to default=True in spec. This will prevent the step from being called when the .run method is used for spec3. 
Running regression tests:
https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1681/
=> JP-3649 Fix cube build error when called from mrs_imatch and add deprecated warning for mrs_imatch

CHANGES.rst, docs/jwst/pipeline/calwebb_coron3.rst, jwst/coron/imageregistration.py, jwst/coron/klip.py, jwst/coron/tests/test_coron.py
Resolves [JP-3727](https://jira.stsci.edu/browse/JP-3727)
Closes #8746 
[A previous pull request](https://github.com/spacetelescope/jwst/pull/8643) implemented a change that simplified the pipeline's coronagraphic data processing such that the alignment of the PSF to the science data is only done on the first science integration, then assumed to be the same for all subsequent integrations.  Prior to this change, the shifted PSF was stored in a 4-dimensional data structure (QuadModel of shape n_sci_integrations, n_psf_integrations, n_rows, n_cols), which made sense when the shift was different on each science integration.  Now, though, this model is identical over the zeroth axis and therefore redundant with itself.  Furthermore, this model uses a lot of memory (see …
=> JP-3727: changed psfalign product from quadmodel to cubemodel

jwst/regtest/test_miri_image.py, jwst/regtest/test_nircam_image.py, jwst/regtest/test_nircam_subarray_4amp.py
This PR addresses failing regression tests resulting from updated detector1 parameter reference files delivered by NIRCam and MIRI. The new reference files skip the refpix step for MIRI images and skip the persistence step for NIRCam data, resulting in test errors on missing `{..}_refpix.fits` and `{..}_trapsfilled.fits` files. This PR removes those suffixes/filenames from the test diffs.
=> Update regression tests to remove missing files from tests

.github/pull_request_template.md
using points from @nden 's email
=> update pull request checklist

CHANGES.rst, jwst/stpipe/core.py, jwst/stpipe/tests/test_step.py
This PR adds log messages (info level) for the jwst version and crds context at the end of pipeline/step runs (by making logging calls during `finalize_result`). The crds context was previously logged only if reference files were used and is now logged for every run. An example of the log messages is as follows:
```
2024-09-06 13:13:55,491 - stpipe.Image3Pipeline - INFO - Results used CRDS context: jwst_1276.pmap
2024-09-06 13:13:55,491 - stpipe.Image3Pipeline - INFO - Results used jwst version: 1.14.1.dev350+g8efc26fdb
2024-09-06 13:13:55,491 - stpipe.Image3Pipeline - INFO - Step Image3Pipeline done
```
Resolves [JP-3729](https://jira.stsci.edu/browse/JP-3729)
Closes #8749
[How to run …
=> JP-3729: log version and crds context at end of step/pipeline runs

CHANGES.rst, docs/jwst/outlier_detection/outlier_detection_imaging.rst, docs/jwst/outlier_detection/outlier_detection_spec.rst, jwst/outlier_detection/imaging.py, jwst/outlier_detection/spec.py, jwst/outlier_detection/tests/test_outlier_detection.py, jwst/outlier_detection/utils.py
Resolves [JP-3730](https://jira.stsci.edu/browse/JP-3730)
Closes #8750
[Recent work](https://github.com/spacetelescope/jwst/pull/8613) refactoring the memory management within the outlier detection step had disabled the creation of blot files as optional intermediate-stage outputs. This PR reverts this removal, allowing these blot models to be saved when `save_intermediate_results` is True.
=> JP-3730: Re-enable saving of blot models during outlier detection

CHANGES.rst, jwst/associations/association.py
This PR addresses JP-3731, updating the log message warning about use of paths within association files.
=> JP-3731: Update association path warning message.

CHANGES.rst, jwst/stpipe/core.py, jwst/stpipe/tests/test_step.py
This is a second attempt at logging the jwst version at the end of pipeline/step runs. The first attempt was subject to a stpipe bug which will need to be separately addressed.
This PR wraps `Step.run` to log the version at the end of a run for a step that has no parent. This is similar to the previous attempt https://github.com/spacetelescope/jwst/pull/8760 but does not use `finalize_result` (as that is called incorrectly by stpipe).
Testing with `strun nsclean abcdefg` (to make sure this works around the stpipe bug: https://github.com/spacetelescope/stpipe/issues/188) gives:
```
2024-09-10 14:05:12,152 - stpipe - WARNING - Input dataset is not an instance of AbstractDataModel.
2024-09-10 14:05:12,152 - stpipe - INFO - PARS-NSCLEANSTEP: CRDS parameter reference retrieval disabled. …
```
=> JP-3729: report jwst version at end of Step.run

CHANGES.rst, docs/jwst/badpix_selfcal/description.rst, jwst/badpix_selfcal/badpix_selfcal_step.py
This PR addresses [JP-3738](https://jira.stsci.edu/browse/JP-3738) by subtracting off the MRS median pedestal dark when performing bad pixel self calibration combine of multiple input exposures.
=> JP-3738: Subtract pedestal dark for MIRI MRS when constructing selfcal minimum

CHANGES.rst, jwst/ramp_fitting/ramp_fit_step.py
Resolves [JP-3669](https://jira.stsci.edu/browse/JP-3669)
This PR updates the code flow for read noise calculation.  For ramps that have CHARGELOSS flagging, when calling the "OLS_C" algorithm, this recalculation is done in the C-extension in the ramp fitting code in STCAL, so the step code calculations defined in the JWST step code no longer needs to be run and will result in errors if it is run.
The step code that handles the recalculation of the read noise for CHARGELOSS flags is now only done when the "OLS" algorithm is used.
=> JP-3669: 'OLS' Conditional Read Noise Recalculation for CHARGELOSS

CHANGES.rst, jwst/outlier_detection/imaging.py, jwst/outlier_detection/tests/test_outlier_detection.py, jwst/outlier_detection/utils.py, jwst/regtest/test_nircam_mtimage.py
Resolves [JP-3743](https://jira.stsci.edu/browse/JP-3743)
Closes #8776
This PR fixes a bug that causes the results of outlier detection to differ between the on-disk and in-memory cases any time there are weights that fall below the threshold value.
=> JP-3743: Make outlier detection respect weights for in-memory models

CHANGES.rst, jwst/coron/imageregistration.py, jwst/regtest/test_miri_coron3.py, jwst/regtest/test_nircam_coron3.py
This PR attempts to reduce the differences for coron3 results when run on different systems.
The changes are:
- remove casts from `float32` to `float64` and back from `float64` to `float32` in image registration
- tighten tolerances for `leastsq` fit in image registration
- relax tolerances for regtest result comparisons
I ran a (limited) jenkins run:
https://plwishmaster.stsci.edu:8081/blue/organizations/jenkins/RT%2FJWST-Developers-Pull-Requests/detail/JWST-Developers-Pull-Requests/1666/pipeline
and (limited) github actions run:
https://github.com/spacetelescope/RegressionTests/actions/runs/10511902948/attempts/1
comparisons of the results using the above tolerances pass. However, the regtests will fail comparison against the current truth files. I suggest that we:
- merge this PR (when …
=> adjust tolerances for coron registration

CHANGES.rst, jwst/pipeline/calwebb_spec3.py
Resolves [JP-3733](https://jira.stsci.edu/browse/JP-3733)
Closes #8754
This PR addresses removes saving the pixel_replace step output by default. The user must set pixel_replace.save_results=True to get the output written to disk. 
- https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1719/
=> JP-3733 remove setting pixel_replace.save to True in calwebb_spec3

jwst/regtest/test_miri_image.py, jwst/regtest/test_nircam_image.py, jwst/regtest/test_niriss_image.py, jwst/regtest/test_nirspec_irs2_detector1.py
Modifying the output file names so that products in the clean_flicker_noise run don't overwrite products in the standard run.
=> Fix output collisions in clean_flicker_noise tests

CHANGES.rst, jwst/pipeline/calwebb_spec2.py
Resolves [JP-3667](https://jira.stsci.edu/browse/JP-3667)
Follow up to #8786 to fix some unexpected interactions between badpix_selfcal and nsclean, causing a failure in the badpix_selfcal regression tests.  If badpix_selfcal is run, the background members are datamodels instead of filenames.
I also noticed in testing this that setting the output file for nsclean on the background/imprint members caused them to be saved by default, so I added a check for that as well.
=> JP-3667: Add safeguards for NSClean on background/imprint members

.github/pull_request_template.md, .github/workflows/changelog.yml, .readthedocs.yaml, CHANGES.rst, changes/8671.docs.rst, docs/rtd_environment.yaml, pyproject.toml
related to #8670 
using `towncrier` to handle changelog entries will
- drastically reduce (or even eliminate) branch conflicts in `CHANGES.rst` we currently experience with PRs
- keep the sections in `CHANGES.rst` consistent and eliminate duplicate sections
- allow automatic links to be generated in the changelog entries
[<img width="1152" alt="image" src="https://github.com/user-attachments/assets/24873697-fe5d-4102-83a4-32b1bf2995dd">](https://jwst-pipeline--8671.org.readthedocs.build/en/8671/jwst/changes.html)
`towncrier` expects "news fragment" files (text files in the `changes/` directory with filenames in the format `<PR#>.<changetype>.rst`, i.e. for this PR it would be `changes/8671.docs.rst`). See docs at https://towncrier.readthedocs.io/en/latest/tutorial.html#creating-news-fragme …
=> use `towncrier` to handle changelog entries

.github/dependabot.yml, .github/workflows/ci.yml, .github/workflows/tests_devdeps.yml, CONTRIBUTING.md, JenkinsfileRT, JenkinsfileRT_dev, README.md, changes/8210.general.rst, docs/getting_started/contributing.rst, docs/getting_started/install.rst, docs/jwst/stpipe/cfg_deprecation.rst
This PR updates the CI and docs to refer to a renamed "main" branch.
Unlike https://github.com/spacetelescope/stdatamodels/pull/247 and https://github.com/spacetelescope/stpipe/pull/136 it is likely that downstream packages are referring to the current default branch. For some period of time (I cannot find a statement that define for how long), github will redirect these requests to the renamed branch.
Known downstream uses will be listed here:
- (broken) link in crds: https://github.com/spacetelescope/crds/pull/1021
For developers, they will need to update their local clones and forks to match the new default branch.
Once the issue of updating packages that use the current jwst default branch is addressed, we should be able to:
- coordinate renaming with all interested parties as …
=> switch default branch name to main in docs/ci

.github/pull_request_template.md
adds new change fragment types `pipeline`, `clean_flicker_noise`, and `badpix_selfcal` to the pull request checklist (they're already in `pyproject.toml`)
- …
=> [docs] add new steps to pull request checklist as change fragment types

.github/workflows/changelog.yml
(copied from https://github.com/spacetelescope/romancal/pull/1412)
Add a CI check to make sure PRs don't change `CHANGES.rst`. Changelog entries now take the form of `towncrier` fragments and manual edits to `CHANGES.rst` are no longer needed.
- …
=> add CI check that `CHANGES.rst` is not modified

jwst/regtest/test_niriss_soss.py
This PR addresses a failure in regression testing after our 1.16.0 release, coupled with the migration of `pastasoss` reference files to CRDS OPS. This test was introduced to ensure the prior algorithm could navigate an internal failure of the transform solver - that solver algorithm is now gone, and the new algorithm is robust to the previous issue (i.e. it does not care what pixel values exist). It is no longer relevant and can be removed.
- …
=> Remove unnecessary test after pastasoss inclusion

changes/8761.stpipe.rst, jwst/extract_2d/tests/test_grisms.py, jwst/stpipe/core.py, jwst/stpipe/tests/test_step.py, jwst/tweakreg/tests/test_tweakreg.py
This PR adds a warning to `Step.__call__` uses to target end-users that might use this expecting the step to use reference files.
Note that `Step.__call__` is used in pipelines so the warning will only appear if `Step.__call__` is used outside a pipeline (it's used on a step that doesn't have a "parent").
If `Step.__call__` is removed, some decision will need to be made about what to do for pipeline uses of `Step.__call__`.
Regression tests show only failures that exist on main:
https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1694/
and do not show the new warning (so there is no use of `Step.__call__` (outside of a pipeline) in jwst.
Resolves [JP-3728](https://jira.stsci.edu/browse/JP-3728)
Closes #8748
**Checklist for PR authors (skip …
=> JP-3728: Deprecate `Step.__call__`

jwst/regtest/test_nirspec_ifu_spec3.py, jwst/regtest/test_nirspec_ifu_spec3_pixelreplace.py
This is a minor reorganization of tests in test_nirspec_ifu_spec3 to more efficiently run them in parallel.
This reduces regtests runtime by about 8 minutes.
jwst/regtest/test_nirspec_ifu_spec3.py contains 2 of the [slower](https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1744/testReport/jwst.regtest/test_nirspec_ifu_spec3/) regtests since the regtests run in parallel scoped by module these 2 tests end up in the same scope given to 1 worker. This worker then spends over 2 hours on those 2 tests (run serially). This PR splits jwst/regtest/test_nirspec_ifu_spec3.py putting the 2 slow fixtures in different files/modules so they can be run on different workers.
Ideally we'd start the slowest tests first so they could toil away while other workers run other tests. …
=> Speed up regtests by reorganizing test_nirspec_ifu_spec3

changes/8787.background.rst, jwst/background/background_sub.py, jwst/background/tests/test_background.py
Resolves [JP-3763](https://jira.stsci.edu/browse/JP-3763)
This PR addresses combining full and subarray observations to accumulate a background. This fixes an issue introduced with #8326, where if you try to use a full frame observation to create a background for a subarray observation, it would crash. This instead uses the best of both worlds: if a multi-int exposure, it will use NINTS from the background obs to form a mean background. If you're mismatching full/subarray observations, it'll use the x/y size of the science to avoid array size mismatches.
I can't run regression tests, but have verified it works in my case
=> JP-3763: Fix crash combining full and subarray for background

changes/8843.associations.rst, jwst/associations/lib/rules_level3_base.py
Resolves [JP-3305](https://jira.stsci.edu/browse/JP-3305)
This PR addresses an issue left behind after merging #8798 - that PR generates the correct associations from the MOSAIC association candidates, but left the bad associations as additional output. Those associations are duplicates of associations generated for observation candidates, but are not caught by the duplication checker in operations due to how the association generator is called (using a single candidate argument, i.e. `-i c1000`). The simple fix is to include `mosaic` in the list of association candidate types that require multiple observations.
- …
=> JP-3305: Clean up bad mosaic associations

changes/8853.outlier_detection.rst, jwst/outlier_detection/tests/test_outlier_detection.py, jwst/outlier_detection/utils.py
Closes #8845 
This PR is a follow up to #8782 and #8840, to address some small issues with intermediate processing when resample_data=False:
- Input models are now copied before being modified for thresholding purposes.
- Copies of the input models are not saved as intermediate data.
- …
=> Fix intermediate issues with non-resampled outlier methods

changes/8851.outlier_detection.rst, docs/jwst/outlier_detection/arguments.rst, docs/jwst/outlier_detection/outlier_detection_imaging.rst, jwst/outlier_detection/imaging.py, jwst/outlier_detection/outlier_detection_step.py, jwst/outlier_detection/spec.py
https://github.com/spacetelescope/jwst/pull/8782 added a pipeline-level `in_memory` flag to `calwebb_image3` that governs the `on_disk` status of the ModelLibrary that is passed through all the pipeline steps.  The same PR updated the outlier detection step to figure out whether the compute the median in-memory or using memory-saving options based on the `on_disk` status of the input ModelLibrary.  This is generally a good thing, because it means that the pipeline-level `in_memory` flag actually does enforce doing all computations in memory.  However, it also means that the step-specific `in_memory` flag for the OutlierDetectionStep is ignored when running the entire pipeline.
This PR updates the documentation to clarify the interaction between the pipeline-level and step-level …
=> Documentation and code updates clarifying the behavior of the ``in_memory`` flag

jwst/regtest/test_nircam_wfs.py
Update NIRCam WFS regression tests to use in-flight data.
Data used is PID 2586, obs 173 detector nrca3, found via a MAST search for NIRCam imaging public data with PATTYPE = WFSC.
This test had an unusual truth directory location ('truth/nircam/test_wfs-image2and3', where most truth directories are at 'truth/test_*').  I made a new truth directory following the more usual pattern and will delete 'truth/nircam' in artifactory when this is complete.
- …
=> JP-2928: Update NIRCam WFS regression test data

jwst/regtest/test_nircam_mtimage.py
Update NIRCam image moving target test to use in-flight data.
The data are a subset of the regression test data set identified by the NIRCam team.  I modified the association file to use only the 5 nrcblong input files, for speed.
- …
=> JP-2928: Update NIRCam image moving target regression test data

.github/workflows/ci.yml, .github/workflows/ci_cron.yml, .github/workflows/contexts.yml, .github/workflows/tests_devdeps.yml
I decided to just copy the workflow here and make the update to avoid the need to update crds (which is showing CI failures that I don't understand https://github.com/spacetelescope/crds/pull/1086).
This PR now copies the contexts workflow from crds into this repo, removes the hst and roman related calls and fixes the jwst curl command. This should be a self-contained fix.
- …
=> vendorize and fix crds workflow

changes/8870.outlier_detection.rst, docs/jwst/outlier_detection/arguments.rst, jwst/outlier_detection/outlier_detection_step.py
Resolves [JP-3705](https://jira.stsci.edu/browse/JP-3705)
Closes #8705
This PR removes the `nlow` and `nhigh` parameters from outlier detection, which were already deprecated in a previous build.
My IDE also noticed that the `_STEP_MODES` variable in `outlier_detection_step.py` is unused anywhere in the repository, so I snuck in its removal as well.
- …
=> JP-3705: Remove deprecated nlow and nhigh parameters from outlier detection step

jwst/lib/tests/test_set_telescope_pointing.py, jwst/regtest/test_nircam_mtimage.py
Move coverage tests for the `update_mt_kwds` function from regression tests to unit tests.  Synthetic data for the unit test is based on the existing file used for the regression test.
Merging this will allow removal of the old pre-flight input files from artifactory.
- …
=> JP-2928: Move test for moving target updates to unit test

jwst/regtest/test_nircam_image.py
Update the remaining NIRCam image tests to use in-flight data.
The `test_image3_closedfile` test was decided to be no longer useful, so it is removed.
The old input data for `test_nircam_frame_averaged_darks` is replaced with a similar exposure from PID 1205 obs 15: subarray SUB400P, NFRAMES = 8, GROUPGAP = 2.
- …
=> JP-2928: Update NIRCam image regression tests

.github/workflows/ci.yml
Pre-commit is currently failing due to setup-python using the default python in `PATH`
```
Run actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3
Warning: Neither 'python-version' nor 'python-version-file' inputs were supplied. Attempting to find '.python-version' file.
Warning: .python-version doesn't exist.
Warning: The `python-version` input is not set.  The version of Python currently in `PATH` will be used.
```
This updates the workflow to define a python version to trigger it to install an isolated python.
- …
=> fix pre-commit action

jwst/outlier_detection/tests/test_outlier_detection.py, jwst/outlier_detection/tso.py
https://github.com/spacetelescope/jwst/pull/8782 added the `nanmedian3D()` convenience function to outlier detection, which calls `np.nanmedian` on the zeroth axis in a way that avoids allocating a float64 array that is the same size as the input data, and also suppresses "all-NaN slice encountered" warnings.  This PR replaces a single instance of `np.nanmedian()` with `nanmedian3D` for TSO data when a rolling median (the default) is NOT requested.
Testing on one fake dataset, constructed by repeating the calints files from regtest/run_nircam_tsimage.py along the time axis until the input data shape was (2000, 64, 64), showed that this change makes no difference to the peak memory usage of the step.  The reasons are that (1) the memory performance of `np.nanmedian` does not scale as …
=> Use nanmedian3D for TSO data in outlier detection

jwst/regtest/test_nirspec_mos_spec2_steps.py, jwst/regtest/test_nirspec_steps_spec2.py
Use intermediate files generated from in-flight data already in artifactory as input for regression tests that test certain steps individually.  Tests are for NIRSpec spec2, input data is IFU and MOS.
- …
=> JP-2928: Update regression test data for NIRSpec spec2 steps

changes/8828.outlier_detection.rst, docs/jwst/outlier_detection/arguments.rst, docs/jwst/outlier_detection/outlier_detection_spec.rst, jwst/outlier_detection/_fileio.py, jwst/outlier_detection/outlier_detection_step.py, jwst/outlier_detection/spec.py, jwst/outlier_detection/tests/test_outlier_detection.py, jwst/outlier_detection/utils.py, jwst/resample/resample.py
Resolves [JP-3347](https://jira.stsci.edu/browse/JP-3347)
Modify outlier detection for spectral data, in order to threshold outliers for an exposure against an error value computed across exposures, instead of the input error for the exposure itself. This is intended to help address extreme outliers that have both very high data values and very high error values in the input exposure.
The process for resampled data is:
- drizzle the error array the same way as the science, to approximate a resampled error for each exposure
- median combine the drizzled error arrays across exposures, in the same way the drizzled science arrays are median combined
- blot the median error back to the input data coordinates, in the same way the median science image is handled
- compare (input data - blotted …
=> JP-3347: Improve spectral outlier detection

changes/8897.assign_wcs.rst, jwst/assign_wcs/tests/test_nircam.py, jwst/assign_wcs/util.py
Resolves [JP-3781](https://jira.stsci.edu/browse/JP-3781)
Closes #8896 
This PR addresses a bug that makes the s_region for imaging data slightly incorrect.  During testing of [AL-837](https://jira.stsci.edu/browse/AL-837), it was discovered that the footprint encoded in model.meta.wcsinfo.s_region is not the same as what you get from `wcs.footprint()`. By default in the pipeline, the s_region is currently calculated as the center of each corner pixel of the footprint using `stcal.alignment.util.compute_sregion_imaging(wcs, center=True)`, but it should calculate the true corners of the footprint using the same function but using the option `center=False`. There is even a [comment in that function](https://github.com/spacetelescope/stcal/blob/dfe1d6d51f0c2a400dff918a52c779328ae19b7d/src/stc …
=> JP-3781: Use center=False for compute_s_region_imaging

jwst/regtest/test_nircam_subarray_4amp.py
Update regression test data for NIRCam subarray, reference pixel correction test. 
~The new data is from PID 1409, obs 34, chosen for its similarity to the original data product (subarray subgrism64, exp_type nrc_tsimage, ngroups 5, nints 1).~
The new data is from PID 2459, obs 5: EXP_TYPE=NRC_TSIMAGE, SUBARRAY=SUBGRISM64, NINTS=4, NGROUPS=5, NOUTPUTS=4.                          
- …
=> JP-2928: Update regression test data for NIRCam subarray

jwst/regtest/test_niriss_sourcefind.py
This PR stores the regression test output catalog from `test_niriss_sourcefind.test_tweakreg_catalog_starfinder_alternatives` into the rtdata module, such that the files can be stored in the results directories and be used to okify the truth files when appropriate.
- …
=> Store NIRISS sourcefind regression test catalog in rtdata

changes/8892.skymatch.rst, jwst/skymatch/region.py
This PR fixes warnings emitted by skymatch when running with numpy 2. These seem to be the majority of warnings emitted by numpy 2.
- …
=> Fix numpy 2 warnings emitted from skymatch

changes/8908.resample_spec.rst, jwst/resample/resample_spec.py
Resolves [JP-3785](https://jira.stsci.edu/browse/JP-3785)
Closes #8905
This PR fixes an issue with the NIRSpec spectral resampled WCS transforms from resampled pixels to a sky tangent projection.  The transforms account for the additional extent of nodded slits along the tangent plane but the code currently only adds this correction for the sky direction that the slit is better aligned with.  This PR adds the necessary corrections for both tangent plane dimensions.
- …
=> JP-3785:  Add tangent plane transform corrections in NIRSpec spectral resampling

jwst/exp_to_source/exp_to_source.py
Resolves [JP-3725](https://jira.stsci.edu/browse/JP-3725)
Closes #8742 
This PR covers the removal of the DefaultOrderedDict class from exp_to_source.py.  The DefaultOrderedDict was only used when turning MultiExposureModels into SourceModelContainers. This class is no longer necessary as of Python 3.7, which specified that the default `dict` preserves order; the builtin `collections.defaultdict` can be used instead.
This PR is sufficient to resolve JP-3725 because it's the only thing relevant to SourceModelContainer that it makes sense to remove at this time.
- …
=> JP-3725: Remove DefaultOrderedDict

changes/8913.cube_build.rst, jwst/cube_build/ifu_cube.py, jwst/cube_build/src/cube_match_sky_driz.c
This PR tweaks some of the printed debugging information for spaxels in cube building, as discussed at JP-3788.
- …
=> JP-3788: Tweak spaxel debugging

changes/8918.datamodels.rst, jwst/datamodels/library.py, jwst/regtest/test_nirspec_ifu_spec3_moving_target.py, pyproject.toml
This PR includes the changes in #8917 to test the fix in this PR and updates the required stpipe version to main.
With these combined changes all regression tests (including the new one) pass:
https://github.com/spacetelescope/RegressionTests/actions/runs/11485771613/job/31967090526
Resolves [JP-3787](https://jira.stsci.edu/browse/JP-3787)
This PR  fixes the bug where ModelLibrary was using `meta.exptype` instead of `meta.asn.exptype`. A small change is needed to stpipe to allow jwst to control the exptypes added to the fake asn when `ModelLibrary` is constructed from a list of models.
- …
=> JP-3787: Use meta.asn.exptype in ModelLibrary

changes/8911.cube_build.rst, jwst/cube_build/ifu_cube.py
Resolves [JP-3750](https://jira.stsci.edu/browse/JP-3750)
Closes #8796
This PR addresses incorrect RA, Dec header information for `_s3d` and `_x1d` data products for moving-target IFU data.  The WCS correctly uses the MT_AVRA and MT_AVDEC as the reference point to build the cube, but the cube itself retains TARG_RA, TARG_DEC and MT_RA, MT_DEC values from the first input model instead of updating those to reflect the average of the inputs.
This also leads to a bug in the extract_1d step if the parameter `ifu_autocen` is set to False: the requested RA, Dec of the extraction point is outside the edge of the image as calculated by the WCS, and the code falls back to attempting extraction at the image center.  This bug is not encountered often because parameter reference files set …
=> JP-3750: Fix IFU cube moving target RA, Dec metadata

changes/8926.docs.rst, docs/jwst/user_documentation/running_pipeline_command_line.rst
Following https://github.com/spacetelescope/stpipe/pull/202 stpipe allows providing a package name to resolve ambiguous aliases provided to strun:
```
strun jwst::resample ...
```
This PR adds a note to the docs about when this might be needed.
Link to note: https://jwst-pipeline--8926.org.readthedocs.build/en/8926/jwst/user_documentation/running_pipeline_command_line.html#overview-of-running-the-pipeline-with-strun
As this PR doesn't touch code no regression tests were run.
- …
=> mention strun package name usage in docs

jwst/regtest/test_fgs_guider.py, jwst/regtest/test_fgs_image3.py
Update test data for FGS guider regression tests to in-flight examples.  Data is from PID 1029 obs 1, the same program as is used in the image2 test.  The EXP_TYPEs tested are FGS_ACQ1, FGS_FINEGUIDE, FGS_ID-IMAGE, FGS_ID-STACK.
There was also an image3 test on non-guider data in the `test_fgs_guider` module that checked the resample step with input data that makes too large a mosaic.  I moved this test to a new file (`test_fgs_image3.py`) and added a new test for image3 on FGS image data.  I used cal files for PID 1029 obs 1 for both tests.  To simulate the failure case on data that should succeed, I set the allowed memory environment variable to a small value.
- …
=> JP-2928: Update FGS guider test data, add image3 test

changes/8935.general.rst, pyproject.toml
A follow up to https://github.com/spacetelescope/jwst/pull/8887
downstream jwst testing in stdatamodels is showing errors:
https://github.com/spacetelescope/stdatamodels/actions/runs/11600882657/job/32302384136?pr=337#step:10:335
```
E               ValueError: ('Source %s: Needs to be a folder for use with pysiaf', PosixPath('/home/runner/work/stdatamodels/stdatamodels/.tox/py311-jwst-cov-xdist/lib/python3.11/site-packages/jwst/lib/tests/data/xml_data_siafxml/SIAFXML'))
```
Which appear to be due to missing test data files.
This PR adds those files to the package data (and should hopefully prevent the failures).
I tested this locally by pip installing jwst (non egg-link) and running the failing test with `--pyargs jwst`. I'm not sure at the moment if it's worth trying to update the CI …
=> include lib tests xml and db files in package data

CHANGES.rst, README.md, jwst/resample/resample_spec.py
Update the changelog and README to reflect the recent patch release.
- …
=> Update changelog and README to reflect patch release

changes/8958.general.rst, jwst/model_blender/_tablebuilder.py, jwst/model_blender/tests/test_blend.py
This PR updates the model blender to skip storing columns full of `nan` for values not defined in any input (blended) model.
Regression tests: https://github.com/spacetelescope/RegressionTests/actions/runs/11824762170
As expected this causes many regression tests differences in the `HDRTAB` extension generated by the model blender like the following:
```
E            Data contains differences:
E              Tables have different number of columns:
E               a: 224
E               b: 417
E              Extra column GSC_VER of format D in b
E              Extra column HGA_STRT of format D in b
E              Extra column HGA_STOP of format D in b
```
To take one example `jwst-pipeline/dev/truth/test_miri_cubebuild/jw01024-o001_t002_miri_ch1-short_s3d.fits` the truth file currently …
=> don't store empty columns in HDRTAB

changes/8947.pipeline.rst, jwst/pipeline/calwebb_spec2.py, jwst/regtest/test_nirspec_mos_movingtarget.py
Resolves [JP-3798](https://jira.stsci.edu/browse/JP-3798)
Closes #
This PR addresses an error found during reprocessing of an MSA moving target dataset. 
Regression tests: https://github.com/spacetelescope/RegressionTests/actions/runs/11750586205
- …
=> JP-3798: Transfer datamodel wcsinfo during Spec2Pipeline MOS+FS processing

jwst/regtest/test_miri_mrs_badpix_selfcal.py
Closes https://github.com/spacetelescope/jwst/issues/8968
This PR makes 2 changes to test_miri_mrs_badpix_selfcal_bkg to allow it's results to be okified.
1) The multiple comparisons are split into different tests using parametrization
2) The background comparisons set `rtdata.output` which is required to allow `okify_regtests` to know what files to replace
To provide some more details on 2 above. Currently this test is failing due to expected header comment differences:
```
a: result_bkgasn_badpix_selfcal_bkg_0.fits
b: /runner/_work/_temp/pytest_basetemp/popen-gw0/test_miri_mrs_badpix_selfcal_rtdata_module0/truth/result_bkgasn_badpix_selfcal_bkg_0.fits
HDU(s) not to be compared:
...
Headers contain differences:
Keyword DRPFRMS1 has different comments:
a> Number of frames dropped prior to …
```
=> restructure test_miri_mrs_badpix_selfcal_bkg to allow it to be okified

changes/8952.firstframe.rst, docs/jwst/firstframe/arguments.rst, jwst/firstframe/firstframe_step.py, jwst/firstframe/firstframe_sub.py, jwst/firstframe/tests/test_firstframe.py
Resolves [JP-3799](https://jira.stsci.edu/browse/JP-3799)
This PR modifies the firstframe step to optionally not flag the 1st group (aka frame) as DO_NOT_USE for pixels that have ramps that saturation between the 2nd and 3rd groups.   In the case of a pixel having a large signal, it has been found that the slope estimated from the 2nd-1st groups and 3rd-2nd groups is equivalent within 1% indicating that the firstframe effect is small compared to the signal in this specific case. This means that for pixels seeing very bright signal (i.e., saturating between the 2nd and 3rd groups), that the slope can be measured from the 1st and 2nd groups. This provides a slope measurement where previously there was none (i.e., a NaN value).
- …
=> JP-3799: First frame bright

jwst/ramp_fitting/tests/test_ramp_fit.py
Resolves [SCSB-166](https://jira.stsci.edu/browse/SCSB-166)
- ``changes/<PR#>.linearity.rst``
- …
=> unskip a regression test

jwst/refpix/irs2_subtract_reference.py, jwst/residual_fringe/tests/test_configuration.py, pyproject.toml
The only valid values for `cal_step` attributes are `SKIPPED` and `COMPLETE` (see [this example](https://github.com/spacetelescope/stdatamodels/blob/4ea7d9134cbe1f4a9fc554ecf0d4ba99ba811684/src/stdatamodels/jwst/datamodels/schemas/core.schema.yaml#L2295) in the corresponding schema).
This PR updates 2 places where an invalid value is set and adds a warning filter to turn the `ValidationWarning`s these assignments were creating into errors.
Regtests running: https://github.com/spacetelescope/RegressionTests/actions/runs/11980161291
- …
=> Cleanup validationwarning

jwst/lib/tests/test_siafdb.py, pyproject.toml
This PR addresses CI failures with py312-xdist caused by a tox testing method of ignoring the tests if an import fails. The import of pysiaf should work as expected with its inclusion in the test dependencies, so we can safely delete the failure catch.
- …
=> Remove testing statement to ignore import failure

jwst/lib/tests/test_engdb_mast.py
This PR updates `test_get_values` in `test_engdb_mast.py` to be compatible with numpy 2.0.
The test is currently failing for numpy 2.0:
https://github.com/spacetelescope/stdatamodels/actions/runs/12012372839/job/33483464825#step:10:345
due to to the change in the string representation of numpy scalars.
This PR updates the test by:
- dropping the string comparison (which was being used to compare numerical results)
- updates the expected values to match the actual values
The updated expected values are taken from:
https://github.com/spacetelescope/jwst/blob/94041ec7f7499f56d455a31a8b4ed13807d5e93d/jwst/lib/tests/test_engdb_mast.py#L16-L22
and allow the test to pass `assert values == expected` due to `engdb.get_values` parsing the `MJD` column to compute the `obstime`: …
=> update test for numpy 2 compatibility

changes/8966.general.rst, pyproject.toml
asdf 4.0.0 was released:
https://pypi.org/project/asdf/4.0.0/
Regression tests all pass with the new version:
https://github.com/spacetelescope/RegressionTests/actions/runs/11897984206
As asdf is semantically versioned this PR updates the asdf upper pin to "<5".
- …
=> bump asdf upper pin

jwst/scripts/okify_regtests.py
Removes use of `--flat` in okify_regtests that can result in file clobbering and failure to okify all differences.
Closes https://github.com/spacetelescope/jwst/issues/8969
- …
=> avoid file clobbering in okify

changes/8978.assign_wcs.rst, jwst/assign_wcs/nirspec.py
Addresses [JP-3664](https://jira.stsci.edu/browse/JP-3664)
Closes #
This PR addresses the fact that under numpy 2, the SHUTTRID values for NIRSPEC MOS data become negative for values >32767 due to their values being held in a signed short integer.  Casting to int64 before calculation (which is what is done implicitly under numpy 1.x) solves the problem.
Regression tests were run with numpy 1.x (no differences) and 2.x (unrelated differences, SHUTTRID differences went away)
- …
=> JP-3664: Fix shuttrid negative values under numpy 2

jwst/regtest/test_miri_mrs_spec3.py
Update MIRI MRS regtests for new default output cubes.
New locally-generated truth files are uploaded to artifactory.  Old files should be removed after merging. …
=> Update MIRI MRS spec3 regtest for new cube defaults

pyproject.toml
An alternative to https://github.com/spacetelescope/stcal/pull/323 which would stall stcal work but allow jwst to continue.
- …
=> pin stcal to commit

jwst/regtest/test_nircam_image.py
This PR fixes the regression test for the SIRS kernel option in the refpix step, adding a suffix to the output so it can be okified by script.
In the truth directory, jw01538046001_03105_00001_nrcalong_refpix_SIRS.fits is replaced by jw01538046001_03105_00001_nrcalong_sirs_refpix.fits.  I have uploaded the new truth file from a local run and will remove the old one when this is merged.
- …
=> Add suffix for SIRS refpix output so it can be okified

changes/9037.refpix.rst, jwst/refpix/refpix_step.py, jwst/regtest/test_nircam_image.py
This PR fixes a bug with the SIRS reference pixel subtraction introduced in https://github.com/spacetelescope/jwst/pull/8726
- …
=> Bugfix for SIRS reference pixel subtraction

.github/workflows/ci.yml, .github/workflows/ci_cron.yml, .github/workflows/contexts.yml, .github/workflows/tests_devdeps.yml
As this is all CI related marking as "no-changelog".
This PR partially reverts #8987 related commits with the following end results:
- retain using `jwst-edit` as the default virtual context
- remove uses of unstable crds jsonrpc call
- restore the `contexts` workflow to resolve the `jwst-edit` virtual context to a valid `pmap`
- cache based on the `pmap` (not the virtual context) (the main bug fix, the other changes are in support of this)
This (partially) addresses the recent CI failures:
- https://github.com/spacetelescope/jwst/actions/runs/12505212660/job/34888218044?pr=9004
- https://github.com/spacetelescope/jwst/actions/runs/12470838495/job/34806708238
- https://github.com/spacetelescope/jwst/actions/runs/12470838495/job/34806707933
- …
=> Update CRDS cache workflow usage to reduce random failures

changes/9036.tweakreg.rst, docs/jwst/tweakreg/README.rst, jwst/tweakreg/tests/test_tweakreg.py, jwst/tweakreg/tweakreg_step.py
Resolves [JP-3834](https://jira.stsci.edu/browse/JP-3834)
Closes #9035
This PR changes the default value for source finding to match the default algorithm (IRAFStarFind). Current values .exclude the sharpest stars
Regression tests: https://github.com/spacetelescope/RegressionTests/actions/runs/12528517548
- …
=> JP-3834: Update default values for the source finding in tweakreg to match the algorithm

jwst/outlier_detection/tests/test_outlier_detection.py
Resolves [JP-3822](https://jira.stsci.edu/browse/JP-3822)
Closes #9014 
Testing of https://github.com/spacetelescope/jwst/pull/8554 revealed two small problems with the structure of the outlier detection unit tests:
1) Prior to this PR, the mock data passed into many tests had incompatible values of `meta.instrument.detector`, `meta.instrument.name`, and `meta.exposure.type`; typically, only the exposure type was being changed.  This made it impossible to call AssignWCS because the proper distortion reference files could not be found.  As a workaround, AssignWCS was called just once assuming MIRI imaging, non-TSO data.  This PR makes it so AssignWCS is called separately for each mode, which may avoid future problems in resample caused by an unrealistic WCS.
2) Prior to this PR, every TSO, …
=> JP-3822: restructure outlier detection unit tests

docs/jwst/references_general/photom_reffile.inc
This PR fixes some errors in the MRS photom file documentation.
- …
=> Update MRS photom documentation

README.md
Addresses [JP-3840](https://jira.stsci.edu/browse/JP-3840)
Closes #9060 
This PR addresses an install issue caused by an incorrect upper pin on `gwcs` for releases 1.15.1 through 1.16.1 - the suggested workaround given in the README is to downgrade the installed version to < 0.22.
- …
=> JP-3840: Include gwcs install warning and stasis install details

jwst/extract_1d/tests/conftest.py
There seems to be a minimization instability in the SOSS extraction unit tests for substrip96 with numpy 2 across different architectures.  I can't reproduce it on my Mac, but regression tests on Linux (e.g. https://github.com/spacetelescope/RegressionTests/actions/runs/12717188152) persistently show a significantly different output spectrum -- all values should be ~30-40, but on Linux have a ~20 element dip below zero.  The input data is pathological (all ones), so I added a little noise to simulate more realistic fitting conditions.  This makes the output more robust across architectures and numpy versions.
Regression test for this unit test alone is here:
https://github.com/spacetelescope/RegressionTests/actions/runs/12750293801
Attempt 3 includes these changes and is now passing with …
=> Fix extract_1d unit test failure under numpy 2

README.md, docs/getting_started/quickstart.rst, docs/jwst/user_documentation/reference_files_crds.rst
Resolves [JP-3838](https://jira.stsci.edu/browse/JP-3838)
This PR addresses JP-3838 regarding proper usage of the CRDS_SERVER_URL in both internal and external network configurations.
- …
=> JP-3838: Update README description of CRDS setup

jwst/assign_wcs/tests/test_schemas.py
Now that stdatamodels 2.2.0 is out (and used here) we can remove the now unnecessary warning filter added in https://github.com/spacetelescope/jwst/pull/8693
Closes https://github.com/spacetelescope/stdatamodels/issues/314
- …
=> remove no longer needed warning filter

jwst/clean_flicker_noise/clean_flicker_noise.py
Very small fix to address a unit test failure under numpy 2: sizes in the log message were printing as `np.int(25)` instead of `25`.
- …
=> Convert np.int to int for logging in numpy 2

changes/9102.assign_wcs.rst, jwst/assign_wcs/nirspec.py, jwst/assign_wcs/tests/test_nirspec.py
Working on a helpdesk ticket, I noticed a bug with NIRSpec imaging WCS transforms when the filter is OPAQUE.  The detector to MSA transform works, e.g.:
`img_det2msa = img_wcs.get_transform('detector', 'msa')`
but fetching the inverse transform crashes:
`img_msa2det = img_wcs.get_transform('msa', 'detector')`
The issue is a scale factor added to the end of the WCS transform to report final wavelengths in um instead of m. The implemented scaling model overwrites the inverse transform in the gwa2msa transform, so that it expects the wrong number of input and output values.  
The fix here is to apply the scaling earlier for wavelengths for terminal MSA coordinates, before the gwa2msa transform and its inverse are defined.
Test data is: jw06646012001_02101_00001_nrs1_rate.fits …
=> Fix msa frame transform for opaque images

.github/workflows/build.yml, .github/workflows/changelog.yml
A few CI jobs started using python 3.13. This is causing changelog check and build failures.
This PR:
- updates the changelog workflow to use python 3.12
- updates the build workflow to use a custom workflow
The custom workflow is needed until either:
- https://github.com/OpenAstronomy/github-actions-workflows/pull/264
- or python 3.13 can be supported by jwst
- …
=> build sdist with python 3.13 (point to workflow fork)

.github/workflows/ci.yml, .pre-commit-config.yaml, CONTRIBUTING.md, jwst/badpix_selfcal/badpix_selfcal.py, pyproject.toml, tox.ini
Closes #9103 
This PR moves the mypy type check out of the `tox.ini` file and into the `pre-commit-config.yaml` file. This makes it so that all the style checks occur in one place, and makes it so that the mypy checks are part of our pre-commit hook.
- …
=> Move mypy type hint checking into pre-commit

.pre-commit-config.yaml, .ruff.toml, changes/9107.pixel_replace.rst, jwst/pixel_replace/__init__.py, jwst/pixel_replace/pixel_replace.py, jwst/pixel_replace/pixel_replace_step.py
Partially resolves [JP-3862](https://jira.stsci.edu/browse/JP-3862)
This PR addresses code style issues in the pixel_replace module.
- …
=> JP-3862: Apply code style to pixel_replace module

.pre-commit-config.yaml, .ruff.toml, jwst/clean_flicker_noise/__init__.py, jwst/clean_flicker_noise/clean_flicker_noise.py, jwst/clean_flicker_noise/clean_flicker_noise_step.py, jwst/clean_flicker_noise/lib.py, jwst/nsclean/__init__.py, jwst/nsclean/nsclean_step.py
Partially addresses [JP-3859](https://jira.stsci.edu/browse/JP-3859)
Also ignores rule TRY400, which requires log.exception instead of log.error inside an except clause.  No need to enforce tracebacks every time we log an error.
Code style updates for clean_flicker_noise and nsclean
- …
=> JP-3859: Apply code style to clean_flicker_noise and nsclean

.github/workflows/build.yml, .github/workflows/changelog.yml, .github/workflows/ci.yml, .github/workflows/ci_cron.yml, .ruff.toml, changes/9116.general.rst, docs/getting_started/install.rst, pyproject.toml
This PR drops support for python 3.10 as per [SPEC0](https://scientific-python.org/specs/spec-0000/).
Regtests run in python 3.12:
https://github.com/spacetelescope/RegressionTests/actions/runs/13021815724/job/36323966628#step:30:28
so they won't be run for this PR.
The oldest deps job (required as per the branch protections) with this PR runs with python 3.11. This branch protection rule will need to be updated when this PR is merged.
Also fixes #9110 since a new version of the build workflow was [released](https://github.com/OpenAstronomy/github-actions-workflows/releases/tag/v1.16.0) with the required [changes](https://github.com/OpenAstronomy/github-actions-workflows/pull/264).
- ``changes/<PR#>.general.rst``: infrastructure or …
=> drop support for python 3.10

.pre-commit-config.yaml, .ruff.toml, jwst/datamodels/library.py, jwst/outlier_detection/__init__.py, jwst/outlier_detection/_fileio.py, jwst/outlier_detection/coron.py, jwst/outlier_detection/ifu.py, jwst/outlier_detection/imaging.py, jwst/outlier_detection/outlier_detection_step.py, jwst/outlier_detection/spec.py, jwst/outlier_detection/tso.py, jwst/outlier_detection/utils.py
Partially Resolves [JP-3860](https://jira.stsci.edu/browse/JP-3860)
This PR addresses style issues with the outlier detection submodule.
A singular change has been added outside `outlier_detection`, which is to avoid direct calls to `ModelLibrary._on_disk` by making the non-underscore-protected `on_disk` a property.
This PR also makes the following small updates to the pre-commit configuration:
-  adds the `--summary` option to `codespell` so it shows what changes it made automatically.
-  adds "D105: missing docstring for magic method" to the ruff ignore list.  This rule would require docstrings for `__iter__`, `__len__` and similar, where it's very often obvious what it does and the function itself is a one-liner.
- …
=> Fix code style in outlier detection

changes/9095.ramp_fitting.rst, docs/jwst/ramp_fitting/arguments.rst, docs/jwst/ramp_fitting/description.rst, jwst/ramp_fitting/ramp_fit_step.py, jwst/ramp_fitting/tests/test_ramp_fit_step.py
Added a unit test and updated docs
Resolves [JP-3777](https://jira.stsci.edu/browse/JP-3777)
Closes #8872
This PR addresses JP-3777.  It enables users to select firstgroup and lastgroup parameters when performing
ramp fitting.  It works by setting the DO_NOT_USE bit in the GROUPDQ extension for groups outside the selected range.
Added a unit test and updated the docs.
- …
=> JP-3777: Select first and last groups in ramp fitting

.pre-commit-config.yaml, docs/conf.py, pyproject.toml
Patches https://github.com/spacetelescope/jwst/pull/9116 
This PR removes three instances where `tomli` is specified as a dependency.  Tomli is no longer necessary for Python >=3.11, as `tomllib` was added to the standard library by [PEP680](https://peps.python.org/pep-0680/).
See also the [Codespell readme](https://github.com/codespell-project/codespell?tab=readme-ov-file#using-a-config-file) stating that `tomli` doesn't need to be a dependency for Python >= 3.11 for codespell.
- …
=> Remove tomli, no longer relevant for 3.11

changes/9098.associations.rst, jwst/associations/generator/generate_per_candidate.py, jwst/associations/load_as_asn.py, jwst/associations/main.py, jwst/regtest/test_associations_sdp_pools.py
Resolves [JP-3116](https://jira.stsci.edu/browse/JP-3116)
Closes #7819 
This PR adds conditional behavior for association generation for DMS; when generating associations for a observation candidate ("o-type"), any science exposures belonging to a background ("c-type") candidate are dropped from consideration. This PR propagates the `DMS` flag of `asn_generate` down to the appropriate function where the new functionality was added. 
Currently in draft; this PR as currently written also modifies level 3 association behavior, which is not strictly part of the JIRA ticket request.
- …
=> JP-3116: Do not create observation-only Level 2 associations if part of a background candidate

.pre-commit-config.yaml, .ruff.toml, jwst/source_catalog/__init__.py, jwst/source_catalog/_wcs_helpers.py, jwst/source_catalog/detection.py, jwst/source_catalog/reference_data.py, jwst/source_catalog/source_catalog.py, jwst/source_catalog/source_catalog_step.py
Partially Resolves [JP-3860](https://jira.stsci.edu/browse/JP-3860)
This PR brings the source_catalog step into compliance with the new code style rules.
- …
=> Apply code style rules to source_catalog

jwst/source_catalog/source_catalog_step.py
Add a space to fix formatting error on main.
- ``changes/<PR#>.linearity.rst``
- ``changes/<PR#>.rscd.rst``
- …
=> Fix formatting error

.pre-commit-config.yaml, .ruff.toml, changes/9085.assign_wcs.rst, changes/9085.barshadow.rst, jwst/assign_wcs/nirspec.py, jwst/assign_wcs/tests/test_nirspec.py, jwst/barshadow/__init__.py, jwst/barshadow/bar_shadow.py, jwst/barshadow/barshadow_step.py, jwst/barshadow/tests/test_barshadow.py, jwst/barshadow/tests/test_barshadow_step.py, jwst/extract_1d/extract.py, jwst/extract_2d/nirspec.py
Resolves [JP-3796](https://jira.stsci.edu/browse/JP-3796)
Partially resolves [JP-1341](https://jira.stsci.edu/browse/JP-1341)
There are two approximations being made in the barshadow correction that are not scaling well to the very long "slitlet" in MOS data taken in longslit mode.
The first is related to [JP-1341](https://jira.stsci.edu/browse/JP-1341): there are two different definitions of slit height. The barshadow correction needs the full bar-to-bar height, but the slit coordinates in the WCS use the open area height. The barshadow code currently hard-codes the ratio between the full and open heights as 1.15, but the value actually varies a bit by quadrant. I'm proposing that we use the equation in [JP-1341](https://jira.stsci.edu/browse/JP-1341) to calculate and store the scale …
=> JP-3796: Scale barshadow correction to long slits

.pre-commit-config.yaml, .ruff.toml, jwst/badpix_selfcal/__init__.py, jwst/badpix_selfcal/badpix_selfcal.py, jwst/badpix_selfcal/badpix_selfcal_step.py
Partially Resolves [JP-3860](https://jira.stsci.edu/browse/JP-3860)
This PR updates the `badpix_selfcal` step to comply with the new code style rules.
- …
=> Apply code style rules to badpix_selfcal

docs/jwst/data_products/msa_metadata.rst
This PR fixes a small error in the MSA metadata description of source coordinates within a shutter identified in a helpdesk ticket (INC0207529).
- …
=> Correct error in MSA metadata coordinate description

.pre-commit-config.yaml, .ruff.toml, jwst/lastframe/__init__.py, jwst/lastframe/lastframe_step.py, jwst/lastframe/lastframe_sub.py
Partilly addresses [JP-3857](https://jira.stsci.edu/browse/JP-3859)
Code style updates for the last frame step.
At this time I have not updated the code in test
-https://github.com/spacetelescope/RegressionTests/actions/runs/13183133505
- …
=> Apply basic code style changes to lastframe step 

.pre-commit-config.yaml, .ruff.toml, jwst/extract_1d/__init__.py, jwst/extract_1d/soss_extract/__init__.py, jwst/extract_1d/soss_extract/atoca.py, jwst/extract_1d/soss_extract/atoca_utils.py, jwst/extract_1d/soss_extract/pastasoss.py, jwst/extract_1d/soss_extract/soss_boxextract.py, jwst/extract_1d/soss_extract/soss_extract.py, jwst/extract_1d/soss_extract/soss_syscor.py, jwst/extract_1d/soss_extract/tests/conftest.py, jwst/extract_1d/soss_extract/tests/test_atoca.py, jwst/extract_1d/soss_extract/tests/test_atoca_utils.py
Partially resolves [JP-3860](https://jira.stsci.edu/browse/JP-3860)
This PR updates the `soss_extract` submodule to comply with the new code style rules.
Since `soss_extract` is nestled inside `extract_1d`, I had to add some ugly per-file-ignores to `.pre-commit-config.yaml` and `.ruff.toml`; these can be removed once the rest of `extract_1d` is updated to follow the style rules.
As a procedural note, I added a line to the epic labeled `soss_extract` and assigned it to myself, then removed my name from the assignment list next to `extract_1d` so someone else could pick up the rest of the step.
- …
=> Apply code style rules to soss_extract

jwst/regtest/test_fgs_guider.py
Causes [JP-3878](https://jira.stsci.edu/browse/JP-3878)
This PR xfails the `test_fgs_guider` regression test, which is expected to continue failing until CRDS updates are completed. This xfail addition will be tracked by JP-3878 to prevent it from lingering for longer than it should.
- …
=> Xfail test_fgs_guider until CRDS files are repaired

.pre-commit-config.yaml, .ruff.toml, jwst/firstframe/__init__.py, jwst/firstframe/firstframe_step.py, jwst/firstframe/firstframe_sub.py
Partially resolves [JP-3855](https://jira.stsci.edu/browse/JP-3855)
This PR updates the first frame step to use the new code style rules. 
- …
=> Update codestyle for first frame step

.pre-commit-config.yaml, .ruff.toml, jwst/jump/__init__.py, jwst/jump/jump_step.py
Partially resolves [JP-3855](https://jira.stsci.edu/browse/JP-3855)
Partially resolves [JP-3856](https://jira.stsci.edu/browse/JP-3856)
This PR addresses code style changes for the jump step.
- …
=> JP-3856: Code Style Updates to Jump Step

.pre-commit-config.yaml, .ruff.toml, jwst/ramp_fitting/__init__.py, jwst/ramp_fitting/ramp_fit_step.py, jwst/ramp_fitting/tests/check_gls_stats.py, jwst/ramp_fitting/tests/test_ramp_fit.py
Partially resolves [JP-5856](https://jira.stsci.edu/browse/JP-5856)
Partially resolves [JP-5855](https://jira.stsci.edu/browse/JP-5855)
This PR addresses the style checkers using `pre-commit`.
- …
=> JP-3856: Style Updates for Ramp Fitting

.pre-commit-config.yaml, .ruff.toml, jwst/dq_init/__init__.py, jwst/dq_init/dq_init_step.py, jwst/dq_init/dq_initialization.py
Resolves [JP-3856](https://jira.stsci.edu/browse/JP-3856)
Resolves [JP-3855](https://jira.stsci.edu/browse/JP-3855)
This PR addresses code style changes for the DQ init step.
- …
=> JP-3855: Style Updates for DQ init

.pre-commit-config.yaml, .ruff.toml, jwst/charge_migration/__init__.py, jwst/charge_migration/charge_migration.py, jwst/charge_migration/charge_migration_step.py
Resolves [JP-3855](https://jira.stsci.edu/browse/JP-3855)
Resolves [JP-3856](https://jira.stsci.edu/browse/JP-3856)
This PR addresses code style changes for the charge migration step.
- …
=> JP-3856: Style Updates for Charge Migration

.pre-commit-config.yaml, .ruff.toml, changes/9128.wavecorr.rst, jwst/wavecorr/__init__.py, jwst/wavecorr/tests/test_wavecorr.py, jwst/wavecorr/wavecorr.py, jwst/wavecorr/wavecorr_step.py
Partially addresses [JP-3859](https://jira.stsci.edu/browse/JP-3859)
Clean up code style in wavecorr.
Also fixed a few minor logic errors in edge cases and added a few unit tests to complete coverage. …
=> JP-3859: Apply code style rules to wavecorr

changes/9186.resample.rst, jwst/resample/resample_spec.py, jwst/resample/resample_utils.py
Fixes a minor bug in `resampled_wcs_from_models` with an unused function input parameter being left inadvertently in the code. Simplified the code.
Closes #9185
- …
=> Fix a bug in resampled_wcs_from_models

.pre-commit-config.yaml, .ruff.toml, jwst/skymatch/__init__.py, jwst/skymatch/skymatch_step.py
Partially Resolves [JP-3860](https://jira.stsci.edu/browse/JP-3860)
This PR applies code style changes to the skymatch step.
- …
=> Apply code style checks to skymatch step

.pre-commit-config.yaml, .ruff.toml, changes/9190.associations.rst, changes/9190.imprint.rst, changes/9190.pipeline.rst, docs/jwst/imprint/description.rst, jwst/associations/lib/rules_level2_base.py, jwst/associations/lib/rules_level2b.py, jwst/imprint/__init__.py, jwst/imprint/imprint_step.py, jwst/imprint/tests/test_imprint.py, jwst/pipeline/calwebb_spec2.py
Resolves [JP-3852](https://jira.stsci.edu/browse/JP-3852)
Resolves [JP-3853](https://jira.stsci.edu/browse/JP-3853)
Several related issues are fixed here:
1. Imprints were missing from level 2 associations in the case where there was a single imprint taken, intending to match all science dithers.  This was introduced when dither position was added as a required constraint in #8410.
2. Extra imprints were added to level 2 associations in the case where there were multiple imprints taken in an observation, intending to match separately to different targets.
3. Separate imprints intended for science and dedicated background targets were not handled separately in the imprint subtraction step, so the match to targets was inaccurate.
To fix the association issues, I removed the dither position …
=> JP-3852 and JP-3853: Fix imprint associations for NRS IFU

docs/jwst/skymatch/description.rst
Resolves [JP-3843](https://jira.stsci.edu/browse/JP-3843)
Fixes #9063 
This PR adds description of image groups in relation to sky matching and when grouping is desirable or not.
=> Document image group usage for sky matching

jwst/resample/tests/test_resample_step.py
This PR fixes one of the failing tests after GWCS supports bounding box check on inverse WCS  transforms.
This PR requires https://github.com/spacetelescope/stcal/pull/326 to be merged first. …
=> Fix test for custom WCS for imaging

.pre-commit-config.yaml, .ruff.toml, jwst/pathloss/__init__.py, jwst/pathloss/pathloss.py, jwst/pathloss/pathloss_step.py
Partially addresses [JP-3861](https://jira.stsci.edu/browse/JP-3861)
Closes #
This PR applies style changes to the pathloss step files …
=> JP-3861: Apply code style changes for pathloss step

changes/9212.align_refs.rst, jwst/coron/align_refs_step.py
This PR replaces the one use of `stdatamodels.dqflags.interpret_bit_flags` with `astropy.nddata.bitmask.interpret_bit_flags`. The astropy function is used throughout jwst code and after this PR stdatamodels can remove `interpret_bit_flags`.
Regression tests all pass: https://github.com/spacetelescope/RegressionTests/actions/runs/13465888407
- …
=> use astropy for interpret_bit_flags

changes/9204.background.rst, jwst/background/background_sub_wfss.py, jwst/background/tests/test_background_wfss.py, pyproject.toml
Resolves [JP-3808](https://jira.stsci.edu/browse/JP-3808)
Closes #8992 
https://github.com/spacetelescope/stdatamodels/pull/407 defines a new schema attribute, `model.meta.background.scaling_factor`, to store the scaling factor from the background step.
This PR stores the scaling factor computed for WFSS data during the background step into that attribute.
- …
=> JP-3808: Store scaling factor for WFSS data in background step

changes/9214.outlier_detection.rst, docs/jwst/outlier_detection/outlier_detection_imaging.rst, jwst/outlier_detection/outlier_detection_step.py
Resolves [JP-3744](https://jira.stsci.edu/browse/JP-3744)
Closes #8779
This PR makes the default of the `in_memory` flag True for the outlier detection step.  The work for JP-3744 was mostly completed in build 11.2, and the outlier step is the only holdout with an `in_memory` default that is not True.  This PR updates that, making the default consistent with the other steps in image 3.  Note that this setting is ignored when running the entire calwebb_image3 pipeline.
- …
=> JP-3744: set outlier step default to in-memory processing

docs/jwst/user_documentation/parameters.rst
Resolves [JP-3812](https://jira.stsci.edu/browse/JP-3812)
Add documentation for output_ext='asdf'.
This is a follow up to an old ticket closed recently: #1757
- …
=> JP-3812: Add output_ext documentation

.pre-commit-config.yaml, .ruff.toml, jwst/extract_1d/apply_apcorr.py, jwst/extract_1d/extract.py, jwst/extract_1d/extract1d.py, jwst/extract_1d/extract_1d_step.py, jwst/extract_1d/ifu.py, jwst/extract_1d/psf_profile.py, jwst/extract_1d/source_location.py, jwst/extract_1d/spec_wcs.py, jwst/extract_1d/tests/conftest.py, jwst/extract_1d/tests/test_apply_apcorr_ifu.py, jwst/extract_1d/tests/test_apply_apcorr_nonifu.py, jwst/extract_1d/tests/test_expected_skips.py, jwst/extract_1d/tests/test_extract.py, jwst/extract_1d/tests/test_extract_1d_step.py, jwst/extract_1d/tests/test_extract_src_flux.py, jwst/extract_1d/tests/test_fit_background_model.py, jwst/extract_1d/tests/test_psf_profile.py, jwst/extract_1d/tests/test_source_location.py
Partially addresses [JP-3859](https://jira.stsci.edu/browse/JP-3859)
Update remaining extract_1d modules for code style fixes.
- …
=> JP-3859: Apply code style rules to extract_1d

.pre-commit-config.yaml, .ruff.toml, changes/9141.guider_cds.rst, jwst/guider_cds/__init__.py, jwst/guider_cds/guider_cds.py, jwst/guider_cds/guider_cds_step.py, jwst/guider_cds/tests/test_guider_cds.py, jwst/regtest/test_fgs_guider.py
Partially resolves [JP-3862](https://jira.stsci.edu/browse/JP-3862)
Relates to [CRDS-917](https://jira.stsci.edu/browse/CRDS-917)
Addresses [JP-3878](https://jira.stsci.edu/browse/JP-3878)
This PR addresses code style issues and some hard-wired reference file information present in the `guider_cds` step.
Unfortunately, we weren't able to completely remove some "workaround" behavior - for `FGS_ID-STACK` data, there is no gain or readnoise reference file matching the data array shape. In conversation with Pierre Chayer of the FGS team, it was confirmed that ID products are used to visually check where guide star and reference stars are located, but are not expected to be fully calibrated products; for stacked data, then, we apply the mean value of the fetched reference file array to the …
=> JP-3862: Clean up guider_cds step for code style and CRDS inconsistencies

jwst/outlier_detection/utils.py
I noticed while testing some MIRI LRS spec3 data that a warning message was issued from outlier_detection with a default pipeline run:
` WARNING - Returning median_error has been disabled since input 'resamp' object does not have 'compute_err' attribute set to 'driz_err'.`
I tracked it down to a misplaced warning message -- median_error is being computed as expected.  I moved the warning message so it does not appear when it shouldn't.
- …
=> Fix inaccurate warning message for median_error computation

docs/jwst/assign_wcs/arguments.rst, jwst/assign_wcs/assign_wcs_step.py
Resolves [JP-3608](https://jira.stsci.edu/browse/JP-3608)
Document the `slit_y_low` and `slit_y_high` parameter values for the assign_wcs step.
- …
=> JP-3608: Document slit low/high parameters

changes/9257.docs.rst, docs/index.rst, docs/jwst/stpipe/user_logging.rst, docs/jwst/user_documentation/logging.rst
This PR adds a docs section describing the `cal_logs` added in https://github.com/spacetelescope/jwst/pull/9211
To aid in the discovery of this section this PR renames the `Logging Configuration` section of `User Documentation` to the more general `Logging`.
Link to docs: https://jwst-pipeline--9257.org.readthedocs.build/en/9257/jwst/user_documentation/logging.html#datamodel-cal-logs
- …
=> mention cal_logs in docs

jwst/barshadow/tests/test_barshadow_step.py, jwst/clean_flicker_noise/tests/test_clean_flicker_noise.py, jwst/clean_flicker_noise/tests/test_clean_flicker_noise_step.py, jwst/conftest.py, jwst/extract_1d/tests/test_extract.py, jwst/extract_1d/tests/test_psf_profile.py, jwst/extract_1d/tests/test_source_location.py, jwst/ramp_fitting/tests/test_ramp_fit_step.py
Closes #9244 
Add a log_watcher fixture that can be configured with a specific log name, for use in unit tests.  Replace all local `log_watcher` fixtures with calls to the more general implementation
This should cut down on code duplication and make log message testing easier to use.
If this is merged first, #9216 should be updated to use the new fixture.
- …
=> Add flexible log_watcher fixture

.pre-commit-config.yaml, .ruff.toml, changes/9187.emicorr.rst, changes/9216.emicorr.rst, docs/jwst/emicorr/arguments.rst, docs/jwst/emicorr/description.rst, docs/jwst/emicorr/reference_files.rst, docs/jwst/references_general/emi_reffile.inc, jwst/emicorr/__init__.py, jwst/emicorr/emicorr.py, jwst/emicorr/emicorr_step.py, jwst/emicorr/tests/test_emicorr.py, jwst/regtest/test_miri_lrs_slitless.py, jwst/tests/helpers.py
Resolves [JP-3597](https://jira.stsci.edu/browse/JP-3597)
Resolves [JP-3674](https://jira.stsci.edu/browse/JP-3674)
Add a new algorithm for fitting and removing EMI noise in MIRI ramps. 
In addition, a few minor bugs in the existing algorithm are fixed here:
- intermediate reference files generated on-the-fly were not formatted correctly and could not be saved
- retrieving subarray cases from the reference file sometimes returned incorrect matches
- the `minmed` function was not performing minimum calculations instead of median when nframes <= 2 as described
I have also added almost-complete unit test coverage for the new and existing algorithms, fixed code style for the new standards, updated documentation, and added a regression test for the new algorithm.  Truth files for the new …
=> JP-3597: Add new algorithm for EMI fit; clean up existing code

changes/9338.ramp_fitting.rst, jwst/ramp_fitting/ramp_fit_step.py
No JP ticket or issue for this fix
This PR puts back the __all_ statement that got inadvertently removed in a previous PR
=> Fix inadvertent removal of __all__

docs/jwst/data_products/science_products.rst
Closes #9340 
Update ramp docs to remove reference to ERR array, which is no longer present in ramp products.
=> Remove reference to ERR in ramp docs

changes/9337.resample.rst, jwst/resample/resample_spec.py
Resolves [JP-3947](https://jira.stsci.edu/browse/JP-3947)
Closes #9309 
This PR addresses fixes a bug in how MIRI LRS data are resampled.
=> JP-3947 Fix MIRI LRS Flux error

.github/pull_request_template.md
This PR addresses the problem of auto closing a GitHub issue when there is JIRA ticket attached. Autoclosing messes up with the JIRA bot workflow and should be avoided.
=> Clarify when to use closes in PR template

changes/8943.associations.rst, jwst/associations/lib/rules_level2_base.py, jwst/associations/lib/rules_level3_base.py, jwst/associations/tests/test_level3_product_names.py, jwst/associations/tests/test_level3_spectrographic.py
Resolves [JP-3795](https://jira.stsci.edu/browse/JP-3795)
A couple fixes for target group observations:
- Update background member identification for spec2 for NIRSpec FS and MOS nodded spectral data to exclude mismatched target IDs
- Update output file names for NIRSpec FS spec3 to include the target ID
Note that this will change the spec3 filenames -- DMS will need a heads-up.
- …
=> JP-3795: Target group association fixes

changes/9254.barshadow.rst, changes/9254.pathloss.rst, changes/9254.wavecorr.rst, docs/jwst/barshadow/description.rst, docs/jwst/pathloss/description.rst, docs/jwst/wavecorr/description.rst, jwst/barshadow/bar_shadow.py, jwst/barshadow/tests/test_barshadow_step.py, jwst/extract_1d/extract.py, jwst/extract_1d/tests/test_extract.py, jwst/pathloss/pathloss.py, jwst/pathloss/tests/test_pathloss_step.py, jwst/wavecorr/tests/test_wavecorr.py, jwst/wavecorr/wavecorr.py
Resolves [JP-3630](https://jira.stsci.edu/browse/JP-3630)
Add some new informational keys to multi-slit data to make clear which slit-specific processing has taken place.  Affected data is NIRSpec MOS and FS; keys are added for wavecorr, pathloss, and barshadow steps.
Requires an stdatamodels change to add the new keys to the slit and spec datamodels: https://github.com/spacetelescope/stdatamodels/pull/431,
now merged.
Also, I noticed in passing a small bug in pathloss and corrected it here: the error propagation is incorrect when the step is inverted.  Error values are not currently used in steps that require the inversion, so there should be no impact to current data products. I added unit tests to verify the change as well as some basic coverage tests.
<details><summary>news fragment …
=> JP-3630: Add slit-specific processing metadata

.ruff.toml
This PR reverts adding G004 into the checks. It was added in https://github.com/spacetelescope/jwst/pull/9276 . Addressing formatting of logger string is now on hold.
No need for regression tests.
Alternative to #9292
=> Revert addition of G004 from PR 9276

jwst/clean_flicker_noise/tests/test_clean_flicker_noise_step.py, jwst/emicorr/tests/test_emicorr.py
Resolves [JP-3912](https://jira.stsci.edu/browse/JP-3912)
This PR modifies some tests for steps that have skip=True by default.  The new tests verify that when a step is called standalone, step.skip is True.  Also, each step is run in a pipeline and the meta.cal_step.step is checked for the
appropriate value "SKIPPED" or "COMPLETE", depending on whether skip is True or False respectively.
=> JP-3912: Modify some tests for steps that are skipped by default

README.md
Remove plwishmaster link, update with link to new scheduled regtests.
I removed the description of the schedule as it's redundant to the workflows in the regtest repo and unlikely to stay in sync if those workflows are updated.
Only a readme change so no regtests will be run.
=> update readme for new regtests

docs/jwst/tweakreg/README.rst, jwst/regtest/test_nircam_align_to_gaia.py, jwst/tweakreg/tweakreg_step.py
Reverts spacetelescope/jwst#9346
This PR was merged without noticing that it requires a matching PR in stcal, which has not yet been part of an stcal release. Because this is not a critical fix to get into B11.3, I'm reverting the changes out of this release branch and will leave it in main to be gathered in B12.0 releases.
=> Revert "Backport PR #9301 on branch release/1.18.x (JP-3686: Test using source catalog output as tweakreg abs_refcat)"

jwst/regtest/test_miri_image.py, jwst/regtest/test_nircam_coron3.py, jwst/regtest/test_niriss_soss.py, jwst/regtest/test_nirspec_mos_spec3.py, pyproject.toml
Partially addresses [JP-3775](https://jira.stsci.edu/browse/JP-3775)
This PR tests the implementation of the new resource_tracker pytest fixture to track memory usage and runtime.
=> JP-3775: Test ci_watson resource_tracker implementation

changes/9376.background.rst, changes/9376.clean_flicker_noise.rst, jwst/background/background_sub_wfss.py, jwst/clean_flicker_noise/clean_flicker_noise.py, jwst/regtest/test_niriss_soss.py
Resolves [JP-3982](https://jira.stsci.edu/browse/JP-3982)
Testing changes in preparation for numpy 2.3.0, to fix devdeps tests.
I added higher float precision in some sum and mean calculations that are affected by a change in buffer sizes in numpy 2.3.0.  This introduces some regtest changes for clean_flicker_noise and WFSS background steps in the current build, but they should now be the same changes in devdeps with numpy 2.3.0.dev0 and in the standard run.  The differences are not scientifically significant.  When this is okified, devdeps should have fewer failures.  It's a little hard to make sure of this from the regtest reports, though, so a follow up PR may be needed if there are other changes revealed by resolving these ones.
I also introduced a change here to the SOSS extras …
=> JP-3982: numpy 2.3.0 accommodation

jwst/lib/exposure_types.py, jwst/lib/set_telescope_pointing.py
This PR addresses two checks that SonarQube isn't happy about. Not new stuff but still good to fix. Since the bug been there for 5 years and no one complained, probably no need with change log.
=> BUG: Fix is_nrs_msaspec_flatlamp and remove redundant if-else in gs_position_acq

jwst/regtest/test_niriss_soss.py
Resolves [JP-3982](https://jira.stsci.edu/browse/JP-3982)
The auxiliary output from ATOCA appears to be radically different in different build environments - the fit diverges wildly in unpredictable places for Mac vs Linux, different numpy versions, etc.  I think it's not reasonable to do a fitsdiff at all on this product.  This PR changes the regtest to just check for existence of the output file instead of checking the contents.
Merging this should fix the last of the regtest failures with devdeps.
=> JP-3982: Ignore fitsdiffs for atoca spectra

changes/9378.straylight.rst, docs/jwst/straylight/arguments.rst, jwst/regtest/test_miri_mrs_straylight.py, jwst/straylight/straylight.py, jwst/straylight/straylight_step.py, jwst/straylight/tests/test_straylight.py, jwst/straylight/tests/test_straylight_step.py
Resolves [JP-3905](https://jira.stsci.edu/browse/JP-3905)
Closes #9240 
This PR adds an option to the straylight step to save the shower model when also running the clean_shower option. 
A new regression test running straylight with clean_showers and save_shower_model = True.
New regression Truth files were added to the regression test suite. 
Regression tests passed:
https://github.com/spacetelescope/RegressionTests/actions/runs/14474571962
=> JP-3905 add option to save shower model in straylight step for MIRI MRS data

.pre-commit-config.yaml, .ruff.toml, jwst/spectral_leak/__init__.py, jwst/spectral_leak/spectral_leak.py, jwst/spectral_leak/spectral_leak_step.py
Helps to resolve [JP-3857](https://jira.stsci.edu/browse/JP-3857)
This PR updates the spectral leak step for code style changes. 
- regression test pass:https://github.com/spacetelescope/RegressionTests/actions/runs/14391771207
=> JP-3855 Update code style for spectral_leak step

changes/9403.resample.rst, docs/jwst/resample/arguments.rst, jwst/assign_wcs/util.py, jwst/resample/resample_spec.py, jwst/resample/resample_step.py
Related to [RCAL-1054](https://jira.stsci.edu/browse/RCAL-1054)
This PR corrects the definition of pixel scale ratio as used in resampling of imaging data (NOTE: for JWST, spectral resampling may use opposite definition to the one used in imaging)
=> Update docs to reflect correct definition for pixel scale ratio

.pre-commit-config.yaml, .ruff.toml, jwst/saturation/__init__.py, jwst/saturation/saturation.py, jwst/saturation/saturation_step.py, jwst/saturation/x_irs2.py
Partially resolves [JP-3857](https://jira.stsci.edu/browse/JP-3857)
This PR updates the saturation step to conform to code style rules. 
Regression test passed: https://github.com/spacetelescope/RegressionTests/actions/runs/14601643348
(https://github.com/spacetelescope/RegressionTests/blob/main/docs/running_regression_tests.md))
=> JP-3857 Saturation code style changes

jwst/cube_build/cube_build.py
Resolves [JP-3989](https://jira.stsci.edu/browse/JP-3989)
Closes #9415 
This PR addresses removes how a dictionary is setup. A reassignment of a values in the pipeline caused an error in some pipeline tests. 
Regression tests passing: https://github.com/spacetelescope/RegressionTests/actions/runs/14715951406
=> JP-3989 cube build bug 

changes/9412.msaflagopen.rst, jwst/clean_flicker_noise/tests/test_clean_flicker_noise.py, jwst/msaflagopen/msaflag_open.py, jwst/msaflagopen/tests/test_msa_open.py, pyproject.toml
Resolves [JP-3932](https://jira.stsci.edu/browse/JP-3932)
This PR addresses https://github.com/spacetelescope/jwst/issues/3116
I don't think this needs a change log?
=> Fix logging message in NIRSpec assign_wcs and turn all invalid interval warning into error

jwst/associations/tests/make_headers.py
Resolves [JP-3862](https://jira.stsci.edu/browse/JP-3862)
This PR addresses incorrect pathlib usage found by sonarscan.
=> JP-3862: Fix Path methods issue found by sonarscan

.ruff.toml, jwst/lib/catalog_utils.py, jwst/lib/engdb_lib.py, jwst/lib/suffix.py
This PR is a follow-up of https://github.com/spacetelescope/jwst/pull/9283 . I skipped some rules back then and said I would follow up later with smaller diff that is easier to review. Does this need a JIRA ticket? Not sure.
=> Follow up of JP-3917: Apply code style rules to lib

jwst/regtest/test_miri_coron3.py, jwst/regtest/test_miri_coron_image2.py, jwst/regtest/test_miri_image.py, jwst/regtest/test_miri_lrs_slit_spec2.py, jwst/regtest/test_miri_lrs_slit_spec3.py, jwst/regtest/test_miri_lrs_slitless.py, jwst/regtest/test_miri_mrs_spec2.py, jwst/regtest/test_miri_mrs_spec3.py, jwst/regtest/test_miri_mrs_tso.py, jwst/regtest/test_nircam_dhs.py, jwst/regtest/test_nircam_image.py, jwst/regtest/test_nircam_tsgrism.py, jwst/regtest/test_nircam_tsimg.py, jwst/regtest/test_nircam_wfss_contam.py, jwst/regtest/test_nircam_wfss_spec2.py, jwst/regtest/test_niriss_ami3.py, jwst/regtest/test_niriss_image.py, jwst/regtest/test_niriss_soss.py, jwst/regtest/test_niriss_wfss.py, jwst/regtest/test_nirspec_brightobj.py, jwst/regtest/test_nirspec_fs_spec2.py, jwst/regtest/test_nirspec_fs_spec3.py, jwst/regtest/test_nirspec_ifu_spec2.py, jwst/regtest/test_nirspec_ifu_spec3.py, jwst/regtest/test_nirspec_irs2_detector1.py, jwst/regtest/test_nirspec_mos_fs_spec2.py, jwst/regtest/test_nirspec_mos_fs_spec3.py, jwst/regtest/test_nirspec_mos_spec2.py
Resolves [JP-3775](https://jira.stsci.edu/browse/JP-3775)
This PR expands coverage of resource tracking to more regression tests.
=> JP-3775: Expand usage of resource_tracker for benchmarking

changes/9442.ami.rst, jwst/ami/lg_model.py, jwst/ami/nrm_core.py, jwst/ami/oifits.py
Resolves [JP-3776](https://jira.stsci.edu/browse/JP-3776)
Closes #8860 
This PR refactors the `AmiAnalyze` step to avoid creating a long list of 3-D arrays, reducing memory usage by a factor of ~13 for my test dataset (`jw01349-c1007_20250319t131303_ami3_00002_asn.json`).  See ticket for memory usage flamegraphs - the one for this PR branch is named `memray-flamegraph-output_refactor.html`.
A beneficial side-effect of this refactor is that it removes a code pattern in which `RawOifits` objects required `FringeFitter` object as input, but some methods of `FringeFitter` required a `RawOifits` that was being initialized with that very same `FringeFitter` object, i.e. `RawOifits(self)`.  Now both classes require only an instrument data object, which I feel makes more logical sense and more …
=> JP-3776: Improve AmiAnalyze memory usage

pyproject.toml
In looking into association tests, I see that xfail was used liberally. The way I want to refactor them, I want xpass to fail because that means we can move a test case out of xfail expectation. To make that possible, I need to utilize `@pytest.mark.xfail` instead of brute-forcing `pytest.xfail` *and* I need `xfail_strict=true`.
This might smoke out other unrelated xpass cases, so I will keep it as draft for now until testing completes.
=> TST: xpass is now a failure

jwst/regtest/test_nirspec_fs_spec2.py, jwst/regtest/test_nirspec_ifu_spec2.py, jwst/regtest/test_nirspec_mos_spec2.py
Currently most NIRSpec spec2 tests explicitly turn nsclean on, but it is off by default, it is a deprecated step, and it is a numerically sensitive algorithm.  It would be helpful to separate out nsclean test results from standard runs.
=> Separate nsclean tests from standard runs

.pre-commit-config.yaml, .ruff.toml, jwst/dark_current/__init__.py, jwst/dark_current/dark_current_step.py
This PR addresses style issues in the dark_current step.
=> Fix style in dark_current

jwst/ami/analyticnrm2.py, jwst/ami/hextransformee.py, jwst/ami/tests/test_analyticnrm2.py, jwst/ami/tests/test_matrix_dft.py
Follow-up of [JP-3810](https://jira.stsci.edu/browse/JP-3810)
Closes #9437 
This PR addresses a few small follow-up items from the larger AMI clean-up PR:
- Remove TODO statement in `hextransformee`, replacing it with a comment explaining that the behavior in question is intended
- Fix a bug in a unit test to `matrix_dft`
- Fix #9437 by just removing the "fringeonly" option, which was already unusable on main prior to the PR for JP-3810.
- Fix "circ" and "circonly" options to `analyticnrm2.psf` erroring out
=> JP-3810 followup: small clean-up tasks in AMI module

changes/9468.dark_current.rst, docs/jwst/dark_current/description.rst, docs/jwst/references_general/dark_reffile.inc, jwst/dark_current/dark_current_step.py, jwst/dark_current/tests/test_dark_sub.py
Partially resolves [JP-3906](https://jira.stsci.edu/browse/JP-3906)
This PR makes changes required to support JP-3906 updates in the stcal and stdatamodels repos: https://github.com/spacetelescope/stcal/pull/368 and https://github.com/spacetelescope/stdatamodels/pull/480
=> JP-3906: Support extrapolation of dark files to match arbitrary science input size

pyproject.toml
This PR fixes the following tox `cov` error:
https://github.com/spacetelescope/jwst/actions/runs/15420719372/job/43397210638?pr=9509#step:10:268
```
INTERNALERROR> pluggy.PluggyTeardownRaisedWarning: A plugin raised an exception during an old-style hookwrapper teardown.
INTERNALERROR> Plugin: _cov, Hook: pytest_runtestloop
INTERNALERROR> CoverageWarning: Couldn't parse '/home/runner/work/jwst/jwst/config-3.py': No source for code: '/home/runner/work/jwst/jwst/config-3.py'. (couldnt-parse)
INTERNALERROR> For more information see https://pluggy.readthedocs.io/en/stable/api_reference.html#pluggy.PluggyTeardownRaisedWarning
```
... by excluding configuration files `cv2` is unable to see when its code is scanned by the `coverage` utility.
=> coverage: omit config[-3].py files

jwst/regtest/st_fitsdiff.py
Closes #9499
This PR addresses a bug in the comparison of common header keywords.
=> stfitsdiff bug in comparison of header keywords and comments

changes/9510.emicorr.rst, docs/jwst/emicorr/arguments.rst, jwst/emicorr/emicorr_step.py
This PR changes the emicorr default algorithm to the 'joint' method based on performance tests by the MIRI team.
=> JP-3940: Change EMIcorr default algorithm

changes/9501.associations.rst, jwst/associations/generator/generate_per_candidate.py
backport #9501
regtest: https://github.com/spacetelescope/RegressionTests/actions/runs/15540530462/job/43750158547
=> Backport PR #9501 on branch release/1.18.x (JP-3116: Use duplication checking to prevent undesirable associations in DMS operations)

changes/9507.background.rst, jwst/background/background_sub_wfss.py, jwst/background/tests/test_background_wfss.py
backporting https://github.com/spacetelescope/jwst/pull/9507
regtest: https://github.com/spacetelescope/RegressionTests/actions/runs/15540520998/job/43750089133
=> Backport PR #9507: JP-4021: Fix a bug where insufficient valid background pixels case was not caught for WFSS background step

.github/workflows/ci.yml, jwst/combine_1d/tests/test_combine1d.py, jwst/datamodels/utils/tests/test_wfss_multispec.py, jwst/datamodels/utils/tests/wfss_helpers.py, jwst/extract_1d/tests/conftest.py, jwst/pipeline/tests/test_calwebb_spec3.py
Closes #9543 
This PR stops importing fixtures across subfolders, fixing an issue that was originally introduced by https://github.com/spacetelescope/jwst/pull/9402.  This code pattern was causing the stdatamodels downstream tests to fail.
=> Fix importing fixtures across subfolders

changes/9565.docs.rst, docs/jwst/stpipe/user_logging.rst
This PR cleans up the docs section pertaining to logging configuration removing descriptions of per-step configuration (which does not work: https://github.com/spacetelescope/stpipe/issues/241).
Link to updated page: https://jwst-pipeline--9565.org.readthedocs.build/en/9565/jwst/stpipe/user_logging.html
As this is only a docs change no regtests will be run.
=> remove description of non-working logging configuration

.github/workflows/ci.yml, pyproject.toml, tox.ini
Partially resolves [JP-4033](https://jira.stsci.edu/browse/JP-4033)
This PR was requested as a temporary solution to avoid logging issues seen in environments using python>=3.13.4; this in preparation of our next candidate release.
Note that this will not result in a clean solution if users build environments with the default python version; conda will install the latest python version and direct users to the last compatible jwst version, 1.18.1. Our README instructs users to install in python 3.12; https://pypistats.org/packages/jwst shows ~5% of installs appear to be on 3.13.
=> Temporary python upper pin to avoid logging failures

pyproject.toml
Add an upper pin to drizzle to disallow 2.1.0:
https://github.com/spacetelescope/drizzle/releases/tag/2.1.0
which is causing unit and regtest failures.
The thought here is to add the pin (to allow other PRs and regtests to run) then a follow-up PR can:
- remove the pin
- fix the unit test
- run regtests (which can then be okified)
If the above approach is not preferred we can close this PR.
Regtests all pass: https://github.com/spacetelescope/RegressionTests/actions/runs/15879813351
=> add upper pin to drizzle

jwst/stpipe/tests/test_step.py
This PR updates one unit test, the only usage of `just_the_step_from_cmdline` outside of stpipe to instead use the [documented](https://jwst-pipeline.readthedocs.io/en/latest/jwst/stpipe/user_step.html#step-from-cmdline) `Step.from_cmdline` API.
The updated test passes with stpipe main and with stpipe PR: https://github.com/spacetelescope/stpipe/pull/240
The updated test also uses monkeypatching to set environment variables instead of a `try/finally`.
As this is only a unit test change no regtests will be started.
=> Update logging unit test

docs/jwst/user_documentation/datamodels.rst, jwst/datamodels/library.py
Resolves [JP-3968](https://jira.stsci.edu/browse/JP-3968)
Closes #9038 
This PR puts ModelContainer, ModelLibrary, and SourceModelContainer API into the JWST docs.
=> JP-3968: Restore ModelContainer to docs, add ModelLibrary and SourceModelContainer to docs

changes/9590.datamodels.rst, jwst/datamodels/container.py, jwst/datamodels/tests/test_model_container.py
Resolves [JP-1497](https://jira.stsci.edu/browse/JP-1497)
Closes #5023 
This PR updates `ModelContainer` to pass kwargs to `datamodels.open()` for opening the individual datamodels in that container.
=> JP-1497: Pass datamodel open kwargs through ModelContainer

.github/workflows/ci.yml, .github/workflows/tests_devdeps.yml, pyproject.toml
Remove the temporary upper pin added in https://github.com/spacetelescope/jwst/pull/9582 and https://github.com/spacetelescope/jwst/pull/9592 now that the work-around in stpipe is merged https://github.com/spacetelescope/stpipe/pull/240
=> Remove python upper pin

tox.ini
Exorcise zero coverage (try 2). Follow-up of https://github.com/spacetelescope/jwst/pull/9550
* close https://github.com/spacetelescope/jwst/pull/9651
* close https://github.com/spacetelescope/jwst/pull/9649
* close https://github.com/spacetelescope/jwst/pull/9652
=>  TST: Fix tox for pyargs (try 2)

.github/workflows/ci_cron.yml, .github/workflows/tests_devdeps.yml
This PR let devdeps run on labeled event and also on backport PRs if label exists. Currently when PR on main, it only runs if label present when PR is opened but not when label is applied after PR is opened. This would have caught failure back in #9660 and would have prevented #9662
=> TST: Allow devdeps and cron to run on labeled PR and backport PR when labeled

changes/9672.white_light.rst, jwst/white_light/tests/test_white_light.py, jwst/white_light/white_light.py
Resolves [JP-4067](https://jira.stsci.edu/browse/JP-4067)
Catch repeated time stamps in the spectral table. If found, warn and keep only the first one.
Test data is:
jw02183-o117_20250411t072937_tso3_00001_asn.json, containing jw02183117001_03103_00001-seg001_nrcalong_calints.fits
=> JP-4067: Fix white_light crash on repeated time stamps

jwst/datamodels/utils/tests/test_wfss_multispec.py, pyproject.toml
Related to [JP-3931](https://jira.stsci.edu/browse/JP-3931)
This PR follows from https://github.com/spacetelescope/stdatamodels/pull/529 , which modified the unit string for WFSS tables. This updates the truth to get passing tests.
=> Test update following WFSS FITS unit change

.ruff.toml, jwst/ami/tests/test_lg_model.py, jwst/ami/tests/test_nrm_core.py, jwst/ami/tests/test_utils.py, jwst/assign_wcs/tests/test_nirspec.py, jwst/clean_flicker_noise/tests/test_clean_flicker_noise.py, jwst/cube_build/tests/test_configuration.py, jwst/emicorr/tests/test_emicorr.py, jwst/extract_1d/tests/test_extract_1d_step.py, jwst/ipc/tests/test_ipc_corr.py, jwst/ipc/tests/test_x_irs2.py, jwst/pathloss/tests/test_pathloss_step.py, jwst/pipeline/tests/test_calwebb_spec3.py, jwst/regtest/test_associations_sdp_pools.py, jwst/regtest/test_miri_image.py, jwst/regtest/test_nirspec_brightobj.py, jwst/regtest/test_nirspec_fs_spec2.py, jwst/regtest/test_nirspec_ifu_internal_cal.py, jwst/regtest/test_nirspec_ifu_spec2.py, jwst/regtest/test_nirspec_ifu_spec3.py, jwst/regtest/test_nirspec_ifu_spec3_emsm.py, jwst/regtest/test_nirspec_ifu_spec3_moving_target.py, jwst/regtest/test_nirspec_ifu_spec3_pixelreplace.py, jwst/regtest/test_nirspec_masterbackground.py, jwst/regtest/test_nirspec_steps_spec2.py, jwst/regtest/test_nirspec_wcs.py, jwst/stpipe/tests/test_step.py, jwst/tso_photometry/tests/test_tso_photometry.py, jwst/wavecorr/tests/test_wavecorr.py
This PR addresses most F rules in test modules.
Motivation: I have flake8 hooked into my Emacs and it bothers me that it complains about unused imports in test modules I work on, but the pre-commit here just happily ignores such travesty.
=> STY: Apply flake8 to test modules and fix most violations

pyproject.toml, tox.ini
This PR addresses a couple of things I noticed while working on other stuff. Particularly regression test suite does not use tox (it uses uv + pytest), so the regtests stuff in `tox.ini` is not used and probably also broken. A warnings directive is defined but never used as well. Also outdated comment in pyproject.toml that no longer applies after #9490
=> TST: Remove unused tox flags and outdated comment

jwst/source_catalog/tests/test_source_catalog.py
Relates to https://github.com/spacetelescope/jwst/pull/9671
This PR adds a unit test to the source catalog step, which was originally written in support of the above-linked PR. That PR is getting closed without merge but the unit test is still useful to have.
=> Unit test source catalog against specific values

jwst/source_catalog/tests/test_source_catalog.py, jwst/tweakreg/tweakreg_catalog.py
Bugfix for issue discovered while testing [JP-3943](https://jira.stsci.edu/browse/JP-3943)
This PR fixes a crash caused by the "orientation" column of the source catalog lacking Astropy units when the sourcefinder was set to "iraf".
=> JP-3943: Fix unit handling for orientation column when iraf is selected finder

jwst/regtest/test_stfitsdiff.py, jwst/stpipe/tests/steps/__init__.py, jwst/stpipe/tests/test_step.py
Replace a few uncommon uses of `datamodels.open` with the more commonly used API.
Regtests pass: https://github.com/spacetelescope/RegressionTests/actions/runs/16529705448
=> remove uncommon datamodels.open usage

changes/9607.associations.rst, changes/README.rst, jwst/associations/lib/prune.py, jwst/associations/lib/tests/test_prune.py, jwst/regtest/test_associations_sdp_pools.py
Resolves [JP-3516](https://jira.stsci.edu/browse/JP-3516)
Fix an edge case in duplicate association checks, where a duplicate "rateints" association should be removed, but an equivalent "rate" association is present, and was accidentally removed instead.
=> JP-3516: Fix duplicate association removal

.github/workflows/ci.yml, .github/workflows/ci_cron.yml
The linkcheck job when run on unrelated PRs returns many `429` errors:
https://github.com/spacetelescope/jwst/actions/runs/16939512936/job/48004555905?pr=9744#step:10:1718
```429 Client Error: Too Many Requests for url: https://asdf-standard.readthedocs.io/en/latest/```
This PR moves it to the scheduled jobs to try and reduce the chance of failure due to connection throttling by the pinged servers.
I added the `run scheduled tests` to this PR to trigger the scheduled jobs to test the workflow modifications.
=> move linkcheck to cron

pyproject.toml
This PR updates the drizzle pins to accommodate the new version. It comes with some slight improvements to edge cases and a slight speedup.
RTs: https://github.com/spacetelescope/RegressionTests/actions/runs/16990585608
=> Update drizzle pin with new release version

changes/9803.general.rst, pyproject.toml
opencv is not used directly in jwst.
The jump step does use opencv but only via stcal (which [has opencv as a dependency](https://github.com/spacetelescope/stcal/blob/702c2856fff0673fb32e654506690ca20ebca643/pyproject.toml#L18)).
This PR removes opencv as a direct dependency to jwst.
Regtests: https://github.com/spacetelescope/RegressionTests/actions/runs/17494168542
all pass and show opencv installed "via stcal":
https://github.com/spacetelescope/RegressionTests/actions/runs/17494168542/job/49690870643#step:17:80
=> drop opencv direct dependency

changes/9840.general.rst, pyproject.toml
Pin python <3.14
There will not be enough time to test with 3.14 before the next release.
This fixes the currently failing build workflows (which are attempting to and failing to build a wheel for 3.14).
=> pin python<3.14

changes/9783.assign_wcs.rst, jwst/assign_wcs/nirspec.py, jwst/assign_wcs/tests/test_nirspec.py
Resolves [JP-4095](https://jira.stsci.edu/browse/JP-4095)
Fix a missing velocity correction in the inverse transform for NIRSpec IFU.  This seems to fix a round trip error of up to ~0.5 pixel.  Example case: jw01251004001_03107_00001_nrs2_rate.fits, with velosys = 20 km/s. 
I checked the other modes for similar errors, and found that NIRSpec MOS and FS needs the same handling.  I'm not sure if we've noted similar round trip errors for these modes, but checking MOS regression test data jw01345066001_05101_00001_nrs1_rate.fits with velosys -15 km/s, it looks like it improves round trip error from ~.08 pixel to ~.001 pixel in a quick spot check on slit 35.
For the other instruments, where the velocity_correction is used, they appear to be propagating it to the inverse correctly. ~I did note …
=> JP-4095: Fix velocity correction in WCS inverse

jwst/ami/tests/test_ami_average.py, jwst/outlier_detection/tests/conftest.py, jwst/pipeline/tests/test_calwebb_image2.py, jwst/pipeline/tests/test_calwebb_spec2.py, jwst/regtest/test_miri_mrs_spec3.py, jwst/resample/tests/test_resample_step.py, jwst/stpipe/core.py, jwst/tests/helpers.py, jwst/tests/test_helpers.py
The "py.warnings" named logger is used by python when warnings are captured and routed to log messages.
https://docs.python.org/3.13/library/logging.html#logging.captureWarnings
as is done [in stpipe](https://github.com/spacetelescope/stpipe/blob/fe38ab0c68594e73449211f0b41a3df9de8886fc/src/stpipe/log.py#L342).
Including "py.warnings" allows log messages like [this one from stcal](https://github.com/spacetelescope/stcal/blob/1b28b89c206ef1a78a43c46f1558a5fd8929d467/src/stcal/resample/utils.py#L449) to be captured. Without listing "py.warnings" the warning message is lost and not displayed to the user.
However, the inclusion of "py.warnings" also means warnings from other packages (gwcs, asdf, astropy, etc...) will show up in strun executions. These were/are shown for all currently …
=> add py.warnings to stpipe loggers

jwst/regtest/conftest.py
No longer needed after #9855, I think.
=> TST: Remove unused folder_copy in regtest

changes/9908.residual_fringe.rst, jwst/residual_fringe/residual_fringe.py, jwst/residual_fringe/utils.py
Declare out when where is used in np.subtract to avoid warning from numpy-dev
Motivation: Failure spam from https://github.com/spacetelescope/RegressionTests/actions/workflows/jwst_devdeps.yml is starting to trigger me. Not sure what's up with the FITS diff but one fire at a time.
Should not need a change log since the changes are invisible to user.
=> Declare out when where is used in np.subtract

changes/9920.tso_photometry.rst, jwst/tso_photometry/tests/test_tso_photometry.py, jwst/tso_photometry/tso_photometry.py
Resolves [JP-4155](https://jira.stsci.edu/browse/JP-4155)
Fix an issue found in testing, where a failed centroid sometimes returns a value out of bounds instead of NaN
=> JP-4155: Add a bounds check for centroid failure in tso_photometry

docs/jwst/associations/association_api.rst, docs/jwst/associations/lib_dmsbase.rst, docs/jwst/associations/registry.rst, docs/jwst/associations/rules_level2.rst, docs/jwst/associations/rules_level3.rst, jwst/associations/asn_from_list.py, jwst/associations/association.py, jwst/associations/lib/acid.py, jwst/associations/lib/constraint.py, jwst/associations/lib/dms_base.py, jwst/associations/lib/keyvalue_registry.py, jwst/associations/lib/process_list.py, jwst/associations/lib/rules_level2_base.py, jwst/associations/lib/rules_level2b.py, jwst/associations/lib/rules_level3.py, jwst/associations/lib/rules_level3_base.py, jwst/associations/load_asn.py, jwst/associations/main.py, jwst/associations/pool.py
This PR addresses a little bit of https://github.com/spacetelescope/jwst/issues/9383 , as seen in https://github.com/spacetelescope/jwst/pull/9666 . This round focuses on `associations` docs. Some broken refs need new API docstrings to be exposed.
The changes are negotiable.
I can run RT when we agree on the changes.
=> DOC: Fix assocations refs, expose more API docstrings
